services:
  postgres:
    image: postgres:16-alpine
    container_name: nihongo-postgres
    restart: unless-stopped
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE:-nihongo}
      POSTGRES_USER: ${PG_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - nihongo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nihongo-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes
    volumes:
      - cache:/data
    networks:
      - nihongo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  nihongo-network:
    driver: bridge

volumes:
  db:
  cache:
