export const OK = 'OK'
export const CREATED = 'Created'
export const ACCEPTED = 'Accepted'
export const NO_CONTENT = 'No Content'

export const BAD_REQUEST = 'Bad Request'
export const UNAUTHORIZED = 'Unauthorized'
export const FORBIDDEN = 'Forbidden'
export const NOT_FOUND = 'Not Found'
export const METHOD_NOT_ALLOWED = 'Method Not Allowed'
export const CONFLICT = 'Conflict'
export const UNPROCESSABLE_ENTITY = 'Unprocessable Entity'
export const TOO_MANY_REQUESTS = 'Too Many Requests'

export const INTERNAL_SERVER_ERROR = 'Internal Server Error'
export const BAD_GATEWAY = 'Bad Gateway'
export const SERVICE_UNAVAILABLE = 'Service Unavailable'
