-- The lesson layer: example sentences, read-tracking, and the prompt gate.
--
-- Generated by drizzle-kit, then made idempotent by hand. Additive throughout —
-- two new tables and one nullable column. Nothing is dropped, no existing row is
-- touched, and re-running changes nothing, so this is safe on a live database.

CREATE TABLE IF NOT EXISTS "grammar_point_sentences" (
	"grammar_point_id" text NOT NULL,
	"sentence_id" text NOT NULL,
	"role" text DEFAULT 'example' NOT NULL,
	"sort_index" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "grammar_point_sentences_grammar_point_id_sentence_id_role_pk" PRIMARY KEY("grammar_point_id","sentence_id","role")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lesson_views" (
	"user_id" text NOT NULL,
	"study_item_id" text NOT NULL,
	"first_seen_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lesson_views_user_id_study_item_id_pk" PRIMARY KEY("user_id","study_item_id")
);
--> statement-breakpoint
ALTER TABLE "exercise_prompts" ADD COLUMN IF NOT EXISTS "requires_grammar_point_id" text;--> statement-breakpoint
-- Postgres has no ADD CONSTRAINT IF NOT EXISTS; swallowing duplicate_object is
-- the standard equivalent and is what drizzle itself used to emit.
DO $$ BEGIN
 ALTER TABLE "grammar_point_sentences" ADD CONSTRAINT "grammar_point_sentences_grammar_point_id_grammar_points_id_fk" FOREIGN KEY ("grammar_point_id") REFERENCES "public"."grammar_points"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "grammar_point_sentences" ADD CONSTRAINT "grammar_point_sentences_sentence_id_sentences_id_fk" FOREIGN KEY ("sentence_id") REFERENCES "public"."sentences"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "lesson_views" ADD CONSTRAINT "lesson_views_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "lesson_views" ADD CONSTRAINT "lesson_views_study_item_id_study_items_id_fk" FOREIGN KEY ("study_item_id") REFERENCES "public"."study_items"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "exercise_prompts" ADD CONSTRAINT "exercise_prompts_requires_grammar_point_id_grammar_points_id_fk" FOREIGN KEY ("requires_grammar_point_id") REFERENCES "public"."grammar_points"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "grammar_point_sentences_point_idx" ON "grammar_point_sentences" USING btree ("grammar_point_id","sort_index");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "grammar_point_sentences_sentence_idx" ON "grammar_point_sentences" USING btree ("sentence_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lesson_views_user_idx" ON "lesson_views" USING btree ("user_id");
