-- Where the stage celebration is remembered, per user per level.
--
-- Generated by drizzle-kit, then made idempotent by hand. Purely additive: one
-- new table, nothing dropped, no existing row touched. Safe on a live database
-- and safe to re-run.

CREATE TABLE IF NOT EXISTS "stage_celebrations" (
	"user_id" text NOT NULL,
	"level_id" text NOT NULL,
	"highest_stage_seen" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "stage_celebrations_user_id_level_id_pk" PRIMARY KEY("user_id","level_id")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stage_celebrations" ADD CONSTRAINT "stage_celebrations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stage_celebrations" ADD CONSTRAINT "stage_celebrations_level_id_language_levels_id_fk" FOREIGN KEY ("level_id") REFERENCES "public"."language_levels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
