-- Give `accounts` the `issuer` column better-auth has required since 1.7.
--
-- Its absence did not fail loudly. The Drizzle adapter looked the field up on
-- the schema, found nothing, and emitted an EMPTY identifier — so every
-- credential lookup ran
--
--   ... where user_id = $1 and provider_id = $2 and  = $3 and account_id = $4
--
-- which Postgres rejects as a syntax error at "=" (42601). The reader saw only
-- "That code was not accepted" when trying to set a password, because the
-- lookup that decides whether to create a credential account never returned.
--
-- Generated by drizzle-kit, then rewritten by hand: the generated form was a
-- single `ADD COLUMN ... NOT NULL`, which aborts on any table that already has
-- rows. Split into add / backfill / constrain so it is safe on a populated
-- production table, and guarded throughout so it is safe to re-run.
--
-- The backfill mirrors better-auth's own constructors: `local:<provider>` for
-- internal methods (`createLocalAccountIssuer`) and `local:oauth:<provider>`
-- for OAuth providers with no issuer of their own (`createOAuthAccountIssuer`).
-- Only 'credential' exists today; the CASE is there so an OAuth row added
-- before this ships is not given the wrong namespace.

ALTER TABLE "accounts" ADD COLUMN IF NOT EXISTS "issuer" text;--> statement-breakpoint

UPDATE "accounts"
SET "issuer" = CASE
                 WHEN "provider_id" IN ('credential', 'email-otp') THEN 'local:' || "provider_id"
                 ELSE 'local:oauth:' || "provider_id"
               END
WHERE "issuer" IS NULL;--> statement-breakpoint

-- No exception handler, deliberately.
--
-- This started as `EXCEPTION WHEN others`, which would have swallowed a lock
-- timeout and left the column quietly nullable while reporting success. The
-- narrowed `WHEN not_null_violation` was worse than useless: 23502 is EXACTLY
-- the error a surviving NULL raises, so the one failure worth hearing about was
-- the one being caught, while the handler contributed nothing to idempotency —
-- a redundant SET NOT NULL on an already-NOT-NULL column is a plain no-op in
-- Postgres and does not raise at all.
--
-- So: bare. Re-running is free, and if a NULL ever survives the backfill above,
-- this fails loudly, which is the only useful thing it can do.
ALTER TABLE "accounts" ALTER COLUMN "issuer" SET NOT NULL;--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "accounts_issuer_account_id_unique" ON "accounts" USING btree ("issuer","account_id");
