-- Lessons: what was completed, and which questions were missed.
--
-- Generated by drizzle-kit, then made idempotent by hand. Purely additive — one
-- new table and two nullable columns. Nothing is dropped, no existing row is
-- touched, and re-running changes nothing, so this is safe on a live database.

CREATE TABLE IF NOT EXISTS "lesson_misses" (
	"user_id" text NOT NULL,
	"prompt_id" text NOT NULL,
	"missed_at" timestamp DEFAULT now() NOT NULL,
	"cleared_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lesson_misses_user_id_prompt_id_pk" PRIMARY KEY("user_id","prompt_id")
);
--> statement-breakpoint
ALTER TABLE "lesson_views" ADD COLUMN IF NOT EXISTS "completed_at" timestamp;--> statement-breakpoint
ALTER TABLE "lesson_views" ADD COLUMN IF NOT EXISTS "quiz_score" smallint;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "lesson_misses" ADD CONSTRAINT "lesson_misses_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "lesson_misses" ADD CONSTRAINT "lesson_misses_prompt_id_exercise_prompts_id_fk" FOREIGN KEY ("prompt_id") REFERENCES "public"."exercise_prompts"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lesson_misses_outstanding_idx" ON "lesson_misses" USING btree ("user_id") WHERE "lesson_misses"."cleared_at" is null;
