-- Kana: the full gojūon in both scripts, plus dakuten and handakuten.
-- Generated rather than hand-written — a couple of hundred rows of pure table
-- data with no upstream dataset worth a pipeline. This is what makes the review
-- loop real before any of the JMdict/KANJIDIC importers exist.
--
-- Hiragana is ordered before katakana (sort_index 0.. vs 1000..) because that is
-- the order people learn them, and sort_index drives the introduction queue.

-- A typed drill graded as romaji. Its own code, because the generic
-- `reading-input` template grades exact kana — the wrong question for
-- "what sound is か".
INSERT INTO exercise_templates
  (id, code, language_id, name, applies_to_kinds, applies_to_facets, input_mode, grader_code, requires, first_exposure_only, config, weight, active)
VALUES
  ('tpl-kana-romaji', 'kana-romaji', 'lang-ja', 'Type the sound',
   ARRAY['kana'], ARRAY['reading'], 'text', 'fuzzy-romaji', '{}', false, '{"answerScript":"romaji"}', 12, true)
ON CONFLICT (code, language_id) DO NOTHING;

INSERT INTO kind_facet_templates (id, language_id, kind, facet, template_id, weight, first_exposure_only)
VALUES ('kft-kana-reading-romaji', 'lang-ja', 'kana', 'reading', 'tpl-kana-romaji', 12, false)
ON CONFLICT (language_id, kind, facet, template_id) DO NOTHING;

INSERT INTO kana (id, language_id, script, character, romaji, "row", "column", variant, order_index) VALUES
  ('kana-h0', 'lang-ja', 'hiragana', 'あ', 'a', '', 'a', 'base', 0),
  ('kana-h1', 'lang-ja', 'hiragana', 'い', 'i', '', 'i', 'base', 1),
  ('kana-h2', 'lang-ja', 'hiragana', 'う', 'u', '', 'u', 'base', 2),
  ('kana-h3', 'lang-ja', 'hiragana', 'え', 'e', '', 'e', 'base', 3),
  ('kana-h4', 'lang-ja', 'hiragana', 'お', 'o', '', 'o', 'base', 4),
  ('kana-h5', 'lang-ja', 'hiragana', 'か', 'ka', 'k', 'a', 'base', 5),
  ('kana-h6', 'lang-ja', 'hiragana', 'き', 'ki', 'k', 'i', 'base', 6),
  ('kana-h7', 'lang-ja', 'hiragana', 'く', 'ku', 'k', 'u', 'base', 7),
  ('kana-h8', 'lang-ja', 'hiragana', 'け', 'ke', 'k', 'e', 'base', 8),
  ('kana-h9', 'lang-ja', 'hiragana', 'こ', 'ko', 'k', 'o', 'base', 9),
  ('kana-h10', 'lang-ja', 'hiragana', 'さ', 'sa', 's', 'a', 'base', 10),
  ('kana-h11', 'lang-ja', 'hiragana', 'し', 'shi', 's', 'i', 'base', 11),
  ('kana-h12', 'lang-ja', 'hiragana', 'す', 'su', 's', 'u', 'base', 12),
  ('kana-h13', 'lang-ja', 'hiragana', 'せ', 'se', 's', 'e', 'base', 13),
  ('kana-h14', 'lang-ja', 'hiragana', 'そ', 'so', 's', 'o', 'base', 14),
  ('kana-h15', 'lang-ja', 'hiragana', 'た', 'ta', 't', 'a', 'base', 15),
  ('kana-h16', 'lang-ja', 'hiragana', 'ち', 'chi', 't', 'i', 'base', 16),
  ('kana-h17', 'lang-ja', 'hiragana', 'つ', 'tsu', 't', 'u', 'base', 17),
  ('kana-h18', 'lang-ja', 'hiragana', 'て', 'te', 't', 'e', 'base', 18),
  ('kana-h19', 'lang-ja', 'hiragana', 'と', 'to', 't', 'o', 'base', 19),
  ('kana-h20', 'lang-ja', 'hiragana', 'な', 'na', 'n', 'a', 'base', 20),
  ('kana-h21', 'lang-ja', 'hiragana', 'に', 'ni', 'n', 'i', 'base', 21),
  ('kana-h22', 'lang-ja', 'hiragana', 'ぬ', 'nu', 'n', 'u', 'base', 22),
  ('kana-h23', 'lang-ja', 'hiragana', 'ね', 'ne', 'n', 'e', 'base', 23),
  ('kana-h24', 'lang-ja', 'hiragana', 'の', 'no', 'n', 'o', 'base', 24),
  ('kana-h25', 'lang-ja', 'hiragana', 'は', 'ha', 'h', 'a', 'base', 25),
  ('kana-h26', 'lang-ja', 'hiragana', 'ひ', 'hi', 'h', 'i', 'base', 26),
  ('kana-h27', 'lang-ja', 'hiragana', 'ふ', 'fu', 'h', 'u', 'base', 27),
  ('kana-h28', 'lang-ja', 'hiragana', 'へ', 'he', 'h', 'e', 'base', 28),
  ('kana-h29', 'lang-ja', 'hiragana', 'ほ', 'ho', 'h', 'o', 'base', 29),
  ('kana-h30', 'lang-ja', 'hiragana', 'ま', 'ma', 'm', 'a', 'base', 30),
  ('kana-h31', 'lang-ja', 'hiragana', 'み', 'mi', 'm', 'i', 'base', 31),
  ('kana-h32', 'lang-ja', 'hiragana', 'む', 'mu', 'm', 'u', 'base', 32),
  ('kana-h33', 'lang-ja', 'hiragana', 'め', 'me', 'm', 'e', 'base', 33),
  ('kana-h34', 'lang-ja', 'hiragana', 'も', 'mo', 'm', 'o', 'base', 34),
  ('kana-h35', 'lang-ja', 'hiragana', 'や', 'ya', 'y', 'a', 'base', 35),
  ('kana-h36', 'lang-ja', 'hiragana', 'ゆ', 'yu', 'y', 'u', 'base', 36),
  ('kana-h37', 'lang-ja', 'hiragana', 'よ', 'yo', 'y', 'o', 'base', 37),
  ('kana-h38', 'lang-ja', 'hiragana', 'ら', 'ra', 'r', 'a', 'base', 38),
  ('kana-h39', 'lang-ja', 'hiragana', 'り', 'ri', 'r', 'i', 'base', 39),
  ('kana-h40', 'lang-ja', 'hiragana', 'る', 'ru', 'r', 'u', 'base', 40),
  ('kana-h41', 'lang-ja', 'hiragana', 'れ', 're', 'r', 'e', 'base', 41),
  ('kana-h42', 'lang-ja', 'hiragana', 'ろ', 'ro', 'r', 'o', 'base', 42),
  ('kana-h43', 'lang-ja', 'hiragana', 'わ', 'wa', 'w', 'a', 'base', 43),
  ('kana-h44', 'lang-ja', 'hiragana', 'を', 'wo', 'w', 'o', 'base', 44),
  ('kana-h45', 'lang-ja', 'hiragana', 'ん', 'n', 'N', 'n', 'base', 45),
  ('kana-h46', 'lang-ja', 'hiragana', 'が', 'ga', 'g', 'a', 'dakuten', 46),
  ('kana-h47', 'lang-ja', 'hiragana', 'ぎ', 'gi', 'g', 'i', 'dakuten', 47),
  ('kana-h48', 'lang-ja', 'hiragana', 'ぐ', 'gu', 'g', 'u', 'dakuten', 48),
  ('kana-h49', 'lang-ja', 'hiragana', 'げ', 'ge', 'g', 'e', 'dakuten', 49),
  ('kana-h50', 'lang-ja', 'hiragana', 'ご', 'go', 'g', 'o', 'dakuten', 50),
  ('kana-h51', 'lang-ja', 'hiragana', 'ざ', 'za', 'z', 'a', 'dakuten', 51),
  ('kana-h52', 'lang-ja', 'hiragana', 'じ', 'ji', 'z', 'i', 'dakuten', 52),
  ('kana-h53', 'lang-ja', 'hiragana', 'ず', 'zu', 'z', 'u', 'dakuten', 53),
  ('kana-h54', 'lang-ja', 'hiragana', 'ぜ', 'ze', 'z', 'e', 'dakuten', 54),
  ('kana-h55', 'lang-ja', 'hiragana', 'ぞ', 'zo', 'z', 'o', 'dakuten', 55),
  ('kana-h56', 'lang-ja', 'hiragana', 'だ', 'da', 'd', 'a', 'dakuten', 56),
  ('kana-h57', 'lang-ja', 'hiragana', 'ぢ', 'ji', 'd', 'i', 'dakuten', 57),
  ('kana-h58', 'lang-ja', 'hiragana', 'づ', 'zu', 'd', 'u', 'dakuten', 58),
  ('kana-h59', 'lang-ja', 'hiragana', 'で', 'de', 'd', 'e', 'dakuten', 59),
  ('kana-h60', 'lang-ja', 'hiragana', 'ど', 'do', 'd', 'o', 'dakuten', 60),
  ('kana-h61', 'lang-ja', 'hiragana', 'ば', 'ba', 'b', 'a', 'dakuten', 61),
  ('kana-h62', 'lang-ja', 'hiragana', 'び', 'bi', 'b', 'i', 'dakuten', 62),
  ('kana-h63', 'lang-ja', 'hiragana', 'ぶ', 'bu', 'b', 'u', 'dakuten', 63),
  ('kana-h64', 'lang-ja', 'hiragana', 'べ', 'be', 'b', 'e', 'dakuten', 64),
  ('kana-h65', 'lang-ja', 'hiragana', 'ぼ', 'bo', 'b', 'o', 'dakuten', 65),
  ('kana-h66', 'lang-ja', 'hiragana', 'ぱ', 'pa', 'p', 'a', 'handakuten', 66),
  ('kana-h67', 'lang-ja', 'hiragana', 'ぴ', 'pi', 'p', 'i', 'handakuten', 67),
  ('kana-h68', 'lang-ja', 'hiragana', 'ぷ', 'pu', 'p', 'u', 'handakuten', 68),
  ('kana-h69', 'lang-ja', 'hiragana', 'ぺ', 'pe', 'p', 'e', 'handakuten', 69),
  ('kana-h70', 'lang-ja', 'hiragana', 'ぽ', 'po', 'p', 'o', 'handakuten', 70),
  ('kana-k1000', 'lang-ja', 'katakana', 'ア', 'a', '', 'a', 'base', 1000),
  ('kana-k1001', 'lang-ja', 'katakana', 'イ', 'i', '', 'i', 'base', 1001),
  ('kana-k1002', 'lang-ja', 'katakana', 'ウ', 'u', '', 'u', 'base', 1002),
  ('kana-k1003', 'lang-ja', 'katakana', 'エ', 'e', '', 'e', 'base', 1003),
  ('kana-k1004', 'lang-ja', 'katakana', 'オ', 'o', '', 'o', 'base', 1004),
  ('kana-k1005', 'lang-ja', 'katakana', 'カ', 'ka', 'k', 'a', 'base', 1005),
  ('kana-k1006', 'lang-ja', 'katakana', 'キ', 'ki', 'k', 'i', 'base', 1006),
  ('kana-k1007', 'lang-ja', 'katakana', 'ク', 'ku', 'k', 'u', 'base', 1007),
  ('kana-k1008', 'lang-ja', 'katakana', 'ケ', 'ke', 'k', 'e', 'base', 1008),
  ('kana-k1009', 'lang-ja', 'katakana', 'コ', 'ko', 'k', 'o', 'base', 1009),
  ('kana-k1010', 'lang-ja', 'katakana', 'サ', 'sa', 's', 'a', 'base', 1010),
  ('kana-k1011', 'lang-ja', 'katakana', 'シ', 'shi', 's', 'i', 'base', 1011),
  ('kana-k1012', 'lang-ja', 'katakana', 'ス', 'su', 's', 'u', 'base', 1012),
  ('kana-k1013', 'lang-ja', 'katakana', 'セ', 'se', 's', 'e', 'base', 1013),
  ('kana-k1014', 'lang-ja', 'katakana', 'ソ', 'so', 's', 'o', 'base', 1014),
  ('kana-k1015', 'lang-ja', 'katakana', 'タ', 'ta', 't', 'a', 'base', 1015),
  ('kana-k1016', 'lang-ja', 'katakana', 'チ', 'chi', 't', 'i', 'base', 1016),
  ('kana-k1017', 'lang-ja', 'katakana', 'ツ', 'tsu', 't', 'u', 'base', 1017),
  ('kana-k1018', 'lang-ja', 'katakana', 'テ', 'te', 't', 'e', 'base', 1018),
  ('kana-k1019', 'lang-ja', 'katakana', 'ト', 'to', 't', 'o', 'base', 1019),
  ('kana-k1020', 'lang-ja', 'katakana', 'ナ', 'na', 'n', 'a', 'base', 1020),
  ('kana-k1021', 'lang-ja', 'katakana', 'ニ', 'ni', 'n', 'i', 'base', 1021),
  ('kana-k1022', 'lang-ja', 'katakana', 'ヌ', 'nu', 'n', 'u', 'base', 1022),
  ('kana-k1023', 'lang-ja', 'katakana', 'ネ', 'ne', 'n', 'e', 'base', 1023),
  ('kana-k1024', 'lang-ja', 'katakana', 'ノ', 'no', 'n', 'o', 'base', 1024),
  ('kana-k1025', 'lang-ja', 'katakana', 'ハ', 'ha', 'h', 'a', 'base', 1025),
  ('kana-k1026', 'lang-ja', 'katakana', 'ヒ', 'hi', 'h', 'i', 'base', 1026),
  ('kana-k1027', 'lang-ja', 'katakana', 'フ', 'fu', 'h', 'u', 'base', 1027),
  ('kana-k1028', 'lang-ja', 'katakana', 'ヘ', 'he', 'h', 'e', 'base', 1028),
  ('kana-k1029', 'lang-ja', 'katakana', 'ホ', 'ho', 'h', 'o', 'base', 1029),
  ('kana-k1030', 'lang-ja', 'katakana', 'マ', 'ma', 'm', 'a', 'base', 1030),
  ('kana-k1031', 'lang-ja', 'katakana', 'ミ', 'mi', 'm', 'i', 'base', 1031),
  ('kana-k1032', 'lang-ja', 'katakana', 'ム', 'mu', 'm', 'u', 'base', 1032),
  ('kana-k1033', 'lang-ja', 'katakana', 'メ', 'me', 'm', 'e', 'base', 1033),
  ('kana-k1034', 'lang-ja', 'katakana', 'モ', 'mo', 'm', 'o', 'base', 1034),
  ('kana-k1035', 'lang-ja', 'katakana', 'ヤ', 'ya', 'y', 'a', 'base', 1035),
  ('kana-k1036', 'lang-ja', 'katakana', 'ユ', 'yu', 'y', 'u', 'base', 1036),
  ('kana-k1037', 'lang-ja', 'katakana', 'ヨ', 'yo', 'y', 'o', 'base', 1037),
  ('kana-k1038', 'lang-ja', 'katakana', 'ラ', 'ra', 'r', 'a', 'base', 1038),
  ('kana-k1039', 'lang-ja', 'katakana', 'リ', 'ri', 'r', 'i', 'base', 1039),
  ('kana-k1040', 'lang-ja', 'katakana', 'ル', 'ru', 'r', 'u', 'base', 1040),
  ('kana-k1041', 'lang-ja', 'katakana', 'レ', 're', 'r', 'e', 'base', 1041),
  ('kana-k1042', 'lang-ja', 'katakana', 'ロ', 'ro', 'r', 'o', 'base', 1042),
  ('kana-k1043', 'lang-ja', 'katakana', 'ワ', 'wa', 'w', 'a', 'base', 1043),
  ('kana-k1044', 'lang-ja', 'katakana', 'ヲ', 'wo', 'w', 'o', 'base', 1044),
  ('kana-k1045', 'lang-ja', 'katakana', 'ン', 'n', 'N', 'n', 'base', 1045),
  ('kana-k1046', 'lang-ja', 'katakana', 'ガ', 'ga', 'g', 'a', 'dakuten', 1046),
  ('kana-k1047', 'lang-ja', 'katakana', 'ギ', 'gi', 'g', 'i', 'dakuten', 1047),
  ('kana-k1048', 'lang-ja', 'katakana', 'グ', 'gu', 'g', 'u', 'dakuten', 1048),
  ('kana-k1049', 'lang-ja', 'katakana', 'ゲ', 'ge', 'g', 'e', 'dakuten', 1049),
  ('kana-k1050', 'lang-ja', 'katakana', 'ゴ', 'go', 'g', 'o', 'dakuten', 1050),
  ('kana-k1051', 'lang-ja', 'katakana', 'ザ', 'za', 'z', 'a', 'dakuten', 1051),
  ('kana-k1052', 'lang-ja', 'katakana', 'ジ', 'ji', 'z', 'i', 'dakuten', 1052),
  ('kana-k1053', 'lang-ja', 'katakana', 'ズ', 'zu', 'z', 'u', 'dakuten', 1053),
  ('kana-k1054', 'lang-ja', 'katakana', 'ゼ', 'ze', 'z', 'e', 'dakuten', 1054),
  ('kana-k1055', 'lang-ja', 'katakana', 'ゾ', 'zo', 'z', 'o', 'dakuten', 1055),
  ('kana-k1056', 'lang-ja', 'katakana', 'ダ', 'da', 'd', 'a', 'dakuten', 1056),
  ('kana-k1057', 'lang-ja', 'katakana', 'ヂ', 'ji', 'd', 'i', 'dakuten', 1057),
  ('kana-k1058', 'lang-ja', 'katakana', 'ヅ', 'zu', 'd', 'u', 'dakuten', 1058),
  ('kana-k1059', 'lang-ja', 'katakana', 'デ', 'de', 'd', 'e', 'dakuten', 1059),
  ('kana-k1060', 'lang-ja', 'katakana', 'ド', 'do', 'd', 'o', 'dakuten', 1060),
  ('kana-k1061', 'lang-ja', 'katakana', 'バ', 'ba', 'b', 'a', 'dakuten', 1061),
  ('kana-k1062', 'lang-ja', 'katakana', 'ビ', 'bi', 'b', 'i', 'dakuten', 1062),
  ('kana-k1063', 'lang-ja', 'katakana', 'ブ', 'bu', 'b', 'u', 'dakuten', 1063),
  ('kana-k1064', 'lang-ja', 'katakana', 'ベ', 'be', 'b', 'e', 'dakuten', 1064),
  ('kana-k1065', 'lang-ja', 'katakana', 'ボ', 'bo', 'b', 'o', 'dakuten', 1065),
  ('kana-k1066', 'lang-ja', 'katakana', 'パ', 'pa', 'p', 'a', 'handakuten', 1066),
  ('kana-k1067', 'lang-ja', 'katakana', 'ピ', 'pi', 'p', 'i', 'handakuten', 1067),
  ('kana-k1068', 'lang-ja', 'katakana', 'プ', 'pu', 'p', 'u', 'handakuten', 1068),
  ('kana-k1069', 'lang-ja', 'katakana', 'ペ', 'pe', 'p', 'e', 'handakuten', 1069),
  ('kana-k1070', 'lang-ja', 'katakana', 'ポ', 'po', 'p', 'o', 'handakuten', 1070)
ON CONFLICT (language_id, script, character) DO NOTHING;

INSERT INTO study_items (id, language_id, kind, kana_id, level_id, sort_index, published, active) VALUES
  ('si-kana-h0', 'lang-ja', 'kana', 'kana-h0', 'lvl-ja-n5', 0, true, true),
  ('si-kana-h1', 'lang-ja', 'kana', 'kana-h1', 'lvl-ja-n5', 1, true, true),
  ('si-kana-h2', 'lang-ja', 'kana', 'kana-h2', 'lvl-ja-n5', 2, true, true),
  ('si-kana-h3', 'lang-ja', 'kana', 'kana-h3', 'lvl-ja-n5', 3, true, true),
  ('si-kana-h4', 'lang-ja', 'kana', 'kana-h4', 'lvl-ja-n5', 4, true, true),
  ('si-kana-h5', 'lang-ja', 'kana', 'kana-h5', 'lvl-ja-n5', 5, true, true),
  ('si-kana-h6', 'lang-ja', 'kana', 'kana-h6', 'lvl-ja-n5', 6, true, true),
  ('si-kana-h7', 'lang-ja', 'kana', 'kana-h7', 'lvl-ja-n5', 7, true, true),
  ('si-kana-h8', 'lang-ja', 'kana', 'kana-h8', 'lvl-ja-n5', 8, true, true),
  ('si-kana-h9', 'lang-ja', 'kana', 'kana-h9', 'lvl-ja-n5', 9, true, true),
  ('si-kana-h10', 'lang-ja', 'kana', 'kana-h10', 'lvl-ja-n5', 10, true, true),
  ('si-kana-h11', 'lang-ja', 'kana', 'kana-h11', 'lvl-ja-n5', 11, true, true),
  ('si-kana-h12', 'lang-ja', 'kana', 'kana-h12', 'lvl-ja-n5', 12, true, true),
  ('si-kana-h13', 'lang-ja', 'kana', 'kana-h13', 'lvl-ja-n5', 13, true, true),
  ('si-kana-h14', 'lang-ja', 'kana', 'kana-h14', 'lvl-ja-n5', 14, true, true),
  ('si-kana-h15', 'lang-ja', 'kana', 'kana-h15', 'lvl-ja-n5', 15, true, true),
  ('si-kana-h16', 'lang-ja', 'kana', 'kana-h16', 'lvl-ja-n5', 16, true, true),
  ('si-kana-h17', 'lang-ja', 'kana', 'kana-h17', 'lvl-ja-n5', 17, true, true),
  ('si-kana-h18', 'lang-ja', 'kana', 'kana-h18', 'lvl-ja-n5', 18, true, true),
  ('si-kana-h19', 'lang-ja', 'kana', 'kana-h19', 'lvl-ja-n5', 19, true, true),
  ('si-kana-h20', 'lang-ja', 'kana', 'kana-h20', 'lvl-ja-n5', 20, true, true),
  ('si-kana-h21', 'lang-ja', 'kana', 'kana-h21', 'lvl-ja-n5', 21, true, true),
  ('si-kana-h22', 'lang-ja', 'kana', 'kana-h22', 'lvl-ja-n5', 22, true, true),
  ('si-kana-h23', 'lang-ja', 'kana', 'kana-h23', 'lvl-ja-n5', 23, true, true),
  ('si-kana-h24', 'lang-ja', 'kana', 'kana-h24', 'lvl-ja-n5', 24, true, true),
  ('si-kana-h25', 'lang-ja', 'kana', 'kana-h25', 'lvl-ja-n5', 25, true, true),
  ('si-kana-h26', 'lang-ja', 'kana', 'kana-h26', 'lvl-ja-n5', 26, true, true),
  ('si-kana-h27', 'lang-ja', 'kana', 'kana-h27', 'lvl-ja-n5', 27, true, true),
  ('si-kana-h28', 'lang-ja', 'kana', 'kana-h28', 'lvl-ja-n5', 28, true, true),
  ('si-kana-h29', 'lang-ja', 'kana', 'kana-h29', 'lvl-ja-n5', 29, true, true),
  ('si-kana-h30', 'lang-ja', 'kana', 'kana-h30', 'lvl-ja-n5', 30, true, true),
  ('si-kana-h31', 'lang-ja', 'kana', 'kana-h31', 'lvl-ja-n5', 31, true, true),
  ('si-kana-h32', 'lang-ja', 'kana', 'kana-h32', 'lvl-ja-n5', 32, true, true),
  ('si-kana-h33', 'lang-ja', 'kana', 'kana-h33', 'lvl-ja-n5', 33, true, true),
  ('si-kana-h34', 'lang-ja', 'kana', 'kana-h34', 'lvl-ja-n5', 34, true, true),
  ('si-kana-h35', 'lang-ja', 'kana', 'kana-h35', 'lvl-ja-n5', 35, true, true),
  ('si-kana-h36', 'lang-ja', 'kana', 'kana-h36', 'lvl-ja-n5', 36, true, true),
  ('si-kana-h37', 'lang-ja', 'kana', 'kana-h37', 'lvl-ja-n5', 37, true, true),
  ('si-kana-h38', 'lang-ja', 'kana', 'kana-h38', 'lvl-ja-n5', 38, true, true),
  ('si-kana-h39', 'lang-ja', 'kana', 'kana-h39', 'lvl-ja-n5', 39, true, true),
  ('si-kana-h40', 'lang-ja', 'kana', 'kana-h40', 'lvl-ja-n5', 40, true, true),
  ('si-kana-h41', 'lang-ja', 'kana', 'kana-h41', 'lvl-ja-n5', 41, true, true),
  ('si-kana-h42', 'lang-ja', 'kana', 'kana-h42', 'lvl-ja-n5', 42, true, true),
  ('si-kana-h43', 'lang-ja', 'kana', 'kana-h43', 'lvl-ja-n5', 43, true, true),
  ('si-kana-h44', 'lang-ja', 'kana', 'kana-h44', 'lvl-ja-n5', 44, true, true),
  ('si-kana-h45', 'lang-ja', 'kana', 'kana-h45', 'lvl-ja-n5', 45, true, true),
  ('si-kana-h46', 'lang-ja', 'kana', 'kana-h46', 'lvl-ja-n5', 46, true, true),
  ('si-kana-h47', 'lang-ja', 'kana', 'kana-h47', 'lvl-ja-n5', 47, true, true),
  ('si-kana-h48', 'lang-ja', 'kana', 'kana-h48', 'lvl-ja-n5', 48, true, true),
  ('si-kana-h49', 'lang-ja', 'kana', 'kana-h49', 'lvl-ja-n5', 49, true, true),
  ('si-kana-h50', 'lang-ja', 'kana', 'kana-h50', 'lvl-ja-n5', 50, true, true),
  ('si-kana-h51', 'lang-ja', 'kana', 'kana-h51', 'lvl-ja-n5', 51, true, true),
  ('si-kana-h52', 'lang-ja', 'kana', 'kana-h52', 'lvl-ja-n5', 52, true, true),
  ('si-kana-h53', 'lang-ja', 'kana', 'kana-h53', 'lvl-ja-n5', 53, true, true),
  ('si-kana-h54', 'lang-ja', 'kana', 'kana-h54', 'lvl-ja-n5', 54, true, true),
  ('si-kana-h55', 'lang-ja', 'kana', 'kana-h55', 'lvl-ja-n5', 55, true, true),
  ('si-kana-h56', 'lang-ja', 'kana', 'kana-h56', 'lvl-ja-n5', 56, true, true),
  ('si-kana-h57', 'lang-ja', 'kana', 'kana-h57', 'lvl-ja-n5', 57, true, true),
  ('si-kana-h58', 'lang-ja', 'kana', 'kana-h58', 'lvl-ja-n5', 58, true, true),
  ('si-kana-h59', 'lang-ja', 'kana', 'kana-h59', 'lvl-ja-n5', 59, true, true),
  ('si-kana-h60', 'lang-ja', 'kana', 'kana-h60', 'lvl-ja-n5', 60, true, true),
  ('si-kana-h61', 'lang-ja', 'kana', 'kana-h61', 'lvl-ja-n5', 61, true, true),
  ('si-kana-h62', 'lang-ja', 'kana', 'kana-h62', 'lvl-ja-n5', 62, true, true),
  ('si-kana-h63', 'lang-ja', 'kana', 'kana-h63', 'lvl-ja-n5', 63, true, true),
  ('si-kana-h64', 'lang-ja', 'kana', 'kana-h64', 'lvl-ja-n5', 64, true, true),
  ('si-kana-h65', 'lang-ja', 'kana', 'kana-h65', 'lvl-ja-n5', 65, true, true),
  ('si-kana-h66', 'lang-ja', 'kana', 'kana-h66', 'lvl-ja-n5', 66, true, true),
  ('si-kana-h67', 'lang-ja', 'kana', 'kana-h67', 'lvl-ja-n5', 67, true, true),
  ('si-kana-h68', 'lang-ja', 'kana', 'kana-h68', 'lvl-ja-n5', 68, true, true),
  ('si-kana-h69', 'lang-ja', 'kana', 'kana-h69', 'lvl-ja-n5', 69, true, true),
  ('si-kana-h70', 'lang-ja', 'kana', 'kana-h70', 'lvl-ja-n5', 70, true, true),
  ('si-kana-k1000', 'lang-ja', 'kana', 'kana-k1000', 'lvl-ja-n5', 1000, true, true),
  ('si-kana-k1001', 'lang-ja', 'kana', 'kana-k1001', 'lvl-ja-n5', 1001, true, true),
  ('si-kana-k1002', 'lang-ja', 'kana', 'kana-k1002', 'lvl-ja-n5', 1002, true, true),
  ('si-kana-k1003', 'lang-ja', 'kana', 'kana-k1003', 'lvl-ja-n5', 1003, true, true),
  ('si-kana-k1004', 'lang-ja', 'kana', 'kana-k1004', 'lvl-ja-n5', 1004, true, true),
  ('si-kana-k1005', 'lang-ja', 'kana', 'kana-k1005', 'lvl-ja-n5', 1005, true, true),
  ('si-kana-k1006', 'lang-ja', 'kana', 'kana-k1006', 'lvl-ja-n5', 1006, true, true),
  ('si-kana-k1007', 'lang-ja', 'kana', 'kana-k1007', 'lvl-ja-n5', 1007, true, true),
  ('si-kana-k1008', 'lang-ja', 'kana', 'kana-k1008', 'lvl-ja-n5', 1008, true, true),
  ('si-kana-k1009', 'lang-ja', 'kana', 'kana-k1009', 'lvl-ja-n5', 1009, true, true),
  ('si-kana-k1010', 'lang-ja', 'kana', 'kana-k1010', 'lvl-ja-n5', 1010, true, true),
  ('si-kana-k1011', 'lang-ja', 'kana', 'kana-k1011', 'lvl-ja-n5', 1011, true, true),
  ('si-kana-k1012', 'lang-ja', 'kana', 'kana-k1012', 'lvl-ja-n5', 1012, true, true),
  ('si-kana-k1013', 'lang-ja', 'kana', 'kana-k1013', 'lvl-ja-n5', 1013, true, true),
  ('si-kana-k1014', 'lang-ja', 'kana', 'kana-k1014', 'lvl-ja-n5', 1014, true, true),
  ('si-kana-k1015', 'lang-ja', 'kana', 'kana-k1015', 'lvl-ja-n5', 1015, true, true),
  ('si-kana-k1016', 'lang-ja', 'kana', 'kana-k1016', 'lvl-ja-n5', 1016, true, true),
  ('si-kana-k1017', 'lang-ja', 'kana', 'kana-k1017', 'lvl-ja-n5', 1017, true, true),
  ('si-kana-k1018', 'lang-ja', 'kana', 'kana-k1018', 'lvl-ja-n5', 1018, true, true),
  ('si-kana-k1019', 'lang-ja', 'kana', 'kana-k1019', 'lvl-ja-n5', 1019, true, true),
  ('si-kana-k1020', 'lang-ja', 'kana', 'kana-k1020', 'lvl-ja-n5', 1020, true, true),
  ('si-kana-k1021', 'lang-ja', 'kana', 'kana-k1021', 'lvl-ja-n5', 1021, true, true),
  ('si-kana-k1022', 'lang-ja', 'kana', 'kana-k1022', 'lvl-ja-n5', 1022, true, true),
  ('si-kana-k1023', 'lang-ja', 'kana', 'kana-k1023', 'lvl-ja-n5', 1023, true, true),
  ('si-kana-k1024', 'lang-ja', 'kana', 'kana-k1024', 'lvl-ja-n5', 1024, true, true),
  ('si-kana-k1025', 'lang-ja', 'kana', 'kana-k1025', 'lvl-ja-n5', 1025, true, true),
  ('si-kana-k1026', 'lang-ja', 'kana', 'kana-k1026', 'lvl-ja-n5', 1026, true, true),
  ('si-kana-k1027', 'lang-ja', 'kana', 'kana-k1027', 'lvl-ja-n5', 1027, true, true),
  ('si-kana-k1028', 'lang-ja', 'kana', 'kana-k1028', 'lvl-ja-n5', 1028, true, true),
  ('si-kana-k1029', 'lang-ja', 'kana', 'kana-k1029', 'lvl-ja-n5', 1029, true, true),
  ('si-kana-k1030', 'lang-ja', 'kana', 'kana-k1030', 'lvl-ja-n5', 1030, true, true),
  ('si-kana-k1031', 'lang-ja', 'kana', 'kana-k1031', 'lvl-ja-n5', 1031, true, true),
  ('si-kana-k1032', 'lang-ja', 'kana', 'kana-k1032', 'lvl-ja-n5', 1032, true, true),
  ('si-kana-k1033', 'lang-ja', 'kana', 'kana-k1033', 'lvl-ja-n5', 1033, true, true),
  ('si-kana-k1034', 'lang-ja', 'kana', 'kana-k1034', 'lvl-ja-n5', 1034, true, true),
  ('si-kana-k1035', 'lang-ja', 'kana', 'kana-k1035', 'lvl-ja-n5', 1035, true, true),
  ('si-kana-k1036', 'lang-ja', 'kana', 'kana-k1036', 'lvl-ja-n5', 1036, true, true),
  ('si-kana-k1037', 'lang-ja', 'kana', 'kana-k1037', 'lvl-ja-n5', 1037, true, true),
  ('si-kana-k1038', 'lang-ja', 'kana', 'kana-k1038', 'lvl-ja-n5', 1038, true, true),
  ('si-kana-k1039', 'lang-ja', 'kana', 'kana-k1039', 'lvl-ja-n5', 1039, true, true),
  ('si-kana-k1040', 'lang-ja', 'kana', 'kana-k1040', 'lvl-ja-n5', 1040, true, true),
  ('si-kana-k1041', 'lang-ja', 'kana', 'kana-k1041', 'lvl-ja-n5', 1041, true, true),
  ('si-kana-k1042', 'lang-ja', 'kana', 'kana-k1042', 'lvl-ja-n5', 1042, true, true),
  ('si-kana-k1043', 'lang-ja', 'kana', 'kana-k1043', 'lvl-ja-n5', 1043, true, true),
  ('si-kana-k1044', 'lang-ja', 'kana', 'kana-k1044', 'lvl-ja-n5', 1044, true, true),
  ('si-kana-k1045', 'lang-ja', 'kana', 'kana-k1045', 'lvl-ja-n5', 1045, true, true),
  ('si-kana-k1046', 'lang-ja', 'kana', 'kana-k1046', 'lvl-ja-n5', 1046, true, true),
  ('si-kana-k1047', 'lang-ja', 'kana', 'kana-k1047', 'lvl-ja-n5', 1047, true, true),
  ('si-kana-k1048', 'lang-ja', 'kana', 'kana-k1048', 'lvl-ja-n5', 1048, true, true),
  ('si-kana-k1049', 'lang-ja', 'kana', 'kana-k1049', 'lvl-ja-n5', 1049, true, true),
  ('si-kana-k1050', 'lang-ja', 'kana', 'kana-k1050', 'lvl-ja-n5', 1050, true, true),
  ('si-kana-k1051', 'lang-ja', 'kana', 'kana-k1051', 'lvl-ja-n5', 1051, true, true),
  ('si-kana-k1052', 'lang-ja', 'kana', 'kana-k1052', 'lvl-ja-n5', 1052, true, true),
  ('si-kana-k1053', 'lang-ja', 'kana', 'kana-k1053', 'lvl-ja-n5', 1053, true, true),
  ('si-kana-k1054', 'lang-ja', 'kana', 'kana-k1054', 'lvl-ja-n5', 1054, true, true),
  ('si-kana-k1055', 'lang-ja', 'kana', 'kana-k1055', 'lvl-ja-n5', 1055, true, true),
  ('si-kana-k1056', 'lang-ja', 'kana', 'kana-k1056', 'lvl-ja-n5', 1056, true, true),
  ('si-kana-k1057', 'lang-ja', 'kana', 'kana-k1057', 'lvl-ja-n5', 1057, true, true),
  ('si-kana-k1058', 'lang-ja', 'kana', 'kana-k1058', 'lvl-ja-n5', 1058, true, true),
  ('si-kana-k1059', 'lang-ja', 'kana', 'kana-k1059', 'lvl-ja-n5', 1059, true, true),
  ('si-kana-k1060', 'lang-ja', 'kana', 'kana-k1060', 'lvl-ja-n5', 1060, true, true),
  ('si-kana-k1061', 'lang-ja', 'kana', 'kana-k1061', 'lvl-ja-n5', 1061, true, true),
  ('si-kana-k1062', 'lang-ja', 'kana', 'kana-k1062', 'lvl-ja-n5', 1062, true, true),
  ('si-kana-k1063', 'lang-ja', 'kana', 'kana-k1063', 'lvl-ja-n5', 1063, true, true),
  ('si-kana-k1064', 'lang-ja', 'kana', 'kana-k1064', 'lvl-ja-n5', 1064, true, true),
  ('si-kana-k1065', 'lang-ja', 'kana', 'kana-k1065', 'lvl-ja-n5', 1065, true, true),
  ('si-kana-k1066', 'lang-ja', 'kana', 'kana-k1066', 'lvl-ja-n5', 1066, true, true),
  ('si-kana-k1067', 'lang-ja', 'kana', 'kana-k1067', 'lvl-ja-n5', 1067, true, true),
  ('si-kana-k1068', 'lang-ja', 'kana', 'kana-k1068', 'lvl-ja-n5', 1068, true, true),
  ('si-kana-k1069', 'lang-ja', 'kana', 'kana-k1069', 'lvl-ja-n5', 1069, true, true),
  ('si-kana-k1070', 'lang-ja', 'kana', 'kana-k1070', 'lvl-ja-n5', 1070, true, true)
ON CONFLICT DO NOTHING;

INSERT INTO study_item_facets (id, study_item_id, facet, enabled, weight, intro_order) VALUES
  ('fac-kana-h0', 'si-kana-h0', 'reading', true, 1, 0),
  ('fac-kana-h1', 'si-kana-h1', 'reading', true, 1, 1),
  ('fac-kana-h2', 'si-kana-h2', 'reading', true, 1, 2),
  ('fac-kana-h3', 'si-kana-h3', 'reading', true, 1, 3),
  ('fac-kana-h4', 'si-kana-h4', 'reading', true, 1, 4),
  ('fac-kana-h5', 'si-kana-h5', 'reading', true, 1, 5),
  ('fac-kana-h6', 'si-kana-h6', 'reading', true, 1, 6),
  ('fac-kana-h7', 'si-kana-h7', 'reading', true, 1, 7),
  ('fac-kana-h8', 'si-kana-h8', 'reading', true, 1, 8),
  ('fac-kana-h9', 'si-kana-h9', 'reading', true, 1, 9),
  ('fac-kana-h10', 'si-kana-h10', 'reading', true, 1, 10),
  ('fac-kana-h11', 'si-kana-h11', 'reading', true, 1, 11),
  ('fac-kana-h12', 'si-kana-h12', 'reading', true, 1, 12),
  ('fac-kana-h13', 'si-kana-h13', 'reading', true, 1, 13),
  ('fac-kana-h14', 'si-kana-h14', 'reading', true, 1, 14),
  ('fac-kana-h15', 'si-kana-h15', 'reading', true, 1, 15),
  ('fac-kana-h16', 'si-kana-h16', 'reading', true, 1, 16),
  ('fac-kana-h17', 'si-kana-h17', 'reading', true, 1, 17),
  ('fac-kana-h18', 'si-kana-h18', 'reading', true, 1, 18),
  ('fac-kana-h19', 'si-kana-h19', 'reading', true, 1, 19),
  ('fac-kana-h20', 'si-kana-h20', 'reading', true, 1, 20),
  ('fac-kana-h21', 'si-kana-h21', 'reading', true, 1, 21),
  ('fac-kana-h22', 'si-kana-h22', 'reading', true, 1, 22),
  ('fac-kana-h23', 'si-kana-h23', 'reading', true, 1, 23),
  ('fac-kana-h24', 'si-kana-h24', 'reading', true, 1, 24),
  ('fac-kana-h25', 'si-kana-h25', 'reading', true, 1, 25),
  ('fac-kana-h26', 'si-kana-h26', 'reading', true, 1, 26),
  ('fac-kana-h27', 'si-kana-h27', 'reading', true, 1, 27),
  ('fac-kana-h28', 'si-kana-h28', 'reading', true, 1, 28),
  ('fac-kana-h29', 'si-kana-h29', 'reading', true, 1, 29),
  ('fac-kana-h30', 'si-kana-h30', 'reading', true, 1, 30),
  ('fac-kana-h31', 'si-kana-h31', 'reading', true, 1, 31),
  ('fac-kana-h32', 'si-kana-h32', 'reading', true, 1, 32),
  ('fac-kana-h33', 'si-kana-h33', 'reading', true, 1, 33),
  ('fac-kana-h34', 'si-kana-h34', 'reading', true, 1, 34),
  ('fac-kana-h35', 'si-kana-h35', 'reading', true, 1, 35),
  ('fac-kana-h36', 'si-kana-h36', 'reading', true, 1, 36),
  ('fac-kana-h37', 'si-kana-h37', 'reading', true, 1, 37),
  ('fac-kana-h38', 'si-kana-h38', 'reading', true, 1, 38),
  ('fac-kana-h39', 'si-kana-h39', 'reading', true, 1, 39),
  ('fac-kana-h40', 'si-kana-h40', 'reading', true, 1, 40),
  ('fac-kana-h41', 'si-kana-h41', 'reading', true, 1, 41),
  ('fac-kana-h42', 'si-kana-h42', 'reading', true, 1, 42),
  ('fac-kana-h43', 'si-kana-h43', 'reading', true, 1, 43),
  ('fac-kana-h44', 'si-kana-h44', 'reading', true, 1, 44),
  ('fac-kana-h45', 'si-kana-h45', 'reading', true, 1, 45),
  ('fac-kana-h46', 'si-kana-h46', 'reading', true, 1, 46),
  ('fac-kana-h47', 'si-kana-h47', 'reading', true, 1, 47),
  ('fac-kana-h48', 'si-kana-h48', 'reading', true, 1, 48),
  ('fac-kana-h49', 'si-kana-h49', 'reading', true, 1, 49),
  ('fac-kana-h50', 'si-kana-h50', 'reading', true, 1, 50),
  ('fac-kana-h51', 'si-kana-h51', 'reading', true, 1, 51),
  ('fac-kana-h52', 'si-kana-h52', 'reading', true, 1, 52),
  ('fac-kana-h53', 'si-kana-h53', 'reading', true, 1, 53),
  ('fac-kana-h54', 'si-kana-h54', 'reading', true, 1, 54),
  ('fac-kana-h55', 'si-kana-h55', 'reading', true, 1, 55),
  ('fac-kana-h56', 'si-kana-h56', 'reading', true, 1, 56),
  ('fac-kana-h57', 'si-kana-h57', 'reading', true, 1, 57),
  ('fac-kana-h58', 'si-kana-h58', 'reading', true, 1, 58),
  ('fac-kana-h59', 'si-kana-h59', 'reading', true, 1, 59),
  ('fac-kana-h60', 'si-kana-h60', 'reading', true, 1, 60),
  ('fac-kana-h61', 'si-kana-h61', 'reading', true, 1, 61),
  ('fac-kana-h62', 'si-kana-h62', 'reading', true, 1, 62),
  ('fac-kana-h63', 'si-kana-h63', 'reading', true, 1, 63),
  ('fac-kana-h64', 'si-kana-h64', 'reading', true, 1, 64),
  ('fac-kana-h65', 'si-kana-h65', 'reading', true, 1, 65),
  ('fac-kana-h66', 'si-kana-h66', 'reading', true, 1, 66),
  ('fac-kana-h67', 'si-kana-h67', 'reading', true, 1, 67),
  ('fac-kana-h68', 'si-kana-h68', 'reading', true, 1, 68),
  ('fac-kana-h69', 'si-kana-h69', 'reading', true, 1, 69),
  ('fac-kana-h70', 'si-kana-h70', 'reading', true, 1, 70),
  ('fac-kana-k1000', 'si-kana-k1000', 'reading', true, 1, 1000),
  ('fac-kana-k1001', 'si-kana-k1001', 'reading', true, 1, 1001),
  ('fac-kana-k1002', 'si-kana-k1002', 'reading', true, 1, 1002),
  ('fac-kana-k1003', 'si-kana-k1003', 'reading', true, 1, 1003),
  ('fac-kana-k1004', 'si-kana-k1004', 'reading', true, 1, 1004),
  ('fac-kana-k1005', 'si-kana-k1005', 'reading', true, 1, 1005),
  ('fac-kana-k1006', 'si-kana-k1006', 'reading', true, 1, 1006),
  ('fac-kana-k1007', 'si-kana-k1007', 'reading', true, 1, 1007),
  ('fac-kana-k1008', 'si-kana-k1008', 'reading', true, 1, 1008),
  ('fac-kana-k1009', 'si-kana-k1009', 'reading', true, 1, 1009),
  ('fac-kana-k1010', 'si-kana-k1010', 'reading', true, 1, 1010),
  ('fac-kana-k1011', 'si-kana-k1011', 'reading', true, 1, 1011),
  ('fac-kana-k1012', 'si-kana-k1012', 'reading', true, 1, 1012),
  ('fac-kana-k1013', 'si-kana-k1013', 'reading', true, 1, 1013),
  ('fac-kana-k1014', 'si-kana-k1014', 'reading', true, 1, 1014),
  ('fac-kana-k1015', 'si-kana-k1015', 'reading', true, 1, 1015),
  ('fac-kana-k1016', 'si-kana-k1016', 'reading', true, 1, 1016),
  ('fac-kana-k1017', 'si-kana-k1017', 'reading', true, 1, 1017),
  ('fac-kana-k1018', 'si-kana-k1018', 'reading', true, 1, 1018),
  ('fac-kana-k1019', 'si-kana-k1019', 'reading', true, 1, 1019),
  ('fac-kana-k1020', 'si-kana-k1020', 'reading', true, 1, 1020),
  ('fac-kana-k1021', 'si-kana-k1021', 'reading', true, 1, 1021),
  ('fac-kana-k1022', 'si-kana-k1022', 'reading', true, 1, 1022),
  ('fac-kana-k1023', 'si-kana-k1023', 'reading', true, 1, 1023),
  ('fac-kana-k1024', 'si-kana-k1024', 'reading', true, 1, 1024),
  ('fac-kana-k1025', 'si-kana-k1025', 'reading', true, 1, 1025),
  ('fac-kana-k1026', 'si-kana-k1026', 'reading', true, 1, 1026),
  ('fac-kana-k1027', 'si-kana-k1027', 'reading', true, 1, 1027),
  ('fac-kana-k1028', 'si-kana-k1028', 'reading', true, 1, 1028),
  ('fac-kana-k1029', 'si-kana-k1029', 'reading', true, 1, 1029),
  ('fac-kana-k1030', 'si-kana-k1030', 'reading', true, 1, 1030),
  ('fac-kana-k1031', 'si-kana-k1031', 'reading', true, 1, 1031),
  ('fac-kana-k1032', 'si-kana-k1032', 'reading', true, 1, 1032),
  ('fac-kana-k1033', 'si-kana-k1033', 'reading', true, 1, 1033),
  ('fac-kana-k1034', 'si-kana-k1034', 'reading', true, 1, 1034),
  ('fac-kana-k1035', 'si-kana-k1035', 'reading', true, 1, 1035),
  ('fac-kana-k1036', 'si-kana-k1036', 'reading', true, 1, 1036),
  ('fac-kana-k1037', 'si-kana-k1037', 'reading', true, 1, 1037),
  ('fac-kana-k1038', 'si-kana-k1038', 'reading', true, 1, 1038),
  ('fac-kana-k1039', 'si-kana-k1039', 'reading', true, 1, 1039),
  ('fac-kana-k1040', 'si-kana-k1040', 'reading', true, 1, 1040),
  ('fac-kana-k1041', 'si-kana-k1041', 'reading', true, 1, 1041),
  ('fac-kana-k1042', 'si-kana-k1042', 'reading', true, 1, 1042),
  ('fac-kana-k1043', 'si-kana-k1043', 'reading', true, 1, 1043),
  ('fac-kana-k1044', 'si-kana-k1044', 'reading', true, 1, 1044),
  ('fac-kana-k1045', 'si-kana-k1045', 'reading', true, 1, 1045),
  ('fac-kana-k1046', 'si-kana-k1046', 'reading', true, 1, 1046),
  ('fac-kana-k1047', 'si-kana-k1047', 'reading', true, 1, 1047),
  ('fac-kana-k1048', 'si-kana-k1048', 'reading', true, 1, 1048),
  ('fac-kana-k1049', 'si-kana-k1049', 'reading', true, 1, 1049),
  ('fac-kana-k1050', 'si-kana-k1050', 'reading', true, 1, 1050),
  ('fac-kana-k1051', 'si-kana-k1051', 'reading', true, 1, 1051),
  ('fac-kana-k1052', 'si-kana-k1052', 'reading', true, 1, 1052),
  ('fac-kana-k1053', 'si-kana-k1053', 'reading', true, 1, 1053),
  ('fac-kana-k1054', 'si-kana-k1054', 'reading', true, 1, 1054),
  ('fac-kana-k1055', 'si-kana-k1055', 'reading', true, 1, 1055),
  ('fac-kana-k1056', 'si-kana-k1056', 'reading', true, 1, 1056),
  ('fac-kana-k1057', 'si-kana-k1057', 'reading', true, 1, 1057),
  ('fac-kana-k1058', 'si-kana-k1058', 'reading', true, 1, 1058),
  ('fac-kana-k1059', 'si-kana-k1059', 'reading', true, 1, 1059),
  ('fac-kana-k1060', 'si-kana-k1060', 'reading', true, 1, 1060),
  ('fac-kana-k1061', 'si-kana-k1061', 'reading', true, 1, 1061),
  ('fac-kana-k1062', 'si-kana-k1062', 'reading', true, 1, 1062),
  ('fac-kana-k1063', 'si-kana-k1063', 'reading', true, 1, 1063),
  ('fac-kana-k1064', 'si-kana-k1064', 'reading', true, 1, 1064),
  ('fac-kana-k1065', 'si-kana-k1065', 'reading', true, 1, 1065),
  ('fac-kana-k1066', 'si-kana-k1066', 'reading', true, 1, 1066),
  ('fac-kana-k1067', 'si-kana-k1067', 'reading', true, 1, 1067),
  ('fac-kana-k1068', 'si-kana-k1068', 'reading', true, 1, 1068),
  ('fac-kana-k1069', 'si-kana-k1069', 'reading', true, 1, 1069),
  ('fac-kana-k1070', 'si-kana-k1070', 'reading', true, 1, 1070)
ON CONFLICT (study_item_id, facet) DO NOTHING;

INSERT INTO exercise_prompts (id, facet_id, template_id, language_id, prompt, answer) VALUES
  ('ep-kana-h0', 'fac-kana-h0', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"あ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"a","accepted":["a"]}'::jsonb),
  ('ep-kana-h1', 'fac-kana-h1', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"い","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"i","accepted":["i"]}'::jsonb),
  ('ep-kana-h2', 'fac-kana-h2', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"う","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"u","accepted":["u"]}'::jsonb),
  ('ep-kana-h3', 'fac-kana-h3', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"え","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"e","accepted":["e"]}'::jsonb),
  ('ep-kana-h4', 'fac-kana-h4', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"お","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"o","accepted":["o"]}'::jsonb),
  ('ep-kana-h5', 'fac-kana-h5', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"か","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ka","accepted":["ka"]}'::jsonb),
  ('ep-kana-h6', 'fac-kana-h6', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"き","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ki","accepted":["ki"]}'::jsonb),
  ('ep-kana-h7', 'fac-kana-h7', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"く","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ku","accepted":["ku"]}'::jsonb),
  ('ep-kana-h8', 'fac-kana-h8', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"け","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ke","accepted":["ke"]}'::jsonb),
  ('ep-kana-h9', 'fac-kana-h9', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"こ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ko","accepted":["ko"]}'::jsonb),
  ('ep-kana-h10', 'fac-kana-h10', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"さ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"sa","accepted":["sa"]}'::jsonb),
  ('ep-kana-h11', 'fac-kana-h11', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"し","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"shi","accepted":["shi","si"]}'::jsonb),
  ('ep-kana-h12', 'fac-kana-h12', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"す","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"su","accepted":["su"]}'::jsonb),
  ('ep-kana-h13', 'fac-kana-h13', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"せ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"se","accepted":["se"]}'::jsonb),
  ('ep-kana-h14', 'fac-kana-h14', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"そ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"so","accepted":["so"]}'::jsonb),
  ('ep-kana-h15', 'fac-kana-h15', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"た","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ta","accepted":["ta"]}'::jsonb),
  ('ep-kana-h16', 'fac-kana-h16', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ち","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"chi","accepted":["chi","ti"]}'::jsonb),
  ('ep-kana-h17', 'fac-kana-h17', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"つ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"tsu","accepted":["tsu","tu"]}'::jsonb),
  ('ep-kana-h18', 'fac-kana-h18', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"て","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"te","accepted":["te"]}'::jsonb),
  ('ep-kana-h19', 'fac-kana-h19', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"と","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"to","accepted":["to"]}'::jsonb),
  ('ep-kana-h20', 'fac-kana-h20', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"な","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"na","accepted":["na"]}'::jsonb),
  ('ep-kana-h21', 'fac-kana-h21', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"に","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ni","accepted":["ni"]}'::jsonb),
  ('ep-kana-h22', 'fac-kana-h22', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぬ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"nu","accepted":["nu"]}'::jsonb),
  ('ep-kana-h23', 'fac-kana-h23', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ね","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ne","accepted":["ne"]}'::jsonb),
  ('ep-kana-h24', 'fac-kana-h24', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"の","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"no","accepted":["no"]}'::jsonb),
  ('ep-kana-h25', 'fac-kana-h25', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"は","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ha","accepted":["ha"]}'::jsonb),
  ('ep-kana-h26', 'fac-kana-h26', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ひ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"hi","accepted":["hi"]}'::jsonb),
  ('ep-kana-h27', 'fac-kana-h27', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ふ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"fu","accepted":["fu","hu"]}'::jsonb),
  ('ep-kana-h28', 'fac-kana-h28', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"へ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"he","accepted":["he"]}'::jsonb),
  ('ep-kana-h29', 'fac-kana-h29', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ほ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ho","accepted":["ho"]}'::jsonb),
  ('ep-kana-h30', 'fac-kana-h30', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ま","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ma","accepted":["ma"]}'::jsonb),
  ('ep-kana-h31', 'fac-kana-h31', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"み","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"mi","accepted":["mi"]}'::jsonb),
  ('ep-kana-h32', 'fac-kana-h32', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"む","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"mu","accepted":["mu"]}'::jsonb),
  ('ep-kana-h33', 'fac-kana-h33', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"め","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"me","accepted":["me"]}'::jsonb),
  ('ep-kana-h34', 'fac-kana-h34', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"も","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"mo","accepted":["mo"]}'::jsonb),
  ('ep-kana-h35', 'fac-kana-h35', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"や","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ya","accepted":["ya"]}'::jsonb),
  ('ep-kana-h36', 'fac-kana-h36', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ゆ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"yu","accepted":["yu"]}'::jsonb),
  ('ep-kana-h37', 'fac-kana-h37', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"よ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"yo","accepted":["yo"]}'::jsonb),
  ('ep-kana-h38', 'fac-kana-h38', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ら","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ra","accepted":["ra"]}'::jsonb),
  ('ep-kana-h39', 'fac-kana-h39', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"り","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ri","accepted":["ri"]}'::jsonb),
  ('ep-kana-h40', 'fac-kana-h40', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"る","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ru","accepted":["ru"]}'::jsonb),
  ('ep-kana-h41', 'fac-kana-h41', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"れ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"re","accepted":["re"]}'::jsonb),
  ('ep-kana-h42', 'fac-kana-h42', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ろ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ro","accepted":["ro"]}'::jsonb),
  ('ep-kana-h43', 'fac-kana-h43', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"わ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"wa","accepted":["wa"]}'::jsonb),
  ('ep-kana-h44', 'fac-kana-h44', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"を","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"wo","accepted":["wo","o"]}'::jsonb),
  ('ep-kana-h45', 'fac-kana-h45', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ん","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"n","accepted":["n","nn"]}'::jsonb),
  ('ep-kana-h46', 'fac-kana-h46', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"が","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ga","accepted":["ga"]}'::jsonb),
  ('ep-kana-h47', 'fac-kana-h47', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぎ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"gi","accepted":["gi"]}'::jsonb),
  ('ep-kana-h48', 'fac-kana-h48', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぐ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"gu","accepted":["gu"]}'::jsonb),
  ('ep-kana-h49', 'fac-kana-h49', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"げ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ge","accepted":["ge"]}'::jsonb),
  ('ep-kana-h50', 'fac-kana-h50', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ご","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"go","accepted":["go"]}'::jsonb),
  ('ep-kana-h51', 'fac-kana-h51', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ざ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"za","accepted":["za"]}'::jsonb),
  ('ep-kana-h52', 'fac-kana-h52', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"じ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ji","accepted":["ji","zi","di"]}'::jsonb),
  ('ep-kana-h53', 'fac-kana-h53', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ず","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"zu","accepted":["zu","du"]}'::jsonb),
  ('ep-kana-h54', 'fac-kana-h54', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぜ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ze","accepted":["ze"]}'::jsonb),
  ('ep-kana-h55', 'fac-kana-h55', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぞ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"zo","accepted":["zo"]}'::jsonb),
  ('ep-kana-h56', 'fac-kana-h56', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"だ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"da","accepted":["da"]}'::jsonb),
  ('ep-kana-h57', 'fac-kana-h57', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぢ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ji","accepted":["ji","zi","di"]}'::jsonb),
  ('ep-kana-h58', 'fac-kana-h58', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"づ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"zu","accepted":["zu","du"]}'::jsonb),
  ('ep-kana-h59', 'fac-kana-h59', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"で","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"de","accepted":["de"]}'::jsonb),
  ('ep-kana-h60', 'fac-kana-h60', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ど","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"do","accepted":["do"]}'::jsonb),
  ('ep-kana-h61', 'fac-kana-h61', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ば","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ba","accepted":["ba"]}'::jsonb),
  ('ep-kana-h62', 'fac-kana-h62', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"び","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"bi","accepted":["bi"]}'::jsonb),
  ('ep-kana-h63', 'fac-kana-h63', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぶ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"bu","accepted":["bu"]}'::jsonb),
  ('ep-kana-h64', 'fac-kana-h64', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"べ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"be","accepted":["be"]}'::jsonb),
  ('ep-kana-h65', 'fac-kana-h65', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぼ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"bo","accepted":["bo"]}'::jsonb),
  ('ep-kana-h66', 'fac-kana-h66', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぱ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pa","accepted":["pa"]}'::jsonb),
  ('ep-kana-h67', 'fac-kana-h67', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぴ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pi","accepted":["pi"]}'::jsonb),
  ('ep-kana-h68', 'fac-kana-h68', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぷ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pu","accepted":["pu"]}'::jsonb),
  ('ep-kana-h69', 'fac-kana-h69', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぺ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pe","accepted":["pe"]}'::jsonb),
  ('ep-kana-h70', 'fac-kana-h70', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"hiragana","character":"ぽ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"po","accepted":["po"]}'::jsonb),
  ('ep-kana-k1000', 'fac-kana-k1000', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ア","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"a","accepted":["a"]}'::jsonb),
  ('ep-kana-k1001', 'fac-kana-k1001', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"イ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"i","accepted":["i"]}'::jsonb),
  ('ep-kana-k1002', 'fac-kana-k1002', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ウ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"u","accepted":["u"]}'::jsonb),
  ('ep-kana-k1003', 'fac-kana-k1003', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"エ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"e","accepted":["e"]}'::jsonb),
  ('ep-kana-k1004', 'fac-kana-k1004', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"オ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"o","accepted":["o"]}'::jsonb),
  ('ep-kana-k1005', 'fac-kana-k1005', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"カ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ka","accepted":["ka"]}'::jsonb),
  ('ep-kana-k1006', 'fac-kana-k1006', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"キ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ki","accepted":["ki"]}'::jsonb),
  ('ep-kana-k1007', 'fac-kana-k1007', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ク","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ku","accepted":["ku"]}'::jsonb),
  ('ep-kana-k1008', 'fac-kana-k1008', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ケ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ke","accepted":["ke"]}'::jsonb),
  ('ep-kana-k1009', 'fac-kana-k1009', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"コ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ko","accepted":["ko"]}'::jsonb),
  ('ep-kana-k1010', 'fac-kana-k1010', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"サ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"sa","accepted":["sa"]}'::jsonb),
  ('ep-kana-k1011', 'fac-kana-k1011', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"シ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"shi","accepted":["shi","si"]}'::jsonb),
  ('ep-kana-k1012', 'fac-kana-k1012', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ス","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"su","accepted":["su"]}'::jsonb),
  ('ep-kana-k1013', 'fac-kana-k1013', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"セ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"se","accepted":["se"]}'::jsonb),
  ('ep-kana-k1014', 'fac-kana-k1014', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ソ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"so","accepted":["so"]}'::jsonb),
  ('ep-kana-k1015', 'fac-kana-k1015', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"タ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ta","accepted":["ta"]}'::jsonb),
  ('ep-kana-k1016', 'fac-kana-k1016', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"チ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"chi","accepted":["chi","ti"]}'::jsonb),
  ('ep-kana-k1017', 'fac-kana-k1017', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ツ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"tsu","accepted":["tsu","tu"]}'::jsonb),
  ('ep-kana-k1018', 'fac-kana-k1018', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"テ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"te","accepted":["te"]}'::jsonb),
  ('ep-kana-k1019', 'fac-kana-k1019', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ト","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"to","accepted":["to"]}'::jsonb),
  ('ep-kana-k1020', 'fac-kana-k1020', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ナ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"na","accepted":["na"]}'::jsonb),
  ('ep-kana-k1021', 'fac-kana-k1021', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ニ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ni","accepted":["ni"]}'::jsonb),
  ('ep-kana-k1022', 'fac-kana-k1022', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヌ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"nu","accepted":["nu"]}'::jsonb),
  ('ep-kana-k1023', 'fac-kana-k1023', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ネ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ne","accepted":["ne"]}'::jsonb),
  ('ep-kana-k1024', 'fac-kana-k1024', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ノ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"no","accepted":["no"]}'::jsonb),
  ('ep-kana-k1025', 'fac-kana-k1025', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ハ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ha","accepted":["ha"]}'::jsonb),
  ('ep-kana-k1026', 'fac-kana-k1026', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヒ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"hi","accepted":["hi"]}'::jsonb),
  ('ep-kana-k1027', 'fac-kana-k1027', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"フ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"fu","accepted":["fu","hu"]}'::jsonb),
  ('ep-kana-k1028', 'fac-kana-k1028', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヘ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"he","accepted":["he"]}'::jsonb),
  ('ep-kana-k1029', 'fac-kana-k1029', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ホ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ho","accepted":["ho"]}'::jsonb),
  ('ep-kana-k1030', 'fac-kana-k1030', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"マ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ma","accepted":["ma"]}'::jsonb),
  ('ep-kana-k1031', 'fac-kana-k1031', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ミ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"mi","accepted":["mi"]}'::jsonb),
  ('ep-kana-k1032', 'fac-kana-k1032', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ム","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"mu","accepted":["mu"]}'::jsonb),
  ('ep-kana-k1033', 'fac-kana-k1033', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"メ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"me","accepted":["me"]}'::jsonb),
  ('ep-kana-k1034', 'fac-kana-k1034', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"モ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"mo","accepted":["mo"]}'::jsonb),
  ('ep-kana-k1035', 'fac-kana-k1035', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヤ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ya","accepted":["ya"]}'::jsonb),
  ('ep-kana-k1036', 'fac-kana-k1036', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ユ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"yu","accepted":["yu"]}'::jsonb),
  ('ep-kana-k1037', 'fac-kana-k1037', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヨ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"yo","accepted":["yo"]}'::jsonb),
  ('ep-kana-k1038', 'fac-kana-k1038', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ラ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ra","accepted":["ra"]}'::jsonb),
  ('ep-kana-k1039', 'fac-kana-k1039', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"リ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ri","accepted":["ri"]}'::jsonb),
  ('ep-kana-k1040', 'fac-kana-k1040', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ル","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ru","accepted":["ru"]}'::jsonb),
  ('ep-kana-k1041', 'fac-kana-k1041', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"レ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"re","accepted":["re"]}'::jsonb),
  ('ep-kana-k1042', 'fac-kana-k1042', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ロ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ro","accepted":["ro"]}'::jsonb),
  ('ep-kana-k1043', 'fac-kana-k1043', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ワ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"wa","accepted":["wa"]}'::jsonb),
  ('ep-kana-k1044', 'fac-kana-k1044', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヲ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"wo","accepted":["wo","o"]}'::jsonb),
  ('ep-kana-k1045', 'fac-kana-k1045', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ン","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"n","accepted":["n","nn"]}'::jsonb),
  ('ep-kana-k1046', 'fac-kana-k1046', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ガ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ga","accepted":["ga"]}'::jsonb),
  ('ep-kana-k1047', 'fac-kana-k1047', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ギ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"gi","accepted":["gi"]}'::jsonb),
  ('ep-kana-k1048', 'fac-kana-k1048', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"グ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"gu","accepted":["gu"]}'::jsonb),
  ('ep-kana-k1049', 'fac-kana-k1049', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ゲ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ge","accepted":["ge"]}'::jsonb),
  ('ep-kana-k1050', 'fac-kana-k1050', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ゴ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"go","accepted":["go"]}'::jsonb),
  ('ep-kana-k1051', 'fac-kana-k1051', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ザ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"za","accepted":["za"]}'::jsonb),
  ('ep-kana-k1052', 'fac-kana-k1052', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ジ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ji","accepted":["ji","zi","di"]}'::jsonb),
  ('ep-kana-k1053', 'fac-kana-k1053', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ズ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"zu","accepted":["zu","du"]}'::jsonb),
  ('ep-kana-k1054', 'fac-kana-k1054', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ゼ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ze","accepted":["ze"]}'::jsonb),
  ('ep-kana-k1055', 'fac-kana-k1055', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ゾ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"zo","accepted":["zo"]}'::jsonb),
  ('ep-kana-k1056', 'fac-kana-k1056', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ダ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"da","accepted":["da"]}'::jsonb),
  ('ep-kana-k1057', 'fac-kana-k1057', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヂ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ji","accepted":["ji","zi","di"]}'::jsonb),
  ('ep-kana-k1058', 'fac-kana-k1058', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ヅ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"zu","accepted":["zu","du"]}'::jsonb),
  ('ep-kana-k1059', 'fac-kana-k1059', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"デ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"de","accepted":["de"]}'::jsonb),
  ('ep-kana-k1060', 'fac-kana-k1060', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ド","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"do","accepted":["do"]}'::jsonb),
  ('ep-kana-k1061', 'fac-kana-k1061', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"バ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"ba","accepted":["ba"]}'::jsonb),
  ('ep-kana-k1062', 'fac-kana-k1062', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ビ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"bi","accepted":["bi"]}'::jsonb),
  ('ep-kana-k1063', 'fac-kana-k1063', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ブ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"bu","accepted":["bu"]}'::jsonb),
  ('ep-kana-k1064', 'fac-kana-k1064', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ベ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"be","accepted":["be"]}'::jsonb),
  ('ep-kana-k1065', 'fac-kana-k1065', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ボ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"bo","accepted":["bo"]}'::jsonb),
  ('ep-kana-k1066', 'fac-kana-k1066', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"パ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pa","accepted":["pa"]}'::jsonb),
  ('ep-kana-k1067', 'fac-kana-k1067', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ピ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pi","accepted":["pi"]}'::jsonb),
  ('ep-kana-k1068', 'fac-kana-k1068', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"プ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pu","accepted":["pu"]}'::jsonb),
  ('ep-kana-k1069', 'fac-kana-k1069', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ペ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"pe","accepted":["pe"]}'::jsonb),
  ('ep-kana-k1070', 'fac-kana-k1070', 'tpl-kana-romaji', 'lang-ja', '{"kind":"kana","script":"katakana","character":"ポ","instruction":"Type the sound in romaji"}'::jsonb, '{"primary":"po","accepted":["po"]}'::jsonb)
ON CONFLICT (facet_id, template_id, version) DO NOTHING;
