-- N5 grammar, part two.
--
-- Same rules as 009: every word authored here, nothing imported, everything
-- 'in-review' until a human signs it off.
--
-- On citations: `quote` is left NULL wherever the supporting text has not been
-- transcribed from the source in hand. A locator points a reviewer at where to
-- check; an invented quotation attributed to a named scholar would be exactly
-- the failure this layer exists to prevent, and is worse than no citation.

INSERT INTO grammar_points
  (id, language_id, slug, title, pattern, level_id, category, register, meaning_short, meaning_long, nuance, status, published, sort_index) VALUES
  ('gp-de-location', 'lang-ja', 'de-location', 'で (place of action)', 'Place + で', 'lvl-ja-n5', 'particle', 'casual', 'Marks where an action happens.', '公園で遊びます "play in the park". Contrast に, which marks where something exists or is going: 公園にいます "am in the park".', 'The split is action versus existence. If a verb does something, the place takes で; if it only sits there, the place takes に. This one distinction accounts for most early particle errors.', 'in-review', true, 20),
  ('gp-de-means', 'lang-ja', 'de-means', 'で (by means of)', 'Noun + で', 'lvl-ja-n5', 'particle', 'casual', 'Marks a tool, method or material.', 'バスで行きます "go by bus", はしで食べます "eat with chopsticks", 日本語で話します "speak in Japanese".', 'Same particle as the place-of-action で, and not a coincidence: both answer "in what circumstance did this happen". Japanese treats setting and instrument as one idea.', 'in-review', true, 21),
  ('gp-he-direction', 'lang-ja', 'he-direction', 'へ (toward)', 'Place + へ', 'lvl-ja-n5', 'particle', 'casual', 'Marks direction of movement.', '東京へ行きます "head toward Tokyo". Written へ, pronounced え.', 'へ emphasises the heading; に emphasises arrival. 東京に行く says you got there, 東京へ行く says you set off that way — a difference English does not mark at all.', 'in-review', true, 22),
  ('gp-to-with', 'lang-ja', 'to-with', 'と (with / and)', 'Noun + と', 'lvl-ja-n5', 'particle', 'casual', 'Joins nouns exhaustively, or marks who you do something with.', '本とノート "a book and a notebook" — and nothing else. 友だちと行きます "go with a friend".', 'と is the exhaustive list. If the list is only examples, use や instead; choosing と when you meant や claims a completeness you did not intend.', 'in-review', true, 23),
  ('gp-ya-particle', 'lang-ja', 'ya-particle', 'や (and, among others)', 'Noun + や + Noun', 'lvl-ja-n5', 'particle', 'casual', 'Joins nouns as examples, not a complete list.', '本やノートがあります "there are books and notebooks, among other things". Often closes with など.', 'The unstated "and so on" is the whole point. や is how Japanese avoids claiming a list is complete.', 'in-review', true, 24),
  ('gp-ga-but', 'lang-ja', 'ga-but', '〜が (but)', 'Clause + が', 'lvl-ja-n5', 'conjunction', 'polite', 'Joins two clauses with mild contrast.', '高いですが、おいしいです "it is expensive, but tasty".', 'Frequently softens rather than contrasts: すみませんが… opens a request by trailing off. The contrast is a courtesy, not an objection.', 'in-review', true, 25),
  ('gp-kedo', 'lang-ja', 'kedo', '〜けど (but)', 'Clause + けど', 'lvl-ja-n5', 'conjunction', 'casual', 'Casual "but".', '行きたいけど、時間がない "I want to go, but I have no time". けれど and けれども are progressively more formal.', 'Like が, けど often just softens. Ending a sentence on けど leaves the objection unsaid, which is frequently the polite thing to do.', 'in-review', true, 26),
  ('gp-kara-made', 'lang-ja', 'kara-made', '〜から〜まで', 'A + から + B + まで', 'lvl-ja-n5', 'construction', 'casual', 'From A to B, in time or space.', '九時から五時まで "from nine to five", 東京から大阪まで "from Tokyo to Osaka".', 'まで is inclusive — it means "up to and including". For a deadline meaning "by", use までに, which is a different pattern learners routinely conflate.', 'in-review', true, 27),
  ('gp-yori', 'lang-ja', 'yori', '〜より (than)', 'A は B より + adjective', 'lvl-ja-n5', 'particle', 'casual', 'Marks the thing compared against.', '電車はバスより速いです "the train is faster than the bus".', 'より attaches to the LOSER of the comparison, which is the reverse of where English puts "than" mentally. Getting this backwards inverts the sentence.', 'in-review', true, 28),
  ('gp-hou-ga', 'lang-ja', 'hou-ga', '〜ほうが', 'A の ほうが + adjective', 'lvl-ja-n5', 'construction', 'casual', 'Marks the preferred or greater of two options.', '電車のほうが速いです "the train is the faster one". Pairs with より: バスより電車のほうが速い.', '方 literally means "side" or "direction", so the phrase is "the train side is faster" — Japanese compares by pointing at a side rather than inflecting the adjective.', 'in-review', true, 29),
  ('gp-i-adjective', 'lang-ja', 'i-adjective', 'い-adjectives', 'Adjective + い', 'lvl-ja-n5', 'construction', 'casual', 'Adjectives that conjugate on their own.', '高い → 高くない → 高かった → 高くなかった. They attach directly to a noun: 高い本.', 'い-adjectives carry their own tense, so 高いでした is wrong — です adds politeness, never past. The adjective has already done that job.', 'in-review', true, 30),
  ('gp-na-adjective', 'lang-ja', 'na-adjective', 'な-adjectives', 'Adjective + な + Noun', 'lvl-ja-n5', 'construction', 'casual', 'Adjectives that behave like nouns.', '静かな部屋 "a quiet room". Predicatively they take だ/です: 静かです. Past: 静かでした.', 'These are nouns wearing an adjective''s coat. That is why they need な to modify a noun and borrow the copula for tense, while い-adjectives need neither.', 'in-review', true, 31),
  ('gp-masen-ka', 'lang-ja', 'masen-ka', '〜ませんか', 'Verb stem + ませんか', 'lvl-ja-n5', 'expression', 'polite', 'Invitation — "won''t you…?"', '一緒に行きませんか "won''t you go with me?"', 'Phrased as a negative question because it leaves room to decline. ましょう assumes agreement; ませんか asks for it.', 'in-review', true, 32),
  ('gp-naide-kudasai', 'lang-ja', 'naide-kudasai', '〜ないでください', 'Verb-ない + でください', 'lvl-ja-n5', 'expression', 'polite', 'Polite negative request — "please don''t".', '入らないでください "please do not enter".', 'Softer than 〜てはいけません, which forbids. This asks; that rules.', 'in-review', true, 33),
  ('gp-ta-koto-ga-aru', 'lang-ja', 'ta-koto-ga-aru', '〜たことがある', 'Verb-た + ことがある', 'lvl-ja-n5', 'construction', 'casual', 'Experience — "have done X before".', '日本に行ったことがあります "I have been to Japan".', 'Experience, not past tense. 日本に行きました says you went; 行ったことがある says it is among the things you have done. Not usable for something that happened once, recently.', 'in-review', true, 34),
  ('gp-nagara', 'lang-ja', 'nagara', '〜ながら', 'Verb stem + ながら', 'lvl-ja-n5', 'conjunction', 'casual', 'Doing two things at once.', '音楽を聞きながら勉強します "study while listening to music".', 'The ながら clause is the BACKGROUND action; the main verb is the point. Swap them and you have changed what the sentence is about.', 'in-review', true, 35),
  ('gp-mae-ni', 'lang-ja', 'mae-ni', '〜前に', 'Verb (dictionary) + 前に', 'lvl-ja-n5', 'construction', 'casual', 'Before doing something.', '寝る前に本を読みます "I read before sleeping". With a noun: 食事の前に.', 'Always the DICTIONARY form, even when the sentence is past: 寝る前に読みました. The 前に fixes the order, so the verb needs no tense of its own.', 'in-review', true, 36),
  ('gp-ato-de', 'lang-ja', 'ato-de', '〜後で', 'Verb-た + 後で', 'lvl-ja-n5', 'construction', 'casual', 'After doing something.', '食べた後で出かけます "I will go out after eating".', 'Mirror image of 前に: 後で takes the TA-form, 前に takes the dictionary form. The tense sits on whichever side has already happened.', 'in-review', true, 37),
  ('gp-toki', 'lang-ja', 'toki', '〜とき', 'Clause + とき', 'lvl-ja-n5', 'construction', 'casual', 'When — the time at which something happens.', '子どものとき "when I was a child", 日本に行くとき "when I go to Japan".', 'The tense before とき says whether the action was complete AT that time, not when it happened overall. 行くとき is before departure; 行ったとき is after arrival.', 'in-review', true, 38),
  ('gp-tara', 'lang-ja', 'tara', '〜たら', 'Verb-た + ら', 'lvl-ja-n5', 'construction', 'casual', 'If / when — the general-purpose conditional.', '雨が降ったら、行きません "if it rains, I will not go".', 'The most flexible of the conditionals and the safest default at N5. It allows a request or a command after it, which ば and と do not.', 'in-review', true, 39),
  ('gp-naru', 'lang-ja', 'naru', '〜になる / 〜くなる', 'Noun+に / Adj-く + なる', 'lvl-ja-n5', 'construction', 'casual', 'Become.', '先生になります "become a teacher", 寒くなりました "it has got cold".', 'Japanese prefers なる where English prefers "make": 便利になった "it became convenient" is far more natural than saying someone made it so. The change is described, not attributed.', 'in-review', true, 40),
  ('gp-sugiru', 'lang-ja', 'sugiru', '〜すぎる', 'Verb stem / Adj stem + すぎる', 'lvl-ja-n5', 'auxiliary', 'casual', 'Too much.', '食べすぎました "I ate too much", 高すぎる "too expensive".', 'Always negative in tone. すぎる is a complaint, so it does not translate a neutral "very".', 'in-review', true, 41),
  ('gp-tsumori', 'lang-ja', 'tsumori', '〜つもり', 'Verb (dictionary) + つもりです', 'lvl-ja-n5', 'expression', 'polite', 'Intention — "I plan to".', '来年、日本に行くつもりです "I intend to go to Japan next year".', 'A settled intention, not a wish. For something merely hoped for, たい is the honest word.', 'in-review', true, 42),
  ('gp-deshou', 'lang-ja', 'deshou', '〜でしょう', 'Plain form + でしょう', 'lvl-ja-n5', 'auxiliary', 'polite', 'Probably — a guess.', '明日は雨でしょう "it will probably rain tomorrow".', 'With rising intonation it seeks agreement instead: 高いでしょう？ "expensive, isn''t it?" Same word, opposite direction of travel.', 'in-review', true, 43),
  ('gp-kosoado', 'lang-ja', 'kosoado', 'これ・それ・あれ・どれ', 'こ / そ / あ / ど + れ', 'lvl-ja-n5', 'construction', 'casual', 'This, that, that over there, which.', 'これ (near me), それ (near you), あれ (near neither), どれ (which). The same roots give ここ/そこ, この/その, こんな/そんな.', 'Three distances, not two. English collapses それ and あれ into "that", which is why learners reach for あれ when they mean the thing in the listener''s hand.', 'in-review', true, 44),
  ('gp-suki', 'lang-ja', 'suki', '〜が好き', 'Noun + が + 好き', 'lvl-ja-n5', 'expression', 'casual', 'Like something.', '音楽が好きです "I like music". Negative: 好きじゃありません.', '好き is an adjective, not a verb, so the thing liked takes が rather than を. "I like it" is closer to "it is likeable to me".', 'in-review', true, 45),
  ('gp-te-kara', 'lang-ja', 'te-kara', '〜てから', 'Verb-て + から', 'lvl-ja-n5', 'construction', 'casual', 'After doing — and then.', '仕事が終わってから、映画を見ます "after work finishes, I will watch a film".', 'Stresses sequence more strongly than the plain て-form: てから says the first thing must finish before the second starts.', 'in-review', true, 46),
  ('gp-node', 'lang-ja', 'node', '〜ので (because)', 'Plain form + ので', 'lvl-ja-n5', 'conjunction', 'polite', 'Gives a reason, softly.', '時間がないので、失礼します "as I have no time, I will excuse myself".', 'から states your reasoning; ので presents a circumstance. That is why excuses and requests reach for ので — it sounds less like an argument.', 'in-review', true, 47),
  ('gp-dake', 'lang-ja', 'dake', '〜だけ (only)', 'Noun / Verb + だけ', 'lvl-ja-n5', 'particle', 'casual', 'Only, just.', '一つだけください "just one, please".', 'Neutral about whether that is enough. しか〜ない carries the disappointment; だけ merely counts.', 'in-review', true, 48),
  ('gp-shika-nai', 'lang-ja', 'shika-nai', '〜しか〜ない', 'Noun + しか + negative', 'lvl-ja-n5', 'construction', 'casual', 'Only — and not enough.', '百円しかありません "I only have a hundred yen".', 'Requires a negative verb, which is what carries the sense of shortfall. だけ states a quantity; しか regrets it.', 'in-review', true, 49)
ON CONFLICT (language_id, slug) DO NOTHING;
