-- N4 grammar, part one: forms the language builds on.
--
-- Same rules as 009: the JLPT point LIST is a fact about the exam, every word
-- of the prose is written for this app, and nothing here is imported. Points
-- ship `published` so the level is usable, at status 'in-review' until a human
-- signs each one off.
--
-- Seven points a standard N4 list carries are deliberately absent from these
-- two files: dake, nagara, shika-nai, sugiru, ta-koto-ga-aru, toki and tsumori.
-- All seven are already taught at N5 in 011, and (language_id, slug) is unique,
-- so restating them here would be seven rows that silently never insert.
--
-- sort_index continues from N5 (which ends at 49) at 100, so the two levels
-- never collide and the ordering stays stable if N5 grows.

INSERT INTO grammar_points
  (id, language_id, slug, title, pattern, level_id, category, register, meaning_short, meaning_long, nuance, status, published, sort_index) VALUES
  ('gp-potential', 'lang-ja', 'potential', '可能形 (potential)', 'Verb → 〜える / 〜られる', 'lvl-ja-n4', 'construction', 'casual', 'Can do, or is able to be done.', '五段 verbs shift the final -u to -eru: 書く → 書ける, 飲む → 飲める. 一段 verbs take られる: 食べる → 食べられる. する → できる, 来る → 来られる.', 'The object of a potential verb usually takes が, not を: 日本語が話せます. The verb has stopped describing an action and started describing a capability, and capabilities are states.', 'in-review', true, 100),
  ('gp-ra-nuki', 'lang-ja', 'ra-nuki', 'ら抜き言葉', '食べられる → 食べれる', 'lvl-ja-n4', 'construction', 'casual', 'The dropped-ら potential heard in speech.', 'Colloquially the ら is dropped from 一段 potentials: 食べられる → 食べれる, 見られる → 見れる. Widespread in speech, still marked as incorrect in writing and on the exam.', 'It is not laziness but a repair: 食べられる is potential AND passive AND honorific at once. Dropping ら gives the potential a form of its own, which is exactly the ambiguity the standard language leaves unresolved.', 'in-review', true, 101),
  ('gp-volitional', 'lang-ja', 'volitional', '意向形 (volitional)', 'Verb → 〜おう / 〜よう', 'lvl-ja-n4', 'construction', 'casual', 'Let''s, or I think I''ll.', '五段 shift -u to -ou: 行く → 行こう. 一段 take よう: 食べる → 食べよう. する → しよう, 来る → 来よう. The polite equivalent is ましょう.', 'Alone it is a proposal to whoever is present. With と思う it becomes a decision you have reached yourself: 行こうと思う, "I''ve decided to go".', 'in-review', true, 102),
  ('gp-passive', 'lang-ja', 'passive', '受身形 (passive)', 'Verb → 〜れる / 〜られる', 'lvl-ja-n4', 'construction', 'casual', 'Something is done to the subject.', '五段 shift -u to -areru: 読む → 読まれる. 一段 take られる: 見る → 見られる. する → される, 来る → 来られる. The agent takes に.', 'Japanese also has the "suffering passive", which English cannot do: 雨に降られた, "I was rained on". The verb is intransitive, so there is no object to promote — the passive is marking that it happened TO you.', 'in-review', true, 103),
  ('gp-causative', 'lang-ja', 'causative', '使役形 (causative)', 'Verb → 〜せる / 〜させる', 'lvl-ja-n4', 'construction', 'casual', 'Make or let someone do something.', '五段 shift -u to -aseru: 行く → 行かせる. 一段 take させる: 食べる → 食べさせる. The person made to act takes に or を.', 'に and を are not interchangeable: 子どもを行かせる makes them go, 子どもに行かせる lets them. The particle carries the whole difference between coercion and permission.', 'in-review', true, 104),
  ('gp-causative-passive', 'lang-ja', 'causative-passive', '使役受身 (causative-passive)', 'Verb → 〜させられる', 'lvl-ja-n4', 'construction', 'casual', 'Made to do something, unwillingly.', 'Causative first, then passive: 行く → 行かせる → 行かせられる (contracted 行かされる). 一段: 食べる → 食べさせられる.', 'It nearly always carries reluctance. 待たされた does not just report that you waited — it complains about it.', 'in-review', true, 105),
  ('gp-to-conditional', 'lang-ja', 'to-conditional', '〜と (conditional)', 'Plain form + と', 'lvl-ja-n4', 'conjunction', 'casual', 'Whenever A, B follows — an automatic result.', '春になると花が咲く. The consequence is inevitable, not chosen, which is why と suits natural laws, machines and directions.', 'と cannot be followed by a request, an invitation or an intention. "If you go, please buy…" is ungrammatical with と, because と rules out anyone deciding anything.', 'in-review', true, 106),
  ('gp-ba-conditional', 'lang-ja', 'ba-conditional', '〜ば (conditional)', 'Verb-ば', 'lvl-ja-n4', 'conjunction', 'casual', 'If A, then B — a general condition.', '行く → 行けば, 食べる → 食べれば, 安い → 安ければ, 学生 → 学生ならば. Negative: 行かなければ.', 'ば is the conditional of general truths and hypotheticals. Where と is automatic and たら is one occasion, ば is the "if" of proverbs: 塵も積もれば山となる.', 'in-review', true, 107),
  ('gp-tara-conditional', 'lang-ja', 'tara-conditional', '〜たら (conditional)', 'Verb-た + ら', 'lvl-ja-n4', 'conjunction', 'casual', 'If / when A happens, B — one specific occasion.', 'Built on the た-form: 食べたら, 行ったら, 高かったら. It is the most flexible of the four conditionals and the safest choice in speech.', 'Because it is built on た, たら always looks at B from a point where A is already finished. That is why it accepts requests and intentions that と rejects: 着いたら電話してください.', 'in-review', true, 108),
  ('gp-nara-conditional', 'lang-ja', 'nara-conditional', '〜なら (conditional)', 'Noun / plain form + なら', 'lvl-ja-n4', 'conjunction', 'casual', 'If that''s the case — picking up what was just said.', '日本に行くなら、京都がいいですよ. Attaches directly to a noun with no だ.', 'なら responds. It takes something the other person has just raised and builds on it, which is why it so often opens advice. The other three conditionals can start a conversation; なら usually cannot.', 'in-review', true, 109),
  ('gp-tari-tari', 'lang-ja', 'tari-tari', '〜たり〜たりする', 'Verb-た + り', 'lvl-ja-n4', 'construction', 'casual', 'Doing things like A and B.', '週末は本を読んだり、映画を見たりします. Formed from the た-form plus り, closed with する.', 'The list is representative, not exhaustive — it means "among other things". て-form chaining lists everything in order; たり deliberately does not.', 'in-review', true, 111),
  ('gp-koto-ga-dekiru', 'lang-ja', 'koto-ga-dekiru', '〜ことができる', 'Plain form + ことができる', 'lvl-ja-n4', 'expression', 'polite', 'Can do — the formal way to say it.', '日本語を話すことができます. Interchangeable with the potential form in meaning.', 'Longer, more formal, and it keeps を on the object where the potential form prefers が. Written notices and public signs favour it for exactly that stiffness.', 'in-review', true, 112),
  ('gp-ru-koto-ga-aru', 'lang-ja', 'ru-koto-ga-aru', '〜ことがある', 'Plain present + ことがある', 'lvl-ja-n4', 'expression', 'casual', 'There are times when — occasional occurrence.', '朝ごはんを食べないことがあります, "there are times I skip breakfast".', 'The same shape as 〜たことがある, but the tense of the verb changes it completely: た gives experience, plain present gives frequency.', 'in-review', true, 114),
  ('gp-yotei', 'lang-ja', 'yotei', '〜予定', 'Plain form / Noun の + 予定', 'lvl-ja-n4', 'expression', 'polite', 'Scheduled to.', '三時に会議をする予定です. Also as a noun: 明日の予定.', 'A 予定 exists independently of you wanting it. It is what the diary says, which is why it sounds neutral where つもり sounds personal.', 'in-review', true, 116),
  ('gp-sou-hearsay', 'lang-ja', 'sou-hearsay', '〜そうだ (hearsay)', 'Plain form + そうだ', 'lvl-ja-n4', 'auxiliary', 'casual', 'I hear that / apparently.', '雨が降るそうです. Attaches to the plain form, including だ: 学生だそうです.', 'Reports without judging. The speaker takes no responsibility for whether it is true — which is exactly what distinguishes it from ようだ, where the speaker is drawing their own conclusion.', 'in-review', true, 117),
  ('gp-sou-appearance', 'lang-ja', 'sou-appearance', '〜そうだ (appearance)', 'Verb stem / Adj stem + そうだ', 'lvl-ja-n4', 'auxiliary', 'casual', 'Looks like it''s about to, or looks that way.', '雨が降りそうです, おいしそうです. Drops the final い of an i-adjective. いい → よさそう, ない → なさそう are irregular.', 'The attachment point is the whole difference: full plain form + そうだ is hearsay, bare stem + そうだ is what your own eyes report. 降るそうだ is what you were told; 降りそうだ is the sky.', 'in-review', true, 118),
  ('gp-you-da', 'lang-ja', 'you-da', '〜ようだ', 'Plain form / Noun の + ようだ', 'lvl-ja-n4', 'auxiliary', 'polite', 'It seems — a conclusion from evidence.', '誰かいるようです. Also makes similes: 夢のようだ, "like a dream".', 'ようだ is the speaker''s own inference from something they can point to. らしい leans on outside information, そうだ (hearsay) simply passes it on.', 'in-review', true, 119),
  ('gp-rashii', 'lang-ja', 'rashii', '〜らしい', 'Plain form / Noun + らしい', 'lvl-ja-n4', 'auxiliary', 'casual', 'Seems / apparently, on the strength of what others say.', '彼は来ないらしい. A second use is "typical of": 男らしい, 春らしい一日.', 'The two uses share a logic: both say something matches what is expected of its type. 春らしい日 is a day behaving as spring should.', 'in-review', true, 120),
  ('gp-mitai', 'lang-ja', 'mitai', '〜みたい', 'Plain form / Noun + みたい', 'lvl-ja-n4', 'auxiliary', 'casual', 'Looks like — the casual ようだ.', '雨みたいです, 子どもみたいに笑う. Attaches straight to a noun with no の.', 'Same job as ようだ, spoken register. Written Japanese and formal speech keep ようだ; conversation almost always reaches for みたい.', 'in-review', true, 121),
  ('gp-hazu', 'lang-ja', 'hazu', '〜はず', 'Plain form + はず', 'lvl-ja-n4', 'expression', 'casual', 'Ought to be — expectation on grounds.', '彼は今日来るはずです. Denial: 〜はずがない, "there''s no way".', 'はず is reasoning, not hope. It says the conclusion follows from what you know, which is why はずだったのに carries such disappointment: the reasoning was sound and reality disagreed.', 'in-review', true, 122),
  ('gp-kamoshirenai', 'lang-ja', 'kamoshirenai', '〜かもしれない', 'Plain form + かもしれない', 'lvl-ja-n4', 'expression', 'casual', 'Might, may.', '雨が降るかもしれません. Casual: 〜かも.', 'Literally "one cannot know whether". It is genuinely uncertain — weaker than でしょう and far weaker than はず.', 'in-review', true, 123),
  ('gp-darou', 'lang-ja', 'darou', '〜だろう / でしょう', 'Plain form + だろう', 'lvl-ja-n4', 'auxiliary', 'casual', 'Probably.', '明日は晴れるでしょう. でしょう is the polite form.', 'With rising intonation it stops guessing and starts seeking agreement: 行くでしょう？ is closer to "you''re going, right?". Weather forecasts use it constantly for the plain probability sense.', 'in-review', true, 124),
  ('gp-to-omou', 'lang-ja', 'to-omou', '〜と思う', 'Plain form + と思う', 'lvl-ja-n4', 'expression', 'casual', 'I think that.', '彼は正しいと思います. と marks the quoted thought, so the clause before it stays plain even when the sentence is polite.', 'Japanese is strict about whose mind it is. 思う reports your own thought; for someone else you need 思っている, because you can only observe another person thinking, not do it.', 'in-review', true, 125),
  ('gp-to-iu', 'lang-ja', 'to-iu', '〜という', 'X + という + Noun', 'lvl-ja-n4', 'expression', 'casual', 'Called, named — or "the fact that".', '田中という人, 東京という町. Also introduces a clause as a noun: 彼が来るということ.', 'It names something the listener may not know yet. Using it about something obviously familiar sounds distancing, as if you doubt they''ve heard of it.', 'in-review', true, 126),
  ('gp-ka-dou-ka', 'lang-ja', 'ka-dou-ka', '〜かどうか', 'Plain form + かどうか', 'lvl-ja-n4', 'expression', 'casual', 'Whether or not.', '行くかどうか分かりません. With a question word, か alone is enough: 誰が来るか分かりません.', 'かどうか is for yes/no questions only. A question word already supplies the alternatives, so どうか becomes redundant.', 'in-review', true, 127),
  ('gp-te-ageru', 'lang-ja', 'te-ageru', '〜てあげる', 'Verb-て + あげる', 'lvl-ja-n4', 'expression', 'casual', 'Do something for someone else.', '友だちに本を貸してあげました. Humble: 〜てさしあげる.', 'Said to the person''s face it can sound condescending — it announces that you did them a favour. Japanese usually leaves the kindness unstated, or recasts it with もらう.', 'in-review', true, 128),
  ('gp-te-kureru', 'lang-ja', 'te-kureru', '〜てくれる', 'Verb-て + くれる', 'lvl-ja-n4', 'expression', 'casual', 'Someone does something for me.', '友だちが手伝ってくれました. Honorific: 〜てくださる.', 'くれる only ever points inward, toward the speaker or the speaker''s side. That direction is fixed by the verb itself, which is why the recipient can go unsaid.', 'in-review', true, 129),
  ('gp-te-morau', 'lang-ja', 'te-morau', '〜てもらう', 'Verb-て + もらう', 'lvl-ja-n4', 'expression', 'casual', 'Have someone do something for you.', '先生に教えてもらいました. Humble: 〜ていただく.', 'Same event as くれる, told from the other end: くれる makes the giver the subject, もらう makes the receiver the subject. Which you choose says whose side the sentence is standing on.', 'in-review', true, 130),
  ('gp-te-oku', 'lang-ja', 'te-oku', '〜ておく', 'Verb-て + おく', 'lvl-ja-n4', 'expression', 'casual', 'Do something in advance, and leave it done.', '会議の前に資料を読んでおきます. Contracts to 〜とく in speech.', 'From 置く, "to put". The action is placed somewhere ready — preparation whose result is meant to stay put until it is needed.', 'in-review', true, 131),
  ('gp-te-shimau', 'lang-ja', 'te-shimau', '〜てしまう', 'Verb-て + しまう', 'lvl-ja-n4', 'expression', 'casual', 'Finish completely — or do something regrettable.', '宿題をしてしまいました. Contracts to 〜ちゃう / 〜じゃう.', 'The two senses are one idea: the action is beyond taking back. Whether that is satisfying or regrettable depends entirely on what was done.', 'in-review', true, 132),
  ('gp-te-miru', 'lang-ja', 'te-miru', '〜てみる', 'Verb-て + みる', 'lvl-ja-n4', 'expression', 'casual', 'Try doing something and see.', '食べてみてください. Written in kana — the 見 is no longer literal.', 'It is trying in order to find out, not trying in order to manage. For attempting something difficult, 〜ようとする is the right pattern.', 'in-review', true, 133)
ON CONFLICT (language_id, slug) DO NOTHING;
