-- N4 grammar, part two: connectors, limits, and the first of the polite forms.
-- Continues the numbering from 015.

INSERT INTO grammar_points
  (id, language_id, slug, title, pattern, level_id, category, register, meaning_short, meaning_long, nuance, status, published, sort_index) VALUES
  ('gp-te-iku-kuru', 'lang-ja', 'te-iku-kuru', '〜ていく / 〜てくる', 'Verb-て + いく / くる', 'lvl-ja-n4', 'expression', 'casual', 'A change moving away from, or toward, now.', '寒くなっていく, "it will keep getting colder". 寒くなってきた, "it has been getting colder".', 'The pair is a timeline with the speaker standing at the present. くる brings the change up to now; いく carries it onward from now. Physical motion is only the most literal case.', 'in-review', true, 134),
  ('gp-te-aru', 'lang-ja', 'te-aru', '〜てある', 'Verb-て + ある', 'lvl-ja-n4', 'expression', 'casual', 'Something has been done and is left that way.', '窓が開けてあります, "the window has been opened (and left open)".', 'Contrast 開いている, which merely reports the window is open. てある says a person did it on purpose — the intention survives in the state.', 'in-review', true, 135),
  ('gp-tame-ni', 'lang-ja', 'tame-ni', '〜ために', 'Plain form / Noun の + ために', 'lvl-ja-n4', 'conjunction', 'casual', 'In order to, or for the sake of.', '日本語を勉強するために、日本に来ました. With a noun: 家族のために.', 'ために needs the same person to control both halves and needs the verb to be volitional. For something you cannot directly will — being able to, not forgetting — ように is the pattern.', 'in-review', true, 136),
  ('gp-you-ni-purpose', 'lang-ja', 'you-ni-purpose', '〜ように (purpose)', 'Plain form + ように', 'lvl-ja-n4', 'conjunction', 'casual', 'So that — for an outcome you cannot simply decide.', '見えるように、大きく書きました. Usually with a potential, a negative, or an intransitive verb.', 'ように aims at a result; ために aims at an action. You can decide to study, so ために fits; you cannot decide to be able to hear, so ように does.', 'in-review', true, 137),
  ('gp-you-ni-naru', 'lang-ja', 'you-ni-naru', '〜ようになる', 'Plain form + ようになる', 'lvl-ja-n4', 'expression', 'casual', 'Reach the point of doing something.', '日本語が話せるようになりました, "I have got to where I can speak Japanese".', 'It marks a change that has completed, most often paired with the potential. なる is the language''s general verb for things turning out a certain way rather than being made to.', 'in-review', true, 138),
  ('gp-you-ni-suru', 'lang-ja', 'you-ni-suru', '〜ようにする', 'Plain form + ようにする', 'lvl-ja-n4', 'expression', 'casual', 'Make a point of doing something.', '毎日運動するようにしています, "I try to exercise every day".', 'する against なる: ようにする is effort you are making, ようになる is a change that has happened to you. The ている form is what turns the effort into an ongoing habit.', 'in-review', true, 139),
  ('gp-yasui-nikui', 'lang-ja', 'yasui-nikui', '〜やすい / 〜にくい', 'Verb stem + やすい / にくい', 'lvl-ja-n4', 'auxiliary', 'casual', 'Easy to / hard to do.', 'この本は読みやすい. Both conjugate as i-adjectives.', 'It describes the THING, not the person. 読みやすい本 is a book that is easy to read for anyone — for your own ability the potential form is what you want.', 'in-review', true, 141),
  ('gp-kata', 'lang-ja', 'kata', '〜方 (かた)', 'Verb stem + 方', 'lvl-ja-n4', 'construction', 'casual', 'The way of doing something.', '使い方, 作り方. The result is a noun, so を becomes の: 漢字の書き方.', 'The particle shift is the giveaway that the verb has become a noun. 漢字を書き方 is a common early mistake for exactly that reason.', 'in-review', true, 142),
  ('gp-hajimeru-owaru', 'lang-ja', 'hajimeru-owaru', '〜始める / 〜終わる / 〜続ける', 'Verb stem + 始める', 'lvl-ja-n4', 'auxiliary', 'casual', 'Start, finish, or keep doing something.', '読み始める, 読み終わる, 読み続ける. All attach to the ます-stem.', 'These are compound verbs, not auxiliaries — the pair behaves as a single verb and conjugates on the second half. 出す is a fourth: 降り出す, rain starting suddenly.', 'in-review', true, 143),
  ('gp-noni-although', 'lang-ja', 'noni-although', '〜のに (although)', 'Plain form + のに', 'lvl-ja-n4', 'conjunction', 'casual', 'Even though — with the speaker put out by it.', '勉強したのに、試験に落ちました. A noun or na-adjective takes な: 元気なのに.', 'のに carries feeling in a way が and けど do not: surprise, disappointment, reproach. A neutral contrast should use けど.', 'in-review', true, 144),
  ('gp-keredo', 'lang-ja', 'keredo', '〜けれど / けど', 'Plain or polite form + けれど', 'lvl-ja-n4', 'conjunction', 'casual', 'But, although.', '高いけれど、買います. けれども is the fullest form, けど the most casual.', 'Often it softens rather than contrasts: すみませんけど… opens a request by trailing off, leaving the listener to complete the thought.', 'in-review', true, 145),
  ('gp-temo', 'lang-ja', 'temo', '〜ても', 'Verb-て + も', 'lvl-ja-n4', 'conjunction', 'casual', 'Even if.', '雨が降っても行きます. Adjectives: 高くても. Nouns: 学生でも.', 'たら supposes a condition and follows it through; ても supposes one and dismisses it. It is the conditional that refuses to matter.', 'in-review', true, 146),
  ('gp-shi', 'lang-ja', 'shi', '〜し', 'Plain form + し', 'lvl-ja-n4', 'conjunction', 'casual', 'And what''s more — stacking reasons.', '安いし、おいしいし、この店にします.', 'し implies the list continues. One し on its own hints at a reason held back, which is why it can end a sentence and still be understood.', 'in-review', true, 147),
  ('gp-aida-ni', 'lang-ja', 'aida-ni', '〜間に', 'Plain form / Noun の + 間に', 'lvl-ja-n4', 'conjunction', 'casual', 'While — during a window.', '寝ている間に、地震がありました.', 'The に is doing real work: 間 spans the whole period, 間に picks a moment inside it. 留守の間 is the whole absence; 留守の間に is something that happened during it.', 'in-review', true, 148),
  ('gp-mae-ni-ato-de', 'lang-ja', 'mae-ni-ato-de', '〜前に / 〜後で', 'Plain present + 前に / Verb-た + 後で', 'lvl-ja-n4', 'conjunction', 'casual', 'Before / after doing something.', '食べる前に手を洗います. 食べた後で歯を磨きます.', 'The tense is fixed by the pattern, not by the sentence: 前に always takes the plain present and 後で always takes た, however long ago it all happened.', 'in-review', true, 149),
  ('gp-made-madeni', 'lang-ja', 'made-madeni', '〜まで / 〜までに', 'Noun / Plain form + まで', 'lvl-ja-n4', 'particle', 'casual', 'Until / by.', '五時まで待ちます. 五時までに来てください.', 'まで is continuous — something goes on up to that point. までに is a deadline. Waiting takes まで; arriving takes までに.', 'in-review', true, 151),
  ('gp-nakutemo-ii', 'lang-ja', 'nakutemo-ii', '〜なくてもいい', 'Verb-ない stem + くてもいい', 'lvl-ja-n4', 'expression', 'casual', 'Don''t have to.', '行かなくてもいいです.', 'It is 〜てもいい with a negative inside: "even if you don''t, it''s fine". Japanese lifts an obligation by permitting the absence rather than denying the duty.', 'in-review', true, 152),
  ('gp-nakucha', 'lang-ja', 'nakucha', '〜なくちゃ / 〜なきゃ', 'Verb-ない stem + くちゃ / きゃ', 'lvl-ja-n4', 'expression', 'casual', 'Gotta — casual obligation.', '行かなくちゃ. Contractions of なくては and なければ.', 'The rest of the sentence is simply dropped: なければならない loses ならない and the obligation survives in the fragment. Speech does this constantly, and the missing half is never actually missed.', 'in-review', true, 153),
  ('gp-bakari', 'lang-ja', 'bakari', '〜ばかり', 'Noun + ばかり / Verb-た + ばかり', 'lvl-ja-n4', 'particle', 'casual', 'Nothing but — or only just now.', 'ゲームばかりしている, "does nothing but play games". 来たばかり, "only just arrived".', 'The complaint sense usually implies too much of one thing. The た-form sense is subjective freshness: 三年前に始めたばかり is fine if three years still feels recent to you.', 'in-review', true, 156),
  ('gp-tokoro', 'lang-ja', 'tokoro', '〜ところ', 'Plain present / ている / た + ところ', 'lvl-ja-n4', 'expression', 'casual', 'Just about to, in the middle of, or just finished.', '食べるところ (about to), 食べているところ (mid-way), 食べたところ (just done).', 'ところ means "place", used here for a place in time. The verb form alone moves you from just-before to just-after.', 'in-review', true, 157),
  ('gp-baai', 'lang-ja', 'baai', '〜場合', 'Plain form / Noun の + 場合', 'lvl-ja-n4', 'expression', 'polite', 'In the case that.', '雨の場合は中止します.', 'The register of rules and notices. It supposes a situation the writer has planned for, which is why it reads coldly in conversation where たら would do.', 'in-review', true, 158),
  ('gp-o-ni-naru', 'lang-ja', 'o-ni-naru', 'お〜になる (respectful)', 'お + Verb stem + になる', 'lvl-ja-n4', 'expression', 'formal', 'Respectful form of someone else''s action.', '先生がお帰りになりました. Some verbs have dedicated forms instead: 行く → いらっしゃる, 言う → おっしゃる.', 'Respectful language raises the OTHER person. It is never used about yourself, and using it about your own company to an outsider is a classic mistake.', 'in-review', true, 159),
  ('gp-o-suru', 'lang-ja', 'o-suru', 'お〜する (humble)', 'お + Verb stem + する', 'lvl-ja-n4', 'expression', 'formal', 'Humble form of your own action.', 'お持ちします, "let me carry that". Dedicated forms: 言う → 申す, 行く → 参る.', 'Humble language lowers yourself, and lowering yourself raises the listener by the same distance. The two systems are one gesture seen from opposite ends.', 'in-review', true, 160),
  ('gp-meirei', 'lang-ja', 'meirei', '命令形 (imperative)', 'Verb → 〜え / 〜ろ', 'lvl-ja-n4', 'construction', 'casual', 'Blunt command.', '行く → 行け, 食べる → 食べろ. する → しろ, 来る → 来い.', 'Genuinely harsh, and rare in ordinary speech. It survives in signs, sport, and set phrases — 頑張れ is a shout of support, not an order.', 'in-review', true, 161),
  ('gp-kinshi-na', 'lang-ja', 'kinshi-na', '〜な (prohibition)', 'Plain present + な', 'lvl-ja-n4', 'particle', 'casual', 'Don''t.', '行くな, "don''t go".', 'Not to be confused with the softening な of 食べな, which is a clipped 食べなさい and means the opposite. The verb form separates them: plain present + な forbids, stem + な urges.', 'in-review', true, 162),
  ('gp-garu', 'lang-ja', 'garu', '〜がる', 'Adj stem + がる', 'lvl-ja-n4', 'auxiliary', 'casual', 'Shows signs of feeling something.', '弟は行きたがっている. 寒がる, 怖がる.', 'Japanese will not let you state another person''s inner state as fact. がる converts the feeling into observable behaviour, which you are allowed to report.', 'in-review', true, 163),
  ('gp-nominalise', 'lang-ja', 'nominalise', '〜こと / 〜の (nominalising)', 'Plain form + こと / の', 'lvl-ja-n4', 'construction', 'casual', 'Turns a clause into a noun.', '泳ぐことが好きです. 彼が来るのを見ました.', 'の is for something perceived directly — seeing, hearing, waiting. こと is for the abstract fact. 見る takes の because you watch an event, not a proposition.', 'in-review', true, 164),
  ('gp-gimonshi-ka', 'lang-ja', 'gimonshi-ka', '疑問詞 + か', '誰か / 何か / どこか', 'lvl-ja-n4', 'construction', 'casual', 'Some- : someone, something, somewhere.', '誰か来ました. With も and a negative it becomes none: 誰も来ません.', 'One particle sets the quantity: か is some, も with a negative is none, も with a positive is every — 何でも, anything at all.', 'in-review', true, 165),
  ('gp-you-to-suru', 'lang-ja', 'you-to-suru', '〜ようとする', 'Volitional + とする', 'lvl-ja-n4', 'expression', 'casual', 'Try to, or be about to.', '出かけようとしたとき、電話が鳴りました.', 'This is attempting something that may fail, which 〜てみる never means. てみる samples; ようとする strains.', 'in-review', true, 166),
  ('gp-sou-mo-nai', 'lang-ja', 'sou-mo-nai', '〜そうもない', 'Verb stem + そうもない', 'lvl-ja-n4', 'expression', 'casual', 'Doesn''t look like it will happen.', '雨がやみそうもない.', 'The negative of appearance-そう, and stronger than a plain negative: it says the evidence itself points the other way.', 'in-review', true, 167)
ON CONFLICT (language_id, slug) DO NOTHING;
