-- N3 grammar.
--
-- Same rules as 009 and 015: the point LIST is a fact about the exam, every
-- word of the prose is written for this app, nothing is imported, and each
-- point ships `published` at status 'in-review' until a human signs it off.
--
-- sort_index continues at 200. Points already taught at N5 or N4 are not
-- restated: (language_id, slug) is unique, so a duplicate row would silently
-- never insert.

INSERT INTO grammar_points
  (id, language_id, slug, title, pattern, level_id, category, register, meaning_short, meaning_long, nuance, status, published, sort_index) VALUES
  ('gp-beki', 'lang-ja', 'beki', '〜べき', 'Plain present + べき', 'lvl-ja-n3', 'expression', 'formal', 'Ought to — a moral or logical should.', '早く行くべきです. する is irregular: すべき or するべき, both current. Negative: 〜べきではない.', 'べき is about what is right, not what is required. なければならない is an obligation imposed from outside; べき is a judgement the speaker is making.', 'in-review', true, 200),
  ('gp-hazu-ga-nai', 'lang-ja', 'hazu-ga-nai', '〜はずがない', 'Plain form + はずがない', 'lvl-ja-n3', 'expression', 'casual', 'There''s no way that.', '彼が知っているはずがない.', 'A denial made from reasoning, not from evidence. わけがない is the same shape and stronger; ないはずだ merely expects the negative rather than ruling it out.', 'in-review', true, 201),
  ('gp-wake', 'lang-ja', 'wake', '〜わけだ', 'Plain form + わけだ', 'lvl-ja-n3', 'expression', 'casual', 'That explains it — no wonder.', '道理で寒いわけだ. Negative: 〜わけではない, "it''s not that…".', 'わけ marks a conclusion that follows from something just established. It is the sound of a penny dropping, which is why it so often follows なるほど.', 'in-review', true, 202),
  ('gp-wake-dewa-nai', 'lang-ja', 'wake-dewa-nai', '〜わけではない', 'Plain form + わけではない', 'lvl-ja-n3', 'expression', 'casual', 'It''s not that — a partial denial.', '嫌いなわけではない, "it''s not that I dislike it".', 'It denies an inference the listener might have drawn, not the fact itself. Saying 嫌いではない denies the dislike; 嫌いなわけではない denies that dislike was the reason.', 'in-review', true, 203),
  ('gp-mono-da', 'lang-ja', 'mono-da', '〜ものだ', 'Plain form + ものだ', 'lvl-ja-n3', 'expression', 'casual', 'That''s how it is — a general truth, or nostalgia.', '子どもは走り回るものだ. With た: よく遊んだものだ, "we used to play a lot".', 'The two senses share a shape because both appeal to how things simply are. With た it becomes fond recollection rather than a rule.', 'in-review', true, 204),
  ('gp-koto-ni-suru', 'lang-ja', 'koto-ni-suru', '〜ことにする', 'Plain form + ことにする', 'lvl-ja-n3', 'expression', 'casual', 'Decide to.', '来年、留学することにしました.', 'The decision is yours. ことになる is the passive twin: something was decided, possibly by you but reported as if not — which is why Japanese uses it for announcements even about one''s own choices.', 'in-review', true, 205),
  ('gp-koto-ni-naru', 'lang-ja', 'koto-ni-naru', '〜ことになる', 'Plain form + ことになる', 'lvl-ja-n3', 'expression', 'polite', 'It has been decided that.', '来月、大阪に転勤することになりました.', 'It presents an outcome as arrived at rather than chosen, which softens it. Announcing your own marriage with ことになりました is normal and not evasive.', 'in-review', true, 206),
  ('gp-tokoro-da', 'lang-ja', 'tokoro-da', '〜たところだ', 'Verb-た + ところだ', 'lvl-ja-n3', 'expression', 'casual', 'Have just this second done it.', '今、着いたところです.', 'Tighter than 〜たばかり. ところ is a point; ばかり is a stretch of time that can be stretched further by how recent it still feels.', 'in-review', true, 207),
  ('gp-uchi-ni', 'lang-ja', 'uchi-ni', '〜うちに', 'Plain form / Noun の + うちに', 'lvl-ja-n3', 'conjunction', 'casual', 'While the chance lasts.', '熱いうちに食べてください. 知らないうちに眠っていた.', 'Unlike 間に, うちに carries the sense that the window will close. 若いうちに is advice; 若い間に is merely a period.', 'in-review', true, 208),
  ('gp-tabi-ni', 'lang-ja', 'tabi-ni', '〜たびに', 'Plain present / Noun の + たびに', 'lvl-ja-n3', 'conjunction', 'casual', 'Every time.', '会うたびに背が伸びている.', 'For occasions, not clock time. 一時間ごとに is every hour; たびに needs an event to recur.', 'in-review', true, 209),
  ('gp-to-tomo-ni', 'lang-ja', 'to-tomo-ni', '〜とともに', 'Plain form / Noun + とともに', 'lvl-ja-n3', 'conjunction', 'formal', 'Along with, or as one thing changes so does another.', '年をとるとともに、体力が落ちる.', 'Written register. It links two changes as moving together, which is why it is so common in reports and explanations.', 'in-review', true, 210),
  ('gp-ni-tsurete', 'lang-ja', 'ni-tsurete', '〜につれて', 'Plain present / Noun + につれて', 'lvl-ja-n3', 'conjunction', 'formal', 'As one thing progresses, another follows.', '時間がたつにつれて、痛みが引いた.', 'The second change is a consequence of the first, gradual and not chosen. It cannot take a request or a decision.', 'in-review', true, 211),
  ('gp-ni-shitagatte', 'lang-ja', 'ni-shitagatte', '〜にしたがって', 'Plain present / Noun + にしたがって', 'lvl-ja-n3', 'conjunction', 'formal', 'In accordance with, or as one thing changes.', '規則にしたがって, "in accordance with the rules". 山を登るにしたがって寒くなった.', 'Two senses from one verb: 従う is to follow. Following a rule and following a trend are the same motion in Japanese.', 'in-review', true, 212),
  ('gp-ni-yotte', 'lang-ja', 'ni-yotte', '〜によって', 'Noun + によって', 'lvl-ja-n3', 'particle', 'formal', 'By means of, depending on, or by (an agent).', '人によって違う. 地震によって倒れた. 法律によって決められる.', 'The agent of a written passive is almost always によって rather than に. に is for a person acting on you; によって is for the cause of a stated fact.', 'in-review', true, 213),
  ('gp-ni-taishite', 'lang-ja', 'ni-taishite', '〜に対して', 'Noun + に対して', 'lvl-ja-n3', 'particle', 'formal', 'Toward, or in contrast to.', '目上の人に対して失礼だ. 兄は静かなのに対して、弟はうるさい.', 'The contrast sense sets two things side by side as opposites. に対する before a noun: 学生に対する態度.', 'in-review', true, 214),
  ('gp-ni-tsuite', 'lang-ja', 'ni-tsuite', '〜について', 'Noun + について', 'lvl-ja-n3', 'particle', 'polite', 'About, concerning.', '日本の文化について話します.', 'The topic of discussion. に関して is its formal twin and slightly broader — について narrows to the subject itself, に関して admits anything related.', 'in-review', true, 215),
  ('gp-ni-totte', 'lang-ja', 'ni-totte', '〜にとって', 'Noun + にとって', 'lvl-ja-n3', 'particle', 'polite', 'For, from the standpoint of.', '私にとって、家族が一番大切です.', 'It sets whose judgement is being reported. Almost always followed by an evaluation — important, difficult, unforgettable — because a standpoint needs something to judge.', 'in-review', true, 216),
  ('gp-kagiri', 'lang-ja', 'kagiri', '〜かぎり', 'Plain form + かぎり', 'lvl-ja-n3', 'conjunction', 'formal', 'As long as, as far as.', '私が知るかぎり. 体が動くかぎり働きたい.', '限る is to limit, and both senses draw a boundary: a limit on the speaker''s knowledge, or a limit on how long something holds.', 'in-review', true, 217),
  ('gp-sae', 'lang-ja', 'sae', '〜さえ', 'Noun + さえ', 'lvl-ja-n3', 'particle', 'casual', 'Even — and with ば, "if only".', '子どもさえ知っている. お金さえあれば.', 'さえ picks an extreme case to prove the rest. With ば it names the one condition that would settle everything, which is why it so often sounds wistful.', 'in-review', true, 218),
  ('gp-koso', 'lang-ja', 'koso', '〜こそ', 'Noun + こそ', 'lvl-ja-n3', 'particle', 'casual', 'Precisely this one.', '今年こそ、日本語を話せるようになる. こちらこそ.', 'It insists on the word it follows against some alternative — this year as opposed to the last few. こちらこそ returns thanks by insisting the debt runs the other way.', 'in-review', true, 219),
  ('gp-dake-de-naku', 'lang-ja', 'dake-de-naku', '〜だけでなく', 'Plain form / Noun + だけでなく', 'lvl-ja-n3', 'conjunction', 'polite', 'Not only — but also.', '英語だけでなく、中国語も話せる.', 'The second half almost always takes も. ばかりでなく is interchangeable and slightly more formal.', 'in-review', true, 220),
  ('gp-hodo', 'lang-ja', 'hodo', '〜ほど', 'Plain form / Noun + ほど', 'lvl-ja-n3', 'particle', 'casual', 'To the extent that — or the more, the more.', '歩けないほど疲れた. 考えれば考えるほど分からなくなる.', 'The doubled form (ば〜ほど) is the standard way to say "the more X, the more Y", and it needs the same verb twice.', 'in-review', true, 221),
  ('gp-kurai', 'lang-ja', 'kurai', '〜くらい / 〜ぐらい', 'Plain form / Noun + くらい', 'lvl-ja-n3', 'particle', 'casual', 'About, or to the point of.', '三十分くらい. 泣きたいくらいうれしい.', 'Where ほど tends to measure something impressive, くらい often belittles: それくらいできる, "I can manage at least that much".', 'in-review', true, 222),
  ('gp-toori', 'lang-ja', 'toori', '〜とおり', 'Plain form / Noun の + とおり', 'lvl-ja-n3', 'expression', 'polite', 'Just as, in the way that.', '説明したとおりにやってください. 予想どおり.', 'Attached straight to a noun it voices as どおり: 予定どおり, 時間どおり. The rendaku is the giveaway that the noun and とおり have fused into one word.', 'in-review', true, 223),
  ('gp-mama', 'lang-ja', 'mama', '〜まま', 'Verb-た / Noun の + まま', 'lvl-ja-n3', 'expression', 'casual', 'Left as it is, unchanged.', '電気をつけたまま寝てしまった. 昔のまま.', 'It marks a state that persists when it should not have, which is why it so often reports carelessness — the light left on, the door left open.', 'in-review', true, 224),
  ('gp-kke', 'lang-ja', 'kke', '〜っけ', 'Plain form + っけ', 'lvl-ja-n3', 'particle', 'casual', 'What was it again?', '君の名前、何だっけ？', 'Only for something you once knew and have mislaid. Using it for something you never knew sounds like a false claim to have met before.', 'in-review', true, 225),
  ('gp-tte', 'lang-ja', 'tte-quote', '〜って (quotation)', 'Clause + って', 'lvl-ja-n3', 'particle', 'casual', 'The casual と / という.', '行くって言ってた. 田中さんって人.', 'Conversation''s all-purpose quoting particle. It can also mark a topic — 日本語って難しい — which と cannot.', 'in-review', true, 226),
  ('gp-nanka', 'lang-ja', 'nanka', '〜なんか / 〜なんて', 'Noun + なんか', 'lvl-ja-n3', 'particle', 'casual', 'Things like — usually dismissive.', '勉強なんかしたくない. 泣くなんて.', 'It belittles what it follows. など is the neutral version; なんか carries an attitude, and about oneself it reads as self-deprecation.', 'in-review', true, 227),
  ('gp-you-ni-iu', 'lang-ja', 'you-ni-iu', '〜ように言う', 'Plain present + ように言う', 'lvl-ja-n3', 'expression', 'polite', 'Tell someone to do something.', '早く来るように言ってください.', 'Reported requests take ように, not と — 「来て」と言う quotes the words, 来るように言う reports the instruction without them.', 'in-review', true, 228),
  ('gp-sasete-itadaku', 'lang-ja', 'sasete-itadaku', '〜させていただく', 'Causative-て + いただく', 'lvl-ja-n3', 'expression', 'formal', 'Humbly do something, with permission.', '説明させていただきます.', 'Literally "receive the favour of being allowed to". Very common in business Japanese, and easy to overdo — used for something nobody could object to, it sounds obsequious.', 'in-review', true, 229),
  ('gp-o-kudasai', 'lang-ja', 'o-kudasai', 'お〜ください', 'お + Verb stem + ください', 'lvl-ja-n3', 'expression', 'formal', 'Respectful request.', 'お待ちください. Irregular verbs use their honorific stems: ご覧ください.', 'The respectful counterpart of てください. Announcements use it constantly precisely because it commands without addressing anyone in particular.', 'in-review', true, 230),
  ('gp-zaru-o-enai', 'lang-ja', 'zaru-o-enai', '〜ざるを得ない', 'Verb-ない stem + ざるを得ない', 'lvl-ja-n3', 'expression', 'formal', 'Have no choice but to.', '認めざるを得ない. する is irregular: せざるを得ない.', 'A classical negative preserved in a modern set phrase, which is why it takes the ない-stem but not ない itself. It carries reluctance that なければならない does not.', 'in-review', true, 231),
  ('gp-ni-chigainai', 'lang-ja', 'ni-chigainai', '〜に違いない', 'Plain form + に違いない', 'lvl-ja-n3', 'expression', 'polite', 'Must be — near certainty.', '彼は知っているに違いない.', 'Stronger than はず, and unlike はず it is a conviction rather than a deduction you could show your working for.', 'in-review', true, 232),
  ('gp-osore-ga-aru', 'lang-ja', 'osore-ga-aru', '〜おそれがある', 'Plain present / Noun の + おそれがある', 'lvl-ja-n3', 'expression', 'formal', 'There''s a risk that.', '大雨のおそれがあります.', 'Only for bad outcomes. Weather warnings and official notices are its natural home; it would be strange about anything welcome.', 'in-review', true, 233),
  ('gp-kanenai', 'lang-ja', 'kanenai', '〜かねない', 'Verb stem + かねない', 'lvl-ja-n3', 'expression', 'formal', 'Might well — and that would be bad.', '事故につながりかねない.', 'Its positive twin かねる means "cannot bring oneself to", so かねない literally says "cannot NOT" — the double negative is why a bare-looking form carries a warning.', 'in-review', true, 234),
  ('gp-gachi', 'lang-ja', 'gachi', '〜がち', 'Verb stem / Noun + がち', 'lvl-ja-n3', 'auxiliary', 'casual', 'Tends to, and not in a good way.', '忘れがち. 病気がち.', 'A tendency the speaker regrets. For a neutral leaning, 〜傾向がある is the word.', 'in-review', true, 235),
  ('gp-ppoi', 'lang-ja', 'ppoi', '〜っぽい', 'Noun / Verb stem + っぽい', 'lvl-ja-n3', 'auxiliary', 'casual', '-ish, has a whiff of.', '子どもっぽい. 忘れっぽい.', 'Casual and usually faintly critical. らしい says something matches its type well; っぽい says it merely resembles it.', 'in-review', true, 236),
  ('gp-darake', 'lang-ja', 'darake', '〜だらけ', 'Noun + だらけ', 'lvl-ja-n3', 'auxiliary', 'casual', 'Covered in, full of.', '間違いだらけ. 泥だらけ.', 'Always negative, and usually physical or messy. まみれ is its narrower cousin, reserved for liquids and dust actually clinging to a surface.', 'in-review', true, 237),
  ('gp-muke-muki', 'lang-ja', 'muke-muki', '〜向け / 〜向き', 'Noun + 向け', 'lvl-ja-n3', 'auxiliary', 'polite', 'Aimed at / suited to.', '子ども向けの番組. 初心者向きの本.', '向け is intent — it was made for them. 向き is fit — it happens to suit them. A textbook can be 子ども向け without being 子ども向き.', 'in-review', true, 238),
  ('gp-chuu', 'lang-ja', 'chuu', '〜中', 'Noun + 中', 'lvl-ja-n3', 'auxiliary', 'polite', 'In the middle of.', '会議中. 工事中. Read ちゅう for an activity, じゅう for a span: 一日中.', 'The reading carries the meaning: ちゅう is "during this activity", じゅう is "throughout this whole extent".', 'in-review', true, 239),
  ('gp-gimi', 'lang-ja', 'gimi', '〜気味', 'Noun / Verb stem + 気味', 'lvl-ja-n3', 'auxiliary', 'casual', 'A touch of, slightly.', '風邪気味. 疲れ気味.', 'A slight and usually unwelcome tendency the speaker senses in themselves. It hedges: 風邪気味 stops short of claiming to be ill.', 'in-review', true, 240),
  ('gp-kake', 'lang-ja', 'kake', '〜かけ', 'Verb stem + かけ', 'lvl-ja-n3', 'auxiliary', 'casual', 'Half-done, left partway.', '読みかけの本. 言いかけてやめた.', 'It marks something begun and abandoned, which is why it so often appears with regret or interruption.', 'in-review', true, 241),
  ('gp-nikui-gatai', 'lang-ja', 'nikui-gatai', '〜がたい', 'Verb stem + がたい', 'lvl-ja-n3', 'auxiliary', 'formal', 'Hard to bring oneself to.', '信じがたい. 忘れがたい.', 'Not the same as にくい. にくい is practical difficulty; がたい is closer to impossible in principle, and belongs to written Japanese.', 'in-review', true, 242),
  ('gp-you-ga-nai', 'lang-ja', 'you-ga-nai', '〜ようがない', 'Verb stem + ようがない', 'lvl-ja-n3', 'expression', 'casual', 'There''s no way to.', '連絡しようがない.', 'Not unwillingness but impossibility — no method exists. 〜られない would leave open that you simply cannot manage it.', 'in-review', true, 243),
  ('gp-tsutsu', 'lang-ja', 'tsutsu', '〜つつ', 'Verb stem + つつ', 'lvl-ja-n3', 'conjunction', 'formal', 'While — the written ながら.', '悪いと知りつつ、やってしまった.', 'つつある is a separate use meaning "is in the process of": 増えつつある. The bare form leans toward "even though", where ながら stays neutral.', 'in-review', true, 244),
  ('gp-nagara-mo', 'lang-ja', 'nagara-mo', '〜ながらも', 'Verb stem / Adj + ながらも', 'lvl-ja-n3', 'conjunction', 'formal', 'Even while — despite.', '狭いながらも楽しい我が家.', 'The も is what turns simultaneity into concession. Without it ながら merely reports two things at once.', 'in-review', true, 245),
  ('gp-mono-no', 'lang-ja', 'mono-no', '〜ものの', 'Plain form + ものの', 'lvl-ja-n3', 'conjunction', 'formal', 'Although — the expectation went unmet.', '買ったものの、一度も使っていない.', 'Written register. It sets up something that happened and then reports that nothing followed from it.', 'in-review', true, 246),
  ('gp-kuseni', 'lang-ja', 'kuseni', '〜くせに', 'Plain form + くせに', 'lvl-ja-n3', 'conjunction', 'casual', 'Even though — said with contempt.', '知っているくせに教えてくれない.', 'のに with an accusation attached. It can only be aimed at a person, and never at yourself without irony.', 'in-review', true, 247),
  ('gp-sei-de', 'lang-ja', 'sei-de', '〜せいで', 'Plain form / Noun の + せいで', 'lvl-ja-n3', 'conjunction', 'casual', 'Because of — and it went badly.', '雨のせいで中止になった.', 'せい assigns blame; おかげ credits. 〜おかげで for a good outcome, and using せい for one is sarcasm.', 'in-review', true, 248),
  ('gp-okage-de', 'lang-ja', 'okage-de', '〜おかげで', 'Plain form / Noun の + おかげで', 'lvl-ja-n3', 'conjunction', 'polite', 'Thanks to.', '先生のおかげで合格しました.', 'From 陰, "shadow" — the protection of standing in someone''s shade. おかげさまで has hardened into a set phrase that thanks nobody in particular.', 'in-review', true, 249),
  ('gp-tame-cause', 'lang-ja', 'tame-cause', '〜ため (cause)', 'Plain form / Noun の + ため', 'lvl-ja-n3', 'conjunction', 'formal', 'Because — in writing.', '事故のため、電車が遅れています.', 'Same word as the purpose ため, told apart by whether the result could have been intended. A delay is nobody''s aim, so this reads as cause.', 'in-review', true, 250),
  ('gp-you-ni-mieru', 'lang-ja', 'you-ni-mieru', '〜ように見える', 'Plain form + ように見える', 'lvl-ja-n3', 'expression', 'casual', 'Looks as if.', '元気なように見える.', 'Restricted to what the eye reports, unlike ようだ which covers inference of any kind.', 'in-review', true, 251),
  ('gp-toshite', 'lang-ja', 'toshite', '〜として', 'Noun + として', 'lvl-ja-n3', 'particle', 'polite', 'As, in the capacity of.', '留学生として日本に来ました.', 'It names the role someone acts in. にとって gives a standpoint for judging; として gives a hat you are wearing while acting.', 'in-review', true, 252),
  ('gp-kara-toiu-made', 'lang-ja', 'kara-made', '〜から〜にかけて', 'Noun + から + Noun + にかけて', 'lvl-ja-n3', 'expression', 'formal', 'From one point to another, roughly.', '夕方から夜にかけて雨が降るでしょう.', 'Deliberately vague at both ends, which から〜まで is not. Forecasts prefer it because the edges genuinely are not known.', 'in-review', true, 253),
  ('gp-owari-ni', 'lang-ja', 'kawari-ni', '〜かわりに', 'Plain form / Noun の + かわりに', 'lvl-ja-n3', 'conjunction', 'casual', 'Instead of, or in exchange for.', '行くかわりに手紙を書いた. 高いかわりに質がいい.', 'The exchange sense balances a drawback against a benefit, which is why it often reads as a concession rather than a substitution.', 'in-review', true, 254)
ON CONFLICT (language_id, slug) DO NOTHING;
