-- N5 grammar, part three: the rest of the level.
--
-- 009 and 011 covered 50 points, and the plan called for ~135. This and 025
-- close that gap. Same rules throughout: the point LIST is a fact about the
-- exam, every word of the prose is written for this app, nothing is imported.
--
-- sort_index continues at 500 — after N5's existing 0–49 and clear of N4's 100
-- block, so nothing has to be renumbered.

INSERT INTO grammar_points
  (id, language_id, slug, title, pattern, level_id, category, register, meaning_short, meaning_long, nuance, status, published, sort_index) VALUES
  ('gp-masen', 'lang-ja', 'masen', '〜ません', 'Verb stem + ません', 'lvl-ja-n5', 'auxiliary', 'polite', 'Polite negative.', '行きません, 食べません. The past is ませんでした.', 'ません is also how a polite invitation begins — 行きませんか is an offer, not a statement that you are not going.', 'in-review', true, 500),
  ('gp-mashita', 'lang-ja', 'mashita', '〜ました', 'Verb stem + ました', 'lvl-ja-n5', 'auxiliary', 'polite', 'Polite past.', '食べました. Negative past: 食べませんでした.', 'ました and た report the same event; only the politeness toward the listener differs. Which you choose says nothing about when it happened.', 'in-review', true, 501),
  ('gp-masen-deshita', 'lang-ja', 'masen-deshita', '〜ませんでした', 'Verb stem + ませんでした', 'lvl-ja-n5', 'auxiliary', 'polite', 'Polite negative past.', '行きませんでした.', 'The でした is doing the past, not ません — which is why the plain equivalent is なかった and not ないでした.', 'in-review', true, 502),
  ('gp-nakatta', 'lang-ja', 'nakatta', '〜なかった', 'Verb-ない stem + かった', 'lvl-ja-n5', 'auxiliary', 'casual', 'Plain negative past.', '行かなかった, 食べなかった.', 'ない conjugates like an i-adjective all the way through, so its past is かった. Every learner tries ないでした once.', 'in-review', true, 503),
  ('gp-deshita', 'lang-ja', 'deshita', '〜でした', 'Noun + でした', 'lvl-ja-n5', 'auxiliary', 'polite', 'Polite past copula.', '学生でした. Negative: じゃありませんでした.', 'です is not a verb, so it takes でした rather than a ます-form past. The two look parallel and are not.', 'in-review', true, 504),
  ('gp-ja-arimasen', 'lang-ja', 'ja-arimasen', '〜じゃありません', 'Noun + じゃありません', 'lvl-ja-n5', 'auxiliary', 'polite', 'Polite negative copula.', '学生じゃありません. Formal: ではありません.', 'じゃ is a spoken contraction of では. Writing it in a formal document looks careless for exactly that reason.', 'in-review', true, 505),
  ('gp-i-adj-negative', 'lang-ja', 'i-adj-negative', 'い-adjective negative', 'iAdj → 〜くない', 'lvl-ja-n5', 'construction', 'casual', 'Not (adjective).', '高い → 高くない. いい is irregular: よくない.', 'いい breaks every rule it can, because its conjugations descend from an older よい. 良かった, よくない, よければ all come from there.', 'in-review', true, 506),
  ('gp-i-adj-past', 'lang-ja', 'i-adj-past', 'い-adjective past', 'iAdj → 〜かった', 'lvl-ja-n5', 'construction', 'casual', 'Was (adjective).', '高かった. Negative past: 高くなかった.', 'The adjective carries the tense itself — 高かったです, never 高いでした. です adds politeness only.', 'in-review', true, 507),
  ('gp-na-adj-past', 'lang-ja', 'na-adj-past', 'な-adjective past', 'naAdj + だった / でした', 'lvl-ja-n5', 'construction', 'casual', 'Was (adjective).', '静かだった, 静かでした. Negative: 静かじゃなかった.', 'A な-adjective behaves like a noun, which is why it takes the copula. That is the whole difference between the two adjective classes.', 'in-review', true, 508),
  ('gp-adverb-ku', 'lang-ja', 'adverb-ku', 'Adjective → adverb', 'iAdj → 〜く / naAdj → 〜に', 'lvl-ja-n5', 'construction', 'casual', 'Turns an adjective into an adverb.', '早い → 早く歩く. 静か → 静かに歩く.', 'The two classes take different endings for the same job, and it is the clearest test of which class an adjective belongs to.', 'in-review', true, 509),
  ('gp-ne-particle', 'lang-ja', 'ne-particle', 'ね (agreement)', 'Sentence + ね', 'lvl-ja-n5', 'particle', 'casual', 'Seeking agreement — "isn''t it?"', 'いい天気ですね.', 'ね assumes the listener shares the view. Used about something only you could know — 私は学生ですね — it sounds strange, because there is nothing to agree with.', 'in-review', true, 510),
  ('gp-yo-particle', 'lang-ja', 'yo-particle', 'よ (telling)', 'Sentence + よ', 'lvl-ja-n5', 'particle', 'casual', 'Telling the listener something new.', '雨が降っていますよ.', 'よ informs; ね agrees. Overusing よ sounds pushy, because every sentence then claims to be news the listener lacked.', 'in-review', true, 511),
  ('gp-no-explanatory', 'lang-ja', 'no-explanatory', '〜のです / 〜んです', 'Plain form + のです', 'lvl-ja-n5', 'expression', 'polite', 'Explaining, or asking for an explanation.', '頭が痛いんです. Nouns and な-adjectives take な: 学生なんです.', 'It frames a statement as a reason or background rather than a bare fact. 行きます states a plan; 行くんです answers a question nobody has quite asked.', 'in-review', true, 512),
  ('gp-made-time', 'lang-ja', 'made-time', '〜まで', 'Noun + まで', 'lvl-ja-n5', 'particle', 'casual', 'Until, as far as.', '五時まで働きます. 駅まで歩く.', 'Both time and distance, and in both it is the far end of something continuous. A deadline is までに, which is N4.', 'in-review', true, 513),
  ('gp-kara-from', 'lang-ja', 'kara-from', '〜から (from)', 'Noun + から', 'lvl-ja-n5', 'particle', 'casual', 'From — a starting point.', '九時から始まります. 東京から来ました.', 'Same から as the "because" one. A reason is where a statement starts, which is not a coincidence but the same idea.', 'in-review', true, 514),
  ('gp-gurai', 'lang-ja', 'gurai', '〜ぐらい / 〜くらい', 'Quantity + ぐらい', 'lvl-ja-n5', 'particle', 'casual', 'About, approximately.', '三十分ぐらいかかります.', 'For amounts. ごろ is its twin for points in time: 三時ごろ is around three o''clock, 三時間ぐらい is about three hours.', 'in-review', true, 515),
  ('gp-goro', 'lang-ja', 'goro', '〜ごろ', 'Time + ごろ', 'lvl-ja-n5', 'particle', 'casual', 'Around (a point in time).', '三時ごろ会いましょう.', 'Only for a moment, never a duration. 三時間ごろ is wrong; that needs ぐらい.', 'in-review', true, 516),
  ('gp-zutsu', 'lang-ja', 'zutsu', '〜ずつ', 'Quantity + ずつ', 'lvl-ja-n5', 'particle', 'casual', 'Each, apiece, at a time.', '一人二つずつ取ってください. 少しずつ.', 'It distributes a quantity across a group or across time. 少しずつ is the most common form and means "little by little".', 'in-review', true, 517),
  ('gp-nado', 'lang-ja', 'nado', '〜など', 'Noun + など', 'lvl-ja-n5', 'particle', 'polite', 'And so on.', '本やノートなどを買いました.', 'The neutral list-ender. なんか is its colloquial form and adds a sneer, which など does not.', 'in-review', true, 518),
  ('gp-toka', 'lang-ja', 'toka', '〜とか', 'Noun + とか', 'lvl-ja-n5', 'particle', 'casual', 'Things like — a casual list.', 'すしとかてんぷらとか.', 'Vaguer than や and far more common in speech. It leaves the list open on purpose.', 'in-review', true, 519),
  ('gp-question-words', 'lang-ja', 'question-words', 'Question words', 'なに / だれ / どこ / いつ / どう', 'lvl-ja-n5', 'construction', 'casual', 'What, who, where, when, how.', '何を食べますか。だれが来ますか。', 'They take が rather than は, because you cannot make a topic of the thing you are asking about. This is the rule learners break most.', 'in-review', true, 520),
  ('gp-doushite', 'lang-ja', 'doushite', 'どうして / なぜ', 'どうして + Clause + か', 'lvl-ja-n5', 'construction', 'casual', 'Why.', 'どうして来なかったんですか.', 'Almost always paired with んです: asking for a reason without it sounds like an accusation rather than a question.', 'in-review', true, 521),
  ('gp-counter-tsu', 'lang-ja', 'counter-tsu', '〜つ (counter)', 'Number + つ', 'lvl-ja-n5', 'construction', 'casual', 'The general counter, one to ten.', '一つ, 二つ … 十つ does not exist — ten is 十.', 'The native Japanese numbers, used when no specific counter fits. Beyond ten, Japanese switches to the Chinese numbers entirely.', 'in-review', true, 522),
  ('gp-counter-nin', 'lang-ja', 'counter-nin', '〜人 (counter)', 'Number + 人', 'lvl-ja-n5', 'construction', 'casual', 'Counter for people.', '三人, 四人（よにん）. One and two are irregular: 一人（ひとり）, 二人（ふたり）.', 'The irregular first two are the native numbers surviving inside an otherwise Chinese-numbered counter.', 'in-review', true, 523),
  ('gp-counter-mai', 'lang-ja', 'counter-mai', '〜枚 (counter)', 'Number + 枚', 'lvl-ja-n5', 'construction', 'casual', 'Counter for flat things.', '紙を三枚. Shirts, plates, tickets, stamps.', 'Japanese counters classify by shape. 枚 is the flat one, 本 the long thin one, 匹 the small animal one.', 'in-review', true, 524),
  ('gp-counter-hon', 'lang-ja', 'counter-hon', '〜本 (counter)', 'Number + 本', 'lvl-ja-n5', 'construction', 'casual', 'Counter for long thin things.', 'ペンを二本. Bottles, pens, umbrellas, trees.', 'The reading shifts with the number: いっぽん, にほん, さんぼん. The consonant changes are regular once you have met them a few times.', 'in-review', true, 525),
  ('gp-counter-ji-fun', 'lang-ja', 'counter-ji-fun', '〜時 / 〜分 (time)', 'Number + 時 / 分', 'lvl-ja-n5', 'construction', 'casual', 'O''clock and minutes.', '七時三十分. Four is よじ, seven しちじ, nine くじ.', 'Those three readings are irregular and no rule predicts them; they simply have to be learned.', 'in-review', true, 526),
  ('gp-counter-sai', 'lang-ja', 'counter-sai', '〜歳 (age)', 'Number + 歳', 'lvl-ja-n5', 'construction', 'casual', 'Counter for years of age.', '二十歳 is irregular: はたち.', 'はたち is a survival from the old native counting system, kept because turning twenty matters in Japan.', 'in-review', true, 527),
  ('gp-totemo', 'lang-ja', 'totemo', 'とても / あまり', 'とても + Adjective', 'lvl-ja-n5', 'adverb', 'casual', 'Very / not very.', 'とても高い. あまり高くない.', 'あまり demands a negative. With a positive verb it means "too much" instead, which is a different word doing a different job.', 'in-review', true, 528),
  ('gp-zenzen', 'lang-ja', 'zenzen', 'ぜんぜん', 'ぜんぜん + negative', 'lvl-ja-n5', 'adverb', 'casual', 'Not at all.', 'ぜんぜん分かりません.', 'Textbooks require a negative; casual speech has long used it with positives for emphasis (ぜんぜん大丈夫). The exam wants the negative.', 'in-review', true, 529),
  ('gp-mada-mou', 'lang-ja', 'mada-mou', 'まだ / もう', 'まだ / もう + Verb', 'lvl-ja-n5', 'adverb', 'casual', 'Still, not yet / already.', 'まだ食べていません. もう食べました.', 'They pair by tense: もう with the past for "already", まだ with ていません for "not yet". まだ食べません means something else entirely — a refusal.', 'in-review', true, 530),
  ('gp-frequency-adverbs', 'lang-ja', 'frequency-adverbs', 'いつも / よく / ときどき / たまに', 'Adverb + Verb', 'lvl-ja-n5', 'adverb', 'casual', 'Always, often, sometimes, rarely.', 'いつも七時に起きます. ときどき映画を見ます.', 'あまり and ぜんぜん complete the scale at the bottom, and both of those need a negative verb where these four do not.', 'in-review', true, 531),
  ('gp-jouzu-heta', 'lang-ja', 'jouzu-heta', '〜が上手 / 〜が下手', 'Noun + が + 上手', 'lvl-ja-n5', 'expression', 'polite', 'Good at / bad at.', '日本語が上手ですね.', 'Never used about yourself — 上手です about your own Japanese sounds boastful. 得意 is the modest word for your own skill.', 'in-review', true, 532),
  ('gp-hoshii', 'lang-ja', 'hoshii', '〜がほしい', 'Noun + がほしい', 'lvl-ja-n5', 'expression', 'casual', 'Want (a thing).', '新しい車がほしい.', 'For things; for actions it is 〜たい. Like たい it is only for your own desire, and a third party takes ほしがる.', 'in-review', true, 533),
  ('gp-te-wa-ikemasen', 'lang-ja', 'te-wa-ikemasen', '〜てはいけません', 'Verb-て + はいけません', 'lvl-ja-n5', 'expression', 'polite', 'Must not.', 'ここでたばこを吸ってはいけません. Casual: 〜ちゃだめ.', 'The refusal that answers 〜てもいいですか. Its contraction ちゃ is so common in speech that the full form sounds like a sign.', 'in-review', true, 534),
  ('gp-nakutemo-ii-n5', 'lang-ja', 'nakutemo-ii-n5', '〜なくてもいい', 'Verb-ない stem + くてもいい', 'lvl-ja-n5', 'expression', 'polite', 'Don''t have to.', '来なくてもいいです.', 'The mirror of なければなりません. Japanese lifts an obligation by permitting its absence rather than denying the duty.', 'in-review', true, 535),
  ('gp-ni-existence', 'lang-ja', 'ni-existence', 'に (place of existence)', 'Place + に + あります / います', 'lvl-ja-n5', 'particle', 'casual', 'Marks where something is.', '机の上に本があります.', 'に for existing, で for doing. 部屋にいます is being in the room; 部屋で勉強します is working in it.', 'in-review', true, 536),
  ('gp-de-reason', 'lang-ja', 'de-reason', 'で (cause)', 'Noun + で', 'lvl-ja-n5', 'particle', 'casual', 'Because of.', '風邪で休みました.', 'Only with a noun. A clause needs から or ので, and trying to use で with one is a common early mistake.', 'in-review', true, 537),
  ('gp-ni-frequency', 'lang-ja', 'ni-frequency', 'に (per)', 'Time + に + Number', 'lvl-ja-n5', 'particle', 'casual', 'Per — how often.', '一週間に三回. 一日に二時間.', 'The period comes first and the count second, which is the reverse of English "three times a week".', 'in-review', true, 538),
  ('gp-nan-no', 'lang-ja', 'nan-no', '何の / どんな', '何の + Noun', 'lvl-ja-n5', 'construction', 'casual', 'What kind of.', '何の本ですか。どんな本ですか。', '何の asks what it is about; どんな asks what it is like. "What book" splits into two questions in Japanese.', 'in-review', true, 539),
  ('gp-dochira', 'lang-ja', 'dochira', 'どちら / どっち', 'A と B と + どちら', 'lvl-ja-n5', 'construction', 'polite', 'Which of two.', 'コーヒーとお茶とどちらがいいですか.', 'どちら is also the polite word for "where" and "who", which is why a formal enquiry asks どちらさま rather than だれ.', 'in-review', true, 540),
  ('gp-ichiban', 'lang-ja', 'ichiban', '一番', 'Group + で + 一番 + Adjective', 'lvl-ja-n5', 'expression', 'casual', 'The most, the -est.', 'クラスで一番高い. 何が一番好きですか.', 'Japanese has no comparative or superlative endings; the work is done by separate words — 一番 for the top, もっと for more.', 'in-review', true, 541),
  ('gp-motto', 'lang-ja', 'motto', 'もっと', 'もっと + Adjective / Verb', 'lvl-ja-n5', 'adverb', 'casual', 'More.', 'もっと大きいのをください.', 'It compares against something already in play, which is why もっと alone is often a complete request.', 'in-review', true, 542)
ON CONFLICT (language_id, slug) DO NOTHING;
