-- N5 example sentences, batch 1: ten topics that had none.
--
-- 121 of the 129 published N5 topics have no example sentences, so their lesson
-- is an explanation and a single multiple-choice question. These ten get four
-- sentences each, which is what the teach deck shows and what the word-order,
-- cloze and dictation questions are generated from.
--
-- Every sentence passed `check:examples` BEFORE this file was written. That
-- matters more than it sounds: `glossLine` matches longest-first against
-- published vocabulary only, and a word it does not hold is not left alone but
-- shredded into the characters it can match. A sentence that fails the check
-- reads as nonsense in the lesson and generates nonsense questions, and once a
-- seed has run it never runs again.
--
-- The vocabulary is therefore deliberately narrow — 猫, 山, 窓, 靴, 新聞 — and
-- every verb form was tried before being used. 少し休みましょう had to become
-- 少し歩きましょう because 休み is also a noun, so the tokeniser took it and left
-- ましょう stranded.
--
-- Additive: new sentences, translations and links, nothing updated or removed.
-- Safe on a live database and safe to re-run.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- wa-particle
  ('sent-ex-wa-1', 'lang-ja', '父は新聞を読みます。', 'ちち わ しんぶん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wa-2', 'lang-ja', '猫は小さいです。', 'ねこ わ ちいさい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wa-3', 'lang-ja', '山は高いです。', 'やま わ たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wa-4', 'lang-ja', '音楽は楽しいです。', 'おんがく わ たのしい です。', 'lvl-ja-n5', 'authored', true),
  -- ga-particle
  ('sent-ex-ga-1', 'lang-ja', '雨が降ります。', 'あめ が ふります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ga-2', 'lang-ja', '猫が好きです。', 'ねこ が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ga-3', 'lang-ja', '車が新しいです。', 'くるま が あたらしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ga-4', 'lang-ja', '花が綺麗です。', 'はな が きれい です。', 'lvl-ja-n5', 'authored', true),
  -- kudasai
  ('sent-ex-kudasai-1', 'lang-ja', '窓を開けてください。', 'まど お あけて ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kudasai-2', 'lang-ja', '手紙を書いてください。', 'てがみ お かいて ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kudasai-3', 'lang-ja', '本を読んでください。', 'ほん お よんで ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kudasai-4', 'lang-ja', '写真を見てください。', 'しゃしん お みて ください。', 'lvl-ja-n5', 'authored', true),
  -- mashou
  ('sent-ex-mashou-1', 'lang-ja', '明日会いましょう。', 'あした あいましょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashou-2', 'lang-ja', '映画を見ましょう。', 'えいが お みましょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashou-3', 'lang-ja', 'お茶を飲みましょう。', 'おちゃ お のみましょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashou-4', 'lang-ja', '少し歩きましょう。', 'すこし あるきましょう。', 'lvl-ja-n5', 'authored', true),
  -- tai
  ('sent-ex-tai-1', 'lang-ja', '水が飲みたいです。', 'みず が のみたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tai-2', 'lang-ja', '映画を見たいです。', 'えいが お みたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tai-3', 'lang-ja', '日本に行きたいです。', 'にほん に いきたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tai-4', 'lang-ja', '魚が食べたいです。', 'さかな が たべたい です。', 'lvl-ja-n5', 'authored', true),
  -- kara-reason
  ('sent-ex-kara-1', 'lang-ja', '寒いから、窓を閉めます。', 'さむい から、まど お しめます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kara-2', 'lang-ja', '忙しいから、休みません。', 'いそがしい から、やすみません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kara-3', 'lang-ja', '安いから、買います。', 'やすい から、かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kara-4', 'lang-ja', '暑いから、水を飲みます。', 'あつい から、みず お のみます。', 'lvl-ja-n5', 'authored', true),
  -- ni-direction
  ('sent-ex-ni-1', 'lang-ja', '学校に行きます。', 'がっこう に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ni-2', 'lang-ja', '部屋に入ります。', 'へや に はいります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ni-3', 'lang-ja', '朝に起きます。', 'あさ に おきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ni-4', 'lang-ja', '日本に来ます。', 'にほん に きます。', 'lvl-ja-n5', 'authored', true),
  -- wo-object
  ('sent-ex-wo-1', 'lang-ja', 'パンを食べます。', 'パン お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wo-2', 'lang-ja', '音楽を聞きます。', 'おんがく お ききます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wo-3', 'lang-ja', '料理を作ります。', 'りょうり お つくります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wo-4', 'lang-ja', '靴を買います。', 'くつ お かいます。', 'lvl-ja-n5', 'authored', true),
  -- mo-particle
  ('sent-ex-mo-1', 'lang-ja', '私も学生です。', 'わたし も がくせい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mo-2', 'lang-ja', '猫も好きです。', 'ねこ も すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mo-3', 'lang-ja', '父も働きます。', 'ちち も はたらきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mo-4', 'lang-ja', '明日も忙しいです。', 'あした も いそがしい です。', 'lvl-ja-n5', 'authored', true),
  -- arimasu-imasu
  ('sent-ex-aru-1', 'lang-ja', '部屋に机があります。', 'へや に つくえ が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-aru-2', 'lang-ja', '学校に先生がいます。', 'がっこう に せんせい が います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-aru-3', 'lang-ja', '時計があります。', 'とけい が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-aru-4', 'lang-ja', '猫がいます。', 'ねこ が います。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-wa-1', 'sent-ex-wa-1', 'en', 'My father reads the newspaper.', 'authored'),
  ('st-ex-wa-2', 'sent-ex-wa-2', 'en', 'Cats are small.', 'authored'),
  ('st-ex-wa-3', 'sent-ex-wa-3', 'en', 'The mountain is tall.', 'authored'),
  ('st-ex-wa-4', 'sent-ex-wa-4', 'en', 'Music is fun.', 'authored'),
  ('st-ex-ga-1', 'sent-ex-ga-1', 'en', 'It rains.', 'authored'),
  ('st-ex-ga-2', 'sent-ex-ga-2', 'en', 'I like cats.', 'authored'),
  ('st-ex-ga-3', 'sent-ex-ga-3', 'en', 'The car is new.', 'authored'),
  ('st-ex-ga-4', 'sent-ex-ga-4', 'en', 'The flowers are beautiful.', 'authored'),
  ('st-ex-kudasai-1', 'sent-ex-kudasai-1', 'en', 'Please open the window.', 'authored'),
  ('st-ex-kudasai-2', 'sent-ex-kudasai-2', 'en', 'Please write a letter.', 'authored'),
  ('st-ex-kudasai-3', 'sent-ex-kudasai-3', 'en', 'Please read the book.', 'authored'),
  ('st-ex-kudasai-4', 'sent-ex-kudasai-4', 'en', 'Please look at the photo.', 'authored'),
  ('st-ex-mashou-1', 'sent-ex-mashou-1', 'en', 'Let''s meet tomorrow.', 'authored'),
  ('st-ex-mashou-2', 'sent-ex-mashou-2', 'en', 'Let''s watch a film.', 'authored'),
  ('st-ex-mashou-3', 'sent-ex-mashou-3', 'en', 'Let''s have some tea.', 'authored'),
  ('st-ex-mashou-4', 'sent-ex-mashou-4', 'en', 'Let''s walk a little.', 'authored'),
  ('st-ex-tai-1', 'sent-ex-tai-1', 'en', 'I want to drink water.', 'authored'),
  ('st-ex-tai-2', 'sent-ex-tai-2', 'en', 'I want to watch a film.', 'authored'),
  ('st-ex-tai-3', 'sent-ex-tai-3', 'en', 'I want to go to Japan.', 'authored'),
  ('st-ex-tai-4', 'sent-ex-tai-4', 'en', 'I want to eat fish.', 'authored'),
  ('st-ex-kara-1', 'sent-ex-kara-1', 'en', 'It''s cold, so I''ll close the window.', 'authored'),
  ('st-ex-kara-2', 'sent-ex-kara-2', 'en', 'I''m busy, so I won''t take a break.', 'authored'),
  ('st-ex-kara-3', 'sent-ex-kara-3', 'en', 'It''s cheap, so I''ll buy it.', 'authored'),
  ('st-ex-kara-4', 'sent-ex-kara-4', 'en', 'It''s hot, so I''ll drink some water.', 'authored'),
  ('st-ex-ni-1', 'sent-ex-ni-1', 'en', 'I go to school.', 'authored'),
  ('st-ex-ni-2', 'sent-ex-ni-2', 'en', 'I enter the room.', 'authored'),
  ('st-ex-ni-3', 'sent-ex-ni-3', 'en', 'I get up in the morning.', 'authored'),
  ('st-ex-ni-4', 'sent-ex-ni-4', 'en', 'I come to Japan.', 'authored'),
  ('st-ex-wo-1', 'sent-ex-wo-1', 'en', 'I eat bread.', 'authored'),
  ('st-ex-wo-2', 'sent-ex-wo-2', 'en', 'I listen to music.', 'authored'),
  ('st-ex-wo-3', 'sent-ex-wo-3', 'en', 'I cook a meal.', 'authored'),
  ('st-ex-wo-4', 'sent-ex-wo-4', 'en', 'I buy shoes.', 'authored'),
  ('st-ex-mo-1', 'sent-ex-mo-1', 'en', 'I am a student too.', 'authored'),
  ('st-ex-mo-2', 'sent-ex-mo-2', 'en', 'I like cats too.', 'authored'),
  ('st-ex-mo-3', 'sent-ex-mo-3', 'en', 'My father works too.', 'authored'),
  ('st-ex-mo-4', 'sent-ex-mo-4', 'en', 'I''m busy tomorrow as well.', 'authored'),
  ('st-ex-aru-1', 'sent-ex-aru-1', 'en', 'There is a desk in the room.', 'authored'),
  ('st-ex-aru-2', 'sent-ex-aru-2', 'en', 'There is a teacher at the school.', 'authored'),
  ('st-ex-aru-3', 'sent-ex-aru-3', 'en', 'There is a clock.', 'authored'),
  ('st-ex-aru-4', 'sent-ex-aru-4', 'en', 'There is a cat.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('wa-particle', 'sent-ex-wa-1', 0),
  ('wa-particle', 'sent-ex-wa-2', 1),
  ('wa-particle', 'sent-ex-wa-3', 2),
  ('wa-particle', 'sent-ex-wa-4', 3),
  ('ga-particle', 'sent-ex-ga-1', 0),
  ('ga-particle', 'sent-ex-ga-2', 1),
  ('ga-particle', 'sent-ex-ga-3', 2),
  ('ga-particle', 'sent-ex-ga-4', 3),
  ('kudasai', 'sent-ex-kudasai-1', 0),
  ('kudasai', 'sent-ex-kudasai-2', 1),
  ('kudasai', 'sent-ex-kudasai-3', 2),
  ('kudasai', 'sent-ex-kudasai-4', 3),
  ('mashou', 'sent-ex-mashou-1', 0),
  ('mashou', 'sent-ex-mashou-2', 1),
  ('mashou', 'sent-ex-mashou-3', 2),
  ('mashou', 'sent-ex-mashou-4', 3),
  ('tai', 'sent-ex-tai-1', 0),
  ('tai', 'sent-ex-tai-2', 1),
  ('tai', 'sent-ex-tai-3', 2),
  ('tai', 'sent-ex-tai-4', 3),
  ('kara-reason', 'sent-ex-kara-1', 0),
  ('kara-reason', 'sent-ex-kara-2', 1),
  ('kara-reason', 'sent-ex-kara-3', 2),
  ('kara-reason', 'sent-ex-kara-4', 3),
  ('ni-direction', 'sent-ex-ni-1', 0),
  ('ni-direction', 'sent-ex-ni-2', 1),
  ('ni-direction', 'sent-ex-ni-3', 2),
  ('ni-direction', 'sent-ex-ni-4', 3),
  ('wo-object', 'sent-ex-wo-1', 0),
  ('wo-object', 'sent-ex-wo-2', 1),
  ('wo-object', 'sent-ex-wo-3', 2),
  ('wo-object', 'sent-ex-wo-4', 3),
  ('mo-particle', 'sent-ex-mo-1', 0),
  ('mo-particle', 'sent-ex-mo-2', 1),
  ('mo-particle', 'sent-ex-mo-3', 2),
  ('mo-particle', 'sent-ex-mo-4', 3),
  ('arimasu-imasu', 'sent-ex-aru-1', 0),
  ('arimasu-imasu', 'sent-ex-aru-2', 1),
  ('arimasu-imasu', 'sent-ex-aru-3', 2),
  ('arimasu-imasu', 'sent-ex-aru-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens, so production gets them too.
--
-- `tokenise:authored` is a dev script and production runs migrations and seeds
-- and nothing else, so this is the only way the tokens reach it. Without them
-- the quiz derivation reads an empty table and generates nothing.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-aru-1', 'sent-ex-aru-2', 'sent-ex-aru-3', 'sent-ex-aru-4', 'sent-ex-ga-1', 'sent-ex-ga-2', 'sent-ex-ga-3', 'sent-ex-ga-4', 'sent-ex-kara-1', 'sent-ex-kara-2', 'sent-ex-kara-3', 'sent-ex-kara-4', 'sent-ex-kudasai-1', 'sent-ex-kudasai-2', 'sent-ex-kudasai-3', 'sent-ex-kudasai-4', 'sent-ex-mashou-1', 'sent-ex-mashou-2', 'sent-ex-mashou-3', 'sent-ex-mashou-4', 'sent-ex-mo-1', 'sent-ex-mo-2', 'sent-ex-mo-3', 'sent-ex-mo-4', 'sent-ex-ni-1', 'sent-ex-ni-2', 'sent-ex-ni-3', 'sent-ex-ni-4', 'sent-ex-tai-1', 'sent-ex-tai-2', 'sent-ex-tai-3', 'sent-ex-tai-4', 'sent-ex-wa-1', 'sent-ex-wa-2', 'sent-ex-wa-3', 'sent-ex-wa-4', 'sent-ex-wo-1', 'sent-ex-wo-2', 'sent-ex-wo-3', 'sent-ex-wo-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-wa-1', 0, '父', 'ちち', (select id from words where primary_form = '父' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 1, 'は', 'わ', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 2, '新聞', 'しんぶん', (select id from words where primary_form = '新聞' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 3, 'を', 'お', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 4, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 0, '猫', 'ねこ', (select id from words where primary_form = '猫' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 1, 'は', 'わ', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 2, '小さい', 'ちいさい', (select id from words where primary_form = '小さい' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"小","r":"ちい"},{"t":"さい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 4, 'す', NULL, NULL, 6, 7, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 5, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 0, '山', 'やま', (select id from words where primary_form = '山' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 1, 'は', 'わ', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 2, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 1, 'は', 'わ', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 2, '楽しい', 'たのしい', (select id from words where primary_form = '楽しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"楽","r":"たの"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 2, '降ります', 'ふります', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"降","r":"ふ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 0, '猫', 'ねこ', (select id from words where primary_form = '猫' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 2, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 0, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 2, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 4, 'す', NULL, NULL, 6, 7, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 5, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 0, '花', 'はな', (select id from words where primary_form = '花' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"花","r":"はな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 2, '綺麗', 'きれい', (select id from words where primary_form = '綺麗' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"綺麗","r":"きれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 0, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 2, '開けて', 'あけて', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"開","r":"あ"},{"t":"けて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 3, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 0, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 2, '書いて', 'かいて', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"書","r":"か"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 3, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 4, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 2, '読んで', 'よんで', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 3, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 0, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 2, '見て', 'みて', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 3, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-1', 1, '会いましょう', NULL, (select id from words where primary_form = '会う' and language_id = 'lang-ja' and published order by id limit 1), 2, 8, '[{"t":"会いましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-1', 2, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 0, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 2, '見ましょう', 'みましょう', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"見","r":"み"},{"t":"ましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 3, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 0, 'お茶', 'おちゃ', (select id from words where primary_form = 'お茶' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"茶","r":"ちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 2, '飲みましょう', 'のみましょう', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"飲","r":"の"},{"t":"みましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 3, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-4', 0, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-4', 1, '歩きましょう', 'あるきましょう', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 2, 8, '[{"t":"歩","r":"ある"},{"t":"きましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-4', 2, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 2, '飲みたい', 'のみたい', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"飲","r":"の"},{"t":"みたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 0, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 2, '見たい', 'みたい', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"見","r":"み"},{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 2, '行きたい', 'いきたい', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"行","r":"い"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 4, 'す', NULL, NULL, 8, 9, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 2, '食べたい', 'たべたい', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"食","r":"た"},{"t":"べたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 0, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 2, '、', NULL, NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 3, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 4, 'を', 'お', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 5, '閉めます', 'しめます', (select id from words where primary_form = '閉める' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"閉","r":"し"},{"t":"めます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 2, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 3, '休みません', 'やすみません', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"休","r":"やす"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 4, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 2, '、', NULL, NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 3, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 0, '暑い', 'あつい', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"暑","r":"あつ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 2, '、', NULL, NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 3, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 4, 'を', 'お', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 5, '飲みます', 'のみます', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 0, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 2, '入ります', 'はいります', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"入","r":"はい"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 0, '朝', 'あさ', (select id from words where primary_form = '朝' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 2, '起きます', 'おきます', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"起","r":"お"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 2, '来ます', 'きます', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 0, 'パン', NULL, (select id from words where primary_form = 'パン' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"パン"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 2, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 2, '聞きます', 'ききます', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"聞","r":"き"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 0, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 2, '作ります', 'つくります', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"作","r":"つく"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 0, '靴', 'くつ', (select id from words where primary_form = '靴' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 2, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 1, 'も', NULL, NULL, 1, 2, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 2, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 0, '猫', 'ねこ', (select id from words where primary_form = '猫' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 1, 'も', NULL, NULL, 1, 2, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 2, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 0, '父', 'ちち', (select id from words where primary_form = '父' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 1, 'も', NULL, NULL, 1, 2, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 2, '働きます', 'はたらきます', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 1, 'も', NULL, NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 2, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 2, '机', 'つくえ', (select id from words where primary_form = '机' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 3, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 4, 'あります', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 0, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 2, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 3, 'が', NULL, NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 4, 'います', 'いる', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 0, '時計', 'とけい', (select id from words where primary_form = '時計' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時計","r":"とけい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 1, 'が', NULL, NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 2, 'あります', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 0, '猫', 'ねこ', (select id from words where primary_form = '猫' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 2, 'います', 'いる', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 3, '。', NULL, NULL, 5, 6, '[{"t":"。"}]'::jsonb);;
