-- N5 example sentences, batch 1: ten topics that had none.
--
-- 121 of the 129 published N5 topics have no example sentences, so their lesson
-- is an explanation and a single multiple-choice question. These ten get four
-- sentences each, which is what the teach deck shows and what the word-order,
-- cloze and dictation questions are generated from.
--
-- Every sentence passed `check:examples` BEFORE this file was written. That
-- matters more than it sounds: `glossLine` matches longest-first against
-- published vocabulary only, and a word it does not hold is not left alone but
-- shredded into the characters it can match. A sentence that fails the check
-- reads as nonsense in the lesson and generates nonsense questions, and once a
-- seed has run it never runs again.
--
-- The vocabulary is therefore deliberately narrow — 猫, 山, 窓, 靴, 新聞 — and
-- every verb form was tried before being used. 少し休みましょう had to become
-- 少し歩きましょう because 休み is also a noun, so the tokeniser took it and left
-- ましょう stranded.
--
-- Additive: new sentences, translations and links, nothing updated or removed.
-- Safe on a live database and safe to re-run.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- wa-particle
  ('sent-ex-wa-1', 'lang-ja', '父は新聞を読みます。', 'ちち わ しんぶん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wa-2', 'lang-ja', '猫は小さいです。', 'ねこ わ ちいさい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wa-3', 'lang-ja', '山は高いです。', 'やま わ たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wa-4', 'lang-ja', '音楽は楽しいです。', 'おんがく わ たのしい です。', 'lvl-ja-n5', 'authored', true),
  -- ga-particle
  ('sent-ex-ga-1', 'lang-ja', '雨が降ります。', 'あめ が ふります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ga-2', 'lang-ja', '猫が好きです。', 'ねこ が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ga-3', 'lang-ja', '車が新しいです。', 'くるま が あたらしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ga-4', 'lang-ja', '花が綺麗です。', 'はな が きれい です。', 'lvl-ja-n5', 'authored', true),
  -- kudasai
  ('sent-ex-kudasai-1', 'lang-ja', '窓を開けてください。', 'まど お あけて ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kudasai-2', 'lang-ja', '手紙を書いてください。', 'てがみ お かいて ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kudasai-3', 'lang-ja', '本を読んでください。', 'ほん お よんで ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kudasai-4', 'lang-ja', '写真を見てください。', 'しゃしん お みて ください。', 'lvl-ja-n5', 'authored', true),
  -- mashou
  ('sent-ex-mashou-1', 'lang-ja', '明日会いましょう。', 'あした あいましょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashou-2', 'lang-ja', '映画を見ましょう。', 'えいが お みましょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashou-3', 'lang-ja', 'お茶を飲みましょう。', 'おちゃ お のみましょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashou-4', 'lang-ja', '少し歩きましょう。', 'すこし あるきましょう。', 'lvl-ja-n5', 'authored', true),
  -- tai
  ('sent-ex-tai-1', 'lang-ja', '水が飲みたいです。', 'みず が のみたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tai-2', 'lang-ja', '映画を見たいです。', 'えいが お みたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tai-3', 'lang-ja', '日本に行きたいです。', 'にほん に いきたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tai-4', 'lang-ja', '魚が食べたいです。', 'さかな が たべたい です。', 'lvl-ja-n5', 'authored', true),
  -- kara-reason
  ('sent-ex-kara-1', 'lang-ja', '寒いから、窓を閉めます。', 'さむい から、まど お しめます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kara-2', 'lang-ja', '忙しいから、休みません。', 'いそがしい から、やすみません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kara-3', 'lang-ja', '安いから、買います。', 'やすい から、かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kara-4', 'lang-ja', '暑いから、水を飲みます。', 'あつい から、みず お のみます。', 'lvl-ja-n5', 'authored', true),
  -- ni-direction
  ('sent-ex-ni-1', 'lang-ja', '学校に行きます。', 'がっこう に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ni-2', 'lang-ja', '部屋に入ります。', 'へや に はいります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ni-3', 'lang-ja', '朝に起きます。', 'あさ に おきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ni-4', 'lang-ja', '日本に来ます。', 'にほん に きます。', 'lvl-ja-n5', 'authored', true),
  -- wo-object
  ('sent-ex-wo-1', 'lang-ja', 'パンを食べます。', 'パン お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wo-2', 'lang-ja', '音楽を聞きます。', 'おんがく お ききます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wo-3', 'lang-ja', '料理を作ります。', 'りょうり お つくります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wo-4', 'lang-ja', '靴を買います。', 'くつ お かいます。', 'lvl-ja-n5', 'authored', true),
  -- mo-particle
  ('sent-ex-mo-1', 'lang-ja', '私も学生です。', 'わたし も がくせい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mo-2', 'lang-ja', '猫も好きです。', 'ねこ も すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mo-3', 'lang-ja', '父も働きます。', 'ちち も はたらきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mo-4', 'lang-ja', '明日も忙しいです。', 'あした も いそがしい です。', 'lvl-ja-n5', 'authored', true),
  -- arimasu-imasu
  ('sent-ex-aru-1', 'lang-ja', '部屋に机があります。', 'へや に つくえ が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-aru-2', 'lang-ja', '学校に先生がいます。', 'がっこう に せんせい が います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-aru-3', 'lang-ja', '時計があります。', 'とけい が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-aru-4', 'lang-ja', '猫がいます。', 'ねこ が います。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-wa-1', 'sent-ex-wa-1', 'en', 'My father reads the newspaper.', 'authored'),
  ('st-ex-wa-2', 'sent-ex-wa-2', 'en', 'Cats are small.', 'authored'),
  ('st-ex-wa-3', 'sent-ex-wa-3', 'en', 'The mountain is tall.', 'authored'),
  ('st-ex-wa-4', 'sent-ex-wa-4', 'en', 'Music is fun.', 'authored'),
  ('st-ex-ga-1', 'sent-ex-ga-1', 'en', 'It rains.', 'authored'),
  ('st-ex-ga-2', 'sent-ex-ga-2', 'en', 'I like cats.', 'authored'),
  ('st-ex-ga-3', 'sent-ex-ga-3', 'en', 'The car is new.', 'authored'),
  ('st-ex-ga-4', 'sent-ex-ga-4', 'en', 'The flowers are beautiful.', 'authored'),
  ('st-ex-kudasai-1', 'sent-ex-kudasai-1', 'en', 'Please open the window.', 'authored'),
  ('st-ex-kudasai-2', 'sent-ex-kudasai-2', 'en', 'Please write a letter.', 'authored'),
  ('st-ex-kudasai-3', 'sent-ex-kudasai-3', 'en', 'Please read the book.', 'authored'),
  ('st-ex-kudasai-4', 'sent-ex-kudasai-4', 'en', 'Please look at the photo.', 'authored'),
  ('st-ex-mashou-1', 'sent-ex-mashou-1', 'en', 'Let''s meet tomorrow.', 'authored'),
  ('st-ex-mashou-2', 'sent-ex-mashou-2', 'en', 'Let''s watch a film.', 'authored'),
  ('st-ex-mashou-3', 'sent-ex-mashou-3', 'en', 'Let''s have some tea.', 'authored'),
  ('st-ex-mashou-4', 'sent-ex-mashou-4', 'en', 'Let''s walk a little.', 'authored'),
  ('st-ex-tai-1', 'sent-ex-tai-1', 'en', 'I want to drink water.', 'authored'),
  ('st-ex-tai-2', 'sent-ex-tai-2', 'en', 'I want to watch a film.', 'authored'),
  ('st-ex-tai-3', 'sent-ex-tai-3', 'en', 'I want to go to Japan.', 'authored'),
  ('st-ex-tai-4', 'sent-ex-tai-4', 'en', 'I want to eat fish.', 'authored'),
  ('st-ex-kara-1', 'sent-ex-kara-1', 'en', 'It''s cold, so I''ll close the window.', 'authored'),
  ('st-ex-kara-2', 'sent-ex-kara-2', 'en', 'I''m busy, so I won''t take a break.', 'authored'),
  ('st-ex-kara-3', 'sent-ex-kara-3', 'en', 'It''s cheap, so I''ll buy it.', 'authored'),
  ('st-ex-kara-4', 'sent-ex-kara-4', 'en', 'It''s hot, so I''ll drink some water.', 'authored'),
  ('st-ex-ni-1', 'sent-ex-ni-1', 'en', 'I go to school.', 'authored'),
  ('st-ex-ni-2', 'sent-ex-ni-2', 'en', 'I enter the room.', 'authored'),
  ('st-ex-ni-3', 'sent-ex-ni-3', 'en', 'I get up in the morning.', 'authored'),
  ('st-ex-ni-4', 'sent-ex-ni-4', 'en', 'I come to Japan.', 'authored'),
  ('st-ex-wo-1', 'sent-ex-wo-1', 'en', 'I eat bread.', 'authored'),
  ('st-ex-wo-2', 'sent-ex-wo-2', 'en', 'I listen to music.', 'authored'),
  ('st-ex-wo-3', 'sent-ex-wo-3', 'en', 'I cook a meal.', 'authored'),
  ('st-ex-wo-4', 'sent-ex-wo-4', 'en', 'I buy shoes.', 'authored'),
  ('st-ex-mo-1', 'sent-ex-mo-1', 'en', 'I am a student too.', 'authored'),
  ('st-ex-mo-2', 'sent-ex-mo-2', 'en', 'I like cats too.', 'authored'),
  ('st-ex-mo-3', 'sent-ex-mo-3', 'en', 'My father works too.', 'authored'),
  ('st-ex-mo-4', 'sent-ex-mo-4', 'en', 'I''m busy tomorrow as well.', 'authored'),
  ('st-ex-aru-1', 'sent-ex-aru-1', 'en', 'There is a desk in the room.', 'authored'),
  ('st-ex-aru-2', 'sent-ex-aru-2', 'en', 'There is a teacher at the school.', 'authored'),
  ('st-ex-aru-3', 'sent-ex-aru-3', 'en', 'There is a clock.', 'authored'),
  ('st-ex-aru-4', 'sent-ex-aru-4', 'en', 'There is a cat.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('wa-particle', 'sent-ex-wa-1', 0),
  ('wa-particle', 'sent-ex-wa-2', 1),
  ('wa-particle', 'sent-ex-wa-3', 2),
  ('wa-particle', 'sent-ex-wa-4', 3),
  ('ga-particle', 'sent-ex-ga-1', 0),
  ('ga-particle', 'sent-ex-ga-2', 1),
  ('ga-particle', 'sent-ex-ga-3', 2),
  ('ga-particle', 'sent-ex-ga-4', 3),
  ('kudasai', 'sent-ex-kudasai-1', 0),
  ('kudasai', 'sent-ex-kudasai-2', 1),
  ('kudasai', 'sent-ex-kudasai-3', 2),
  ('kudasai', 'sent-ex-kudasai-4', 3),
  ('mashou', 'sent-ex-mashou-1', 0),
  ('mashou', 'sent-ex-mashou-2', 1),
  ('mashou', 'sent-ex-mashou-3', 2),
  ('mashou', 'sent-ex-mashou-4', 3),
  ('tai', 'sent-ex-tai-1', 0),
  ('tai', 'sent-ex-tai-2', 1),
  ('tai', 'sent-ex-tai-3', 2),
  ('tai', 'sent-ex-tai-4', 3),
  ('kara-reason', 'sent-ex-kara-1', 0),
  ('kara-reason', 'sent-ex-kara-2', 1),
  ('kara-reason', 'sent-ex-kara-3', 2),
  ('kara-reason', 'sent-ex-kara-4', 3),
  ('ni-direction', 'sent-ex-ni-1', 0),
  ('ni-direction', 'sent-ex-ni-2', 1),
  ('ni-direction', 'sent-ex-ni-3', 2),
  ('ni-direction', 'sent-ex-ni-4', 3),
  ('wo-object', 'sent-ex-wo-1', 0),
  ('wo-object', 'sent-ex-wo-2', 1),
  ('wo-object', 'sent-ex-wo-3', 2),
  ('wo-object', 'sent-ex-wo-4', 3),
  ('mo-particle', 'sent-ex-mo-1', 0),
  ('mo-particle', 'sent-ex-mo-2', 1),
  ('mo-particle', 'sent-ex-mo-3', 2),
  ('mo-particle', 'sent-ex-mo-4', 3),
  ('arimasu-imasu', 'sent-ex-aru-1', 0),
  ('arimasu-imasu', 'sent-ex-aru-2', 1),
  ('arimasu-imasu', 'sent-ex-aru-3', 2),
  ('arimasu-imasu', 'sent-ex-aru-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens, so production gets them too.
--
-- `tokenise:authored` is a dev script and production runs migrations and seeds
-- and nothing else, so this is the only way the tokens reach it. Without them
-- the quiz derivation reads an empty table and generates nothing.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-aru-1', 'sent-ex-aru-2', 'sent-ex-aru-3', 'sent-ex-aru-4', 'sent-ex-ga-1', 'sent-ex-ga-2', 'sent-ex-ga-3', 'sent-ex-ga-4', 'sent-ex-kara-1', 'sent-ex-kara-2', 'sent-ex-kara-3', 'sent-ex-kara-4', 'sent-ex-kudasai-1', 'sent-ex-kudasai-2', 'sent-ex-kudasai-3', 'sent-ex-kudasai-4', 'sent-ex-mashou-1', 'sent-ex-mashou-2', 'sent-ex-mashou-3', 'sent-ex-mashou-4', 'sent-ex-mo-1', 'sent-ex-mo-2', 'sent-ex-mo-3', 'sent-ex-mo-4', 'sent-ex-ni-1', 'sent-ex-ni-2', 'sent-ex-ni-3', 'sent-ex-ni-4', 'sent-ex-tai-1', 'sent-ex-tai-2', 'sent-ex-tai-3', 'sent-ex-tai-4', 'sent-ex-wa-1', 'sent-ex-wa-2', 'sent-ex-wa-3', 'sent-ex-wa-4', 'sent-ex-wo-1', 'sent-ex-wo-2', 'sent-ex-wo-3', 'sent-ex-wo-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-wa-1', 0, '父', 'ちち', 'ee283026-0bb8-448f-83e8-204fe427c7b9', 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 1, 'は', 'わ', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 2, '新聞', 'しんぶん', '66072ae2-f8fc-4367-a221-cb59f3ec454a', 2, 4, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 3, 'を', 'お', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 4, '読みます', 'よみます', '1c659ec9-be5a-4805-ab6c-51ceda5763fb', 5, 9, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-1', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 0, '猫', 'ねこ', 'c6ec2551-173f-464c-94d0-4098e1165c3e', 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 1, 'は', 'わ', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 2, '小さい', 'ちいさい', 'f9f80b7b-3c6b-4e48-8bc3-d39f36196925', 2, 5, '[{"t":"小","r":"ちい"},{"t":"さい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 4, 'す', NULL, NULL, 6, 7, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-2', 5, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 0, '山', 'やま', '37b55423-0c09-495a-87e9-1ca7d4bbbeed', 0, 1, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 1, 'は', 'わ', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 2, '高い', 'たかい', 'b9f375ce-c7e3-4b81-bfed-58fb9057bc8a', 2, 4, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-3', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 0, '音楽', 'おんがく', '9996af4b-f2a7-435d-b6e6-c3b784bf93dc', 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 1, 'は', 'わ', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 2, '楽しい', 'たのしい', '4453c4b8-6a8c-4627-b784-b8bb237090b0', 3, 6, '[{"t":"楽","r":"たの"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wa-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 0, '雨', 'あめ', '754619f1-15a8-48dc-a8c0-81c74ea9a69a', 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 2, '降ります', 'ふります', '5ace5ec6-4992-4ab8-abbb-6ee6dd197435', 2, 6, '[{"t":"降","r":"ふ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-1', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 0, '猫', 'ねこ', 'c6ec2551-173f-464c-94d0-4098e1165c3e', 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 2, 4, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-2', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 0, '車', 'くるま', '5dc5735d-214f-4348-b3ee-a0fb3c4bdb9f', 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 2, '新しい', 'あたらしい', 'f4c48018-6652-4f08-8980-44a5339d40b1', 2, 5, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 4, 'す', NULL, NULL, 6, 7, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-3', 5, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 0, '花', 'はな', '3fd50ae6-11ab-45cc-aa4d-734bc685823d', 0, 1, '[{"t":"花","r":"はな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 2, '綺麗', 'きれい', '47370d32-ec9b-41e7-a8cc-a58a93ff9014', 2, 4, '[{"t":"綺麗","r":"きれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ga-4', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 0, '窓', 'まど', '590df083-c00c-4652-bcdd-f7630ff251d0', 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 2, '開けて', 'あけて', '8fba3d97-141b-4404-86e7-6530e7c19e3c', 2, 5, '[{"t":"開","r":"あ"},{"t":"けて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 3, 'ください', NULL, '1ae2c483-be5f-49ac-ae8b-388c185550f1', 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-1', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 0, '手紙', 'てがみ', '041bc6df-1284-47ba-95ff-b197c144f360', 0, 2, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 2, '書いて', 'かいて', 'd28ed980-0333-4bf5-aab0-e7947c6ee424', 3, 6, '[{"t":"書","r":"か"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 3, 'ください', NULL, '1ae2c483-be5f-49ac-ae8b-388c185550f1', 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-2', 4, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 2, '読んで', 'よんで', '1c659ec9-be5a-4805-ab6c-51ceda5763fb', 2, 5, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 3, 'ください', NULL, '1ae2c483-be5f-49ac-ae8b-388c185550f1', 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-3', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 0, '写真', 'しゃしん', '22d349ca-aa49-4f0e-b283-319611ccdf3c', 0, 2, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 2, '見て', 'みて', '85ec6cc4-0dca-4479-abcf-d53e33fc9e49', 3, 5, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 3, 'ください', NULL, '1ae2c483-be5f-49ac-ae8b-388c185550f1', 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kudasai-4', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-1', 0, '明日', 'あした', '823cfb1a-cb34-4c88-86d6-5cdfca69eed5', 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-1', 1, '会いましょう', NULL, '887821df-833f-4aac-a413-7ae78d3cfe17', 2, 8, '[{"t":"会いましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-1', 2, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 0, '映画', 'えいが', '94093c2a-fa1e-4b90-9f87-b13ba46cd7fb', 0, 2, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 2, '見ましょう', 'みましょう', '85ec6cc4-0dca-4479-abcf-d53e33fc9e49', 3, 8, '[{"t":"見","r":"み"},{"t":"ましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-2', 3, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 0, 'お茶', 'おちゃ', '99ec9749-6643-4371-9ba0-25d05cb28c8a', 0, 2, '[{"t":"お"},{"t":"茶","r":"ちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 2, '飲みましょう', 'のみましょう', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 3, 9, '[{"t":"飲","r":"の"},{"t":"みましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-3', 3, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-4', 0, '少し', 'すこし', 'c3fea249-9141-44a5-a822-a2bbe599d73d', 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-4', 1, '歩きましょう', 'あるきましょう', '0b7f8e92-250b-4efd-9746-a8b08960d587', 2, 8, '[{"t":"歩","r":"ある"},{"t":"きましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashou-4', 2, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 0, '水', 'みず', '02cd9dd6-94a1-43e7-9e49-2dfff6e0edf2', 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 2, '飲みたい', 'のみたい', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 2, 6, '[{"t":"飲","r":"の"},{"t":"みたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-1', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 0, '映画', 'えいが', '94093c2a-fa1e-4b90-9f87-b13ba46cd7fb', 0, 2, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 2, '見たい', 'みたい', '85ec6cc4-0dca-4479-abcf-d53e33fc9e49', 3, 6, '[{"t":"見","r":"み"},{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-2', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 0, '日本', 'にほん', '9de924d0-d7d7-4284-bbae-c05ecbef3e5e', 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 1, 'に', NULL, '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 2, '行きたい', 'いきたい', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 3, 7, '[{"t":"行","r":"い"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 4, 'す', NULL, NULL, 8, 9, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-3', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 0, '魚', 'さかな', 'e1e048a7-24b7-4875-8727-b61a2e2c4857', 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 2, '食べたい', 'たべたい', '788557df-2bac-4ae7-a157-8a81fbe1da16', 2, 6, '[{"t":"食","r":"た"},{"t":"べたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tai-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 0, '寒い', 'さむい', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 2, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 1, 'から', NULL, '22b44903-fdbc-4403-b597-a713aae7507f', 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 2, '、', NULL, NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 3, '窓', 'まど', '590df083-c00c-4652-bcdd-f7630ff251d0', 5, 6, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 4, 'を', 'お', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 5, '閉めます', 'しめます', '04878ef8-4532-4802-a9a4-942ed222f860', 7, 11, '[{"t":"閉","r":"し"},{"t":"めます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-1', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 0, '忙しい', 'いそがしい', '65ae7422-9448-4faa-b28d-f80a027123bf', 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 1, 'から', NULL, '22b44903-fdbc-4403-b597-a713aae7507f', 3, 5, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 2, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 3, '休みません', 'やすみません', '52fd60de-a97d-47be-9b31-894be752027a', 6, 11, '[{"t":"休","r":"やす"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-2', 4, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 0, '安い', 'やすい', '817cb322-0f7f-4c83-a195-dde87e4bd13f', 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 1, 'から', NULL, '22b44903-fdbc-4403-b597-a713aae7507f', 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 2, '、', NULL, NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 3, '買います', 'かいます', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 5, 9, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-3', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 0, '暑い', 'あつい', '24ba41c3-4af8-45a2-9f3a-318c80560e5b', 0, 2, '[{"t":"暑","r":"あつ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 1, 'から', NULL, '22b44903-fdbc-4403-b597-a713aae7507f', 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 2, '、', NULL, NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 3, '水', 'みず', '02cd9dd6-94a1-43e7-9e49-2dfff6e0edf2', 5, 6, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 4, 'を', 'お', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 5, '飲みます', 'のみます', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 7, 11, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kara-4', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 0, '学校', 'がっこう', 'c6989610-93a3-4175-8b9c-d969d934a05a', 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 1, 'に', NULL, '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 2, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-1', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 0, '部屋', 'へや', 'e1bce843-0d3a-4107-9293-11fbdd4312c7', 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 1, 'に', NULL, '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 2, '入ります', 'はいります', 'f50ebbe5-7336-454a-b70e-da6cb8332d88', 3, 7, '[{"t":"入","r":"はい"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-2', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 0, '朝', 'あさ', 'd69bdfb8-8f9e-40d7-800c-f6361221d7b2', 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 1, 'に', NULL, '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 2, '起きます', 'おきます', '5fb365d9-60b4-4d75-a1c7-5170ce4bbcf5', 2, 6, '[{"t":"起","r":"お"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-3', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 0, '日本', 'にほん', '9de924d0-d7d7-4284-bbae-c05ecbef3e5e', 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 1, 'に', NULL, '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 2, '来ます', 'きます', 'e40f6686-fee0-4bc0-820d-ba5c272193a8', 3, 6, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ni-4', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 0, 'パン', NULL, '43f9f85f-e28d-4e4e-bd10-5d21644d7431', 0, 2, '[{"t":"パン"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 2, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 3, 7, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-1', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 0, '音楽', 'おんがく', '9996af4b-f2a7-435d-b6e6-c3b784bf93dc', 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 2, '聞きます', 'ききます', 'c1cb817b-80ef-4ac2-8fd6-995a7ea99784', 3, 7, '[{"t":"聞","r":"き"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-2', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 0, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 0, 2, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 2, '作ります', 'つくります', '65a81607-104f-4156-987e-b1b2edeafe4f', 3, 7, '[{"t":"作","r":"つく"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-3', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 0, '靴', 'くつ', 'da19bf49-6698-4142-bf0f-90077a00f120', 0, 1, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 2, '買います', 'かいます', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 2, 6, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wo-4', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 0, '私', 'わたし', '07d07dec-dc8f-45b2-8095-b49b5087da75', 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 1, 'も', NULL, NULL, 1, 2, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 2, '学生', 'がくせい', '15fb2da0-1205-42cf-8c9c-59295ac9fb62', 2, 4, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-1', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 0, '猫', 'ねこ', 'c6ec2551-173f-464c-94d0-4098e1165c3e', 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 1, 'も', NULL, NULL, 1, 2, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 2, 4, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-2', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 0, '父', 'ちち', 'ee283026-0bb8-448f-83e8-204fe427c7b9', 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 1, 'も', NULL, NULL, 1, 2, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 2, '働きます', 'はたらきます', '75abeac3-31b6-44dd-8434-96e88d07f940', 2, 6, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-3', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 0, '明日', 'あした', '823cfb1a-cb34-4c88-86d6-5cdfca69eed5', 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 1, 'も', NULL, NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 2, '忙しい', 'いそがしい', '65ae7422-9448-4faa-b28d-f80a027123bf', 3, 6, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 3, 'で', NULL, '107c2108-67cd-4a47-b42b-0e4f19b2a745', 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mo-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 0, '部屋', 'へや', 'e1bce843-0d3a-4107-9293-11fbdd4312c7', 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 1, 'に', NULL, '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 2, '机', 'つくえ', '0e738844-19ce-48ea-b9b2-0ff1a120b423', 3, 4, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 3, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 4, 'あります', 'ある', 'e95a2a8b-2112-4767-b118-008d51786f36', 5, 9, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-1', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 0, '学校', 'がっこう', 'c6989610-93a3-4175-8b9c-d969d934a05a', 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 1, 'に', NULL, '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 2, '先生', 'せんせい', 'f2bd1cf4-e22c-48f8-a563-771e2f0599a9', 3, 5, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 3, 'が', NULL, NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 4, 'います', 'いる', '2e8dd83a-7a6a-43db-853d-072f7519c172', 6, 9, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-2', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 0, '時計', 'とけい', '413a14d5-27ae-4e9a-9087-7e9a8b26f506', 0, 2, '[{"t":"時計","r":"とけい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 1, 'が', NULL, NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 2, 'あります', 'ある', 'e95a2a8b-2112-4767-b118-008d51786f36', 3, 7, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-3', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 0, '猫', 'ねこ', 'c6ec2551-173f-464c-94d0-4098e1165c3e', 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 2, 'います', 'いる', '2e8dd83a-7a6a-43db-853d-072f7519c172', 2, 5, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aru-4', 3, '。', NULL, NULL, 5, 6, '[{"t":"。"}]'::jsonb);;
