-- N5 example sentences, batch 2: ten more topics.
--
-- Same shape as 056 and the same rule: every sentence passed `check:examples`
-- before this file existed.
--
-- Two topics that should have been in this batch are NOT here, because the
-- tokeniser cannot read their own pattern:
--
--   〜てもいい          もいい cuts as も | い | い
--   〜なければなりません  なければ cuts as な | け | れ | ば
--
-- Neither is a word the dictionary holds — they are grammar, assembled from
-- pieces — and いい is deliberately blocked besides, because 飯 "cooked rice"
-- is also read いい and would claim the spelling. A lesson whose example
-- sentences shred the very pattern they teach is worse than no lesson, so they
-- wait for the tokeniser to learn about grammar patterns. i-adjective and
-- na-adjective take their place here.
--
-- 〜が (but) is written as ますが rather than ですが throughout: です has no
-- dictionary entry and always splits into で + す, which passes unnoticed at the
-- end of a sentence and reads as shredded kana in the middle of one.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- no-possessive
  ('sent-ex-no-1', 'lang-ja', '父の車です。', 'ちち の くるま です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-no-2', 'lang-ja', '学校の先生です。', 'がっこう の せんせい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-no-3', 'lang-ja', '日本の音楽が好きです。', 'にほん の おんがく が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-no-4', 'lang-ja', '部屋の窓を開けます。', 'へや の まど お あけます。', 'lvl-ja-n5', 'authored', true),
  -- ka-question
  ('sent-ex-ka-1', 'lang-ja', '学生ですか。', 'がくせい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ka-2', 'lang-ja', '音楽を聞きますか。', 'おんがく お ききます か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ka-3', 'lang-ja', '魚が好きですか。', 'さかな が すき です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ka-4', 'lang-ja', '明日来ますか。', 'あした きます か。', 'lvl-ja-n5', 'authored', true),
  -- de-location
  ('sent-ex-deloc-1', 'lang-ja', '学校で勉強します。', 'がっこう で べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deloc-2', 'lang-ja', '部屋で音楽を聞きます。', 'へや で おんがく お ききます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deloc-3', 'lang-ja', '海で泳ぎます。', 'うみ で およぎます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deloc-4', 'lang-ja', '店でパンを買います。', 'みせ で パン お かいます。', 'lvl-ja-n5', 'authored', true),
  -- de-means
  ('sent-ex-demeans-1', 'lang-ja', '電車で行きます。', 'でんしゃ で いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-demeans-2', 'lang-ja', '車で来ます。', 'くるま で きます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-demeans-3', 'lang-ja', '手で作ります。', 'て で つくります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-demeans-4', 'lang-ja', '水で洗います。', 'みず で あらいます。', 'lvl-ja-n5', 'authored', true),
  -- he-direction
  ('sent-ex-he-1', 'lang-ja', '学校へ行きます。', 'がっこう え いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-he-2', 'lang-ja', '日本へ来ます。', 'にほん え きます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-he-3', 'lang-ja', '海へ行きたいです。', 'うみ え いきたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-he-4', 'lang-ja', '部屋へ入ります。', 'へや え はいります。', 'lvl-ja-n5', 'authored', true),
  -- to-with
  ('sent-ex-to-1', 'lang-ja', '友達と行きます。', 'ともだち と いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-to-2', 'lang-ja', '父と話します。', 'ちち と はなします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-to-3', 'lang-ja', '猫と遊びます。', 'ねこ と あそびます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-to-4', 'lang-ja', '魚と肉を買います。', 'さかな と にく お かいます。', 'lvl-ja-n5', 'authored', true),
  -- ya-particle
  ('sent-ex-ya-1', 'lang-ja', '魚や肉を食べます。', 'さかな や にく お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ya-2', 'lang-ja', '本や新聞を読みます。', 'ほん や しんぶん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ya-3', 'lang-ja', '山や海が好きです。', 'やま や うみ が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ya-4', 'lang-ja', '靴や服を買います。', 'くつ や ふく お かいます。', 'lvl-ja-n5', 'authored', true),
  -- ga-but
  ('sent-ex-gabut-1', 'lang-ja', '買いますが、高いです。', 'かいます が、たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gabut-2', 'lang-ja', '行きますが、忙しいです。', 'いきます が、いそがしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gabut-3', 'lang-ja', '魚を食べますが、肉は食べません。', 'さかな お たべます が、にく わ たべません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gabut-4', 'lang-ja', '泳ぎますが、寒いです。', 'およぎます が、さむい です。', 'lvl-ja-n5', 'authored', true),
  -- i-adjective
  ('sent-ex-iadj-1', 'lang-ja', '大きい山が見えます。', 'おおきい やま が みえます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadj-2', 'lang-ja', '新しい車を買いました。', 'あたらしい くるま お かいました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadj-3', 'lang-ja', '古い本を読みます。', 'ふるい ほん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadj-4', 'lang-ja', '暑い日は水を飲みます。', 'あつい ひ わ みず お のみます。', 'lvl-ja-n5', 'authored', true),
  -- na-adjective
  ('sent-ex-naadj-1', 'lang-ja', '静かな部屋で勉強します。', 'しずかな へや で べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naadj-2', 'lang-ja', '綺麗な花を買います。', 'きれいな はな お かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naadj-3', 'lang-ja', '元気な猫です。', 'げんきな ねこ です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naadj-4', 'lang-ja', '便利な店です。', 'べんりな みせ です。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-no-1', 'sent-ex-no-1', 'en', 'It''s my father''s car.', 'authored'),
  ('st-ex-no-2', 'sent-ex-no-2', 'en', 'It''s the school teacher.', 'authored'),
  ('st-ex-no-3', 'sent-ex-no-3', 'en', 'I like Japanese music.', 'authored'),
  ('st-ex-no-4', 'sent-ex-no-4', 'en', 'I open the room''s window.', 'authored'),
  ('st-ex-ka-1', 'sent-ex-ka-1', 'en', 'Are you a student?', 'authored'),
  ('st-ex-ka-2', 'sent-ex-ka-2', 'en', 'Do you listen to music?', 'authored'),
  ('st-ex-ka-3', 'sent-ex-ka-3', 'en', 'Do you like fish?', 'authored'),
  ('st-ex-ka-4', 'sent-ex-ka-4', 'en', 'Are you coming tomorrow?', 'authored'),
  ('st-ex-deloc-1', 'sent-ex-deloc-1', 'en', 'I study at school.', 'authored'),
  ('st-ex-deloc-2', 'sent-ex-deloc-2', 'en', 'I listen to music in my room.', 'authored'),
  ('st-ex-deloc-3', 'sent-ex-deloc-3', 'en', 'I swim in the sea.', 'authored'),
  ('st-ex-deloc-4', 'sent-ex-deloc-4', 'en', 'I buy bread at the shop.', 'authored'),
  ('st-ex-demeans-1', 'sent-ex-demeans-1', 'en', 'I go by train.', 'authored'),
  ('st-ex-demeans-2', 'sent-ex-demeans-2', 'en', 'I come by car.', 'authored'),
  ('st-ex-demeans-3', 'sent-ex-demeans-3', 'en', 'I make it by hand.', 'authored'),
  ('st-ex-demeans-4', 'sent-ex-demeans-4', 'en', 'I wash it with water.', 'authored'),
  ('st-ex-he-1', 'sent-ex-he-1', 'en', 'I go to school.', 'authored'),
  ('st-ex-he-2', 'sent-ex-he-2', 'en', 'I come to Japan.', 'authored'),
  ('st-ex-he-3', 'sent-ex-he-3', 'en', 'I want to go to the sea.', 'authored'),
  ('st-ex-he-4', 'sent-ex-he-4', 'en', 'I go into the room.', 'authored'),
  ('st-ex-to-1', 'sent-ex-to-1', 'en', 'I go with a friend.', 'authored'),
  ('st-ex-to-2', 'sent-ex-to-2', 'en', 'I talk with my father.', 'authored'),
  ('st-ex-to-3', 'sent-ex-to-3', 'en', 'I play with the cat.', 'authored'),
  ('st-ex-to-4', 'sent-ex-to-4', 'en', 'I buy fish and meat.', 'authored'),
  ('st-ex-ya-1', 'sent-ex-ya-1', 'en', 'I eat fish, meat and so on.', 'authored'),
  ('st-ex-ya-2', 'sent-ex-ya-2', 'en', 'I read books, newspapers and the like.', 'authored'),
  ('st-ex-ya-3', 'sent-ex-ya-3', 'en', 'I like mountains, the sea and so on.', 'authored'),
  ('st-ex-ya-4', 'sent-ex-ya-4', 'en', 'I buy shoes, clothes and so on.', 'authored'),
  ('st-ex-gabut-1', 'sent-ex-gabut-1', 'en', 'I''ll buy it, but it''s expensive.', 'authored'),
  ('st-ex-gabut-2', 'sent-ex-gabut-2', 'en', 'I''ll go, but I''m busy.', 'authored'),
  ('st-ex-gabut-3', 'sent-ex-gabut-3', 'en', 'I eat fish, but I don''t eat meat.', 'authored'),
  ('st-ex-gabut-4', 'sent-ex-gabut-4', 'en', 'I''ll swim, but it''s cold.', 'authored'),
  ('st-ex-iadj-1', 'sent-ex-iadj-1', 'en', 'I can see a big mountain.', 'authored'),
  ('st-ex-iadj-2', 'sent-ex-iadj-2', 'en', 'I bought a new car.', 'authored'),
  ('st-ex-iadj-3', 'sent-ex-iadj-3', 'en', 'I read an old book.', 'authored'),
  ('st-ex-iadj-4', 'sent-ex-iadj-4', 'en', 'On hot days I drink water.', 'authored'),
  ('st-ex-naadj-1', 'sent-ex-naadj-1', 'en', 'I study in a quiet room.', 'authored'),
  ('st-ex-naadj-2', 'sent-ex-naadj-2', 'en', 'I buy beautiful flowers.', 'authored'),
  ('st-ex-naadj-3', 'sent-ex-naadj-3', 'en', 'It''s a lively cat.', 'authored'),
  ('st-ex-naadj-4', 'sent-ex-naadj-4', 'en', 'It''s a convenient shop.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('no-possessive', 'sent-ex-no-1', 0),
  ('no-possessive', 'sent-ex-no-2', 1),
  ('no-possessive', 'sent-ex-no-3', 2),
  ('no-possessive', 'sent-ex-no-4', 3),
  ('ka-question', 'sent-ex-ka-1', 0),
  ('ka-question', 'sent-ex-ka-2', 1),
  ('ka-question', 'sent-ex-ka-3', 2),
  ('ka-question', 'sent-ex-ka-4', 3),
  ('de-location', 'sent-ex-deloc-1', 0),
  ('de-location', 'sent-ex-deloc-2', 1),
  ('de-location', 'sent-ex-deloc-3', 2),
  ('de-location', 'sent-ex-deloc-4', 3),
  ('de-means', 'sent-ex-demeans-1', 0),
  ('de-means', 'sent-ex-demeans-2', 1),
  ('de-means', 'sent-ex-demeans-3', 2),
  ('de-means', 'sent-ex-demeans-4', 3),
  ('he-direction', 'sent-ex-he-1', 0),
  ('he-direction', 'sent-ex-he-2', 1),
  ('he-direction', 'sent-ex-he-3', 2),
  ('he-direction', 'sent-ex-he-4', 3),
  ('to-with', 'sent-ex-to-1', 0),
  ('to-with', 'sent-ex-to-2', 1),
  ('to-with', 'sent-ex-to-3', 2),
  ('to-with', 'sent-ex-to-4', 3),
  ('ya-particle', 'sent-ex-ya-1', 0),
  ('ya-particle', 'sent-ex-ya-2', 1),
  ('ya-particle', 'sent-ex-ya-3', 2),
  ('ya-particle', 'sent-ex-ya-4', 3),
  ('ga-but', 'sent-ex-gabut-1', 0),
  ('ga-but', 'sent-ex-gabut-2', 1),
  ('ga-but', 'sent-ex-gabut-3', 2),
  ('ga-but', 'sent-ex-gabut-4', 3),
  ('i-adjective', 'sent-ex-iadj-1', 0),
  ('i-adjective', 'sent-ex-iadj-2', 1),
  ('i-adjective', 'sent-ex-iadj-3', 2),
  ('i-adjective', 'sent-ex-iadj-4', 3),
  ('na-adjective', 'sent-ex-naadj-1', 0),
  ('na-adjective', 'sent-ex-naadj-2', 1),
  ('na-adjective', 'sent-ex-naadj-3', 2),
  ('na-adjective', 'sent-ex-naadj-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens, so production gets them too.
--
-- `tokenise:authored` is a dev script and production runs migrations and
-- seeds and nothing else, so this is the only way the tokens reach it.
-- Word-order chips and cloze spans are cut from `sentence_tokens`, never
-- from the sentence text, so without these the derivation in 059 would read
-- an empty table and generate nothing.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-no-1', 'sent-ex-no-2', 'sent-ex-no-3', 'sent-ex-no-4', 'sent-ex-ka-1', 'sent-ex-ka-2', 'sent-ex-ka-3', 'sent-ex-ka-4', 'sent-ex-deloc-1', 'sent-ex-deloc-2', 'sent-ex-deloc-3', 'sent-ex-deloc-4', 'sent-ex-demeans-1', 'sent-ex-demeans-2', 'sent-ex-demeans-3', 'sent-ex-demeans-4', 'sent-ex-he-1', 'sent-ex-he-2', 'sent-ex-he-3', 'sent-ex-he-4', 'sent-ex-to-1', 'sent-ex-to-2', 'sent-ex-to-3', 'sent-ex-to-4', 'sent-ex-ya-1', 'sent-ex-ya-2', 'sent-ex-ya-3', 'sent-ex-ya-4', 'sent-ex-gabut-1', 'sent-ex-gabut-2', 'sent-ex-gabut-3', 'sent-ex-gabut-4', 'sent-ex-iadj-1', 'sent-ex-iadj-2', 'sent-ex-iadj-3', 'sent-ex-iadj-4', 'sent-ex-naadj-1', 'sent-ex-naadj-2', 'sent-ex-naadj-3', 'sent-ex-naadj-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-no-1', 0, '父', 'ちち', (select id from words where primary_form = '父' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-1', 1, 'の', NULL, NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-1', 2, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-1', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-1', 4, 'す', NULL, NULL, 4, 5, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-1', 5, '。', NULL, NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-2', 0, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-2', 1, 'の', NULL, NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-2', 2, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-2', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-2', 4, 'す', NULL, NULL, 6, 7, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-2', 5, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 1, 'の', NULL, NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 2, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 3, 'が', NULL, NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 4, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 5, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 6, 'す', NULL, NULL, 9, 10, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-3', 7, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-4', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-4', 1, 'の', NULL, NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-4', 2, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-4', 3, 'を', 'お', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-4', 4, '開けます', 'あけます', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"開","r":"あ"},{"t":"けます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-no-4', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-1', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-1', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-1', 2, 'す', NULL, NULL, 3, 4, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-1', 3, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-1', 4, '。', NULL, NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-2', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-2', 2, '聞きます', 'ききます', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"聞","r":"き"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-2', 3, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-2', 4, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-3', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-3', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-3', 2, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-3', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-3', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-3', 5, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-3', 6, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-4', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-4', 1, '来ます', NULL, (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"来ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-4', 2, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ka-4', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-1', 0, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-1', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-1', 2, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-1', 3, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-2', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-2', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-2', 2, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-2', 3, 'を', 'お', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-2', 4, '聞きます', 'ききます', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"聞","r":"き"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-2', 5, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-3', 0, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-3', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-3', 2, '泳ぎます', 'およぎます', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"泳","r":"およ"},{"t":"ぎます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-3', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-4', 0, '店', 'てん', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"店","r":"てん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-4', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-4', 2, 'パン', NULL, (select id from words where primary_form = 'パン' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"パン"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-4', 3, 'を', 'お', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-4', 4, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deloc-4', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-1', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-1', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-1', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-1', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-2', 0, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-2', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-2', 2, '来ます', 'きます', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-2', 3, '。', NULL, NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-3', 0, '手', 'て', (select id from words where primary_form = '手' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"手","r":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-3', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-3', 2, '作ります', 'つくります', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"作","r":"つく"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-3', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-4', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-4', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-4', 2, '洗います', 'あらいます', (select id from words where primary_form = '洗う' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"洗","r":"あら"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-demeans-4', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-1', 0, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-1', 1, 'へ', 'え', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-1', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-1', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-2', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-2', 1, 'へ', 'え', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-2', 2, '来ます', 'きます', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-2', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-3', 0, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-3', 1, 'へ', 'え', NULL, 1, 2, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-3', 2, '行きたい', 'いきたい', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"行","r":"い"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-3', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-3', 4, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-3', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-4', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-4', 1, 'へ', 'え', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-4', 2, '入ります', 'はいります', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"入","r":"はい"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-he-4', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-1', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-1', 1, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-1', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-1', 3, '。', NULL, NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-2', 0, '父', 'ちち', (select id from words where primary_form = '父' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-2', 1, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-2', 2, '話します', 'はなします', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"話","r":"はな"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-2', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-3', 0, '猫', 'ねこ', (select id from words where primary_form = '猫' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-3', 1, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-3', 2, '遊びます', 'あそびます', (select id from words where primary_form = '遊ぶ' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"遊","r":"あそ"},{"t":"びます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-3', 3, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-4', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-4', 1, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-4', 2, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-4', 3, 'を', 'お', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-4', 4, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-to-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-1', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-1', 1, 'や', NULL, (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-1', 2, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-1', 3, 'を', 'お', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-1', 4, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-1', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-2', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-2', 1, 'や', NULL, (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-2', 2, '新聞', 'しんぶん', (select id from words where primary_form = '新聞' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-2', 3, 'を', 'お', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-2', 4, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-2', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 0, '山', 'やま', (select id from words where primary_form = '山' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 1, 'や', NULL, (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 2, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 3, 'が', NULL, NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 4, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 5, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 6, 'す', NULL, NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-3', 7, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-4', 0, '靴', 'くつ', (select id from words where primary_form = '靴' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-4', 1, 'や', NULL, (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-4', 2, '服', 'ふく', (select id from words where primary_form = '服' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"服","r":"ふく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-4', 3, 'を', 'お', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-4', 4, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ya-4', 5, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-1', 0, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-1', 1, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-1', 2, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-1', 3, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-1', 4, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-1', 5, 'す', NULL, NULL, 9, 10, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-1', 6, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-2', 0, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-2', 1, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-2', 2, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-2', 3, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-2', 4, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-2', 5, 'す', NULL, NULL, 10, 11, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-2', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 2, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 3, 'が', NULL, NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 4, '、', NULL, NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 5, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 6, 'は', 'わ', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 7, '食べません', 'たべません', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"食","r":"た"},{"t":"べません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-3', 8, '。', NULL, NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-4', 0, '泳ぎます', 'およぎます', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"泳","r":"およ"},{"t":"ぎます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-4', 1, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-4', 2, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-4', 3, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-4', 4, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-4', 5, 'す', NULL, NULL, 9, 10, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gabut-4', 6, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-1', 0, '大きい', 'おおきい', (select id from words where primary_form = '大きい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"大","r":"おお"},{"t":"きい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-1', 1, '山', 'やま', (select id from words where primary_form = '山' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-1', 2, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-1', 3, '見えます', 'みえます', (select id from words where primary_form = '見える' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"見","r":"み"},{"t":"えます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-1', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-2', 0, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-2', 1, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-2', 2, 'を', 'お', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-2', 3, '買いました', 'かいました', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"買","r":"か"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-2', 4, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-3', 0, '古い', 'ふるい', (select id from words where primary_form = '古い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"古","r":"ふる"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-3', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-3', 2, 'を', 'お', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-3', 3, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-3', 4, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-4', 0, '暑い', 'あつい', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"暑","r":"あつ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-4', 1, '日', 'ひ', (select id from words where primary_form = '日' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"日","r":"ひ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-4', 2, 'は', 'わ', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-4', 3, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-4', 4, 'を', 'お', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-4', 5, '飲みます', 'のみます', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadj-4', 6, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-1', 0, '静か', 'しずか', (select id from words where primary_form = '静か' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"静","r":"しず"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-1', 1, 'な', NULL, (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-1', 2, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-1', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-1', 4, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-1', 5, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-2', 0, '綺麗', 'きれい', (select id from words where primary_form = '綺麗' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"綺麗","r":"きれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-2', 1, 'な', NULL, (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-2', 2, '花', 'はな', (select id from words where primary_form = '花' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"花","r":"はな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-2', 3, 'を', 'お', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-2', 4, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-2', 5, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-3', 0, '元気', 'げんき', (select id from words where primary_form = '元気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"元気","r":"げんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-3', 1, 'な', NULL, (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-3', 2, '猫', 'ねこ', (select id from words where primary_form = '猫' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-3', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-3', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-3', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-4', 0, '便利', 'べんり', (select id from words where primary_form = '便利' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"便利","r":"べんり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-4', 1, 'な', NULL, (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-4', 2, '店', 'てん', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"店","r":"てん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-4', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-4', 4, 'す', NULL, NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadj-4', 5, '。', NULL, NULL, 6, 7, '[{"t":"。"}]'::jsonb);
