-- N5 example sentences, batch 3: から〜まで, より, 〜ませんか, 〜ないでください,
-- 〜たことがある, 〜ながら, 〜前に, 〜後で, とき and 〜たら.
--
-- One more topic joins the blocked list from 058: けど cuts as け | ど, the same
-- way もいい and なければ do. That is now three N5 topics — 〜てもいい,
-- 〜なければなりません and けど — waiting on the tokeniser learning to read a
-- grammar pattern as one unit.
--
-- Two rewrites the checker forced, both the same trap: a verb's ます stem is
-- often also a noun, and the tokeniser takes the noun and strands the grammar.
-- 新聞を読みながら came apart as 読み | な | が | ら, so the sentence uses
-- 聞きながら instead. 少し休みましょう hit this in 056.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- kara-made
  ('sent-ex-karamade-1', 'lang-ja', '学校から海まで歩きます。', 'がっこう から うみ まで あるきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-karamade-2', 'lang-ja', '朝から夜まで勉強します。', 'あさ から よる まで べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-karamade-3', 'lang-ja', '月曜日から金曜日まで働きます。', 'げつようび から きんようび まで はたらきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-karamade-4', 'lang-ja', '家から会社まで電車で行きます。', 'いえ から かいしゃ まで でんしゃ で いきます。', 'lvl-ja-n5', 'authored', true),
  -- yori
  ('sent-ex-yori-1', 'lang-ja', '魚より肉が好きです。', 'さかな より にく が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-yori-2', 'lang-ja', '車より電車が速いです。', 'くるま より でんしゃ が はやい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-yori-3', 'lang-ja', '山より海が好きです。', 'やま より うみ が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-yori-4', 'lang-ja', '本より映画が面白いです。', 'ほん より えいが が おもしろい です。', 'lvl-ja-n5', 'authored', true),
  -- masen-ka
  ('sent-ex-masenka-1', 'lang-ja', '一緒に行きませんか。', 'いっしょ に いきません か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masenka-2', 'lang-ja', '映画を見ませんか。', 'えいが お みません か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masenka-3', 'lang-ja', 'お茶を飲みませんか。', 'おちゃ お のみません か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masenka-4', 'lang-ja', '海で泳ぎませんか。', 'うみ で およぎません か。', 'lvl-ja-n5', 'authored', true),
  -- naide-kudasai
  ('sent-ex-naide-1', 'lang-ja', '水を飲まないでください。', 'みず お のまないで ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naide-2', 'lang-ja', '窓を開けないでください。', 'まど お あけないで ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naide-3', 'lang-ja', '写真を撮らないでください。', 'しゃしん お とらないで ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naide-4', 'lang-ja', '走らないでください。', 'はしらないで ください。', 'lvl-ja-n5', 'authored', true),
  -- ta-koto-ga-aru
  ('sent-ex-takoto-1', 'lang-ja', '日本へ行ったことがあります。', 'にほん え いった こと が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-takoto-2', 'lang-ja', '魚を食べたことがあります。', 'さかな お たべた こと が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-takoto-3', 'lang-ja', '海で泳いだことがあります。', 'うみ で およいだ こと が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-takoto-4', 'lang-ja', '日本の音楽を聞いたことがあります。', 'にほん の おんがく お きいた こと が あります。', 'lvl-ja-n5', 'authored', true),
  -- nagara
  ('sent-ex-nagara-1', 'lang-ja', '音楽を聞きながら勉強します。', 'おんがく お ききながら べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nagara-2', 'lang-ja', '歩きながら話します。', 'あるきながら はなします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nagara-3', 'lang-ja', 'テレビを見ながら食べます。', 'テレビ お みながら たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nagara-4', 'lang-ja', '音楽を聞きながらご飯を食べます。', 'おんがく お ききながら ごはん お たべます。', 'lvl-ja-n5', 'authored', true),
  -- mae-ni
  ('sent-ex-maeni-1', 'lang-ja', '寝る前に本を読みます。', 'ねる まえ に ほん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-maeni-2', 'lang-ja', '食べる前に手を洗います。', 'たべる まえ に て お あらいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-maeni-3', 'lang-ja', '行く前に電話します。', 'いく まえ に でんわ します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-maeni-4', 'lang-ja', '出る前に窓を閉めます。', 'でる まえ に まど お しめます。', 'lvl-ja-n5', 'authored', true),
  -- ato-de
  ('sent-ex-atode-1', 'lang-ja', '食べた後で休みます。', 'たべた あと で やすみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-atode-2', 'lang-ja', '勉強した後で遊びます。', 'べんきょう した あと で あそびます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-atode-3', 'lang-ja', '帰った後でご飯を作ります。', 'かえった あと で ごはん お つくります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-atode-4', 'lang-ja', '見た後で話します。', 'みた あと で はなします。', 'lvl-ja-n5', 'authored', true),
  -- toki
  ('sent-ex-toki-1', 'lang-ja', '子供のとき、海で泳ぎました。', 'こども の とき、うみ で およぎました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-toki-2', 'lang-ja', '暑いとき、水を飲みます。', 'あつい とき、みず お のみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-toki-3', 'lang-ja', '忙しいとき、休みません。', 'いそがしい とき、やすみません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-toki-4', 'lang-ja', '日本へ行くとき、電車を使います。', 'にほん え いく とき、でんしゃ お つかいます。', 'lvl-ja-n5', 'authored', true),
  -- tara
  ('sent-ex-tara-1', 'lang-ja', '雨が降ったら、行きません。', 'あめ が ふったら、いきません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tara-2', 'lang-ja', '安かったら、買います。', 'やすかったら、かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tara-3', 'lang-ja', '忙しかったら、休みます。', 'いそがしかったら、やすみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tara-4', 'lang-ja', '日本へ行ったら、写真を撮ります。', 'にほん え いったら、しゃしん お とります。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-karamade-1', 'sent-ex-karamade-1', 'en', 'I walk from school to the sea.', 'authored'),
  ('st-ex-karamade-2', 'sent-ex-karamade-2', 'en', 'I study from morning until night.', 'authored'),
  ('st-ex-karamade-3', 'sent-ex-karamade-3', 'en', 'I work from Monday to Friday.', 'authored'),
  ('st-ex-karamade-4', 'sent-ex-karamade-4', 'en', 'I go from home to the office by train.', 'authored'),
  ('st-ex-yori-1', 'sent-ex-yori-1', 'en', 'I like meat more than fish.', 'authored'),
  ('st-ex-yori-2', 'sent-ex-yori-2', 'en', 'The train is faster than the car.', 'authored'),
  ('st-ex-yori-3', 'sent-ex-yori-3', 'en', 'I like the sea more than the mountains.', 'authored'),
  ('st-ex-yori-4', 'sent-ex-yori-4', 'en', 'Films are more interesting than books.', 'authored'),
  ('st-ex-masenka-1', 'sent-ex-masenka-1', 'en', 'Won''t you come along?', 'authored'),
  ('st-ex-masenka-2', 'sent-ex-masenka-2', 'en', 'Shall we watch a film?', 'authored'),
  ('st-ex-masenka-3', 'sent-ex-masenka-3', 'en', 'Would you like some tea?', 'authored'),
  ('st-ex-masenka-4', 'sent-ex-masenka-4', 'en', 'Shall we swim in the sea?', 'authored'),
  ('st-ex-naide-1', 'sent-ex-naide-1', 'en', 'Please don''t drink the water.', 'authored'),
  ('st-ex-naide-2', 'sent-ex-naide-2', 'en', 'Please don''t open the window.', 'authored'),
  ('st-ex-naide-3', 'sent-ex-naide-3', 'en', 'Please don''t take photos.', 'authored'),
  ('st-ex-naide-4', 'sent-ex-naide-4', 'en', 'Please don''t run.', 'authored'),
  ('st-ex-takoto-1', 'sent-ex-takoto-1', 'en', 'I have been to Japan.', 'authored'),
  ('st-ex-takoto-2', 'sent-ex-takoto-2', 'en', 'I have eaten fish.', 'authored'),
  ('st-ex-takoto-3', 'sent-ex-takoto-3', 'en', 'I have swum in the sea.', 'authored'),
  ('st-ex-takoto-4', 'sent-ex-takoto-4', 'en', 'I have listened to Japanese music.', 'authored'),
  ('st-ex-nagara-1', 'sent-ex-nagara-1', 'en', 'I study while listening to music.', 'authored'),
  ('st-ex-nagara-2', 'sent-ex-nagara-2', 'en', 'We talk while walking.', 'authored'),
  ('st-ex-nagara-3', 'sent-ex-nagara-3', 'en', 'I eat while watching television.', 'authored'),
  ('st-ex-nagara-4', 'sent-ex-nagara-4', 'en', 'I eat while listening to music.', 'authored'),
  ('st-ex-maeni-1', 'sent-ex-maeni-1', 'en', 'I read a book before I sleep.', 'authored'),
  ('st-ex-maeni-2', 'sent-ex-maeni-2', 'en', 'I wash my hands before eating.', 'authored'),
  ('st-ex-maeni-3', 'sent-ex-maeni-3', 'en', 'I phone before going.', 'authored'),
  ('st-ex-maeni-4', 'sent-ex-maeni-4', 'en', 'I close the window before going out.', 'authored'),
  ('st-ex-atode-1', 'sent-ex-atode-1', 'en', 'I rest after eating.', 'authored'),
  ('st-ex-atode-2', 'sent-ex-atode-2', 'en', 'I play after studying.', 'authored'),
  ('st-ex-atode-3', 'sent-ex-atode-3', 'en', 'I cook after coming home.', 'authored'),
  ('st-ex-atode-4', 'sent-ex-atode-4', 'en', 'We talk after watching.', 'authored'),
  ('st-ex-toki-1', 'sent-ex-toki-1', 'en', 'When I was a child, I swam in the sea.', 'authored'),
  ('st-ex-toki-2', 'sent-ex-toki-2', 'en', 'When it is hot, I drink water.', 'authored'),
  ('st-ex-toki-3', 'sent-ex-toki-3', 'en', 'When I am busy, I do not rest.', 'authored'),
  ('st-ex-toki-4', 'sent-ex-toki-4', 'en', 'When I go to Japan, I use the train.', 'authored'),
  ('st-ex-tara-1', 'sent-ex-tara-1', 'en', 'If it rains, I won''t go.', 'authored'),
  ('st-ex-tara-2', 'sent-ex-tara-2', 'en', 'If it''s cheap, I''ll buy it.', 'authored'),
  ('st-ex-tara-3', 'sent-ex-tara-3', 'en', 'If I''m busy, I''ll take a break.', 'authored'),
  ('st-ex-tara-4', 'sent-ex-tara-4', 'en', 'If I go to Japan, I''ll take photos.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('kara-made', 'sent-ex-karamade-1', 0),
  ('kara-made', 'sent-ex-karamade-2', 1),
  ('kara-made', 'sent-ex-karamade-3', 2),
  ('kara-made', 'sent-ex-karamade-4', 3),
  ('yori', 'sent-ex-yori-1', 0),
  ('yori', 'sent-ex-yori-2', 1),
  ('yori', 'sent-ex-yori-3', 2),
  ('yori', 'sent-ex-yori-4', 3),
  ('masen-ka', 'sent-ex-masenka-1', 0),
  ('masen-ka', 'sent-ex-masenka-2', 1),
  ('masen-ka', 'sent-ex-masenka-3', 2),
  ('masen-ka', 'sent-ex-masenka-4', 3),
  ('naide-kudasai', 'sent-ex-naide-1', 0),
  ('naide-kudasai', 'sent-ex-naide-2', 1),
  ('naide-kudasai', 'sent-ex-naide-3', 2),
  ('naide-kudasai', 'sent-ex-naide-4', 3),
  ('ta-koto-ga-aru', 'sent-ex-takoto-1', 0),
  ('ta-koto-ga-aru', 'sent-ex-takoto-2', 1),
  ('ta-koto-ga-aru', 'sent-ex-takoto-3', 2),
  ('ta-koto-ga-aru', 'sent-ex-takoto-4', 3),
  ('nagara', 'sent-ex-nagara-1', 0),
  ('nagara', 'sent-ex-nagara-2', 1),
  ('nagara', 'sent-ex-nagara-3', 2),
  ('nagara', 'sent-ex-nagara-4', 3),
  ('mae-ni', 'sent-ex-maeni-1', 0),
  ('mae-ni', 'sent-ex-maeni-2', 1),
  ('mae-ni', 'sent-ex-maeni-3', 2),
  ('mae-ni', 'sent-ex-maeni-4', 3),
  ('ato-de', 'sent-ex-atode-1', 0),
  ('ato-de', 'sent-ex-atode-2', 1),
  ('ato-de', 'sent-ex-atode-3', 2),
  ('ato-de', 'sent-ex-atode-4', 3),
  ('toki', 'sent-ex-toki-1', 0),
  ('toki', 'sent-ex-toki-2', 1),
  ('toki', 'sent-ex-toki-3', 2),
  ('toki', 'sent-ex-toki-4', 3),
  ('tara', 'sent-ex-tara-1', 0),
  ('tara', 'sent-ex-tara-2', 1),
  ('tara', 'sent-ex-tara-3', 2),
  ('tara', 'sent-ex-tara-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds, so this is how they get there; the quiz derivation
-- cuts its chips from these rows and not from the sentence text.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-karamade-1', 'sent-ex-karamade-2', 'sent-ex-karamade-3', 'sent-ex-karamade-4', 'sent-ex-yori-1', 'sent-ex-yori-2', 'sent-ex-yori-3', 'sent-ex-yori-4', 'sent-ex-masenka-1', 'sent-ex-masenka-2', 'sent-ex-masenka-3', 'sent-ex-masenka-4', 'sent-ex-naide-1', 'sent-ex-naide-2', 'sent-ex-naide-3', 'sent-ex-naide-4', 'sent-ex-takoto-1', 'sent-ex-takoto-2', 'sent-ex-takoto-3', 'sent-ex-takoto-4', 'sent-ex-nagara-1', 'sent-ex-nagara-2', 'sent-ex-nagara-3', 'sent-ex-nagara-4', 'sent-ex-maeni-1', 'sent-ex-maeni-2', 'sent-ex-maeni-3', 'sent-ex-maeni-4', 'sent-ex-atode-1', 'sent-ex-atode-2', 'sent-ex-atode-3', 'sent-ex-atode-4', 'sent-ex-toki-1', 'sent-ex-toki-2', 'sent-ex-toki-3', 'sent-ex-toki-4', 'sent-ex-tara-1', 'sent-ex-tara-2', 'sent-ex-tara-3', 'sent-ex-tara-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-karamade-1', 0, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-1', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-1', 2, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-1', 3, 'ま', NULL, NULL, 5, 6, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-1', 4, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-1', 5, '歩きます', 'あるきます', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"歩","r":"ある"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-1', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-2', 0, '朝', 'あさ', (select id from words where primary_form = '朝' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-2', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-2', 2, '夜', 'よる', (select id from words where primary_form = '夜' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"夜","r":"よる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-2', 3, 'ま', NULL, NULL, 4, 5, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-2', 4, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-2', 5, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-2', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-3', 0, '月曜日', 'げつようび', (select id from words where primary_form = '月曜日' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"月曜日","r":"げつようび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-3', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-3', 2, '金曜日', 'きんようび', (select id from words where primary_form = '金曜日' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"金曜日","r":"きんようび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-3', 3, 'ま', NULL, NULL, 8, 9, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-3', 4, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-3', 5, '働きます', 'はたらきます', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-3', 6, '。', NULL, NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 0, '家', 'け', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"家","r":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 1, 'から', NULL, (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 2, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 3, 'ま', NULL, NULL, 5, 6, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 4, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 5, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 6, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 7, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karamade-4', 8, '。', NULL, NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 1, 'より', NULL, (select id from words where primary_form = 'より' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"より"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 2, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 3, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 4, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 5, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 6, 'す', NULL, NULL, 8, 9, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-1', 7, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 0, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 1, 'より', NULL, (select id from words where primary_form = 'より' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"より"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 2, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 3, 'が', NULL, NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 4, '速い', 'はやい', (select id from words where primary_form = '早い' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"速","r":"はや"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 5, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 6, 'す', NULL, NULL, 9, 10, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-2', 7, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 0, '山', 'やま', (select id from words where primary_form = '山' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 1, 'より', NULL, (select id from words where primary_form = 'より' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"より"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 2, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 3, 'が', NULL, NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 4, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 5, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 6, 'す', NULL, NULL, 8, 9, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-3', 7, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 1, 'より', NULL, (select id from words where primary_form = 'より' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"より"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 2, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 3, 'が', NULL, NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 4, '面白い', 'おもしろい', (select id from words where primary_form = '面白い' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 5, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 6, 'す', NULL, NULL, 10, 11, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yori-4', 7, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-1', 0, '一緒', 'いっしょ', (select id from words where primary_form = '一緒' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一緒","r":"いっしょ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-1', 1, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-1', 2, '行きません', 'いきません', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"行","r":"い"},{"t":"きません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-1', 3, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-1', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-2', 0, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-2', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-2', 2, '見ません', 'みません', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"見","r":"み"},{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-2', 3, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-2', 4, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-3', 0, 'お茶', 'おちゃ', (select id from words where primary_form = 'お茶' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"茶","r":"ちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-3', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-3', 2, '飲みません', 'のみません', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"飲","r":"の"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-3', 3, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-3', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-4', 0, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-4', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-4', 2, '泳ぎません', 'およぎません', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"泳","r":"およ"},{"t":"ぎません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-4', 3, 'か', NULL, (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masenka-4', 4, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-1', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-1', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-1', 2, '飲まない', 'のまない', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"飲","r":"の"},{"t":"まない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-1', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-1', 4, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-1', 5, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-2', 0, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-2', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-2', 2, '開けない', 'あけない', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"開","r":"あ"},{"t":"けない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-2', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-2', 4, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-2', 5, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-3', 0, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-3', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-3', 2, '撮らない', 'とらない', (select id from words where primary_form = '撮る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"撮","r":"と"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-3', 3, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-3', 4, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-3', 5, '。', NULL, NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-4', 0, '走らない', 'はしらない', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"走","r":"はし"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-4', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-4', 2, 'ください', NULL, (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naide-4', 3, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-1', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-1', 1, 'へ', 'え', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-1', 2, '行った', 'いった', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"行","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-1', 3, 'こと', NULL, (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-1', 4, 'が', NULL, NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-1', 5, 'あります', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-1', 6, '。', NULL, NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-2', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-2', 1, 'を', 'お', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-2', 2, '食べた', 'たべた', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"食","r":"た"},{"t":"べた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-2', 3, 'こと', NULL, (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-2', 4, 'が', NULL, NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-2', 5, 'あります', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-2', 6, '。', NULL, NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-3', 0, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-3', 1, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-3', 2, '泳いだ', 'およいだ', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"泳","r":"およ"},{"t":"いだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-3', 3, 'こと', NULL, (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-3', 4, 'が', NULL, NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-3', 5, 'あります', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-3', 6, '。', NULL, NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 1, 'の', NULL, NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 2, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 3, 'を', 'お', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 4, '聞いた', 'きいた', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"聞","r":"き"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 5, 'こと', NULL, (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 6, 'が', NULL, NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 7, 'あります', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-takoto-4', 8, '。', NULL, NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-1', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-1', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-1', 2, '聞きながら', 'ききながら', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"聞","r":"き"},{"t":"きながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-1', 3, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 8, 13, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-1', 4, '。', NULL, NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-2', 0, '歩きながら', 'あるきながら', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"歩","r":"ある"},{"t":"きながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-2', 1, '話します', 'はなします', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"話","r":"はな"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-2', 2, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-3', 0, 'テレビ', NULL, (select id from words where primary_form = 'テレビ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"テレビ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-3', 1, 'を', 'お', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-3', 2, '見ながら', 'みながら', (select id from words where primary_form = '見なす' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"見","r":"み"},{"t":"ながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-3', 3, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-3', 4, '。', NULL, NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-4', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-4', 1, 'を', 'お', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-4', 2, '聞きながらご', 'ききながらご', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"聞","r":"き"},{"t":"きながらご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-4', 3, '飯', 'めし', (select id from words where primary_form = '飯' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"飯","r":"めし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-4', 4, 'を', 'お', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-4', 5, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagara-4', 6, '。', NULL, NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-1', 0, '寝る', 'ねる', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"寝","r":"ね"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-1', 1, '前', 'ぜん', (select id from words where primary_form = '前' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"前","r":"ぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-1', 2, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-1', 3, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-1', 4, 'を', 'お', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-1', 5, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-1', 6, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-2', 0, '食べる', 'たべる', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"食","r":"た"},{"t":"べる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-2', 1, '前', 'ぜん', (select id from words where primary_form = '前' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"前","r":"ぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-2', 2, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-2', 3, '手', 'て', (select id from words where primary_form = '手' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"手","r":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-2', 4, 'を', 'お', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-2', 5, '洗います', 'あらいます', (select id from words where primary_form = '洗う' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"洗","r":"あら"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-2', 6, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-3', 0, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-3', 1, '前', 'ぜん', (select id from words where primary_form = '前' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"前","r":"ぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-3', 2, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-3', 3, '電話します', 'でんわします', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"電話","r":"でんわ"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-3', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-4', 0, '出る', 'でる', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"出","r":"で"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-4', 1, '前', 'ぜん', (select id from words where primary_form = '前' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"前","r":"ぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-4', 2, 'に', NULL, (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-4', 3, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-4', 4, 'を', 'お', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-4', 5, '閉めます', 'しめます', (select id from words where primary_form = '閉める' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"閉","r":"し"},{"t":"めます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeni-4', 6, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-1', 0, '食べた', 'たべた', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"食","r":"た"},{"t":"べた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-1', 1, '後', 'あと', (select id from words where primary_form = '後' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"後","r":"あと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-1', 2, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-1', 3, '休みます', 'やすみます', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-1', 4, '。', NULL, NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-2', 0, '勉強した', 'べんきょうした', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"勉強","r":"べんきょう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-2', 1, '後', 'あと', (select id from words where primary_form = '後' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"後","r":"あと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-2', 2, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-2', 3, '遊びます', 'あそびます', (select id from words where primary_form = '遊ぶ' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"遊","r":"あそ"},{"t":"びます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-2', 4, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-3', 0, '帰った', 'かえった', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"帰","r":"かえ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-3', 1, '後', 'あと', (select id from words where primary_form = '後' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"後","r":"あと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-3', 2, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-3', 3, 'ご飯', 'ごはん', (select id from words where primary_form = 'ご飯' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-3', 4, 'を', 'お', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-3', 5, '作ります', 'つくります', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"作","r":"つく"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-3', 6, '。', NULL, NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-4', 0, '見た', 'みた', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"見","r":"み"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-4', 1, '後', 'あと', (select id from words where primary_form = '後' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"後","r":"あと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-4', 2, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-4', 3, '話します', 'はなします', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"話","r":"はな"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-atode-4', 4, '。', NULL, NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 1, 'の', NULL, NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 2, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 3, 'き', NULL, NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 4, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 5, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 6, 'で', NULL, (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 7, '泳ぎました', 'およぎました', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 8, 13, '[{"t":"泳","r":"およ"},{"t":"ぎました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-1', 8, '。', NULL, NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 0, '暑い', 'あつい', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"暑","r":"あつ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 1, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 2, 'き', NULL, NULL, 3, 4, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 3, '、', NULL, NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 4, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 5, 'を', 'お', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 6, '飲みます', 'のみます', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-2', 7, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-3', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-3', 1, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-3', 2, 'き', NULL, NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-3', 3, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-3', 4, '休みません', 'やすみません', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"休","r":"やす"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-3', 5, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 1, 'へ', 'え', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 2, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 3, 'と', NULL, (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 4, 'き', NULL, NULL, 6, 7, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 5, '、', NULL, NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 6, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 7, 'を', 'お', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 8, '使います', 'つかいます', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"使","r":"つか"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toki-4', 9, '。', NULL, NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-1', 1, 'が', NULL, NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-1', 2, '降ったら', 'ふったら', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"降","r":"ふ"},{"t":"ったら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-1', 3, '、', NULL, NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-1', 4, '行きません', 'いきません', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"行","r":"い"},{"t":"きません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-1', 5, '。', NULL, NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-2', 0, '安かったら', 'やすかったら', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"安","r":"やす"},{"t":"かったら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-2', 1, '、', NULL, NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-2', 2, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-2', 3, '。', NULL, NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-3', 0, '忙しかったら', 'いそがしかったら', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"忙","r":"いそが"},{"t":"しかったら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-3', 1, '、', NULL, NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-3', 2, '休みます', 'やすみます', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-3', 3, '。', NULL, NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 1, 'へ', 'え', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 2, '行ったら', 'いったら', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"行","r":"い"},{"t":"ったら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 3, '、', NULL, NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 4, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 5, 'を', 'お', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 6, '撮ります', 'とります', (select id from words where primary_form = '撮る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"撮","r":"と"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tara-4', 7, '。', NULL, NULL, 15, 16, '[{"t":"。"}]'::jsonb);
