-- N5 example sentences, batch 4: 〜方が, 〜になる, 〜すぎる, 〜が好き, 〜てから,
-- 〜ので, だけ, 〜ません, 〜ました and iAdj〜くない.
--
-- Three more topics join the blocked list, all for the same reason as もいい and
-- なければ — the pattern is not a word the dictionary holds, so it shreds into
-- the kana it is spelled with:
--
--   つもり     つ | も | り
--   でしょう   で | し | ょ | う   (です, again)
--   これ/それ  こ | れ  and  そ | れ   — the こそあど topic
--
-- 〜方が is written with the kanji 方 rather than ほう, which is both normal
-- Japanese and the only spelling the tokeniser can read: ほう alone shreds.
--
-- One tokeniser change came out of this batch and is in the same commit: なる
-- now conjugates from its kana spelling, as ある and いる already did. 先生に
-- なります was coming apart as な|り|ま|す, which makes the topic unwritable —
-- 成る is tagged rK, so the row is dropped before it can conjugate. It is named
-- individually, so 鳴る "to sound" and 生る "to bear fruit" cannot take なります
-- from it.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- hou-ga
  ('sent-ex-houga-1', 'lang-ja', '電車の方が速いです。', 'でんしゃ の ほう が はやい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-houga-2', 'lang-ja', '魚の方が好きです。', 'さかな の ほう が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-houga-3', 'lang-ja', '海の方が楽しいです。', 'うみ の ほう が たのしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-houga-4', 'lang-ja', '本の方が面白いです。', 'ほん の ほう が おもしろい です。', 'lvl-ja-n5', 'authored', true),
  -- naru
  ('sent-ex-naru-1', 'lang-ja', '先生になります。', 'せんせい に なります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naru-2', 'lang-ja', '寒くなります。', 'さむく なります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naru-3', 'lang-ja', '元気になりました。', 'げんき に なりました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naru-4', 'lang-ja', '高くなりました。', 'たかく なりました。', 'lvl-ja-n5', 'authored', true),
  -- sugiru
  ('sent-ex-sugiru-1', 'lang-ja', '食べすぎました。', 'たべすぎました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-sugiru-2', 'lang-ja', '高すぎます。', 'たかすぎます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-sugiru-3', 'lang-ja', '飲みすぎました。', 'のみすぎました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-sugiru-4', 'lang-ja', '暑すぎます。', 'あつすぎます。', 'lvl-ja-n5', 'authored', true),
  -- suki
  ('sent-ex-suki-1', 'lang-ja', '音楽が好きです。', 'おんがく が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-suki-2', 'lang-ja', '花が好きです。', 'はな が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-suki-3', 'lang-ja', '映画が好きです。', 'えいが が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-suki-4', 'lang-ja', '日本の料理が好きです。', 'にほん の りょうり が すき です。', 'lvl-ja-n5', 'authored', true),
  -- te-kara
  ('sent-ex-tekara-1', 'lang-ja', '食べてから出ます。', 'たべて から でます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tekara-2', 'lang-ja', '手を洗ってから食べます。', 'て お あらって から たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tekara-3', 'lang-ja', '勉強してから寝ます。', 'べんきょう して から ねます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tekara-4', 'lang-ja', '帰ってから休みます。', 'かえって から やすみます。', 'lvl-ja-n5', 'authored', true),
  -- node
  ('sent-ex-node-1', 'lang-ja', '雨が降るので、行きません。', 'あめ が ふる ので、いきません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-node-2', 'lang-ja', '寒いので、家にいます。', 'さむい ので、いえ に います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-node-3', 'lang-ja', '忙しいので、電話しません。', 'いそがしい ので、でんわ しません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-node-4', 'lang-ja', '音楽が好きなので、毎日聞きます。', 'おんがく が すき な ので、まいにち ききます。', 'lvl-ja-n5', 'authored', true),
  -- dake
  ('sent-ex-dake-1', 'lang-ja', '水だけ飲みます。', 'みず だけ のみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dake-2', 'lang-ja', '少しだけ食べます。', 'すこし だけ たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dake-3', 'lang-ja', '本だけ買います。', 'ほん だけ かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dake-4', 'lang-ja', '魚だけ食べます。', 'さかな だけ たべます。', 'lvl-ja-n5', 'authored', true),
  -- masen
  ('sent-ex-masen-1', 'lang-ja', '肉を食べません。', 'にく お たべません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masen-2', 'lang-ja', 'お酒を飲みません。', 'おさけ お のみません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masen-3', 'lang-ja', '朝は勉強しません。', 'あさ わ べんきょう しません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masen-4', 'lang-ja', '海へ行きません。', 'うみ え いきません。', 'lvl-ja-n5', 'authored', true),
  -- mashita
  ('sent-ex-mashita-1', 'lang-ja', '新聞を読みました。', 'しんぶん お よみました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashita-2', 'lang-ja', '海で泳ぎました。', 'うみ で およぎました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashita-3', 'lang-ja', '友達に会いました。', 'ともだち に あいました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mashita-4', 'lang-ja', '手紙を書きました。', 'てがみ お かきました。', 'lvl-ja-n5', 'authored', true),
  -- i-adj-negative
  ('sent-ex-iadjneg-1', 'lang-ja', '寒くないです。', 'さむく ない です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjneg-2', 'lang-ja', '高くないです。', 'たかく ない です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjneg-3', 'lang-ja', '安くないです。', 'やすく ない です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjneg-4', 'lang-ja', '忙しくないです。', 'いそがしく ない です。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-houga-1', 'sent-ex-houga-1', 'en', 'The train is faster.', 'authored'),
  ('st-ex-houga-2', 'sent-ex-houga-2', 'en', 'I prefer fish.', 'authored'),
  ('st-ex-houga-3', 'sent-ex-houga-3', 'en', 'The sea is more fun.', 'authored'),
  ('st-ex-houga-4', 'sent-ex-houga-4', 'en', 'Books are more interesting.', 'authored'),
  ('st-ex-naru-1', 'sent-ex-naru-1', 'en', 'I am going to be a teacher.', 'authored'),
  ('st-ex-naru-2', 'sent-ex-naru-2', 'en', 'It is getting cold.', 'authored'),
  ('st-ex-naru-3', 'sent-ex-naru-3', 'en', 'I got better.', 'authored'),
  ('st-ex-naru-4', 'sent-ex-naru-4', 'en', 'It has got expensive.', 'authored'),
  ('st-ex-sugiru-1', 'sent-ex-sugiru-1', 'en', 'I ate too much.', 'authored'),
  ('st-ex-sugiru-2', 'sent-ex-sugiru-2', 'en', 'It is too expensive.', 'authored'),
  ('st-ex-sugiru-3', 'sent-ex-sugiru-3', 'en', 'I drank too much.', 'authored'),
  ('st-ex-sugiru-4', 'sent-ex-sugiru-4', 'en', 'It is too hot.', 'authored'),
  ('st-ex-suki-1', 'sent-ex-suki-1', 'en', 'I like music.', 'authored'),
  ('st-ex-suki-2', 'sent-ex-suki-2', 'en', 'I like flowers.', 'authored'),
  ('st-ex-suki-3', 'sent-ex-suki-3', 'en', 'I like films.', 'authored'),
  ('st-ex-suki-4', 'sent-ex-suki-4', 'en', 'I like Japanese food.', 'authored'),
  ('st-ex-tekara-1', 'sent-ex-tekara-1', 'en', 'I go out after eating.', 'authored'),
  ('st-ex-tekara-2', 'sent-ex-tekara-2', 'en', 'I eat after washing my hands.', 'authored'),
  ('st-ex-tekara-3', 'sent-ex-tekara-3', 'en', 'I sleep after studying.', 'authored'),
  ('st-ex-tekara-4', 'sent-ex-tekara-4', 'en', 'I rest after getting home.', 'authored'),
  ('st-ex-node-1', 'sent-ex-node-1', 'en', 'It is going to rain, so I am not going.', 'authored'),
  ('st-ex-node-2', 'sent-ex-node-2', 'en', 'It is cold, so I am staying home.', 'authored'),
  ('st-ex-node-3', 'sent-ex-node-3', 'en', 'I am busy, so I will not call.', 'authored'),
  ('st-ex-node-4', 'sent-ex-node-4', 'en', 'I like music, so I listen every day.', 'authored'),
  ('st-ex-dake-1', 'sent-ex-dake-1', 'en', 'I only drink water.', 'authored'),
  ('st-ex-dake-2', 'sent-ex-dake-2', 'en', 'I only eat a little.', 'authored'),
  ('st-ex-dake-3', 'sent-ex-dake-3', 'en', 'I only buy books.', 'authored'),
  ('st-ex-dake-4', 'sent-ex-dake-4', 'en', 'I only eat fish.', 'authored'),
  ('st-ex-masen-1', 'sent-ex-masen-1', 'en', 'I do not eat meat.', 'authored'),
  ('st-ex-masen-2', 'sent-ex-masen-2', 'en', 'I do not drink alcohol.', 'authored'),
  ('st-ex-masen-3', 'sent-ex-masen-3', 'en', 'I do not study in the morning.', 'authored'),
  ('st-ex-masen-4', 'sent-ex-masen-4', 'en', 'I am not going to the sea.', 'authored'),
  ('st-ex-mashita-1', 'sent-ex-mashita-1', 'en', 'I read the newspaper.', 'authored'),
  ('st-ex-mashita-2', 'sent-ex-mashita-2', 'en', 'I swam in the sea.', 'authored'),
  ('st-ex-mashita-3', 'sent-ex-mashita-3', 'en', 'I met a friend.', 'authored'),
  ('st-ex-mashita-4', 'sent-ex-mashita-4', 'en', 'I wrote a letter.', 'authored'),
  ('st-ex-iadjneg-1', 'sent-ex-iadjneg-1', 'en', 'It is not cold.', 'authored'),
  ('st-ex-iadjneg-2', 'sent-ex-iadjneg-2', 'en', 'It is not expensive.', 'authored'),
  ('st-ex-iadjneg-3', 'sent-ex-iadjneg-3', 'en', 'It is not cheap.', 'authored'),
  ('st-ex-iadjneg-4', 'sent-ex-iadjneg-4', 'en', 'I am not busy.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('hou-ga', 'sent-ex-houga-1', 0),
  ('hou-ga', 'sent-ex-houga-2', 1),
  ('hou-ga', 'sent-ex-houga-3', 2),
  ('hou-ga', 'sent-ex-houga-4', 3),
  ('naru', 'sent-ex-naru-1', 0),
  ('naru', 'sent-ex-naru-2', 1),
  ('naru', 'sent-ex-naru-3', 2),
  ('naru', 'sent-ex-naru-4', 3),
  ('sugiru', 'sent-ex-sugiru-1', 0),
  ('sugiru', 'sent-ex-sugiru-2', 1),
  ('sugiru', 'sent-ex-sugiru-3', 2),
  ('sugiru', 'sent-ex-sugiru-4', 3),
  ('suki', 'sent-ex-suki-1', 0),
  ('suki', 'sent-ex-suki-2', 1),
  ('suki', 'sent-ex-suki-3', 2),
  ('suki', 'sent-ex-suki-4', 3),
  ('te-kara', 'sent-ex-tekara-1', 0),
  ('te-kara', 'sent-ex-tekara-2', 1),
  ('te-kara', 'sent-ex-tekara-3', 2),
  ('te-kara', 'sent-ex-tekara-4', 3),
  ('node', 'sent-ex-node-1', 0),
  ('node', 'sent-ex-node-2', 1),
  ('node', 'sent-ex-node-3', 2),
  ('node', 'sent-ex-node-4', 3),
  ('dake', 'sent-ex-dake-1', 0),
  ('dake', 'sent-ex-dake-2', 1),
  ('dake', 'sent-ex-dake-3', 2),
  ('dake', 'sent-ex-dake-4', 3),
  ('masen', 'sent-ex-masen-1', 0),
  ('masen', 'sent-ex-masen-2', 1),
  ('masen', 'sent-ex-masen-3', 2),
  ('masen', 'sent-ex-masen-4', 3),
  ('mashita', 'sent-ex-mashita-1', 0),
  ('mashita', 'sent-ex-mashita-2', 1),
  ('mashita', 'sent-ex-mashita-3', 2),
  ('mashita', 'sent-ex-mashita-4', 3),
  ('i-adj-negative', 'sent-ex-iadjneg-1', 0),
  ('i-adj-negative', 'sent-ex-iadjneg-2', 1),
  ('i-adj-negative', 'sent-ex-iadjneg-3', 2),
  ('i-adj-negative', 'sent-ex-iadjneg-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-houga-1', 'sent-ex-houga-2', 'sent-ex-houga-3', 'sent-ex-houga-4', 'sent-ex-naru-1', 'sent-ex-naru-2', 'sent-ex-naru-3', 'sent-ex-naru-4', 'sent-ex-sugiru-1', 'sent-ex-sugiru-2', 'sent-ex-sugiru-3', 'sent-ex-sugiru-4', 'sent-ex-suki-1', 'sent-ex-suki-2', 'sent-ex-suki-3', 'sent-ex-suki-4', 'sent-ex-tekara-1', 'sent-ex-tekara-2', 'sent-ex-tekara-3', 'sent-ex-tekara-4', 'sent-ex-node-1', 'sent-ex-node-2', 'sent-ex-node-3', 'sent-ex-node-4', 'sent-ex-dake-1', 'sent-ex-dake-2', 'sent-ex-dake-3', 'sent-ex-dake-4', 'sent-ex-masen-1', 'sent-ex-masen-2', 'sent-ex-masen-3', 'sent-ex-masen-4', 'sent-ex-mashita-1', 'sent-ex-mashita-2', 'sent-ex-mashita-3', 'sent-ex-mashita-4', 'sent-ex-iadjneg-1', 'sent-ex-iadjneg-2', 'sent-ex-iadjneg-3', 'sent-ex-iadjneg-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-houga-1', 0, '電車', 'でんしゃ', '36d08b54-317b-4525-9c99-cf5cae0c7ae2', 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-1', 2, '方', 'ほう', '1fc859f0-ed39-463c-95ca-71fc00ea6e39', 3, 4, '[{"t":"方","r":"ほう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-1', 4, '速い', 'はやい', 'd5ccebef-e5f2-45b0-882b-c020fefd992b', 5, 7, '[{"t":"速","r":"はや"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-1', 5, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-1', 6, 'す', 'す', NULL, 8, 9, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-1', 7, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 0, '魚', 'さかな', 'e1e048a7-24b7-4875-8727-b61a2e2c4857', 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 2, '方', 'ほう', '1fc859f0-ed39-463c-95ca-71fc00ea6e39', 2, 3, '[{"t":"方","r":"ほう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 3, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 4, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 4, 6, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 5, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 6, 'す', 'す', NULL, 7, 8, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-2', 7, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 0, '海', 'うみ', 'e3cb86b5-f5fc-4cf7-81de-c038f64be645', 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 2, '方', 'ほう', '1fc859f0-ed39-463c-95ca-71fc00ea6e39', 2, 3, '[{"t":"方","r":"ほう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 3, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 4, '楽しい', 'たのしい', '4453c4b8-6a8c-4627-b784-b8bb237090b0', 4, 7, '[{"t":"楽","r":"たの"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 5, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 6, 'す', 'す', NULL, 8, 9, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-3', 7, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 2, '方', 'ほう', '1fc859f0-ed39-463c-95ca-71fc00ea6e39', 2, 3, '[{"t":"方","r":"ほう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 3, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 4, '面白い', 'おもしろい', 'f5d6fc6a-618d-4fbd-8782-19bd4443c7da', 4, 7, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 5, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 6, 'す', 'す', NULL, 8, 9, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-houga-4', 7, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-1', 0, '先生', 'せんせい', 'f2bd1cf4-e22c-48f8-a563-771e2f0599a9', 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-1', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-1', 2, 'なります', 'なります', '3116c98a-69c8-4c74-8674-e4e38ef4d1b5', 3, 7, '[{"t":"なります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-2', 0, '寒くなります', 'さむくなります', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 6, '[{"t":"寒","r":"さむ"},{"t":"くなります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-2', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-3', 0, '元気', 'げんき', '9c71f674-2595-41b1-abe5-1d9092a705e8', 0, 2, '[{"t":"元気","r":"げんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-3', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-3', 2, 'なりました', 'なりました', '3116c98a-69c8-4c74-8674-e4e38ef4d1b5', 3, 8, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-4', 0, '高くなりました', 'たかくなりました', 'ddc1e88a-997a-4781-8bc9-d3a184a07301', 0, 7, '[{"t":"高","r":"たか"},{"t":"くなりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naru-4', 1, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-1', 0, '食べすぎました', 'たべすぎました', '788557df-2bac-4ae7-a157-8a81fbe1da16', 0, 7, '[{"t":"食","r":"た"},{"t":"べすぎました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-1', 1, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-2', 0, '高すぎます', 'たかすぎます', 'ddc1e88a-997a-4781-8bc9-d3a184a07301', 0, 5, '[{"t":"高","r":"たか"},{"t":"すぎます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-2', 1, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-3', 0, '飲みすぎました', 'のみすぎました', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 0, 7, '[{"t":"飲","r":"の"},{"t":"みすぎました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-3', 1, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-4', 0, '暑すぎます', 'あつすぎます', '24ba41c3-4af8-45a2-9f3a-318c80560e5b', 0, 5, '[{"t":"暑","r":"あつ"},{"t":"すぎます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sugiru-4', 1, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-1', 0, '音楽', 'おんがく', '9996af4b-f2a7-435d-b6e6-c3b784bf93dc', 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-1', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 3, 5, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-1', 3, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-1', 4, 'す', 'す', NULL, 6, 7, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-1', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-2', 0, '花', 'はな', '3fd50ae6-11ab-45cc-aa4d-734bc685823d', 0, 1, '[{"t":"花","r":"はな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-2', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 2, 4, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-2', 3, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-2', 4, 'す', 'す', NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-2', 5, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-3', 0, '映画', 'えいが', '94093c2a-fa1e-4b90-9f87-b13ba46cd7fb', 0, 2, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-3', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 3, 5, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-3', 3, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-3', 4, 'す', 'す', NULL, 6, 7, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-3', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 0, '日本', 'にほん', '9de924d0-d7d7-4284-bbae-c05ecbef3e5e', 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 2, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 3, 5, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 3, 'が', 'が', NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 4, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 6, 8, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 5, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 6, 'す', 'す', NULL, 9, 10, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-suki-4', 7, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-1', 0, '食べて', 'たべて', '788557df-2bac-4ae7-a157-8a81fbe1da16', 0, 3, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-1', 1, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 3, 5, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-1', 2, '出ます', 'でます', '8fa15a12-763b-4db6-88b3-3895d0eca3c0', 5, 8, '[{"t":"出","r":"で"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-2', 0, '手', 'て', '0efec346-391e-41b1-af6c-f48b68b9eec1', 0, 1, '[{"t":"手","r":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-2', 2, '洗って', 'あらって', '2bbb8c32-86e8-4c45-a12b-1174a8f4d189', 2, 5, '[{"t":"洗","r":"あら"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-2', 3, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 5, 7, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-2', 4, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 7, 11, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-3', 0, '勉強して', 'べんきょうして', 'b5a69b9b-5017-4a76-b301-dbd5c9f5ba2a', 0, 4, '[{"t":"勉強","r":"べんきょう"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-3', 1, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 4, 6, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-3', 2, '寝ます', 'ねます', '056f037c-201a-4cd0-85be-f063237124fd', 6, 9, '[{"t":"寝","r":"ね"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-3', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-4', 0, '帰って', 'かえって', '0e66e781-bb50-49e8-a7da-ea0a8bb6cbe0', 0, 3, '[{"t":"帰","r":"かえ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-4', 1, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 3, 5, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-4', 2, '休みます', 'やすみます', '52fd60de-a97d-47be-9b31-894be752027a', 5, 9, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekara-4', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 0, '雨', 'あめ', '754619f1-15a8-48dc-a8c0-81c74ea9a69a', 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 2, '降る', 'ふる', '5ace5ec6-4992-4ab8-abbb-6ee6dd197435', 2, 4, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 4, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 5, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 6, '行きません', 'いきません', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 7, 12, '[{"t":"行","r":"い"},{"t":"きません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-1', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 0, '寒い', 'さむい', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 2, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 2, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 3, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 4, '家', 'いえ', '23cdeb40-9591-49ca-b837-a591ceb929d5', 5, 6, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 5, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 6, 'います', 'います', '2e8dd83a-7a6a-43db-853d-072f7519c172', 7, 10, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-2', 7, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-3', 0, '忙しい', 'いそがしい', '65ae7422-9448-4faa-b28d-f80a027123bf', 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-3', 1, 'の', 'の', NULL, 3, 4, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-3', 2, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-3', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-3', 4, '電話しません', 'でんわしません', 'd39abe7d-c638-4789-b2c7-368c66d1feec', 6, 12, '[{"t":"電話","r":"でんわ"},{"t":"しません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-3', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 0, '音楽', 'おんがく', '9996af4b-f2a7-435d-b6e6-c3b784bf93dc', 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 3, 5, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 3, 'な', 'な', '6ac13c77-d34b-48a1-88aa-a6f30ec5c45e', 5, 6, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 4, 'の', 'の', NULL, 6, 7, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 5, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 6, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 7, '毎日', 'まいにち', '7475b67c-3081-49d9-81ce-4065be5e79f2', 9, 11, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 8, '聞きます', 'ききます', 'c1cb817b-80ef-4ac2-8fd6-995a7ea99784', 11, 15, '[{"t":"聞","r":"き"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-node-4', 9, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-1', 0, '水', 'みず', '02cd9dd6-94a1-43e7-9e49-2dfff6e0edf2', 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-1', 1, 'だけ', 'だけ', '4baefbb0-a9e6-4acb-93cd-5349696bb0eb', 1, 3, '[{"t":"だけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-1', 2, '飲みます', 'のみます', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 3, 7, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-2', 0, '少し', 'すこし', 'c3fea249-9141-44a5-a822-a2bbe599d73d', 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-2', 1, 'だけ', 'だけ', '4baefbb0-a9e6-4acb-93cd-5349696bb0eb', 2, 4, '[{"t":"だけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-2', 2, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 4, 8, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-3', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-3', 1, 'だけ', 'だけ', '4baefbb0-a9e6-4acb-93cd-5349696bb0eb', 1, 3, '[{"t":"だけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-3', 2, '買います', 'かいます', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 3, 7, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-3', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-4', 0, '魚', 'さかな', 'e1e048a7-24b7-4875-8727-b61a2e2c4857', 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-4', 1, 'だけ', 'だけ', '4baefbb0-a9e6-4acb-93cd-5349696bb0eb', 1, 3, '[{"t":"だけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-4', 2, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 3, 7, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dake-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-1', 0, '肉', 'にく', '5df9f1a7-e606-44b7-b5a7-484d84d86549', 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-1', 2, '食べません', 'たべません', '788557df-2bac-4ae7-a157-8a81fbe1da16', 2, 7, '[{"t":"食","r":"た"},{"t":"べません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-2', 0, 'お酒', 'おさけ', 'd3b89b1f-f075-490d-9bec-295dda0ae069', 0, 2, '[{"t":"お"},{"t":"酒","r":"さけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-2', 2, '飲みません', 'のみません', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 3, 8, '[{"t":"飲","r":"の"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-3', 0, '朝', 'あさ', 'd69bdfb8-8f9e-40d7-800c-f6361221d7b2', 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-3', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-3', 2, '勉強しません', 'べんきょうしません', 'b5a69b9b-5017-4a76-b301-dbd5c9f5ba2a', 2, 8, '[{"t":"勉強","r":"べんきょう"},{"t":"しません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-4', 0, '海', 'うみ', 'e3cb86b5-f5fc-4cf7-81de-c038f64be645', 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-4', 1, 'へ', 'へ', NULL, 1, 2, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-4', 2, '行きません', 'いきません', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 2, 7, '[{"t":"行","r":"い"},{"t":"きません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masen-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-1', 0, '新聞', 'しんぶん', '66072ae2-f8fc-4367-a221-cb59f3ec454a', 0, 2, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-1', 2, '読みました', 'よみました', '1c659ec9-be5a-4805-ab6c-51ceda5763fb', 3, 8, '[{"t":"読","r":"よ"},{"t":"みました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-2', 0, '海', 'うみ', 'e3cb86b5-f5fc-4cf7-81de-c038f64be645', 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-2', 1, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-2', 2, '泳ぎました', 'およぎました', '4a024e52-0385-4952-bf06-f139e395cb8f', 2, 7, '[{"t":"泳","r":"およ"},{"t":"ぎました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-2', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-3', 0, '友達', 'ともだち', '826a97e0-e8f0-4ae7-a4ce-c9899a7a3c6f', 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-3', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-3', 2, '会いました', 'あいました', '887821df-833f-4aac-a413-7ae78d3cfe17', 3, 8, '[{"t":"会","r":"あ"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-4', 0, '手紙', 'てがみ', '041bc6df-1284-47ba-95ff-b197c144f360', 0, 2, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-4', 2, '書きました', 'かきました', 'd28ed980-0333-4bf5-aab0-e7947c6ee424', 3, 8, '[{"t":"書","r":"か"},{"t":"きました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mashita-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-1', 0, '寒くないです', 'さむくないです', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 6, '[{"t":"寒","r":"さむ"},{"t":"くないです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-1', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-2', 0, '高くないです', 'たかくないです', 'ddc1e88a-997a-4781-8bc9-d3a184a07301', 0, 6, '[{"t":"高","r":"たか"},{"t":"くないです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-2', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-3', 0, '安くないです', 'やすくないです', 'c1f2deec-8ed2-4b54-b23c-5ae7d8524e07', 0, 6, '[{"t":"安","r":"やす"},{"t":"くないです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-3', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-4', 0, '忙しくないです', 'いそがしくないです', '65ae7422-9448-4faa-b28d-f80a027123bf', 0, 7, '[{"t":"忙","r":"いそが"},{"t":"しくないです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjneg-4', 1, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb);
