-- N5 example sentences, batch 5: the topics that were blocked.
--
-- Six of these ten could not be written at all until the tokeniser learned to
-- read a grammar pattern as one unit — 〜てもいい, 〜なければなりません, けど,
-- 〜つもり, 〜でしょう and こそあど each shredded into the kana they are spelled
-- with, and a sentence teaching a pattern necessarily contains it. The blocked
-- list is empty now.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- te-mo-ii
  ('sent-ex-temoii-1', 'lang-ja', '窓を開けてもいいですか。', 'まど お あけて も いい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-temoii-2', 'lang-ja', '写真を見てもいいですか。', 'しゃしん お みて も いい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-temoii-3', 'lang-ja', '水を飲んでもいいです。', 'みず お のんで も いい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-temoii-4', 'lang-ja', '少し休んでもいいですか。', 'すこし やすんで も いい です か。', 'lvl-ja-n5', 'authored', true),
  -- nakereba-narimasen
  ('sent-ex-nakereba-1', 'lang-ja', '勉強しなければなりません。', 'べんきょう しなければ なりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakereba-2', 'lang-ja', '早く起きなければなりません。', 'はやく おきなければ なりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakereba-3', 'lang-ja', '会社に行かなければなりません。', 'かいしゃ に いかなければ なりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakereba-4', 'lang-ja', '手紙を書かなければなりません。', 'てがみ お かかなければ なりません。', 'lvl-ja-n5', 'authored', true),
  -- kedo
  ('sent-ex-kedo-1', 'lang-ja', '安いけど、古いです。', 'やすい けど、ふるい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kedo-2', 'lang-ja', '買いますけど、高いです。', 'かいます けど、たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kedo-3', 'lang-ja', '忙しいけど、行きます。', 'いそがしい けど、いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kedo-4', 'lang-ja', '寒いけど、泳ぎます。', 'さむい けど、およぎます。', 'lvl-ja-n5', 'authored', true),
  -- tsumori
  ('sent-ex-tsumori-1', 'lang-ja', '日本へ行くつもりです。', 'にほん え いく つもり です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tsumori-2', 'lang-ja', '明日休むつもりです。', 'あした やすむ つもり です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tsumori-3', 'lang-ja', '車を買うつもりです。', 'くるま お かう つもり です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tsumori-4', 'lang-ja', '本を読むつもりです。', 'ほん お よむ つもり です。', 'lvl-ja-n5', 'authored', true),
  -- deshou
  ('sent-ex-deshou-1', 'lang-ja', '明日は寒いでしょう。', 'あした わ さむい でしょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshou-2', 'lang-ja', '雨が降るでしょう。', 'あめ が ふる でしょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshou-3', 'lang-ja', '友達も来るでしょう。', 'ともだち も くる でしょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshou-4', 'lang-ja', '店は高いでしょう。', 'みせ わ たかい でしょう。', 'lvl-ja-n5', 'authored', true),
  -- kosoado
  ('sent-ex-kosoado-1', 'lang-ja', 'これは本です。', 'これ わ ほん です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kosoado-2', 'lang-ja', 'それは私の靴です。', 'それ わ わたし の くつ です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kosoado-3', 'lang-ja', 'あれは学校です。', 'あれ わ がっこう です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kosoado-4', 'lang-ja', 'どれが好きですか。', 'どれ が すき です か。', 'lvl-ja-n5', 'authored', true),
  -- i-adj-past
  ('sent-ex-iadjpast-1', 'lang-ja', '寒かったです。', 'さむかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjpast-2', 'lang-ja', '暑かったです。', 'あつかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjpast-3', 'lang-ja', '高かったです。', 'たかかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjpast-4', 'lang-ja', '安かったです。', 'やすかった です。', 'lvl-ja-n5', 'authored', true),
  -- shika-nai
  ('sent-ex-shika-1', 'lang-ja', '水しか飲みません。', 'みず しか のみません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-shika-2', 'lang-ja', '本しか買いません。', 'ほん しか かいません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-shika-3', 'lang-ja', '魚しか食べません。', 'さかな しか たべません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-shika-4', 'lang-ja', '少ししか寝ません。', 'すこし しか ねません。', 'lvl-ja-n5', 'authored', true),
  -- masen-deshita
  ('sent-ex-masendeshita-1', 'lang-ja', '肉を食べませんでした。', 'にく お たべません でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masendeshita-2', 'lang-ja', '海へ行きませんでした。', 'うみ え いきません でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masendeshita-3', 'lang-ja', 'お酒を飲みませんでした。', 'おさけ お のみません でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masendeshita-4', 'lang-ja', '手紙を書きませんでした。', 'てがみ お かきません でした。', 'lvl-ja-n5', 'authored', true),
  -- nakatta
  ('sent-ex-nakatta-1', 'lang-ja', '寒くなかったです。', 'さむく なかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakatta-2', 'lang-ja', '高くなかったです。', 'たかく なかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakatta-3', 'lang-ja', '安くなかったです。', 'やすく なかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakatta-4', 'lang-ja', '暑くなかったです。', 'あつく なかった です。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-temoii-1', 'sent-ex-temoii-1', 'en', 'May I open the window?', 'authored'),
  ('st-ex-temoii-2', 'sent-ex-temoii-2', 'en', 'May I look at the photo?', 'authored'),
  ('st-ex-temoii-3', 'sent-ex-temoii-3', 'en', 'You may drink the water.', 'authored'),
  ('st-ex-temoii-4', 'sent-ex-temoii-4', 'en', 'May I rest a little?', 'authored'),
  ('st-ex-nakereba-1', 'sent-ex-nakereba-1', 'en', 'I have to study.', 'authored'),
  ('st-ex-nakereba-2', 'sent-ex-nakereba-2', 'en', 'I have to get up early.', 'authored'),
  ('st-ex-nakereba-3', 'sent-ex-nakereba-3', 'en', 'I have to go to the office.', 'authored'),
  ('st-ex-nakereba-4', 'sent-ex-nakereba-4', 'en', 'I have to write a letter.', 'authored'),
  ('st-ex-kedo-1', 'sent-ex-kedo-1', 'en', 'It''s cheap, but it''s old.', 'authored'),
  ('st-ex-kedo-2', 'sent-ex-kedo-2', 'en', 'I''ll buy it, but it''s expensive.', 'authored'),
  ('st-ex-kedo-3', 'sent-ex-kedo-3', 'en', 'I''m busy, but I''ll go.', 'authored'),
  ('st-ex-kedo-4', 'sent-ex-kedo-4', 'en', 'It''s cold, but I''ll swim.', 'authored'),
  ('st-ex-tsumori-1', 'sent-ex-tsumori-1', 'en', 'I intend to go to Japan.', 'authored'),
  ('st-ex-tsumori-2', 'sent-ex-tsumori-2', 'en', 'I intend to take tomorrow off.', 'authored'),
  ('st-ex-tsumori-3', 'sent-ex-tsumori-3', 'en', 'I intend to buy a car.', 'authored'),
  ('st-ex-tsumori-4', 'sent-ex-tsumori-4', 'en', 'I intend to read the book.', 'authored'),
  ('st-ex-deshou-1', 'sent-ex-deshou-1', 'en', 'It will probably be cold tomorrow.', 'authored'),
  ('st-ex-deshou-2', 'sent-ex-deshou-2', 'en', 'It will probably rain.', 'authored'),
  ('st-ex-deshou-3', 'sent-ex-deshou-3', 'en', 'My friend will probably come too.', 'authored'),
  ('st-ex-deshou-4', 'sent-ex-deshou-4', 'en', 'The shop is probably expensive.', 'authored'),
  ('st-ex-kosoado-1', 'sent-ex-kosoado-1', 'en', 'This is a book.', 'authored'),
  ('st-ex-kosoado-2', 'sent-ex-kosoado-2', 'en', 'Those are my shoes.', 'authored'),
  ('st-ex-kosoado-3', 'sent-ex-kosoado-3', 'en', 'That over there is a school.', 'authored'),
  ('st-ex-kosoado-4', 'sent-ex-kosoado-4', 'en', 'Which one do you like?', 'authored'),
  ('st-ex-iadjpast-1', 'sent-ex-iadjpast-1', 'en', 'It was cold.', 'authored'),
  ('st-ex-iadjpast-2', 'sent-ex-iadjpast-2', 'en', 'It was hot.', 'authored'),
  ('st-ex-iadjpast-3', 'sent-ex-iadjpast-3', 'en', 'It was expensive.', 'authored'),
  ('st-ex-iadjpast-4', 'sent-ex-iadjpast-4', 'en', 'It was cheap.', 'authored'),
  ('st-ex-shika-1', 'sent-ex-shika-1', 'en', 'I drink nothing but water.', 'authored'),
  ('st-ex-shika-2', 'sent-ex-shika-2', 'en', 'I buy nothing but books.', 'authored'),
  ('st-ex-shika-3', 'sent-ex-shika-3', 'en', 'I eat nothing but fish.', 'authored'),
  ('st-ex-shika-4', 'sent-ex-shika-4', 'en', 'I sleep only a little.', 'authored'),
  ('st-ex-masendeshita-1', 'sent-ex-masendeshita-1', 'en', 'I did not eat meat.', 'authored'),
  ('st-ex-masendeshita-2', 'sent-ex-masendeshita-2', 'en', 'I did not go to the sea.', 'authored'),
  ('st-ex-masendeshita-3', 'sent-ex-masendeshita-3', 'en', 'I did not drink alcohol.', 'authored'),
  ('st-ex-masendeshita-4', 'sent-ex-masendeshita-4', 'en', 'I did not write a letter.', 'authored'),
  ('st-ex-nakatta-1', 'sent-ex-nakatta-1', 'en', 'It was not cold.', 'authored'),
  ('st-ex-nakatta-2', 'sent-ex-nakatta-2', 'en', 'It was not expensive.', 'authored'),
  ('st-ex-nakatta-3', 'sent-ex-nakatta-3', 'en', 'It was not cheap.', 'authored'),
  ('st-ex-nakatta-4', 'sent-ex-nakatta-4', 'en', 'It was not hot.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('te-mo-ii', 'sent-ex-temoii-1', 0),
  ('te-mo-ii', 'sent-ex-temoii-2', 1),
  ('te-mo-ii', 'sent-ex-temoii-3', 2),
  ('te-mo-ii', 'sent-ex-temoii-4', 3),
  ('nakereba-narimasen', 'sent-ex-nakereba-1', 0),
  ('nakereba-narimasen', 'sent-ex-nakereba-2', 1),
  ('nakereba-narimasen', 'sent-ex-nakereba-3', 2),
  ('nakereba-narimasen', 'sent-ex-nakereba-4', 3),
  ('kedo', 'sent-ex-kedo-1', 0),
  ('kedo', 'sent-ex-kedo-2', 1),
  ('kedo', 'sent-ex-kedo-3', 2),
  ('kedo', 'sent-ex-kedo-4', 3),
  ('tsumori', 'sent-ex-tsumori-1', 0),
  ('tsumori', 'sent-ex-tsumori-2', 1),
  ('tsumori', 'sent-ex-tsumori-3', 2),
  ('tsumori', 'sent-ex-tsumori-4', 3),
  ('deshou', 'sent-ex-deshou-1', 0),
  ('deshou', 'sent-ex-deshou-2', 1),
  ('deshou', 'sent-ex-deshou-3', 2),
  ('deshou', 'sent-ex-deshou-4', 3),
  ('kosoado', 'sent-ex-kosoado-1', 0),
  ('kosoado', 'sent-ex-kosoado-2', 1),
  ('kosoado', 'sent-ex-kosoado-3', 2),
  ('kosoado', 'sent-ex-kosoado-4', 3),
  ('i-adj-past', 'sent-ex-iadjpast-1', 0),
  ('i-adj-past', 'sent-ex-iadjpast-2', 1),
  ('i-adj-past', 'sent-ex-iadjpast-3', 2),
  ('i-adj-past', 'sent-ex-iadjpast-4', 3),
  ('shika-nai', 'sent-ex-shika-1', 0),
  ('shika-nai', 'sent-ex-shika-2', 1),
  ('shika-nai', 'sent-ex-shika-3', 2),
  ('shika-nai', 'sent-ex-shika-4', 3),
  ('masen-deshita', 'sent-ex-masendeshita-1', 0),
  ('masen-deshita', 'sent-ex-masendeshita-2', 1),
  ('masen-deshita', 'sent-ex-masendeshita-3', 2),
  ('masen-deshita', 'sent-ex-masendeshita-4', 3),
  ('nakatta', 'sent-ex-nakatta-1', 0),
  ('nakatta', 'sent-ex-nakatta-2', 1),
  ('nakatta', 'sent-ex-nakatta-3', 2),
  ('nakatta', 'sent-ex-nakatta-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-temoii-1', 'sent-ex-temoii-2', 'sent-ex-temoii-3', 'sent-ex-temoii-4', 'sent-ex-nakereba-1', 'sent-ex-nakereba-2', 'sent-ex-nakereba-3', 'sent-ex-nakereba-4', 'sent-ex-kedo-1', 'sent-ex-kedo-2', 'sent-ex-kedo-3', 'sent-ex-kedo-4', 'sent-ex-tsumori-1', 'sent-ex-tsumori-2', 'sent-ex-tsumori-3', 'sent-ex-tsumori-4', 'sent-ex-deshou-1', 'sent-ex-deshou-2', 'sent-ex-deshou-3', 'sent-ex-deshou-4', 'sent-ex-kosoado-1', 'sent-ex-kosoado-2', 'sent-ex-kosoado-3', 'sent-ex-kosoado-4', 'sent-ex-iadjpast-1', 'sent-ex-iadjpast-2', 'sent-ex-iadjpast-3', 'sent-ex-iadjpast-4', 'sent-ex-shika-1', 'sent-ex-shika-2', 'sent-ex-shika-3', 'sent-ex-shika-4', 'sent-ex-masendeshita-1', 'sent-ex-masendeshita-2', 'sent-ex-masendeshita-3', 'sent-ex-masendeshita-4', 'sent-ex-nakatta-1', 'sent-ex-nakatta-2', 'sent-ex-nakatta-3', 'sent-ex-nakatta-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 0, '窓', 'まど', '590df083-c00c-4652-bcdd-f7630ff251d0', 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 2, '開けて', 'あけて', '8fba3d97-141b-4404-86e7-6530e7c19e3c', 2, 5, '[{"t":"開","r":"あ"},{"t":"けて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 3, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 5, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 0, '写真', 'しゃしん', '22d349ca-aa49-4f0e-b283-319611ccdf3c', 0, 2, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 2, '見て', 'みて', '85ec6cc4-0dca-4479-abcf-d53e33fc9e49', 3, 5, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 3, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 5, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 0, '水', 'みず', '02cd9dd6-94a1-43e7-9e49-2dfff6e0edf2', 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 2, '飲んで', 'のんで', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 2, 5, '[{"t":"飲","r":"の"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 3, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 0, '少し', 'すこし', 'c3fea249-9141-44a5-a822-a2bbe599d73d', 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 1, '休んで', 'やすんで', '52fd60de-a97d-47be-9b31-894be752027a', 2, 5, '[{"t":"休","r":"やす"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 2, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 3, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 4, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 0, '勉強', 'べんきょう', 'b5a69b9b-5017-4a76-b301-dbd5c9f5ba2a', 0, 2, '[{"t":"勉強","r":"べんきょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 1, 'し', 'し', '56bf2da7-a29f-422c-bfe1-331fecf3bb9e', 2, 3, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 2, 'なければなりません', 'なければなりません', NULL, 3, 12, '[{"t":"なければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 3, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-2', 0, '早く', 'はやく', '416d3a31-5940-475c-8c7f-d7997aff8665', 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-2', 1, '起きなければなりません', 'おきなければなりません', '5fb365d9-60b4-4d75-a1c7-5170ce4bbcf5', 2, 13, '[{"t":"起","r":"お"},{"t":"きなければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-2', 2, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 0, '会社', 'かいしゃ', '25dda620-f5a1-476f-8bb1-bef2843c78ea', 0, 2, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 2, '行かなければなりません', 'いかなければなりません', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 3, 14, '[{"t":"行","r":"い"},{"t":"かなければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 3, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 0, '手紙', 'てがみ', '041bc6df-1284-47ba-95ff-b197c144f360', 0, 2, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 2, '書かなければなりません', 'かかなければなりません', 'd28ed980-0333-4bf5-aab0-e7947c6ee424', 3, 14, '[{"t":"書","r":"か"},{"t":"かなければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 3, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 0, '安い', 'やすい', '817cb322-0f7f-4c83-a195-dde87e4bd13f', 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 1, 'けど', 'けど', NULL, 2, 4, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 3, '古い', 'ふるい', '10baa5e0-ce4b-4c15-8907-b6884ec41fdc', 5, 7, '[{"t":"古","r":"ふる"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 0, '買います', 'かいます', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 0, 4, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 1, 'けど', 'けど', NULL, 4, 6, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 3, '高い', 'たかい', 'b9f375ce-c7e3-4b81-bfed-58fb9057bc8a', 7, 9, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 4, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 0, '忙しい', 'いそがしい', '65ae7422-9448-4faa-b28d-f80a027123bf', 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 1, 'けど', 'けど', NULL, 3, 5, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 3, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 0, '寒い', 'さむい', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 2, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 1, 'けど', 'けど', NULL, 2, 4, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 3, '泳ぎます', 'およぎます', '4a024e52-0385-4952-bf06-f139e395cb8f', 5, 9, '[{"t":"泳","r":"およ"},{"t":"ぎます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 0, '日本', 'にほん', '9de924d0-d7d7-4284-bbae-c05ecbef3e5e', 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 1, 'へ', 'へ', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 2, '行く', 'いく', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 3, 5, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 3, 'つもり', 'つもり', NULL, 5, 8, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 0, '明日', 'あした', '823cfb1a-cb34-4c88-86d6-5cdfca69eed5', 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 1, '休む', 'やすむ', '52fd60de-a97d-47be-9b31-894be752027a', 2, 4, '[{"t":"休","r":"やす"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 2, 'つもり', 'つもり', NULL, 4, 7, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 3, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 0, '車', 'くるま', '5dc5735d-214f-4348-b3ee-a0fb3c4bdb9f', 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 2, '買う', 'かう', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 2, 4, '[{"t":"買","r":"か"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 3, 'つもり', 'つもり', NULL, 4, 7, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 2, '読む', 'よむ', '1c659ec9-be5a-4805-ab6c-51ceda5763fb', 2, 4, '[{"t":"読","r":"よ"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 3, 'つもり', 'つもり', NULL, 4, 7, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 0, '明日', 'あした', '823cfb1a-cb34-4c88-86d6-5cdfca69eed5', 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 2, '寒い', 'さむい', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 3, 5, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 3, 'でしょう', 'でしょう', NULL, 5, 9, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 0, '雨', 'あめ', '754619f1-15a8-48dc-a8c0-81c74ea9a69a', 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 2, '降る', 'ふる', '5ace5ec6-4992-4ab8-abbb-6ee6dd197435', 2, 4, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 3, 'でしょう', 'でしょう', NULL, 4, 8, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 0, '友達', 'ともだち', '826a97e0-e8f0-4ae7-a4ce-c9899a7a3c6f', 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 2, '来る', 'くる', 'e40f6686-fee0-4bc0-820d-ba5c272193a8', 3, 5, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 3, 'でしょう', 'でしょう', NULL, 5, 9, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 0, '店', 'みせ', '0d3b2056-ec77-4e25-b39c-f6ade640ed47', 0, 1, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 2, '高い', 'たかい', 'b9f375ce-c7e3-4b81-bfed-58fb9057bc8a', 2, 4, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 3, 'でしょう', 'でしょう', NULL, 4, 8, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 0, 'これ', 'これ', 'ad6ab23c-4a16-4a3d-b96c-9a67ed6aebf9', 0, 2, '[{"t":"これ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 2, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 3, 4, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 3, 'です', 'です', NULL, 4, 6, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 0, 'それ', 'それ', '3a4d7c20-6525-4d93-865d-3abdbaba0d67', 0, 2, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 2, '私', 'わたし', '07d07dec-dc8f-45b2-8095-b49b5087da75', 3, 4, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 4, '靴', 'くつ', 'da19bf49-6698-4142-bf0f-90077a00f120', 5, 6, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 5, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 6, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 0, 'あれ', 'あれ', 'b93da0ef-2b8a-4dad-b645-8b25ad756914', 0, 2, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 2, '学校', 'がっこう', 'c6989610-93a3-4175-8b9c-d969d934a05a', 3, 5, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 0, 'どれ', 'どれ', NULL, 0, 2, '[{"t":"どれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 3, 5, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 4, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-1', 0, '寒かったです', 'さむかったです', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 6, '[{"t":"寒","r":"さむ"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-1', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-2', 0, '暑かったです', 'あつかったです', '24ba41c3-4af8-45a2-9f3a-318c80560e5b', 0, 6, '[{"t":"暑","r":"あつ"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-2', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-3', 0, '高かったです', 'たかかったです', 'ddc1e88a-997a-4781-8bc9-d3a184a07301', 0, 6, '[{"t":"高","r":"たか"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-3', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-4', 0, '安かったです', 'やすかったです', 'c1f2deec-8ed2-4b54-b23c-5ae7d8524e07', 0, 6, '[{"t":"安","r":"やす"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-4', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 0, '水', 'みず', '02cd9dd6-94a1-43e7-9e49-2dfff6e0edf2', 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 1, 'しか', 'しか', 'a3348ac5-92fb-42b2-a796-9a6e2de58381', 1, 3, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 2, '飲みません', 'のみません', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 3, 8, '[{"t":"飲","r":"の"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 1, 'しか', 'しか', 'a3348ac5-92fb-42b2-a796-9a6e2de58381', 1, 3, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 2, '買いません', 'かいません', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 3, 8, '[{"t":"買","r":"か"},{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 0, '魚', 'さかな', 'e1e048a7-24b7-4875-8727-b61a2e2c4857', 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 1, 'しか', 'しか', 'a3348ac5-92fb-42b2-a796-9a6e2de58381', 1, 3, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 2, '食べません', 'たべません', '788557df-2bac-4ae7-a157-8a81fbe1da16', 3, 8, '[{"t":"食","r":"た"},{"t":"べません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 0, '少し', 'すこし', 'c3fea249-9141-44a5-a822-a2bbe599d73d', 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 1, 'しか', 'しか', 'a3348ac5-92fb-42b2-a796-9a6e2de58381', 2, 4, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 2, '寝ません', 'ねません', '056f037c-201a-4cd0-85be-f063237124fd', 4, 8, '[{"t":"寝","r":"ね"},{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 0, '肉', 'にく', '5df9f1a7-e606-44b7-b5a7-484d84d86549', 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 2, '食べませんでした', 'たべませんでした', '788557df-2bac-4ae7-a157-8a81fbe1da16', 2, 10, '[{"t":"食","r":"た"},{"t":"べませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 0, '海', 'うみ', 'e3cb86b5-f5fc-4cf7-81de-c038f64be645', 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 1, 'へ', 'へ', NULL, 1, 2, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 2, '行きませんでした', 'いきませんでした', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 2, 10, '[{"t":"行","r":"い"},{"t":"きませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 0, 'お酒', 'おさけ', 'd3b89b1f-f075-490d-9bec-295dda0ae069', 0, 2, '[{"t":"お"},{"t":"酒","r":"さけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 2, '飲みませんでした', 'のみませんでした', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 3, 11, '[{"t":"飲","r":"の"},{"t":"みませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 0, '手紙', 'てがみ', '041bc6df-1284-47ba-95ff-b197c144f360', 0, 2, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 2, '書きませんでした', 'かきませんでした', 'd28ed980-0333-4bf5-aab0-e7947c6ee424', 3, 11, '[{"t":"書","r":"か"},{"t":"きませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-1', 0, '寒くなかったです', 'さむくなかったです', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 8, '[{"t":"寒","r":"さむ"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-1', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-2', 0, '高くなかったです', 'たかくなかったです', 'ddc1e88a-997a-4781-8bc9-d3a184a07301', 0, 8, '[{"t":"高","r":"たか"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-2', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-3', 0, '安くなかったです', 'やすくなかったです', 'c1f2deec-8ed2-4b54-b23c-5ae7d8524e07', 0, 8, '[{"t":"安","r":"やす"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-3', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-4', 0, '暑くなかったです', 'あつくなかったです', '24ba41c3-4af8-45a2-9f3a-318c80560e5b', 0, 8, '[{"t":"暑","r":"あつ"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-4', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb);
