-- N5 example sentences, batch 5: the topics that were blocked.
--
-- Six of these ten could not be written at all until the tokeniser learned to
-- read a grammar pattern as one unit — 〜てもいい, 〜なければなりません, けど,
-- 〜つもり, 〜でしょう and こそあど each shredded into the kana they are spelled
-- with, and a sentence teaching a pattern necessarily contains it. The blocked
-- list is empty now.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- te-mo-ii
  ('sent-ex-temoii-1', 'lang-ja', '窓を開けてもいいですか。', 'まど お あけて も いい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-temoii-2', 'lang-ja', '写真を見てもいいですか。', 'しゃしん お みて も いい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-temoii-3', 'lang-ja', '水を飲んでもいいです。', 'みず お のんで も いい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-temoii-4', 'lang-ja', '少し休んでもいいですか。', 'すこし やすんで も いい です か。', 'lvl-ja-n5', 'authored', true),
  -- nakereba-narimasen
  ('sent-ex-nakereba-1', 'lang-ja', '勉強しなければなりません。', 'べんきょう しなければ なりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakereba-2', 'lang-ja', '早く起きなければなりません。', 'はやく おきなければ なりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakereba-3', 'lang-ja', '会社に行かなければなりません。', 'かいしゃ に いかなければ なりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakereba-4', 'lang-ja', '手紙を書かなければなりません。', 'てがみ お かかなければ なりません。', 'lvl-ja-n5', 'authored', true),
  -- kedo
  ('sent-ex-kedo-1', 'lang-ja', '安いけど、古いです。', 'やすい けど、ふるい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kedo-2', 'lang-ja', '買いますけど、高いです。', 'かいます けど、たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kedo-3', 'lang-ja', '忙しいけど、行きます。', 'いそがしい けど、いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kedo-4', 'lang-ja', '寒いけど、泳ぎます。', 'さむい けど、およぎます。', 'lvl-ja-n5', 'authored', true),
  -- tsumori
  ('sent-ex-tsumori-1', 'lang-ja', '日本へ行くつもりです。', 'にほん え いく つもり です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tsumori-2', 'lang-ja', '明日休むつもりです。', 'あした やすむ つもり です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tsumori-3', 'lang-ja', '車を買うつもりです。', 'くるま お かう つもり です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tsumori-4', 'lang-ja', '本を読むつもりです。', 'ほん お よむ つもり です。', 'lvl-ja-n5', 'authored', true),
  -- deshou
  ('sent-ex-deshou-1', 'lang-ja', '明日は寒いでしょう。', 'あした わ さむい でしょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshou-2', 'lang-ja', '雨が降るでしょう。', 'あめ が ふる でしょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshou-3', 'lang-ja', '友達も来るでしょう。', 'ともだち も くる でしょう。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshou-4', 'lang-ja', '店は高いでしょう。', 'みせ わ たかい でしょう。', 'lvl-ja-n5', 'authored', true),
  -- kosoado
  ('sent-ex-kosoado-1', 'lang-ja', 'これは本です。', 'これ わ ほん です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kosoado-2', 'lang-ja', 'それは私の靴です。', 'それ わ わたし の くつ です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kosoado-3', 'lang-ja', 'あれは学校です。', 'あれ わ がっこう です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kosoado-4', 'lang-ja', 'どれが好きですか。', 'どれ が すき です か。', 'lvl-ja-n5', 'authored', true),
  -- i-adj-past
  ('sent-ex-iadjpast-1', 'lang-ja', '寒かったです。', 'さむかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjpast-2', 'lang-ja', '暑かったです。', 'あつかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjpast-3', 'lang-ja', '高かったです。', 'たかかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-iadjpast-4', 'lang-ja', '安かったです。', 'やすかった です。', 'lvl-ja-n5', 'authored', true),
  -- shika-nai
  ('sent-ex-shika-1', 'lang-ja', '水しか飲みません。', 'みず しか のみません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-shika-2', 'lang-ja', '本しか買いません。', 'ほん しか かいません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-shika-3', 'lang-ja', '魚しか食べません。', 'さかな しか たべません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-shika-4', 'lang-ja', '少ししか寝ません。', 'すこし しか ねません。', 'lvl-ja-n5', 'authored', true),
  -- masen-deshita
  ('sent-ex-masendeshita-1', 'lang-ja', '肉を食べませんでした。', 'にく お たべません でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masendeshita-2', 'lang-ja', '海へ行きませんでした。', 'うみ え いきません でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masendeshita-3', 'lang-ja', 'お酒を飲みませんでした。', 'おさけ お のみません でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-masendeshita-4', 'lang-ja', '手紙を書きませんでした。', 'てがみ お かきません でした。', 'lvl-ja-n5', 'authored', true),
  -- nakatta
  ('sent-ex-nakatta-1', 'lang-ja', '寒くなかったです。', 'さむく なかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakatta-2', 'lang-ja', '高くなかったです。', 'たかく なかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakatta-3', 'lang-ja', '安くなかったです。', 'やすく なかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakatta-4', 'lang-ja', '暑くなかったです。', 'あつく なかった です。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-temoii-1', 'sent-ex-temoii-1', 'en', 'May I open the window?', 'authored'),
  ('st-ex-temoii-2', 'sent-ex-temoii-2', 'en', 'May I look at the photo?', 'authored'),
  ('st-ex-temoii-3', 'sent-ex-temoii-3', 'en', 'You may drink the water.', 'authored'),
  ('st-ex-temoii-4', 'sent-ex-temoii-4', 'en', 'May I rest a little?', 'authored'),
  ('st-ex-nakereba-1', 'sent-ex-nakereba-1', 'en', 'I have to study.', 'authored'),
  ('st-ex-nakereba-2', 'sent-ex-nakereba-2', 'en', 'I have to get up early.', 'authored'),
  ('st-ex-nakereba-3', 'sent-ex-nakereba-3', 'en', 'I have to go to the office.', 'authored'),
  ('st-ex-nakereba-4', 'sent-ex-nakereba-4', 'en', 'I have to write a letter.', 'authored'),
  ('st-ex-kedo-1', 'sent-ex-kedo-1', 'en', 'It''s cheap, but it''s old.', 'authored'),
  ('st-ex-kedo-2', 'sent-ex-kedo-2', 'en', 'I''ll buy it, but it''s expensive.', 'authored'),
  ('st-ex-kedo-3', 'sent-ex-kedo-3', 'en', 'I''m busy, but I''ll go.', 'authored'),
  ('st-ex-kedo-4', 'sent-ex-kedo-4', 'en', 'It''s cold, but I''ll swim.', 'authored'),
  ('st-ex-tsumori-1', 'sent-ex-tsumori-1', 'en', 'I intend to go to Japan.', 'authored'),
  ('st-ex-tsumori-2', 'sent-ex-tsumori-2', 'en', 'I intend to take tomorrow off.', 'authored'),
  ('st-ex-tsumori-3', 'sent-ex-tsumori-3', 'en', 'I intend to buy a car.', 'authored'),
  ('st-ex-tsumori-4', 'sent-ex-tsumori-4', 'en', 'I intend to read the book.', 'authored'),
  ('st-ex-deshou-1', 'sent-ex-deshou-1', 'en', 'It will probably be cold tomorrow.', 'authored'),
  ('st-ex-deshou-2', 'sent-ex-deshou-2', 'en', 'It will probably rain.', 'authored'),
  ('st-ex-deshou-3', 'sent-ex-deshou-3', 'en', 'My friend will probably come too.', 'authored'),
  ('st-ex-deshou-4', 'sent-ex-deshou-4', 'en', 'The shop is probably expensive.', 'authored'),
  ('st-ex-kosoado-1', 'sent-ex-kosoado-1', 'en', 'This is a book.', 'authored'),
  ('st-ex-kosoado-2', 'sent-ex-kosoado-2', 'en', 'Those are my shoes.', 'authored'),
  ('st-ex-kosoado-3', 'sent-ex-kosoado-3', 'en', 'That over there is a school.', 'authored'),
  ('st-ex-kosoado-4', 'sent-ex-kosoado-4', 'en', 'Which one do you like?', 'authored'),
  ('st-ex-iadjpast-1', 'sent-ex-iadjpast-1', 'en', 'It was cold.', 'authored'),
  ('st-ex-iadjpast-2', 'sent-ex-iadjpast-2', 'en', 'It was hot.', 'authored'),
  ('st-ex-iadjpast-3', 'sent-ex-iadjpast-3', 'en', 'It was expensive.', 'authored'),
  ('st-ex-iadjpast-4', 'sent-ex-iadjpast-4', 'en', 'It was cheap.', 'authored'),
  ('st-ex-shika-1', 'sent-ex-shika-1', 'en', 'I drink nothing but water.', 'authored'),
  ('st-ex-shika-2', 'sent-ex-shika-2', 'en', 'I buy nothing but books.', 'authored'),
  ('st-ex-shika-3', 'sent-ex-shika-3', 'en', 'I eat nothing but fish.', 'authored'),
  ('st-ex-shika-4', 'sent-ex-shika-4', 'en', 'I sleep only a little.', 'authored'),
  ('st-ex-masendeshita-1', 'sent-ex-masendeshita-1', 'en', 'I did not eat meat.', 'authored'),
  ('st-ex-masendeshita-2', 'sent-ex-masendeshita-2', 'en', 'I did not go to the sea.', 'authored'),
  ('st-ex-masendeshita-3', 'sent-ex-masendeshita-3', 'en', 'I did not drink alcohol.', 'authored'),
  ('st-ex-masendeshita-4', 'sent-ex-masendeshita-4', 'en', 'I did not write a letter.', 'authored'),
  ('st-ex-nakatta-1', 'sent-ex-nakatta-1', 'en', 'It was not cold.', 'authored'),
  ('st-ex-nakatta-2', 'sent-ex-nakatta-2', 'en', 'It was not expensive.', 'authored'),
  ('st-ex-nakatta-3', 'sent-ex-nakatta-3', 'en', 'It was not cheap.', 'authored'),
  ('st-ex-nakatta-4', 'sent-ex-nakatta-4', 'en', 'It was not hot.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('te-mo-ii', 'sent-ex-temoii-1', 0),
  ('te-mo-ii', 'sent-ex-temoii-2', 1),
  ('te-mo-ii', 'sent-ex-temoii-3', 2),
  ('te-mo-ii', 'sent-ex-temoii-4', 3),
  ('nakereba-narimasen', 'sent-ex-nakereba-1', 0),
  ('nakereba-narimasen', 'sent-ex-nakereba-2', 1),
  ('nakereba-narimasen', 'sent-ex-nakereba-3', 2),
  ('nakereba-narimasen', 'sent-ex-nakereba-4', 3),
  ('kedo', 'sent-ex-kedo-1', 0),
  ('kedo', 'sent-ex-kedo-2', 1),
  ('kedo', 'sent-ex-kedo-3', 2),
  ('kedo', 'sent-ex-kedo-4', 3),
  ('tsumori', 'sent-ex-tsumori-1', 0),
  ('tsumori', 'sent-ex-tsumori-2', 1),
  ('tsumori', 'sent-ex-tsumori-3', 2),
  ('tsumori', 'sent-ex-tsumori-4', 3),
  ('deshou', 'sent-ex-deshou-1', 0),
  ('deshou', 'sent-ex-deshou-2', 1),
  ('deshou', 'sent-ex-deshou-3', 2),
  ('deshou', 'sent-ex-deshou-4', 3),
  ('kosoado', 'sent-ex-kosoado-1', 0),
  ('kosoado', 'sent-ex-kosoado-2', 1),
  ('kosoado', 'sent-ex-kosoado-3', 2),
  ('kosoado', 'sent-ex-kosoado-4', 3),
  ('i-adj-past', 'sent-ex-iadjpast-1', 0),
  ('i-adj-past', 'sent-ex-iadjpast-2', 1),
  ('i-adj-past', 'sent-ex-iadjpast-3', 2),
  ('i-adj-past', 'sent-ex-iadjpast-4', 3),
  ('shika-nai', 'sent-ex-shika-1', 0),
  ('shika-nai', 'sent-ex-shika-2', 1),
  ('shika-nai', 'sent-ex-shika-3', 2),
  ('shika-nai', 'sent-ex-shika-4', 3),
  ('masen-deshita', 'sent-ex-masendeshita-1', 0),
  ('masen-deshita', 'sent-ex-masendeshita-2', 1),
  ('masen-deshita', 'sent-ex-masendeshita-3', 2),
  ('masen-deshita', 'sent-ex-masendeshita-4', 3),
  ('nakatta', 'sent-ex-nakatta-1', 0),
  ('nakatta', 'sent-ex-nakatta-2', 1),
  ('nakatta', 'sent-ex-nakatta-3', 2),
  ('nakatta', 'sent-ex-nakatta-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-temoii-1', 'sent-ex-temoii-2', 'sent-ex-temoii-3', 'sent-ex-temoii-4', 'sent-ex-nakereba-1', 'sent-ex-nakereba-2', 'sent-ex-nakereba-3', 'sent-ex-nakereba-4', 'sent-ex-kedo-1', 'sent-ex-kedo-2', 'sent-ex-kedo-3', 'sent-ex-kedo-4', 'sent-ex-tsumori-1', 'sent-ex-tsumori-2', 'sent-ex-tsumori-3', 'sent-ex-tsumori-4', 'sent-ex-deshou-1', 'sent-ex-deshou-2', 'sent-ex-deshou-3', 'sent-ex-deshou-4', 'sent-ex-kosoado-1', 'sent-ex-kosoado-2', 'sent-ex-kosoado-3', 'sent-ex-kosoado-4', 'sent-ex-iadjpast-1', 'sent-ex-iadjpast-2', 'sent-ex-iadjpast-3', 'sent-ex-iadjpast-4', 'sent-ex-shika-1', 'sent-ex-shika-2', 'sent-ex-shika-3', 'sent-ex-shika-4', 'sent-ex-masendeshita-1', 'sent-ex-masendeshita-2', 'sent-ex-masendeshita-3', 'sent-ex-masendeshita-4', 'sent-ex-nakatta-1', 'sent-ex-nakatta-2', 'sent-ex-nakatta-3', 'sent-ex-nakatta-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 0, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 2, '開けて', 'あけて', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"開","r":"あ"},{"t":"けて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 3, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 5, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 0, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 2, '見て', 'みて', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 3, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 5, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 2, '飲んで', 'のんで', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"飲","r":"の"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 3, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-3', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 0, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 1, '休んで', 'やすんで', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"休","r":"やす"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 2, 'もいい', 'もいい', NULL, 5, 8, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 3, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 4, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temoii-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 0, '勉強', 'べんきょう', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"勉強","r":"べんきょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 1, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 2, 'なければなりません', 'なければなりません', NULL, 3, 12, '[{"t":"なければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-1', 3, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-2', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-2', 1, '起きなければなりません', 'おきなければなりません', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 2, 13, '[{"t":"起","r":"お"},{"t":"きなければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-2', 2, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 0, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 2, '行かなければなりません', 'いかなければなりません', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 14, '[{"t":"行","r":"い"},{"t":"かなければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-3', 3, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 0, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 2, '書かなければなりません', 'かかなければなりません', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 3, 14, '[{"t":"書","r":"か"},{"t":"かなければなりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakereba-4', 3, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 1, 'けど', 'けど', NULL, 2, 4, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 3, '古い', 'ふるい', (select id from words where primary_form = '古い' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"古","r":"ふる"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 0, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 1, 'けど', 'けど', NULL, 4, 6, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 3, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 4, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 1, 'けど', 'けど', NULL, 3, 5, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 3, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 0, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 1, 'けど', 'けど', NULL, 2, 4, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 3, '泳ぎます', 'およぎます', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"泳","r":"およ"},{"t":"ぎます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kedo-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 1, 'へ', 'へ', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 2, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 3, 'つもり', 'つもり', NULL, 5, 8, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 1, '休む', 'やすむ', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"休","r":"やす"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 2, 'つもり', 'つもり', NULL, 4, 7, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 3, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 0, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 2, '買う', 'かう', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"買","r":"か"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 3, 'つもり', 'つもり', NULL, 4, 7, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 2, '読む', 'よむ', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"読","r":"よ"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 3, 'つもり', 'つもり', NULL, 4, 7, '[{"t":"つもり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsumori-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 2, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 3, 'でしょう', 'でしょう', NULL, 5, 9, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 2, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 3, 'でしょう', 'でしょう', NULL, 4, 8, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 3, 'でしょう', 'でしょう', NULL, 5, 9, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 0, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 2, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 3, 'でしょう', 'でしょう', NULL, 4, 8, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshou-4', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 0, 'これ', 'これ', (select id from words where primary_form = 'これ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"これ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 2, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 3, 'です', 'です', NULL, 4, 6, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-1', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 0, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 2, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 4, '靴', 'くつ', (select id from words where primary_form = '靴' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 5, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-2', 6, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 0, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 2, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-3', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 0, 'どれ', 'どれ', NULL, 0, 2, '[{"t":"どれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 2, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 4, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kosoado-4', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-1', 0, '寒かったです', 'さむかったです', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"寒","r":"さむ"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-1', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-2', 0, '暑かったです', 'あつかったです', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"暑","r":"あつ"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-2', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-3', 0, '高かったです', 'たかかったです', (select id from words where primary_form = '高まる' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"高","r":"たか"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-3', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-4', 0, '安かったです', 'やすかったです', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"安","r":"やす"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-iadjpast-4', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 1, 'しか', 'しか', (select id from words where primary_form = 'しか' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 2, '飲みません', 'のみません', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"飲","r":"の"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 1, 'しか', 'しか', (select id from words where primary_form = 'しか' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 2, '買いません', 'かいません', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"買","r":"か"},{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 1, 'しか', 'しか', (select id from words where primary_form = 'しか' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 2, '食べません', 'たべません', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"食","r":"た"},{"t":"べません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 0, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 1, 'しか', 'しか', (select id from words where primary_form = 'しか' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"しか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 2, '寝ません', 'ねません', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"寝","r":"ね"},{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shika-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 0, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 2, '食べませんでした', 'たべませんでした', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 10, '[{"t":"食","r":"た"},{"t":"べませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-1', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 0, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 1, 'へ', 'へ', NULL, 1, 2, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 2, '行きませんでした', 'いきませんでした', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 10, '[{"t":"行","r":"い"},{"t":"きませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-2', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 0, 'お酒', 'おさけ', (select id from words where primary_form = 'お酒' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"酒","r":"さけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 2, '飲みませんでした', 'のみませんでした', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 3, 11, '[{"t":"飲","r":"の"},{"t":"みませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-3', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 0, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 2, '書きませんでした', 'かきませんでした', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 3, 11, '[{"t":"書","r":"か"},{"t":"きませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-masendeshita-4', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-1', 0, '寒くなかったです', 'さむくなかったです', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 0, 8, '[{"t":"寒","r":"さむ"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-1', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-2', 0, '高くなかったです', 'たかくなかったです', (select id from words where primary_form = '高まる' and language_id = 'lang-ja' and published order by id limit 1), 0, 8, '[{"t":"高","r":"たか"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-2', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-3', 0, '安くなかったです', 'やすくなかったです', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 0, 8, '[{"t":"安","r":"やす"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-3', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-4', 0, '暑くなかったです', 'あつくなかったです', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 0, 8, '[{"t":"暑","r":"あつ"},{"t":"くなかったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakatta-4', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb);
