-- N5 example sentences, batch 6: でした, じゃありません, naAdj past, adverbs,
-- ね, よ, 〜のです, まで (time), から (from) and など.
--
-- The first batch since the tokeniser learned to read grammar patterns, and it
-- shows: all forty sentences passed `check:examples` on the first attempt,
-- where earlier batches needed two or three rewrites each to work around です
-- and its relatives shredding.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- deshita
  ('sent-ex-deshita-1', 'lang-ja', '昨日は水曜日でした。', 'きのう わ すいようび でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshita-2', 'lang-ja', '母は先生でした。', 'はは わ せんせい でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshita-3', 'lang-ja', '昨日は休みでした。', 'きのう わ やすみ でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-deshita-4', 'lang-ja', '私の靴でした。', 'わたし の くつ でした。', 'lvl-ja-n5', 'authored', true),
  -- ja-arimasen
  ('sent-ex-jaarimasen-1', 'lang-ja', '学生じゃありません。', 'がくせい じゃ ありません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jaarimasen-2', 'lang-ja', '私の本じゃありません。', 'わたし の ほん じゃ ありません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jaarimasen-3', 'lang-ja', '先生じゃありません。', 'せんせい じゃ ありません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jaarimasen-4', 'lang-ja', '猫じゃありません。', 'ねこ じゃ ありません。', 'lvl-ja-n5', 'authored', true),
  -- na-adj-past
  ('sent-ex-naadjpast-1', 'lang-ja', '静かでした。', 'しずか でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naadjpast-2', 'lang-ja', '元気でした。', 'げんき でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naadjpast-3', 'lang-ja', '綺麗でした。', 'きれい でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-naadjpast-4', 'lang-ja', '便利でした。', 'べんり でした。', 'lvl-ja-n5', 'authored', true),
  -- adverb-ku
  ('sent-ex-adverb-1', 'lang-ja', '早く起きます。', 'はやく おきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-adverb-2', 'lang-ja', '静かに話します。', 'しずか に はなします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-adverb-3', 'lang-ja', '安く買いました。', 'やすく かいました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-adverb-4', 'lang-ja', '綺麗に洗います。', 'きれい に あらいます。', 'lvl-ja-n5', 'authored', true),
  -- ne-particle
  ('sent-ex-ne-1', 'lang-ja', '高いですね。', 'たかい です ね。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ne-2', 'lang-ja', '綺麗ですね。', 'きれい です ね。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ne-3', 'lang-ja', '寒いですね。', 'さむい です ね。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ne-4', 'lang-ja', '面白いですね。', 'おもしろい です ね。', 'lvl-ja-n5', 'authored', true),
  -- yo-particle
  ('sent-ex-yo-1', 'lang-ja', '安いですよ。', 'やすい です よ。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-yo-2', 'lang-ja', '面白いですよ。', 'おもしろい です よ。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-yo-3', 'lang-ja', '行きますよ。', 'いきます よ。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-yo-4', 'lang-ja', '好きですよ。', 'すき です よ。', 'lvl-ja-n5', 'authored', true),
  -- no-explanatory
  ('sent-ex-noexp-1', 'lang-ja', '忙しいのです。', 'いそがしい のです。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-noexp-2', 'lang-ja', '行くのです。', 'いく のです。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-noexp-3', 'lang-ja', '好きなのです。', 'すき な のです。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-noexp-4', 'lang-ja', '帰るのです。', 'かえる のです。', 'lvl-ja-n5', 'authored', true),
  -- made-time
  ('sent-ex-madetime-1', 'lang-ja', '夜まで働きます。', 'よる まで はたらきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madetime-2', 'lang-ja', '朝まで寝ます。', 'あさ まで ねます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madetime-3', 'lang-ja', '明日まで休みます。', 'あした まで やすみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madetime-4', 'lang-ja', '金曜日まで忙しいです。', 'きんようび まで いそがしい です。', 'lvl-ja-n5', 'authored', true),
  -- kara-from
  ('sent-ex-karafrom-1', 'lang-ja', '朝から働きます。', 'あさ から はたらきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-karafrom-2', 'lang-ja', '日本から来ました。', 'にほん から きました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-karafrom-3', 'lang-ja', '学校から帰ります。', 'がっこう から かえります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-karafrom-4', 'lang-ja', '明日から休みます。', 'あした から やすみます。', 'lvl-ja-n5', 'authored', true),
  -- nado
  ('sent-ex-nado-1', 'lang-ja', '魚などを食べます。', 'さかな など お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nado-2', 'lang-ja', '本や新聞などを読みます。', 'ほん や しんぶん など お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nado-3', 'lang-ja', '肉などを買います。', 'にく など お かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nado-4', 'lang-ja', '海や山などが好きです。', 'うみ や やま など が すき です。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-deshita-1', 'sent-ex-deshita-1', 'en', 'Yesterday was Wednesday.', 'authored'),
  ('st-ex-deshita-2', 'sent-ex-deshita-2', 'en', 'My mother was a teacher.', 'authored'),
  ('st-ex-deshita-3', 'sent-ex-deshita-3', 'en', 'Yesterday was a day off.', 'authored'),
  ('st-ex-deshita-4', 'sent-ex-deshita-4', 'en', 'They were my shoes.', 'authored'),
  ('st-ex-jaarimasen-1', 'sent-ex-jaarimasen-1', 'en', 'I am not a student.', 'authored'),
  ('st-ex-jaarimasen-2', 'sent-ex-jaarimasen-2', 'en', 'It is not my book.', 'authored'),
  ('st-ex-jaarimasen-3', 'sent-ex-jaarimasen-3', 'en', 'She is not a teacher.', 'authored'),
  ('st-ex-jaarimasen-4', 'sent-ex-jaarimasen-4', 'en', 'It is not a cat.', 'authored'),
  ('st-ex-naadjpast-1', 'sent-ex-naadjpast-1', 'en', 'It was quiet.', 'authored'),
  ('st-ex-naadjpast-2', 'sent-ex-naadjpast-2', 'en', 'I was well.', 'authored'),
  ('st-ex-naadjpast-3', 'sent-ex-naadjpast-3', 'en', 'It was beautiful.', 'authored'),
  ('st-ex-naadjpast-4', 'sent-ex-naadjpast-4', 'en', 'It was convenient.', 'authored'),
  ('st-ex-adverb-1', 'sent-ex-adverb-1', 'en', 'I get up early.', 'authored'),
  ('st-ex-adverb-2', 'sent-ex-adverb-2', 'en', 'I speak quietly.', 'authored'),
  ('st-ex-adverb-3', 'sent-ex-adverb-3', 'en', 'I bought it cheaply.', 'authored'),
  ('st-ex-adverb-4', 'sent-ex-adverb-4', 'en', 'I wash it clean.', 'authored'),
  ('st-ex-ne-1', 'sent-ex-ne-1', 'en', 'It is expensive, isn’t it?', 'authored'),
  ('st-ex-ne-2', 'sent-ex-ne-2', 'en', 'It is beautiful, isn’t it?', 'authored'),
  ('st-ex-ne-3', 'sent-ex-ne-3', 'en', 'It is cold, isn’t it?', 'authored'),
  ('st-ex-ne-4', 'sent-ex-ne-4', 'en', 'It is interesting, isn’t it?', 'authored'),
  ('st-ex-yo-1', 'sent-ex-yo-1', 'en', 'It is cheap, you know.', 'authored'),
  ('st-ex-yo-2', 'sent-ex-yo-2', 'en', 'It is interesting, you know.', 'authored'),
  ('st-ex-yo-3', 'sent-ex-yo-3', 'en', 'I am going, you know.', 'authored'),
  ('st-ex-yo-4', 'sent-ex-yo-4', 'en', 'I like it, you know.', 'authored'),
  ('st-ex-noexp-1', 'sent-ex-noexp-1', 'en', 'The thing is, I am busy.', 'authored'),
  ('st-ex-noexp-2', 'sent-ex-noexp-2', 'en', 'The thing is, I am going.', 'authored'),
  ('st-ex-noexp-3', 'sent-ex-noexp-3', 'en', 'The thing is, I like it.', 'authored'),
  ('st-ex-noexp-4', 'sent-ex-noexp-4', 'en', 'The thing is, I am going home.', 'authored'),
  ('st-ex-madetime-1', 'sent-ex-madetime-1', 'en', 'I work until night.', 'authored'),
  ('st-ex-madetime-2', 'sent-ex-madetime-2', 'en', 'I sleep until morning.', 'authored'),
  ('st-ex-madetime-3', 'sent-ex-madetime-3', 'en', 'I am off until tomorrow.', 'authored'),
  ('st-ex-madetime-4', 'sent-ex-madetime-4', 'en', 'I am busy until Friday.', 'authored'),
  ('st-ex-karafrom-1', 'sent-ex-karafrom-1', 'en', 'I work from the morning.', 'authored'),
  ('st-ex-karafrom-2', 'sent-ex-karafrom-2', 'en', 'I came from Japan.', 'authored'),
  ('st-ex-karafrom-3', 'sent-ex-karafrom-3', 'en', 'I come home from school.', 'authored'),
  ('st-ex-karafrom-4', 'sent-ex-karafrom-4', 'en', 'I am off from tomorrow.', 'authored'),
  ('st-ex-nado-1', 'sent-ex-nado-1', 'en', 'I eat fish and so on.', 'authored'),
  ('st-ex-nado-2', 'sent-ex-nado-2', 'en', 'I read books, newspapers and so on.', 'authored'),
  ('st-ex-nado-3', 'sent-ex-nado-3', 'en', 'I buy meat and so on.', 'authored'),
  ('st-ex-nado-4', 'sent-ex-nado-4', 'en', 'I like the sea, mountains and so on.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('deshita', 'sent-ex-deshita-1', 0),
  ('deshita', 'sent-ex-deshita-2', 1),
  ('deshita', 'sent-ex-deshita-3', 2),
  ('deshita', 'sent-ex-deshita-4', 3),
  ('ja-arimasen', 'sent-ex-jaarimasen-1', 0),
  ('ja-arimasen', 'sent-ex-jaarimasen-2', 1),
  ('ja-arimasen', 'sent-ex-jaarimasen-3', 2),
  ('ja-arimasen', 'sent-ex-jaarimasen-4', 3),
  ('na-adj-past', 'sent-ex-naadjpast-1', 0),
  ('na-adj-past', 'sent-ex-naadjpast-2', 1),
  ('na-adj-past', 'sent-ex-naadjpast-3', 2),
  ('na-adj-past', 'sent-ex-naadjpast-4', 3),
  ('adverb-ku', 'sent-ex-adverb-1', 0),
  ('adverb-ku', 'sent-ex-adverb-2', 1),
  ('adverb-ku', 'sent-ex-adverb-3', 2),
  ('adverb-ku', 'sent-ex-adverb-4', 3),
  ('ne-particle', 'sent-ex-ne-1', 0),
  ('ne-particle', 'sent-ex-ne-2', 1),
  ('ne-particle', 'sent-ex-ne-3', 2),
  ('ne-particle', 'sent-ex-ne-4', 3),
  ('yo-particle', 'sent-ex-yo-1', 0),
  ('yo-particle', 'sent-ex-yo-2', 1),
  ('yo-particle', 'sent-ex-yo-3', 2),
  ('yo-particle', 'sent-ex-yo-4', 3),
  ('no-explanatory', 'sent-ex-noexp-1', 0),
  ('no-explanatory', 'sent-ex-noexp-2', 1),
  ('no-explanatory', 'sent-ex-noexp-3', 2),
  ('no-explanatory', 'sent-ex-noexp-4', 3),
  ('made-time', 'sent-ex-madetime-1', 0),
  ('made-time', 'sent-ex-madetime-2', 1),
  ('made-time', 'sent-ex-madetime-3', 2),
  ('made-time', 'sent-ex-madetime-4', 3),
  ('kara-from', 'sent-ex-karafrom-1', 0),
  ('kara-from', 'sent-ex-karafrom-2', 1),
  ('kara-from', 'sent-ex-karafrom-3', 2),
  ('kara-from', 'sent-ex-karafrom-4', 3),
  ('nado', 'sent-ex-nado-1', 0),
  ('nado', 'sent-ex-nado-2', 1),
  ('nado', 'sent-ex-nado-3', 2),
  ('nado', 'sent-ex-nado-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-deshita-1', 'sent-ex-deshita-2', 'sent-ex-deshita-3', 'sent-ex-deshita-4', 'sent-ex-jaarimasen-1', 'sent-ex-jaarimasen-2', 'sent-ex-jaarimasen-3', 'sent-ex-jaarimasen-4', 'sent-ex-naadjpast-1', 'sent-ex-naadjpast-2', 'sent-ex-naadjpast-3', 'sent-ex-naadjpast-4', 'sent-ex-adverb-1', 'sent-ex-adverb-2', 'sent-ex-adverb-3', 'sent-ex-adverb-4', 'sent-ex-ne-1', 'sent-ex-ne-2', 'sent-ex-ne-3', 'sent-ex-ne-4', 'sent-ex-yo-1', 'sent-ex-yo-2', 'sent-ex-yo-3', 'sent-ex-yo-4', 'sent-ex-noexp-1', 'sent-ex-noexp-2', 'sent-ex-noexp-3', 'sent-ex-noexp-4', 'sent-ex-madetime-1', 'sent-ex-madetime-2', 'sent-ex-madetime-3', 'sent-ex-madetime-4', 'sent-ex-karafrom-1', 'sent-ex-karafrom-2', 'sent-ex-karafrom-3', 'sent-ex-karafrom-4', 'sent-ex-nado-1', 'sent-ex-nado-2', 'sent-ex-nado-3', 'sent-ex-nado-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-deshita-1', 0, '昨日', 'きのう', '89b5855e-63be-4984-8c64-31de7d611fca', 0, 2, '[{"t":"昨日","r":"きのう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-1', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-1', 2, '水曜日', 'すいようび', '18ad1c7f-834e-4d3c-aba0-d9922addfb44', 3, 6, '[{"t":"水曜日","r":"すいようび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-1', 3, 'でした', 'でした', NULL, 6, 9, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-2', 0, '母', 'はは', '85939c87-5d17-44b2-affc-26fb46091623', 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-2', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-2', 2, '先生', 'せんせい', 'f2bd1cf4-e22c-48f8-a563-771e2f0599a9', 2, 4, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-2', 3, 'でした', 'でした', NULL, 4, 7, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-3', 0, '昨日', 'きのう', '89b5855e-63be-4984-8c64-31de7d611fca', 0, 2, '[{"t":"昨日","r":"きのう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-3', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-3', 2, '休み', 'やすみ', '3bce69b7-ff4b-452d-b9f8-062f16ae674b', 3, 5, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-3', 3, 'でした', 'でした', NULL, 5, 8, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-4', 0, '私', 'わたし', '07d07dec-dc8f-45b2-8095-b49b5087da75', 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-4', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-4', 2, '靴', 'くつ', 'da19bf49-6698-4142-bf0f-90077a00f120', 2, 3, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-4', 3, 'でした', 'でした', NULL, 3, 6, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deshita-4', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-1', 0, '学生', 'がくせい', '15fb2da0-1205-42cf-8c9c-59295ac9fb62', 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-1', 1, 'じゃありません', 'じゃありません', NULL, 2, 9, '[{"t":"じゃありません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-1', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-2', 0, '私', 'わたし', '07d07dec-dc8f-45b2-8095-b49b5087da75', 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-2', 2, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-2', 3, 'じゃありません', 'じゃありません', NULL, 3, 10, '[{"t":"じゃありません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-2', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-3', 0, '先生', 'せんせい', 'f2bd1cf4-e22c-48f8-a563-771e2f0599a9', 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-3', 1, 'じゃありません', 'じゃありません', NULL, 2, 9, '[{"t":"じゃありません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-3', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-4', 0, '猫', 'ねこ', 'c6ec2551-173f-464c-94d0-4098e1165c3e', 0, 1, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-4', 1, 'じゃありません', 'じゃありません', NULL, 1, 8, '[{"t":"じゃありません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jaarimasen-4', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-1', 0, '静か', 'しずか', '845a308a-e796-4400-a1df-b4e8ffa7d896', 0, 2, '[{"t":"静","r":"しず"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-1', 1, 'でした', 'でした', NULL, 2, 5, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-1', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-2', 0, '元気', 'げんき', '9c71f674-2595-41b1-abe5-1d9092a705e8', 0, 2, '[{"t":"元気","r":"げんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-2', 1, 'でした', 'でした', NULL, 2, 5, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-2', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-3', 0, '綺麗', 'きれい', '47370d32-ec9b-41e7-a8cc-a58a93ff9014', 0, 2, '[{"t":"綺麗","r":"きれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-3', 1, 'でした', 'でした', NULL, 2, 5, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-3', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-4', 0, '便利', 'べんり', '2f71e5ff-171c-4cbb-82e3-b4323123a703', 0, 2, '[{"t":"便利","r":"べんり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-4', 1, 'でした', 'でした', NULL, 2, 5, '[{"t":"でした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naadjpast-4', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-1', 0, '早く', 'はやく', '416d3a31-5940-475c-8c7f-d7997aff8665', 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-1', 1, '起きます', 'おきます', '5fb365d9-60b4-4d75-a1c7-5170ce4bbcf5', 2, 6, '[{"t":"起","r":"お"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-1', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-2', 0, '静か', 'しずか', '845a308a-e796-4400-a1df-b4e8ffa7d896', 0, 2, '[{"t":"静","r":"しず"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-2', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-2', 2, '話します', 'はなします', 'e6ac7966-a5f8-484c-bc4a-28d4b3592d54', 3, 7, '[{"t":"話","r":"はな"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-2', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-3', 0, '安く', 'やすく', 'c1f2deec-8ed2-4b54-b23c-5ae7d8524e07', 0, 2, '[{"t":"安","r":"やす"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-3', 1, '買いました', 'かいました', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 2, 7, '[{"t":"買","r":"か"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-3', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-4', 0, '綺麗', 'きれい', '47370d32-ec9b-41e7-a8cc-a58a93ff9014', 0, 2, '[{"t":"綺麗","r":"きれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-4', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-4', 2, '洗います', 'あらいます', '2bbb8c32-86e8-4c45-a12b-1174a8f4d189', 3, 7, '[{"t":"洗","r":"あら"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-adverb-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-1', 0, '高い', 'たかい', 'b9f375ce-c7e3-4b81-bfed-58fb9057bc8a', 0, 2, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-1', 1, 'です', 'です', NULL, 2, 4, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-1', 2, 'ね', 'ね', '8837b28e-0594-4f00-96ff-bba4722acb9f', 4, 5, '[{"t":"ね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-1', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-2', 0, '綺麗', 'きれい', '47370d32-ec9b-41e7-a8cc-a58a93ff9014', 0, 2, '[{"t":"綺麗","r":"きれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-2', 1, 'です', 'です', NULL, 2, 4, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-2', 2, 'ね', 'ね', '8837b28e-0594-4f00-96ff-bba4722acb9f', 4, 5, '[{"t":"ね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-2', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-3', 0, '寒い', 'さむい', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 0, 2, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-3', 1, 'です', 'です', NULL, 2, 4, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-3', 2, 'ね', 'ね', '8837b28e-0594-4f00-96ff-bba4722acb9f', 4, 5, '[{"t":"ね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-3', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-4', 0, '面白い', 'おもしろい', 'f5d6fc6a-618d-4fbd-8782-19bd4443c7da', 0, 3, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-4', 1, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-4', 2, 'ね', 'ね', '8837b28e-0594-4f00-96ff-bba4722acb9f', 5, 6, '[{"t":"ね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ne-4', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-1', 0, '安い', 'やすい', '817cb322-0f7f-4c83-a195-dde87e4bd13f', 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-1', 1, 'です', 'です', NULL, 2, 4, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-1', 2, 'よ', 'よ', '9b4319d4-69ab-43ab-907f-e27235c546ac', 4, 5, '[{"t":"よ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-1', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-2', 0, '面白い', 'おもしろい', 'f5d6fc6a-618d-4fbd-8782-19bd4443c7da', 0, 3, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-2', 1, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-2', 2, 'よ', 'よ', '9b4319d4-69ab-43ab-907f-e27235c546ac', 5, 6, '[{"t":"よ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-2', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-3', 0, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 0, 4, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-3', 1, 'よ', 'よ', '9b4319d4-69ab-43ab-907f-e27235c546ac', 4, 5, '[{"t":"よ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-3', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-4', 0, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 0, 2, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-4', 1, 'です', 'です', NULL, 2, 4, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-4', 2, 'よ', 'よ', '9b4319d4-69ab-43ab-907f-e27235c546ac', 4, 5, '[{"t":"よ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yo-4', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-1', 0, '忙しい', 'いそがしい', '65ae7422-9448-4faa-b28d-f80a027123bf', 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-1', 1, 'のです', 'のです', NULL, 3, 6, '[{"t":"のです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-1', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-2', 0, '行く', 'いく', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 0, 2, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-2', 1, 'のです', 'のです', NULL, 2, 5, '[{"t":"のです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-2', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-3', 0, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 0, 2, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-3', 1, 'な', 'な', '6ac13c77-d34b-48a1-88aa-a6f30ec5c45e', 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-3', 2, 'のです', 'のです', NULL, 3, 6, '[{"t":"のです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-3', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-4', 0, '帰る', 'かえる', '0e66e781-bb50-49e8-a7da-ea0a8bb6cbe0', 0, 2, '[{"t":"帰","r":"かえ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-4', 1, 'のです', 'のです', NULL, 2, 5, '[{"t":"のです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noexp-4', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-1', 0, '夜', 'よる', 'a6a8d533-c3bd-477c-b00b-67509d45a9d8', 0, 1, '[{"t":"夜","r":"よる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-1', 1, 'まで', 'まで', NULL, 1, 3, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-1', 2, '働きます', 'はたらきます', '75abeac3-31b6-44dd-8434-96e88d07f940', 3, 7, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-2', 0, '朝', 'あさ', 'd69bdfb8-8f9e-40d7-800c-f6361221d7b2', 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-2', 1, 'まで', 'まで', NULL, 1, 3, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-2', 2, '寝ます', 'ねます', '056f037c-201a-4cd0-85be-f063237124fd', 3, 6, '[{"t":"寝","r":"ね"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-2', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-3', 0, '明日', 'あした', '823cfb1a-cb34-4c88-86d6-5cdfca69eed5', 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-3', 1, 'まで', 'まで', NULL, 2, 4, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-3', 2, '休みます', 'やすみます', '52fd60de-a97d-47be-9b31-894be752027a', 4, 8, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-4', 0, '金曜日', 'きんようび', '9b51c2f1-0af2-4fba-a9a4-dd57b8665b80', 0, 3, '[{"t":"金曜日","r":"きんようび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-4', 1, 'まで', 'まで', NULL, 3, 5, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-4', 2, '忙しい', 'いそがしい', '65ae7422-9448-4faa-b28d-f80a027123bf', 5, 8, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-4', 3, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madetime-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-1', 0, '朝', 'あさ', 'd69bdfb8-8f9e-40d7-800c-f6361221d7b2', 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-1', 1, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-1', 2, '働きます', 'はたらきます', '75abeac3-31b6-44dd-8434-96e88d07f940', 3, 7, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-2', 0, '日本', 'にほん', '9de924d0-d7d7-4284-bbae-c05ecbef3e5e', 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-2', 1, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-2', 2, '来ました', 'きました', 'e40f6686-fee0-4bc0-820d-ba5c272193a8', 4, 8, '[{"t":"来","r":"き"},{"t":"ました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-3', 0, '学校', 'がっこう', 'c6989610-93a3-4175-8b9c-d969d934a05a', 0, 2, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-3', 1, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-3', 2, '帰ります', 'かえります', '0e66e781-bb50-49e8-a7da-ea0a8bb6cbe0', 4, 8, '[{"t":"帰","r":"かえ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-4', 0, '明日', 'あした', '823cfb1a-cb34-4c88-86d6-5cdfca69eed5', 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-4', 1, 'から', 'から', '22b44903-fdbc-4403-b597-a713aae7507f', 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-4', 2, '休みます', 'やすみます', '52fd60de-a97d-47be-9b31-894be752027a', 4, 8, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karafrom-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-1', 0, '魚', 'さかな', 'e1e048a7-24b7-4875-8727-b61a2e2c4857', 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-1', 1, 'など', 'など', NULL, 1, 3, '[{"t":"など"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-1', 2, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-1', 3, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 4, 8, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-1', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-2', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-2', 1, 'や', 'や', '824441f4-6411-4a54-9d05-67890b8e5a0c', 1, 2, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-2', 2, '新聞', 'しんぶん', '66072ae2-f8fc-4367-a221-cb59f3ec454a', 2, 4, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-2', 3, 'など', 'など', NULL, 4, 6, '[{"t":"など"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-2', 4, 'を', 'を', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-2', 5, '読みます', 'よみます', '1c659ec9-be5a-4805-ab6c-51ceda5763fb', 7, 11, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-3', 0, '肉', 'にく', '5df9f1a7-e606-44b7-b5a7-484d84d86549', 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-3', 1, 'など', 'など', NULL, 1, 3, '[{"t":"など"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-3', 2, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-3', 3, '買います', 'かいます', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 0, '海', 'うみ', 'e3cb86b5-f5fc-4cf7-81de-c038f64be645', 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 1, 'や', 'や', '824441f4-6411-4a54-9d05-67890b8e5a0c', 1, 2, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 2, '山', 'やま', '37b55423-0c09-495a-87e9-1ca7d4bbbeed', 2, 3, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 3, 'など', 'など', NULL, 3, 5, '[{"t":"など"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 4, 'が', 'が', NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 5, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 6, 8, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 6, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nado-4', 7, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb);
