-- N5 example sentences, batch 7: ぐらい, とか, question words, どうして, とても,
-- ぜんぜん, まだ／もう, 〜が欲しい, 〜てはいけません and に (existence).
--
-- Forty sentences, no rewrites needed.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- gurai
  ('sent-ex-gurai-1', 'lang-ja', '一時間ぐらい歩きます。', 'いちじかん ぐらい あるきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gurai-2', 'lang-ja', '少しぐらい休みます。', 'すこし ぐらい やすみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gurai-3', 'lang-ja', '一時間ぐらい勉強します。', 'いちじかん ぐらい べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gurai-4', 'lang-ja', '一時間ぐらい待ちます。', 'いちじかん ぐらい まちます。', 'lvl-ja-n5', 'authored', true),
  -- toka
  ('sent-ex-toka-1', 'lang-ja', '魚とか肉を食べます。', 'さかな とか にく お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-toka-2', 'lang-ja', '本とか新聞を読みます。', 'ほん とか しんぶん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-toka-3', 'lang-ja', '海とか山が好きです。', 'うみ とか やま が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-toka-4', 'lang-ja', '靴とか服を買います。', 'くつ とか ふく お かいます。', 'lvl-ja-n5', 'authored', true),
  -- question-words
  ('sent-ex-qword-1', 'lang-ja', '何を食べますか。', 'なに お たべます か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-qword-2', 'lang-ja', 'どこへ行きますか。', 'どこ え いきます か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-qword-3', 'lang-ja', 'いつ来ますか。', 'いつ きます か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-qword-4', 'lang-ja', '誰が来ますか。', 'だれ が きます か。', 'lvl-ja-n5', 'authored', true),
  -- doushite
  ('sent-ex-doushite-1', 'lang-ja', 'どうして行きませんか。', 'どうして いきません か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-doushite-2', 'lang-ja', 'どうして休みますか。', 'どうして やすみます か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-doushite-3', 'lang-ja', 'どうして高いですか。', 'どうして たかい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-doushite-4', 'lang-ja', 'どうして来ませんか。', 'どうして きません か。', 'lvl-ja-n5', 'authored', true),
  -- totemo
  ('sent-ex-totemo-1', 'lang-ja', 'とても寒いです。', 'とても さむい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-totemo-2', 'lang-ja', 'とても高いです。', 'とても たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-totemo-3', 'lang-ja', 'とても面白いです。', 'とても おもしろい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-totemo-4', 'lang-ja', 'とても綺麗です。', 'とても きれい です。', 'lvl-ja-n5', 'authored', true),
  -- zenzen
  ('sent-ex-zenzen-1', 'lang-ja', 'ぜんぜん分かりません。', 'ぜんぜん わかりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-zenzen-2', 'lang-ja', 'ぜんぜん食べません。', 'ぜんぜん たべません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-zenzen-3', 'lang-ja', 'ぜんぜん寒くないです。', 'ぜんぜん さむく ない です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-zenzen-4', 'lang-ja', 'ぜんぜん飲みません。', 'ぜんぜん のみません。', 'lvl-ja-n5', 'authored', true),
  -- mada-mou
  ('sent-ex-madamou-1', 'lang-ja', 'もう食べました。', 'もう たべました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madamou-2', 'lang-ja', 'まだ食べません。', 'まだ たべません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madamou-3', 'lang-ja', 'もう帰りました。', 'もう かえりました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madamou-4', 'lang-ja', 'まだ寝ません。', 'まだ ねません。', 'lvl-ja-n5', 'authored', true),
  -- hoshii
  ('sent-ex-hoshii-1', 'lang-ja', '車が欲しいです。', 'くるま が ほしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-hoshii-2', 'lang-ja', '本が欲しいです。', 'ほん が ほしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-hoshii-3', 'lang-ja', '靴が欲しいです。', 'くつ が ほしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-hoshii-4', 'lang-ja', '時計が欲しいです。', 'とけい が ほしい です。', 'lvl-ja-n5', 'authored', true),
  -- te-wa-ikemasen
  ('sent-ex-tewaikemasen-1', 'lang-ja', '走ってはいけません。', 'はしって わ いけません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tewaikemasen-2', 'lang-ja', '飲んではいけません。', 'のんで わ いけません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tewaikemasen-3', 'lang-ja', '見てはいけません。', 'みて わ いけません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tewaikemasen-4', 'lang-ja', '入ってはいけません。', 'はいって わ いけません。', 'lvl-ja-n5', 'authored', true),
  -- ni-existence
  ('sent-ex-niexist-1', 'lang-ja', '部屋に猫がいます。', 'へや に ねこ が います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-niexist-2', 'lang-ja', '店に人がいます。', 'みせ に ひと が います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-niexist-3', 'lang-ja', '机に本があります。', 'つくえ に ほん が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-niexist-4', 'lang-ja', '部屋に窓があります。', 'へや に まど が あります。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-gurai-1', 'sent-ex-gurai-1', 'en', 'I walk for about an hour.', 'authored'),
  ('st-ex-gurai-2', 'sent-ex-gurai-2', 'en', 'I rest for a little while.', 'authored'),
  ('st-ex-gurai-3', 'sent-ex-gurai-3', 'en', 'I study for about an hour.', 'authored'),
  ('st-ex-gurai-4', 'sent-ex-gurai-4', 'en', 'I wait for about an hour.', 'authored'),
  ('st-ex-toka-1', 'sent-ex-toka-1', 'en', 'I eat things like fish and meat.', 'authored'),
  ('st-ex-toka-2', 'sent-ex-toka-2', 'en', 'I read things like books and newspapers.', 'authored'),
  ('st-ex-toka-3', 'sent-ex-toka-3', 'en', 'I like places like the sea and the mountains.', 'authored'),
  ('st-ex-toka-4', 'sent-ex-toka-4', 'en', 'I buy things like shoes and clothes.', 'authored'),
  ('st-ex-qword-1', 'sent-ex-qword-1', 'en', 'What will you eat?', 'authored'),
  ('st-ex-qword-2', 'sent-ex-qword-2', 'en', 'Where are you going?', 'authored'),
  ('st-ex-qword-3', 'sent-ex-qword-3', 'en', 'When are you coming?', 'authored'),
  ('st-ex-qword-4', 'sent-ex-qword-4', 'en', 'Who is coming?', 'authored'),
  ('st-ex-doushite-1', 'sent-ex-doushite-1', 'en', 'Why are you not going?', 'authored'),
  ('st-ex-doushite-2', 'sent-ex-doushite-2', 'en', 'Why are you taking time off?', 'authored'),
  ('st-ex-doushite-3', 'sent-ex-doushite-3', 'en', 'Why is it expensive?', 'authored'),
  ('st-ex-doushite-4', 'sent-ex-doushite-4', 'en', 'Why are you not coming?', 'authored'),
  ('st-ex-totemo-1', 'sent-ex-totemo-1', 'en', 'It is very cold.', 'authored'),
  ('st-ex-totemo-2', 'sent-ex-totemo-2', 'en', 'It is very expensive.', 'authored'),
  ('st-ex-totemo-3', 'sent-ex-totemo-3', 'en', 'It is very interesting.', 'authored'),
  ('st-ex-totemo-4', 'sent-ex-totemo-4', 'en', 'It is very beautiful.', 'authored'),
  ('st-ex-zenzen-1', 'sent-ex-zenzen-1', 'en', 'I do not understand at all.', 'authored'),
  ('st-ex-zenzen-2', 'sent-ex-zenzen-2', 'en', 'I do not eat it at all.', 'authored'),
  ('st-ex-zenzen-3', 'sent-ex-zenzen-3', 'en', 'It is not cold at all.', 'authored'),
  ('st-ex-zenzen-4', 'sent-ex-zenzen-4', 'en', 'I do not drink at all.', 'authored'),
  ('st-ex-madamou-1', 'sent-ex-madamou-1', 'en', 'I have already eaten.', 'authored'),
  ('st-ex-madamou-2', 'sent-ex-madamou-2', 'en', 'I am not eating yet.', 'authored'),
  ('st-ex-madamou-3', 'sent-ex-madamou-3', 'en', 'He has already gone home.', 'authored'),
  ('st-ex-madamou-4', 'sent-ex-madamou-4', 'en', 'I am not going to bed yet.', 'authored'),
  ('st-ex-hoshii-1', 'sent-ex-hoshii-1', 'en', 'I want a car.', 'authored'),
  ('st-ex-hoshii-2', 'sent-ex-hoshii-2', 'en', 'I want a book.', 'authored'),
  ('st-ex-hoshii-3', 'sent-ex-hoshii-3', 'en', 'I want shoes.', 'authored'),
  ('st-ex-hoshii-4', 'sent-ex-hoshii-4', 'en', 'I want a watch.', 'authored'),
  ('st-ex-tewaikemasen-1', 'sent-ex-tewaikemasen-1', 'en', 'You must not run.', 'authored'),
  ('st-ex-tewaikemasen-2', 'sent-ex-tewaikemasen-2', 'en', 'You must not drink it.', 'authored'),
  ('st-ex-tewaikemasen-3', 'sent-ex-tewaikemasen-3', 'en', 'You must not look.', 'authored'),
  ('st-ex-tewaikemasen-4', 'sent-ex-tewaikemasen-4', 'en', 'You must not enter.', 'authored'),
  ('st-ex-niexist-1', 'sent-ex-niexist-1', 'en', 'There is a cat in the room.', 'authored'),
  ('st-ex-niexist-2', 'sent-ex-niexist-2', 'en', 'There is someone in the shop.', 'authored'),
  ('st-ex-niexist-3', 'sent-ex-niexist-3', 'en', 'There is a book on the desk.', 'authored'),
  ('st-ex-niexist-4', 'sent-ex-niexist-4', 'en', 'There is a window in the room.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('gurai', 'sent-ex-gurai-1', 0),
  ('gurai', 'sent-ex-gurai-2', 1),
  ('gurai', 'sent-ex-gurai-3', 2),
  ('gurai', 'sent-ex-gurai-4', 3),
  ('toka', 'sent-ex-toka-1', 0),
  ('toka', 'sent-ex-toka-2', 1),
  ('toka', 'sent-ex-toka-3', 2),
  ('toka', 'sent-ex-toka-4', 3),
  ('question-words', 'sent-ex-qword-1', 0),
  ('question-words', 'sent-ex-qword-2', 1),
  ('question-words', 'sent-ex-qword-3', 2),
  ('question-words', 'sent-ex-qword-4', 3),
  ('doushite', 'sent-ex-doushite-1', 0),
  ('doushite', 'sent-ex-doushite-2', 1),
  ('doushite', 'sent-ex-doushite-3', 2),
  ('doushite', 'sent-ex-doushite-4', 3),
  ('totemo', 'sent-ex-totemo-1', 0),
  ('totemo', 'sent-ex-totemo-2', 1),
  ('totemo', 'sent-ex-totemo-3', 2),
  ('totemo', 'sent-ex-totemo-4', 3),
  ('zenzen', 'sent-ex-zenzen-1', 0),
  ('zenzen', 'sent-ex-zenzen-2', 1),
  ('zenzen', 'sent-ex-zenzen-3', 2),
  ('zenzen', 'sent-ex-zenzen-4', 3),
  ('mada-mou', 'sent-ex-madamou-1', 0),
  ('mada-mou', 'sent-ex-madamou-2', 1),
  ('mada-mou', 'sent-ex-madamou-3', 2),
  ('mada-mou', 'sent-ex-madamou-4', 3),
  ('hoshii', 'sent-ex-hoshii-1', 0),
  ('hoshii', 'sent-ex-hoshii-2', 1),
  ('hoshii', 'sent-ex-hoshii-3', 2),
  ('hoshii', 'sent-ex-hoshii-4', 3),
  ('te-wa-ikemasen', 'sent-ex-tewaikemasen-1', 0),
  ('te-wa-ikemasen', 'sent-ex-tewaikemasen-2', 1),
  ('te-wa-ikemasen', 'sent-ex-tewaikemasen-3', 2),
  ('te-wa-ikemasen', 'sent-ex-tewaikemasen-4', 3),
  ('ni-existence', 'sent-ex-niexist-1', 0),
  ('ni-existence', 'sent-ex-niexist-2', 1),
  ('ni-existence', 'sent-ex-niexist-3', 2),
  ('ni-existence', 'sent-ex-niexist-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-gurai-1', 'sent-ex-gurai-2', 'sent-ex-gurai-3', 'sent-ex-gurai-4', 'sent-ex-toka-1', 'sent-ex-toka-2', 'sent-ex-toka-3', 'sent-ex-toka-4', 'sent-ex-qword-1', 'sent-ex-qword-2', 'sent-ex-qword-3', 'sent-ex-qword-4', 'sent-ex-doushite-1', 'sent-ex-doushite-2', 'sent-ex-doushite-3', 'sent-ex-doushite-4', 'sent-ex-totemo-1', 'sent-ex-totemo-2', 'sent-ex-totemo-3', 'sent-ex-totemo-4', 'sent-ex-zenzen-1', 'sent-ex-zenzen-2', 'sent-ex-zenzen-3', 'sent-ex-zenzen-4', 'sent-ex-madamou-1', 'sent-ex-madamou-2', 'sent-ex-madamou-3', 'sent-ex-madamou-4', 'sent-ex-hoshii-1', 'sent-ex-hoshii-2', 'sent-ex-hoshii-3', 'sent-ex-hoshii-4', 'sent-ex-tewaikemasen-1', 'sent-ex-tewaikemasen-2', 'sent-ex-tewaikemasen-3', 'sent-ex-tewaikemasen-4', 'sent-ex-niexist-1', 'sent-ex-niexist-2', 'sent-ex-niexist-3', 'sent-ex-niexist-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-gurai-1', 0, '一時', 'いちじ', '1be5025c-2f9d-4a1f-88e3-fbbcd9245e52', 0, 2, '[{"t":"一時","r":"いちじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-1', 1, '間', 'あいだ', 'ddeac12f-874b-447b-b995-454caf669c74', 2, 3, '[{"t":"間","r":"あいだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-1', 2, 'ぐらい', 'ぐらい', NULL, 3, 6, '[{"t":"ぐらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-1', 3, '歩きます', 'あるきます', '0b7f8e92-250b-4efd-9746-a8b08960d587', 6, 10, '[{"t":"歩","r":"ある"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-1', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-2', 0, '少し', 'すこし', 'c3fea249-9141-44a5-a822-a2bbe599d73d', 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-2', 1, 'ぐらい', 'ぐらい', NULL, 2, 5, '[{"t":"ぐらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-2', 2, '休みます', 'やすみます', '52fd60de-a97d-47be-9b31-894be752027a', 5, 9, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-3', 0, '一時', 'いちじ', '1be5025c-2f9d-4a1f-88e3-fbbcd9245e52', 0, 2, '[{"t":"一時","r":"いちじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-3', 1, '間', 'あいだ', 'ddeac12f-874b-447b-b995-454caf669c74', 2, 3, '[{"t":"間","r":"あいだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-3', 2, 'ぐらい', 'ぐらい', NULL, 3, 6, '[{"t":"ぐらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-3', 3, '勉強します', 'べんきょうします', 'b5a69b9b-5017-4a76-b301-dbd5c9f5ba2a', 6, 11, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-3', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-4', 0, '一時', 'いちじ', '1be5025c-2f9d-4a1f-88e3-fbbcd9245e52', 0, 2, '[{"t":"一時","r":"いちじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-4', 1, '間', 'あいだ', 'ddeac12f-874b-447b-b995-454caf669c74', 2, 3, '[{"t":"間","r":"あいだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-4', 2, 'ぐらい', 'ぐらい', NULL, 3, 6, '[{"t":"ぐらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-4', 3, '待ちます', 'まちます', '9e737ca0-2423-4337-859c-402dded4a3a7', 6, 10, '[{"t":"待","r":"ま"},{"t":"ちます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gurai-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-1', 0, '魚', 'さかな', 'e1e048a7-24b7-4875-8727-b61a2e2c4857', 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-1', 1, 'とか', 'とか', NULL, 1, 3, '[{"t":"とか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-1', 2, '肉', 'にく', '5df9f1a7-e606-44b7-b5a7-484d84d86549', 3, 4, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-1', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-1', 4, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 5, 9, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-2', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-2', 1, 'とか', 'とか', NULL, 1, 3, '[{"t":"とか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-2', 2, '新聞', 'しんぶん', '66072ae2-f8fc-4367-a221-cb59f3ec454a', 3, 5, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-2', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-2', 4, '読みます', 'よみます', '1c659ec9-be5a-4805-ab6c-51ceda5763fb', 6, 10, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-2', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-3', 0, '海', 'うみ', 'e3cb86b5-f5fc-4cf7-81de-c038f64be645', 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-3', 1, 'とか', 'とか', NULL, 1, 3, '[{"t":"とか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-3', 2, '山', 'やま', '37b55423-0c09-495a-87e9-1ca7d4bbbeed', 3, 4, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-3', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-3', 4, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 5, 7, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-3', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-3', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-4', 0, '靴', 'くつ', 'da19bf49-6698-4142-bf0f-90077a00f120', 0, 1, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-4', 1, 'とか', 'とか', NULL, 1, 3, '[{"t":"とか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-4', 2, '服', 'ふく', '3944c908-3f40-475a-a58d-62961b84d8bb', 3, 4, '[{"t":"服","r":"ふく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-4', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-4', 4, '買います', 'かいます', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 5, 9, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toka-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-1', 0, '何', 'なに', '39226ec4-356a-41c4-a270-2d76dda6f89e', 0, 1, '[{"t":"何","r":"なに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-1', 2, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 2, 6, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-1', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-1', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-2', 0, 'どこ', 'どこ', NULL, 0, 2, '[{"t":"どこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-2', 1, 'へ', 'へ', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-2', 2, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-2', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-3', 0, 'いつ', 'いつ', NULL, 0, 2, '[{"t":"いつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-3', 1, '来ます', 'きます', 'e40f6686-fee0-4bc0-820d-ba5c272193a8', 2, 5, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-3', 2, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 5, 6, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-3', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-4', 0, '誰', 'だれ', 'cd4d7e73-b32b-4852-8570-49c4be886e54', 0, 1, '[{"t":"誰","r":"だれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-4', 2, '来ます', 'きます', 'e40f6686-fee0-4bc0-820d-ba5c272193a8', 2, 5, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-4', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 5, 6, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-qword-4', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-1', 0, 'どうして', 'どうして', NULL, 0, 4, '[{"t":"どうして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-1', 1, '行きません', 'いきません', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 4, 9, '[{"t":"行","r":"い"},{"t":"きません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-1', 2, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 9, 10, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-1', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-2', 0, 'どうして', 'どうして', NULL, 0, 4, '[{"t":"どうして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-2', 1, '休みます', 'やすみます', '52fd60de-a97d-47be-9b31-894be752027a', 4, 8, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-2', 2, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-3', 0, 'どうして', 'どうして', NULL, 0, 4, '[{"t":"どうして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-3', 1, '高い', 'たかい', 'b9f375ce-c7e3-4b81-bfed-58fb9057bc8a', 4, 6, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-3', 2, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-3', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-4', 0, 'どうして', 'どうして', NULL, 0, 4, '[{"t":"どうして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-4', 1, '来ません', 'きません', 'e40f6686-fee0-4bc0-820d-ba5c272193a8', 4, 8, '[{"t":"来","r":"き"},{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-4', 2, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-doushite-4', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-1', 0, 'とて', 'とて', NULL, 0, 2, '[{"t":"とて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-1', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-1', 2, '寒い', 'さむい', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 3, 5, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-1', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-1', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-2', 0, 'とて', 'とて', NULL, 0, 2, '[{"t":"とて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-2', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-2', 2, '高い', 'たかい', 'b9f375ce-c7e3-4b81-bfed-58fb9057bc8a', 3, 5, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-2', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-3', 0, 'とて', 'とて', NULL, 0, 2, '[{"t":"とて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-3', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-3', 2, '面白い', 'おもしろい', 'f5d6fc6a-618d-4fbd-8782-19bd4443c7da', 3, 6, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-3', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-4', 0, 'とて', 'とて', NULL, 0, 2, '[{"t":"とて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-4', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-4', 2, '綺麗', 'きれい', '47370d32-ec9b-41e7-a8cc-a58a93ff9014', 3, 5, '[{"t":"綺麗","r":"きれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-4', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totemo-4', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-1', 0, 'ぜんぜん', 'ぜんぜん', NULL, 0, 4, '[{"t":"ぜんぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-1', 1, '分かりません', 'わかりません', '3d9bdd1b-da65-41a9-8893-79f313127e27', 4, 10, '[{"t":"分","r":"わ"},{"t":"かりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-1', 2, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-2', 0, 'ぜんぜん', 'ぜんぜん', NULL, 0, 4, '[{"t":"ぜんぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-2', 1, '食べません', 'たべません', '788557df-2bac-4ae7-a157-8a81fbe1da16', 4, 9, '[{"t":"食","r":"た"},{"t":"べません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-2', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-3', 0, 'ぜんぜん', 'ぜんぜん', NULL, 0, 4, '[{"t":"ぜんぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-3', 1, '寒くないです', 'さむくないです', '7804ecd2-11fd-4390-9b3d-061a74ac662d', 4, 10, '[{"t":"寒","r":"さむ"},{"t":"くないです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-3', 2, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-4', 0, 'ぜんぜん', 'ぜんぜん', NULL, 0, 4, '[{"t":"ぜんぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-4', 1, '飲みません', 'のみません', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 4, 9, '[{"t":"飲","r":"の"},{"t":"みません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zenzen-4', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-1', 0, 'もう', 'もう', '4f205665-62ea-4fe1-acdc-39a4ae8265d6', 0, 2, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-1', 1, '食べました', 'たべました', '788557df-2bac-4ae7-a157-8a81fbe1da16', 2, 7, '[{"t":"食","r":"た"},{"t":"べました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-1', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-2', 0, 'まだ', 'まだ', '13fd9720-3a3b-41cf-84ab-c45a019d6c13', 0, 2, '[{"t":"まだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-2', 1, '食べません', 'たべません', '788557df-2bac-4ae7-a157-8a81fbe1da16', 2, 7, '[{"t":"食","r":"た"},{"t":"べません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-2', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-3', 0, 'もう', 'もう', '4f205665-62ea-4fe1-acdc-39a4ae8265d6', 0, 2, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-3', 1, '帰りました', 'かえりました', '0e66e781-bb50-49e8-a7da-ea0a8bb6cbe0', 2, 7, '[{"t":"帰","r":"かえ"},{"t":"りました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-3', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-4', 0, 'まだ', 'まだ', '13fd9720-3a3b-41cf-84ab-c45a019d6c13', 0, 2, '[{"t":"まだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-4', 1, '寝ません', 'ねません', '056f037c-201a-4cd0-85be-f063237124fd', 2, 6, '[{"t":"寝","r":"ね"},{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madamou-4', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-1', 0, '車', 'くるま', '5dc5735d-214f-4348-b3ee-a0fb3c4bdb9f', 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-1', 2, '欲しい', 'ほしい', 'ace38ac9-8747-495e-bc9d-12b10af1ffd9', 2, 5, '[{"t":"欲","r":"ほ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-1', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-1', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-2', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-2', 2, '欲しい', 'ほしい', 'ace38ac9-8747-495e-bc9d-12b10af1ffd9', 2, 5, '[{"t":"欲","r":"ほ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-2', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-3', 0, '靴', 'くつ', 'da19bf49-6698-4142-bf0f-90077a00f120', 0, 1, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-3', 2, '欲しい', 'ほしい', 'ace38ac9-8747-495e-bc9d-12b10af1ffd9', 2, 5, '[{"t":"欲","r":"ほ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-3', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-3', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-4', 0, '時計', 'とけい', '413a14d5-27ae-4e9a-9087-7e9a8b26f506', 0, 2, '[{"t":"時計","r":"とけい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-4', 2, '欲しい', 'ほしい', 'ace38ac9-8747-495e-bc9d-12b10af1ffd9', 3, 6, '[{"t":"欲","r":"ほ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-4', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hoshii-4', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-1', 0, '走って', 'はしって', '3dadb2da-a7a4-4b04-8142-859eec7a6675', 0, 3, '[{"t":"走","r":"はし"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-1', 1, 'はいけません', 'はいけません', NULL, 3, 9, '[{"t":"はいけません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-1', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-2', 0, '飲んで', 'のんで', '4ed30497-acb5-467e-ba5b-898fbc4c4c7c', 0, 3, '[{"t":"飲","r":"の"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-2', 1, 'はいけません', 'はいけません', NULL, 3, 9, '[{"t":"はいけません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-2', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-3', 0, '見て', 'みて', '85ec6cc4-0dca-4479-abcf-d53e33fc9e49', 0, 2, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-3', 1, 'はいけません', 'はいけません', NULL, 2, 8, '[{"t":"はいけません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-3', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-4', 0, '入って', 'はいって', 'f50ebbe5-7336-454a-b70e-da6cb8332d88', 0, 3, '[{"t":"入","r":"はい"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-4', 1, 'はいけません', 'はいけません', NULL, 3, 9, '[{"t":"はいけません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewaikemasen-4', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-1', 0, '部屋', 'へや', 'e1bce843-0d3a-4107-9293-11fbdd4312c7', 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-1', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-1', 2, '猫', 'ねこ', 'c6ec2551-173f-464c-94d0-4098e1165c3e', 3, 4, '[{"t":"猫","r":"ねこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-1', 4, 'います', 'います', '2e8dd83a-7a6a-43db-853d-072f7519c172', 5, 8, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-2', 0, '店', 'みせ', '0d3b2056-ec77-4e25-b39c-f6ade640ed47', 0, 1, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-2', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-2', 2, '人', 'ひと', '2be74f52-bdfa-434c-9039-e0618e4956c6', 2, 3, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-2', 3, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-2', 4, 'います', 'います', '2e8dd83a-7a6a-43db-853d-072f7519c172', 4, 7, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-2', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-3', 0, '机', 'つくえ', '0e738844-19ce-48ea-b9b2-0ff1a120b423', 0, 1, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-3', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-3', 2, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-3', 3, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-3', 4, 'あります', 'あります', 'e95a2a8b-2112-4767-b118-008d51786f36', 4, 8, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-3', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-4', 0, '部屋', 'へや', 'e1bce843-0d3a-4107-9293-11fbdd4312c7', 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-4', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-4', 2, '窓', 'まど', '590df083-c00c-4652-bcdd-f7630ff251d0', 3, 4, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-4', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-4', 4, 'あります', 'あります', 'e95a2a8b-2112-4767-b118-008d51786f36', 5, 9, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niexist-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb);
