-- N5 example sentences, batch 8: 〜が上手／下手, 一番, もっと, どちら, 何ですか,
-- できる, 分かる, 同じ, か (or) and に (purpose).
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- jouzu-heta
  ('sent-ex-jouzu-1', 'lang-ja', '父は料理が上手です。', 'ちち わ りょうり が じょうず です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jouzu-2', 'lang-ja', '母は料理が下手です。', 'はは わ りょうり が へた です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jouzu-3', 'lang-ja', '友達は料理が上手です。', 'ともだち わ りょうり が じょうず です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jouzu-4', 'lang-ja', '私は料理が下手です。', 'わたし わ りょうり が へた です。', 'lvl-ja-n5', 'authored', true),
  -- ichiban
  ('sent-ex-ichiban-1', 'lang-ja', '海が一番好きです。', 'うみ が いちばん すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ichiban-2', 'lang-ja', 'これが一番安いです。', 'これ が いちばん やすい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ichiban-3', 'lang-ja', '山が一番高いです。', 'やま が いちばん たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ichiban-4', 'lang-ja', '電車が一番速いです。', 'でんしゃ が いちばん はやい です。', 'lvl-ja-n5', 'authored', true),
  -- motto
  ('sent-ex-motto-1', 'lang-ja', 'もっと食べます。', 'もっと たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-motto-2', 'lang-ja', 'もっと勉強します。', 'もっと べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-motto-3', 'lang-ja', 'もっと待ちます。', 'もっと まちます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-motto-4', 'lang-ja', 'もっと欲しいです。', 'もっと ほしい です。', 'lvl-ja-n5', 'authored', true),
  -- dochira
  ('sent-ex-dochira-1', 'lang-ja', 'どちらが好きですか。', 'どちら が すき です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dochira-2', 'lang-ja', 'どちらが安いですか。', 'どちら が やすい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dochira-3', 'lang-ja', 'どちらへ行きますか。', 'どちら え いきます か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dochira-4', 'lang-ja', 'どちらが速いですか。', 'どちら が はやい です か。', 'lvl-ja-n5', 'authored', true),
  -- nan-desu-ka
  ('sent-ex-nandesuka-1', 'lang-ja', 'これは何ですか。', 'これ わ なん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nandesuka-2', 'lang-ja', 'それは何ですか。', 'それ わ なん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nandesuka-3', 'lang-ja', 'あれは何ですか。', 'あれ わ なん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nandesuka-4', 'lang-ja', '仕事は何ですか。', 'しごと わ なん です か。', 'lvl-ja-n5', 'authored', true),
  -- dekiru-n5
  ('sent-ex-dekiru-1', 'lang-ja', '料理ができます。', 'りょうり が できます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dekiru-2', 'lang-ja', '勉強ができます。', 'べんきょう が できます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dekiru-3', 'lang-ja', '電話ができます。', 'でんわ が できます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dekiru-4', 'lang-ja', '料理ができません。', 'りょうり が できません。', 'lvl-ja-n5', 'authored', true),
  -- wakaru
  ('sent-ex-wakaru-1', 'lang-ja', '分かりました。', 'わかりました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wakaru-2', 'lang-ja', '分かりません。', 'わかりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wakaru-3', 'lang-ja', 'よく分かります。', 'よく わかります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wakaru-4', 'lang-ja', '少し分かります。', 'すこし わかります。', 'lvl-ja-n5', 'authored', true),
  -- onaji
  ('sent-ex-onaji-1', 'lang-ja', '同じ本です。', 'おなじ ほん です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onaji-2', 'lang-ja', '同じ学校です。', 'おなじ がっこう です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onaji-3', 'lang-ja', '同じ靴です。', 'おなじ くつ です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onaji-4', 'lang-ja', '同じ店で買いました。', 'おなじ みせ で かいました。', 'lvl-ja-n5', 'authored', true),
  -- ka-or
  ('sent-ex-kaor-1', 'lang-ja', '魚か肉を食べます。', 'さかな か にく お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kaor-2', 'lang-ja', '本か新聞を読みます。', 'ほん か しんぶん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kaor-3', 'lang-ja', '電車か車で行きます。', 'でんしゃ か くるま で いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kaor-4', 'lang-ja', '今日か明日行きます。', 'きょう か あした いきます。', 'lvl-ja-n5', 'authored', true),
  -- ni-purpose
  ('sent-ex-nipurpose-1', 'lang-ja', '本を買いに行きます。', 'ほん お かい に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nipurpose-2', 'lang-ja', '友達に会いに行きます。', 'ともだち に あい に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nipurpose-3', 'lang-ja', 'ご飯を食べに行きます。', 'ごはん お たべ に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nipurpose-4', 'lang-ja', '泳ぎに行きます。', 'およぎ に いきます。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-jouzu-1', 'sent-ex-jouzu-1', 'en', 'My father is good at cooking.', 'authored'),
  ('st-ex-jouzu-2', 'sent-ex-jouzu-2', 'en', 'My mother is bad at cooking.', 'authored'),
  ('st-ex-jouzu-3', 'sent-ex-jouzu-3', 'en', 'My friend is good at cooking.', 'authored'),
  ('st-ex-jouzu-4', 'sent-ex-jouzu-4', 'en', 'I am bad at cooking.', 'authored'),
  ('st-ex-ichiban-1', 'sent-ex-ichiban-1', 'en', 'I like the sea best.', 'authored'),
  ('st-ex-ichiban-2', 'sent-ex-ichiban-2', 'en', 'This one is the cheapest.', 'authored'),
  ('st-ex-ichiban-3', 'sent-ex-ichiban-3', 'en', 'The mountain is the tallest.', 'authored'),
  ('st-ex-ichiban-4', 'sent-ex-ichiban-4', 'en', 'The train is the fastest.', 'authored'),
  ('st-ex-motto-1', 'sent-ex-motto-1', 'en', 'I will eat more.', 'authored'),
  ('st-ex-motto-2', 'sent-ex-motto-2', 'en', 'I will study more.', 'authored'),
  ('st-ex-motto-3', 'sent-ex-motto-3', 'en', 'I will wait longer.', 'authored'),
  ('st-ex-motto-4', 'sent-ex-motto-4', 'en', 'I want more.', 'authored'),
  ('st-ex-dochira-1', 'sent-ex-dochira-1', 'en', 'Which do you prefer?', 'authored'),
  ('st-ex-dochira-2', 'sent-ex-dochira-2', 'en', 'Which is cheaper?', 'authored'),
  ('st-ex-dochira-3', 'sent-ex-dochira-3', 'en', 'Which way are you going?', 'authored'),
  ('st-ex-dochira-4', 'sent-ex-dochira-4', 'en', 'Which is faster?', 'authored'),
  ('st-ex-nandesuka-1', 'sent-ex-nandesuka-1', 'en', 'What is this?', 'authored'),
  ('st-ex-nandesuka-2', 'sent-ex-nandesuka-2', 'en', 'What is that?', 'authored'),
  ('st-ex-nandesuka-3', 'sent-ex-nandesuka-3', 'en', 'What is that over there?', 'authored'),
  ('st-ex-nandesuka-4', 'sent-ex-nandesuka-4', 'en', 'What is your job?', 'authored'),
  ('st-ex-dekiru-1', 'sent-ex-dekiru-1', 'en', 'I can cook.', 'authored'),
  ('st-ex-dekiru-2', 'sent-ex-dekiru-2', 'en', 'I am able to study.', 'authored'),
  ('st-ex-dekiru-3', 'sent-ex-dekiru-3', 'en', 'I can make a phone call.', 'authored'),
  ('st-ex-dekiru-4', 'sent-ex-dekiru-4', 'en', 'I cannot cook.', 'authored'),
  ('st-ex-wakaru-1', 'sent-ex-wakaru-1', 'en', 'I understand.', 'authored'),
  ('st-ex-wakaru-2', 'sent-ex-wakaru-2', 'en', 'I do not understand.', 'authored'),
  ('st-ex-wakaru-3', 'sent-ex-wakaru-3', 'en', 'I understand it well.', 'authored'),
  ('st-ex-wakaru-4', 'sent-ex-wakaru-4', 'en', 'I understand a little.', 'authored'),
  ('st-ex-onaji-1', 'sent-ex-onaji-1', 'en', 'It is the same book.', 'authored'),
  ('st-ex-onaji-2', 'sent-ex-onaji-2', 'en', 'It is the same school.', 'authored'),
  ('st-ex-onaji-3', 'sent-ex-onaji-3', 'en', 'They are the same shoes.', 'authored'),
  ('st-ex-onaji-4', 'sent-ex-onaji-4', 'en', 'I bought it at the same shop.', 'authored'),
  ('st-ex-kaor-1', 'sent-ex-kaor-1', 'en', 'I will eat fish or meat.', 'authored'),
  ('st-ex-kaor-2', 'sent-ex-kaor-2', 'en', 'I read a book or a newspaper.', 'authored'),
  ('st-ex-kaor-3', 'sent-ex-kaor-3', 'en', 'I go by train or by car.', 'authored'),
  ('st-ex-kaor-4', 'sent-ex-kaor-4', 'en', 'I will go today or tomorrow.', 'authored'),
  ('st-ex-nipurpose-1', 'sent-ex-nipurpose-1', 'en', 'I am going to buy a book.', 'authored'),
  ('st-ex-nipurpose-2', 'sent-ex-nipurpose-2', 'en', 'I am going to meet a friend.', 'authored'),
  ('st-ex-nipurpose-3', 'sent-ex-nipurpose-3', 'en', 'I am going out to eat.', 'authored'),
  ('st-ex-nipurpose-4', 'sent-ex-nipurpose-4', 'en', 'I am going swimming.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('jouzu-heta', 'sent-ex-jouzu-1', 0),
  ('jouzu-heta', 'sent-ex-jouzu-2', 1),
  ('jouzu-heta', 'sent-ex-jouzu-3', 2),
  ('jouzu-heta', 'sent-ex-jouzu-4', 3),
  ('ichiban', 'sent-ex-ichiban-1', 0),
  ('ichiban', 'sent-ex-ichiban-2', 1),
  ('ichiban', 'sent-ex-ichiban-3', 2),
  ('ichiban', 'sent-ex-ichiban-4', 3),
  ('motto', 'sent-ex-motto-1', 0),
  ('motto', 'sent-ex-motto-2', 1),
  ('motto', 'sent-ex-motto-3', 2),
  ('motto', 'sent-ex-motto-4', 3),
  ('dochira', 'sent-ex-dochira-1', 0),
  ('dochira', 'sent-ex-dochira-2', 1),
  ('dochira', 'sent-ex-dochira-3', 2),
  ('dochira', 'sent-ex-dochira-4', 3),
  ('nan-desu-ka', 'sent-ex-nandesuka-1', 0),
  ('nan-desu-ka', 'sent-ex-nandesuka-2', 1),
  ('nan-desu-ka', 'sent-ex-nandesuka-3', 2),
  ('nan-desu-ka', 'sent-ex-nandesuka-4', 3),
  ('dekiru-n5', 'sent-ex-dekiru-1', 0),
  ('dekiru-n5', 'sent-ex-dekiru-2', 1),
  ('dekiru-n5', 'sent-ex-dekiru-3', 2),
  ('dekiru-n5', 'sent-ex-dekiru-4', 3),
  ('wakaru', 'sent-ex-wakaru-1', 0),
  ('wakaru', 'sent-ex-wakaru-2', 1),
  ('wakaru', 'sent-ex-wakaru-3', 2),
  ('wakaru', 'sent-ex-wakaru-4', 3),
  ('onaji', 'sent-ex-onaji-1', 0),
  ('onaji', 'sent-ex-onaji-2', 1),
  ('onaji', 'sent-ex-onaji-3', 2),
  ('onaji', 'sent-ex-onaji-4', 3),
  ('ka-or', 'sent-ex-kaor-1', 0),
  ('ka-or', 'sent-ex-kaor-2', 1),
  ('ka-or', 'sent-ex-kaor-3', 2),
  ('ka-or', 'sent-ex-kaor-4', 3),
  ('ni-purpose', 'sent-ex-nipurpose-1', 0),
  ('ni-purpose', 'sent-ex-nipurpose-2', 1),
  ('ni-purpose', 'sent-ex-nipurpose-3', 2),
  ('ni-purpose', 'sent-ex-nipurpose-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-jouzu-1', 'sent-ex-jouzu-2', 'sent-ex-jouzu-3', 'sent-ex-jouzu-4', 'sent-ex-ichiban-1', 'sent-ex-ichiban-2', 'sent-ex-ichiban-3', 'sent-ex-ichiban-4', 'sent-ex-motto-1', 'sent-ex-motto-2', 'sent-ex-motto-3', 'sent-ex-motto-4', 'sent-ex-dochira-1', 'sent-ex-dochira-2', 'sent-ex-dochira-3', 'sent-ex-dochira-4', 'sent-ex-nandesuka-1', 'sent-ex-nandesuka-2', 'sent-ex-nandesuka-3', 'sent-ex-nandesuka-4', 'sent-ex-dekiru-1', 'sent-ex-dekiru-2', 'sent-ex-dekiru-3', 'sent-ex-dekiru-4', 'sent-ex-wakaru-1', 'sent-ex-wakaru-2', 'sent-ex-wakaru-3', 'sent-ex-wakaru-4', 'sent-ex-onaji-1', 'sent-ex-onaji-2', 'sent-ex-onaji-3', 'sent-ex-onaji-4', 'sent-ex-kaor-1', 'sent-ex-kaor-2', 'sent-ex-kaor-3', 'sent-ex-kaor-4', 'sent-ex-nipurpose-1', 'sent-ex-nipurpose-2', 'sent-ex-nipurpose-3', 'sent-ex-nipurpose-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 0, '父', 'ちち', 'ee283026-0bb8-448f-83e8-204fe427c7b9', 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 2, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 2, 4, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 4, '上手', 'じょうず', 'a927574d-9212-4803-bbaa-a91c220966cf', 5, 7, '[{"t":"上手","r":"じょうず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 0, '母', 'はは', '85939c87-5d17-44b2-affc-26fb46091623', 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 2, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 2, 4, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 4, '下手', 'へた', '0a70934b-9198-42c1-866c-ac383f238a49', 5, 7, '[{"t":"下手","r":"へた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 0, '友達', 'ともだち', '826a97e0-e8f0-4ae7-a4ce-c9899a7a3c6f', 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 2, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 3, 5, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 3, 'が', 'が', NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 4, '上手', 'じょうず', 'a927574d-9212-4803-bbaa-a91c220966cf', 6, 8, '[{"t":"上手","r":"じょうず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 5, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 0, '私', 'わたし', '07d07dec-dc8f-45b2-8095-b49b5087da75', 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 2, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 2, 4, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 4, '下手', 'へた', '0a70934b-9198-42c1-866c-ac383f238a49', 5, 7, '[{"t":"下手","r":"へた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 0, '海', 'うみ', 'e3cb86b5-f5fc-4cf7-81de-c038f64be645', 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 2, '一番', 'いちばん', 'ddb5f07b-149a-4d8a-8d18-e197ac35125e', 2, 4, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 3, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 4, 6, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 0, 'これ', 'これ', 'ad6ab23c-4a16-4a3d-b96c-9a67ed6aebf9', 0, 2, '[{"t":"これ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 2, '一番', 'いちばん', 'ddb5f07b-149a-4d8a-8d18-e197ac35125e', 3, 5, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 3, '安い', 'やすい', '817cb322-0f7f-4c83-a195-dde87e4bd13f', 5, 7, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 0, '山', 'やま', '37b55423-0c09-495a-87e9-1ca7d4bbbeed', 0, 1, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 2, '一番', 'いちばん', 'ddb5f07b-149a-4d8a-8d18-e197ac35125e', 2, 4, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 3, '高い', 'たかい', 'b9f375ce-c7e3-4b81-bfed-58fb9057bc8a', 4, 6, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 0, '電車', 'でんしゃ', '36d08b54-317b-4525-9c99-cf5cae0c7ae2', 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 2, '一番', 'いちばん', 'ddb5f07b-149a-4d8a-8d18-e197ac35125e', 3, 5, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 3, '速い', 'はやい', 'd5ccebef-e5f2-45b0-882b-c020fefd992b', 5, 7, '[{"t":"速","r":"はや"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-1', 0, 'もっと', 'もっと', '41e428ed-6d2d-4612-9ce7-82951fad1543', 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-1', 1, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 3, 7, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-1', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-2', 0, 'もっと', 'もっと', '41e428ed-6d2d-4612-9ce7-82951fad1543', 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-2', 1, '勉強します', 'べんきょうします', 'b5a69b9b-5017-4a76-b301-dbd5c9f5ba2a', 3, 8, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-2', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-3', 0, 'もっと', 'もっと', '41e428ed-6d2d-4612-9ce7-82951fad1543', 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-3', 1, '待ちます', 'まちます', '9e737ca0-2423-4337-859c-402dded4a3a7', 3, 7, '[{"t":"待","r":"ま"},{"t":"ちます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-3', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 0, 'もっと', 'もっと', '41e428ed-6d2d-4612-9ce7-82951fad1543', 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 1, '欲しい', 'ほしい', 'ace38ac9-8747-495e-bc9d-12b10af1ffd9', 3, 6, '[{"t":"欲","r":"ほ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 2, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 1, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 2, '好き', 'すき', '1ae6ab02-aa14-40ad-9a57-739000a42d61', 4, 6, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 4, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 1, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 2, '安い', 'やすい', '817cb322-0f7f-4c83-a195-dde87e4bd13f', 4, 6, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 4, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 1, 'へ', 'へ', NULL, 3, 4, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 2, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 4, 8, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 1, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 2, '速い', 'はやい', 'd5ccebef-e5f2-45b0-882b-c020fefd992b', 4, 6, '[{"t":"速","r":"はや"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 4, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 0, 'これ', 'これ', 'ad6ab23c-4a16-4a3d-b96c-9a67ed6aebf9', 0, 2, '[{"t":"これ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 0, 'それ', 'それ', '3a4d7c20-6525-4d93-865d-3abdbaba0d67', 0, 2, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 0, 'あれ', 'あれ', 'b93da0ef-2b8a-4dad-b645-8b25ad756914', 0, 2, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 0, '仕事', 'しごと', '91dd183d-925a-473f-98ec-e5eaeb5a64ba', 0, 2, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 1, 'は', 'は', '0dacf911-48fa-4c5e-8d6f-d2b5cd33a0b6', 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 3, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 0, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 0, 2, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 2, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 4, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 0, '勉強', 'べんきょう', 'b5a69b9b-5017-4a76-b301-dbd5c9f5ba2a', 0, 2, '[{"t":"勉強","r":"べんきょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 2, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 4, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 0, '電話', 'でんわ', 'd39abe7d-c638-4789-b2c7-368c66d1feec', 0, 2, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 2, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 4, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 0, '料理', 'りょうり', 'cbec3d5c-6b91-4da0-a5b5-40bd1c0c0b8b', 0, 2, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 2, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 4, 'ません', 'ません', NULL, 5, 8, '[{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-1', 0, '分かりました', 'わかりました', '3d9bdd1b-da65-41a9-8893-79f313127e27', 0, 6, '[{"t":"分","r":"わ"},{"t":"かりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-1', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-2', 0, '分かりません', 'わかりません', '3d9bdd1b-da65-41a9-8893-79f313127e27', 0, 6, '[{"t":"分","r":"わ"},{"t":"かりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-2', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-3', 0, 'よく', 'よく', NULL, 0, 2, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-3', 1, '分かります', 'わかります', '3d9bdd1b-da65-41a9-8893-79f313127e27', 2, 7, '[{"t":"分","r":"わ"},{"t":"かります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-3', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-4', 0, '少し', 'すこし', 'c3fea249-9141-44a5-a822-a2bbe599d73d', 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-4', 1, '分かります', 'わかります', '3d9bdd1b-da65-41a9-8893-79f313127e27', 2, 7, '[{"t":"分","r":"わ"},{"t":"かります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-4', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 0, '同じ', 'おなじ', 'bf3966fa-7499-4235-8bea-344a02468d5e', 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 1, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 2, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 0, '同じ', 'おなじ', 'bf3966fa-7499-4235-8bea-344a02468d5e', 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 1, '学校', 'がっこう', 'c6989610-93a3-4175-8b9c-d969d934a05a', 2, 4, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 2, 'です', 'です', NULL, 4, 6, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 0, '同じ', 'おなじ', 'bf3966fa-7499-4235-8bea-344a02468d5e', 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 1, '靴', 'くつ', 'da19bf49-6698-4142-bf0f-90077a00f120', 2, 3, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 2, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 0, '同じ', 'おなじ', 'bf3966fa-7499-4235-8bea-344a02468d5e', 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 1, '店', 'みせ', '0d3b2056-ec77-4e25-b39c-f6ade640ed47', 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 2, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 3, '買いました', 'かいました', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 4, 9, '[{"t":"買","r":"か"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 0, '魚', 'さかな', 'e1e048a7-24b7-4875-8727-b61a2e2c4857', 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 1, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 1, 2, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 2, '肉', 'にく', '5df9f1a7-e606-44b7-b5a7-484d84d86549', 2, 3, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 3, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 4, '食べます', 'たべます', '788557df-2bac-4ae7-a157-8a81fbe1da16', 4, 8, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 1, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 1, 2, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 2, '新聞', 'しんぶん', '66072ae2-f8fc-4367-a221-cb59f3ec454a', 2, 4, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 4, '読みます', 'よみます', '1c659ec9-be5a-4805-ab6c-51ceda5763fb', 5, 9, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 0, '電車', 'でんしゃ', '36d08b54-317b-4525-9c99-cf5cae0c7ae2', 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 1, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 2, 3, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 2, '車', 'くるま', '5dc5735d-214f-4348-b3ee-a0fb3c4bdb9f', 3, 4, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 3, 'で', 'で', '107c2108-67cd-4a47-b42b-0e4f19b2a745', 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 4, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 5, 9, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 0, '今日', 'きょう', '3e025dc9-b02a-42a8-9558-47084b9e5e32', 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 1, 'か', 'か', '6fa759b2-f7d0-46ad-a002-86b1cff2e301', 2, 3, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 2, '明日', 'あした', '823cfb1a-cb34-4c88-86d6-5cdfca69eed5', 3, 5, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 3, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 5, 9, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 0, '本', 'ほん', 'beca25ad-0afa-4c20-bb1f-06c53a60f4ad', 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 2, '買いに', 'かいに', '5f7e2bcd-8631-4aeb-b3a4-c00877dedc47', 2, 5, '[{"t":"買","r":"か"},{"t":"いに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 3, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 5, 9, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 0, '友達', 'ともだち', '826a97e0-e8f0-4ae7-a4ce-c9899a7a3c6f', 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 2, '会いに', 'あいに', '887821df-833f-4aac-a413-7ae78d3cfe17', 3, 6, '[{"t":"会","r":"あ"},{"t":"いに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 3, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 0, 'ご飯', 'ごはん', 'ef7c1c27-7c91-46bf-9abf-1bb2ab95f4dc', 0, 2, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 2, '食べに', 'たべに', '788557df-2bac-4ae7-a157-8a81fbe1da16', 3, 6, '[{"t":"食","r":"た"},{"t":"べに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 3, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 0, '泳ぎ', 'およぎ', '1cdec3e9-4930-4c93-958d-343070e4c463', 0, 2, '[{"t":"泳","r":"およ"},{"t":"ぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 1, 'に', 'に', '05bb22cc-d56f-436c-b3ba-710cb3e2e41a', 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 2, '行きます', 'いきます', '6897cf00-2694-4be3-bbf5-0486e60dcdcb', 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb);
