-- N5 example sentences, batch 8: 〜が上手／下手, 一番, もっと, どちら, 何ですか,
-- できる, 分かる, 同じ, か (or) and に (purpose).
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- jouzu-heta
  ('sent-ex-jouzu-1', 'lang-ja', '父は料理が上手です。', 'ちち わ りょうり が じょうず です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jouzu-2', 'lang-ja', '母は料理が下手です。', 'はは わ りょうり が へた です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jouzu-3', 'lang-ja', '友達は料理が上手です。', 'ともだち わ りょうり が じょうず です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-jouzu-4', 'lang-ja', '私は料理が下手です。', 'わたし わ りょうり が へた です。', 'lvl-ja-n5', 'authored', true),
  -- ichiban
  ('sent-ex-ichiban-1', 'lang-ja', '海が一番好きです。', 'うみ が いちばん すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ichiban-2', 'lang-ja', 'これが一番安いです。', 'これ が いちばん やすい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ichiban-3', 'lang-ja', '山が一番高いです。', 'やま が いちばん たかい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ichiban-4', 'lang-ja', '電車が一番速いです。', 'でんしゃ が いちばん はやい です。', 'lvl-ja-n5', 'authored', true),
  -- motto
  ('sent-ex-motto-1', 'lang-ja', 'もっと食べます。', 'もっと たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-motto-2', 'lang-ja', 'もっと勉強します。', 'もっと べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-motto-3', 'lang-ja', 'もっと待ちます。', 'もっと まちます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-motto-4', 'lang-ja', 'もっと欲しいです。', 'もっと ほしい です。', 'lvl-ja-n5', 'authored', true),
  -- dochira
  ('sent-ex-dochira-1', 'lang-ja', 'どちらが好きですか。', 'どちら が すき です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dochira-2', 'lang-ja', 'どちらが安いですか。', 'どちら が やすい です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dochira-3', 'lang-ja', 'どちらへ行きますか。', 'どちら え いきます か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dochira-4', 'lang-ja', 'どちらが速いですか。', 'どちら が はやい です か。', 'lvl-ja-n5', 'authored', true),
  -- nan-desu-ka
  ('sent-ex-nandesuka-1', 'lang-ja', 'これは何ですか。', 'これ わ なん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nandesuka-2', 'lang-ja', 'それは何ですか。', 'それ わ なん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nandesuka-3', 'lang-ja', 'あれは何ですか。', 'あれ わ なん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nandesuka-4', 'lang-ja', '仕事は何ですか。', 'しごと わ なん です か。', 'lvl-ja-n5', 'authored', true),
  -- dekiru-n5
  ('sent-ex-dekiru-1', 'lang-ja', '料理ができます。', 'りょうり が できます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dekiru-2', 'lang-ja', '勉強ができます。', 'べんきょう が できます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dekiru-3', 'lang-ja', '電話ができます。', 'でんわ が できます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dekiru-4', 'lang-ja', '料理ができません。', 'りょうり が できません。', 'lvl-ja-n5', 'authored', true),
  -- wakaru
  ('sent-ex-wakaru-1', 'lang-ja', '分かりました。', 'わかりました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wakaru-2', 'lang-ja', '分かりません。', 'わかりません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wakaru-3', 'lang-ja', 'よく分かります。', 'よく わかります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wakaru-4', 'lang-ja', '少し分かります。', 'すこし わかります。', 'lvl-ja-n5', 'authored', true),
  -- onaji
  ('sent-ex-onaji-1', 'lang-ja', '同じ本です。', 'おなじ ほん です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onaji-2', 'lang-ja', '同じ学校です。', 'おなじ がっこう です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onaji-3', 'lang-ja', '同じ靴です。', 'おなじ くつ です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onaji-4', 'lang-ja', '同じ店で買いました。', 'おなじ みせ で かいました。', 'lvl-ja-n5', 'authored', true),
  -- ka-or
  ('sent-ex-kaor-1', 'lang-ja', '魚か肉を食べます。', 'さかな か にく お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kaor-2', 'lang-ja', '本か新聞を読みます。', 'ほん か しんぶん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kaor-3', 'lang-ja', '電車か車で行きます。', 'でんしゃ か くるま で いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-kaor-4', 'lang-ja', '今日か明日行きます。', 'きょう か あした いきます。', 'lvl-ja-n5', 'authored', true),
  -- ni-purpose
  ('sent-ex-nipurpose-1', 'lang-ja', '本を買いに行きます。', 'ほん お かい に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nipurpose-2', 'lang-ja', '友達に会いに行きます。', 'ともだち に あい に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nipurpose-3', 'lang-ja', 'ご飯を食べに行きます。', 'ごはん お たべ に いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nipurpose-4', 'lang-ja', '泳ぎに行きます。', 'およぎ に いきます。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-jouzu-1', 'sent-ex-jouzu-1', 'en', 'My father is good at cooking.', 'authored'),
  ('st-ex-jouzu-2', 'sent-ex-jouzu-2', 'en', 'My mother is bad at cooking.', 'authored'),
  ('st-ex-jouzu-3', 'sent-ex-jouzu-3', 'en', 'My friend is good at cooking.', 'authored'),
  ('st-ex-jouzu-4', 'sent-ex-jouzu-4', 'en', 'I am bad at cooking.', 'authored'),
  ('st-ex-ichiban-1', 'sent-ex-ichiban-1', 'en', 'I like the sea best.', 'authored'),
  ('st-ex-ichiban-2', 'sent-ex-ichiban-2', 'en', 'This one is the cheapest.', 'authored'),
  ('st-ex-ichiban-3', 'sent-ex-ichiban-3', 'en', 'The mountain is the tallest.', 'authored'),
  ('st-ex-ichiban-4', 'sent-ex-ichiban-4', 'en', 'The train is the fastest.', 'authored'),
  ('st-ex-motto-1', 'sent-ex-motto-1', 'en', 'I will eat more.', 'authored'),
  ('st-ex-motto-2', 'sent-ex-motto-2', 'en', 'I will study more.', 'authored'),
  ('st-ex-motto-3', 'sent-ex-motto-3', 'en', 'I will wait longer.', 'authored'),
  ('st-ex-motto-4', 'sent-ex-motto-4', 'en', 'I want more.', 'authored'),
  ('st-ex-dochira-1', 'sent-ex-dochira-1', 'en', 'Which do you prefer?', 'authored'),
  ('st-ex-dochira-2', 'sent-ex-dochira-2', 'en', 'Which is cheaper?', 'authored'),
  ('st-ex-dochira-3', 'sent-ex-dochira-3', 'en', 'Which way are you going?', 'authored'),
  ('st-ex-dochira-4', 'sent-ex-dochira-4', 'en', 'Which is faster?', 'authored'),
  ('st-ex-nandesuka-1', 'sent-ex-nandesuka-1', 'en', 'What is this?', 'authored'),
  ('st-ex-nandesuka-2', 'sent-ex-nandesuka-2', 'en', 'What is that?', 'authored'),
  ('st-ex-nandesuka-3', 'sent-ex-nandesuka-3', 'en', 'What is that over there?', 'authored'),
  ('st-ex-nandesuka-4', 'sent-ex-nandesuka-4', 'en', 'What is your job?', 'authored'),
  ('st-ex-dekiru-1', 'sent-ex-dekiru-1', 'en', 'I can cook.', 'authored'),
  ('st-ex-dekiru-2', 'sent-ex-dekiru-2', 'en', 'I am able to study.', 'authored'),
  ('st-ex-dekiru-3', 'sent-ex-dekiru-3', 'en', 'I can make a phone call.', 'authored'),
  ('st-ex-dekiru-4', 'sent-ex-dekiru-4', 'en', 'I cannot cook.', 'authored'),
  ('st-ex-wakaru-1', 'sent-ex-wakaru-1', 'en', 'I understand.', 'authored'),
  ('st-ex-wakaru-2', 'sent-ex-wakaru-2', 'en', 'I do not understand.', 'authored'),
  ('st-ex-wakaru-3', 'sent-ex-wakaru-3', 'en', 'I understand it well.', 'authored'),
  ('st-ex-wakaru-4', 'sent-ex-wakaru-4', 'en', 'I understand a little.', 'authored'),
  ('st-ex-onaji-1', 'sent-ex-onaji-1', 'en', 'It is the same book.', 'authored'),
  ('st-ex-onaji-2', 'sent-ex-onaji-2', 'en', 'It is the same school.', 'authored'),
  ('st-ex-onaji-3', 'sent-ex-onaji-3', 'en', 'They are the same shoes.', 'authored'),
  ('st-ex-onaji-4', 'sent-ex-onaji-4', 'en', 'I bought it at the same shop.', 'authored'),
  ('st-ex-kaor-1', 'sent-ex-kaor-1', 'en', 'I will eat fish or meat.', 'authored'),
  ('st-ex-kaor-2', 'sent-ex-kaor-2', 'en', 'I read a book or a newspaper.', 'authored'),
  ('st-ex-kaor-3', 'sent-ex-kaor-3', 'en', 'I go by train or by car.', 'authored'),
  ('st-ex-kaor-4', 'sent-ex-kaor-4', 'en', 'I will go today or tomorrow.', 'authored'),
  ('st-ex-nipurpose-1', 'sent-ex-nipurpose-1', 'en', 'I am going to buy a book.', 'authored'),
  ('st-ex-nipurpose-2', 'sent-ex-nipurpose-2', 'en', 'I am going to meet a friend.', 'authored'),
  ('st-ex-nipurpose-3', 'sent-ex-nipurpose-3', 'en', 'I am going out to eat.', 'authored'),
  ('st-ex-nipurpose-4', 'sent-ex-nipurpose-4', 'en', 'I am going swimming.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('jouzu-heta', 'sent-ex-jouzu-1', 0),
  ('jouzu-heta', 'sent-ex-jouzu-2', 1),
  ('jouzu-heta', 'sent-ex-jouzu-3', 2),
  ('jouzu-heta', 'sent-ex-jouzu-4', 3),
  ('ichiban', 'sent-ex-ichiban-1', 0),
  ('ichiban', 'sent-ex-ichiban-2', 1),
  ('ichiban', 'sent-ex-ichiban-3', 2),
  ('ichiban', 'sent-ex-ichiban-4', 3),
  ('motto', 'sent-ex-motto-1', 0),
  ('motto', 'sent-ex-motto-2', 1),
  ('motto', 'sent-ex-motto-3', 2),
  ('motto', 'sent-ex-motto-4', 3),
  ('dochira', 'sent-ex-dochira-1', 0),
  ('dochira', 'sent-ex-dochira-2', 1),
  ('dochira', 'sent-ex-dochira-3', 2),
  ('dochira', 'sent-ex-dochira-4', 3),
  ('nan-desu-ka', 'sent-ex-nandesuka-1', 0),
  ('nan-desu-ka', 'sent-ex-nandesuka-2', 1),
  ('nan-desu-ka', 'sent-ex-nandesuka-3', 2),
  ('nan-desu-ka', 'sent-ex-nandesuka-4', 3),
  ('dekiru-n5', 'sent-ex-dekiru-1', 0),
  ('dekiru-n5', 'sent-ex-dekiru-2', 1),
  ('dekiru-n5', 'sent-ex-dekiru-3', 2),
  ('dekiru-n5', 'sent-ex-dekiru-4', 3),
  ('wakaru', 'sent-ex-wakaru-1', 0),
  ('wakaru', 'sent-ex-wakaru-2', 1),
  ('wakaru', 'sent-ex-wakaru-3', 2),
  ('wakaru', 'sent-ex-wakaru-4', 3),
  ('onaji', 'sent-ex-onaji-1', 0),
  ('onaji', 'sent-ex-onaji-2', 1),
  ('onaji', 'sent-ex-onaji-3', 2),
  ('onaji', 'sent-ex-onaji-4', 3),
  ('ka-or', 'sent-ex-kaor-1', 0),
  ('ka-or', 'sent-ex-kaor-2', 1),
  ('ka-or', 'sent-ex-kaor-3', 2),
  ('ka-or', 'sent-ex-kaor-4', 3),
  ('ni-purpose', 'sent-ex-nipurpose-1', 0),
  ('ni-purpose', 'sent-ex-nipurpose-2', 1),
  ('ni-purpose', 'sent-ex-nipurpose-3', 2),
  ('ni-purpose', 'sent-ex-nipurpose-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-jouzu-1', 'sent-ex-jouzu-2', 'sent-ex-jouzu-3', 'sent-ex-jouzu-4', 'sent-ex-ichiban-1', 'sent-ex-ichiban-2', 'sent-ex-ichiban-3', 'sent-ex-ichiban-4', 'sent-ex-motto-1', 'sent-ex-motto-2', 'sent-ex-motto-3', 'sent-ex-motto-4', 'sent-ex-dochira-1', 'sent-ex-dochira-2', 'sent-ex-dochira-3', 'sent-ex-dochira-4', 'sent-ex-nandesuka-1', 'sent-ex-nandesuka-2', 'sent-ex-nandesuka-3', 'sent-ex-nandesuka-4', 'sent-ex-dekiru-1', 'sent-ex-dekiru-2', 'sent-ex-dekiru-3', 'sent-ex-dekiru-4', 'sent-ex-wakaru-1', 'sent-ex-wakaru-2', 'sent-ex-wakaru-3', 'sent-ex-wakaru-4', 'sent-ex-onaji-1', 'sent-ex-onaji-2', 'sent-ex-onaji-3', 'sent-ex-onaji-4', 'sent-ex-kaor-1', 'sent-ex-kaor-2', 'sent-ex-kaor-3', 'sent-ex-kaor-4', 'sent-ex-nipurpose-1', 'sent-ex-nipurpose-2', 'sent-ex-nipurpose-3', 'sent-ex-nipurpose-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 0, '父', 'ちち', (select id from words where primary_form = '父' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 2, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 4, '上手', 'じょうず', (select id from words where primary_form = '上手' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"上手","r":"じょうず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-1', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 2, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 4, '下手', 'へた', (select id from words where primary_form = '下手' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"下手","r":"へた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-2', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 2, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 3, 'が', 'が', NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 4, '上手', 'じょうず', (select id from words where primary_form = '上手' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"上手","r":"じょうず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 5, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-3', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 2, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 4, '下手', 'へた', (select id from words where primary_form = '下手' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"下手","r":"へた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-jouzu-4', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 0, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 2, '一番', 'いちばん', (select id from words where primary_form = '一番' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 3, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 0, 'これ', 'これ', (select id from words where primary_form = 'これ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"これ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 2, '一番', 'いちばん', (select id from words where primary_form = '一番' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 3, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 0, '山', 'やま', (select id from words where primary_form = '山' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 2, '一番', 'いちばん', (select id from words where primary_form = '一番' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 3, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-3', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 2, '一番', 'いちばん', (select id from words where primary_form = '一番' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 3, '速い', 'はやい', (select id from words where primary_form = '早い' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"速","r":"はや"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ichiban-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-1', 0, 'もっと', 'もっと', (select id from words where primary_form = 'もっと' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-1', 1, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-1', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-2', 0, 'もっと', 'もっと', (select id from words where primary_form = 'もっと' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-2', 1, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-2', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-3', 0, 'もっと', 'もっと', (select id from words where primary_form = 'もっと' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-3', 1, '待ちます', 'まちます', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"待","r":"ま"},{"t":"ちます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-3', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 0, 'もっと', 'もっと', (select id from words where primary_form = 'もっと' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 1, '欲しい', 'ほしい', (select id from words where primary_form = '欲しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"欲","r":"ほ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 2, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-motto-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 1, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 2, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 4, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 1, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 2, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 4, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 1, 'へ', 'へ', NULL, 3, 4, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 0, 'どちら', 'どちら', NULL, 0, 3, '[{"t":"どちら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 1, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 2, '速い', 'はやい', (select id from words where primary_form = '早い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"速","r":"はや"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 4, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dochira-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 0, 'これ', 'これ', (select id from words where primary_form = 'これ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"これ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-1', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 0, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 0, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-3', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 0, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 2, '何です', 'なんです', NULL, 3, 6, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nandesuka-4', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 0, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 4, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-1', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 0, '勉強', 'べんきょう', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"勉強","r":"べんきょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 4, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-2', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 0, '電話', 'でんわ', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 4, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-3', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 0, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 4, 'ません', 'ません', NULL, 5, 8, '[{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dekiru-4', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-1', 0, '分かりました', 'わかりました', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"分","r":"わ"},{"t":"かりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-1', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-2', 0, '分かりません', 'わかりません', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"分","r":"わ"},{"t":"かりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-2', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-3', 0, 'よく', 'よく', NULL, 0, 2, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-3', 1, '分かります', 'わかります', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"分","r":"わ"},{"t":"かります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-3', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-4', 0, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-4', 1, '分かります', 'わかります', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"分","r":"わ"},{"t":"かります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakaru-4', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 0, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 2, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-1', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 0, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 1, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 2, 'です', 'です', NULL, 4, 6, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-2', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 0, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 1, '靴', 'くつ', (select id from words where primary_form = '靴' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 2, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-3', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 0, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 3, '買いました', 'かいました', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"買","r":"か"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onaji-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 1, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 2, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 3, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 4, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 1, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 2, '新聞', 'しんぶん', (select id from words where primary_form = '新聞' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 4, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 1, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 2, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 4, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 1, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 2, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 3, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaor-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 2, '買いに', 'かいに', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"買","r":"か"},{"t":"いに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 3, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 2, '会いに', 'あいに', (select id from words where primary_form = '会う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"会","r":"あ"},{"t":"いに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 3, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-2', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 0, 'ご飯', 'ごはん', (select id from words where primary_form = 'ご飯' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 2, '食べに', 'たべに', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"食","r":"た"},{"t":"べに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 3, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 0, '泳ぎ', 'およぎ', (select id from words where primary_form = '泳ぎ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"泳","r":"およ"},{"t":"ぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nipurpose-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb);
