-- N5 example sentences, batch 9: 〜なくてもいい, で (reason), 何の, の (pronoun),
-- 〜ないで, もうすぐ, 〜ている (habit), まだ〜ていません, 〜がある (possession) and
-- 何も.
--
-- One checker change came out of this batch and is in the same commit: a run
-- made only of PARTICLES is no longer treated as shredded text. を, へ and の
-- are not in the dictionary — it holds words — so they carry no gloss and count
-- as bare kana. Alone that is invisible, because the check wants a run of two;
-- but 安いのを買います puts two of them together, and the sentence was rejected
-- for being ordinary Japanese.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- nakutemo-ii-n5
  ('sent-ex-nakutemo-1', 'lang-ja', '行かなくてもいいです。', 'いかなくて も いい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakutemo-2', 'lang-ja', '買わなくてもいいです。', 'かわなくて も いい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakutemo-3', 'lang-ja', '来なくてもいいです。', 'こなくて も いい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nakutemo-4', 'lang-ja', '食べなくてもいいです。', 'たべなくて も いい です。', 'lvl-ja-n5', 'authored', true),
  -- de-reason
  ('sent-ex-dereason-1', 'lang-ja', '雨で行きません。', 'あめ で いきません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dereason-2', 'lang-ja', '仕事で忙しいです。', 'しごと で いそがしい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dereason-3', 'lang-ja', '雨で休みます。', 'あめ で やすみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-dereason-4', 'lang-ja', '仕事で来ません。', 'しごと で きません。', 'lvl-ja-n5', 'authored', true),
  -- nan-no
  ('sent-ex-nanno-1', 'lang-ja', '何の本ですか。', 'なん の ほん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nanno-2', 'lang-ja', '何の仕事ですか。', 'なん の しごと です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nanno-3', 'lang-ja', '何の音楽が好きですか。', 'なん の おんがく が すき です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nanno-4', 'lang-ja', '何の映画ですか。', 'なん の えいが です か。', 'lvl-ja-n5', 'authored', true),
  -- no-pronoun
  ('sent-ex-nopron-1', 'lang-ja', '安いのを買います。', 'やすい の お かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nopron-2', 'lang-ja', '新しいのが好きです。', 'あたらしい の が すき です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nopron-3', 'lang-ja', '大きいのをください。', 'おおきい の お ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nopron-4', 'lang-ja', '小さいのが欲しいです。', 'ちいさい の が ほしい です。', 'lvl-ja-n5', 'authored', true),
  -- te-negative
  ('sent-ex-tenegative-1', 'lang-ja', '食べないで行きます。', 'たべないで いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tenegative-2', 'lang-ja', '寝ないで勉強します。', 'ねないで べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tenegative-3', 'lang-ja', '休まないで働きます。', 'やすまないで はたらきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-tenegative-4', 'lang-ja', '飲まないで帰ります。', 'のまないで かえります。', 'lvl-ja-n5', 'authored', true),
  -- mou-sugu
  ('sent-ex-mousugu-1', 'lang-ja', 'もうすぐ来ます。', 'もうすぐ きます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mousugu-2', 'lang-ja', 'もうすぐ帰ります。', 'もうすぐ かえります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mousugu-3', 'lang-ja', 'もうすぐ食べます。', 'もうすぐ たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-mousugu-4', 'lang-ja', 'もうすぐ寝ます。', 'もうすぐ ねます。', 'lvl-ja-n5', 'authored', true),
  -- teiru-habit
  ('sent-ex-teiruhabit-1', 'lang-ja', '毎日ご飯を食べています。', 'まいにち ごはん お たべて います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-teiruhabit-2', 'lang-ja', '毎朝新聞を読んでいます。', 'まいあさ しんぶん お よんで います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-teiruhabit-3', 'lang-ja', '日本に住んでいます。', 'にほん に すんで います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-teiruhabit-4', 'lang-ja', '会社で働いています。', 'かいしゃ で はたらいて います。', 'lvl-ja-n5', 'authored', true),
  -- mada-teimasen
  ('sent-ex-madatei-1', 'lang-ja', 'まだ食べていません。', 'まだ たべて いません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madatei-2', 'lang-ja', 'まだ来ていません。', 'まだ きて いません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madatei-3', 'lang-ja', 'まだ勉強していません。', 'まだ べんきょう して いません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-madatei-4', 'lang-ja', 'まだ買っていません。', 'まだ かって いません。', 'lvl-ja-n5', 'authored', true),
  -- aru-iru-possession
  ('sent-ex-possession-1', 'lang-ja', '車があります。', 'くるま が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-possession-2', 'lang-ja', '友達がいます。', 'ともだち が います。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-possession-3', 'lang-ja', '時間があります。', 'じかん が あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-possession-4', 'lang-ja', '仕事があります。', 'しごと が あります。', 'lvl-ja-n5', 'authored', true),
  -- nani-mo
  ('sent-ex-nanimo-1', 'lang-ja', '何も食べません。', 'なに も たべません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nanimo-2', 'lang-ja', '何も買いません。', 'なに も かいません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nanimo-3', 'lang-ja', '何も見ません。', 'なに も みません。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nanimo-4', 'lang-ja', '何も分かりません。', 'なに も わかりません。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-nakutemo-1', 'sent-ex-nakutemo-1', 'en', 'You do not have to go.', 'authored'),
  ('st-ex-nakutemo-2', 'sent-ex-nakutemo-2', 'en', 'You do not have to buy it.', 'authored'),
  ('st-ex-nakutemo-3', 'sent-ex-nakutemo-3', 'en', 'You do not have to come.', 'authored'),
  ('st-ex-nakutemo-4', 'sent-ex-nakutemo-4', 'en', 'You do not have to eat it.', 'authored'),
  ('st-ex-dereason-1', 'sent-ex-dereason-1', 'en', 'I am not going because of the rain.', 'authored'),
  ('st-ex-dereason-2', 'sent-ex-dereason-2', 'en', 'I am busy with work.', 'authored'),
  ('st-ex-dereason-3', 'sent-ex-dereason-3', 'en', 'I am taking the day off because of the rain.', 'authored'),
  ('st-ex-dereason-4', 'sent-ex-dereason-4', 'en', 'He is not coming because of work.', 'authored'),
  ('st-ex-nanno-1', 'sent-ex-nanno-1', 'en', 'What kind of book is it?', 'authored'),
  ('st-ex-nanno-2', 'sent-ex-nanno-2', 'en', 'What kind of work is it?', 'authored'),
  ('st-ex-nanno-3', 'sent-ex-nanno-3', 'en', 'What kind of music do you like?', 'authored'),
  ('st-ex-nanno-4', 'sent-ex-nanno-4', 'en', 'What kind of film is it?', 'authored'),
  ('st-ex-nopron-1', 'sent-ex-nopron-1', 'en', 'I will buy the cheap one.', 'authored'),
  ('st-ex-nopron-2', 'sent-ex-nopron-2', 'en', 'I like the new one.', 'authored'),
  ('st-ex-nopron-3', 'sent-ex-nopron-3', 'en', 'The big one, please.', 'authored'),
  ('st-ex-nopron-4', 'sent-ex-nopron-4', 'en', 'I want the small one.', 'authored'),
  ('st-ex-tenegative-1', 'sent-ex-tenegative-1', 'en', 'I go without eating.', 'authored'),
  ('st-ex-tenegative-2', 'sent-ex-tenegative-2', 'en', 'I study without sleeping.', 'authored'),
  ('st-ex-tenegative-3', 'sent-ex-tenegative-3', 'en', 'I work without resting.', 'authored'),
  ('st-ex-tenegative-4', 'sent-ex-tenegative-4', 'en', 'I go home without drinking.', 'authored'),
  ('st-ex-mousugu-1', 'sent-ex-mousugu-1', 'en', 'He is coming soon.', 'authored'),
  ('st-ex-mousugu-2', 'sent-ex-mousugu-2', 'en', 'I am going home soon.', 'authored'),
  ('st-ex-mousugu-3', 'sent-ex-mousugu-3', 'en', 'We will eat soon.', 'authored'),
  ('st-ex-mousugu-4', 'sent-ex-mousugu-4', 'en', 'I am going to bed soon.', 'authored'),
  ('st-ex-teiruhabit-1', 'sent-ex-teiruhabit-1', 'en', 'I eat rice every day.', 'authored'),
  ('st-ex-teiruhabit-2', 'sent-ex-teiruhabit-2', 'en', 'I read the newspaper every morning.', 'authored'),
  ('st-ex-teiruhabit-3', 'sent-ex-teiruhabit-3', 'en', 'I live in Japan.', 'authored'),
  ('st-ex-teiruhabit-4', 'sent-ex-teiruhabit-4', 'en', 'I work at a company.', 'authored'),
  ('st-ex-madatei-1', 'sent-ex-madatei-1', 'en', 'I have not eaten yet.', 'authored'),
  ('st-ex-madatei-2', 'sent-ex-madatei-2', 'en', 'He has not come yet.', 'authored'),
  ('st-ex-madatei-3', 'sent-ex-madatei-3', 'en', 'I have not studied yet.', 'authored'),
  ('st-ex-madatei-4', 'sent-ex-madatei-4', 'en', 'I have not bought it yet.', 'authored'),
  ('st-ex-possession-1', 'sent-ex-possession-1', 'en', 'I have a car.', 'authored'),
  ('st-ex-possession-2', 'sent-ex-possession-2', 'en', 'I have a friend.', 'authored'),
  ('st-ex-possession-3', 'sent-ex-possession-3', 'en', 'I have time.', 'authored'),
  ('st-ex-possession-4', 'sent-ex-possession-4', 'en', 'I have work.', 'authored'),
  ('st-ex-nanimo-1', 'sent-ex-nanimo-1', 'en', 'I am not eating anything.', 'authored'),
  ('st-ex-nanimo-2', 'sent-ex-nanimo-2', 'en', 'I am not buying anything.', 'authored'),
  ('st-ex-nanimo-3', 'sent-ex-nanimo-3', 'en', 'I am not watching anything.', 'authored'),
  ('st-ex-nanimo-4', 'sent-ex-nanimo-4', 'en', 'I do not understand anything.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('nakutemo-ii-n5', 'sent-ex-nakutemo-1', 0),
  ('nakutemo-ii-n5', 'sent-ex-nakutemo-2', 1),
  ('nakutemo-ii-n5', 'sent-ex-nakutemo-3', 2),
  ('nakutemo-ii-n5', 'sent-ex-nakutemo-4', 3),
  ('de-reason', 'sent-ex-dereason-1', 0),
  ('de-reason', 'sent-ex-dereason-2', 1),
  ('de-reason', 'sent-ex-dereason-3', 2),
  ('de-reason', 'sent-ex-dereason-4', 3),
  ('nan-no', 'sent-ex-nanno-1', 0),
  ('nan-no', 'sent-ex-nanno-2', 1),
  ('nan-no', 'sent-ex-nanno-3', 2),
  ('nan-no', 'sent-ex-nanno-4', 3),
  ('no-pronoun', 'sent-ex-nopron-1', 0),
  ('no-pronoun', 'sent-ex-nopron-2', 1),
  ('no-pronoun', 'sent-ex-nopron-3', 2),
  ('no-pronoun', 'sent-ex-nopron-4', 3),
  ('te-negative', 'sent-ex-tenegative-1', 0),
  ('te-negative', 'sent-ex-tenegative-2', 1),
  ('te-negative', 'sent-ex-tenegative-3', 2),
  ('te-negative', 'sent-ex-tenegative-4', 3),
  ('mou-sugu', 'sent-ex-mousugu-1', 0),
  ('mou-sugu', 'sent-ex-mousugu-2', 1),
  ('mou-sugu', 'sent-ex-mousugu-3', 2),
  ('mou-sugu', 'sent-ex-mousugu-4', 3),
  ('teiru-habit', 'sent-ex-teiruhabit-1', 0),
  ('teiru-habit', 'sent-ex-teiruhabit-2', 1),
  ('teiru-habit', 'sent-ex-teiruhabit-3', 2),
  ('teiru-habit', 'sent-ex-teiruhabit-4', 3),
  ('mada-teimasen', 'sent-ex-madatei-1', 0),
  ('mada-teimasen', 'sent-ex-madatei-2', 1),
  ('mada-teimasen', 'sent-ex-madatei-3', 2),
  ('mada-teimasen', 'sent-ex-madatei-4', 3),
  ('aru-iru-possession', 'sent-ex-possession-1', 0),
  ('aru-iru-possession', 'sent-ex-possession-2', 1),
  ('aru-iru-possession', 'sent-ex-possession-3', 2),
  ('aru-iru-possession', 'sent-ex-possession-4', 3),
  ('nani-mo', 'sent-ex-nanimo-1', 0),
  ('nani-mo', 'sent-ex-nanimo-2', 1),
  ('nani-mo', 'sent-ex-nanimo-3', 2),
  ('nani-mo', 'sent-ex-nanimo-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-nakutemo-1', 'sent-ex-nakutemo-2', 'sent-ex-nakutemo-3', 'sent-ex-nakutemo-4', 'sent-ex-dereason-1', 'sent-ex-dereason-2', 'sent-ex-dereason-3', 'sent-ex-dereason-4', 'sent-ex-nanno-1', 'sent-ex-nanno-2', 'sent-ex-nanno-3', 'sent-ex-nanno-4', 'sent-ex-nopron-1', 'sent-ex-nopron-2', 'sent-ex-nopron-3', 'sent-ex-nopron-4', 'sent-ex-tenegative-1', 'sent-ex-tenegative-2', 'sent-ex-tenegative-3', 'sent-ex-tenegative-4', 'sent-ex-mousugu-1', 'sent-ex-mousugu-2', 'sent-ex-mousugu-3', 'sent-ex-mousugu-4', 'sent-ex-teiruhabit-1', 'sent-ex-teiruhabit-2', 'sent-ex-teiruhabit-3', 'sent-ex-teiruhabit-4', 'sent-ex-madatei-1', 'sent-ex-madatei-2', 'sent-ex-madatei-3', 'sent-ex-madatei-4', 'sent-ex-possession-1', 'sent-ex-possession-2', 'sent-ex-possession-3', 'sent-ex-possession-4', 'sent-ex-nanimo-1', 'sent-ex-nanimo-2', 'sent-ex-nanimo-3', 'sent-ex-nanimo-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-nakutemo-1', 0, '行かなくてもいいです', 'いかなくてもいいです', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 10, '[{"t":"行","r":"い"},{"t":"かなくてもいいです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-1', 1, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-2', 0, '買わなくてもいいです', 'かわなくてもいいです', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 10, '[{"t":"買","r":"か"},{"t":"わなくてもいいです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-2', 1, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-3', 0, '来', 'こ', (select id from words where primary_form = '来' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"来","r":"こ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-3', 1, 'なくてもいい', 'なくてもいい', NULL, 1, 7, '[{"t":"なくてもいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-3', 2, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-3', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-4', 0, '食べなくてもいいです', 'たべなくてもいいです', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 0, 10, '[{"t":"食","r":"た"},{"t":"べなくてもいいです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemo-4', 1, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-1', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-1', 2, '行きません', 'いきません', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"行","r":"い"},{"t":"きません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-2', 0, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-2', 2, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-2', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-3', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-3', 2, '休みます', 'やすみます', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-3', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-4', 0, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-4', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-4', 2, '来ません', 'きません', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"来","r":"き"},{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dereason-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-1', 0, '何の', 'なんの', NULL, 0, 2, '[{"t":"何","r":"なん"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-1', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-1', 2, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-1', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-1', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-2', 0, '何の', 'なんの', NULL, 0, 2, '[{"t":"何","r":"なん"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-2', 1, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-2', 2, 'です', 'です', NULL, 4, 6, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-2', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-3', 0, '何の', 'なんの', NULL, 0, 2, '[{"t":"何","r":"なん"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-3', 1, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-3', 2, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-3', 3, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-3', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-3', 5, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-3', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-4', 0, '何の', 'なんの', NULL, 0, 2, '[{"t":"何","r":"なん"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-4', 1, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-4', 2, 'です', 'です', NULL, 4, 6, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-4', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanno-4', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-1', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-1', 2, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-1', 3, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-1', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-2', 0, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-2', 1, 'の', 'の', NULL, 3, 4, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-2', 2, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-2', 3, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-2', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-3', 0, '大きい', 'おおきい', (select id from words where primary_form = '大きい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"大","r":"おお"},{"t":"きい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-3', 1, 'の', 'の', NULL, 3, 4, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-3', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-3', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-4', 0, '小さい', 'ちいさい', (select id from words where primary_form = '小さい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"小","r":"ちい"},{"t":"さい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-4', 1, 'の', 'の', NULL, 3, 4, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-4', 2, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-4', 3, '欲しい', 'ほしい', (select id from words where primary_form = '欲しい' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"欲","r":"ほ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-4', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nopron-4', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-1', 0, '食べない', 'たべない', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"食","r":"た"},{"t":"べない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-1', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-1', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-1', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-2', 0, '寝ない', 'ねない', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"寝","r":"ね"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-2', 2, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-3', 0, '休まない', 'やすまない', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"休","r":"やす"},{"t":"まない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-3', 2, '働きます', 'はたらきます', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-3', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-4', 0, '飲まない', 'のまない', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"飲","r":"の"},{"t":"まない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-4', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-4', 2, '帰ります', 'かえります', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"帰","r":"かえ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tenegative-4', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-1', 0, 'もうすぐ', 'もうすぐ', NULL, 0, 4, '[{"t":"もうすぐ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-1', 1, '来ます', 'きます', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-1', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-2', 0, 'もうすぐ', 'もうすぐ', NULL, 0, 4, '[{"t":"もうすぐ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-2', 1, '帰ります', 'かえります', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"帰","r":"かえ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-2', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-3', 0, 'もうすぐ', 'もうすぐ', NULL, 0, 4, '[{"t":"もうすぐ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-3', 1, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-3', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-4', 0, 'もうすぐ', 'もうすぐ', NULL, 0, 4, '[{"t":"もうすぐ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-4', 1, '寝ます', 'ねます', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"寝","r":"ね"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mousugu-4', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-1', 0, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-1', 1, 'ご飯', 'ごはん', (select id from words where primary_form = 'ご飯' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-1', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-1', 3, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-1', 4, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-2', 0, '毎朝', 'まいあさ', (select id from words where primary_form = '毎朝' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎朝","r":"まいあさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-2', 1, '新聞', 'しんぶん', (select id from words where primary_form = '新聞' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-2', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-2', 3, '読んで', 'よんで', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-2', 4, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-3', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-3', 2, '住んで', 'すんで', (select id from words where primary_form = '住む' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"住","r":"す"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-3', 3, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-4', 0, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-4', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-4', 2, '働いて', 'はたらいて', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"働","r":"はたら"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-4', 3, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teiruhabit-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-1', 0, 'まだ', 'まだ', (select id from words where primary_form = '未だ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"まだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-1', 1, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-1', 2, 'いません', 'いません', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-1', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-2', 0, 'まだ', 'まだ', (select id from words where primary_form = '未だ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"まだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-2', 1, '来て', 'きて', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"来","r":"き"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-2', 2, 'いません', 'いません', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-3', 0, 'まだ', 'まだ', (select id from words where primary_form = '未だ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"まだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-3', 1, '勉強して', 'べんきょうして', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"勉強","r":"べんきょう"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-3', 2, 'いません', 'いません', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-3', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-4', 0, 'まだ', 'まだ', (select id from words where primary_form = '未だ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"まだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-4', 1, '買って', 'かって', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"買","r":"か"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-4', 2, 'いません', 'いません', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madatei-4', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-1', 0, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-1', 2, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-1', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-2', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-2', 2, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-2', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-3', 0, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-3', 2, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-3', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-4', 0, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-4', 2, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-possession-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-1', 0, '何も', 'なにも', NULL, 0, 2, '[{"t":"何","r":"なに"},{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-1', 1, '食べません', 'たべません', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"食","r":"た"},{"t":"べません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-1', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-2', 0, '何も', 'なにも', NULL, 0, 2, '[{"t":"何","r":"なに"},{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-2', 1, '買いません', 'かいません', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"買","r":"か"},{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-2', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-3', 0, '何も', 'なにも', NULL, 0, 2, '[{"t":"何","r":"なに"},{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-3', 1, '見ません', 'みません', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"見","r":"み"},{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-3', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-4', 0, '何も', 'なにも', NULL, 0, 2, '[{"t":"何","r":"なに"},{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-4', 1, '分かりません', 'わかりません', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 2, 8, '[{"t":"分","r":"わ"},{"t":"かりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanimo-4', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb);
