-- N5 example sentences, batch 11: the counter topics, plus 〜ごろ, 〜ずつ,
-- frequency, modifying clauses, で (tool) and と (together).
--
-- The counters are writable because the number-and-counter forms are indexed
-- now — 三時, 七時, 五分, 二枚, 三本, 五歳 are words everybody who speaks
-- Japanese knows, with one reading each, and the dictionary holds 時 and holds
-- 三 and generates the rest on demand. 七時に起きます is here as it was first
-- written, having had to become 朝ご飯を食べます in the very first batch.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- counter-ji-fun
  ('sent-ex-ctji-1', 'lang-ja', '三時に帰ります。', 'さんじ に かえります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctji-2', 'lang-ja', '七時に起きます。', 'しちじ に おきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctji-3', 'lang-ja', '八時から働きます。', 'はちじ から はたらきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctji-4', 'lang-ja', '五分待ちます。', 'ごふん まちます。', 'lvl-ja-n5', 'authored', true),
  -- counter-mai
  ('sent-ex-ctmai-1', 'lang-ja', '二枚買います。', 'にまい かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctmai-2', 'lang-ja', '三枚あります。', 'さんまい あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctmai-3', 'lang-ja', '一枚ください。', 'いちまい ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctmai-4', 'lang-ja', '五枚読みます。', 'ごまい よみます。', 'lvl-ja-n5', 'authored', true),
  -- counter-hon
  ('sent-ex-cthon-1', 'lang-ja', '三本あります。', 'さんぼん あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-cthon-2', 'lang-ja', '二本買います。', 'にほん かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-cthon-3', 'lang-ja', '一本ください。', 'いっぽん ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-cthon-4', 'lang-ja', '五本飲みます。', 'ごほん のみます。', 'lvl-ja-n5', 'authored', true),
  -- counter-sai
  ('sent-ex-ctsai-1', 'lang-ja', '二十歳です。', 'はたち です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctsai-2', 'lang-ja', '五歳です。', 'ごさい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctsai-3', 'lang-ja', '十歳になりました。', 'じゅっさい に なりました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-ctsai-4', 'lang-ja', '三歳です。', 'さんさい です。', 'lvl-ja-n5', 'authored', true),
  -- goro
  ('sent-ex-goro-1', 'lang-ja', '三時ごろ帰ります。', 'さんじ ごろ かえります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-goro-2', 'lang-ja', '七時ごろ起きます。', 'しちじ ごろ おきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-goro-3', 'lang-ja', '八時ごろ来ます。', 'はちじ ごろ きます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-goro-4', 'lang-ja', '十時ごろ寝ます。', 'じゅうじ ごろ ねます。', 'lvl-ja-n5', 'authored', true),
  -- zutsu
  ('sent-ex-zutsu-1', 'lang-ja', '一つずつください。', 'ひとつ ずつ ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-zutsu-2', 'lang-ja', '二つずつあります。', 'ふたつ ずつ あります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-zutsu-3', 'lang-ja', '一本ずつ買います。', 'いっぽん ずつ かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-zutsu-4', 'lang-ja', '一枚ずつ読みます。', 'いちまい ずつ よみます。', 'lvl-ja-n5', 'authored', true),
  -- ni-frequency
  ('sent-ex-nifreq-1', 'lang-ja', '一日に三回食べます。', 'いちにち に さんかい たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nifreq-2', 'lang-ja', '一日に二回歩きます。', 'いちにち に にかい あるきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nifreq-3', 'lang-ja', '一日に一回勉強します。', 'いちにち に いっかい べんきょう します。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-nifreq-4', 'lang-ja', '一日に三回飲みます。', 'いちにち に さんかい のみます。', 'lvl-ja-n5', 'authored', true),
  -- modifying-clause
  ('sent-ex-modclause-1', 'lang-ja', '買った本を読みます。', 'かった ほん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-modclause-2', 'lang-ja', '作った料理を食べます。', 'つくった りょうり お たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-modclause-3', 'lang-ja', '買った本は高かったです。', 'かった ほん わ たかかった です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-modclause-4', 'lang-ja', '住んでいる家は古いです。', 'すんで いる いえ わ ふるい です。', 'lvl-ja-n5', 'authored', true),
  -- de-tool
  ('sent-ex-detool-1', 'lang-ja', '手で食べます。', 'て で たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-detool-2', 'lang-ja', '電話で話します。', 'でんわ で はなします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-detool-3', 'lang-ja', '水で洗います。', 'みず で あらいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-detool-4', 'lang-ja', '車で来ます。', 'くるま で きます。', 'lvl-ja-n5', 'authored', true),
  -- to-together-n5
  ('sent-ex-totogether-1', 'lang-ja', '友達と食べます。', 'ともだち と たべます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-totogether-2', 'lang-ja', '父と行きます。', 'ちち と いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-totogether-3', 'lang-ja', '母と買います。', 'はは と かいます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-totogether-4', 'lang-ja', '友達と泳ぎます。', 'ともだち と およぎます。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-ctji-1', 'sent-ex-ctji-1', 'en', 'I go home at three.', 'authored'),
  ('st-ex-ctji-2', 'sent-ex-ctji-2', 'en', 'I get up at seven.', 'authored'),
  ('st-ex-ctji-3', 'sent-ex-ctji-3', 'en', 'I work from eight.', 'authored'),
  ('st-ex-ctji-4', 'sent-ex-ctji-4', 'en', 'I will wait five minutes.', 'authored'),
  ('st-ex-ctmai-1', 'sent-ex-ctmai-1', 'en', 'I will buy two.', 'authored'),
  ('st-ex-ctmai-2', 'sent-ex-ctmai-2', 'en', 'There are three.', 'authored'),
  ('st-ex-ctmai-3', 'sent-ex-ctmai-3', 'en', 'One, please.', 'authored'),
  ('st-ex-ctmai-4', 'sent-ex-ctmai-4', 'en', 'I will read five.', 'authored'),
  ('st-ex-cthon-1', 'sent-ex-cthon-1', 'en', 'There are three.', 'authored'),
  ('st-ex-cthon-2', 'sent-ex-cthon-2', 'en', 'I will buy two.', 'authored'),
  ('st-ex-cthon-3', 'sent-ex-cthon-3', 'en', 'One, please.', 'authored'),
  ('st-ex-cthon-4', 'sent-ex-cthon-4', 'en', 'I will drink five.', 'authored'),
  ('st-ex-ctsai-1', 'sent-ex-ctsai-1', 'en', 'I am twenty.', 'authored'),
  ('st-ex-ctsai-2', 'sent-ex-ctsai-2', 'en', 'He is five.', 'authored'),
  ('st-ex-ctsai-3', 'sent-ex-ctsai-3', 'en', 'She turned ten.', 'authored'),
  ('st-ex-ctsai-4', 'sent-ex-ctsai-4', 'en', 'He is three.', 'authored'),
  ('st-ex-goro-1', 'sent-ex-goro-1', 'en', 'I go home at about three.', 'authored'),
  ('st-ex-goro-2', 'sent-ex-goro-2', 'en', 'I get up at about seven.', 'authored'),
  ('st-ex-goro-3', 'sent-ex-goro-3', 'en', 'He comes at about eight.', 'authored'),
  ('st-ex-goro-4', 'sent-ex-goro-4', 'en', 'I go to bed at about ten.', 'authored'),
  ('st-ex-zutsu-1', 'sent-ex-zutsu-1', 'en', 'One each, please.', 'authored'),
  ('st-ex-zutsu-2', 'sent-ex-zutsu-2', 'en', 'There are two of each.', 'authored'),
  ('st-ex-zutsu-3', 'sent-ex-zutsu-3', 'en', 'I buy one of each.', 'authored'),
  ('st-ex-zutsu-4', 'sent-ex-zutsu-4', 'en', 'I read one at a time.', 'authored'),
  ('st-ex-nifreq-1', 'sent-ex-nifreq-1', 'en', 'I eat three times a day.', 'authored'),
  ('st-ex-nifreq-2', 'sent-ex-nifreq-2', 'en', 'I walk twice a day.', 'authored'),
  ('st-ex-nifreq-3', 'sent-ex-nifreq-3', 'en', 'I study once a day.', 'authored'),
  ('st-ex-nifreq-4', 'sent-ex-nifreq-4', 'en', 'I drink it three times a day.', 'authored'),
  ('st-ex-modclause-1', 'sent-ex-modclause-1', 'en', 'I read the book I bought.', 'authored'),
  ('st-ex-modclause-2', 'sent-ex-modclause-2', 'en', 'I eat the food I cooked.', 'authored'),
  ('st-ex-modclause-3', 'sent-ex-modclause-3', 'en', 'The book I bought was expensive.', 'authored'),
  ('st-ex-modclause-4', 'sent-ex-modclause-4', 'en', 'The house I live in is old.', 'authored'),
  ('st-ex-detool-1', 'sent-ex-detool-1', 'en', 'I eat with my hands.', 'authored'),
  ('st-ex-detool-2', 'sent-ex-detool-2', 'en', 'I talk on the phone.', 'authored'),
  ('st-ex-detool-3', 'sent-ex-detool-3', 'en', 'I wash it with water.', 'authored'),
  ('st-ex-detool-4', 'sent-ex-detool-4', 'en', 'I come by car.', 'authored'),
  ('st-ex-totogether-1', 'sent-ex-totogether-1', 'en', 'I eat with a friend.', 'authored'),
  ('st-ex-totogether-2', 'sent-ex-totogether-2', 'en', 'I go with my father.', 'authored'),
  ('st-ex-totogether-3', 'sent-ex-totogether-3', 'en', 'I buy it with my mother.', 'authored'),
  ('st-ex-totogether-4', 'sent-ex-totogether-4', 'en', 'I swim with a friend.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('counter-ji-fun', 'sent-ex-ctji-1', 0),
  ('counter-ji-fun', 'sent-ex-ctji-2', 1),
  ('counter-ji-fun', 'sent-ex-ctji-3', 2),
  ('counter-ji-fun', 'sent-ex-ctji-4', 3),
  ('counter-mai', 'sent-ex-ctmai-1', 0),
  ('counter-mai', 'sent-ex-ctmai-2', 1),
  ('counter-mai', 'sent-ex-ctmai-3', 2),
  ('counter-mai', 'sent-ex-ctmai-4', 3),
  ('counter-hon', 'sent-ex-cthon-1', 0),
  ('counter-hon', 'sent-ex-cthon-2', 1),
  ('counter-hon', 'sent-ex-cthon-3', 2),
  ('counter-hon', 'sent-ex-cthon-4', 3),
  ('counter-sai', 'sent-ex-ctsai-1', 0),
  ('counter-sai', 'sent-ex-ctsai-2', 1),
  ('counter-sai', 'sent-ex-ctsai-3', 2),
  ('counter-sai', 'sent-ex-ctsai-4', 3),
  ('goro', 'sent-ex-goro-1', 0),
  ('goro', 'sent-ex-goro-2', 1),
  ('goro', 'sent-ex-goro-3', 2),
  ('goro', 'sent-ex-goro-4', 3),
  ('zutsu', 'sent-ex-zutsu-1', 0),
  ('zutsu', 'sent-ex-zutsu-2', 1),
  ('zutsu', 'sent-ex-zutsu-3', 2),
  ('zutsu', 'sent-ex-zutsu-4', 3),
  ('ni-frequency', 'sent-ex-nifreq-1', 0),
  ('ni-frequency', 'sent-ex-nifreq-2', 1),
  ('ni-frequency', 'sent-ex-nifreq-3', 2),
  ('ni-frequency', 'sent-ex-nifreq-4', 3),
  ('modifying-clause', 'sent-ex-modclause-1', 0),
  ('modifying-clause', 'sent-ex-modclause-2', 1),
  ('modifying-clause', 'sent-ex-modclause-3', 2),
  ('modifying-clause', 'sent-ex-modclause-4', 3),
  ('de-tool', 'sent-ex-detool-1', 0),
  ('de-tool', 'sent-ex-detool-2', 1),
  ('de-tool', 'sent-ex-detool-3', 2),
  ('de-tool', 'sent-ex-detool-4', 3),
  ('to-together-n5', 'sent-ex-totogether-1', 0),
  ('to-together-n5', 'sent-ex-totogether-2', 1),
  ('to-together-n5', 'sent-ex-totogether-3', 2),
  ('to-together-n5', 'sent-ex-totogether-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-ctji-1', 'sent-ex-ctji-2', 'sent-ex-ctji-3', 'sent-ex-ctji-4', 'sent-ex-ctmai-1', 'sent-ex-ctmai-2', 'sent-ex-ctmai-3', 'sent-ex-ctmai-4', 'sent-ex-cthon-1', 'sent-ex-cthon-2', 'sent-ex-cthon-3', 'sent-ex-cthon-4', 'sent-ex-ctsai-1', 'sent-ex-ctsai-2', 'sent-ex-ctsai-3', 'sent-ex-ctsai-4', 'sent-ex-goro-1', 'sent-ex-goro-2', 'sent-ex-goro-3', 'sent-ex-goro-4', 'sent-ex-zutsu-1', 'sent-ex-zutsu-2', 'sent-ex-zutsu-3', 'sent-ex-zutsu-4', 'sent-ex-nifreq-1', 'sent-ex-nifreq-2', 'sent-ex-nifreq-3', 'sent-ex-nifreq-4', 'sent-ex-modclause-1', 'sent-ex-modclause-2', 'sent-ex-modclause-3', 'sent-ex-modclause-4', 'sent-ex-detool-1', 'sent-ex-detool-2', 'sent-ex-detool-3', 'sent-ex-detool-4', 'sent-ex-totogether-1', 'sent-ex-totogether-2', 'sent-ex-totogether-3', 'sent-ex-totogether-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-ctji-1', 0, '三時', 'さんじ', NULL, 0, 2, '[{"t":"三時","r":"さんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-1', 2, '帰ります', 'かえります', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"帰","r":"かえ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-2', 0, '七時', 'しちじ', NULL, 0, 2, '[{"t":"七時","r":"しちじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-2', 2, '起きます', 'おきます', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"起","r":"お"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-2', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-3', 0, '八時', 'はちじ', NULL, 0, 2, '[{"t":"八時","r":"はちじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-3', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-3', 2, '働きます', 'はたらきます', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-4', 0, '五分', 'ごふん', NULL, 0, 2, '[{"t":"五分","r":"ごふん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-4', 1, '待ちます', 'まちます', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"待","r":"ま"},{"t":"ちます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctji-4', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-1', 0, '二枚', 'にまい', NULL, 0, 2, '[{"t":"二枚","r":"にまい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-1', 1, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-1', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-2', 0, '三枚', 'さんまい', NULL, 0, 2, '[{"t":"三枚","r":"さんまい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-2', 1, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-2', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-3', 0, '一枚', 'いちまい', NULL, 0, 2, '[{"t":"一枚","r":"いちまい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-3', 1, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-3', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-4', 0, '五枚', 'ごまい', NULL, 0, 2, '[{"t":"五枚","r":"ごまい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-4', 1, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctmai-4', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-1', 0, '三本', 'さんぼん', NULL, 0, 2, '[{"t":"三本","r":"さんぼん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-1', 1, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-1', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-2', 0, '二本', 'にほん', NULL, 0, 2, '[{"t":"二本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-2', 1, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-2', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-3', 0, '一本', 'いっぽん', NULL, 0, 2, '[{"t":"一本","r":"いっぽん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-3', 1, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-3', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-4', 0, '五本', 'ごほん', NULL, 0, 2, '[{"t":"五本","r":"ごほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-4', 1, '飲みます', 'のみます', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-cthon-4', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-1', 0, '二十歳', 'はたち', (select id from words where primary_form = '二十歳' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"二十歳","r":"はたち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-1', 1, 'です', 'です', NULL, 3, 5, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-1', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-2', 0, '五歳', 'ごさい', NULL, 0, 2, '[{"t":"五歳","r":"ごさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-2', 1, 'です', 'です', NULL, 2, 4, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-2', 2, '。', '。', NULL, 4, 5, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-3', 0, '十歳', 'じゅっさい', NULL, 0, 2, '[{"t":"十歳","r":"じゅっさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-3', 2, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-4', 0, '三歳', 'さんさい', NULL, 0, 2, '[{"t":"三歳","r":"さんさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-4', 1, 'です', 'です', NULL, 2, 4, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ctsai-4', 2, '。', '。', NULL, 4, 5, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-1', 0, '三時', 'さんじ', NULL, 0, 2, '[{"t":"三時","r":"さんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-1', 1, 'ごろ', 'ごろ', NULL, 2, 4, '[{"t":"ごろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-1', 2, '帰ります', 'かえります', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"帰","r":"かえ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-2', 0, '七時', 'しちじ', NULL, 0, 2, '[{"t":"七時","r":"しちじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-2', 1, 'ごろ', 'ごろ', NULL, 2, 4, '[{"t":"ごろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-2', 2, '起きます', 'おきます', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"起","r":"お"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-3', 0, '八時', 'はちじ', NULL, 0, 2, '[{"t":"八時","r":"はちじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-3', 1, 'ごろ', 'ごろ', NULL, 2, 4, '[{"t":"ごろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-3', 2, '来ます', 'きます', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-3', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-4', 0, '十時', 'じゅうじ', NULL, 0, 2, '[{"t":"十時","r":"じゅうじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-4', 1, 'ごろ', 'ごろ', NULL, 2, 4, '[{"t":"ごろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-4', 2, '寝ます', 'ねます', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"寝","r":"ね"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-goro-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-1', 0, '一つ', 'ひとつ', (select id from words where primary_form = '一つ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一","r":"ひと"},{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-1', 1, 'ずつ', 'ずつ', NULL, 2, 4, '[{"t":"ずつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-1', 2, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-2', 0, '二つ', 'ふたつ', (select id from words where primary_form = '二つ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"二","r":"ふた"},{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-2', 1, 'ずつ', 'ずつ', NULL, 2, 4, '[{"t":"ずつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-2', 2, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-3', 0, '一本', 'いっぽん', NULL, 0, 2, '[{"t":"一本","r":"いっぽん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-3', 1, 'ずつ', 'ずつ', NULL, 2, 4, '[{"t":"ずつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-3', 2, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-4', 0, '一枚', 'いちまい', NULL, 0, 2, '[{"t":"一枚","r":"いちまい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-4', 1, 'ずつ', 'ずつ', NULL, 2, 4, '[{"t":"ずつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-4', 2, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zutsu-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-1', 0, '一日', 'いちにち', (select id from words where primary_form = '一日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一日","r":"いちにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-1', 2, '三回', 'さんかい', NULL, 3, 5, '[{"t":"三回","r":"さんかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-1', 3, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-2', 0, '一日', 'いちにち', (select id from words where primary_form = '一日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一日","r":"いちにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-2', 2, '二回', 'にかい', NULL, 3, 5, '[{"t":"二回","r":"にかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-2', 3, '歩きます', 'あるきます', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"歩","r":"ある"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-3', 0, '一日', 'いちにち', (select id from words where primary_form = '一日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一日","r":"いちにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-3', 2, '一回', 'いっかい', NULL, 3, 5, '[{"t":"一回","r":"いっかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-3', 3, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-4', 0, '一日', 'いちにち', (select id from words where primary_form = '一日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一日","r":"いちにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-4', 2, '三回', 'さんかい', NULL, 3, 5, '[{"t":"三回","r":"さんかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-4', 3, '飲みます', 'のみます', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nifreq-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-1', 0, '買った', 'かった', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"買","r":"か"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-1', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-1', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-1', 3, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-2', 0, '作った', 'つくった', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"作","r":"つく"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-2', 1, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-2', 2, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-2', 3, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-2', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-3', 0, '買った', 'かった', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"買","r":"か"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-3', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-3', 3, '高かったです', 'たかかったです', (select id from words where primary_form = '高まる' and language_id = 'lang-ja' and published order by id limit 1), 5, 11, '[{"t":"高","r":"たか"},{"t":"かったです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-3', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-4', 0, '住んで', 'すんで', (select id from words where primary_form = '住む' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"住","r":"す"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-4', 1, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-4', 2, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-4', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-4', 4, '古い', 'ふるい', (select id from words where primary_form = '古い' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"古","r":"ふる"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-4', 5, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-modclause-4', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-1', 0, '手', 'て', (select id from words where primary_form = '手' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"手","r":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-1', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-1', 2, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-1', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-2', 0, '電話', 'でんわ', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-2', 2, '話します', 'はなします', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"話","r":"はな"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-2', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-3', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-3', 2, '洗います', 'あらいます', (select id from words where primary_form = '洗う' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"洗","r":"あら"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-3', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-4', 0, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-4', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-4', 2, '来ます', 'きます', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"来","r":"き"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-detool-4', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-1', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-1', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-1', 2, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-2', 0, '父', 'ちち', (select id from words where primary_form = '父' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-2', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-2', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-2', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-3', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-3', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-3', 2, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-3', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-4', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-4', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-4', 2, '泳ぎます', 'およぎます', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"泳","r":"およ"},{"t":"ぎます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totogether-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb);
