-- N5 example sentences, batch 12: greetings and the set phrases.
--
-- ありがとうございます was coming apart as あり | が | と | う | ご | ざ | います —
-- seven pieces, one of them the verb 居る, for the first phrase anybody learns.
-- JMdict is not wrong to leave it out; it is 有り難う plus ございます, each with
-- its own entry, and the polite form is generated rather than listed. But a
-- beginner meets it as one thing, and the greetings lesson is about the phrase.
--
-- These are the expressions where the pieces are less useful than the whole.
-- Everything else stays decomposed: 本を読んで、書いてください is a request built
-- out of parts a reader should learn to see, and gluing it together teaches
-- less, so the 〜て chain topic keeps its pieces.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- greetings
  ('sent-ex-greet-1', 'lang-ja', 'おはようございます。', 'おはようございます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-greet-2', 'lang-ja', 'こんにちは。', 'こんにちは。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-greet-3', 'lang-ja', 'こんばんは。', 'こんばんは。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-greet-4', 'lang-ja', 'さようなら。', 'さようなら。', 'lvl-ja-n5', 'authored', true),
  -- sumimasen
  ('sent-ex-sumimasen-1', 'lang-ja', 'すみません、駅はどこですか。', 'すみません、えき わ どこ です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-sumimasen-2', 'lang-ja', 'すみません、お願いします。', 'すみません、おねがいします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-sumimasen-3', 'lang-ja', 'すみません、これは何ですか。', 'すみません、これ わ なん です か。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-sumimasen-4', 'lang-ja', 'すみません、水をください。', 'すみません、みず お ください。', 'lvl-ja-n5', 'authored', true),
  -- onegaishimasu
  ('sent-ex-onegai-1', 'lang-ja', 'お願いします。', 'おねがいします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onegai-2', 'lang-ja', 'よろしくお願いします。', 'よろしく おねがいします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onegai-3', 'lang-ja', 'お茶をお願いします。', 'おちゃ お おねがいします。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-onegai-4', 'lang-ja', '水をお願いします。', 'みず お おねがいします。', 'lvl-ja-n5', 'authored', true),
  -- itadakimasu
  ('sent-ex-itadaki-1', 'lang-ja', 'いただきます。', 'いただきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-itadaki-2', 'lang-ja', 'ごちそうさまでした。', 'ごちそうさま でした。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-itadaki-3', 'lang-ja', 'ごちそうさま。', 'ごちそうさま。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-itadaki-4', 'lang-ja', 'いただきますと言います。', 'いただきます と いいます。', 'lvl-ja-n5', 'authored', true),
  -- douzo-doumo
  ('sent-ex-douzo-1', 'lang-ja', 'どうぞ食べてください。', 'どうぞ たべて ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-douzo-2', 'lang-ja', 'どうもありがとうございます。', 'どうも ありがとうございます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-douzo-3', 'lang-ja', 'どうぞ座ってください。', 'どうぞ すわって ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-douzo-4', 'lang-ja', 'どうぞ入ってください。', 'どうぞ はいって ください。', 'lvl-ja-n5', 'authored', true),
  -- sou-desu-ka
  ('sent-ex-soudesuka-1', 'lang-ja', 'そうですか。', 'そうですか。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-soudesuka-2', 'lang-ja', 'そうですね。', 'そうですね。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-soudesuka-3', 'lang-ja', 'そうですか、分かりました。', 'そうですか、わかりました。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-soudesuka-4', 'lang-ja', 'そうですね、行きます。', 'そうですね、いきます。', 'lvl-ja-n5', 'authored', true),
  -- te-form-request-chain
  ('sent-ex-techain-1', 'lang-ja', '本を読んで、書いてください。', 'ほん お よんで、かいて ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-techain-2', 'lang-ja', '食べて、休んでください。', 'たべて、やすんで ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-techain-3', 'lang-ja', '見て、待ってください。', 'みて、まって ください。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-techain-4', 'lang-ja', '来て、話してください。', 'きて、はなして ください。', 'lvl-ja-n5', 'authored', true),
  -- ga-desire
  ('sent-ex-gadesire-1', 'lang-ja', 'お茶が飲みたいです。', 'おちゃ が のみたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gadesire-2', 'lang-ja', '本が読みたいです。', 'ほん が よみたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gadesire-3', 'lang-ja', '魚が買いたいです。', 'さかな が かいたい です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gadesire-4', 'lang-ja', '音楽が聞きたいです。', 'おんがく が ききたい です。', 'lvl-ja-n5', 'authored', true),
  -- ga-in-clause
  ('sent-ex-gaclause-1', 'lang-ja', '雨が降る日は休みます。', 'あめ が ふる ひ わ やすみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gaclause-2', 'lang-ja', '友達が来る時、料理を作ります。', 'ともだち が くる とき、りょうり お つくります。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gaclause-3', 'lang-ja', '私が買った本です。', 'わたし が かった ほん です。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-gaclause-4', 'lang-ja', '母が作った料理を食べます。', 'はは が つくった りょうり お たべます。', 'lvl-ja-n5', 'authored', true),
  -- word-order
  ('sent-ex-wordorder-1', 'lang-ja', '私は毎日学校へ行きます。', 'わたし わ まいにち がっこう え いきます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wordorder-2', 'lang-ja', '父は朝新聞を読みます。', 'ちち わ あさ しんぶん お よみます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wordorder-3', 'lang-ja', '友達と映画を見ます。', 'ともだち と えいが お みます。', 'lvl-ja-n5', 'authored', true),
  ('sent-ex-wordorder-4', 'lang-ja', '母は店でパンを買います。', 'はは わ みせ で パン お かいます。', 'lvl-ja-n5', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-greet-1', 'sent-ex-greet-1', 'en', 'Good morning.', 'authored'),
  ('st-ex-greet-2', 'sent-ex-greet-2', 'en', 'Hello.', 'authored'),
  ('st-ex-greet-3', 'sent-ex-greet-3', 'en', 'Good evening.', 'authored'),
  ('st-ex-greet-4', 'sent-ex-greet-4', 'en', 'Goodbye.', 'authored'),
  ('st-ex-sumimasen-1', 'sent-ex-sumimasen-1', 'en', 'Excuse me, where is the station?', 'authored'),
  ('st-ex-sumimasen-2', 'sent-ex-sumimasen-2', 'en', 'Excuse me, please.', 'authored'),
  ('st-ex-sumimasen-3', 'sent-ex-sumimasen-3', 'en', 'Excuse me, what is this?', 'authored'),
  ('st-ex-sumimasen-4', 'sent-ex-sumimasen-4', 'en', 'Excuse me, water please.', 'authored'),
  ('st-ex-onegai-1', 'sent-ex-onegai-1', 'en', 'Please.', 'authored'),
  ('st-ex-onegai-2', 'sent-ex-onegai-2', 'en', 'Please — nice to meet you.', 'authored'),
  ('st-ex-onegai-3', 'sent-ex-onegai-3', 'en', 'Tea, please.', 'authored'),
  ('st-ex-onegai-4', 'sent-ex-onegai-4', 'en', 'Water, please.', 'authored'),
  ('st-ex-itadaki-1', 'sent-ex-itadaki-1', 'en', 'Said before eating.', 'authored'),
  ('st-ex-itadaki-2', 'sent-ex-itadaki-2', 'en', 'Said after eating.', 'authored'),
  ('st-ex-itadaki-3', 'sent-ex-itadaki-3', 'en', 'Said after eating (casual).', 'authored'),
  ('st-ex-itadaki-4', 'sent-ex-itadaki-4', 'en', 'You say “itadakimasu”.', 'authored'),
  ('st-ex-douzo-1', 'sent-ex-douzo-1', 'en', 'Please, go ahead and eat.', 'authored'),
  ('st-ex-douzo-2', 'sent-ex-douzo-2', 'en', 'Thank you very much.', 'authored'),
  ('st-ex-douzo-3', 'sent-ex-douzo-3', 'en', 'Please, take a seat.', 'authored'),
  ('st-ex-douzo-4', 'sent-ex-douzo-4', 'en', 'Please, come in.', 'authored'),
  ('st-ex-soudesuka-1', 'sent-ex-soudesuka-1', 'en', 'Is that so?', 'authored'),
  ('st-ex-soudesuka-2', 'sent-ex-soudesuka-2', 'en', 'That is right.', 'authored'),
  ('st-ex-soudesuka-3', 'sent-ex-soudesuka-3', 'en', 'I see, understood.', 'authored'),
  ('st-ex-soudesuka-4', 'sent-ex-soudesuka-4', 'en', 'Right, I will go.', 'authored'),
  ('st-ex-techain-1', 'sent-ex-techain-1', 'en', 'Please read the book and write.', 'authored'),
  ('st-ex-techain-2', 'sent-ex-techain-2', 'en', 'Please eat and then rest.', 'authored'),
  ('st-ex-techain-3', 'sent-ex-techain-3', 'en', 'Please look and wait.', 'authored'),
  ('st-ex-techain-4', 'sent-ex-techain-4', 'en', 'Please come and talk.', 'authored'),
  ('st-ex-gadesire-1', 'sent-ex-gadesire-1', 'en', 'I want to drink tea.', 'authored'),
  ('st-ex-gadesire-2', 'sent-ex-gadesire-2', 'en', 'I want to read a book.', 'authored'),
  ('st-ex-gadesire-3', 'sent-ex-gadesire-3', 'en', 'I want to buy fish.', 'authored'),
  ('st-ex-gadesire-4', 'sent-ex-gadesire-4', 'en', 'I want to listen to music.', 'authored'),
  ('st-ex-gaclause-1', 'sent-ex-gaclause-1', 'en', 'On days when it rains, I take the day off.', 'authored'),
  ('st-ex-gaclause-2', 'sent-ex-gaclause-2', 'en', 'When a friend comes, I cook.', 'authored'),
  ('st-ex-gaclause-3', 'sent-ex-gaclause-3', 'en', 'It is the book I bought.', 'authored'),
  ('st-ex-gaclause-4', 'sent-ex-gaclause-4', 'en', 'I eat the food my mother made.', 'authored'),
  ('st-ex-wordorder-1', 'sent-ex-wordorder-1', 'en', 'I go to school every day.', 'authored'),
  ('st-ex-wordorder-2', 'sent-ex-wordorder-2', 'en', 'My father reads the newspaper in the morning.', 'authored'),
  ('st-ex-wordorder-3', 'sent-ex-wordorder-3', 'en', 'I watch a film with a friend.', 'authored'),
  ('st-ex-wordorder-4', 'sent-ex-wordorder-4', 'en', 'My mother buys bread at the shop.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('greetings', 'sent-ex-greet-1', 0),
  ('greetings', 'sent-ex-greet-2', 1),
  ('greetings', 'sent-ex-greet-3', 2),
  ('greetings', 'sent-ex-greet-4', 3),
  ('sumimasen', 'sent-ex-sumimasen-1', 0),
  ('sumimasen', 'sent-ex-sumimasen-2', 1),
  ('sumimasen', 'sent-ex-sumimasen-3', 2),
  ('sumimasen', 'sent-ex-sumimasen-4', 3),
  ('onegaishimasu', 'sent-ex-onegai-1', 0),
  ('onegaishimasu', 'sent-ex-onegai-2', 1),
  ('onegaishimasu', 'sent-ex-onegai-3', 2),
  ('onegaishimasu', 'sent-ex-onegai-4', 3),
  ('itadakimasu', 'sent-ex-itadaki-1', 0),
  ('itadakimasu', 'sent-ex-itadaki-2', 1),
  ('itadakimasu', 'sent-ex-itadaki-3', 2),
  ('itadakimasu', 'sent-ex-itadaki-4', 3),
  ('douzo-doumo', 'sent-ex-douzo-1', 0),
  ('douzo-doumo', 'sent-ex-douzo-2', 1),
  ('douzo-doumo', 'sent-ex-douzo-3', 2),
  ('douzo-doumo', 'sent-ex-douzo-4', 3),
  ('sou-desu-ka', 'sent-ex-soudesuka-1', 0),
  ('sou-desu-ka', 'sent-ex-soudesuka-2', 1),
  ('sou-desu-ka', 'sent-ex-soudesuka-3', 2),
  ('sou-desu-ka', 'sent-ex-soudesuka-4', 3),
  ('te-form-request-chain', 'sent-ex-techain-1', 0),
  ('te-form-request-chain', 'sent-ex-techain-2', 1),
  ('te-form-request-chain', 'sent-ex-techain-3', 2),
  ('te-form-request-chain', 'sent-ex-techain-4', 3),
  ('ga-desire', 'sent-ex-gadesire-1', 0),
  ('ga-desire', 'sent-ex-gadesire-2', 1),
  ('ga-desire', 'sent-ex-gadesire-3', 2),
  ('ga-desire', 'sent-ex-gadesire-4', 3),
  ('ga-in-clause', 'sent-ex-gaclause-1', 0),
  ('ga-in-clause', 'sent-ex-gaclause-2', 1),
  ('ga-in-clause', 'sent-ex-gaclause-3', 2),
  ('ga-in-clause', 'sent-ex-gaclause-4', 3),
  ('word-order', 'sent-ex-wordorder-1', 0),
  ('word-order', 'sent-ex-wordorder-2', 1),
  ('word-order', 'sent-ex-wordorder-3', 2),
  ('word-order', 'sent-ex-wordorder-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-greet-1', 'sent-ex-greet-2', 'sent-ex-greet-3', 'sent-ex-greet-4', 'sent-ex-sumimasen-1', 'sent-ex-sumimasen-2', 'sent-ex-sumimasen-3', 'sent-ex-sumimasen-4', 'sent-ex-onegai-1', 'sent-ex-onegai-2', 'sent-ex-onegai-3', 'sent-ex-onegai-4', 'sent-ex-itadaki-1', 'sent-ex-itadaki-2', 'sent-ex-itadaki-3', 'sent-ex-itadaki-4', 'sent-ex-douzo-1', 'sent-ex-douzo-2', 'sent-ex-douzo-3', 'sent-ex-douzo-4', 'sent-ex-soudesuka-1', 'sent-ex-soudesuka-2', 'sent-ex-soudesuka-3', 'sent-ex-soudesuka-4', 'sent-ex-techain-1', 'sent-ex-techain-2', 'sent-ex-techain-3', 'sent-ex-techain-4', 'sent-ex-gadesire-1', 'sent-ex-gadesire-2', 'sent-ex-gadesire-3', 'sent-ex-gadesire-4', 'sent-ex-gaclause-1', 'sent-ex-gaclause-2', 'sent-ex-gaclause-3', 'sent-ex-gaclause-4', 'sent-ex-wordorder-1', 'sent-ex-wordorder-2', 'sent-ex-wordorder-3', 'sent-ex-wordorder-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-greet-1', 0, 'おはようございます', 'おはようございます', NULL, 0, 9, '[{"t":"おはようございます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-greet-1', 1, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-greet-2', 0, 'こんにちは', 'こんにちは', NULL, 0, 5, '[{"t":"こんにちは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-greet-2', 1, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-greet-3', 0, 'こんばんは', 'こんばんは', NULL, 0, 5, '[{"t":"こんばんは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-greet-3', 1, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-greet-4', 0, 'さようなら', 'さようなら', NULL, 0, 5, '[{"t":"さようなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-greet-4', 1, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 0, 'すみません', 'すみません', NULL, 0, 5, '[{"t":"すみません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 2, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 4, 'どこ', 'どこ', NULL, 8, 10, '[{"t":"どこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 5, 'です', 'です', NULL, 10, 12, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 6, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-1', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-2', 0, 'すみません', 'すみません', NULL, 0, 5, '[{"t":"すみません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-2', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-2', 2, 'お願いします', 'おねがいします', (select id from words where primary_form = 'お願いします' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"お"},{"t":"願","r":"ねが"},{"t":"いします"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-2', 3, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-3', 0, 'すみません', 'すみません', NULL, 0, 5, '[{"t":"すみません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-3', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-3', 2, 'これ', 'これ', (select id from words where primary_form = 'これ' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"これ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-3', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-3', 4, '何です', 'なんです', NULL, 9, 12, '[{"t":"何","r":"なん"},{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-3', 5, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-4', 0, 'すみません', 'すみません', NULL, 0, 5, '[{"t":"すみません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-4', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-4', 2, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-4', 3, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-4', 4, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sumimasen-4', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-1', 0, 'お願いします', 'おねがいします', (select id from words where primary_form = 'お願いします' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"お"},{"t":"願","r":"ねが"},{"t":"いします"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-1', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-2', 0, 'よろしくお願いします', 'よろしくおねがいします', NULL, 0, 10, '[{"t":"よろしくお"},{"t":"願","r":"ねが"},{"t":"いします"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-2', 1, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-3', 0, 'お茶', 'おちゃ', (select id from words where primary_form = 'お茶' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"茶","r":"ちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-3', 1, 'をお願いし', 'をお願いし', NULL, 2, 7, '[{"t":"をお"},{"t":"願","r":"願"},{"t":"いし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-3', 2, 'ます', 'ます', NULL, 7, 9, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-3', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-4', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-4', 1, 'をお願いし', 'をお願いし', NULL, 1, 6, '[{"t":"をお"},{"t":"願","r":"願"},{"t":"いし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-4', 2, 'ます', 'ます', NULL, 6, 8, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-onegai-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-1', 0, 'いただきます', 'いただきます', NULL, 0, 6, '[{"t":"いただきます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-1', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-2', 0, 'ごちそうさまでした', 'ごちそうさまでした', NULL, 0, 9, '[{"t":"ごちそうさまでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-2', 1, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-3', 0, 'ごちそうさま', 'ごちそうさま', NULL, 0, 6, '[{"t":"ごちそうさま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-3', 1, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-4', 0, 'いただきます', 'いただきます', NULL, 0, 6, '[{"t":"いただきます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-4', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-4', 2, '言います', 'いいます', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"言","r":"い"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-itadaki-4', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-1', 0, 'どうぞ', 'どうぞ', (select id from words where primary_form = 'どうぞ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"どうぞ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-1', 1, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-1', 2, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-1', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-2', 0, 'どうもありがとうございます', 'どうもありがとうございます', NULL, 0, 13, '[{"t":"どうもありがとうございます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-2', 1, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-3', 0, 'どうぞ', 'どうぞ', (select id from words where primary_form = 'どうぞ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"どうぞ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-3', 1, '座って', 'すわって', (select id from words where primary_form = '座る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"座","r":"すわ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-3', 2, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-3', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-4', 0, 'どうぞ', 'どうぞ', (select id from words where primary_form = 'どうぞ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"どうぞ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-4', 1, '入って', 'はいって', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"入","r":"はい"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-4', 2, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-douzo-4', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-1', 0, 'そうですか', 'そうですか', NULL, 0, 5, '[{"t":"そうですか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-1', 1, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-2', 0, 'そうですね', 'そうですね', NULL, 0, 5, '[{"t":"そうですね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-2', 1, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-3', 0, 'そうですか', 'そうですか', NULL, 0, 5, '[{"t":"そうですか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-3', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-3', 2, '分かりました', 'わかりました', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"分","r":"わ"},{"t":"かりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-3', 3, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-4', 0, 'そうですね', 'そうですね', NULL, 0, 5, '[{"t":"そうですね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-4', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-4', 2, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soudesuka-4', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-1', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-1', 2, '読んで', 'よんで', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-1', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-1', 4, '書いて', 'かいて', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"書","r":"か"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-1', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-1', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-2', 0, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-2', 1, '、', '、', NULL, 3, 4, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-2', 2, '休んで', 'やすんで', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"休","r":"やす"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-2', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-3', 0, '見て', 'みて', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-3', 1, '、', '、', NULL, 2, 3, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-3', 2, '待って', 'まって', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"待","r":"ま"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-3', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-4', 0, '来て', 'きて', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"来","r":"き"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-4', 1, '、', '、', NULL, 2, 3, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-4', 2, '話して', 'はなして', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"話","r":"はな"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-4', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-techain-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-1', 0, 'お茶', 'おちゃ', (select id from words where primary_form = 'お茶' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"茶","r":"ちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-1', 2, '飲みたい', 'のみたい', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"飲","r":"の"},{"t":"みたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-1', 3, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-2', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-2', 2, '読みたい', 'よみたい', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"読","r":"よ"},{"t":"みたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-2', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-3', 0, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-3', 2, '買いたい', 'かいたい', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"買","r":"か"},{"t":"いたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-3', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-4', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-4', 2, '聞きたい', 'ききたい', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"聞","r":"き"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-4', 3, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gadesire-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-1', 2, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-1', 3, '日', 'ひ', (select id from words where primary_form = '日' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"日","r":"ひ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-1', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-1', 5, '休みます', 'やすみます', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"休","r":"やす"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-1', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 3, '時', 'とき', (select id from words where primary_form = '時' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"時","r":"とき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 4, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 5, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 6, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 7, '作ります', 'つくります', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"作","r":"つく"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-2', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-3', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-3', 2, '買った', 'かった', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"買","r":"か"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-3', 3, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-3', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-3', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-4', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-4', 2, '作った', 'つくった', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"作","r":"つく"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-4', 3, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-4', 4, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-4', 5, '食べます', 'たべます', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"食","r":"た"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gaclause-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-1', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-1', 2, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-1', 3, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-1', 4, 'へ', 'へ', NULL, 6, 7, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-1', 5, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-2', 0, '父', 'ちち', (select id from words where primary_form = '父' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"父","r":"ちち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-2', 2, '朝', 'あさ', (select id from words where primary_form = '朝' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-2', 3, '新聞', 'しんぶん', (select id from words where primary_form = '新聞' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-2', 4, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-2', 5, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-2', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-3', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-3', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-3', 2, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-3', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-3', 4, '見ます', 'みます', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"見","r":"み"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 2, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 4, 'パン', 'パン', (select id from words where primary_form = 'パン' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"パン"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 5, 'を', 'を', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 6, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wordorder-4', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb);
