-- N4 example sentences, batch 1: the conjugation forms and the four conditionals.
--
-- N5 taught verbs in two shapes, polite and plain. N4 opens by bending them:
-- potential, volitional, passive, causative, and the causative-passive that
-- stacks the last two. Then the four ways Japanese says "if" — と, ば, たら,
-- なら — which are one word in English and four different claims here.
--
-- Two rewordings the tokeniser forced:
--
--   日本語 is not a published word, so 日本語が話せます came apart as 日本 |
--   語が and the gloss offered 語る, "to talk about", for a particle. 英語 is
--   published; the potential topic asks about English instead.
--
--   昨日雨に降られました left 雨 with no ruby: the reading aligner gives 雨 its
--   あめ when the word opens the sentence and not when it follows 昨日, so the
--   token shipped bare and romaji mode had nothing to show. 雨 leads the
--   sentence instead.
--
--   歌わせられました shredded to 歌 | わ | せ | ら | れ. The causative-passive
--   of a godan verb is five morphemes deep and the index holds only some of
--   them; 書かせられました survives whole, so the sentence is about being made
--   to write kanji every day rather than being made to sing.
--
-- Also avoided: この and その are not published (あの is), nor are ボタン,
-- まっすぐ, 多く and 速い. Nothing here uses them.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- potential
  ('sent-ex-potential-1', 'lang-ja', '私は英語が少し話せます。', 'わたし わ えいご が すこし はなせます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-potential-2', 'lang-ja', '漢字が読めますか。', 'かんじ が よめます か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-potential-3', 'lang-ja', '朝早く起きられません。', 'あさ はやく おきられません。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-potential-4', 'lang-ja', '兄は海で泳げます。', 'あに わ うみ で およげます。', 'lvl-ja-n4', 'authored', true),
  -- ra-nuki
  ('sent-ex-ranuki-1', 'lang-ja', '今日は早く寝れる。', 'きょう わ はやく ねれる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-ranuki-2', 'lang-ja', 'あの映画は子供も見れる。', 'あの えいが わ こども も みれる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-ranuki-3', 'lang-ja', '朝早く起きれない。', 'あさ はやく おきれない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-ranuki-4', 'lang-ja', '全部は食べれない。', 'ぜんぶ わ たべれない。', 'lvl-ja-n4', 'authored', true),
  -- volitional
  ('sent-ex-volitional-1', 'lang-ja', '一緒に行こう。', 'いっしょ に いこう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-volitional-2', 'lang-ja', '明日映画を見よう。', 'あした えいが お みよう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-volitional-3', 'lang-ja', 'ご飯を食べようか。', 'ごはん お たべよう か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-volitional-4', 'lang-ja', 'そろそろ帰ろう。', 'そろそろ かえろう。', 'lvl-ja-n4', 'authored', true),
  -- passive
  ('sent-ex-passive-1', 'lang-ja', '先生に名前を呼ばれました。', 'せんせい に なまえ お よばれました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-passive-2', 'lang-ja', '雨に降られて困りました。', 'あめ に ふられて こまりました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-passive-3', 'lang-ja', '弟にケーキを食べられた。', 'おとうと に ケーキ お たべられた。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-passive-4', 'lang-ja', 'あの本は学生に読まれています。', 'あの ほん わ がくせい に よまれて います。', 'lvl-ja-n4', 'authored', true),
  -- causative
  ('sent-ex-causative-1', 'lang-ja', '先生は学生に本を読ませました。', 'せんせい わ がくせい に ほん お よませました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-causative-2', 'lang-ja', '母は妹に野菜を食べさせる。', 'はは わ いもうと に やさい お たべさせる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-causative-3', 'lang-ja', '子供を公園で遊ばせます。', 'こども お こうえん で あそばせます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-causative-4', 'lang-ja', '少し休ませてください。', 'すこし やすませて ください。', 'lvl-ja-n4', 'authored', true),
  -- causative-passive
  ('sent-ex-causpass-1', 'lang-ja', '母に野菜を食べさせられました。', 'はは に やさい お たべさせられました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-causpass-2', 'lang-ja', '会社で長い時間働かせられた。', 'かいしゃ で ながい じかん はたらかせられた。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-causpass-3', 'lang-ja', '毎日漢字を書かせられました。', 'まいにち かんじ お かかせられました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-causpass-4', 'lang-ja', '一時間も待たせられた。', 'いちじかん も またせられた。', 'lvl-ja-n4', 'authored', true),
  -- to-conditional
  ('sent-ex-tocond-1', 'lang-ja', '春になると、桜が咲きます。', 'はる に なる と、さくら が さきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tocond-2', 'lang-ja', 'ドアを押すと、開きます。', 'ドア お おす と、あきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tocond-3', 'lang-ja', '右に曲がると、駅があります。', 'みぎ に まがる と、えき が あります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tocond-4', 'lang-ja', '駅を出ると、銀行が見えます。', 'えき お でる と、ぎんこう が みえます。', 'lvl-ja-n4', 'authored', true),
  -- ba-conditional
  ('sent-ex-bacond-1', 'lang-ja', '時間があれば、行きます。', 'じかん が あれば、いきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-bacond-2', 'lang-ja', '安ければ買います。', 'やすければ かいます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-bacond-3', 'lang-ja', '早く行けば、間に合います。', 'はやく いけば、まにあいます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-bacond-4', 'lang-ja', '薬を飲めば、よくなります。', 'くすり お のめば、よく なります。', 'lvl-ja-n4', 'authored', true),
  -- tara-conditional
  ('sent-ex-taracond-1', 'lang-ja', '駅に着いたら、電話してください。', 'えき に ついたら、でんわ して ください。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-taracond-2', 'lang-ja', '家に帰ったら、宿題をします。', 'いえ に かえったら、しゅくだい お します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-taracond-3', 'lang-ja', '大学を卒業したら、日本で働きたいです。', 'だいがく お そつぎょう したら、にほん で はたらきたい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-taracond-4', 'lang-ja', 'お金があったら、車を買います。', 'おかね が あったら、くるま お かいます。', 'lvl-ja-n4', 'authored', true),
  -- nara-conditional
  ('sent-ex-naracond-1', 'lang-ja', '英語ならできます。', 'えいご なら できます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-naracond-2', 'lang-ja', '行くなら、私も行きます。', 'いく なら、わたし も いきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-naracond-3', 'lang-ja', '安いなら買います。', 'やすい なら かいます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-naracond-4', 'lang-ja', '明日なら時間があります。', 'あした なら じかん が あります。', 'lvl-ja-n4', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-potential-1', 'sent-ex-potential-1', 'en', 'I can speak a little English.', 'authored'),
  ('st-ex-potential-2', 'sent-ex-potential-2', 'en', 'Can you read kanji?', 'authored'),
  ('st-ex-potential-3', 'sent-ex-potential-3', 'en', 'I can''t get up early in the morning.', 'authored'),
  ('st-ex-potential-4', 'sent-ex-potential-4', 'en', 'My older brother can swim in the sea.', 'authored'),
  ('st-ex-ranuki-1', 'sent-ex-ranuki-1', 'en', 'I can go to bed early today.', 'authored'),
  ('st-ex-ranuki-2', 'sent-ex-ranuki-2', 'en', 'Children can watch that film too.', 'authored'),
  ('st-ex-ranuki-3', 'sent-ex-ranuki-3', 'en', 'I can''t get up early in the morning.', 'authored'),
  ('st-ex-ranuki-4', 'sent-ex-ranuki-4', 'en', 'I can''t eat all of it.', 'authored'),
  ('st-ex-volitional-1', 'sent-ex-volitional-1', 'en', 'Let''s go together.', 'authored'),
  ('st-ex-volitional-2', 'sent-ex-volitional-2', 'en', 'Let''s watch a film tomorrow.', 'authored'),
  ('st-ex-volitional-3', 'sent-ex-volitional-3', 'en', 'Shall we eat?', 'authored'),
  ('st-ex-volitional-4', 'sent-ex-volitional-4', 'en', 'Let''s head home soon.', 'authored'),
  ('st-ex-passive-1', 'sent-ex-passive-1', 'en', 'My name was called by the teacher.', 'authored'),
  ('st-ex-passive-2', 'sent-ex-passive-2', 'en', 'I got rained on, and it was a nuisance.', 'authored'),
  ('st-ex-passive-3', 'sent-ex-passive-3', 'en', 'My little brother ate my cake on me.', 'authored'),
  ('st-ex-passive-4', 'sent-ex-passive-4', 'en', 'That book is read by students.', 'authored'),
  ('st-ex-causative-1', 'sent-ex-causative-1', 'en', 'The teacher made the students read a book.', 'authored'),
  ('st-ex-causative-2', 'sent-ex-causative-2', 'en', 'My mother makes my little sister eat vegetables.', 'authored'),
  ('st-ex-causative-3', 'sent-ex-causative-3', 'en', 'I let the children play in the park.', 'authored'),
  ('st-ex-causative-4', 'sent-ex-causative-4', 'en', 'Please let me rest a little.', 'authored'),
  ('st-ex-causpass-1', 'sent-ex-causpass-1', 'en', 'I was made to eat vegetables by my mother.', 'authored'),
  ('st-ex-causpass-2', 'sent-ex-causpass-2', 'en', 'I was made to work long hours at the company.', 'authored'),
  ('st-ex-causpass-3', 'sent-ex-causpass-3', 'en', 'I was made to write kanji every day.', 'authored'),
  ('st-ex-causpass-4', 'sent-ex-causpass-4', 'en', 'I was kept waiting for a whole hour.', 'authored'),
  ('st-ex-tocond-1', 'sent-ex-tocond-1', 'en', 'When spring comes, the cherry blossoms bloom.', 'authored'),
  ('st-ex-tocond-2', 'sent-ex-tocond-2', 'en', 'If you push the door, it opens.', 'authored'),
  ('st-ex-tocond-3', 'sent-ex-tocond-3', 'en', 'If you turn right, there is the station.', 'authored'),
  ('st-ex-tocond-4', 'sent-ex-tocond-4', 'en', 'When you leave the station, you can see the bank.', 'authored'),
  ('st-ex-bacond-1', 'sent-ex-bacond-1', 'en', 'If I have time, I will go.', 'authored'),
  ('st-ex-bacond-2', 'sent-ex-bacond-2', 'en', 'If it''s cheap, I''ll buy it.', 'authored'),
  ('st-ex-bacond-3', 'sent-ex-bacond-3', 'en', 'If you go early, you will be in time.', 'authored'),
  ('st-ex-bacond-4', 'sent-ex-bacond-4', 'en', 'If you take the medicine, you will get better.', 'authored'),
  ('st-ex-taracond-1', 'sent-ex-taracond-1', 'en', 'When you arrive at the station, please call me.', 'authored'),
  ('st-ex-taracond-2', 'sent-ex-taracond-2', 'en', 'When I get home, I do my homework.', 'authored'),
  ('st-ex-taracond-3', 'sent-ex-taracond-3', 'en', 'When I graduate from university, I want to work in Japan.', 'authored'),
  ('st-ex-taracond-4', 'sent-ex-taracond-4', 'en', 'If I had the money, I would buy a car.', 'authored'),
  ('st-ex-naracond-1', 'sent-ex-naracond-1', 'en', 'If it is English, I can do it.', 'authored'),
  ('st-ex-naracond-2', 'sent-ex-naracond-2', 'en', 'If you are going, I will go too.', 'authored'),
  ('st-ex-naracond-3', 'sent-ex-naracond-3', 'en', 'If it''s cheap, I''ll buy it.', 'authored'),
  ('st-ex-naracond-4', 'sent-ex-naracond-4', 'en', 'If it is tomorrow, I have time.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('potential', 'sent-ex-potential-1', 0),
  ('potential', 'sent-ex-potential-2', 1),
  ('potential', 'sent-ex-potential-3', 2),
  ('potential', 'sent-ex-potential-4', 3),
  ('ra-nuki', 'sent-ex-ranuki-1', 0),
  ('ra-nuki', 'sent-ex-ranuki-2', 1),
  ('ra-nuki', 'sent-ex-ranuki-3', 2),
  ('ra-nuki', 'sent-ex-ranuki-4', 3),
  ('volitional', 'sent-ex-volitional-1', 0),
  ('volitional', 'sent-ex-volitional-2', 1),
  ('volitional', 'sent-ex-volitional-3', 2),
  ('volitional', 'sent-ex-volitional-4', 3),
  ('passive', 'sent-ex-passive-1', 0),
  ('passive', 'sent-ex-passive-2', 1),
  ('passive', 'sent-ex-passive-3', 2),
  ('passive', 'sent-ex-passive-4', 3),
  ('causative', 'sent-ex-causative-1', 0),
  ('causative', 'sent-ex-causative-2', 1),
  ('causative', 'sent-ex-causative-3', 2),
  ('causative', 'sent-ex-causative-4', 3),
  ('causative-passive', 'sent-ex-causpass-1', 0),
  ('causative-passive', 'sent-ex-causpass-2', 1),
  ('causative-passive', 'sent-ex-causpass-3', 2),
  ('causative-passive', 'sent-ex-causpass-4', 3),
  ('to-conditional', 'sent-ex-tocond-1', 0),
  ('to-conditional', 'sent-ex-tocond-2', 1),
  ('to-conditional', 'sent-ex-tocond-3', 2),
  ('to-conditional', 'sent-ex-tocond-4', 3),
  ('ba-conditional', 'sent-ex-bacond-1', 0),
  ('ba-conditional', 'sent-ex-bacond-2', 1),
  ('ba-conditional', 'sent-ex-bacond-3', 2),
  ('ba-conditional', 'sent-ex-bacond-4', 3),
  ('tara-conditional', 'sent-ex-taracond-1', 0),
  ('tara-conditional', 'sent-ex-taracond-2', 1),
  ('tara-conditional', 'sent-ex-taracond-3', 2),
  ('tara-conditional', 'sent-ex-taracond-4', 3),
  ('nara-conditional', 'sent-ex-naracond-1', 0),
  ('nara-conditional', 'sent-ex-naracond-2', 1),
  ('nara-conditional', 'sent-ex-naracond-3', 2),
  ('nara-conditional', 'sent-ex-naracond-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-potential-1', 'sent-ex-potential-2', 'sent-ex-potential-3', 'sent-ex-potential-4', 'sent-ex-ranuki-1', 'sent-ex-ranuki-2', 'sent-ex-ranuki-3', 'sent-ex-ranuki-4', 'sent-ex-volitional-1', 'sent-ex-volitional-2', 'sent-ex-volitional-3', 'sent-ex-volitional-4', 'sent-ex-passive-1', 'sent-ex-passive-3', 'sent-ex-passive-4', 'sent-ex-causative-1', 'sent-ex-causative-2', 'sent-ex-causative-3', 'sent-ex-causative-4', 'sent-ex-causpass-1', 'sent-ex-causpass-2', 'sent-ex-causpass-3', 'sent-ex-causpass-4', 'sent-ex-tocond-1', 'sent-ex-tocond-2', 'sent-ex-tocond-3', 'sent-ex-tocond-4', 'sent-ex-bacond-1', 'sent-ex-bacond-2', 'sent-ex-bacond-3', 'sent-ex-bacond-4', 'sent-ex-taracond-1', 'sent-ex-taracond-2', 'sent-ex-taracond-3', 'sent-ex-taracond-4', 'sent-ex-naracond-1', 'sent-ex-naracond-2', 'sent-ex-naracond-3', 'sent-ex-naracond-4', 'sent-ex-passive-2');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-potential-1', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-1', 2, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-1', 4, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-1', 5, '話せ', 'はなせ', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"話","r":"はな"},{"t":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-1', 6, 'ます', 'ます', NULL, 9, 11, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-1', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-2', 0, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-2', 2, '読め', 'よめ', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"読","r":"よ"},{"t":"め"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-2', 3, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-2', 4, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-2', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-3', 0, '朝', 'あさ', (select id from words where primary_form = '朝' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-3', 1, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-3', 2, '起きられません', 'おきられません', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 3, 10, '[{"t":"起","r":"お"},{"t":"きられません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-3', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-4', 2, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-4', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-4', 4, '泳げ', 'およげ', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"泳","r":"およ"},{"t":"げ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-4', 5, 'ます', 'ます', NULL, 6, 8, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-potential-4', 6, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-1', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-1', 2, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-1', 3, '寝れる', 'ねれる', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"寝","r":"ね"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-1', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-2', 1, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-2', 3, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-2', 4, 'も', 'も', NULL, 7, 8, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-2', 5, '見れる', 'みれる', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"見","r":"み"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-3', 0, '朝', 'あさ', (select id from words where primary_form = '朝' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-3', 1, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-3', 2, '起きれない', 'おきれない', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"起","r":"お"},{"t":"きれない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-4', 0, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-4', 2, '食べれない', 'たべれない', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"食","r":"た"},{"t":"べれない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ranuki-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-1', 0, '一緒', 'いっしょ', (select id from words where primary_form = '一緒' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一緒","r":"いっしょ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-1', 2, '行こう', 'いこう', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"行","r":"い"},{"t":"こう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-1', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-2', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-2', 1, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-2', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-2', 3, '見よう', 'みよう', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"見","r":"み"},{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-3', 0, 'ご飯', 'ごはん', (select id from words where primary_form = 'ご飯' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-3', 2, '食べよう', 'たべよう', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"食","r":"た"},{"t":"べよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-3', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-4', 0, 'そろそろ', 'そろそろ', (select id from words where primary_form = 'そろそろ' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"そろそろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-4', 1, '帰ろう', 'かえろう', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"帰","r":"かえ"},{"t":"ろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-volitional-4', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-1', 2, '名前', 'なまえ', (select id from words where primary_form = '名前' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"名前","r":"なまえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-1', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-1', 4, '呼ばれました', 'よばれました', (select id from words where primary_form = '呼ぶ' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"呼","r":"よ"},{"t":"ばれました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-3', 0, '弟', 'おとうと', (select id from words where primary_form = '弟' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"弟","r":"おとうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-3', 2, 'ケーキ', 'ケーキ', (select id from words where primary_form = 'ケーキ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"ケーキ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-3', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-3', 4, '食べられた', 'たべられた', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"食","r":"た"},{"t":"べられた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-4', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-4', 3, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-4', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-4', 5, '読まれています', 'よまれています', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 7, 14, '[{"t":"読","r":"よ"},{"t":"まれています"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-4', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 2, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 4, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 5, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 6, '読ませました', 'よませました', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 8, 14, '[{"t":"読","r":"よ"},{"t":"ませました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-1', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 2, '妹', 'いもうと', (select id from words where primary_form = '妹' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"妹","r":"いもうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 4, '野菜', 'やさい', (select id from words where primary_form = '野菜' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"野菜","r":"やさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 5, 'を', 'を', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 6, '食べさせる', 'たべさせる', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"食","r":"た"},{"t":"べさせる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-2', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-3', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-3', 2, '公園', 'こうえん', (select id from words where primary_form = '公園' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"公園","r":"こうえん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-3', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-3', 4, '遊ばせます', 'あそばせます', (select id from words where primary_form = '遊ぶ' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"遊","r":"あそ"},{"t":"ばせます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-4', 0, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-4', 1, '休ませてください', 'やすませてください', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 2, 10, '[{"t":"休","r":"やす"},{"t":"ませてください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causative-4', 2, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-1', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-1', 2, '野菜', 'やさい', (select id from words where primary_form = '野菜' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"野菜","r":"やさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-1', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-1', 4, '食べさせられました', 'たべさせられました', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 14, '[{"t":"食","r":"た"},{"t":"べさせられました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-1', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-2', 0, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-2', 2, '長い', 'ながい', (select id from words where primary_form = '長い' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"長","r":"なが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-2', 3, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-2', 4, '働かせられた', 'はたらかせられた', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 7, 13, '[{"t":"働","r":"はたら"},{"t":"かせられた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-2', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-3', 0, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-3', 1, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-3', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-3', 3, '書かせられました', 'かかせられました', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 5, 13, '[{"t":"書","r":"か"},{"t":"かせられました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-3', 4, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-4', 0, '一時間', 'いちじかん', NULL, 0, 3, '[{"t":"一時間","r":"いちじかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-4', 1, 'も', 'も', NULL, 3, 4, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-4', 2, '待たせられた', 'またせられた', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 4, 10, '[{"t":"待","r":"ま"},{"t":"たせられた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-causpass-4', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 0, '春', 'はる', (select id from words where primary_form = '春' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"春","r":"はる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 2, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 4, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 5, '桜', 'さくら', (select id from words where primary_form = '桜' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"桜","r":"さくら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 6, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 7, '咲きます', 'さきます', (select id from words where primary_form = '咲く' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"咲","r":"さ"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-1', 8, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-2', 0, 'ドア', 'ドア', (select id from words where primary_form = 'ドア' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"ドア"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-2', 2, '押す', 'おす', (select id from words where primary_form = '押す' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"押","r":"お"},{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-2', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-2', 4, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-2', 5, '開きます', 'あきます', (select id from words where primary_form = '開く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"開","r":"あ"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 0, '右', 'みぎ', (select id from words where primary_form = '右' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"右","r":"みぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 2, '曲がる', 'まがる', (select id from words where primary_form = '曲がる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"曲","r":"ま"},{"t":"がる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 4, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 5, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 6, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 7, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-3', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 0, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 2, '出る', 'でる', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"出","r":"で"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 4, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 5, '銀行', 'ぎんこう', (select id from words where primary_form = '銀行' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"銀行","r":"ぎんこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 6, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 7, '見えます', 'みえます', (select id from words where primary_form = '見える' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"見","r":"み"},{"t":"えます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tocond-4', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-1', 0, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-1', 2, 'あれば', 'あれば', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"あれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-1', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-1', 4, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-2', 0, '安ければ', 'やすければ', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"安","r":"やす"},{"t":"ければ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-2', 1, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-2', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-3', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-3', 1, '行けば', 'いけば', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"行","r":"い"},{"t":"けば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-3', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-3', 3, '間に合います', 'まにあいます', (select id from words where primary_form = '間に合う' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"間","r":"ま"},{"t":"に"},{"t":"合","r":"あ"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-4', 0, '薬', 'くすり', (select id from words where primary_form = '薬' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"薬","r":"くすり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-4', 2, '飲めば', 'のめば', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"飲","r":"の"},{"t":"めば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-4', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-4', 4, 'よく', 'よく', NULL, 6, 8, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-4', 5, 'なります', 'なります', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"なります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bacond-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-1', 0, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-1', 2, '着いたら', 'ついたら', (select id from words where primary_form = '着く' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"着","r":"つ"},{"t":"いたら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-1', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-1', 4, '電話して', 'でんわして', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"電話","r":"でんわ"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-1', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-1', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 0, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 2, '帰ったら', 'かえったら', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"帰","r":"かえ"},{"t":"ったら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 4, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 5, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 6, 'します', 'します', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-2', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 0, '大学', 'だいがく', (select id from words where primary_form = '大学' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"大学","r":"だいがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 2, '卒業したら', 'そつぎょうしたら', (select id from words where primary_form = '卒業' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"卒業","r":"そつぎょう"},{"t":"したら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 4, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 5, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 6, '働きたい', 'はたらきたい', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"働","r":"はたら"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 7, 'です', 'です', NULL, 16, 18, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-3', 8, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 0, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 2, 'あったら', 'あったら', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"あったら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 4, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 5, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 6, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taracond-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-1', 0, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-1', 1, 'なら', 'なら', NULL, 2, 4, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-1', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-1', 3, 'き', 'き', NULL, 5, 6, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-1', 4, 'ます', 'ます', NULL, 6, 8, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-2', 0, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-2', 1, 'なら', 'なら', NULL, 2, 4, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-2', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-2', 3, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-2', 4, 'も', 'も', NULL, 6, 7, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-2', 5, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-3', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-3', 1, 'なら', 'なら', NULL, 2, 4, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-3', 2, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-4', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-4', 1, 'なら', 'なら', NULL, 2, 4, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-4', 2, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-4', 3, 'が', 'が', NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-4', 4, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naracond-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-2', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-2', 2, '降られて', 'ふられて', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"降","r":"ふ"},{"t":"られて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-2', 3, '困りました', 'こまりました', (select id from words where primary_form = '困る' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"困","r":"こま"},{"t":"りました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-passive-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb);
