-- N4 example sentences, batch 2: what you can do, and how sure you are.
--
-- 〜たり and 〜ことができる list and permit; 〜ことがある and 〜予定 place
-- things in time. Then six ways to hedge — そうだ twice over (heard it, looks
-- it), ようだ, らしい, みたい and はず — which English collapses into "seems"
-- and Japanese keeps apart by how the speaker came to believe it.
--
-- One rewording: ここ shreds to こ|こ, so 「ここで写真を撮ることが
-- できますか」 asks about 駅 instead. こ・そ demonstratives are thin in the
-- published vocabulary generally — この and その are missing where あの is
-- there — and the batch leans on あの throughout.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- tari-tari
  ('sent-ex-taritari-1', 'lang-ja', '日曜日は本を読んだり、音楽を聞いたりします。', 'にちようび わ ほん お よんだり、おんがく お きいたり します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-taritari-2', 'lang-ja', '休みの日は掃除したり、買い物したりします。', 'やすみ の ひ わ そうじ したり、かいもの したり します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-taritari-3', 'lang-ja', '公園で歩いたり、走ったりしました。', 'こうえん で あるいたり、はしったり しました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-taritari-4', 'lang-ja', '子供は泣いたり笑ったりします。', 'こども わ ないたり わらったり します。', 'lvl-ja-n4', 'authored', true),
  -- koto-ga-dekiru
  ('sent-ex-kotodekiru-1', 'lang-ja', '私はピアノを弾くことができます。', 'わたし わ ピアノ お ひく こと が できます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kotodekiru-2', 'lang-ja', '駅で写真を撮ることができますか。', 'えき で しゃしん お とる こと が できます か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kotodekiru-3', 'lang-ja', '難しい漢字を書くことができません。', 'むずかしい かんじ お かく こと が できません。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kotodekiru-4', 'lang-ja', '兄は車を運転することができます。', 'あに わ くるま お うんてん する こと が できます。', 'lvl-ja-n4', 'authored', true),
  -- ru-koto-ga-aru
  ('sent-ex-kotogaaru-1', 'lang-ja', '朝ご飯を食べないことがあります。', 'あさごはん お たべない こと が あります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kotogaaru-2', 'lang-ja', '会社に遅れることがあります。', 'かいしゃ に おくれる こと が あります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kotogaaru-3', 'lang-ja', '雪で電車が止まることがあります。', 'ゆき で でんしゃ が とまる こと が あります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kotogaaru-4', 'lang-ja', '夜遅くまで働くことがある。', 'よる おそく まで はたらく こと が ある。', 'lvl-ja-n4', 'authored', true),
  -- yotei
  ('sent-ex-yotei-1', 'lang-ja', '明日日本へ行く予定です。', 'あした にほん え いく よてい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-yotei-2', 'lang-ja', '来週会議をする予定です。', 'らいしゅう かいぎ お する よてい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-yotei-3', 'lang-ja', '旅行の予定はありますか。', 'りょこう の よてい わ あります か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-yotei-4', 'lang-ja', '兄は来年結婚する予定です。', 'あに わ らいねん けっこん する よてい です。', 'lvl-ja-n4', 'authored', true),
  -- sou-hearsay
  ('sent-ex-souhear-1', 'lang-ja', '明日は雨が降るそうです。', 'あした わ あめ が ふる そう です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-souhear-2', 'lang-ja', 'あの店は安いそうです。', 'あの みせ わ やすい そう です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-souhear-3', 'lang-ja', '先生は来ないそうだ。', 'せんせい わ こない そう だ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-souhear-4', 'lang-ja', '兄は元気だそうです。', 'あに わ げんき だ そう です。', 'lvl-ja-n4', 'authored', true),
  -- sou-appearance
  ('sent-ex-souapp-1', 'lang-ja', '雨が降りそうです。', 'あめ が ふりそう です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-souapp-2', 'lang-ja', 'あのケーキはおいしそうです。', 'あの ケーキ わ おいしそう です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-souapp-3', 'lang-ja', '元気そうですね。', 'げんきそう です ね。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-souapp-4', 'lang-ja', '今にも泣きそうです。', 'いま に も なきそう です。', 'lvl-ja-n4', 'authored', true),
  -- you-da
  ('sent-ex-youda-1', 'lang-ja', '雨が降ったようです。', 'あめ が ふった よう です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youda-2', 'lang-ja', '先生は忙しいようだ。', 'せんせい わ いそがしい よう だ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youda-3', 'lang-ja', '兄は疲れているようです。', 'あに わ つかれて いる よう です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youda-4', 'lang-ja', '店は休みのようです。', 'みせ わ やすみ の よう です。', 'lvl-ja-n4', 'authored', true),
  -- rashii
  ('sent-ex-rashii-1', 'lang-ja', '明日は寒いらしいです。', 'あした わ さむい らしい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-rashii-2', 'lang-ja', 'あの店は有名らしい。', 'あの みせ わ ゆうめい らしい。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-rashii-3', 'lang-ja', '兄は来週日本へ行くらしい。', 'あに わ らいしゅう にほん え いく らしい。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-rashii-4', 'lang-ja', '試験は難しいらしいです。', 'しけん わ むずかしい らしい です。', 'lvl-ja-n4', 'authored', true),
  -- mitai
  ('sent-ex-mitai-1', 'lang-ja', '外は寒いみたいです。', 'そと わ さむい みたい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-mitai-2', 'lang-ja', '誰かいるみたいだ。', 'だれか いる みたい だ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-mitai-3', 'lang-ja', '子供みたいですね。', 'こども みたい です ね。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-mitai-4', 'lang-ja', 'あの人は先生みたいだ。', 'あの ひと わ せんせい みたい だ。', 'lvl-ja-n4', 'authored', true),
  -- hazu
  ('sent-ex-hazu-1', 'lang-ja', '先生はもう来たはずです。', 'せんせい わ もう きた はず です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-hazu-2', 'lang-ja', '会議はもう終わるはずだ。', 'かいぎ わ もう おわる はず だ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-hazu-3', 'lang-ja', 'あの店は今日休みのはずです。', 'あの みせ わ きょう やすみ の はず です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-hazu-4', 'lang-ja', '兄は英語が話せるはずです。', 'あに わ えいご が はなせる はず です。', 'lvl-ja-n4', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-taritari-1', 'sent-ex-taritari-1', 'en', 'On Sundays I read books, listen to music, and so on.', 'authored'),
  ('st-ex-taritari-2', 'sent-ex-taritari-2', 'en', 'On my day off I clean, do the shopping, and the like.', 'authored'),
  ('st-ex-taritari-3', 'sent-ex-taritari-3', 'en', 'We walked and ran around in the park.', 'authored'),
  ('st-ex-taritari-4', 'sent-ex-taritari-4', 'en', 'Children cry and laugh and cry again.', 'authored'),
  ('st-ex-kotodekiru-1', 'sent-ex-kotodekiru-1', 'en', 'I can play the piano.', 'authored'),
  ('st-ex-kotodekiru-2', 'sent-ex-kotodekiru-2', 'en', 'Can you take photographs at the station?', 'authored'),
  ('st-ex-kotodekiru-3', 'sent-ex-kotodekiru-3', 'en', 'I can''t write difficult kanji.', 'authored'),
  ('st-ex-kotodekiru-4', 'sent-ex-kotodekiru-4', 'en', 'My older brother can drive a car.', 'authored'),
  ('st-ex-kotogaaru-1', 'sent-ex-kotogaaru-1', 'en', 'There are times when I skip breakfast.', 'authored'),
  ('st-ex-kotogaaru-2', 'sent-ex-kotogaaru-2', 'en', 'There are times when I am late for work.', 'authored'),
  ('st-ex-kotogaaru-3', 'sent-ex-kotogaaru-3', 'en', 'There are times when the trains stop because of snow.', 'authored'),
  ('st-ex-kotogaaru-4', 'sent-ex-kotogaaru-4', 'en', 'There are times when I work late into the night.', 'authored'),
  ('st-ex-yotei-1', 'sent-ex-yotei-1', 'en', 'I am planning to go to Japan tomorrow.', 'authored'),
  ('st-ex-yotei-2', 'sent-ex-yotei-2', 'en', 'We are scheduled to hold a meeting next week.', 'authored'),
  ('st-ex-yotei-3', 'sent-ex-yotei-3', 'en', 'Do you have any travel plans?', 'authored'),
  ('st-ex-yotei-4', 'sent-ex-yotei-4', 'en', 'My older brother is planning to get married next year.', 'authored'),
  ('st-ex-souhear-1', 'sent-ex-souhear-1', 'en', 'I hear it will rain tomorrow.', 'authored'),
  ('st-ex-souhear-2', 'sent-ex-souhear-2', 'en', 'They say that shop is cheap.', 'authored'),
  ('st-ex-souhear-3', 'sent-ex-souhear-3', 'en', 'I hear the teacher is not coming.', 'authored'),
  ('st-ex-souhear-4', 'sent-ex-souhear-4', 'en', 'I hear my older brother is well.', 'authored'),
  ('st-ex-souapp-1', 'sent-ex-souapp-1', 'en', 'It looks like it is going to rain.', 'authored'),
  ('st-ex-souapp-2', 'sent-ex-souapp-2', 'en', 'That cake looks delicious.', 'authored'),
  ('st-ex-souapp-3', 'sent-ex-souapp-3', 'en', 'You look well.', 'authored'),
  ('st-ex-souapp-4', 'sent-ex-souapp-4', 'en', 'She looks about to burst into tears.', 'authored'),
  ('st-ex-youda-1', 'sent-ex-youda-1', 'en', 'It seems it rained.', 'authored'),
  ('st-ex-youda-2', 'sent-ex-youda-2', 'en', 'The teacher seems to be busy.', 'authored'),
  ('st-ex-youda-3', 'sent-ex-youda-3', 'en', 'My older brother seems to be tired.', 'authored'),
  ('st-ex-youda-4', 'sent-ex-youda-4', 'en', 'The shop appears to be closed.', 'authored'),
  ('st-ex-rashii-1', 'sent-ex-rashii-1', 'en', 'It seems it will be cold tomorrow.', 'authored'),
  ('st-ex-rashii-2', 'sent-ex-rashii-2', 'en', 'That shop is apparently famous.', 'authored'),
  ('st-ex-rashii-3', 'sent-ex-rashii-3', 'en', 'Apparently my older brother is going to Japan next week.', 'authored'),
  ('st-ex-rashii-4', 'sent-ex-rashii-4', 'en', 'The exam is supposed to be difficult.', 'authored'),
  ('st-ex-mitai-1', 'sent-ex-mitai-1', 'en', 'It looks cold outside.', 'authored'),
  ('st-ex-mitai-2', 'sent-ex-mitai-2', 'en', 'It looks like somebody is in.', 'authored'),
  ('st-ex-mitai-3', 'sent-ex-mitai-3', 'en', 'You are just like a child.', 'authored'),
  ('st-ex-mitai-4', 'sent-ex-mitai-4', 'en', 'That person looks like a teacher.', 'authored'),
  ('st-ex-hazu-1', 'sent-ex-hazu-1', 'en', 'The teacher should have arrived already.', 'authored'),
  ('st-ex-hazu-2', 'sent-ex-hazu-2', 'en', 'The meeting ought to be finishing soon.', 'authored'),
  ('st-ex-hazu-3', 'sent-ex-hazu-3', 'en', 'That shop is supposed to be closed today.', 'authored'),
  ('st-ex-hazu-4', 'sent-ex-hazu-4', 'en', 'My older brother should be able to speak English.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('tari-tari', 'sent-ex-taritari-1', 0),
  ('tari-tari', 'sent-ex-taritari-2', 1),
  ('tari-tari', 'sent-ex-taritari-3', 2),
  ('tari-tari', 'sent-ex-taritari-4', 3),
  ('koto-ga-dekiru', 'sent-ex-kotodekiru-1', 0),
  ('koto-ga-dekiru', 'sent-ex-kotodekiru-2', 1),
  ('koto-ga-dekiru', 'sent-ex-kotodekiru-3', 2),
  ('koto-ga-dekiru', 'sent-ex-kotodekiru-4', 3),
  ('ru-koto-ga-aru', 'sent-ex-kotogaaru-1', 0),
  ('ru-koto-ga-aru', 'sent-ex-kotogaaru-2', 1),
  ('ru-koto-ga-aru', 'sent-ex-kotogaaru-3', 2),
  ('ru-koto-ga-aru', 'sent-ex-kotogaaru-4', 3),
  ('yotei', 'sent-ex-yotei-1', 0),
  ('yotei', 'sent-ex-yotei-2', 1),
  ('yotei', 'sent-ex-yotei-3', 2),
  ('yotei', 'sent-ex-yotei-4', 3),
  ('sou-hearsay', 'sent-ex-souhear-1', 0),
  ('sou-hearsay', 'sent-ex-souhear-2', 1),
  ('sou-hearsay', 'sent-ex-souhear-3', 2),
  ('sou-hearsay', 'sent-ex-souhear-4', 3),
  ('sou-appearance', 'sent-ex-souapp-1', 0),
  ('sou-appearance', 'sent-ex-souapp-2', 1),
  ('sou-appearance', 'sent-ex-souapp-3', 2),
  ('sou-appearance', 'sent-ex-souapp-4', 3),
  ('you-da', 'sent-ex-youda-1', 0),
  ('you-da', 'sent-ex-youda-2', 1),
  ('you-da', 'sent-ex-youda-3', 2),
  ('you-da', 'sent-ex-youda-4', 3),
  ('rashii', 'sent-ex-rashii-1', 0),
  ('rashii', 'sent-ex-rashii-2', 1),
  ('rashii', 'sent-ex-rashii-3', 2),
  ('rashii', 'sent-ex-rashii-4', 3),
  ('mitai', 'sent-ex-mitai-1', 0),
  ('mitai', 'sent-ex-mitai-2', 1),
  ('mitai', 'sent-ex-mitai-3', 2),
  ('mitai', 'sent-ex-mitai-4', 3),
  ('hazu', 'sent-ex-hazu-1', 0),
  ('hazu', 'sent-ex-hazu-2', 1),
  ('hazu', 'sent-ex-hazu-3', 2),
  ('hazu', 'sent-ex-hazu-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-taritari-1', 'sent-ex-taritari-2', 'sent-ex-taritari-3', 'sent-ex-taritari-4', 'sent-ex-kotodekiru-1', 'sent-ex-kotodekiru-2', 'sent-ex-kotodekiru-3', 'sent-ex-kotodekiru-4', 'sent-ex-kotogaaru-1', 'sent-ex-kotogaaru-2', 'sent-ex-kotogaaru-3', 'sent-ex-kotogaaru-4', 'sent-ex-yotei-1', 'sent-ex-yotei-2', 'sent-ex-yotei-3', 'sent-ex-yotei-4', 'sent-ex-souhear-1', 'sent-ex-souhear-2', 'sent-ex-souhear-3', 'sent-ex-souhear-4', 'sent-ex-souapp-1', 'sent-ex-souapp-2', 'sent-ex-souapp-3', 'sent-ex-souapp-4', 'sent-ex-youda-1', 'sent-ex-youda-2', 'sent-ex-youda-3', 'sent-ex-youda-4', 'sent-ex-rashii-1', 'sent-ex-rashii-2', 'sent-ex-rashii-3', 'sent-ex-rashii-4', 'sent-ex-mitai-1', 'sent-ex-mitai-2', 'sent-ex-mitai-3', 'sent-ex-mitai-4', 'sent-ex-hazu-1', 'sent-ex-hazu-2', 'sent-ex-hazu-3', 'sent-ex-hazu-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 0, '日曜日', 'にちようび', (select id from words where primary_form = '日曜日' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"日曜日","r":"にちようび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 2, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 4, '読んだ', 'よんだ', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"読","r":"よ"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 5, 'り', 'り', NULL, 9, 10, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 6, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 7, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 8, 'を', 'を', NULL, 13, 14, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 9, '聞いた', 'きいた', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 14, 17, '[{"t":"聞","r":"き"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 10, 'り', 'り', NULL, 17, 18, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 11, 'します', 'します', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 18, 21, '[{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-1', 12, '。', '。', NULL, 21, 22, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 0, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 2, '日', 'ひ', (select id from words where primary_form = '日' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"日","r":"ひ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 4, '掃除した', 'そうじした', (select id from words where primary_form = '掃除' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"掃除","r":"そうじ"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 5, 'り', 'り', NULL, 9, 10, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 6, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 7, '買い物した', 'かいものした', (select id from words where primary_form = '買い物' and language_id = 'lang-ja' and published order by id limit 1), 11, 16, '[{"t":"買","r":"か"},{"t":"い"},{"t":"物","r":"もの"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 8, 'り', 'り', NULL, 16, 17, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 9, 'します', 'します', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 17, 20, '[{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-2', 10, '。', '。', NULL, 20, 21, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 0, '公園', 'こうえん', (select id from words where primary_form = '公園' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"公園","r":"こうえん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 2, '歩いた', 'あるいた', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"歩","r":"ある"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 3, 'り', 'り', NULL, 6, 7, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 5, '走った', 'はしった', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"走","r":"はし"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 6, 'り', 'り', NULL, 11, 12, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 7, 'しました', 'しました', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-3', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 2, '泣いた', 'ないた', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"泣","r":"な"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 3, 'り', 'り', NULL, 6, 7, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 4, '笑った', 'わらった', (select id from words where primary_form = '笑う' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"笑","r":"わら"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 5, 'り', 'り', NULL, 10, 11, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 6, 'します', 'します', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritari-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-1', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-1', 2, 'ピアノ', 'ピアノ', (select id from words where primary_form = 'ピアノ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"ピアノ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-1', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-1', 4, '弾く', 'ひく', (select id from words where primary_form = '弾く' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"弾","r":"ひ"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-1', 5, 'ことができます', 'ことができます', NULL, 8, 15, '[{"t":"ことができます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-1', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 0, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 2, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 4, '撮る', 'とる', (select id from words where primary_form = '撮る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"撮","r":"と"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 5, 'ことができます', 'ことができます', NULL, 7, 14, '[{"t":"ことができます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 6, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 0, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 1, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 2, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 3, '書く', 'かく', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"書","r":"か"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 4, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 5, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 6, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 7, 'き', 'き', NULL, 12, 13, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 8, 'ません', 'ません', NULL, 13, 16, '[{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-3', 9, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-4', 2, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-4', 3, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-4', 4, '運転する', 'うんてんする', (select id from words where primary_form = '運転' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"運転","r":"うんてん"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-4', 5, 'ことができます', 'ことができます', NULL, 8, 15, '[{"t":"ことができます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotodekiru-4', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-1', 0, '朝ご飯', 'あさごはん', (select id from words where primary_form = '朝ごはん' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"朝","r":"あさ"},{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-1', 1, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-1', 2, '食べない', 'たべない', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"食","r":"た"},{"t":"べない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-1', 3, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-1', 4, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-1', 5, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-1', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-2', 0, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-2', 2, '遅れる', 'おくれる', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"遅","r":"おく"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-2', 3, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-2', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-2', 5, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 0, '雪', 'ゆき', (select id from words where primary_form = '雪' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雪","r":"ゆき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 2, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 4, '止まる', 'とまる', (select id from words where primary_form = '止まる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"止","r":"と"},{"t":"まる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 5, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 6, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 7, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-3', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-4', 0, '夜', 'よる', (select id from words where primary_form = '夜' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"夜","r":"よる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-4', 1, '遅くまで', 'おそくまで', (select id from words where primary_form = '遅くとも' and language_id = 'lang-ja' and published order by id limit 1), 1, 5, '[{"t":"遅","r":"おそ"},{"t":"くまで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-4', 2, '働く', 'はたらく', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"働","r":"はたら"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-4', 3, 'ことがある', 'ことがある', NULL, 7, 12, '[{"t":"ことがある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotogaaru-4', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-1', 1, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-1', 2, 'へ', 'へ', NULL, 4, 5, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-1', 3, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-1', 4, '予定', 'よてい', (select id from words where primary_form = '予定' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"予定","r":"よてい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-1', 5, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-2', 0, '来週', 'らいしゅう', (select id from words where primary_form = '来週' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"来週","r":"らいしゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-2', 1, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-2', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-2', 3, 'する', 'する', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-2', 4, '予定', 'よてい', (select id from words where primary_form = '予定' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"予定","r":"よてい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-2', 5, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-3', 0, '旅行', 'りょこう', (select id from words where primary_form = '旅行' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"旅行","r":"りょこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-3', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-3', 2, '予定', 'よてい', (select id from words where primary_form = '予定' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"予定","r":"よてい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-3', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-3', 4, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-3', 5, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-4', 2, '来年', 'らいねん', (select id from words where primary_form = '来年' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"来年","r":"らいねん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-4', 3, '結婚する', 'けっこんする', (select id from words where primary_form = '結婚' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"結婚","r":"けっこん"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-4', 4, '予定', 'よてい', (select id from words where primary_form = '予定' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"予定","r":"よてい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-4', 5, 'です', 'です', NULL, 10, 12, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yotei-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 2, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 4, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 5, 'そう', 'そう', (select id from words where primary_form = 'そう' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"そう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 6, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-1', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-2', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-2', 3, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-2', 4, 'そう', 'そう', (select id from words where primary_form = 'そう' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"そう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-2', 5, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-2', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-3', 2, '来ない', 'こない', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"来","r":"こ"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-3', 3, 'そうだ', 'そうだ', NULL, 6, 9, '[{"t":"そうだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-4', 2, '元気', 'げんき', (select id from words where primary_form = '元気' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"元気","r":"げんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-4', 3, 'だ', 'だ', NULL, 4, 5, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-4', 4, 'そう', 'そう', (select id from words where primary_form = 'そう' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"そう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-4', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souhear-4', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-1', 2, '降り', 'ふり', (select id from words where primary_form = '下り' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"降","r":"ふ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-1', 3, 'そう', 'そう', (select id from words where primary_form = 'そう' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"そう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-1', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 1, 'ケーキ', 'ケーキ', (select id from words where primary_form = 'ケーキ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"ケーキ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 3, 'おい', 'おい', (select id from words where primary_form = 'おい' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"おい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 4, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 5, 'そう', 'そう', (select id from words where primary_form = 'そう' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"そう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 6, 'です', 'です', NULL, 11, 13, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-2', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-3', 0, '元気', 'げんき', (select id from words where primary_form = '元気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"元気","r":"げんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-3', 1, 'そうですね', 'そうですね', NULL, 2, 7, '[{"t":"そうですね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-3', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-4', 0, '今にも', 'いまにも', (select id from words where primary_form = '今にも' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"今","r":"いま"},{"t":"にも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-4', 1, '泣きそうです', 'なきそうです', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"泣","r":"な"},{"t":"きそうです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-souapp-4', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-1', 2, '降った', 'ふった', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"降","r":"ふ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-1', 3, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-1', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-2', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-2', 2, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-2', 3, 'ようだ', 'ようだ', NULL, 6, 9, '[{"t":"ようだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-3', 2, '疲れて', 'つかれて', (select id from words where primary_form = '疲れる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"疲","r":"つか"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-3', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-3', 4, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-3', 5, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-4', 0, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-4', 2, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-4', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-4', 4, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-4', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youda-4', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-1', 2, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-1', 3, 'らしい', 'らしい', NULL, 5, 8, '[{"t":"らしい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-1', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-2', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-2', 3, '有名', 'ゆうめい', (select id from words where primary_form = '有名' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"有名","r":"ゆうめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-2', 4, 'らしい', 'らしい', NULL, 6, 9, '[{"t":"らしい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 2, '来週', 'らいしゅう', (select id from words where primary_form = '来週' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"来週","r":"らいしゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 3, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 4, 'へ', 'へ', NULL, 6, 7, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 5, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 6, 'らしい', 'らしい', NULL, 9, 12, '[{"t":"らしい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-3', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-4', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-4', 2, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-4', 3, 'らしい', 'らしい', NULL, 6, 9, '[{"t":"らしい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-4', 4, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-rashii-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-1', 0, '外', 'そと', (select id from words where primary_form = '外' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"外","r":"そと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-1', 2, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-1', 3, 'み', 'み', NULL, 4, 5, '[{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-1', 4, 'たい', 'たい', (select id from words where primary_form = 'たい' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-1', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-1', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-2', 0, '誰か', 'だれか', (select id from words where primary_form = '誰か' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"誰","r":"だれ"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-2', 1, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-2', 2, 'み', 'み', NULL, 4, 5, '[{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-2', 3, 'たい', 'たい', (select id from words where primary_form = 'たい' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-2', 4, 'だ', 'だ', NULL, 7, 8, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-2', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-3', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-3', 1, 'み', 'み', NULL, 2, 3, '[{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-3', 2, 'たい', 'たい', (select id from words where primary_form = 'たい' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-3', 3, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-3', 4, 'ね', 'ね', (select id from words where primary_form = 'ね' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"ね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-3', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 1, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 3, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 4, 'み', 'み', NULL, 6, 7, '[{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 5, 'たい', 'たい', (select id from words where primary_form = 'たい' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 6, 'だ', 'だ', NULL, 9, 10, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mitai-4', 7, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-1', 2, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-1', 3, '来た', 'きた', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"来","r":"き"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-1', 4, 'はず', 'はず', NULL, 7, 9, '[{"t":"はず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-1', 5, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-2', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-2', 2, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-2', 3, '終わる', 'おわる', (select id from words where primary_form = '終わる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"終","r":"お"},{"t":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-2', 4, 'はず', 'はず', NULL, 8, 10, '[{"t":"はず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-2', 5, 'だ', 'だ', NULL, 10, 11, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 3, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 4, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 5, 'の', 'の', NULL, 8, 9, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 6, 'はず', 'はず', NULL, 9, 11, '[{"t":"はず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 7, 'です', 'です', NULL, 11, 13, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-3', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 2, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 4, '話せる', 'はなせる', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"話","r":"はな"},{"t":"せる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 5, 'はず', 'はず', NULL, 8, 10, '[{"t":"はず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 6, 'です', 'です', NULL, 10, 12, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazu-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb);
