-- N4 example sentences, batch 3: guessing, quoting, and doing things for people.
--
-- 〜かもしれない, 〜だろう, 〜と思う, 〜という, 〜かどうか, then the five
-- auxiliary verbs that ride on 〜て: あげる, くれる, もらう, おく, しまう.
--
-- The auxiliaries came with a constraint worth writing down. あげる, くれる,
-- もらう and the aspectual おく and しまう are in the vocabulary as dictionary
-- forms only — the index holds spellings, not conjugations, and it de-inflects
-- kanji-stemmed verbs (読んで, 教えて, 撮って all cut clean) but not kana-only
-- ones. So 読んであげました shredded to 読んで | あ | げ | ました, and so did
-- あげた, あげたい, くれます, くれた, もらいました, おきます and しまった.
--
-- What survives is あげる, くれる, もらう, おく, おいて, しまう and
-- しまいました. Those five topics are therefore written in plain form, which
-- is what their patterns show anyway — Verb-て + あげる, not + あげました.
-- Not a lexicon fix worth making from a seed; the giving verbs want proper
-- entries and that is a vocabulary import, not four example sentences.
--
-- One other rewording: 明日雨が降るかどうか… left 雨 with no ruby, the same
-- aligner gap batch 1 hit behind 昨日. 雨 opens the sentence instead.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- kamoshirenai
  ('sent-ex-kamo-1', 'lang-ja', '明日は雨が降るかもしれません。', 'あした わ あめ が ふる かもしれません。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kamo-2', 'lang-ja', '先生は来ないかもしれない。', 'せんせい わ こない かもしれない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kamo-3', 'lang-ja', '試験は難しいかもしれません。', 'しけん わ むずかしい かもしれません。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kamo-4', 'lang-ja', '兄はもう帰ったかもしれない。', 'あに わ もう かえった かもしれない。', 'lvl-ja-n4', 'authored', true),
  -- darou
  ('sent-ex-darou-1', 'lang-ja', '明日は寒いでしょう。', 'あした わ さむい でしょう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-darou-2', 'lang-ja', 'あの店は高いだろう。', 'あの みせ わ たかい だろう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-darou-3', 'lang-ja', '先生はもう来るでしょう。', 'せんせい わ もう くる でしょう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-darou-4', 'lang-ja', '今夜は雪が降るだろう。', 'こんや わ ゆき が ふる だろう。', 'lvl-ja-n4', 'authored', true),
  -- to-omou
  ('sent-ex-toomou-1', 'lang-ja', '明日は雨が降ると思います。', 'あした わ あめ が ふる と おもいます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-toomou-2', 'lang-ja', 'あの映画は面白いと思う。', 'あの えいが わ おもしろい と おもう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-toomou-3', 'lang-ja', '日本へ行こうと思います。', 'にほん え いこう と おもいます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-toomou-4', 'lang-ja', '先生は来ないと思います。', 'せんせい わ こない と おもいます。', 'lvl-ja-n4', 'authored', true),
  -- to-iu
  ('sent-ex-toiu-1', 'lang-ja', '桜という花を知っていますか。', 'さくら という はな お しって います か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-toiu-2', 'lang-ja', 'あれは何という店ですか。', 'あれ わ なん という みせ です か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-toiu-3', 'lang-ja', '花見という言葉を習いました。', 'はなみ という ことば お ならいました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-toiu-4', 'lang-ja', '兄が来ないという話を聞いた。', 'あに が こない という はなし お きいた。', 'lvl-ja-n4', 'authored', true),
  -- ka-dou-ka
  ('sent-ex-kadouka-1', 'lang-ja', '雨が降るかどうか分かりません。', 'あめ が ふる か どう か わかりません。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kadouka-2', 'lang-ja', '先生が来るかどうか聞いてください。', 'せんせい が くる か どう か きいて ください。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kadouka-3', 'lang-ja', '店が開いているかどうか分からない。', 'みせ が あいて いる か どう か わからない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kadouka-4', 'lang-ja', '正しいかどうか教えてください。', 'ただしい か どう か おしえて ください。', 'lvl-ja-n4', 'authored', true),
  -- te-ageru
  ('sent-ex-teageru-1', 'lang-ja', '妹に本を読んであげる。', 'いもうと に ほん お よんで あげる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teageru-2', 'lang-ja', '弟の宿題を手伝ってあげる。', 'おとうと の しゅくだい お てつだって あげる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teageru-3', 'lang-ja', '友達に写真を見せてあげる。', 'ともだち に しゃしん お みせて あげる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teageru-4', 'lang-ja', '母にお茶を作ってあげる。', 'はは に おちゃ お つくって あげる。', 'lvl-ja-n4', 'authored', true),
  -- te-kureru
  ('sent-ex-tekureru-1', 'lang-ja', '兄が駅まで送ってくれる。', 'あに が えき まで おくって くれる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tekureru-2', 'lang-ja', '友達が宿題を手伝ってくれる。', 'ともだち が しゅくだい お てつだって くれる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tekureru-3', 'lang-ja', '先生が漢字を教えてくれる。', 'せんせい が かんじ お おしえて くれる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tekureru-4', 'lang-ja', '母がケーキを作ってくれる。', 'はは が ケーキ お つくって くれる。', 'lvl-ja-n4', 'authored', true),
  -- te-morau
  ('sent-ex-temorau-1', 'lang-ja', '友達に写真を撮ってもらう。', 'ともだち に しゃしん お とって もらう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temorau-2', 'lang-ja', '先生に手紙を読んでもらう。', 'せんせい に てがみ お よんで もらう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temorau-3', 'lang-ja', '兄に車を運転してもらう。', 'あに に くるま お うんてん して もらう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temorau-4', 'lang-ja', '妹に部屋を掃除してもらう。', 'いもうと に へや お そうじ して もらう。', 'lvl-ja-n4', 'authored', true),
  -- te-oku
  ('sent-ex-teoku-1', 'lang-ja', '部屋を掃除しておく。', 'へや お そうじ して おく。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teoku-2', 'lang-ja', '会議の前に資料を読んでおく。', 'かいぎ の まえ に しりょう お よんで おく。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teoku-3', 'lang-ja', '窓を開けておいてください。', 'まど お あけて おいて ください。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teoku-4', 'lang-ja', '切符を買っておいてください。', 'きっぷ お かって おいて ください。', 'lvl-ja-n4', 'authored', true),
  -- te-shimau
  ('sent-ex-teshimau-1', 'lang-ja', '宿題を全部やってしまいました。', 'しゅくだい お ぜんぶ やって しまいました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teshimau-2', 'lang-ja', 'ケーキを全部食べてしまう。', 'ケーキ お ぜんぶ たべて しまう。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teshimau-3', 'lang-ja', '電車の中で寝てしまいました。', 'でんしゃ の なか で ねて しまいました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teshimau-4', 'lang-ja', '傘を忘れてしまいました。', 'かさ お わすれて しまいました。', 'lvl-ja-n4', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-kamo-1', 'sent-ex-kamo-1', 'en', 'It might rain tomorrow.', 'authored'),
  ('st-ex-kamo-2', 'sent-ex-kamo-2', 'en', 'The teacher might not come.', 'authored'),
  ('st-ex-kamo-3', 'sent-ex-kamo-3', 'en', 'The exam might be difficult.', 'authored'),
  ('st-ex-kamo-4', 'sent-ex-kamo-4', 'en', 'My older brother might have gone home already.', 'authored'),
  ('st-ex-darou-1', 'sent-ex-darou-1', 'en', 'It will probably be cold tomorrow.', 'authored'),
  ('st-ex-darou-2', 'sent-ex-darou-2', 'en', 'That shop is probably expensive.', 'authored'),
  ('st-ex-darou-3', 'sent-ex-darou-3', 'en', 'The teacher will probably be here soon.', 'authored'),
  ('st-ex-darou-4', 'sent-ex-darou-4', 'en', 'It will probably snow tonight.', 'authored'),
  ('st-ex-toomou-1', 'sent-ex-toomou-1', 'en', 'I think it will rain tomorrow.', 'authored'),
  ('st-ex-toomou-2', 'sent-ex-toomou-2', 'en', 'I think that film is interesting.', 'authored'),
  ('st-ex-toomou-3', 'sent-ex-toomou-3', 'en', 'I am thinking of going to Japan.', 'authored'),
  ('st-ex-toomou-4', 'sent-ex-toomou-4', 'en', 'I do not think the teacher is coming.', 'authored'),
  ('st-ex-toiu-1', 'sent-ex-toiu-1', 'en', 'Do you know a flower called sakura?', 'authored'),
  ('st-ex-toiu-2', 'sent-ex-toiu-2', 'en', 'What is that shop called?', 'authored'),
  ('st-ex-toiu-3', 'sent-ex-toiu-3', 'en', 'I learned the word hanami.', 'authored'),
  ('st-ex-toiu-4', 'sent-ex-toiu-4', 'en', 'I heard that my older brother is not coming.', 'authored'),
  ('st-ex-kadouka-1', 'sent-ex-kadouka-1', 'en', 'I do not know whether it will rain.', 'authored'),
  ('st-ex-kadouka-2', 'sent-ex-kadouka-2', 'en', 'Please ask whether the teacher is coming.', 'authored'),
  ('st-ex-kadouka-3', 'sent-ex-kadouka-3', 'en', 'I do not know whether the shop is open.', 'authored'),
  ('st-ex-kadouka-4', 'sent-ex-kadouka-4', 'en', 'Please tell me whether it is right.', 'authored'),
  ('st-ex-teageru-1', 'sent-ex-teageru-1', 'en', 'I read a book for my little sister.', 'authored'),
  ('st-ex-teageru-2', 'sent-ex-teageru-2', 'en', 'I help my little brother with his homework.', 'authored'),
  ('st-ex-teageru-3', 'sent-ex-teageru-3', 'en', 'I show my friend the photograph.', 'authored'),
  ('st-ex-teageru-4', 'sent-ex-teageru-4', 'en', 'I make tea for my mother.', 'authored'),
  ('st-ex-tekureru-1', 'sent-ex-tekureru-1', 'en', 'My older brother takes me to the station.', 'authored'),
  ('st-ex-tekureru-2', 'sent-ex-tekureru-2', 'en', 'My friend helps me with my homework.', 'authored'),
  ('st-ex-tekureru-3', 'sent-ex-tekureru-3', 'en', 'The teacher teaches me kanji.', 'authored'),
  ('st-ex-tekureru-4', 'sent-ex-tekureru-4', 'en', 'My mother makes a cake for me.', 'authored'),
  ('st-ex-temorau-1', 'sent-ex-temorau-1', 'en', 'I have my friend take a photograph.', 'authored'),
  ('st-ex-temorau-2', 'sent-ex-temorau-2', 'en', 'I have the teacher read the letter.', 'authored'),
  ('st-ex-temorau-3', 'sent-ex-temorau-3', 'en', 'I have my older brother drive the car.', 'authored'),
  ('st-ex-temorau-4', 'sent-ex-temorau-4', 'en', 'I get my little sister to clean the room.', 'authored'),
  ('st-ex-teoku-1', 'sent-ex-teoku-1', 'en', 'I clean the room in advance.', 'authored'),
  ('st-ex-teoku-2', 'sent-ex-teoku-2', 'en', 'I read the material before the meeting.', 'authored'),
  ('st-ex-teoku-3', 'sent-ex-teoku-3', 'en', 'Please leave the window open.', 'authored'),
  ('st-ex-teoku-4', 'sent-ex-teoku-4', 'en', 'Please buy the tickets in advance.', 'authored'),
  ('st-ex-teshimau-1', 'sent-ex-teshimau-1', 'en', 'I finished all my homework.', 'authored'),
  ('st-ex-teshimau-2', 'sent-ex-teshimau-2', 'en', 'I end up eating the whole cake.', 'authored'),
  ('st-ex-teshimau-3', 'sent-ex-teshimau-3', 'en', 'I fell asleep on the train.', 'authored'),
  ('st-ex-teshimau-4', 'sent-ex-teshimau-4', 'en', 'I went and forgot my umbrella.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('kamoshirenai', 'sent-ex-kamo-1', 0),
  ('kamoshirenai', 'sent-ex-kamo-2', 1),
  ('kamoshirenai', 'sent-ex-kamo-3', 2),
  ('kamoshirenai', 'sent-ex-kamo-4', 3),
  ('darou', 'sent-ex-darou-1', 0),
  ('darou', 'sent-ex-darou-2', 1),
  ('darou', 'sent-ex-darou-3', 2),
  ('darou', 'sent-ex-darou-4', 3),
  ('to-omou', 'sent-ex-toomou-1', 0),
  ('to-omou', 'sent-ex-toomou-2', 1),
  ('to-omou', 'sent-ex-toomou-3', 2),
  ('to-omou', 'sent-ex-toomou-4', 3),
  ('to-iu', 'sent-ex-toiu-1', 0),
  ('to-iu', 'sent-ex-toiu-2', 1),
  ('to-iu', 'sent-ex-toiu-3', 2),
  ('to-iu', 'sent-ex-toiu-4', 3),
  ('ka-dou-ka', 'sent-ex-kadouka-1', 0),
  ('ka-dou-ka', 'sent-ex-kadouka-2', 1),
  ('ka-dou-ka', 'sent-ex-kadouka-3', 2),
  ('ka-dou-ka', 'sent-ex-kadouka-4', 3),
  ('te-ageru', 'sent-ex-teageru-1', 0),
  ('te-ageru', 'sent-ex-teageru-2', 1),
  ('te-ageru', 'sent-ex-teageru-3', 2),
  ('te-ageru', 'sent-ex-teageru-4', 3),
  ('te-kureru', 'sent-ex-tekureru-1', 0),
  ('te-kureru', 'sent-ex-tekureru-2', 1),
  ('te-kureru', 'sent-ex-tekureru-3', 2),
  ('te-kureru', 'sent-ex-tekureru-4', 3),
  ('te-morau', 'sent-ex-temorau-1', 0),
  ('te-morau', 'sent-ex-temorau-2', 1),
  ('te-morau', 'sent-ex-temorau-3', 2),
  ('te-morau', 'sent-ex-temorau-4', 3),
  ('te-oku', 'sent-ex-teoku-1', 0),
  ('te-oku', 'sent-ex-teoku-2', 1),
  ('te-oku', 'sent-ex-teoku-3', 2),
  ('te-oku', 'sent-ex-teoku-4', 3),
  ('te-shimau', 'sent-ex-teshimau-1', 0),
  ('te-shimau', 'sent-ex-teshimau-2', 1),
  ('te-shimau', 'sent-ex-teshimau-3', 2),
  ('te-shimau', 'sent-ex-teshimau-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-kamo-1', 'sent-ex-kamo-2', 'sent-ex-kamo-3', 'sent-ex-kamo-4', 'sent-ex-darou-1', 'sent-ex-darou-2', 'sent-ex-darou-3', 'sent-ex-darou-4', 'sent-ex-toomou-1', 'sent-ex-toomou-2', 'sent-ex-toomou-3', 'sent-ex-toomou-4', 'sent-ex-toiu-1', 'sent-ex-toiu-2', 'sent-ex-toiu-3', 'sent-ex-toiu-4', 'sent-ex-kadouka-1', 'sent-ex-kadouka-2', 'sent-ex-kadouka-3', 'sent-ex-kadouka-4', 'sent-ex-teageru-1', 'sent-ex-teageru-2', 'sent-ex-teageru-3', 'sent-ex-teageru-4', 'sent-ex-tekureru-1', 'sent-ex-tekureru-2', 'sent-ex-tekureru-3', 'sent-ex-tekureru-4', 'sent-ex-temorau-1', 'sent-ex-temorau-2', 'sent-ex-temorau-3', 'sent-ex-temorau-4', 'sent-ex-teoku-1', 'sent-ex-teoku-2', 'sent-ex-teoku-3', 'sent-ex-teoku-4', 'sent-ex-teshimau-1', 'sent-ex-teshimau-2', 'sent-ex-teshimau-3', 'sent-ex-teshimau-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 2, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 4, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 5, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 6, 'も', 'も', NULL, 8, 9, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 7, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 8, 'れ', 'れ', NULL, 10, 11, '[{"t":"れ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 9, 'ません', 'ません', NULL, 11, 14, '[{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-1', 10, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-2', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-2', 2, '来ない', 'こない', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"来","r":"こ"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-2', 3, 'かもしれない', 'かもしれない', NULL, 6, 12, '[{"t":"かもしれない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-2', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 2, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 4, 'も', 'も', NULL, 7, 8, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 5, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 6, 'れ', 'れ', NULL, 9, 10, '[{"t":"れ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 7, 'ません', 'ません', NULL, 10, 13, '[{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-3', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-4', 2, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-4', 3, '帰った', 'かえった', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"帰","r":"かえ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-4', 4, 'かもしれない', 'かもしれない', NULL, 7, 13, '[{"t":"かもしれない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kamo-4', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-1', 2, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-1', 3, 'でしょう', 'でしょう', NULL, 5, 9, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-2', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-2', 3, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-2', 4, 'だろう', 'だろう', NULL, 6, 9, '[{"t":"だろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-3', 2, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-3', 3, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-3', 4, 'でしょう', 'でしょう', NULL, 7, 11, '[{"t":"でしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-4', 0, '今夜', 'こんや', (select id from words where primary_form = '今夜' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今夜","r":"こんや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-4', 2, '雪', 'ゆき', (select id from words where primary_form = '雪' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"雪","r":"ゆき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-4', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-4', 4, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-4', 5, 'だろう', 'だろう', NULL, 7, 10, '[{"t":"だろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darou-4', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 2, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 4, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 5, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 6, '思います', 'おもいます', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"思","r":"おも"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-1', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-2', 1, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-2', 3, '面白い', 'おもしろい', (select id from words where primary_form = '面白い' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-2', 4, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-2', 5, '思う', 'おもう', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"思","r":"おも"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-3', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-3', 1, 'へ', 'へ', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-3', 2, '行こう', 'いこう', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"行","r":"い"},{"t":"こう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-3', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-3', 4, '思います', 'おもいます', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"思","r":"おも"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-4', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-4', 2, '来ない', 'こない', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"来","r":"こ"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-4', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-4', 4, '思います', 'おもいます', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"思","r":"おも"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toomou-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 0, '桜', 'さくら', (select id from words where primary_form = '桜' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"桜","r":"さくら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 1, 'という', 'という', NULL, 1, 4, '[{"t":"という"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 2, '花', 'はな', (select id from words where primary_form = '花' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"花","r":"はな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 4, '知って', 'しって', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"知","r":"し"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 5, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 6, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-1', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 0, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 2, '何', 'なん', (select id from words where primary_form = '何' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"何","r":"なん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 3, 'という', 'という', NULL, 4, 7, '[{"t":"という"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 4, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 5, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 6, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-2', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-3', 0, '花見', 'はなみ', (select id from words where primary_form = '花見' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"花見","r":"はなみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-3', 1, 'という', 'という', NULL, 2, 5, '[{"t":"という"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-3', 2, '言葉', 'ことば', (select id from words where primary_form = '言葉' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"言葉","r":"ことば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-3', 3, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-3', 4, '習いました', 'ならいました', (select id from words where primary_form = '習う' and language_id = 'lang-ja' and published order by id limit 1), 8, 13, '[{"t":"習","r":"なら"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-3', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 2, '来ない', 'こない', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"来","r":"こ"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 3, 'という', 'という', NULL, 5, 8, '[{"t":"という"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 4, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 5, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 6, '聞いた', 'きいた', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"聞","r":"き"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiu-4', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-1', 2, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-1', 3, 'かどうか', 'かどうか', NULL, 4, 8, '[{"t":"かどうか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-1', 4, '分かりません', 'わかりません', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 8, 14, '[{"t":"分","r":"わ"},{"t":"かりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-1', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-2', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-2', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-2', 3, 'かどうか', 'かどうか', NULL, 5, 9, '[{"t":"かどうか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-2', 4, '聞いて', 'きいて', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"聞","r":"き"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-2', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-2', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-3', 0, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-3', 2, '開いて', 'あいて', (select id from words where primary_form = '開く' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"開","r":"あ"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-3', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-3', 4, 'かどうか', 'かどうか', NULL, 7, 11, '[{"t":"かどうか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-3', 5, '分からない', 'わからない', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 11, 16, '[{"t":"分","r":"わ"},{"t":"からない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-3', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-4', 0, '正しい', 'ただしい', (select id from words where primary_form = '正しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"正","r":"ただ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-4', 1, 'かどうか', 'かどうか', NULL, 3, 7, '[{"t":"かどうか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-4', 2, '教えて', 'おしえて', (select id from words where primary_form = '教える' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"教","r":"おし"},{"t":"えて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-4', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kadouka-4', 4, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-1', 0, '妹', 'いもうと', (select id from words where primary_form = '妹' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"妹","r":"いもうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-1', 2, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-1', 3, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-1', 4, '読んで', 'よんで', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-1', 5, 'あげる', 'あげる', NULL, 7, 10, '[{"t":"あげる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-1', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-2', 0, '弟', 'おとうと', (select id from words where primary_form = '弟' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"弟","r":"おとうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-2', 2, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-2', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-2', 4, '手伝って', 'てつだって', (select id from words where primary_form = '手伝う' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"手伝","r":"てつだ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-2', 5, 'あげる', 'あげる', NULL, 9, 12, '[{"t":"あげる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-3', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-3', 2, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-3', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-3', 4, '見せて', 'みせて', (select id from words where primary_form = '見せる' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"見","r":"み"},{"t":"せて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-3', 5, 'あげる', 'あげる', NULL, 9, 12, '[{"t":"あげる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-4', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-4', 2, 'お茶', 'おちゃ', (select id from words where primary_form = 'お茶' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"お"},{"t":"茶","r":"ちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-4', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-4', 4, '作って', 'つくって', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"作","r":"つく"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-4', 5, 'あげる', 'あげる', NULL, 8, 11, '[{"t":"あげる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teageru-4', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-1', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-1', 2, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-1', 3, 'まで', 'まで', NULL, 3, 5, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-1', 4, '送って', 'おくって', (select id from words where primary_form = '送る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"送","r":"おく"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-1', 5, 'くれる', 'くれる', NULL, 8, 11, '[{"t":"くれる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-2', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-2', 2, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-2', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-2', 4, '手伝って', 'てつだって', (select id from words where primary_form = '手伝う' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"手伝","r":"てつだ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-2', 5, 'くれる', 'くれる', NULL, 10, 13, '[{"t":"くれる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-3', 2, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-3', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-3', 4, '教えて', 'おしえて', (select id from words where primary_form = '教える' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"教","r":"おし"},{"t":"えて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-3', 5, 'くれる', 'くれる', NULL, 9, 12, '[{"t":"くれる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-4', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-4', 2, 'ケーキ', 'ケーキ', (select id from words where primary_form = 'ケーキ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"ケーキ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-4', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-4', 4, '作って', 'つくって', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"作","r":"つく"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-4', 5, 'くれる', 'くれる', NULL, 9, 12, '[{"t":"くれる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tekureru-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-1', 0, '友達', 'ともだち', (select id from words where primary_form = '友達' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友達","r":"ともだち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-1', 2, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-1', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-1', 4, '撮って', 'とって', (select id from words where primary_form = '撮る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"撮","r":"と"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-1', 5, 'もらう', 'もらう', NULL, 9, 12, '[{"t":"もらう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-2', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-2', 2, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-2', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-2', 4, '読んで', 'よんで', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-2', 5, 'もらう', 'もらう', NULL, 9, 12, '[{"t":"もらう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-3', 2, '車', 'くるま', (select id from words where primary_form = '車' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"車","r":"くるま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-3', 3, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-3', 4, '運転して', 'うんてんして', (select id from words where primary_form = '運転' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"運転","r":"うんてん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-3', 5, 'もらう', 'もらう', NULL, 8, 11, '[{"t":"もらう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-4', 0, '妹', 'いもうと', (select id from words where primary_form = '妹' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"妹","r":"いもうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-4', 2, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-4', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-4', 4, '掃除して', 'そうじして', (select id from words where primary_form = '掃除' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"掃除","r":"そうじ"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-4', 5, 'もらう', 'もらう', NULL, 9, 12, '[{"t":"もらう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temorau-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-1', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-1', 2, '掃除して', 'そうじして', (select id from words where primary_form = '掃除' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"掃除","r":"そうじ"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-1', 3, 'おく', 'おく', NULL, 7, 9, '[{"t":"おく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 2, '前に', 'まえに', NULL, 3, 5, '[{"t":"前","r":"まえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 3, '資料', 'しりょう', (select id from words where primary_form = '資料' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"資料","r":"しりょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 4, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 5, '読んで', 'よんで', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 6, 'おく', 'おく', NULL, 11, 13, '[{"t":"おく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-2', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-3', 0, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-3', 2, '開けて', 'あけて', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"開","r":"あ"},{"t":"けて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-3', 3, 'おい', 'おい', (select id from words where primary_form = 'おい' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"おい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-3', 4, 'て', 'て', NULL, 7, 8, '[{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-3', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-4', 0, '切符', 'きっぷ', (select id from words where primary_form = '切符' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"切符","r":"きっぷ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-4', 2, '買って', 'かって', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"買","r":"か"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-4', 3, 'おい', 'おい', (select id from words where primary_form = 'おい' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"おい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-4', 4, 'て', 'て', NULL, 8, 9, '[{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-4', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teoku-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 0, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 2, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 3, 'や', 'や', (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 4, 'って', 'って', (select id from words where primary_form = 'って' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 5, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 6, 'ま', 'ま', NULL, 9, 10, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 7, 'いました', 'いました', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-1', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-2', 0, 'ケーキ', 'ケーキ', (select id from words where primary_form = 'ケーキ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"ケーキ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-2', 1, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-2', 2, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-2', 3, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-2', 4, 'しまう', 'しまう', NULL, 9, 12, '[{"t":"しまう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-2', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 2, '中', 'なか', (select id from words where primary_form = '中' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"中","r":"なか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 4, '寝て', 'ねて', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"寝","r":"ね"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 5, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 6, 'ま', 'ま', NULL, 8, 9, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 7, 'いました', 'いました', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-3', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-4', 0, '傘', 'かさ', (select id from words where primary_form = '傘' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"傘","r":"かさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-4', 2, '忘れて', 'わすれて', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"忘","r":"わす"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-4', 3, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-4', 4, 'ま', 'ま', NULL, 6, 7, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-4', 5, 'いました', 'いました', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teshimau-4', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb);
