-- N4 example sentences, batch 4: trying things, purposes, and compound verbs.
--
-- 〜てみる, 〜ていく/〜てくる and 〜てある finish the て-auxiliaries batch 3
-- started. Then the four purpose-and-change patterns — ために, ように,
-- ようになる, ようにする — which sit close enough together that the examples
-- are written to contrast them: ように is what you aim at, ようになる is what
-- you can do now that you could not before, ようにする is a habit you keep.
-- Last, three things that attach to a verb stem: 〜やすい/〜にくい, 〜方, and
-- 〜始める/〜終わる/〜続ける.
--
-- Unlike batch 3's giving verbs, みる, いく, くる and ある all conjugate
-- cleanly here, so these sentences are not confined to plain form.
--
-- One rewording: 風邪をひかないように気をつけます came apart as 風邪 | を |
-- ひ | かな | いよう — ひく in kana has no entry, and the shrapnel then
-- swallowed the ように the topic is about. The teacher speaks in plain words
-- so the students understand instead.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- te-miru
  ('sent-ex-temiru-1', 'lang-ja', '新しい店に行ってみる。', 'あたらしい みせ に いって みる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temiru-2', 'lang-ja', '英語で手紙を書いてみる。', 'えいご で てがみ お かいて みる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temiru-3', 'lang-ja', 'あの映画を見てみる。', 'あの えいが お みて みる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temiru-4', 'lang-ja', '兄に聞いてみる。', 'あに に きいて みる。', 'lvl-ja-n4', 'authored', true),
  -- te-iku-kuru
  ('sent-ex-teikukuru-1', 'lang-ja', 'パンを買ってくる。', 'パン お かって くる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teikukuru-2', 'lang-ja', '傘を持っていく。', 'かさ お もって いく。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teikukuru-3', 'lang-ja', '駅まで走っていく。', 'えき まで はしって いく。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-teikukuru-4', 'lang-ja', '妹が家に帰ってくる。', 'いもうと が いえ に かえって くる。', 'lvl-ja-n4', 'authored', true),
  -- te-aru
  ('sent-ex-tearu-1', 'lang-ja', '窓が開けてある。', 'まど が あけて ある。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tearu-2', 'lang-ja', '机の上に本が置いてある。', 'つくえ の うえ に ほん が おいて ある。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tearu-3', 'lang-ja', '切符はもう買ってある。', 'きっぷ わ もう かって ある。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tearu-4', 'lang-ja', '部屋に花が飾ってある。', 'へや に はな が かざって ある。', 'lvl-ja-n4', 'authored', true),
  -- tame-ni
  ('sent-ex-tameni-1', 'lang-ja', '日本へ行くためにお金が必要です。', 'にほん え いく ため に おかね が ひつよう です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tameni-2', 'lang-ja', '試験のために勉強します。', 'しけん の ため に べんきょう します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tameni-3', 'lang-ja', '体のために野菜を食べる。', 'からだ の ため に やさい お たべる。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tameni-4', 'lang-ja', '家族のために働きます。', 'かぞく の ため に はたらきます。', 'lvl-ja-n4', 'authored', true),
  -- you-ni-purpose
  ('sent-ex-younimoku-1', 'lang-ja', '忘れないようにノートに書きます。', 'わすれない よう に ノート に かきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-younimoku-2', 'lang-ja', '見えるように前に座ります。', 'みえる よう に まえ に すわります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-younimoku-3', 'lang-ja', '間に合うように早く出ます。', 'まにあう よう に はやく でます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-younimoku-4', 'lang-ja', '学生が分かるように易しい言葉で話します。', 'がくせい が わかる よう に やさしい ことば で はなします。', 'lvl-ja-n4', 'authored', true),
  -- you-ni-naru
  ('sent-ex-youninaru-1', 'lang-ja', '漢字が読めるようになりました。', 'かんじ が よめる よう に なりました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youninaru-2', 'lang-ja', '海で泳げるようになった。', 'うみ で およげる よう に なった。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youninaru-3', 'lang-ja', '英語が話せるようになりたい。', 'えいご が はなせる よう に なりたい。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youninaru-4', 'lang-ja', '早く起きられるようになりました。', 'はやく おきられる よう に なりました。', 'lvl-ja-n4', 'authored', true),
  -- you-ni-suru
  ('sent-ex-younisuru-1', 'lang-ja', '毎日野菜を食べるようにしています。', 'まいにち やさい お たべる よう に して います。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-younisuru-2', 'lang-ja', '早く寝るようにする。', 'はやく ねる よう に する。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-younisuru-3', 'lang-ja', '会社に遅れないようにします。', 'かいしゃ に おくれない よう に します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-younisuru-4', 'lang-ja', '毎朝走るようにしています。', 'まいあさ はしる よう に して います。', 'lvl-ja-n4', 'authored', true),
  -- yasui-nikui
  ('sent-ex-yasuinikui-1', 'lang-ja', 'あの本は読みやすいです。', 'あの ほん わ よみやすい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-yasuinikui-2', 'lang-ja', 'あの漢字は書きにくい。', 'あの かんじ わ かきにくい。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-yasuinikui-3', 'lang-ja', '先生の話は分かりやすいです。', 'せんせい の はなし わ わかりやすい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-yasuinikui-4', 'lang-ja', '新しい靴は歩きにくい。', 'あたらしい くつ わ あるきにくい。', 'lvl-ja-n4', 'authored', true),
  -- kata
  ('sent-ex-kata-1', 'lang-ja', '漢字の書き方を教えてください。', 'かんじ の かきかた お おしえて ください。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kata-2', 'lang-ja', '料理の作り方が分かりません。', 'りょうり の つくりかた が わかりません。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kata-3', 'lang-ja', '使い方を習いました。', 'つかいかた お ならいました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kata-4', 'lang-ja', '名前の読み方が難しい。', 'なまえ の よみかた が むずかしい。', 'lvl-ja-n4', 'authored', true),
  -- hajimeru-owaru
  ('sent-ex-hajimeru-1', 'lang-ja', '雨が降り始めました。', 'あめ が ふりはじめました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-hajimeru-2', 'lang-ja', '本を読み終わりました。', 'ほん お よみおわりました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-hajimeru-3', 'lang-ja', '英語を習い続けています。', 'えいご お ならいつづけて います。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-hajimeru-4', 'lang-ja', '兄はピアノを弾き始めた。', 'あに わ ピアノ お ひきはじめた。', 'lvl-ja-n4', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-temiru-1', 'sent-ex-temiru-1', 'en', 'I will try going to the new shop.', 'authored'),
  ('st-ex-temiru-2', 'sent-ex-temiru-2', 'en', 'I will try writing the letter in English.', 'authored'),
  ('st-ex-temiru-3', 'sent-ex-temiru-3', 'en', 'I will give that film a try.', 'authored'),
  ('st-ex-temiru-4', 'sent-ex-temiru-4', 'en', 'I will try asking my older brother.', 'authored'),
  ('st-ex-teikukuru-1', 'sent-ex-teikukuru-1', 'en', 'I will go and buy some bread.', 'authored'),
  ('st-ex-teikukuru-2', 'sent-ex-teikukuru-2', 'en', 'I will take an umbrella with me.', 'authored'),
  ('st-ex-teikukuru-3', 'sent-ex-teikukuru-3', 'en', 'I will run to the station.', 'authored'),
  ('st-ex-teikukuru-4', 'sent-ex-teikukuru-4', 'en', 'My little sister is coming home.', 'authored'),
  ('st-ex-tearu-1', 'sent-ex-tearu-1', 'en', 'The window has been left open.', 'authored'),
  ('st-ex-tearu-2', 'sent-ex-tearu-2', 'en', 'A book has been placed on the desk.', 'authored'),
  ('st-ex-tearu-3', 'sent-ex-tearu-3', 'en', 'The tickets have already been bought.', 'authored'),
  ('st-ex-tearu-4', 'sent-ex-tearu-4', 'en', 'Flowers have been arranged in the room.', 'authored'),
  ('st-ex-tameni-1', 'sent-ex-tameni-1', 'en', 'I need money in order to go to Japan.', 'authored'),
  ('st-ex-tameni-2', 'sent-ex-tameni-2', 'en', 'I study for the exam.', 'authored'),
  ('st-ex-tameni-3', 'sent-ex-tameni-3', 'en', 'I eat vegetables for the sake of my health.', 'authored'),
  ('st-ex-tameni-4', 'sent-ex-tameni-4', 'en', 'I work for my family.', 'authored'),
  ('st-ex-younimoku-1', 'sent-ex-younimoku-1', 'en', 'I write it in my notebook so that I do not forget.', 'authored'),
  ('st-ex-younimoku-2', 'sent-ex-younimoku-2', 'en', 'I sit at the front so that I can see.', 'authored'),
  ('st-ex-younimoku-3', 'sent-ex-younimoku-3', 'en', 'I leave early so as to be on time.', 'authored'),
  ('st-ex-younimoku-4', 'sent-ex-younimoku-4', 'en', 'I speak in plain words so that the students understand.', 'authored'),
  ('st-ex-youninaru-1', 'sent-ex-youninaru-1', 'en', 'I have got to the point where I can read kanji.', 'authored'),
  ('st-ex-youninaru-2', 'sent-ex-youninaru-2', 'en', 'I became able to swim in the sea.', 'authored'),
  ('st-ex-youninaru-3', 'sent-ex-youninaru-3', 'en', 'I want to become able to speak English.', 'authored'),
  ('st-ex-youninaru-4', 'sent-ex-youninaru-4', 'en', 'I have become able to get up early.', 'authored'),
  ('st-ex-younisuru-1', 'sent-ex-younisuru-1', 'en', 'I make a point of eating vegetables every day.', 'authored'),
  ('st-ex-younisuru-2', 'sent-ex-younisuru-2', 'en', 'I will make a point of going to bed early.', 'authored'),
  ('st-ex-younisuru-3', 'sent-ex-younisuru-3', 'en', 'I make sure not to be late for work.', 'authored'),
  ('st-ex-younisuru-4', 'sent-ex-younisuru-4', 'en', 'I make a point of running every morning.', 'authored'),
  ('st-ex-yasuinikui-1', 'sent-ex-yasuinikui-1', 'en', 'That book is easy to read.', 'authored'),
  ('st-ex-yasuinikui-2', 'sent-ex-yasuinikui-2', 'en', 'That kanji is hard to write.', 'authored'),
  ('st-ex-yasuinikui-3', 'sent-ex-yasuinikui-3', 'en', 'The teacher''s explanations are easy to understand.', 'authored'),
  ('st-ex-yasuinikui-4', 'sent-ex-yasuinikui-4', 'en', 'New shoes are hard to walk in.', 'authored'),
  ('st-ex-kata-1', 'sent-ex-kata-1', 'en', 'Please teach me how to write kanji.', 'authored'),
  ('st-ex-kata-2', 'sent-ex-kata-2', 'en', 'I do not know how to make the dish.', 'authored'),
  ('st-ex-kata-3', 'sent-ex-kata-3', 'en', 'I learned how to use it.', 'authored'),
  ('st-ex-kata-4', 'sent-ex-kata-4', 'en', 'The way the name is read is difficult.', 'authored'),
  ('st-ex-hajimeru-1', 'sent-ex-hajimeru-1', 'en', 'It started raining.', 'authored'),
  ('st-ex-hajimeru-2', 'sent-ex-hajimeru-2', 'en', 'I finished reading the book.', 'authored'),
  ('st-ex-hajimeru-3', 'sent-ex-hajimeru-3', 'en', 'I have been going on learning English.', 'authored'),
  ('st-ex-hajimeru-4', 'sent-ex-hajimeru-4', 'en', 'My older brother started playing the piano.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('te-miru', 'sent-ex-temiru-1', 0),
  ('te-miru', 'sent-ex-temiru-2', 1),
  ('te-miru', 'sent-ex-temiru-3', 2),
  ('te-miru', 'sent-ex-temiru-4', 3),
  ('te-iku-kuru', 'sent-ex-teikukuru-1', 0),
  ('te-iku-kuru', 'sent-ex-teikukuru-2', 1),
  ('te-iku-kuru', 'sent-ex-teikukuru-3', 2),
  ('te-iku-kuru', 'sent-ex-teikukuru-4', 3),
  ('te-aru', 'sent-ex-tearu-1', 0),
  ('te-aru', 'sent-ex-tearu-2', 1),
  ('te-aru', 'sent-ex-tearu-3', 2),
  ('te-aru', 'sent-ex-tearu-4', 3),
  ('tame-ni', 'sent-ex-tameni-1', 0),
  ('tame-ni', 'sent-ex-tameni-2', 1),
  ('tame-ni', 'sent-ex-tameni-3', 2),
  ('tame-ni', 'sent-ex-tameni-4', 3),
  ('you-ni-purpose', 'sent-ex-younimoku-1', 0),
  ('you-ni-purpose', 'sent-ex-younimoku-2', 1),
  ('you-ni-purpose', 'sent-ex-younimoku-3', 2),
  ('you-ni-purpose', 'sent-ex-younimoku-4', 3),
  ('you-ni-naru', 'sent-ex-youninaru-1', 0),
  ('you-ni-naru', 'sent-ex-youninaru-2', 1),
  ('you-ni-naru', 'sent-ex-youninaru-3', 2),
  ('you-ni-naru', 'sent-ex-youninaru-4', 3),
  ('you-ni-suru', 'sent-ex-younisuru-1', 0),
  ('you-ni-suru', 'sent-ex-younisuru-2', 1),
  ('you-ni-suru', 'sent-ex-younisuru-3', 2),
  ('you-ni-suru', 'sent-ex-younisuru-4', 3),
  ('yasui-nikui', 'sent-ex-yasuinikui-1', 0),
  ('yasui-nikui', 'sent-ex-yasuinikui-2', 1),
  ('yasui-nikui', 'sent-ex-yasuinikui-3', 2),
  ('yasui-nikui', 'sent-ex-yasuinikui-4', 3),
  ('kata', 'sent-ex-kata-1', 0),
  ('kata', 'sent-ex-kata-2', 1),
  ('kata', 'sent-ex-kata-3', 2),
  ('kata', 'sent-ex-kata-4', 3),
  ('hajimeru-owaru', 'sent-ex-hajimeru-1', 0),
  ('hajimeru-owaru', 'sent-ex-hajimeru-2', 1),
  ('hajimeru-owaru', 'sent-ex-hajimeru-3', 2),
  ('hajimeru-owaru', 'sent-ex-hajimeru-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-temiru-1', 'sent-ex-temiru-2', 'sent-ex-temiru-3', 'sent-ex-temiru-4', 'sent-ex-teikukuru-1', 'sent-ex-teikukuru-2', 'sent-ex-teikukuru-3', 'sent-ex-teikukuru-4', 'sent-ex-tearu-1', 'sent-ex-tearu-2', 'sent-ex-tearu-3', 'sent-ex-tearu-4', 'sent-ex-tameni-1', 'sent-ex-tameni-2', 'sent-ex-tameni-3', 'sent-ex-tameni-4', 'sent-ex-younimoku-1', 'sent-ex-younimoku-2', 'sent-ex-younimoku-3', 'sent-ex-younimoku-4', 'sent-ex-youninaru-1', 'sent-ex-youninaru-2', 'sent-ex-youninaru-3', 'sent-ex-youninaru-4', 'sent-ex-younisuru-1', 'sent-ex-younisuru-2', 'sent-ex-younisuru-3', 'sent-ex-younisuru-4', 'sent-ex-yasuinikui-1', 'sent-ex-yasuinikui-2', 'sent-ex-yasuinikui-3', 'sent-ex-yasuinikui-4', 'sent-ex-kata-1', 'sent-ex-kata-2', 'sent-ex-kata-3', 'sent-ex-kata-4', 'sent-ex-hajimeru-1', 'sent-ex-hajimeru-2', 'sent-ex-hajimeru-3', 'sent-ex-hajimeru-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-temiru-1', 0, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-1', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-1', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-1', 3, '行って', 'いって', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"行","r":"い"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-1', 4, 'みる', 'みる', NULL, 8, 10, '[{"t":"みる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-2', 0, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-2', 2, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-2', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-2', 4, '書いて', 'かいて', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"書","r":"か"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-2', 5, 'みる', 'みる', NULL, 9, 11, '[{"t":"みる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-3', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-3', 1, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-3', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-3', 3, '見て', 'みて', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-3', 4, 'みる', 'みる', NULL, 7, 9, '[{"t":"みる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-4', 2, '聞いて', 'きいて', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"聞","r":"き"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-4', 3, 'みる', 'みる', NULL, 5, 7, '[{"t":"みる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temiru-4', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-1', 0, 'パン', 'パン', (select id from words where primary_form = 'パン' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"パン"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-1', 2, '買って', 'かって', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"買","r":"か"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-1', 3, 'くる', 'くる', NULL, 6, 8, '[{"t":"くる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-1', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-2', 0, '傘', 'かさ', (select id from words where primary_form = '傘' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"傘","r":"かさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-2', 2, '持って', 'もって', (select id from words where primary_form = '持つ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"持","r":"も"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-2', 3, 'いく', 'いく', NULL, 5, 7, '[{"t":"いく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-3', 0, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-3', 1, 'まで', 'まで', NULL, 1, 3, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-3', 2, '走って', 'はしって', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"走","r":"はし"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-3', 3, 'いく', 'いく', NULL, 6, 8, '[{"t":"いく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-4', 0, '妹', 'いもうと', (select id from words where primary_form = '妹' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"妹","r":"いもうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-4', 2, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-4', 4, '帰って', 'かえって', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"帰","r":"かえ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-4', 5, 'くる', 'くる', NULL, 7, 9, '[{"t":"くる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-teikukuru-4', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-1', 0, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-1', 2, '開けて', 'あけて', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"開","r":"あ"},{"t":"けて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-1', 3, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-1', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 0, '机', 'つくえ', (select id from words where primary_form = '机' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 2, '上に', 'うえに', NULL, 2, 4, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 3, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 4, 'が', 'が', NULL, 5, 6, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 5, '置いて', 'おいて', (select id from words where primary_form = '置く' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"置","r":"お"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 6, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-2', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-3', 0, '切符', 'きっぷ', (select id from words where primary_form = '切符' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"切符","r":"きっぷ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-3', 2, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-3', 3, '買って', 'かって', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"買","r":"か"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-3', 4, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-3', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-4', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-4', 2, '花', 'はな', (select id from words where primary_form = '花' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"花","r":"はな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-4', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-4', 4, '飾って', 'かざって', (select id from words where primary_form = '飾る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"飾","r":"かざ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-4', 5, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tearu-4', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 1, 'へ', 'へ', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 2, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 3, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 5, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 6, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 7, '必要', 'ひつよう', (select id from words where primary_form = '必要' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"必要","r":"ひつよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 8, 'です', 'です', NULL, 13, 15, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-1', 9, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-2', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-2', 2, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-2', 4, '勉強します', 'べんきょうします', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"勉強","r":"べんきょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 0, '体', 'からだ', (select id from words where primary_form = '体' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"体","r":"からだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 2, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 4, '野菜', 'やさい', (select id from words where primary_form = '野菜' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"野菜","r":"やさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 5, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 6, '食べる', 'たべる', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"食","r":"た"},{"t":"べる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-3', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-4', 0, '家族', 'かぞく', (select id from words where primary_form = '家族' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"家族","r":"かぞく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-4', 2, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-4', 4, '働きます', 'はたらきます', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"働","r":"はたら"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tameni-4', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-1', 0, '忘れない', 'わすれない', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"忘","r":"わす"},{"t":"れない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-1', 1, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-1', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-1', 3, 'ノート', 'ノート', (select id from words where primary_form = 'ノート' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"ノート"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-1', 5, '書きます', 'かきます', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"書","r":"か"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-1', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-2', 0, '見える', 'みえる', (select id from words where primary_form = '見える' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"見","r":"み"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-2', 1, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-2', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-2', 3, '前に', 'まえに', NULL, 6, 8, '[{"t":"前","r":"まえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-2', 4, '座ります', 'すわります', (select id from words where primary_form = '座る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"座","r":"すわ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-2', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-3', 0, '間に合う', 'まにあう', (select id from words where primary_form = '間に合う' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"間","r":"ま"},{"t":"に"},{"t":"合","r":"あ"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-3', 1, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-3', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-3', 3, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-3', 4, '出ます', 'でます', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"出","r":"で"},{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-3', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 2, '分かる', 'わかる', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"分","r":"わ"},{"t":"かる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 3, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 5, '易しい', 'やさしい', (select id from words where primary_form = '易しい' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"易","r":"やさ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 6, '言葉', 'ことば', (select id from words where primary_form = '言葉' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"言葉","r":"ことば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 7, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 8, '話します', 'はなします', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 15, 19, '[{"t":"話","r":"はな"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimoku-4', 9, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-1', 0, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-1', 2, '読める', 'よめる', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"読","r":"よ"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-1', 3, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-1', 5, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-2', 0, '海', 'うみ', (select id from words where primary_form = '海' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"海","r":"うみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-2', 2, '泳げる', 'およげる', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"泳","r":"およ"},{"t":"げる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-2', 3, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-2', 5, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-3', 0, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-3', 2, '話せる', 'はなせる', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"話","r":"はな"},{"t":"せる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-3', 3, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-3', 5, 'なりたい', 'なりたい', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"なりたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-4', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-4', 1, '起きられる', 'おきられる', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"起","r":"お"},{"t":"きられる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-4', 2, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-4', 4, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youninaru-4', 5, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 0, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 1, '野菜', 'やさい', (select id from words where primary_form = '野菜' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"野菜","r":"やさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 3, '食べる', 'たべる', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"食","r":"た"},{"t":"べる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 4, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 6, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 7, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-1', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-2', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-2', 1, '寝る', 'ねる', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"寝","r":"ね"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-2', 2, 'ようにする', 'ようにする', NULL, 4, 9, '[{"t":"ようにする"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-3', 0, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-3', 2, '遅れない', 'おくれない', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"遅","r":"おく"},{"t":"れない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-3', 3, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-3', 5, 'します', 'します', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-4', 0, '毎朝', 'まいあさ', (select id from words where primary_form = '毎朝' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎朝","r":"まいあさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-4', 1, '走る', 'はしる', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"走","r":"はし"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-4', 2, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-4', 4, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-4', 5, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younisuru-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-1', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-1', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-1', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-1', 3, '読み', 'よみ', (select id from words where primary_form = '読み' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"読","r":"よ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-1', 4, 'やすい', 'やすい', NULL, 6, 9, '[{"t":"やすい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-1', 5, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-2', 1, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-2', 3, '書きにくい', 'かきにくい', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"書","r":"か"},{"t":"きにくい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-2', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 2, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 4, '分', 'わ', (select id from words where primary_form = '分' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"分","r":"わ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 5, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 6, 'り', 'り', NULL, 7, 8, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 7, 'やすい', 'やすい', NULL, 8, 11, '[{"t":"やすい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 8, 'です', 'です', NULL, 11, 13, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-3', 9, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-4', 0, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-4', 1, '靴', 'くつ', (select id from words where primary_form = '靴' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-4', 3, '歩きにくい', 'あるきにくい', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"歩","r":"ある"},{"t":"きにくい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yasuinikui-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 0, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 2, '書き', 'かき', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"書","r":"か"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 3, '方', 'かた', (select id from words where primary_form = '方' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"方","r":"かた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 4, 'を', 'を', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 5, '教えて', 'おしえて', (select id from words where primary_form = '教える' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"教","r":"おし"},{"t":"えて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-1', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-2', 0, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-2', 2, '作り', 'つくり', (select id from words where primary_form = '作り' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"作","r":"つく"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-2', 3, '方', 'かた', (select id from words where primary_form = '方' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"方","r":"かた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-2', 4, 'が', 'が', NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-2', 5, '分かりません', 'わかりません', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 7, 13, '[{"t":"分","r":"わ"},{"t":"かりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-3', 0, '使い', 'つかい', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"使","r":"つか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-3', 1, '方', 'かた', (select id from words where primary_form = '方' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"方","r":"かた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-3', 2, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-3', 3, '習いました', 'ならいました', (select id from words where primary_form = '習う' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"習","r":"なら"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-4', 0, '名前', 'なまえ', (select id from words where primary_form = '名前' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"名前","r":"なまえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-4', 2, '読み', 'よみ', (select id from words where primary_form = '読み' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"読","r":"よ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-4', 3, '方', 'かた', (select id from words where primary_form = '方' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"方","r":"かた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-4', 4, 'が', 'が', NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-4', 5, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kata-4', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-1', 2, '降り', 'ふり', (select id from words where primary_form = '下り' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"降","r":"ふ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-1', 3, '始めました', 'はじめました', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"始","r":"はじ"},{"t":"めました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-2', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-2', 2, '読み', 'よみ', (select id from words where primary_form = '読み' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"読","r":"よ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-2', 3, '終わりました', 'おわりました', (select id from words where primary_form = '終わる' and language_id = 'lang-ja' and published order by id limit 1), 4, 10, '[{"t":"終","r":"お"},{"t":"わりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-2', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-3', 0, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-3', 2, '習い', 'ならい', (select id from words where primary_form = '習う' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"習","r":"なら"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-3', 3, '続けて', 'つづけて', (select id from words where primary_form = '続ける' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"続","r":"つづ"},{"t":"けて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-3', 4, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 2, 'ピアノ', 'ピアノ', (select id from words where primary_form = 'ピアノ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"ピアノ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 4, '弾', 'ひ', (select id from words where primary_form = '弾' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"弾","r":"ひ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 5, 'き', 'き', NULL, 7, 8, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 6, '始めた', 'はじめた', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"始","r":"はじ"},{"t":"めた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hajimeru-4', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb);
