-- N4 example sentences, batch 5: joining clauses, and placing them in time.
--
-- 〜のに, 〜けれど, 〜ても and 〜し are four ways to hang one clause off
-- another; 〜間に, 〜前に/〜後で and 〜まで/〜までに say when. Then the two
-- obligation shapes — 〜なくてもいい, which lets you off, and 〜なくちゃ/
-- 〜なきゃ, which does not — and 〜ばかり.
--
-- 〜なくてもいい also exists at N5, with its own four sentences (行かなくても
-- いいです and friends). These are written fresh rather than repeated, so a
-- learner who meets the topic twice does not see the same deck twice.
--
-- One rewording: いけない shreds to い|け|ない, so 宿題をしなくちゃいけない
-- became 今日は宿題をしなくちゃ — which is how the contraction is actually
-- used anyway, with the いけない left hanging.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- noni-although
  ('sent-ex-noni-1', 'lang-ja', '薬を飲んだのに、よくならない。', 'くすり お のんだ のに、よく ならない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-noni-2', 'lang-ja', '高いのに買いました。', 'たかい のに かいました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-noni-3', 'lang-ja', '雨が降っているのに出かけました。', 'あめ が ふって いる のに でかけました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-noni-4', 'lang-ja', '勉強したのに試験ができなかった。', 'べんきょう した のに しけん が できなかった。', 'lvl-ja-n4', 'authored', true),
  -- keredo
  ('sent-ex-keredo-1', 'lang-ja', '安いけれど、買いません。', 'やすい けれど、かいません。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-keredo-2', 'lang-ja', '行きたいけれど、時間がない。', 'いきたい けれど、じかん が ない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-keredo-3', 'lang-ja', '電話したけど、出なかった。', 'でんわ した けど、でなかった。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-keredo-4', 'lang-ja', '難しいけれど、面白いです。', 'むずかしい けれど、おもしろい です。', 'lvl-ja-n4', 'authored', true),
  -- temo
  ('sent-ex-temo-1', 'lang-ja', '雨が降っても行きます。', 'あめ が ふって も いきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temo-2', 'lang-ja', '高くても買います。', 'たかくて も かいます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temo-3', 'lang-ja', '先生に聞いても分からない。', 'せんせい に きいて も わからない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-temo-4', 'lang-ja', '薬を飲んでもよくならない。', 'くすり お のんで も よく ならない。', 'lvl-ja-n4', 'authored', true),
  -- shi
  ('sent-ex-shi-1', 'lang-ja', 'あの店は安いし、近いです。', 'あの みせ わ やすい し、ちかい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-shi-2', 'lang-ja', '雨が降っているし、寒いです。', 'あめ が ふって いる し、さむい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-shi-3', 'lang-ja', 'お金もないし、時間もない。', 'おかね も ない し、じかん も ない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-shi-4', 'lang-ja', '先生は優しいし、面白いです。', 'せんせい わ やさしい し、おもしろい です。', 'lvl-ja-n4', 'authored', true),
  -- aida-ni
  ('sent-ex-aidani-1', 'lang-ja', '母が寝ている間に掃除しました。', 'はは が ねて いる あいだ に そうじ しました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-aidani-2', 'lang-ja', '夏休みの間に日本へ行きます。', 'なつやすみ の あいだ に にほん え いきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-aidani-3', 'lang-ja', '兄がいない間に部屋を片付けます。', 'あに が いない あいだ に へや お かたづけます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-aidani-4', 'lang-ja', '電車に乗っている間に本を読みます。', 'でんしゃ に のって いる あいだ に ほん お よみます。', 'lvl-ja-n4', 'authored', true),
  -- mae-ni-ato-de
  ('sent-ex-maeato-1', 'lang-ja', '寝る前に歯を磨きます。', 'ねる まえ に は お みがきます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-maeato-2', 'lang-ja', 'ご飯を食べた後で薬を飲みます。', 'ごはん お たべた あと で くすり お のみます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-maeato-3', 'lang-ja', '出かける前に窓を閉めます。', 'でかける まえ に まど お しめます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-maeato-4', 'lang-ja', '会議の後で電話します。', 'かいぎ の あと で でんわ します。', 'lvl-ja-n4', 'authored', true),
  -- made-madeni
  ('sent-ex-made-1', 'lang-ja', '先生が来るまで待ちます。', 'せんせい が くる まで まちます。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-made-2', 'lang-ja', '明日までに宿題をします。', 'あした まで に しゅくだい お します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-made-3', 'lang-ja', '夜まで働きました。', 'よる まで はたらきました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-made-4', 'lang-ja', '来週までに返してください。', 'らいしゅう まで に かえして ください。', 'lvl-ja-n4', 'authored', true),
  -- nakutemo-ii
  ('sent-ex-nakutemon4-1', 'lang-ja', '今日は働かなくてもいいです。', 'きょう わ はたらかなくて も いい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nakutemon4-2', 'lang-ja', '傘を持たなくてもいい。', 'かさ お もたなくて も いい。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nakutemon4-3', 'lang-ja', '早く起きなくてもいいです。', 'はやく おきなくて も いい です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nakutemon4-4', 'lang-ja', '全部読まなくてもいい。', 'ぜんぶ よまなくて も いい。', 'lvl-ja-n4', 'authored', true),
  -- nakucha
  ('sent-ex-nakucha-1', 'lang-ja', 'もう帰らなくちゃ。', 'もう かえらなくちゃ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nakucha-2', 'lang-ja', '今日は宿題をしなくちゃ。', 'きょう わ しゅくだい お しなくちゃ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nakucha-3', 'lang-ja', '早く寝なきゃ。', 'はやく ねなきゃ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nakucha-4', 'lang-ja', '薬を飲まなきゃいけない。', 'くすり お のまなきゃ いけない。', 'lvl-ja-n4', 'authored', true),
  -- bakari
  ('sent-ex-bakari-1', 'lang-ja', '弟はゲームばかりしています。', 'おとうと わ ゲーム ばかり して います。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-bakari-2', 'lang-ja', '今起きたばかりです。', 'いま おきた ばかり です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-bakari-3', 'lang-ja', '日本に来たばかりです。', 'にほん に きた ばかり です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-bakari-4', 'lang-ja', '肉ばかり食べています。', 'にく ばかり たべて います。', 'lvl-ja-n4', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-noni-1', 'sent-ex-noni-1', 'en', 'I took the medicine and yet I am not getting better.', 'authored'),
  ('st-ex-noni-2', 'sent-ex-noni-2', 'en', 'I bought it even though it was expensive.', 'authored'),
  ('st-ex-noni-3', 'sent-ex-noni-3', 'en', 'I went out even though it was raining.', 'authored'),
  ('st-ex-noni-4', 'sent-ex-noni-4', 'en', 'I studied and yet I could not do the exam.', 'authored'),
  ('st-ex-keredo-1', 'sent-ex-keredo-1', 'en', 'It is cheap, but I am not buying it.', 'authored'),
  ('st-ex-keredo-2', 'sent-ex-keredo-2', 'en', 'I want to go, but I have no time.', 'authored'),
  ('st-ex-keredo-3', 'sent-ex-keredo-3', 'en', 'I rang, but nobody answered.', 'authored'),
  ('st-ex-keredo-4', 'sent-ex-keredo-4', 'en', 'It is difficult, but it is interesting.', 'authored'),
  ('st-ex-temo-1', 'sent-ex-temo-1', 'en', 'I will go even if it rains.', 'authored'),
  ('st-ex-temo-2', 'sent-ex-temo-2', 'en', 'I will buy it even if it is expensive.', 'authored'),
  ('st-ex-temo-3', 'sent-ex-temo-3', 'en', 'Even if I ask the teacher I do not understand.', 'authored'),
  ('st-ex-temo-4', 'sent-ex-temo-4', 'en', 'Even taking the medicine I do not get better.', 'authored'),
  ('st-ex-shi-1', 'sent-ex-shi-1', 'en', 'That shop is cheap, and it is close by.', 'authored'),
  ('st-ex-shi-2', 'sent-ex-shi-2', 'en', 'It is raining, and it is cold.', 'authored'),
  ('st-ex-shi-3', 'sent-ex-shi-3', 'en', 'I have no money, and I have no time either.', 'authored'),
  ('st-ex-shi-4', 'sent-ex-shi-4', 'en', 'The teacher is kind, and interesting too.', 'authored'),
  ('st-ex-aidani-1', 'sent-ex-aidani-1', 'en', 'I cleaned while my mother was asleep.', 'authored'),
  ('st-ex-aidani-2', 'sent-ex-aidani-2', 'en', 'I am going to Japan during the summer holidays.', 'authored'),
  ('st-ex-aidani-3', 'sent-ex-aidani-3', 'en', 'I tidy the room while my older brother is out.', 'authored'),
  ('st-ex-aidani-4', 'sent-ex-aidani-4', 'en', 'I read a book while I am on the train.', 'authored'),
  ('st-ex-maeato-1', 'sent-ex-maeato-1', 'en', 'I brush my teeth before going to bed.', 'authored'),
  ('st-ex-maeato-2', 'sent-ex-maeato-2', 'en', 'I take my medicine after eating.', 'authored'),
  ('st-ex-maeato-3', 'sent-ex-maeato-3', 'en', 'I shut the window before going out.', 'authored'),
  ('st-ex-maeato-4', 'sent-ex-maeato-4', 'en', 'I will ring after the meeting.', 'authored'),
  ('st-ex-made-1', 'sent-ex-made-1', 'en', 'I will wait until the teacher comes.', 'authored'),
  ('st-ex-made-2', 'sent-ex-made-2', 'en', 'I will do my homework by tomorrow.', 'authored'),
  ('st-ex-made-3', 'sent-ex-made-3', 'en', 'I worked until night.', 'authored'),
  ('st-ex-made-4', 'sent-ex-made-4', 'en', 'Please give it back by next week.', 'authored'),
  ('st-ex-nakutemon4-1', 'sent-ex-nakutemon4-1', 'en', 'You do not have to work today.', 'authored'),
  ('st-ex-nakutemon4-2', 'sent-ex-nakutemon4-2', 'en', 'You do not have to bring an umbrella.', 'authored'),
  ('st-ex-nakutemon4-3', 'sent-ex-nakutemon4-3', 'en', 'You do not have to get up early.', 'authored'),
  ('st-ex-nakutemon4-4', 'sent-ex-nakutemon4-4', 'en', 'You do not have to read all of it.', 'authored'),
  ('st-ex-nakucha-1', 'sent-ex-nakucha-1', 'en', 'I have got to go home now.', 'authored'),
  ('st-ex-nakucha-2', 'sent-ex-nakucha-2', 'en', 'I have to do my homework today.', 'authored'),
  ('st-ex-nakucha-3', 'sent-ex-nakucha-3', 'en', 'I have got to go to bed early.', 'authored'),
  ('st-ex-nakucha-4', 'sent-ex-nakucha-4', 'en', 'I have to take my medicine.', 'authored'),
  ('st-ex-bakari-1', 'sent-ex-bakari-1', 'en', 'My little brother does nothing but play games.', 'authored'),
  ('st-ex-bakari-2', 'sent-ex-bakari-2', 'en', 'I have only just got up.', 'authored'),
  ('st-ex-bakari-3', 'sent-ex-bakari-3', 'en', 'I have only just arrived in Japan.', 'authored'),
  ('st-ex-bakari-4', 'sent-ex-bakari-4', 'en', 'I eat nothing but meat.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('noni-although', 'sent-ex-noni-1', 0),
  ('noni-although', 'sent-ex-noni-2', 1),
  ('noni-although', 'sent-ex-noni-3', 2),
  ('noni-although', 'sent-ex-noni-4', 3),
  ('keredo', 'sent-ex-keredo-1', 0),
  ('keredo', 'sent-ex-keredo-2', 1),
  ('keredo', 'sent-ex-keredo-3', 2),
  ('keredo', 'sent-ex-keredo-4', 3),
  ('temo', 'sent-ex-temo-1', 0),
  ('temo', 'sent-ex-temo-2', 1),
  ('temo', 'sent-ex-temo-3', 2),
  ('temo', 'sent-ex-temo-4', 3),
  ('shi', 'sent-ex-shi-1', 0),
  ('shi', 'sent-ex-shi-2', 1),
  ('shi', 'sent-ex-shi-3', 2),
  ('shi', 'sent-ex-shi-4', 3),
  ('aida-ni', 'sent-ex-aidani-1', 0),
  ('aida-ni', 'sent-ex-aidani-2', 1),
  ('aida-ni', 'sent-ex-aidani-3', 2),
  ('aida-ni', 'sent-ex-aidani-4', 3),
  ('mae-ni-ato-de', 'sent-ex-maeato-1', 0),
  ('mae-ni-ato-de', 'sent-ex-maeato-2', 1),
  ('mae-ni-ato-de', 'sent-ex-maeato-3', 2),
  ('mae-ni-ato-de', 'sent-ex-maeato-4', 3),
  ('made-madeni', 'sent-ex-made-1', 0),
  ('made-madeni', 'sent-ex-made-2', 1),
  ('made-madeni', 'sent-ex-made-3', 2),
  ('made-madeni', 'sent-ex-made-4', 3),
  ('nakutemo-ii', 'sent-ex-nakutemon4-1', 0),
  ('nakutemo-ii', 'sent-ex-nakutemon4-2', 1),
  ('nakutemo-ii', 'sent-ex-nakutemon4-3', 2),
  ('nakutemo-ii', 'sent-ex-nakutemon4-4', 3),
  ('nakucha', 'sent-ex-nakucha-1', 0),
  ('nakucha', 'sent-ex-nakucha-2', 1),
  ('nakucha', 'sent-ex-nakucha-3', 2),
  ('nakucha', 'sent-ex-nakucha-4', 3),
  ('bakari', 'sent-ex-bakari-1', 0),
  ('bakari', 'sent-ex-bakari-2', 1),
  ('bakari', 'sent-ex-bakari-3', 2),
  ('bakari', 'sent-ex-bakari-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-noni-1', 'sent-ex-noni-2', 'sent-ex-noni-3', 'sent-ex-noni-4', 'sent-ex-keredo-1', 'sent-ex-keredo-2', 'sent-ex-keredo-3', 'sent-ex-keredo-4', 'sent-ex-temo-1', 'sent-ex-temo-2', 'sent-ex-temo-3', 'sent-ex-temo-4', 'sent-ex-shi-1', 'sent-ex-shi-2', 'sent-ex-shi-3', 'sent-ex-shi-4', 'sent-ex-aidani-1', 'sent-ex-aidani-2', 'sent-ex-aidani-3', 'sent-ex-aidani-4', 'sent-ex-maeato-1', 'sent-ex-maeato-2', 'sent-ex-maeato-3', 'sent-ex-maeato-4', 'sent-ex-made-1', 'sent-ex-made-2', 'sent-ex-made-3', 'sent-ex-made-4', 'sent-ex-nakutemon4-1', 'sent-ex-nakutemon4-2', 'sent-ex-nakutemon4-3', 'sent-ex-nakutemon4-4', 'sent-ex-nakucha-1', 'sent-ex-nakucha-2', 'sent-ex-nakucha-3', 'sent-ex-nakucha-4', 'sent-ex-bakari-1', 'sent-ex-bakari-2', 'sent-ex-bakari-3', 'sent-ex-bakari-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-noni-1', 0, '薬', 'くすり', (select id from words where primary_form = '薬' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"薬","r":"くすり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-1', 2, '飲んだ', 'のんだ', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"飲","r":"の"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-1', 3, 'のに', 'のに', NULL, 5, 7, '[{"t":"のに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-1', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-1', 5, 'よく', 'よく', NULL, 8, 10, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-1', 6, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-1', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-2', 0, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-2', 1, 'のに', 'のに', NULL, 2, 4, '[{"t":"のに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-2', 2, '買いました', 'かいました', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"買","r":"か"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-3', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-3', 2, '降って', 'ふって', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"降","r":"ふ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-3', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-3', 4, 'のに', 'のに', NULL, 7, 9, '[{"t":"のに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-3', 5, '出かけました', 'でかけました', (select id from words where primary_form = '出かける' and language_id = 'lang-ja' and published order by id limit 1), 9, 15, '[{"t":"出","r":"で"},{"t":"かけました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-3', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 0, '勉強した', 'べんきょうした', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"勉強","r":"べんきょう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 1, 'のに', 'のに', NULL, 4, 6, '[{"t":"のに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 2, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 3, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 5, 'き', 'き', NULL, 10, 11, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 6, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noni-4', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-1', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-1', 1, 'けれど', 'けれど', NULL, 2, 5, '[{"t":"けれど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-1', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-1', 3, '買いません', 'かいません', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"買","r":"か"},{"t":"いません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-1', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-2', 0, '行きたい', 'いきたい', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"行","r":"い"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-2', 1, 'けれど', 'けれど', NULL, 4, 7, '[{"t":"けれど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-2', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-2', 3, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-2', 4, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-2', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-3', 0, '電話した', 'でんわした', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"電話","r":"でんわ"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-3', 1, 'けど', 'けど', NULL, 4, 6, '[{"t":"けど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-3', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-3', 3, '出なかった', 'でなかった', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"出","r":"で"},{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-4', 0, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-4', 1, 'けれど', 'けれど', NULL, 3, 6, '[{"t":"けれど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-4', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-4', 3, '面白い', 'おもしろい', (select id from words where primary_form = '面白い' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-4', 4, 'です', 'です', NULL, 10, 12, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-keredo-4', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-1', 2, '降って', 'ふって', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"降","r":"ふ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-1', 3, 'も', 'も', NULL, 5, 6, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-1', 4, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-2', 0, '高くても', 'たかくても', (select id from words where primary_form = '高まる' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"高","r":"たか"},{"t":"くても"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-2', 1, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-2', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-3', 2, '聞いて', 'きいて', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"聞","r":"き"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-3', 3, 'も', 'も', NULL, 6, 7, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-3', 4, '分からない', 'わからない', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"分","r":"わ"},{"t":"からない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-3', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-4', 0, '薬', 'くすり', (select id from words where primary_form = '薬' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"薬","r":"くすり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-4', 2, '飲んで', 'のんで', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"飲","r":"の"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-4', 3, 'も', 'も', NULL, 5, 6, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-4', 4, 'よく', 'よく', NULL, 6, 8, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-4', 5, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-temo-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 3, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 4, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 5, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 6, '近い', 'ちかい', (select id from words where primary_form = '近い' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"近","r":"ちか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 7, 'です', 'です', NULL, 10, 12, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-1', 8, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 2, '降って', 'ふって', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"降","r":"ふ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 4, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 6, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 7, 'です', 'です', NULL, 11, 13, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-2', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 0, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 2, 'ないし', 'ないし', (select id from words where primary_form = '乃至' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"ないし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 4, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 5, 'も', 'も', NULL, 9, 10, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 6, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-3', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 2, '優しい', 'やさしい', (select id from words where primary_form = '優しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"優","r":"やさ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 3, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 5, '面白い', 'おもしろい', (select id from words where primary_form = '面白い' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 6, 'です', 'です', NULL, 11, 13, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shi-4', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-1', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-1', 2, '寝て', 'ねて', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"寝","r":"ね"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-1', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-1', 4, '間に', 'あいだに', NULL, 6, 8, '[{"t":"間","r":"あいだ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-1', 5, '掃除しました', 'そうじしました', (select id from words where primary_form = '掃除' and language_id = 'lang-ja' and published order by id limit 1), 8, 14, '[{"t":"掃除","r":"そうじ"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-2', 0, '夏休み', 'なつやすみ', (select id from words where primary_form = '夏休み' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"夏休","r":"なつやす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-2', 1, 'の', 'の', NULL, 3, 4, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-2', 2, '間に', 'あいだに', NULL, 4, 6, '[{"t":"間","r":"あいだ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-2', 3, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-2', 4, 'へ', 'へ', NULL, 8, 9, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-2', 5, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 2, 'いない', 'いない', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 3, '間に', 'あいだに', NULL, 5, 7, '[{"t":"間","r":"あいだ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 4, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 5, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 6, '片付けます', 'かたづけます', (select id from words where primary_form = '片付ける' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"片付","r":"かたづ"},{"t":"けます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-3', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 2, '乗って', 'のって', (select id from words where primary_form = '乗る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"乗","r":"の"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 4, '間に', 'あいだに', NULL, 8, 10, '[{"t":"間","r":"あいだ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 5, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 6, 'を', 'を', NULL, 11, 12, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 7, '読みます', 'よみます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"読","r":"よ"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-aidani-4', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-1', 0, '寝る', 'ねる', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"寝","r":"ね"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-1', 1, '前に', 'まえに', NULL, 2, 4, '[{"t":"前","r":"まえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-1', 2, '歯', 'は', (select id from words where primary_form = '歯' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"歯","r":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-1', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-1', 4, '磨きます', 'みがきます', (select id from words where primary_form = '磨く' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"磨","r":"みが"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 0, 'ご飯', 'ごはん', (select id from words where primary_form = 'ご飯' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 2, '食べた', 'たべた', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"食","r":"た"},{"t":"べた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 3, '後で', 'あとで', NULL, 6, 8, '[{"t":"後","r":"あと"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 4, '薬', 'くすり', (select id from words where primary_form = '薬' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"薬","r":"くすり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 5, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 6, '飲みます', 'のみます', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"飲","r":"の"},{"t":"みます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-2', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-3', 0, '出かける', 'でかける', (select id from words where primary_form = '出かける' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"出","r":"で"},{"t":"かける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-3', 1, '前に', 'まえに', NULL, 4, 6, '[{"t":"前","r":"まえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-3', 2, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-3', 3, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-3', 4, '閉めます', 'しめます', (select id from words where primary_form = '閉める' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"閉","r":"し"},{"t":"めます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-3', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-4', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-4', 2, '後で', 'あとで', NULL, 3, 5, '[{"t":"後","r":"あと"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-4', 3, '電話します', 'でんわします', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"電話","r":"でんわ"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-maeato-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-1', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-1', 3, 'まで', 'まで', NULL, 5, 7, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-1', 4, '待ちます', 'まちます', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"待","r":"ま"},{"t":"ちます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-2', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-2', 1, 'までに', 'までに', NULL, 2, 5, '[{"t":"までに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-2', 2, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-2', 3, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-2', 4, 'します', 'します', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-3', 0, '夜', 'よる', (select id from words where primary_form = '夜' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"夜","r":"よる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-3', 1, 'まで', 'まで', NULL, 1, 3, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-3', 2, '働きました', 'はたらきました', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"働","r":"はたら"},{"t":"きました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-4', 0, '来週', 'らいしゅう', (select id from words where primary_form = '来週' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"来週","r":"らいしゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-4', 1, 'までに', 'までに', NULL, 2, 5, '[{"t":"までに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-4', 2, '返して', 'かえして', (select id from words where primary_form = '返す' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"返","r":"かえ"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-4', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-made-4', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-1', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-1', 2, '働かなくてもいいです', 'はたらかなくてもいいです', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 3, 13, '[{"t":"働","r":"はたら"},{"t":"かなくてもいいです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-1', 3, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-2', 0, '傘', 'かさ', (select id from words where primary_form = '傘' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"傘","r":"かさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-2', 2, '持たなくてもいい', 'もたなくてもいい', (select id from words where primary_form = '持つ' and language_id = 'lang-ja' and published order by id limit 1), 2, 10, '[{"t":"持","r":"も"},{"t":"たなくてもいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-2', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-3', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-3', 1, '起きなくてもいいです', 'おきなくてもいいです', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 2, 12, '[{"t":"起","r":"お"},{"t":"きなくてもいいです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-3', 2, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-4', 0, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-4', 1, '読まなくてもいい', 'よまなくてもいい', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 10, '[{"t":"読","r":"よ"},{"t":"まなくてもいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakutemon4-4', 2, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-1', 0, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-1', 1, '帰らなくちゃ', 'かえらなくちゃ', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 2, 8, '[{"t":"帰","r":"かえ"},{"t":"らなくちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-1', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-2', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-2', 2, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-2', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-2', 4, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-2', 5, 'なくちゃ', 'なくちゃ', NULL, 7, 11, '[{"t":"なくちゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-3', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-3', 1, '寝なきゃ', 'ねなきゃ', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"寝","r":"ね"},{"t":"なきゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-3', 2, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-4', 0, '薬', 'くすり', (select id from words where primary_form = '薬' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"薬","r":"くすり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-4', 2, '飲まなきゃいけない', 'のまなきゃいけない', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 2, 11, '[{"t":"飲","r":"の"},{"t":"まなきゃいけない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakucha-4', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-1', 0, '弟', 'おとうと', (select id from words where primary_form = '弟' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"弟","r":"おとうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-1', 2, 'ゲーム', 'ゲーム', (select id from words where primary_form = 'ゲーム' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"ゲーム"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-1', 3, 'ばかり', 'ばかり', NULL, 5, 8, '[{"t":"ばかり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-1', 4, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-1', 5, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-1', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-2', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-2', 1, '起きた', 'おきた', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 1, 4, '[{"t":"起","r":"お"},{"t":"きた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-2', 2, 'ばかり', 'ばかり', NULL, 4, 7, '[{"t":"ばかり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-2', 3, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-3', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-3', 2, '来た', 'きた', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来","r":"き"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-3', 3, 'ばかり', 'ばかり', NULL, 5, 8, '[{"t":"ばかり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-3', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-3', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-4', 0, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-4', 1, 'ばかり', 'ばかり', NULL, 1, 4, '[{"t":"ばかり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-4', 2, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-4', 3, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakari-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb);
