-- N4 example sentences, batch 6: the last eleven topics, and the level is done.
--
-- 〜ところ and 〜場合, the two keigo shapes (お〜になる respectful, お〜する
-- humble), the imperative and its prohibition twin 〜な, 〜がる, こと/の as
-- nominalisers, 疑問詞 + か, 〜ようとする and 〜そうもない.
--
-- Two things the tokeniser dictated, both about what may sit in FRONT of a
-- word:
--
--   The honorific お is not a dictionary entry, so any particle immediately
--   before it makes a run of bare kana and the sentence is rejected —
--   新聞をお読みになります fails on を|お, 私がお持ちします on が|お. A real
--   word in that slot breaks the run, which is why every keigo sentence here
--   opens its polite verb after もう, 今日, 明日, 今, 駅まで or 後で rather
--   than after a particle.
--
--   行きたがっている shreds to 行き|た|が: 〜たがる stacks two suffixes the
--   index does not hold. The 〜がる examples use adjective stems — 欲しがる,
--   怖がる, 寒がる, 暑がる — which cut clean. 降ってきた lost き|た the same
--   way, so 〜ようとする reaches for 雨が降った instead.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- tokoro
  ('sent-ex-tokoro-1', 'lang-ja', '今から出かけるところです。', 'いま から でかける ところ です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tokoro-2', 'lang-ja', '今ご飯を食べているところです。', 'いま ごはん お たべて いる ところ です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tokoro-3', 'lang-ja', '今帰ってきたところです。', 'いま かえって きた ところ です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-tokoro-4', 'lang-ja', '会議が終わったところだ。', 'かいぎ が おわった ところ だ。', 'lvl-ja-n4', 'authored', true),
  -- baai
  ('sent-ex-baai-1', 'lang-ja', '雨の場合は中止です。', 'あめ の ばあい わ ちゅうし です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-baai-2', 'lang-ja', '遅れる場合は電話してください。', 'おくれる ばあい わ でんわ して ください。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-baai-3', 'lang-ja', '分からない場合は先生に聞いてください。', 'わからない ばあい わ せんせい に きいて ください。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-baai-4', 'lang-ja', '病気の場合は休んでください。', 'びょうき の ばあい わ やすんで ください。', 'lvl-ja-n4', 'authored', true),
  -- o-ni-naru
  ('sent-ex-oninaru-1', 'lang-ja', '先生はもうお帰りになりました。', 'せんせい わ もう おかえり に なりました。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-oninaru-2', 'lang-ja', '部長は今日お休みになります。', 'ぶちょう わ きょう おやすみ に なります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-oninaru-3', 'lang-ja', '社長は明日お出かけになります。', 'しゃちょう わ あした おでかけ に なります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-oninaru-4', 'lang-ja', '先生は今お着きになりました。', 'せんせい わ いま おつき に なりました。', 'lvl-ja-n4', 'authored', true),
  -- o-suru
  ('sent-ex-osuru-1', 'lang-ja', '明日お持ちします。', 'あした おもち します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-osuru-2', 'lang-ja', '駅までお送りします。', 'えき まで おおくり します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-osuru-3', 'lang-ja', '後でお電話します。', 'あと で おでんわ します。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-osuru-4', 'lang-ja', '先生にお聞きします。', 'せんせい に おきき します。', 'lvl-ja-n4', 'authored', true),
  -- meirei
  ('sent-ex-meirei-1', 'lang-ja', '早く来い。', 'はやく こい。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-meirei-2', 'lang-ja', '静かにしろ。', 'しずか に しろ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-meirei-3', 'lang-ja', '早く食べろ。', 'はやく たべろ。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-meirei-4', 'lang-ja', '本を読め。', 'ほん お よめ。', 'lvl-ja-n4', 'authored', true),
  -- kinshi-na
  ('sent-ex-kinshina-1', 'lang-ja', '部屋に入るな。', 'へや に はいる な。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kinshina-2', 'lang-ja', '肉ばかり食べるな。', 'にく ばかり たべる な。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kinshina-3', 'lang-ja', '窓を開けるな。', 'まど お あける な。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-kinshina-4', 'lang-ja', '電車の中で話すな。', 'でんしゃ の なか で はなす な。', 'lvl-ja-n4', 'authored', true),
  -- garu
  ('sent-ex-garu-1', 'lang-ja', '弟は新しい靴を欲しがっています。', 'おとうと わ あたらしい くつ お ほしがって います。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-garu-2', 'lang-ja', '妹は犬を怖がります。', 'いもうと わ いぬ お こわがります。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-garu-3', 'lang-ja', '子供は寒がっています。', 'こども わ さむがって います。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-garu-4', 'lang-ja', '兄は暑がります。', 'あに わ あつがります。', 'lvl-ja-n4', 'authored', true),
  -- nominalise
  ('sent-ex-nominal-1', 'lang-ja', '本を読むことが好きです。', 'ほん お よむ こと が すき です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nominal-2', 'lang-ja', '泳ぐのが好きです。', 'およぐ の が すき です。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nominal-3', 'lang-ja', '早く起きることは難しい。', 'はやく おきる こと わ むずかしい。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-nominal-4', 'lang-ja', '兄が来るのを待っています。', 'あに が くる の お まって います。', 'lvl-ja-n4', 'authored', true),
  -- gimonshi-ka
  ('sent-ex-gimonka-1', 'lang-ja', '誰か来ましたか。', 'だれか きました か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-gimonka-2', 'lang-ja', '何か食べましたか。', 'なにか たべました か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-gimonka-3', 'lang-ja', 'どこかへ行きましたか。', 'どこか え いきました か。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-gimonka-4', 'lang-ja', '誰かに聞いてください。', 'だれか に きいて ください。', 'lvl-ja-n4', 'authored', true),
  -- you-to-suru
  ('sent-ex-youtosuru-1', 'lang-ja', '出かけようとしたが、雨が降った。', 'でかけよう と した が、あめ が ふった。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youtosuru-2', 'lang-ja', '食べようとしたが、食べられなかった。', 'たべよう と した が、たべられなかった。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youtosuru-3', 'lang-ja', '兄は日本へ行こうとしています。', 'あに わ にほん え いこう と して います。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-youtosuru-4', 'lang-ja', '寝ようとしたら、電話が鳴った。', 'ねよう と したら、でんわ が なった。', 'lvl-ja-n4', 'authored', true),
  -- sou-mo-nai
  ('sent-ex-soumonai-1', 'lang-ja', '今日は間に合いそうもない。', 'きょう わ まにあいそう も ない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-soumonai-2', 'lang-ja', '会議は終わりそうもない。', 'かいぎ わ おわりそう も ない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-soumonai-3', 'lang-ja', '兄は来そうもない。', 'あに わ きそう も ない。', 'lvl-ja-n4', 'authored', true),
  ('sent-ex-soumonai-4', 'lang-ja', '本を読み終わりそうもない。', 'ほん お よみおわりそう も ない。', 'lvl-ja-n4', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-tokoro-1', 'sent-ex-tokoro-1', 'en', 'I am just about to go out.', 'authored'),
  ('st-ex-tokoro-2', 'sent-ex-tokoro-2', 'en', 'I am in the middle of eating.', 'authored'),
  ('st-ex-tokoro-3', 'sent-ex-tokoro-3', 'en', 'I have just got back.', 'authored'),
  ('st-ex-tokoro-4', 'sent-ex-tokoro-4', 'en', 'The meeting has only just finished.', 'authored'),
  ('st-ex-baai-1', 'sent-ex-baai-1', 'en', 'In the event of rain it is cancelled.', 'authored'),
  ('st-ex-baai-2', 'sent-ex-baai-2', 'en', 'If you are going to be late, please ring.', 'authored'),
  ('st-ex-baai-3', 'sent-ex-baai-3', 'en', 'If you do not understand, please ask the teacher.', 'authored'),
  ('st-ex-baai-4', 'sent-ex-baai-4', 'en', 'If you are ill, please stay off.', 'authored'),
  ('st-ex-oninaru-1', 'sent-ex-oninaru-1', 'en', 'The teacher has already gone home.', 'authored'),
  ('st-ex-oninaru-2', 'sent-ex-oninaru-2', 'en', 'The department head is taking today off.', 'authored'),
  ('st-ex-oninaru-3', 'sent-ex-oninaru-3', 'en', 'The company president is going out tomorrow.', 'authored'),
  ('st-ex-oninaru-4', 'sent-ex-oninaru-4', 'en', 'The teacher has just arrived.', 'authored'),
  ('st-ex-osuru-1', 'sent-ex-osuru-1', 'en', 'I will bring it tomorrow.', 'authored'),
  ('st-ex-osuru-2', 'sent-ex-osuru-2', 'en', 'I will see you as far as the station.', 'authored'),
  ('st-ex-osuru-3', 'sent-ex-osuru-3', 'en', 'I will ring you later.', 'authored'),
  ('st-ex-osuru-4', 'sent-ex-osuru-4', 'en', 'I will ask the teacher.', 'authored'),
  ('st-ex-meirei-1', 'sent-ex-meirei-1', 'en', 'Get over here.', 'authored'),
  ('st-ex-meirei-2', 'sent-ex-meirei-2', 'en', 'Be quiet.', 'authored'),
  ('st-ex-meirei-3', 'sent-ex-meirei-3', 'en', 'Eat up.', 'authored'),
  ('st-ex-meirei-4', 'sent-ex-meirei-4', 'en', 'Read the book.', 'authored'),
  ('st-ex-kinshina-1', 'sent-ex-kinshina-1', 'en', 'Do not go into the room.', 'authored'),
  ('st-ex-kinshina-2', 'sent-ex-kinshina-2', 'en', 'Do not eat nothing but meat.', 'authored'),
  ('st-ex-kinshina-3', 'sent-ex-kinshina-3', 'en', 'Do not open the window.', 'authored'),
  ('st-ex-kinshina-4', 'sent-ex-kinshina-4', 'en', 'Do not talk on the train.', 'authored'),
  ('st-ex-garu-1', 'sent-ex-garu-1', 'en', 'My little brother wants new shoes.', 'authored'),
  ('st-ex-garu-2', 'sent-ex-garu-2', 'en', 'My little sister is afraid of dogs.', 'authored'),
  ('st-ex-garu-3', 'sent-ex-garu-3', 'en', 'The children are feeling the cold.', 'authored'),
  ('st-ex-garu-4', 'sent-ex-garu-4', 'en', 'My older brother feels the heat.', 'authored'),
  ('st-ex-nominal-1', 'sent-ex-nominal-1', 'en', 'I like reading books.', 'authored'),
  ('st-ex-nominal-2', 'sent-ex-nominal-2', 'en', 'I like swimming.', 'authored'),
  ('st-ex-nominal-3', 'sent-ex-nominal-3', 'en', 'Getting up early is hard.', 'authored'),
  ('st-ex-nominal-4', 'sent-ex-nominal-4', 'en', 'I am waiting for my older brother to come.', 'authored'),
  ('st-ex-gimonka-1', 'sent-ex-gimonka-1', 'en', 'Did somebody come?', 'authored'),
  ('st-ex-gimonka-2', 'sent-ex-gimonka-2', 'en', 'Did you eat anything?', 'authored'),
  ('st-ex-gimonka-3', 'sent-ex-gimonka-3', 'en', 'Did you go anywhere?', 'authored'),
  ('st-ex-gimonka-4', 'sent-ex-gimonka-4', 'en', 'Please ask somebody.', 'authored'),
  ('st-ex-youtosuru-1', 'sent-ex-youtosuru-1', 'en', 'I was about to go out, and then it rained.', 'authored'),
  ('st-ex-youtosuru-2', 'sent-ex-youtosuru-2', 'en', 'I tried to eat it, but I could not.', 'authored'),
  ('st-ex-youtosuru-3', 'sent-ex-youtosuru-3', 'en', 'My older brother is trying to get to Japan.', 'authored'),
  ('st-ex-youtosuru-4', 'sent-ex-youtosuru-4', 'en', 'Just as I was dropping off to sleep, the phone rang.', 'authored'),
  ('st-ex-soumonai-1', 'sent-ex-soumonai-1', 'en', 'There is no sign of making it in time today.', 'authored'),
  ('st-ex-soumonai-2', 'sent-ex-soumonai-2', 'en', 'The meeting shows no sign of ending.', 'authored'),
  ('st-ex-soumonai-3', 'sent-ex-soumonai-3', 'en', 'My older brother does not look likely to come.', 'authored'),
  ('st-ex-soumonai-4', 'sent-ex-soumonai-4', 'en', 'I do not look like finishing the book.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('tokoro', 'sent-ex-tokoro-1', 0),
  ('tokoro', 'sent-ex-tokoro-2', 1),
  ('tokoro', 'sent-ex-tokoro-3', 2),
  ('tokoro', 'sent-ex-tokoro-4', 3),
  ('baai', 'sent-ex-baai-1', 0),
  ('baai', 'sent-ex-baai-2', 1),
  ('baai', 'sent-ex-baai-3', 2),
  ('baai', 'sent-ex-baai-4', 3),
  ('o-ni-naru', 'sent-ex-oninaru-1', 0),
  ('o-ni-naru', 'sent-ex-oninaru-2', 1),
  ('o-ni-naru', 'sent-ex-oninaru-3', 2),
  ('o-ni-naru', 'sent-ex-oninaru-4', 3),
  ('o-suru', 'sent-ex-osuru-1', 0),
  ('o-suru', 'sent-ex-osuru-2', 1),
  ('o-suru', 'sent-ex-osuru-3', 2),
  ('o-suru', 'sent-ex-osuru-4', 3),
  ('meirei', 'sent-ex-meirei-1', 0),
  ('meirei', 'sent-ex-meirei-2', 1),
  ('meirei', 'sent-ex-meirei-3', 2),
  ('meirei', 'sent-ex-meirei-4', 3),
  ('kinshi-na', 'sent-ex-kinshina-1', 0),
  ('kinshi-na', 'sent-ex-kinshina-2', 1),
  ('kinshi-na', 'sent-ex-kinshina-3', 2),
  ('kinshi-na', 'sent-ex-kinshina-4', 3),
  ('garu', 'sent-ex-garu-1', 0),
  ('garu', 'sent-ex-garu-2', 1),
  ('garu', 'sent-ex-garu-3', 2),
  ('garu', 'sent-ex-garu-4', 3),
  ('nominalise', 'sent-ex-nominal-1', 0),
  ('nominalise', 'sent-ex-nominal-2', 1),
  ('nominalise', 'sent-ex-nominal-3', 2),
  ('nominalise', 'sent-ex-nominal-4', 3),
  ('gimonshi-ka', 'sent-ex-gimonka-1', 0),
  ('gimonshi-ka', 'sent-ex-gimonka-2', 1),
  ('gimonshi-ka', 'sent-ex-gimonka-3', 2),
  ('gimonshi-ka', 'sent-ex-gimonka-4', 3),
  ('you-to-suru', 'sent-ex-youtosuru-1', 0),
  ('you-to-suru', 'sent-ex-youtosuru-2', 1),
  ('you-to-suru', 'sent-ex-youtosuru-3', 2),
  ('you-to-suru', 'sent-ex-youtosuru-4', 3),
  ('sou-mo-nai', 'sent-ex-soumonai-1', 0),
  ('sou-mo-nai', 'sent-ex-soumonai-2', 1),
  ('sou-mo-nai', 'sent-ex-soumonai-3', 2),
  ('sou-mo-nai', 'sent-ex-soumonai-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-tokoro-1', 'sent-ex-tokoro-2', 'sent-ex-tokoro-3', 'sent-ex-tokoro-4', 'sent-ex-baai-1', 'sent-ex-baai-2', 'sent-ex-baai-3', 'sent-ex-baai-4', 'sent-ex-oninaru-1', 'sent-ex-oninaru-2', 'sent-ex-oninaru-3', 'sent-ex-oninaru-4', 'sent-ex-osuru-1', 'sent-ex-osuru-2', 'sent-ex-osuru-3', 'sent-ex-osuru-4', 'sent-ex-meirei-1', 'sent-ex-meirei-2', 'sent-ex-meirei-3', 'sent-ex-meirei-4', 'sent-ex-kinshina-1', 'sent-ex-kinshina-2', 'sent-ex-kinshina-3', 'sent-ex-kinshina-4', 'sent-ex-garu-1', 'sent-ex-garu-2', 'sent-ex-garu-3', 'sent-ex-garu-4', 'sent-ex-nominal-1', 'sent-ex-nominal-2', 'sent-ex-nominal-3', 'sent-ex-nominal-4', 'sent-ex-gimonka-1', 'sent-ex-gimonka-2', 'sent-ex-gimonka-3', 'sent-ex-gimonka-4', 'sent-ex-youtosuru-1', 'sent-ex-youtosuru-2', 'sent-ex-youtosuru-3', 'sent-ex-youtosuru-4', 'sent-ex-soumonai-1', 'sent-ex-soumonai-2', 'sent-ex-soumonai-3', 'sent-ex-soumonai-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-tokoro-1', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-1', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-1', 2, '出かける', 'でかける', (select id from words where primary_form = '出かける' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"出","r":"で"},{"t":"かける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-1', 3, 'ところで', 'ところで', NULL, 7, 11, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-1', 4, 'す', 'す', NULL, 11, 12, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 1, 'ご飯', 'ごはん', (select id from words where primary_form = 'ご飯' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 2, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 3, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 4, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 5, 'ところで', 'ところで', NULL, 9, 13, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 6, 'す', 'す', NULL, 13, 14, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-2', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-3', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-3', 1, '帰って', 'かえって', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 1, 4, '[{"t":"帰","r":"かえ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-3', 2, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-3', 3, 'たところで', 'たところで', NULL, 5, 10, '[{"t":"たところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-3', 4, 'す', 'す', NULL, 10, 11, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-4', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-4', 2, '終わった', 'おわった', (select id from words where primary_form = '終わる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"終","r":"お"},{"t":"わった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-4', 3, 'ところだ', 'ところだ', NULL, 7, 11, '[{"t":"ところだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tokoro-4', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-1', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-1', 2, '場合', 'ばあい', (select id from words where primary_form = '場合' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"場合","r":"ばあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-1', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-1', 4, '中止', 'ちゅうし', (select id from words where primary_form = '中止' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"中止","r":"ちゅうし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-1', 5, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-1', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-2', 0, '遅れる', 'おくれる', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"遅","r":"おく"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-2', 1, '場合', 'ばあい', (select id from words where primary_form = '場合' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"場合","r":"ばあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-2', 3, '電話して', 'でんわして', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"電話","r":"でんわ"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-2', 4, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-2', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 0, '分からない', 'わからない', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"分","r":"わ"},{"t":"からない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 1, '場合', 'ばあい', (select id from words where primary_form = '場合' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"場合","r":"ばあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 3, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 5, '聞いて', 'きいて', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"聞","r":"き"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-3', 7, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-4', 0, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-4', 2, '場合', 'ばあい', (select id from words where primary_form = '場合' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"場合","r":"ばあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-4', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-4', 4, '休んで', 'やすんで', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"休","r":"やす"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-4', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-baai-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-1', 2, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-1', 3, 'お帰り', 'おかえり', (select id from words where primary_form = 'お帰り' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"お"},{"t":"帰","r":"かえ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-1', 5, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-2', 0, '部長', 'ぶちょう', (select id from words where primary_form = '部長' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部長","r":"ぶちょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-2', 2, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-2', 3, 'お休み', 'おやすみ', (select id from words where primary_form = 'お休み' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"お"},{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-2', 5, 'なります', 'なります', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"なります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-3', 0, '社長', 'しゃちょう', (select id from words where primary_form = '社長' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"社長","r":"しゃちょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-3', 2, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-3', 3, 'お出かけ', 'おでかけ', (select id from words where primary_form = 'お出かけ' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"お"},{"t":"出","r":"で"},{"t":"かけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-3', 5, 'なります', 'なります', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"なります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-3', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-4', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-4', 2, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-4', 3, 'お', 'お', NULL, 4, 5, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-4', 4, '着きになりました', 'つきになりました', (select id from words where primary_form = '着く' and language_id = 'lang-ja' and published order by id limit 1), 5, 13, '[{"t":"着","r":"つ"},{"t":"きになりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-oninaru-4', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-1', 1, 'お', 'お', NULL, 2, 3, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-1', 2, '持ちします', 'もちします', (select id from words where primary_form = '持つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"持","r":"も"},{"t":"ちします"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-2', 0, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-2', 1, 'まで', 'まで', NULL, 1, 3, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-2', 2, 'お', 'お', NULL, 3, 4, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-2', 3, '送りします', 'おくりします', (select id from words where primary_form = '送る' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"送","r":"おく"},{"t":"りします"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-3', 0, '後で', 'あとで', NULL, 0, 2, '[{"t":"後","r":"あと"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-3', 1, 'お', 'お', NULL, 2, 3, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-3', 2, '電話します', 'でんわします', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"電話","r":"でんわ"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-4', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-4', 2, 'お', 'お', NULL, 3, 4, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-4', 3, '聞きします', 'ききします', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"聞","r":"き"},{"t":"きします"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osuru-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-1', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-1', 1, '来い', 'こい', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"来","r":"こ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-1', 2, '。', '。', NULL, 4, 5, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-2', 0, '静か', 'しずか', (select id from words where primary_form = '静か' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"静","r":"しず"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-2', 2, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-2', 3, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-3', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-3', 1, '食べろ', 'たべろ', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"食","r":"た"},{"t":"べろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-3', 2, '。', '。', NULL, 5, 6, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-4', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-4', 2, '読め', 'よめ', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"読","r":"よ"},{"t":"め"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-meirei-4', 3, '。', '。', NULL, 4, 5, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-1', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-1', 2, '入る', 'はいる', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"入","r":"はい"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-1', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-1', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-2', 0, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-2', 1, 'ばかり', 'ばかり', NULL, 1, 4, '[{"t":"ばかり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-2', 2, '食べる', 'たべる', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"食","r":"た"},{"t":"べる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-2', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-3', 0, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-3', 2, '開ける', 'あける', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"開","r":"あ"},{"t":"ける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-3', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-3', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-4', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-4', 2, '中', 'なか', (select id from words where primary_form = '中' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"中","r":"なか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-4', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-4', 4, '話す', 'はなす', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"話","r":"はな"},{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-4', 5, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kinshina-4', 6, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 0, '弟', 'おとうと', (select id from words where primary_form = '弟' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"弟","r":"おとうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 2, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 3, '靴', 'くつ', (select id from words where primary_form = '靴' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 4, 'を', 'を', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 5, '欲', 'ほ', (select id from words where primary_form = '欲' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"欲","r":"ほ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 6, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 7, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 8, 'って', 'って', (select id from words where primary_form = 'って' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 9, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-1', 10, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-2', 0, '妹', 'いもうと', (select id from words where primary_form = '妹' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"妹","r":"いもうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-2', 2, '犬', 'いぬ', (select id from words where primary_form = '犬' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"犬","r":"いぬ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-2', 3, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-2', 4, '怖がります', 'こわがります', (select id from words where primary_form = '恐れる' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"怖","r":"こわ"},{"t":"がります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-3', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-3', 2, '寒がっています', 'さむがっています', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 3, 10, '[{"t":"寒","r":"さむ"},{"t":"がっています"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-3', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-4', 2, '暑がります', 'あつがります', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"暑","r":"あつ"},{"t":"がります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-garu-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 2, '読む', 'よむ', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"読","r":"よ"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 3, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 4, 'が', 'が', NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 5, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 6, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-1', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-2', 0, '泳ぐ', 'およぐ', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"泳","r":"およ"},{"t":"ぐ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-2', 2, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-2', 3, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-2', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-2', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-3', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-3', 1, '起きる', 'おきる', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"起","r":"お"},{"t":"きる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-3', 2, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-3', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-3', 4, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 4, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 5, '待って', 'まって', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"待","r":"ま"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 6, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nominal-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-1', 0, '誰か', 'だれか', (select id from words where primary_form = '誰か' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"誰","r":"だれ"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-1', 1, '来ました', 'きました', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"来","r":"き"},{"t":"ました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-1', 2, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-2', 0, '何か', 'なにか', (select id from words where primary_form = '何か' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"何","r":"なに"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-2', 1, '食べました', 'たべました', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"食","r":"た"},{"t":"べました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-2', 2, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-3', 0, 'どこか', 'どこか', NULL, 0, 3, '[{"t":"どこか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-3', 1, 'へ', 'へ', NULL, 3, 4, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-3', 2, '行きました', 'いきました', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"行","r":"い"},{"t":"きました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-3', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-4', 0, '誰か', 'だれか', (select id from words where primary_form = '誰か' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"誰","r":"だれ"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-4', 2, '聞いて', 'きいて', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"聞","r":"き"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-4', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimonka-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 0, '出かけよう', 'でかけよう', (select id from words where primary_form = '出かける' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"出","r":"で"},{"t":"かけよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 2, 'した', 'した', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 3, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 5, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 6, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 7, '降った', 'ふった', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"降","r":"ふ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-1', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-2', 0, '食べよう', 'たべよう', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"食","r":"た"},{"t":"べよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-2', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-2', 2, 'した', 'した', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-2', 3, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-2', 5, '食べられなかった', 'たべられなかった', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 9, 17, '[{"t":"食","r":"た"},{"t":"べられなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-2', 6, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 2, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 3, 'へ', 'へ', NULL, 4, 5, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 4, '行こう', 'いこう', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"行","r":"い"},{"t":"こう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 5, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 6, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 7, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-3', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 0, '寝よう', 'ねよう', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"寝","r":"ね"},{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 2, 'したら', 'したら', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"したら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 4, '電話', 'でんわ', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 5, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 6, '鳴った', 'なった', (select id from words where primary_form = '鳴る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"鳴","r":"な"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youtosuru-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-1', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-1', 2, '間に', 'まに', NULL, 3, 5, '[{"t":"間","r":"ま"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-1', 3, '合いそうもない', 'あいそうもない', (select id from words where primary_form = '合う' and language_id = 'lang-ja' and published order by id limit 1), 5, 12, '[{"t":"合","r":"あ"},{"t":"いそうもない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-1', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-2', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-2', 2, '終わり', 'おわり', (select id from words where primary_form = '終わり' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"終","r":"お"},{"t":"わり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-2', 3, 'そうもない', 'そうもない', NULL, 6, 11, '[{"t":"そうもない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-3', 2, '来', 'き', (select id from words where primary_form = '来' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"来","r":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-3', 3, 'そうもない', 'そうもない', NULL, 3, 8, '[{"t":"そうもない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-4', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-4', 2, '読み', 'よみ', (select id from words where primary_form = '読み' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"読","r":"よ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-4', 3, '終わり', 'おわり', (select id from words where primary_form = '終わり' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"終","r":"お"},{"t":"わり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-4', 4, 'そうもない', 'そうもない', NULL, 7, 12, '[{"t":"そうもない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-soumonai-4', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb);
