-- N3 example sentences, batch 1: obligation, denial, and habits.
--
-- N3 opens where N4 left off and turns the screw. 〜べき says what ought to
-- happen; 〜はずがない denies that something could; 〜わけだ draws the
-- conclusion and 〜わけではない refuses to draw the whole of it. Then 〜ものだ
-- for the way things are and the way they were, the ことにする / ことになる
-- pair — a decision you made against one that was made for you — 〜たところだ,
-- 〜うちに and 〜たびに.
--
-- 〜たところだ also exists at N4 as 〜ところ, with 今帰ってきたところです and
-- friends; the N3 sentences are written fresh rather than repeated.
--
-- One rewording: 十年住んでいたから… warned on 十|年, two single kanji the
-- index does not hold as a compound and which would have shipped as two
-- word-order chips asking a reader to assemble "ten years" a character at a
-- time. 長く住んでいた says it without the number.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- beki
  ('sent-ex-beki-1', 'lang-ja', '約束は守るべきです。', 'やくそく わ まもる べき です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-beki-2', 'lang-ja', 'もっと勉強するべきだ。', 'もっと べんきょう する べき だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-beki-3', 'lang-ja', '先生に相談するべきです。', 'せんせい に そうだん する べき です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-beki-4', 'lang-ja', '熱があるなら医者に行くべきだ。', 'ねつ が ある なら いしゃ に いく べき だ。', 'lvl-ja-n3', 'authored', true),
  -- hazu-ga-nai
  ('sent-ex-hazuganai-1', 'lang-ja', '先生が知らないはずがない。', 'せんせい が しらない はず が ない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-hazuganai-2', 'lang-ja', 'あの店が休みのはずがない。', 'あの みせ が やすみ の はず が ない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-hazuganai-3', 'lang-ja', '兄が約束を忘れるはずがない。', 'あに が やくそく お わすれる はず が ない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-hazuganai-4', 'lang-ja', '毎日練習した彼が負けるはずがない。', 'まいにち れんしゅう した かれ が まける はず が ない。', 'lvl-ja-n3', 'authored', true),
  -- wake
  ('sent-ex-wakeda-1', 'lang-ja', '毎日練習したから、上手になったわけだ。', 'まいにち れんしゅう した から、じょうず に なった わけ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-wakeda-2', 'lang-ja', '長く住んでいたから、日本の生活に慣れているわけだ。', 'ながく すんで いた から、にほん の せいかつ に なれて いる わけ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-wakeda-3', 'lang-ja', '電車が止まったから、遅れたわけだ。', 'でんしゃ が とまった から、おくれた わけ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-wakeda-4', 'lang-ja', '雪が降ったから、寒いわけだ。', 'ゆき が ふった から、さむい わけ だ。', 'lvl-ja-n3', 'authored', true),
  -- wake-dewa-nai
  ('sent-ex-wakedewa-1', 'lang-ja', '嫌いなわけではない。', 'きらい な わけ で わ ない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-wakedewa-2', 'lang-ja', '全部分かるわけではありません。', 'ぜんぶ わかる わけ で わ ありません。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-wakedewa-3', 'lang-ja', '毎日行くわけではない。', 'まいにち いく わけ で わ ない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-wakedewa-4', 'lang-ja', '高いから買わないわけではありません。', 'たかい から かわない わけ で わ ありません。', 'lvl-ja-n3', 'authored', true),
  -- mono-da
  ('sent-ex-monoda-1', 'lang-ja', '子供の時、よく川で泳いだものだ。', 'こども の とき、よく かわ で およいだ もの だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-monoda-2', 'lang-ja', '時間が経つのは早いものだ。', 'じかん が たつ の わ はやい もの だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-monoda-3', 'lang-ja', '親の言うことは聞くものだ。', 'おや の いう こと わ きく もの だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-monoda-4', 'lang-ja', '昔はよく本を読んだものだ。', 'むかし わ よく ほん お よんだ もの だ。', 'lvl-ja-n3', 'authored', true),
  -- koto-ni-suru
  ('sent-ex-kotonisuru-1', 'lang-ja', '毎朝走ることにしました。', 'まいあさ はしる こと に しました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kotonisuru-2', 'lang-ja', '毎日日記を書くことにした。', 'まいにち にっき お かく こと に した。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kotonisuru-3', 'lang-ja', '来年日本へ行くことにします。', 'らいねん にほん え いく こと に します。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kotonisuru-4', 'lang-ja', '甘いものを食べないことにしている。', 'あまい もの お たべない こと に して いる。', 'lvl-ja-n3', 'authored', true),
  -- koto-ni-naru
  ('sent-ex-kotoninaru-1', 'lang-ja', '来月から新しい会社で働くことになりました。', 'らいげつ から あたらしい かいしゃ で はたらく こと に なりました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kotoninaru-2', 'lang-ja', '試験は来週行うことになりました。', 'しけん わ らいしゅう おこなう こと に なりました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kotoninaru-3', 'lang-ja', '兄が結婚することになりました。', 'あに が けっこん する こと に なりました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kotoninaru-4', 'lang-ja', '明日から店を閉めることになった。', 'あした から みせ お しめる こと に なった。', 'lvl-ja-n3', 'authored', true),
  -- tokoro-da
  ('sent-ex-tatokoroda-1', 'lang-ja', '今、駅に着いたところだ。', 'いま、えき に ついた ところ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tatokoroda-2', 'lang-ja', 'バスが出たところです。', 'バス が でた ところ です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tatokoroda-3', 'lang-ja', '先生と話したところです。', 'せんせい と はなした ところ です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tatokoroda-4', 'lang-ja', '母に電話したところだ。', 'はは に でんわ した ところ だ。', 'lvl-ja-n3', 'authored', true),
  -- uchi-ni
  ('sent-ex-uchini-1', 'lang-ja', '若いうちに外国へ行きたい。', 'わかい うち に がいこく え いきたい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-uchini-2', 'lang-ja', '明るいうちに帰りましょう。', 'あかるい うち に かえりましょう。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-uchini-3', 'lang-ja', '忘れないうちにメモします。', 'わすれない うち に メモ します。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-uchini-4', 'lang-ja', '熱いうちに食べてください。', 'あつい うち に たべて ください。', 'lvl-ja-n3', 'authored', true),
  -- tabi-ni
  ('sent-ex-tabini-1', 'lang-ja', 'あの写真を見るたびに、子供の時を思い出す。', 'あの しゃしん お みる たび に、こども の とき お おもいだす。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tabini-2', 'lang-ja', '日本へ行くたびに、お土産を買います。', 'にほん え いく たび に、おみやげ お かいます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tabini-3', 'lang-ja', '兄に会うたびに、背が高くなる。', 'あに に あう たび に、せ が たかく なる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tabini-4', 'lang-ja', '雨が降るたびに、道が悪くなる。', 'あめ が ふる たび に、みち が わるく なる。', 'lvl-ja-n3', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-beki-1', 'sent-ex-beki-1', 'en', 'You ought to keep your promises.', 'authored'),
  ('st-ex-beki-2', 'sent-ex-beki-2', 'en', 'I should study more.', 'authored'),
  ('st-ex-beki-3', 'sent-ex-beki-3', 'en', 'You ought to talk it over with the teacher.', 'authored'),
  ('st-ex-beki-4', 'sent-ex-beki-4', 'en', 'If you have a temperature you ought to see a doctor.', 'authored'),
  ('st-ex-hazuganai-1', 'sent-ex-hazuganai-1', 'en', 'There is no way the teacher does not know.', 'authored'),
  ('st-ex-hazuganai-2', 'sent-ex-hazuganai-2', 'en', 'That shop cannot possibly be closed.', 'authored'),
  ('st-ex-hazuganai-3', 'sent-ex-hazuganai-3', 'en', 'There is no way my older brother would forget a promise.', 'authored'),
  ('st-ex-hazuganai-4', 'sent-ex-hazuganai-4', 'en', 'He practised every day; there is no way he loses.', 'authored'),
  ('st-ex-wakeda-1', 'sent-ex-wakeda-1', 'en', 'He practised every day, so of course he got good at it.', 'authored'),
  ('st-ex-wakeda-2', 'sent-ex-wakeda-2', 'en', 'He lived there a long time, so naturally he is used to life in Japan.', 'authored'),
  ('st-ex-wakeda-3', 'sent-ex-wakeda-3', 'en', 'The train stopped, so that is why we were late.', 'authored'),
  ('st-ex-wakeda-4', 'sent-ex-wakeda-4', 'en', 'It snowed, so no wonder it is cold.', 'authored'),
  ('st-ex-wakedewa-1', 'sent-ex-wakedewa-1', 'en', 'It is not that I dislike it.', 'authored'),
  ('st-ex-wakedewa-2', 'sent-ex-wakedewa-2', 'en', 'It is not as if I understand all of it.', 'authored'),
  ('st-ex-wakedewa-3', 'sent-ex-wakedewa-3', 'en', 'It is not that I go every day.', 'authored'),
  ('st-ex-wakedewa-4', 'sent-ex-wakedewa-4', 'en', 'It is not that I am refusing to buy it because it is expensive.', 'authored'),
  ('st-ex-monoda-1', 'sent-ex-monoda-1', 'en', 'When I was a child I used to swim in the river a lot.', 'authored'),
  ('st-ex-monoda-2', 'sent-ex-monoda-2', 'en', 'How quickly time passes.', 'authored'),
  ('st-ex-monoda-3', 'sent-ex-monoda-3', 'en', 'You should listen to what your parents tell you.', 'authored'),
  ('st-ex-monoda-4', 'sent-ex-monoda-4', 'en', 'I used to read a lot of books in the old days.', 'authored'),
  ('st-ex-kotonisuru-1', 'sent-ex-kotonisuru-1', 'en', 'I have decided to run every morning.', 'authored'),
  ('st-ex-kotonisuru-2', 'sent-ex-kotonisuru-2', 'en', 'I decided to keep a diary every day.', 'authored'),
  ('st-ex-kotonisuru-3', 'sent-ex-kotonisuru-3', 'en', 'I have decided to go to Japan next year.', 'authored'),
  ('st-ex-kotonisuru-4', 'sent-ex-kotonisuru-4', 'en', 'I make it a rule not to eat sweet things.', 'authored'),
  ('st-ex-kotoninaru-1', 'sent-ex-kotoninaru-1', 'en', 'It has been arranged that I will work at a new company from next month.', 'authored'),
  ('st-ex-kotoninaru-2', 'sent-ex-kotoninaru-2', 'en', 'It has been decided that the exam will be held next week.', 'authored'),
  ('st-ex-kotoninaru-3', 'sent-ex-kotoninaru-3', 'en', 'It has been settled that my older brother is getting married.', 'authored'),
  ('st-ex-kotoninaru-4', 'sent-ex-kotoninaru-4', 'en', 'It has been decided that the shop closes from tomorrow.', 'authored'),
  ('st-ex-tatokoroda-1', 'sent-ex-tatokoroda-1', 'en', 'I have just this minute arrived at the station.', 'authored'),
  ('st-ex-tatokoroda-2', 'sent-ex-tatokoroda-2', 'en', 'The bus has just left.', 'authored'),
  ('st-ex-tatokoroda-3', 'sent-ex-tatokoroda-3', 'en', 'I have just been speaking to the teacher.', 'authored'),
  ('st-ex-tatokoroda-4', 'sent-ex-tatokoroda-4', 'en', 'I have just rung my mother.', 'authored'),
  ('st-ex-uchini-1', 'sent-ex-uchini-1', 'en', 'I want to go abroad while I am still young.', 'authored'),
  ('st-ex-uchini-2', 'sent-ex-uchini-2', 'en', 'Let us go home while it is still light.', 'authored'),
  ('st-ex-uchini-3', 'sent-ex-uchini-3', 'en', 'I will make a note of it before I forget.', 'authored'),
  ('st-ex-uchini-4', 'sent-ex-uchini-4', 'en', 'Please eat it while it is hot.', 'authored'),
  ('st-ex-tabini-1', 'sent-ex-tabini-1', 'en', 'Every time I look at that photograph I remember my childhood.', 'authored'),
  ('st-ex-tabini-2', 'sent-ex-tabini-2', 'en', 'Every time I go to Japan I buy souvenirs.', 'authored'),
  ('st-ex-tabini-3', 'sent-ex-tabini-3', 'en', 'Every time I meet my older brother he is taller.', 'authored'),
  ('st-ex-tabini-4', 'sent-ex-tabini-4', 'en', 'Every time it rains the road gets worse.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('beki', 'sent-ex-beki-1', 0),
  ('beki', 'sent-ex-beki-2', 1),
  ('beki', 'sent-ex-beki-3', 2),
  ('beki', 'sent-ex-beki-4', 3),
  ('hazu-ga-nai', 'sent-ex-hazuganai-1', 0),
  ('hazu-ga-nai', 'sent-ex-hazuganai-2', 1),
  ('hazu-ga-nai', 'sent-ex-hazuganai-3', 2),
  ('hazu-ga-nai', 'sent-ex-hazuganai-4', 3),
  ('wake', 'sent-ex-wakeda-1', 0),
  ('wake', 'sent-ex-wakeda-2', 1),
  ('wake', 'sent-ex-wakeda-3', 2),
  ('wake', 'sent-ex-wakeda-4', 3),
  ('wake-dewa-nai', 'sent-ex-wakedewa-1', 0),
  ('wake-dewa-nai', 'sent-ex-wakedewa-2', 1),
  ('wake-dewa-nai', 'sent-ex-wakedewa-3', 2),
  ('wake-dewa-nai', 'sent-ex-wakedewa-4', 3),
  ('mono-da', 'sent-ex-monoda-1', 0),
  ('mono-da', 'sent-ex-monoda-2', 1),
  ('mono-da', 'sent-ex-monoda-3', 2),
  ('mono-da', 'sent-ex-monoda-4', 3),
  ('koto-ni-suru', 'sent-ex-kotonisuru-1', 0),
  ('koto-ni-suru', 'sent-ex-kotonisuru-2', 1),
  ('koto-ni-suru', 'sent-ex-kotonisuru-3', 2),
  ('koto-ni-suru', 'sent-ex-kotonisuru-4', 3),
  ('koto-ni-naru', 'sent-ex-kotoninaru-1', 0),
  ('koto-ni-naru', 'sent-ex-kotoninaru-2', 1),
  ('koto-ni-naru', 'sent-ex-kotoninaru-3', 2),
  ('koto-ni-naru', 'sent-ex-kotoninaru-4', 3),
  ('tokoro-da', 'sent-ex-tatokoroda-1', 0),
  ('tokoro-da', 'sent-ex-tatokoroda-2', 1),
  ('tokoro-da', 'sent-ex-tatokoroda-3', 2),
  ('tokoro-da', 'sent-ex-tatokoroda-4', 3),
  ('uchi-ni', 'sent-ex-uchini-1', 0),
  ('uchi-ni', 'sent-ex-uchini-2', 1),
  ('uchi-ni', 'sent-ex-uchini-3', 2),
  ('uchi-ni', 'sent-ex-uchini-4', 3),
  ('tabi-ni', 'sent-ex-tabini-1', 0),
  ('tabi-ni', 'sent-ex-tabini-2', 1),
  ('tabi-ni', 'sent-ex-tabini-3', 2),
  ('tabi-ni', 'sent-ex-tabini-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-beki-1', 'sent-ex-beki-2', 'sent-ex-beki-3', 'sent-ex-beki-4', 'sent-ex-hazuganai-1', 'sent-ex-hazuganai-2', 'sent-ex-hazuganai-3', 'sent-ex-hazuganai-4', 'sent-ex-wakeda-1', 'sent-ex-wakeda-2', 'sent-ex-wakeda-3', 'sent-ex-wakeda-4', 'sent-ex-wakedewa-1', 'sent-ex-wakedewa-2', 'sent-ex-wakedewa-3', 'sent-ex-wakedewa-4', 'sent-ex-monoda-1', 'sent-ex-monoda-2', 'sent-ex-monoda-3', 'sent-ex-monoda-4', 'sent-ex-kotonisuru-1', 'sent-ex-kotonisuru-2', 'sent-ex-kotonisuru-3', 'sent-ex-kotonisuru-4', 'sent-ex-kotoninaru-1', 'sent-ex-kotoninaru-2', 'sent-ex-kotoninaru-3', 'sent-ex-kotoninaru-4', 'sent-ex-tatokoroda-1', 'sent-ex-tatokoroda-2', 'sent-ex-tatokoroda-3', 'sent-ex-tatokoroda-4', 'sent-ex-uchini-1', 'sent-ex-uchini-2', 'sent-ex-uchini-3', 'sent-ex-uchini-4', 'sent-ex-tabini-1', 'sent-ex-tabini-2', 'sent-ex-tabini-3', 'sent-ex-tabini-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-beki-1', 0, '約束', 'やくそく', (select id from words where primary_form = '約束' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"約束","r":"やくそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-1', 2, '守る', 'まもる', (select id from words where primary_form = '守る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"守","r":"まも"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-1', 3, 'べき', 'べき', NULL, 5, 7, '[{"t":"べき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-1', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-2', 0, 'もっと', 'もっと', (select id from words where primary_form = 'もっと' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-2', 1, '勉強する', 'べんきょうする', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"勉強","r":"べんきょう"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-2', 2, 'べき', 'べき', NULL, 7, 9, '[{"t":"べき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-2', 3, 'だ', 'だ', NULL, 9, 10, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-2', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-3', 2, '相談する', 'そうだんする', (select id from words where primary_form = '相談' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"相談","r":"そうだん"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-3', 3, 'べき', 'べき', NULL, 7, 9, '[{"t":"べき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-3', 4, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 0, '熱', 'ねつ', (select id from words where primary_form = '熱' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"熱","r":"ねつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 2, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 3, 'なら', 'なら', NULL, 4, 6, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 4, '医者', 'いしゃ', (select id from words where primary_form = '医者' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"医者","r":"いしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 6, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 7, 'べき', 'べき', NULL, 11, 13, '[{"t":"べき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 8, 'だ', 'だ', NULL, 13, 14, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beki-4', 9, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-1', 2, '知らない', 'しらない', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"知","r":"し"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-1', 3, 'はずがない', 'はずがない', NULL, 7, 12, '[{"t":"はずがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-1', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-2', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-2', 2, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-2', 3, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-2', 4, 'の', 'の', NULL, 6, 7, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-2', 5, 'はずがない', 'はずがない', NULL, 7, 12, '[{"t":"はずがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-3', 2, '約束', 'やくそく', (select id from words where primary_form = '約束' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"約束","r":"やくそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-3', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-3', 4, '忘れる', 'わすれる', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"忘","r":"わす"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-3', 5, 'はずがない', 'はずがない', NULL, 8, 13, '[{"t":"はずがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-4', 0, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-4', 1, '練習した', 'れんしゅうした', (select id from words where primary_form = '練習' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"練習","r":"れんしゅう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-4', 2, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-4', 3, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-4', 4, '負ける', 'まける', (select id from words where primary_form = '負ける' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"負","r":"ま"},{"t":"ける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-4', 5, 'はずがない', 'はずがない', NULL, 11, 16, '[{"t":"はずがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazuganai-4', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 0, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 1, '練習した', 'れんしゅうした', (select id from words where primary_form = '練習' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"練習","r":"れんしゅう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 2, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 4, '上手', 'じょうず', (select id from words where primary_form = '上手' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"上手","r":"じょうず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 6, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 7, 'わけだ', 'わけだ', NULL, 15, 18, '[{"t":"わけだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-1', 8, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 0, '長く', 'ながく', (select id from words where primary_form = '常しえ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"長","r":"なが"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 1, '住んで', 'すんで', (select id from words where primary_form = '住む' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"住","r":"す"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 2, 'いた', 'いた', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 3, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 5, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 6, 'の', 'の', NULL, 12, 13, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 7, '生活', 'せいかつ', (select id from words where primary_form = '生活' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"生活","r":"せいかつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 8, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 15, 16, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 9, '慣れて', 'なれて', (select id from words where primary_form = '慣れる' and language_id = 'lang-ja' and published order by id limit 1), 16, 19, '[{"t":"慣","r":"な"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 10, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 19, 21, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 11, 'わけだ', 'わけだ', NULL, 21, 24, '[{"t":"わけだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-2', 12, '。', '。', NULL, 24, 25, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 2, '止まった', 'とまった', (select id from words where primary_form = '止まる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"止","r":"と"},{"t":"まった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 3, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 5, '遅れた', 'おくれた', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"遅","r":"おく"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 6, 'わけだ', 'わけだ', NULL, 13, 16, '[{"t":"わけだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-3', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 0, '雪', 'ゆき', (select id from words where primary_form = '雪' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雪","r":"ゆき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 2, '降った', 'ふった', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"降","r":"ふ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 3, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 5, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 6, 'わけだ', 'わけだ', NULL, 10, 13, '[{"t":"わけだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakeda-4', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-1', 0, '嫌い', 'きらい', (select id from words where primary_form = '嫌い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"嫌","r":"きら"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-1', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-1', 2, 'わけではない', 'わけではない', NULL, 3, 9, '[{"t":"わけではない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-1', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-2', 0, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-2', 1, '分かる', 'わかる', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"分","r":"わ"},{"t":"かる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-2', 2, 'わ', 'わ', (select id from words where primary_form = 'わ' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"わ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-2', 3, 'け', 'け', NULL, 6, 7, '[{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-2', 4, 'では', 'では', (select id from words where primary_form = 'では' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"では"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-2', 5, 'ありません', 'ありません', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"ありません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-3', 0, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-3', 1, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-3', 2, 'わけではない', 'わけではない', NULL, 4, 10, '[{"t":"わけではない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-3', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 0, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 2, '買わない', 'かわない', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"買","r":"か"},{"t":"わない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 3, 'わ', 'わ', (select id from words where primary_form = 'わ' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"わ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 4, 'け', 'け', NULL, 9, 10, '[{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 5, 'では', 'では', (select id from words where primary_form = 'では' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"では"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 6, 'ありません', 'ありません', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 12, 17, '[{"t":"ありません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wakedewa-4', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 2, '時', 'とき', (select id from words where primary_form = '時' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"時","r":"とき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 3, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 4, 'よく', 'よく', NULL, 5, 7, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 5, '川', 'かわ', (select id from words where primary_form = '川' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"川","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 6, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 7, '泳いだ', 'およいだ', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"泳","r":"およ"},{"t":"いだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 8, 'ものだ', 'ものだ', NULL, 12, 15, '[{"t":"ものだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-1', 9, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 0, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 2, '経つ', 'たつ', (select id from words where primary_form = '経つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"経","r":"た"},{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 3, 'の', 'の', NULL, 5, 6, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 5, '早い', 'はやい', (select id from words where primary_form = '早い' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"早","r":"はや"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 6, 'ものだ', 'ものだ', NULL, 9, 12, '[{"t":"ものだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-2', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 0, '親', 'おや', (select id from words where primary_form = '親' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"親","r":"おや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 2, '言う', 'いう', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"言","r":"い"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 3, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 5, '聞く', 'きく', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"聞","r":"き"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 6, 'ものだ', 'ものだ', NULL, 9, 12, '[{"t":"ものだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-3', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 0, '昔', 'むかし', (select id from words where primary_form = '昔' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"昔","r":"むかし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 2, 'よく', 'よく', NULL, 2, 4, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 3, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 4, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 5, '読んだ', 'よんだ', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"読","r":"よ"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 6, 'ものだ', 'ものだ', NULL, 9, 12, '[{"t":"ものだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monoda-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-1', 0, '毎朝', 'まいあさ', (select id from words where primary_form = '毎朝' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎朝","r":"まいあさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-1', 1, '走る', 'はしる', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"走","r":"はし"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-1', 2, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-1', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-1', 4, 'しました', 'しました', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 0, '毎日', 'まいにち', (select id from words where primary_form = '毎日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"毎日","r":"まいにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 1, '日記', 'にっき', (select id from words where primary_form = '日記' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"日記","r":"にっき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 3, '書く', 'かく', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"書","r":"か"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 4, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 6, 'した', 'した', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-2', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 0, '来年', 'らいねん', (select id from words where primary_form = '来年' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"来年","r":"らいねん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 1, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 2, 'へ', 'へ', NULL, 4, 5, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 3, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 4, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 6, 'します', 'します', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-3', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 0, '甘い', 'あまい', (select id from words where primary_form = '甘い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"甘","r":"あま"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 1, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 3, '食べない', 'たべない', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"食","r":"た"},{"t":"べない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 4, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 6, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 7, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonisuru-4', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 0, '来月', 'らいげつ', (select id from words where primary_form = '来月' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"来月","r":"らいげつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 2, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 3, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 5, '働く', 'はたらく', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"働","r":"はたら"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 6, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 7, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 8, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 15, 20, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-1', 9, '。', '。', NULL, 20, 21, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 2, '来週', 'らいしゅう', (select id from words where primary_form = '来週' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来週","r":"らいしゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 3, '行う', 'おこなう', (select id from words where primary_form = '行う' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"行","r":"おこな"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 4, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 6, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-3', 2, '結婚する', 'けっこんする', (select id from words where primary_form = '結婚' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"結婚","r":"けっこん"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-3', 3, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-3', 5, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-3', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 2, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 4, '閉める', 'しめる', (select id from words where primary_form = '閉める' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"閉","r":"し"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 5, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 6, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 7, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotoninaru-4', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-1', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-1', 1, '、', '、', NULL, 1, 2, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-1', 2, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-1', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-1', 4, '着いた', 'ついた', (select id from words where primary_form = '着く' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"着","r":"つ"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-1', 5, 'ところだ', 'ところだ', NULL, 7, 11, '[{"t":"ところだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-2', 0, 'バス', 'バス', (select id from words where primary_form = 'バス' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"バス"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-2', 2, '出た', 'でた', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"出","r":"で"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-2', 3, 'ところで', 'ところで', NULL, 5, 9, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-2', 4, 'す', 'す', NULL, 9, 10, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-2', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-3', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-3', 2, '話した', 'はなした', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"話","r":"はな"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-3', 3, 'ところで', 'ところで', NULL, 6, 10, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-3', 4, 'す', 'す', NULL, 10, 11, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-4', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-4', 2, '電話した', 'でんわした', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"電話","r":"でんわ"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-4', 3, 'ところだ', 'ところだ', NULL, 6, 10, '[{"t":"ところだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokoroda-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-1', 0, '若い', 'わかい', (select id from words where primary_form = '若い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"若","r":"わか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-1', 1, 'うち', 'うち', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"うち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-1', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-1', 3, '外国', 'がいこく', (select id from words where primary_form = '外国' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"外国","r":"がいこく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-1', 4, 'へ', 'へ', NULL, 7, 8, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-1', 5, '行きたい', 'いきたい', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"行","r":"い"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-2', 0, '明るい', 'あかるい', (select id from words where primary_form = '明るい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"明","r":"あか"},{"t":"るい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-2', 1, 'うち', 'うち', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"うち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-2', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-2', 3, '帰り', 'かえり', (select id from words where primary_form = '帰り' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"帰","r":"かえ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-2', 4, 'ましょう', 'ましょう', NULL, 8, 12, '[{"t":"ましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-2', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-3', 0, '忘れない', 'わすれない', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"忘","r":"わす"},{"t":"れない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-3', 1, 'うち', 'うち', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"うち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-3', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-3', 3, 'メモします', 'メモします', (select id from words where primary_form = 'メモ' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"メモします"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-4', 0, '熱い', 'あつい', (select id from words where primary_form = '熱い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"熱","r":"あつ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-4', 1, 'うち', 'うち', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"うち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-4', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-4', 3, '食べて', 'たべて', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"食","r":"た"},{"t":"べて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-4', 4, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uchini-4', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 1, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 3, '見る', 'みる', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"見","r":"み"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 4, 'たびに', 'たびに', NULL, 7, 10, '[{"t":"たびに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 5, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 6, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 7, 'の', 'の', NULL, 13, 14, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 8, '時', 'とき', (select id from words where primary_form = '時' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"時","r":"とき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 9, 'を', 'を', NULL, 15, 16, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 10, '思い出す', 'おもいだす', (select id from words where primary_form = '思い出す' and language_id = 'lang-ja' and published order by id limit 1), 16, 20, '[{"t":"思","r":"おも"},{"t":"い"},{"t":"出","r":"だ"},{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-1', 11, '。', '。', NULL, 20, 21, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 1, 'へ', 'へ', NULL, 2, 3, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 2, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 3, 'たびに', 'たびに', NULL, 5, 8, '[{"t":"たびに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 5, 'お土産', 'おみやげ', (select id from words where primary_form = 'お土産' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"お"},{"t":"土産","r":"みやげ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 6, 'を', 'を', NULL, 12, 13, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 7, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-2', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 2, '会う', 'あう', (select id from words where primary_form = '会う' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"会","r":"あ"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 3, 'たびに', 'たびに', NULL, 4, 7, '[{"t":"たびに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 5, '背', 'せ', (select id from words where primary_form = '背' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"背","r":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 6, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 7, '高くなる', 'たかくなる', (select id from words where primary_form = '高まる' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"高","r":"たか"},{"t":"くなる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-3', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 2, '降る', 'ふる', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"降","r":"ふ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 3, 'たびに', 'たびに', NULL, 4, 7, '[{"t":"たびに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 5, '道', 'みち', (select id from words where primary_form = '道' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"道","r":"みち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 6, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 7, '悪', 'わる', (select id from words where primary_form = '悪' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"悪","r":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 8, 'く', 'く', NULL, 11, 12, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 9, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tabini-4', 10, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb);
