-- N3 example sentences, batch 2: the に-compounds, and three particles that
-- put weight on a noun.
--
-- 〜とともに, 〜につれて and 〜にしたがって all say one thing changes as
-- another does, and the examples deliberately share a subject — 年をとる —
-- across the three so the difference is in the pattern and not in the
-- vocabulary. Then によって, に対して, について, にとって: four に-compounds
-- that English hands to "by", "towards", "about" and "for". Last かぎり, さえ
-- and こそ.
--
-- Two rewordings, both その: it is not a published word and shreds to そ|の,
-- exactly as この does. Those two sentences use 学生の and あの instead. The
-- first also lost 答えられなかった, which comes apart as 答え|ら|れ|なかった —
-- a potential negative is one inflection deeper than the index goes — so the
-- teacher answers rather than the student failing to.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- to-tomo-ni
  ('sent-ex-totomoni-1', 'lang-ja', '年をとるとともに、体が弱くなる。', 'とし お とる と ともに、からだ が よわく なる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-totomoni-2', 'lang-ja', '経済の発展とともに、生活が変わった。', 'けいざい の はってん と ともに、せいかつ が かわった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-totomoni-3', 'lang-ja', '家族とともに日本へ行きます。', 'かぞく と ともに にほん え いきます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-totomoni-4', 'lang-ja', '時代とともに言葉も変わる。', 'じだい と ともに ことば も かわる。', 'lvl-ja-n3', 'authored', true),
  -- ni-tsurete
  ('sent-ex-nitsurete-1', 'lang-ja', '年をとるにつれて、体が弱くなる。', 'とし お とる に つれて、からだ が よわく なる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitsurete-2', 'lang-ja', '夜になるにつれて、寒くなった。', 'よる に なる に つれて、さむく なった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitsurete-3', 'lang-ja', '時間が経つにつれて、痛みが消えた。', 'じかん が たつ に つれて、いたみ が きえた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitsurete-4', 'lang-ja', '町が大きくなるにつれて、人が増えた。', 'まち が おおきく なる に つれて、ひと が ふえた。', 'lvl-ja-n3', 'authored', true),
  -- ni-shitagatte
  ('sent-ex-nishitagatte-1', 'lang-ja', '規則にしたがって行動してください。', 'きそく に したがって こうどう して ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nishitagatte-2', 'lang-ja', '先生の説明にしたがって書いてください。', 'せんせい の せつめい に したがって かいて ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nishitagatte-3', 'lang-ja', '時間が経つにしたがって、風が強くなった。', 'じかん が たつ に したがって、かぜ が つよく なった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nishitagatte-4', 'lang-ja', '年をとるにしたがって、考えが変わる。', 'とし お とる に したがって、かんがえ が かわる。', 'lvl-ja-n3', 'authored', true),
  -- ni-yotte
  ('sent-ex-niyotte-1', 'lang-ja', '人によって考えが違う。', 'ひと に よって かんがえ が ちがう。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-niyotte-2', 'lang-ja', '地震によって多くの家が壊れた。', 'じしん に よって おおく の いえ が こわれた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-niyotte-3', 'lang-ja', '季節によって値段が変わります。', 'きせつ に よって ねだん が かわります。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-niyotte-4', 'lang-ja', 'あの本は有名な作家によって書かれた。', 'あの ほん わ ゆうめい な さっか に よって かかれた。', 'lvl-ja-n3', 'authored', true),
  -- ni-taishite
  ('sent-ex-nitaishite-1', 'lang-ja', '先生に対して失礼な態度を取った。', 'せんせい に たいして しつれい な たいど お とった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitaishite-2', 'lang-ja', '学生の質問に対して先生が答えました。', 'がくせい の しつもん に たいして せんせい が こたえました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitaishite-3', 'lang-ja', '学生に対して厳しい先生です。', 'がくせい に たいして きびしい せんせい です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitaishite-4', 'lang-ja', '政府の政策に対して反対しています。', 'せいふ の せいさく に たいして はんたい して います。', 'lvl-ja-n3', 'authored', true),
  -- ni-tsuite
  ('sent-ex-nitsuite-1', 'lang-ja', '日本の歴史について勉強しています。', 'にほん の れきし に ついて べんきょう して います。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitsuite-2', 'lang-ja', 'あの問題について話し合いましょう。', 'あの もんだい に ついて はなしあいましょう。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitsuite-3', 'lang-ja', '彼について何も知りません。', 'かれ に ついて なに も しりません。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitsuite-4', 'lang-ja', '環境について発表します。', 'かんきょう に ついて はっぴょう します。', 'lvl-ja-n3', 'authored', true),
  -- ni-totte
  ('sent-ex-nitotte-1', 'lang-ja', '私にとって家族が一番大切です。', 'わたし に とって かぞく が いちばん たいせつ です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitotte-2', 'lang-ja', '学生にとってあの試験は難しい。', 'がくせい に とって あの しけん わ むずかしい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitotte-3', 'lang-ja', '彼にとってそれは大きな問題だ。', 'かれ に とって それ わ おおきな もんだい だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nitotte-4', 'lang-ja', '子供にとって遊びは大切です。', 'こども に とって あそび わ たいせつ です。', 'lvl-ja-n3', 'authored', true),
  -- kagiri
  ('sent-ex-kagiri-1', 'lang-ja', '私が知るかぎり、彼は正直な人です。', 'わたし が しる かぎり、かれ わ しょうじき な ひと です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kagiri-2', 'lang-ja', '体が丈夫なかぎり、働き続けます。', 'からだ が じょうぶ な かぎり、はたらきつづけます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kagiri-3', 'lang-ja', '見るかぎり、問題はない。', 'みる かぎり、もんだい わ ない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kagiri-4', 'lang-ja', '時間があるかぎり、手伝います。', 'じかん が ある かぎり、てつだいます。', 'lvl-ja-n3', 'authored', true),
  -- sae
  ('sent-ex-sae-1', 'lang-ja', '彼は自分の名前さえ書けない。', 'かれ わ じぶん の なまえ さえ かけない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-sae-2', 'lang-ja', '水さえあれば生きられる。', 'みず さえ あれば いきられる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-sae-3', 'lang-ja', '子供さえ知っている。', 'こども さえ しって いる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-sae-4', 'lang-ja', 'お金さえあれば買えます。', 'おかね さえ あれば かえます。', 'lvl-ja-n3', 'authored', true),
  -- koso
  ('sent-ex-koso-1', 'lang-ja', '今年こそ日本へ行きます。', 'ことし こそ にほん え いきます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-koso-2', 'lang-ja', '今こそ始める時だ。', 'いま こそ はじめる とき だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-koso-3', 'lang-ja', '努力こそ大切だ。', 'どりょく こそ たいせつ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-koso-4', 'lang-ja', '今度こそ成功したい。', 'こんど こそ せいこう したい。', 'lvl-ja-n3', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-totomoni-1', 'sent-ex-totomoni-1', 'en', 'As you grow older, your body grows weaker.', 'authored'),
  ('st-ex-totomoni-2', 'sent-ex-totomoni-2', 'en', 'Along with economic development, daily life changed.', 'authored'),
  ('st-ex-totomoni-3', 'sent-ex-totomoni-3', 'en', 'I am going to Japan together with my family.', 'authored'),
  ('st-ex-totomoni-4', 'sent-ex-totomoni-4', 'en', 'Words change along with the times.', 'authored'),
  ('st-ex-nitsurete-1', 'sent-ex-nitsurete-1', 'en', 'As you grow older, your body grows weaker.', 'authored'),
  ('st-ex-nitsurete-2', 'sent-ex-nitsurete-2', 'en', 'As night came on, it grew colder.', 'authored'),
  ('st-ex-nitsurete-3', 'sent-ex-nitsurete-3', 'en', 'As time passed, the pain faded.', 'authored'),
  ('st-ex-nitsurete-4', 'sent-ex-nitsurete-4', 'en', 'As the town grew, the population rose.', 'authored'),
  ('st-ex-nishitagatte-1', 'sent-ex-nishitagatte-1', 'en', 'Please act in accordance with the rules.', 'authored'),
  ('st-ex-nishitagatte-2', 'sent-ex-nishitagatte-2', 'en', 'Please write it following the teacher''s explanation.', 'authored'),
  ('st-ex-nishitagatte-3', 'sent-ex-nishitagatte-3', 'en', 'As time went on, the wind grew stronger.', 'authored'),
  ('st-ex-nishitagatte-4', 'sent-ex-nishitagatte-4', 'en', 'As you grow older, your views change.', 'authored'),
  ('st-ex-niyotte-1', 'sent-ex-niyotte-1', 'en', 'Views differ from person to person.', 'authored'),
  ('st-ex-niyotte-2', 'sent-ex-niyotte-2', 'en', 'Many houses were destroyed by the earthquake.', 'authored'),
  ('st-ex-niyotte-3', 'sent-ex-niyotte-3', 'en', 'Prices change with the season.', 'authored'),
  ('st-ex-niyotte-4', 'sent-ex-niyotte-4', 'en', 'That book was written by a famous author.', 'authored'),
  ('st-ex-nitaishite-1', 'sent-ex-nitaishite-1', 'en', 'I behaved rudely towards the teacher.', 'authored'),
  ('st-ex-nitaishite-2', 'sent-ex-nitaishite-2', 'en', 'The teacher answered the student''s question.', 'authored'),
  ('st-ex-nitaishite-3', 'sent-ex-nitaishite-3', 'en', 'She is a teacher who is strict with her students.', 'authored'),
  ('st-ex-nitaishite-4', 'sent-ex-nitaishite-4', 'en', 'We oppose the government''s policy.', 'authored'),
  ('st-ex-nitsuite-1', 'sent-ex-nitsuite-1', 'en', 'I am studying the history of Japan.', 'authored'),
  ('st-ex-nitsuite-2', 'sent-ex-nitsuite-2', 'en', 'Let us talk that problem over.', 'authored'),
  ('st-ex-nitsuite-3', 'sent-ex-nitsuite-3', 'en', 'I know nothing about him.', 'authored'),
  ('st-ex-nitsuite-4', 'sent-ex-nitsuite-4', 'en', 'I am giving a presentation on the environment.', 'authored'),
  ('st-ex-nitotte-1', 'sent-ex-nitotte-1', 'en', 'For me, family matters most.', 'authored'),
  ('st-ex-nitotte-2', 'sent-ex-nitotte-2', 'en', 'For a student, that exam is hard.', 'authored'),
  ('st-ex-nitotte-3', 'sent-ex-nitotte-3', 'en', 'For him it is a big problem.', 'authored'),
  ('st-ex-nitotte-4', 'sent-ex-nitotte-4', 'en', 'For a child, play matters.', 'authored'),
  ('st-ex-kagiri-1', 'sent-ex-kagiri-1', 'en', 'As far as I know, he is an honest man.', 'authored'),
  ('st-ex-kagiri-2', 'sent-ex-kagiri-2', 'en', 'As long as my health holds, I will go on working.', 'authored'),
  ('st-ex-kagiri-3', 'sent-ex-kagiri-3', 'en', 'As far as I can see, there is no problem.', 'authored'),
  ('st-ex-kagiri-4', 'sent-ex-kagiri-4', 'en', 'As long as I have the time, I will help.', 'authored'),
  ('st-ex-sae-1', 'sent-ex-sae-1', 'en', 'He cannot even write his own name.', 'authored'),
  ('st-ex-sae-2', 'sent-ex-sae-2', 'en', 'If you have water you can survive.', 'authored'),
  ('st-ex-sae-3', 'sent-ex-sae-3', 'en', 'Even a child knows that.', 'authored'),
  ('st-ex-sae-4', 'sent-ex-sae-4', 'en', 'If you have the money you can buy it.', 'authored'),
  ('st-ex-koso-1', 'sent-ex-koso-1', 'en', 'This year I really am going to Japan.', 'authored'),
  ('st-ex-koso-2', 'sent-ex-koso-2', 'en', 'Now is precisely the time to start.', 'authored'),
  ('st-ex-koso-3', 'sent-ex-koso-3', 'en', 'It is effort that counts.', 'authored'),
  ('st-ex-koso-4', 'sent-ex-koso-4', 'en', 'This time I really do want to succeed.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('to-tomo-ni', 'sent-ex-totomoni-1', 0),
  ('to-tomo-ni', 'sent-ex-totomoni-2', 1),
  ('to-tomo-ni', 'sent-ex-totomoni-3', 2),
  ('to-tomo-ni', 'sent-ex-totomoni-4', 3),
  ('ni-tsurete', 'sent-ex-nitsurete-1', 0),
  ('ni-tsurete', 'sent-ex-nitsurete-2', 1),
  ('ni-tsurete', 'sent-ex-nitsurete-3', 2),
  ('ni-tsurete', 'sent-ex-nitsurete-4', 3),
  ('ni-shitagatte', 'sent-ex-nishitagatte-1', 0),
  ('ni-shitagatte', 'sent-ex-nishitagatte-2', 1),
  ('ni-shitagatte', 'sent-ex-nishitagatte-3', 2),
  ('ni-shitagatte', 'sent-ex-nishitagatte-4', 3),
  ('ni-yotte', 'sent-ex-niyotte-1', 0),
  ('ni-yotte', 'sent-ex-niyotte-2', 1),
  ('ni-yotte', 'sent-ex-niyotte-3', 2),
  ('ni-yotte', 'sent-ex-niyotte-4', 3),
  ('ni-taishite', 'sent-ex-nitaishite-1', 0),
  ('ni-taishite', 'sent-ex-nitaishite-2', 1),
  ('ni-taishite', 'sent-ex-nitaishite-3', 2),
  ('ni-taishite', 'sent-ex-nitaishite-4', 3),
  ('ni-tsuite', 'sent-ex-nitsuite-1', 0),
  ('ni-tsuite', 'sent-ex-nitsuite-2', 1),
  ('ni-tsuite', 'sent-ex-nitsuite-3', 2),
  ('ni-tsuite', 'sent-ex-nitsuite-4', 3),
  ('ni-totte', 'sent-ex-nitotte-1', 0),
  ('ni-totte', 'sent-ex-nitotte-2', 1),
  ('ni-totte', 'sent-ex-nitotte-3', 2),
  ('ni-totte', 'sent-ex-nitotte-4', 3),
  ('kagiri', 'sent-ex-kagiri-1', 0),
  ('kagiri', 'sent-ex-kagiri-2', 1),
  ('kagiri', 'sent-ex-kagiri-3', 2),
  ('kagiri', 'sent-ex-kagiri-4', 3),
  ('sae', 'sent-ex-sae-1', 0),
  ('sae', 'sent-ex-sae-2', 1),
  ('sae', 'sent-ex-sae-3', 2),
  ('sae', 'sent-ex-sae-4', 3),
  ('koso', 'sent-ex-koso-1', 0),
  ('koso', 'sent-ex-koso-2', 1),
  ('koso', 'sent-ex-koso-3', 2),
  ('koso', 'sent-ex-koso-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-totomoni-1', 'sent-ex-totomoni-2', 'sent-ex-totomoni-3', 'sent-ex-totomoni-4', 'sent-ex-nitsurete-1', 'sent-ex-nitsurete-2', 'sent-ex-nitsurete-3', 'sent-ex-nitsurete-4', 'sent-ex-nishitagatte-1', 'sent-ex-nishitagatte-2', 'sent-ex-nishitagatte-3', 'sent-ex-nishitagatte-4', 'sent-ex-niyotte-1', 'sent-ex-niyotte-2', 'sent-ex-niyotte-3', 'sent-ex-niyotte-4', 'sent-ex-nitaishite-1', 'sent-ex-nitaishite-2', 'sent-ex-nitaishite-3', 'sent-ex-nitaishite-4', 'sent-ex-nitsuite-1', 'sent-ex-nitsuite-2', 'sent-ex-nitsuite-3', 'sent-ex-nitsuite-4', 'sent-ex-nitotte-1', 'sent-ex-nitotte-2', 'sent-ex-nitotte-3', 'sent-ex-nitotte-4', 'sent-ex-kagiri-1', 'sent-ex-kagiri-2', 'sent-ex-kagiri-3', 'sent-ex-kagiri-4', 'sent-ex-sae-1', 'sent-ex-sae-2', 'sent-ex-sae-3', 'sent-ex-sae-4', 'sent-ex-koso-1', 'sent-ex-koso-2', 'sent-ex-koso-3', 'sent-ex-koso-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 0, '年', 'とし', (select id from words where primary_form = '年' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"年","r":"とし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 2, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 3, 'る', 'る', NULL, 3, 4, '[{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 4, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 5, 'ともに', 'ともに', (select id from words where primary_form = '共に' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"ともに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 6, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 7, '体', 'からだ', (select id from words where primary_form = '体' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"体","r":"からだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 8, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 9, '弱', 'よわ', (select id from words where primary_form = '弱' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"弱","r":"よわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 10, 'く', 'く', NULL, 12, 13, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 11, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-1', 12, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 0, '経済', 'けいざい', (select id from words where primary_form = '経済' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経済","r":"けいざい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 2, '発展', 'はってん', (select id from words where primary_form = '発展' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"発展","r":"はってん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 4, 'ともに', 'ともに', (select id from words where primary_form = '共に' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"ともに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 5, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 6, '生活', 'せいかつ', (select id from words where primary_form = '生活' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"生活","r":"せいかつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 7, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 8, '変わった', 'かわった', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"変","r":"か"},{"t":"わった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-2', 9, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-3', 0, '家族', 'かぞく', (select id from words where primary_form = '家族' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"家族","r":"かぞく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-3', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-3', 2, 'ともに', 'ともに', (select id from words where primary_form = '共に' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"ともに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-3', 3, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-3', 4, 'へ', 'へ', NULL, 8, 9, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-3', 5, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-4', 0, '時代', 'じだい', (select id from words where primary_form = '時代' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時代","r":"じだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-4', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-4', 2, 'ともに', 'ともに', (select id from words where primary_form = '共に' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"ともに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-4', 3, '言葉', 'ことば', (select id from words where primary_form = '言葉' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"言葉","r":"ことば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-4', 4, 'も', 'も', NULL, 8, 9, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-4', 5, '変わる', 'かわる', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"変","r":"か"},{"t":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-totomoni-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 0, '年', 'とし', (select id from words where primary_form = '年' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"年","r":"とし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 2, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 3, 'る', 'る', NULL, 3, 4, '[{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 4, 'につれて', 'につれて', NULL, 4, 8, '[{"t":"につれて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 6, '体', 'からだ', (select id from words where primary_form = '体' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"体","r":"からだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 7, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 8, '弱', 'よわ', (select id from words where primary_form = '弱' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"弱","r":"よわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 9, 'く', 'く', NULL, 12, 13, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 10, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-1', 11, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-2', 0, '夜', 'よる', (select id from words where primary_form = '夜' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"夜","r":"よる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-2', 2, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-2', 3, 'につれて', 'につれて', NULL, 4, 8, '[{"t":"につれて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-2', 5, '寒くなった', 'さむくなった', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"寒","r":"さむ"},{"t":"くなった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 0, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 2, '経つ', 'たつ', (select id from words where primary_form = '経つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"経","r":"た"},{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 3, 'につれて', 'につれて', NULL, 5, 9, '[{"t":"につれて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 5, '痛み', 'いたみ', (select id from words where primary_form = '痛み' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"痛","r":"いた"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 6, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 7, '消えた', 'きえた', (select id from words where primary_form = '消える' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"消","r":"き"},{"t":"えた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-3', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 0, '町', 'まち', (select id from words where primary_form = '町' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"町","r":"まち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 2, '大き', 'おおき', (select id from words where primary_form = '大き' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"大","r":"おお"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 3, 'く', 'く', NULL, 4, 5, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 4, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 5, 'につれて', 'につれて', NULL, 7, 11, '[{"t":"につれて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 6, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 7, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 8, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 9, '増えた', 'ふえた', (select id from words where primary_form = '増える' and language_id = 'lang-ja' and published order by id limit 1), 14, 17, '[{"t":"増","r":"ふ"},{"t":"えた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsurete-4', 10, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-1', 0, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-1', 1, 'にしたがって', 'にしたがって', NULL, 2, 8, '[{"t":"にしたがって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-1', 2, '行動して', 'こうどうして', (select id from words where primary_form = '行動' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"行動","r":"こうどう"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-1', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-1', 4, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-2', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-2', 2, '説明', 'せつめい', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"説明","r":"せつめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-2', 3, 'にしたがって', 'にしたがって', NULL, 5, 11, '[{"t":"にしたがって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-2', 4, '書いて', 'かいて', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"書","r":"か"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-2', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-2', 6, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 0, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 2, '経つ', 'たつ', (select id from words where primary_form = '経つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"経","r":"た"},{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 3, 'にしたがって', 'にしたがって', NULL, 5, 11, '[{"t":"にしたがって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 4, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 5, '風', 'かぜ', (select id from words where primary_form = '風' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"風","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 6, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 7, '強', 'つよ', (select id from words where primary_form = '強' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"強","r":"つよ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 8, 'く', 'く', NULL, 15, 16, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 9, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 16, 19, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-3', 10, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 0, '年', 'とし', (select id from words where primary_form = '年' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"年","r":"とし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 2, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 3, 'る', 'る', NULL, 3, 4, '[{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 4, 'にしたがって', 'にしたがって', NULL, 4, 10, '[{"t":"にしたがって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 5, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 6, '考え', 'かんがえ', (select id from words where primary_form = '考え' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"考","r":"かんが"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 7, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 8, '変わる', 'かわる', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 14, 17, '[{"t":"変","r":"か"},{"t":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishitagatte-4', 9, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-1', 0, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-1', 1, 'によって', 'によって', NULL, 1, 5, '[{"t":"によって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-1', 2, '考え', 'かんがえ', (select id from words where primary_form = '考え' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"考","r":"かんが"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-1', 3, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-1', 4, '違う', 'ちがう', (select id from words where primary_form = '違う' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"違","r":"ちが"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-2', 0, '地震', 'じしん', (select id from words where primary_form = '地震' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"地震","r":"じしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-2', 1, 'によって', 'によって', NULL, 2, 6, '[{"t":"によって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-2', 2, '多くの', 'おおくの', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"多","r":"おお"},{"t":"くの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-2', 3, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-2', 4, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-2', 5, '壊れた', 'こわれた', (select id from words where primary_form = '壊れる' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"壊","r":"こわ"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-3', 0, '季節', 'きせつ', (select id from words where primary_form = '季節' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"季節","r":"きせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-3', 1, 'によって', 'によって', NULL, 2, 6, '[{"t":"によって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-3', 2, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-3', 3, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-3', 4, '変わります', 'かわります', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"変","r":"か"},{"t":"わります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-3', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 3, '有名', 'ゆうめい', (select id from words where primary_form = '有名' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"有名","r":"ゆうめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 4, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 5, '作家', 'さっか', (select id from words where primary_form = '作家' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"作家","r":"さっか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 6, 'によって', 'によって', NULL, 9, 13, '[{"t":"によって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 7, '書かれた', 'かかれた', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"書","r":"か"},{"t":"かれた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niyotte-4', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 2, '対して', 'たいして', (select id from words where primary_form = '対する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"対","r":"たい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 3, '失礼', 'しつれい', (select id from words where primary_form = '失礼' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"失礼","r":"しつれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 4, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 5, '態度', 'たいど', (select id from words where primary_form = '態度' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"態度","r":"たいど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 6, 'を', 'を', NULL, 11, 12, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 7, '取った', 'とった', (select id from words where primary_form = '取る' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"取","r":"と"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-1', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 2, '質問', 'しつもん', (select id from words where primary_form = '質問' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"質問","r":"しつもん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 4, '対して', 'たいして', (select id from words where primary_form = '対する' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"対","r":"たい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 5, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 6, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 7, '答えました', 'こたえました', (select id from words where primary_form = '答える' and language_id = 'lang-ja' and published order by id limit 1), 12, 17, '[{"t":"答","r":"こた"},{"t":"えました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-2', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-3', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-3', 2, '対して', 'たいして', (select id from words where primary_form = '対する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"対","r":"たい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-3', 3, '厳しい', 'きびしい', (select id from words where primary_form = '厳しい' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"厳","r":"きび"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-3', 4, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-3', 5, 'です', 'です', NULL, 11, 13, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 0, '政府', 'せいふ', (select id from words where primary_form = '政府' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"政府","r":"せいふ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 2, '政策', 'せいさく', (select id from words where primary_form = '政策' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"政策","r":"せいさく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 4, '対して', 'たいして', (select id from words where primary_form = '対する' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"対","r":"たい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 5, '反対して', 'はんたいして', (select id from words where primary_form = '反対' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"反対","r":"はんたい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 6, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaishite-4', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-1', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-1', 2, '歴史', 'れきし', (select id from words where primary_form = '歴史' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"歴史","r":"れきし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-1', 3, 'について', 'について', NULL, 5, 9, '[{"t":"について"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-1', 4, '勉強して', 'べんきょうして', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"勉強","r":"べんきょう"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-1', 5, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-1', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-2', 1, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-2', 2, 'について', 'について', NULL, 4, 8, '[{"t":"について"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-2', 3, '話し合い', 'はなしあい', (select id from words where primary_form = '話し合い' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"話","r":"はな"},{"t":"し"},{"t":"合","r":"あ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-2', 4, 'ましょう', 'ましょう', NULL, 12, 16, '[{"t":"ましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-2', 5, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-3', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-3', 1, 'について', 'について', NULL, 1, 5, '[{"t":"について"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-3', 2, '何も', 'なにも', NULL, 5, 7, '[{"t":"何","r":"なに"},{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-3', 3, '知りません', 'しりません', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"知","r":"し"},{"t":"りません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-4', 0, '環境', 'かんきょう', (select id from words where primary_form = '環境' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"環境","r":"かんきょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-4', 1, 'について', 'について', NULL, 2, 6, '[{"t":"について"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-4', 2, '発表します', 'はっぴょうします', (select id from words where primary_form = '発表' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"発表","r":"はっぴょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitsuite-4', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 1, 'にとって', 'にとって', NULL, 1, 5, '[{"t":"にとって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 2, '家族', 'かぞく', (select id from words where primary_form = '家族' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"家族","r":"かぞく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 3, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 4, '一番', 'いちばん', (select id from words where primary_form = '一番' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"一番","r":"いちばん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 5, '大切', 'たいせつ', (select id from words where primary_form = '大切' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"大切","r":"たいせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 6, 'です', 'です', NULL, 12, 14, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-1', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-2', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-2', 1, 'にとって', 'にとって', NULL, 2, 6, '[{"t":"にとって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-2', 2, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-2', 3, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-2', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-2', 5, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 1, 'にとって', 'にとって', NULL, 1, 5, '[{"t":"にとって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 2, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 4, '大きな', 'おおきな', (select id from words where primary_form = '大きな' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"大","r":"おお"},{"t":"きな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 5, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 6, 'だ', 'だ', NULL, 13, 14, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-3', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-4', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-4', 1, 'にとって', 'にとって', NULL, 2, 6, '[{"t":"にとって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-4', 2, '遊び', 'あそび', (select id from words where primary_form = '遊び' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"遊","r":"あそ"},{"t":"び"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-4', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-4', 4, '大切', 'たいせつ', (select id from words where primary_form = '大切' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"大切","r":"たいせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-4', 5, 'です', 'です', NULL, 11, 13, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitotte-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 2, '知る', 'しる', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"知","r":"し"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 3, 'かぎり', 'かぎり', NULL, 4, 7, '[{"t":"かぎり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 5, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 6, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 7, '正直', 'しょうじき', (select id from words where primary_form = '正直' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"正直","r":"しょうじき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 8, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 9, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 10, 'です', 'です', NULL, 14, 16, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-1', 11, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 0, '体', 'からだ', (select id from words where primary_form = '体' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"体","r":"からだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 2, '丈夫', 'じょうぶ', (select id from words where primary_form = '丈夫' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"丈夫","r":"じょうぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 4, 'かぎり', 'かぎり', NULL, 5, 8, '[{"t":"かぎり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 6, '働き', 'はたらき', (select id from words where primary_form = '働き' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"働","r":"はたら"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 7, '続けます', 'つづけます', (select id from words where primary_form = '続ける' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"続","r":"つづ"},{"t":"けます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-2', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-3', 0, '見る', 'みる', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"見","r":"み"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-3', 1, 'かぎり', 'かぎり', NULL, 2, 5, '[{"t":"かぎり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-3', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-3', 3, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-3', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-4', 0, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-4', 2, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-4', 3, 'かぎり', 'かぎり', NULL, 5, 8, '[{"t":"かぎり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-4', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-4', 5, '手伝います', 'てつだいます', (select id from words where primary_form = '手伝う' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"手伝","r":"てつだ"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kagiri-4', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 2, '自分', 'じぶん', (select id from words where primary_form = '自分' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"自分","r":"じぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 4, '名前', 'なまえ', (select id from words where primary_form = '名前' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"名前","r":"なまえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 5, 'さえ', 'さえ', NULL, 7, 9, '[{"t":"さえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 6, '書け', 'かけ', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"書","r":"か"},{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 7, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-1', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-2', 0, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-2', 1, 'さえ', 'さえ', NULL, 1, 3, '[{"t":"さえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-2', 2, 'あれば', 'あれば', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"あれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-2', 3, '生きられる', 'いきられる', (select id from words where primary_form = '生きる' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"生","r":"い"},{"t":"きられる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-3', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-3', 1, 'さえ', 'さえ', NULL, 2, 4, '[{"t":"さえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-3', 2, '知って', 'しって', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"知","r":"し"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-3', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-4', 0, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-4', 1, 'さえ', 'さえ', NULL, 2, 4, '[{"t":"さえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-4', 2, 'あれば', 'あれば', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"あれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-4', 3, '買え', 'かえ', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"買","r":"か"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-4', 4, 'ます', 'ます', NULL, 9, 11, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sae-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-1', 0, '今年', 'ことし', (select id from words where primary_form = '今年' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今年","r":"ことし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-1', 1, 'こそ', 'こそ', NULL, 2, 4, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-1', 2, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-1', 3, 'へ', 'へ', NULL, 6, 7, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-1', 4, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-2', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-2', 1, 'こそ', 'こそ', NULL, 1, 3, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-2', 2, '始める', 'はじめる', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"始","r":"はじ"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-2', 3, '時', 'とき', (select id from words where primary_form = '時' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"時","r":"とき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-2', 4, 'だ', 'だ', NULL, 7, 8, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-2', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-3', 0, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-3', 1, 'こそ', 'こそ', NULL, 2, 4, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-3', 2, '大切', 'たいせつ', (select id from words where primary_form = '大切' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"大切","r":"たいせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-3', 3, 'だ', 'だ', NULL, 6, 7, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-3', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-4', 0, '今度', 'こんど', (select id from words where primary_form = '今度' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今度","r":"こんど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-4', 1, 'こそ', 'こそ', NULL, 2, 4, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-4', 2, '成功したい', 'せいこうしたい', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"成功","r":"せいこう"},{"t":"したい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-koso-4', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb);
