-- N3 example sentences, batch 3: degree, report, and the spoken shortcuts.
--
-- 〜だけでなく, 〜ほど, 〜くらい and 〜とおり measure and compare; 〜まま
-- freezes a state. Then three things that only really live in speech —
-- 〜っけ for what you have half-forgotten, 〜って as the casual quote, 〜なんか
-- / 〜なんて for dismissal — and two that only live in formal register:
-- 〜ように言う and 〜させていただく.
--
-- Three rewordings:
--
--   予想どおり shreds to 予想|ど|お|り. とおり written in kana after a noun
--   has no entry; 予想のとおり keeps the の and cuts clean.
--
--   寝てしまった lost ま|っ|た, the same しまう gap batch 3 of N4 hit —
--   しまいました survives whole, so the sentence is polite past.
--
--   発表させていただきます came apart as 発表 | さ | せ | て. A する-verb
--   causative is two suffixes past what the index holds; 読ませて cuts clean,
--   so the humble example is about reading rather than presenting.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- dake-de-naku
  ('sent-ex-dakedenaku-1', 'lang-ja', '彼は英語だけでなく、料理も上手だ。', 'かれ わ えいご だけ で なく、りょうり も じょうず だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-dakedenaku-2', 'lang-ja', '値段が安いだけでなく、味もいい。', 'ねだん が やすい だけ で なく、あじ も いい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-dakedenaku-3', 'lang-ja', '子供だけでなく、大人も楽しめる。', 'こども だけ で なく、おとな も たのしめる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-dakedenaku-4', 'lang-ja', '雨だけでなく、風も強かった。', 'あめ だけ で なく、かぜ も つよかった。', 'lvl-ja-n3', 'authored', true),
  -- hodo
  ('sent-ex-hodo-1', 'lang-ja', '今日は歩けないほど疲れた。', 'きょう わ あるけない ほど つかれた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-hodo-2', 'lang-ja', '彼ほど親切な人はいない。', 'かれ ほど しんせつ な ひと わ いない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-hodo-3', 'lang-ja', '泣きたいほど嬉しかった。', 'なきたい ほど うれしかった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-hodo-4', 'lang-ja', '勉強すればするほど、分かるようになる。', 'べんきょう すれば する ほど、わかる よう に なる。', 'lvl-ja-n3', 'authored', true),
  -- kurai
  ('sent-ex-kurai-1', 'lang-ja', 'あの店は歩いて行けるくらい近い。', 'あの みせ わ あるいて いける くらい ちかい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kurai-2', 'lang-ja', '泣きたいくらい悲しかった。', 'なきたい くらい かなしかった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kurai-3', 'lang-ja', 'それくらいできます。', 'それ くらい できます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kurai-4', 'lang-ja', '半分ぐらい残っています。', 'はんぶん ぐらい のこって います。', 'lvl-ja-n3', 'authored', true),
  -- toori
  ('sent-ex-toori-1', 'lang-ja', '説明のとおりに作ってください。', 'せつめい の とおり に つくって ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-toori-2', 'lang-ja', '思ったとおりだった。', 'おもった とおり だった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-toori-3', 'lang-ja', '先生が言ったとおりにしました。', 'せんせい が いった とおり に しました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-toori-4', 'lang-ja', '予想のとおり、彼が勝った。', 'よそう の とおり、かれ が かった。', 'lvl-ja-n3', 'authored', true),
  -- mama
  ('sent-ex-mama-1', 'lang-ja', '窓を開けたまま寝てしまいました。', 'まど お あけた まま ねて しまいました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-mama-2', 'lang-ja', '靴を履いたまま入らないでください。', 'くつ お はいた まま はいらないで ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-mama-3', 'lang-ja', '昔のままです。', 'むかし の まま です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-mama-4', 'lang-ja', '立ったまま食べた。', 'たった まま たべた。', 'lvl-ja-n3', 'authored', true),
  -- kke
  ('sent-ex-kke-1', 'lang-ja', '明日は休みだっけ。', 'あした わ やすみ だっけ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kke-2', 'lang-ja', '彼の名前は何だっけ。', 'かれ の なまえ わ なん だっけ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kke-3', 'lang-ja', '試験は来週だっけ。', 'しけん わ らいしゅう だっけ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kke-4', 'lang-ja', '宿題があったっけ。', 'しゅくだい が あったっけ。', 'lvl-ja-n3', 'authored', true),
  -- tte-quote
  ('sent-ex-ttequote-1', 'lang-ja', '彼は行かないって言っていた。', 'かれ わ いかない って いって いた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-ttequote-2', 'lang-ja', '明日は雨だって。', 'あした わ あめ だって。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-ttequote-3', 'lang-ja', '先生が来るって聞いた。', 'せんせい が くる って きいた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-ttequote-4', 'lang-ja', '無理だって思った。', 'むり だって おもった。', 'lvl-ja-n3', 'authored', true),
  -- nanka
  ('sent-ex-nanka-1', 'lang-ja', '私なんかにはできません。', 'わたし なんか に わ できません。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nanka-2', 'lang-ja', '野菜なんか食べたくない。', 'やさい なんか たべたくない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nanka-3', 'lang-ja', '彼が来るなんて思わなかった。', 'かれ が くる なんて おもわなかった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nanka-4', 'lang-ja', '試験に落ちるなんて信じられない。', 'しけん に おちる なんて しんじられない。', 'lvl-ja-n3', 'authored', true),
  -- you-ni-iu
  ('sent-ex-youniiu-1', 'lang-ja', '先生は学生に静かにするように言った。', 'せんせい わ がくせい に しずか に する よう に いった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-youniiu-2', 'lang-ja', '母に早く帰るように言われた。', 'はは に はやく かえる よう に いわれた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-youniiu-3', 'lang-ja', '医者に薬を飲むように言われました。', 'いしゃ に くすり お のむ よう に いわれました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-youniiu-4', 'lang-ja', '妹に部屋を片付けるように言いました。', 'いもうと に へや お かたづける よう に いいました。', 'lvl-ja-n3', 'authored', true),
  -- sasete-itadaku
  ('sent-ex-saseteitadaku-1', 'lang-ja', '明日休ませていただきます。', 'あした やすませて いただきます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-saseteitadaku-2', 'lang-ja', '本を読ませていただきます。', 'ほん お よませて いただきます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-saseteitadaku-3', 'lang-ja', '今日は早く帰らせていただきます。', 'きょう わ はやく かえらせて いただきます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-saseteitadaku-4', 'lang-ja', '使わせていただきました。', 'つかわせて いただきました。', 'lvl-ja-n3', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-dakedenaku-1', 'sent-ex-dakedenaku-1', 'en', 'He is good not only at English but at cooking too.', 'authored'),
  ('st-ex-dakedenaku-2', 'sent-ex-dakedenaku-2', 'en', 'Not only is it cheap, it tastes good as well.', 'authored'),
  ('st-ex-dakedenaku-3', 'sent-ex-dakedenaku-3', 'en', 'Not just children — adults can enjoy it too.', 'authored'),
  ('st-ex-dakedenaku-4', 'sent-ex-dakedenaku-4', 'en', 'It was not only raining; the wind was strong as well.', 'authored'),
  ('st-ex-hodo-1', 'sent-ex-hodo-1', 'en', 'Today I am so tired I can hardly walk.', 'authored'),
  ('st-ex-hodo-2', 'sent-ex-hodo-2', 'en', 'There is nobody as kind as he is.', 'authored'),
  ('st-ex-hodo-3', 'sent-ex-hodo-3', 'en', 'I was so happy I could have cried.', 'authored'),
  ('st-ex-hodo-4', 'sent-ex-hodo-4', 'en', 'The more you study, the more you understand.', 'authored'),
  ('st-ex-kurai-1', 'sent-ex-kurai-1', 'en', 'That shop is close enough to walk to.', 'authored'),
  ('st-ex-kurai-2', 'sent-ex-kurai-2', 'en', 'I was sad enough to cry.', 'authored'),
  ('st-ex-kurai-3', 'sent-ex-kurai-3', 'en', 'I can manage that much.', 'authored'),
  ('st-ex-kurai-4', 'sent-ex-kurai-4', 'en', 'About half of it is left.', 'authored'),
  ('st-ex-toori-1', 'sent-ex-toori-1', 'en', 'Please make it the way the instructions say.', 'authored'),
  ('st-ex-toori-2', 'sent-ex-toori-2', 'en', 'It was just as I thought.', 'authored'),
  ('st-ex-toori-3', 'sent-ex-toori-3', 'en', 'I did as the teacher said.', 'authored'),
  ('st-ex-toori-4', 'sent-ex-toori-4', 'en', 'Just as expected, he won.', 'authored'),
  ('st-ex-mama-1', 'sent-ex-mama-1', 'en', 'I fell asleep with the window left open.', 'authored'),
  ('st-ex-mama-2', 'sent-ex-mama-2', 'en', 'Please do not come in with your shoes on.', 'authored'),
  ('st-ex-mama-3', 'sent-ex-mama-3', 'en', 'It is just as it always was.', 'authored'),
  ('st-ex-mama-4', 'sent-ex-mama-4', 'en', 'I ate standing up.', 'authored'),
  ('st-ex-kke-1', 'sent-ex-kke-1', 'en', 'Tomorrow is a day off, isn’t it?', 'authored'),
  ('st-ex-kke-2', 'sent-ex-kke-2', 'en', 'What was his name again?', 'authored'),
  ('st-ex-kke-3', 'sent-ex-kke-3', 'en', 'The exam is next week, right?', 'authored'),
  ('st-ex-kke-4', 'sent-ex-kke-4', 'en', 'Was there homework?', 'authored'),
  ('st-ex-ttequote-1', 'sent-ex-ttequote-1', 'en', 'He was saying he is not going.', 'authored'),
  ('st-ex-ttequote-2', 'sent-ex-ttequote-2', 'en', 'Apparently it is going to rain tomorrow.', 'authored'),
  ('st-ex-ttequote-3', 'sent-ex-ttequote-3', 'en', 'I heard the teacher is coming.', 'authored'),
  ('st-ex-ttequote-4', 'sent-ex-ttequote-4', 'en', 'I thought it was hopeless.', 'authored'),
  ('st-ex-nanka-1', 'sent-ex-nanka-1', 'en', 'Somebody like me could never do it.', 'authored'),
  ('st-ex-nanka-2', 'sent-ex-nanka-2', 'en', 'I do not want to eat vegetables or anything like that.', 'authored'),
  ('st-ex-nanka-3', 'sent-ex-nanka-3', 'en', 'I never expected him to come.', 'authored'),
  ('st-ex-nanka-4', 'sent-ex-nanka-4', 'en', 'I cannot believe I failed the exam.', 'authored'),
  ('st-ex-youniiu-1', 'sent-ex-youniiu-1', 'en', 'The teacher told the students to be quiet.', 'authored'),
  ('st-ex-youniiu-2', 'sent-ex-youniiu-2', 'en', 'My mother told me to come home early.', 'authored'),
  ('st-ex-youniiu-3', 'sent-ex-youniiu-3', 'en', 'The doctor told me to take the medicine.', 'authored'),
  ('st-ex-youniiu-4', 'sent-ex-youniiu-4', 'en', 'I told my little sister to tidy her room.', 'authored'),
  ('st-ex-saseteitadaku-1', 'sent-ex-saseteitadaku-1', 'en', 'I will take tomorrow off, if I may.', 'authored'),
  ('st-ex-saseteitadaku-2', 'sent-ex-saseteitadaku-2', 'en', 'Allow me to read the book.', 'authored'),
  ('st-ex-saseteitadaku-3', 'sent-ex-saseteitadaku-3', 'en', 'I will take my leave early today, if I may.', 'authored'),
  ('st-ex-saseteitadaku-4', 'sent-ex-saseteitadaku-4', 'en', 'I was allowed to use it.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('dake-de-naku', 'sent-ex-dakedenaku-1', 0),
  ('dake-de-naku', 'sent-ex-dakedenaku-2', 1),
  ('dake-de-naku', 'sent-ex-dakedenaku-3', 2),
  ('dake-de-naku', 'sent-ex-dakedenaku-4', 3),
  ('hodo', 'sent-ex-hodo-1', 0),
  ('hodo', 'sent-ex-hodo-2', 1),
  ('hodo', 'sent-ex-hodo-3', 2),
  ('hodo', 'sent-ex-hodo-4', 3),
  ('kurai', 'sent-ex-kurai-1', 0),
  ('kurai', 'sent-ex-kurai-2', 1),
  ('kurai', 'sent-ex-kurai-3', 2),
  ('kurai', 'sent-ex-kurai-4', 3),
  ('toori', 'sent-ex-toori-1', 0),
  ('toori', 'sent-ex-toori-2', 1),
  ('toori', 'sent-ex-toori-3', 2),
  ('toori', 'sent-ex-toori-4', 3),
  ('mama', 'sent-ex-mama-1', 0),
  ('mama', 'sent-ex-mama-2', 1),
  ('mama', 'sent-ex-mama-3', 2),
  ('mama', 'sent-ex-mama-4', 3),
  ('kke', 'sent-ex-kke-1', 0),
  ('kke', 'sent-ex-kke-2', 1),
  ('kke', 'sent-ex-kke-3', 2),
  ('kke', 'sent-ex-kke-4', 3),
  ('tte-quote', 'sent-ex-ttequote-1', 0),
  ('tte-quote', 'sent-ex-ttequote-2', 1),
  ('tte-quote', 'sent-ex-ttequote-3', 2),
  ('tte-quote', 'sent-ex-ttequote-4', 3),
  ('nanka', 'sent-ex-nanka-1', 0),
  ('nanka', 'sent-ex-nanka-2', 1),
  ('nanka', 'sent-ex-nanka-3', 2),
  ('nanka', 'sent-ex-nanka-4', 3),
  ('you-ni-iu', 'sent-ex-youniiu-1', 0),
  ('you-ni-iu', 'sent-ex-youniiu-2', 1),
  ('you-ni-iu', 'sent-ex-youniiu-3', 2),
  ('you-ni-iu', 'sent-ex-youniiu-4', 3),
  ('sasete-itadaku', 'sent-ex-saseteitadaku-1', 0),
  ('sasete-itadaku', 'sent-ex-saseteitadaku-2', 1),
  ('sasete-itadaku', 'sent-ex-saseteitadaku-3', 2),
  ('sasete-itadaku', 'sent-ex-saseteitadaku-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-dakedenaku-1', 'sent-ex-dakedenaku-2', 'sent-ex-dakedenaku-3', 'sent-ex-dakedenaku-4', 'sent-ex-hodo-1', 'sent-ex-hodo-2', 'sent-ex-hodo-3', 'sent-ex-hodo-4', 'sent-ex-kurai-1', 'sent-ex-kurai-2', 'sent-ex-kurai-3', 'sent-ex-kurai-4', 'sent-ex-toori-1', 'sent-ex-toori-2', 'sent-ex-toori-3', 'sent-ex-toori-4', 'sent-ex-mama-1', 'sent-ex-mama-2', 'sent-ex-mama-3', 'sent-ex-mama-4', 'sent-ex-kke-1', 'sent-ex-kke-2', 'sent-ex-kke-3', 'sent-ex-kke-4', 'sent-ex-ttequote-1', 'sent-ex-ttequote-2', 'sent-ex-ttequote-3', 'sent-ex-ttequote-4', 'sent-ex-nanka-1', 'sent-ex-nanka-2', 'sent-ex-nanka-3', 'sent-ex-nanka-4', 'sent-ex-youniiu-1', 'sent-ex-youniiu-2', 'sent-ex-youniiu-3', 'sent-ex-youniiu-4', 'sent-ex-saseteitadaku-1', 'sent-ex-saseteitadaku-2', 'sent-ex-saseteitadaku-3', 'sent-ex-saseteitadaku-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 2, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 3, 'だけでなく', 'だけでなく', NULL, 4, 9, '[{"t":"だけでなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 5, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 6, 'も', 'も', NULL, 12, 13, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 7, '上手', 'じょうず', (select id from words where primary_form = '上手' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"上手","r":"じょうず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 8, 'だ', 'だ', NULL, 15, 16, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-1', 9, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 0, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 2, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 3, 'だけでなく', 'だけでなく', NULL, 5, 10, '[{"t":"だけでなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 4, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 5, '味', 'あじ', (select id from words where primary_form = '味' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"味","r":"あじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 6, 'もいい', 'もいい', NULL, 12, 15, '[{"t":"もいい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-3', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-3', 1, 'だけでなく', 'だけでなく', NULL, 2, 7, '[{"t":"だけでなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-3', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-3', 3, '大人', 'おとな', (select id from words where primary_form = '大人' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"大人","r":"おとな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-3', 4, 'も', 'も', NULL, 10, 11, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-3', 5, '楽しめる', 'たのしめる', (select id from words where primary_form = '楽しむ' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"楽","r":"たの"},{"t":"しめる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-3', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 1, 'だけでなく', 'だけでなく', NULL, 1, 6, '[{"t":"だけでなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 3, '風', 'かぜ', (select id from words where primary_form = '風' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"風","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 4, 'も', 'も', NULL, 8, 9, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 5, '強', 'つよ', (select id from words where primary_form = '強' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"強","r":"つよ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 6, 'かった', 'かった', NULL, 10, 13, '[{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dakedenaku-4', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-1', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-1', 2, '歩け', 'あるけ', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"歩","r":"ある"},{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-1', 3, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-1', 4, 'ほど', 'ほど', (select id from words where primary_form = '程' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"ほど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-1', 5, '疲れた', 'つかれた', (select id from words where primary_form = '疲れる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"疲","r":"つか"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 1, 'ほど', 'ほど', (select id from words where primary_form = '程' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"ほど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 2, '親切', 'しんせつ', (select id from words where primary_form = '親切' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"親切","r":"しんせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 4, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 5, 'はい', 'はい', (select id from words where primary_form = 'はい' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"はい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 6, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-2', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-3', 0, '泣きたい', 'なきたい', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"泣","r":"な"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-3', 1, 'ほど', 'ほど', (select id from words where primary_form = '程' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"ほど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-3', 2, '嬉しかった', 'うれしかった', (select id from words where primary_form = '嬉しい' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"嬉","r":"うれ"},{"t":"しかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-3', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-4', 0, '勉強すれば', 'べんきょうすれば', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"勉強","r":"べんきょう"},{"t":"すれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-4', 1, 'する', 'する', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-4', 2, 'ほど', 'ほど', (select id from words where primary_form = '程' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"ほど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-4', 3, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-4', 4, '分かる', 'わかる', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"分","r":"わ"},{"t":"かる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-4', 5, 'ようになる', 'ようになる', NULL, 13, 18, '[{"t":"ようになる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hodo-4', 6, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 3, '歩いて', 'あるいて', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"歩","r":"ある"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 4, '行ける', 'いける', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"行","r":"い"},{"t":"ける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 5, 'くらい', 'くらい', NULL, 10, 13, '[{"t":"くらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 6, '近い', 'ちかい', (select id from words where primary_form = '近い' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"近","r":"ちか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-1', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-2', 0, '泣きたい', 'なきたい', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"泣","r":"な"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-2', 1, 'くらい', 'くらい', NULL, 4, 7, '[{"t":"くらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-2', 2, '悲しかった', 'かなしかった', (select id from words where primary_form = '悲しむ' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"悲","r":"かな"},{"t":"しかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-2', 3, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-3', 0, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-3', 1, 'くらい', 'くらい', NULL, 2, 5, '[{"t":"くらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-3', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-3', 3, 'き', 'き', NULL, 6, 7, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-3', 4, 'ます', 'ます', NULL, 7, 9, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-4', 0, '半分', 'はんぶん', (select id from words where primary_form = '半分' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"半分","r":"はんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-4', 1, 'ぐらい', 'ぐらい', NULL, 2, 5, '[{"t":"ぐらい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-4', 2, '残って', 'のこって', (select id from words where primary_form = '残る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"残","r":"のこ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-4', 3, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kurai-4', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-1', 0, '説明', 'せつめい', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"説明","r":"せつめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-1', 2, 'とおり', 'とおり', NULL, 3, 6, '[{"t":"とおり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-1', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-1', 4, '作って', 'つくって', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"作","r":"つく"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-1', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-2', 0, '思った', 'おもった', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"思","r":"おも"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-2', 1, 'とおり', 'とおり', NULL, 3, 6, '[{"t":"とおり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-2', 2, 'だった', 'だった', NULL, 6, 9, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-3', 2, '言った', 'いった', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"言","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-3', 3, 'とおり', 'とおり', NULL, 6, 9, '[{"t":"とおり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-3', 5, 'しました', 'しました', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-3', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 0, '予想', 'よそう', (select id from words where primary_form = '予想' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"予想","r":"よそう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 2, 'とおり', 'とおり', NULL, 3, 6, '[{"t":"とおり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 4, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 5, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 6, '勝った', 'かった', (select id from words where primary_form = '勝つ' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"勝","r":"か"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toori-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 0, '窓', 'まど', (select id from words where primary_form = '窓' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"窓","r":"まど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 2, '開けた', 'あけた', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"開","r":"あ"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 3, 'まま', 'まま', NULL, 5, 7, '[{"t":"まま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 4, '寝て', 'ねて', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"寝","r":"ね"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 5, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 6, 'ま', 'ま', NULL, 10, 11, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 7, 'いました', 'いました', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-1', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 0, '靴', 'くつ', (select id from words where primary_form = '靴' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"靴","r":"くつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 2, '履いた', 'はいた', (select id from words where primary_form = '履く' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"履","r":"は"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 3, 'まま', 'まま', NULL, 5, 7, '[{"t":"まま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 4, '入らない', 'はいらない', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"入","r":"はい"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 5, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-2', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-3', 0, '昔', 'むかし', (select id from words where primary_form = '昔' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"昔","r":"むかし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-3', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-3', 2, 'まま', 'まま', NULL, 2, 4, '[{"t":"まま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-3', 3, 'です', 'です', NULL, 4, 6, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-3', 4, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-4', 0, '立った', 'たった', (select id from words where primary_form = '立つ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"立","r":"た"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-4', 1, 'まま', 'まま', NULL, 3, 5, '[{"t":"まま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-4', 2, '食べた', 'たべた', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"食","r":"た"},{"t":"べた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mama-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-1', 2, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-1', 3, 'だ', 'だ', NULL, 5, 6, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-1', 4, 'っけ', 'っけ', NULL, 6, 8, '[{"t":"っけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-2', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-2', 1, '名前', 'なまえ', (select id from words where primary_form = '名前' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"名前","r":"なまえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-2', 3, '何', 'なん', (select id from words where primary_form = '何' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"何","r":"なん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-2', 4, 'だ', 'だ', NULL, 6, 7, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-2', 5, 'っけ', 'っけ', NULL, 7, 9, '[{"t":"っけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-2', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-3', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-3', 2, '来週', 'らいしゅう', (select id from words where primary_form = '来週' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来週","r":"らいしゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-3', 3, 'だ', 'だ', NULL, 5, 6, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-3', 4, 'っけ', 'っけ', NULL, 6, 8, '[{"t":"っけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-3', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-4', 0, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-4', 2, 'あった', 'あった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"あった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-4', 3, 'っけ', 'っけ', NULL, 6, 8, '[{"t":"っけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kke-4', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-1', 2, '行かない', 'いかない', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"行","r":"い"},{"t":"かない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-1', 3, 'って', 'って', (select id from words where primary_form = 'って' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-1', 4, '言って', 'いって', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"言","r":"い"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-1', 5, 'いた', 'いた', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-1', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-2', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-2', 2, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-2', 3, 'だって', 'だって', (select id from words where primary_form = 'だって' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"だって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-3', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-3', 3, 'って', 'って', (select id from words where primary_form = 'って' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-3', 4, '聞いた', 'きいた', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"聞","r":"き"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-3', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-4', 0, '無理', 'むり', (select id from words where primary_form = '無理' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"無理","r":"むり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-4', 1, 'だって', 'だって', (select id from words where primary_form = 'だって' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"だって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-4', 2, '思った', 'おもった', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"思","r":"おも"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ttequote-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 1, 'なんか', 'なんか', NULL, 1, 4, '[{"t":"なんか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 5, 'き', 'き', NULL, 7, 8, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 6, 'ません', 'ません', NULL, 8, 11, '[{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-1', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-2', 0, '野菜', 'やさい', (select id from words where primary_form = '野菜' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"野菜","r":"やさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-2', 1, 'なんか', 'なんか', NULL, 2, 5, '[{"t":"なんか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-2', 2, '食べた', 'たべた', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"食","r":"た"},{"t":"べた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-2', 3, 'く', 'く', NULL, 8, 9, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-2', 4, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-3', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-3', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-3', 3, 'なんて', 'なんて', NULL, 4, 7, '[{"t":"なんて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-3', 4, '思わなかった', 'おもわなかった', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 7, 13, '[{"t":"思","r":"おも"},{"t":"わなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-3', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-4', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-4', 2, '落ちる', 'おちる', (select id from words where primary_form = '落ちる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"落","r":"お"},{"t":"ちる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-4', 3, 'なんて', 'なんて', NULL, 6, 9, '[{"t":"なんて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-4', 4, '信じられない', 'しんじられない', (select id from words where primary_form = '信じる' and language_id = 'lang-ja' and published order by id limit 1), 9, 15, '[{"t":"信","r":"しん"},{"t":"じられない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nanka-4', 5, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 2, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 4, '静か', 'しずか', (select id from words where primary_form = '静か' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"静","r":"しず"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 6, 'する', 'する', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 7, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 8, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 9, '言った', 'いった', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 14, 17, '[{"t":"言","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-1', 10, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 0, '母', 'はは', (select id from words where primary_form = '母' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"母","r":"はは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 2, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 3, '帰る', 'かえる', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"帰","r":"かえ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 4, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 6, '言われた', 'いわれた', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"言","r":"い"},{"t":"われた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-2', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 0, '医者', 'いしゃ', (select id from words where primary_form = '医者' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"医者","r":"いしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 2, '薬', 'くすり', (select id from words where primary_form = '薬' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"薬","r":"くすり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 4, '飲む', 'のむ', (select id from words where primary_form = '飲む' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"飲","r":"の"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 5, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 6, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 7, '言われました', 'いわれました', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 10, 16, '[{"t":"言","r":"い"},{"t":"われました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-3', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 0, '妹', 'いもうと', (select id from words where primary_form = '妹' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"妹","r":"いもうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 2, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 4, '片付ける', 'かたづける', (select id from words where primary_form = '片付ける' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"片付","r":"かたづ"},{"t":"ける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 5, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 6, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 7, '言いました', 'いいました', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 12, 17, '[{"t":"言","r":"い"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youniiu-4', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-1', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-1', 1, '休ませていただきます', 'やすませていただきます', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 2, 12, '[{"t":"休","r":"やす"},{"t":"ませていただきます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-1', 2, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-2', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-2', 2, '読ませていただきます', 'よませていただきます', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 12, '[{"t":"読","r":"よ"},{"t":"ませていただきます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-2', 3, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-3', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-3', 2, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-3', 3, '帰らせていただきます', 'かえらせていただきます', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 5, 15, '[{"t":"帰","r":"かえ"},{"t":"らせていただきます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-3', 4, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-4', 0, '使わせていただきました', 'つかわせていただきました', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 0, 11, '[{"t":"使","r":"つか"},{"t":"わせていただきました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-saseteitadaku-4', 1, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb);
