-- N3 example sentences, batch 4: what you have no choice about, what might go
-- wrong, and six suffixes.
--
-- お〜ください, 〜ざるを得ない, 〜に違いない, 〜おそれがある and 〜かねない
-- run from polite request through certainty to warning. Then the suffix
-- family: 〜がち, 〜っぽい, 〜だらけ, 〜向け/〜向き and 〜中.
--
-- Three of these are the narrowest the tokeniser has been so far, and it is
-- worth writing down what survives so the next author does not rediscover it:
--
--   〜ざるを得ない cuts clean in the PRESENT only. 中止せざるを得ない,
--   賛成せざるを得ない, 出かけざるを得ない and 下げざるを得ない all pass;
--   得なかった changes the longest-first path and 中止 | せ | ざ | る | を
--   falls apart. Godan verbs are worse — 認めざるを and 頼らざるを are matched
--   whole and glossed as their lemma, which puts a gloss on a particle.
--
--   〜がち only attaches where the index already holds the compound: 忘れがち,
--   買いがち, 使いがち, 寝すぎがち, 太りがち and 食べがち work; 休みがち,
--   曇りがち, 病気がち, 遅れがち, 疲れがち and every する-verb do not.
--
--   〜中 needs a KATAKANA noun in front of it. 会議中 is one unbroken run of
--   kanji, and `splitReading` puts a run's whole reading on its first
--   character, so 中 shipped with no ruby at all — invisible to
--   `check:examples`, which sees a perfectly correct segmentation. ゲーム中,
--   テスト中, アルバイト中 and レッスン中 break the run and keep their ruby.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- o-kudasai
  ('sent-ex-okudasai-1', 'lang-ja', 'どうぞお座りください。', 'どうぞ おすわり ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-okudasai-2', 'lang-ja', '少々お待ちください。', 'しょうしょう おまち ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-okudasai-3', 'lang-ja', '明日お電話ください。', 'あした おでんわ ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-okudasai-4', 'lang-ja', '後でお読みください。', 'あと で およみ ください。', 'lvl-ja-n3', 'authored', true),
  -- zaru-o-enai
  ('sent-ex-zaruoenai-1', 'lang-ja', '会議を中止せざるを得ない。', 'かいぎ お ちゅうし せざる お えない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-zaruoenai-2', 'lang-ja', '彼の意見に賛成せざるを得ない。', 'かれ の いけん に さんせい せざる お えない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-zaruoenai-3', 'lang-ja', '早く出かけざるを得ない。', 'はやく でかけざる お えない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-zaruoenai-4', 'lang-ja', '値段を下げざるを得ない。', 'ねだん お さげざる お えない。', 'lvl-ja-n3', 'authored', true),
  -- ni-chigainai
  ('sent-ex-nichigainai-1', 'lang-ja', '彼は知っているに違いない。', 'かれ わ しって いる に ちがいない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nichigainai-2', 'lang-ja', 'あの店は高いに違いない。', 'あの みせ わ たかい に ちがいない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nichigainai-3', 'lang-ja', 'これは彼の本に違いない。', 'これ わ かれ の ほん に ちがいない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nichigainai-4', 'lang-ja', '彼女は忘れたに違いない。', 'かのじょ わ わすれた に ちがいない。', 'lvl-ja-n3', 'authored', true),
  -- osore-ga-aru
  ('sent-ex-osoregaaru-1', 'lang-ja', '台風が来るおそれがあります。', 'たいふう が くる おそれ が あります。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-osoregaaru-2', 'lang-ja', '川の水が増えるおそれがある。', 'かわ の みず が ふえる おそれ が ある。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-osoregaaru-3', 'lang-ja', '病気が広がるおそれがある。', 'びょうき が ひろがる おそれ が ある。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-osoregaaru-4', 'lang-ja', '事故が起こるおそれがあります。', 'じこ が おこる おそれ が あります。', 'lvl-ja-n3', 'authored', true),
  -- kanenai
  ('sent-ex-kanenai-1', 'lang-ja', 'そんな運転では事故を起こしかねない。', 'そんな うんてん で わ じこ お おこしかねない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kanenai-2', 'lang-ja', '彼なら言いかねない。', 'かれ なら いいかねない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kanenai-3', 'lang-ja', '無理をすると病気になりかねない。', 'むり お する と びょうき に なりかねない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kanenai-4', 'lang-ja', '寝ないと倒れかねない。', 'ねない と たおれかねない。', 'lvl-ja-n3', 'authored', true),
  -- gachi
  ('sent-ex-gachi-1', 'lang-ja', '彼は約束を忘れがちだ。', 'かれ わ やくそく お わすれがち だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gachi-2', 'lang-ja', '安いものを買いがちです。', 'やすい もの お かいがち です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gachi-3', 'lang-ja', '同じ言葉を使いがちだ。', 'おなじ ことば お つかいがち だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gachi-4', 'lang-ja', '休みの日は寝すぎがちだ。', 'やすみ の ひ わ ねすぎがち だ。', 'lvl-ja-n3', 'authored', true),
  -- ppoi
  ('sent-ex-ppoi-1', 'lang-ja', '彼は忘れっぽい。', 'かれ わ わすれっぽい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-ppoi-2', 'lang-ja', '子供っぽいところがある。', 'こども っぽい ところ が ある。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-ppoi-3', 'lang-ja', 'あの服は安っぽい。', 'あの ふく わ やすっぽい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-ppoi-4', 'lang-ja', '彼は怒りっぽい。', 'かれ わ おこりっぽい。', 'lvl-ja-n3', 'authored', true),
  -- darake
  ('sent-ex-darake-1', 'lang-ja', '服が泥だらけになった。', 'ふく が どろだらけ に なった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-darake-2', 'lang-ja', '彼の作文は間違いだらけだ。', 'かれ の さくぶん わ まちがいだらけ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-darake-3', 'lang-ja', '机の上は本だらけだ。', 'つくえ の うえ わ ほんだらけ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-darake-4', 'lang-ja', '手が傷だらけだ。', 'て が きずだらけ だ。', 'lvl-ja-n3', 'authored', true),
  -- muke-muki
  ('sent-ex-mukemuki-1', 'lang-ja', '子供向けの本です。', 'こども むけ の ほん です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-mukemuki-2', 'lang-ja', 'あの部屋は南向きです。', 'あの へや わ みなみむき です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-mukemuki-3', 'lang-ja', '学生向けの値段です。', 'がくせい むけ の ねだん です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-mukemuki-4', 'lang-ja', 'あの店は若い人向けです。', 'あの みせ わ わかい ひと むけ です。', 'lvl-ja-n3', 'authored', true),
  -- chuu
  ('sent-ex-chuu-1', 'lang-ja', 'ゲーム中に電話が鳴った。', 'ゲーム ちゅう に でんわ が なった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-chuu-2', 'lang-ja', 'テスト中は静かにしてください。', 'テスト ちゅう わ しずか に して ください。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-chuu-3', 'lang-ja', '兄はアルバイト中です。', 'あに わ アルバイト ちゅう です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-chuu-4', 'lang-ja', 'レッスン中は入らないでください。', 'レッスン ちゅう わ はいらないで ください。', 'lvl-ja-n3', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-okudasai-1', 'sent-ex-okudasai-1', 'en', 'Please take a seat.', 'authored'),
  ('st-ex-okudasai-2', 'sent-ex-okudasai-2', 'en', 'One moment, please.', 'authored'),
  ('st-ex-okudasai-3', 'sent-ex-okudasai-3', 'en', 'Please ring tomorrow.', 'authored'),
  ('st-ex-okudasai-4', 'sent-ex-okudasai-4', 'en', 'Please read it later.', 'authored'),
  ('st-ex-zaruoenai-1', 'sent-ex-zaruoenai-1', 'en', 'We have no choice but to call off the meeting.', 'authored'),
  ('st-ex-zaruoenai-2', 'sent-ex-zaruoenai-2', 'en', 'I cannot help but agree with his view.', 'authored'),
  ('st-ex-zaruoenai-3', 'sent-ex-zaruoenai-3', 'en', 'I have no choice but to leave early.', 'authored'),
  ('st-ex-zaruoenai-4', 'sent-ex-zaruoenai-4', 'en', 'We have no option but to lower the price.', 'authored'),
  ('st-ex-nichigainai-1', 'sent-ex-nichigainai-1', 'en', 'He must know.', 'authored'),
  ('st-ex-nichigainai-2', 'sent-ex-nichigainai-2', 'en', 'That shop is bound to be expensive.', 'authored'),
  ('st-ex-nichigainai-3', 'sent-ex-nichigainai-3', 'en', 'This must be his book.', 'authored'),
  ('st-ex-nichigainai-4', 'sent-ex-nichigainai-4', 'en', 'She must have forgotten.', 'authored'),
  ('st-ex-osoregaaru-1', 'sent-ex-osoregaaru-1', 'en', 'There is a risk that a typhoon will come.', 'authored'),
  ('st-ex-osoregaaru-2', 'sent-ex-osoregaaru-2', 'en', 'There is a danger the river will rise.', 'authored'),
  ('st-ex-osoregaaru-3', 'sent-ex-osoregaaru-3', 'en', 'There is a risk the illness will spread.', 'authored'),
  ('st-ex-osoregaaru-4', 'sent-ex-osoregaaru-4', 'en', 'There is a danger of an accident happening.', 'authored'),
  ('st-ex-kanenai-1', 'sent-ex-kanenai-1', 'en', 'Driving like that, he could well cause an accident.', 'authored'),
  ('st-ex-kanenai-2', 'sent-ex-kanenai-2', 'en', 'He is quite capable of saying it.', 'authored'),
  ('st-ex-kanenai-3', 'sent-ex-kanenai-3', 'en', 'Overdo it and you could well end up ill.', 'authored'),
  ('st-ex-kanenai-4', 'sent-ex-kanenai-4', 'en', 'If you do not sleep you could well collapse.', 'authored'),
  ('st-ex-gachi-1', 'sent-ex-gachi-1', 'en', 'He tends to forget his promises.', 'authored'),
  ('st-ex-gachi-2', 'sent-ex-gachi-2', 'en', 'I have a tendency to buy the cheap thing.', 'authored'),
  ('st-ex-gachi-3', 'sent-ex-gachi-3', 'en', 'I tend to use the same words.', 'authored'),
  ('st-ex-gachi-4', 'sent-ex-gachi-4', 'en', 'On my days off I tend to oversleep.', 'authored'),
  ('st-ex-ppoi-1', 'sent-ex-ppoi-1', 'en', 'He is forgetful.', 'authored'),
  ('st-ex-ppoi-2', 'sent-ex-ppoi-2', 'en', 'There is something childish about him.', 'authored'),
  ('st-ex-ppoi-3', 'sent-ex-ppoi-3', 'en', 'Those clothes look cheap.', 'authored'),
  ('st-ex-ppoi-4', 'sent-ex-ppoi-4', 'en', 'He is quick to anger.', 'authored'),
  ('st-ex-darake-1', 'sent-ex-darake-1', 'en', 'My clothes got covered in mud.', 'authored'),
  ('st-ex-darake-2', 'sent-ex-darake-2', 'en', 'His essay is full of mistakes.', 'authored'),
  ('st-ex-darake-3', 'sent-ex-darake-3', 'en', 'The desk is covered in books.', 'authored'),
  ('st-ex-darake-4', 'sent-ex-darake-4', 'en', 'My hands are covered in cuts.', 'authored'),
  ('st-ex-mukemuki-1', 'sent-ex-mukemuki-1', 'en', 'It is a book for children.', 'authored'),
  ('st-ex-mukemuki-2', 'sent-ex-mukemuki-2', 'en', 'That room faces south.', 'authored'),
  ('st-ex-mukemuki-3', 'sent-ex-mukemuki-3', 'en', 'It is a price aimed at students.', 'authored'),
  ('st-ex-mukemuki-4', 'sent-ex-mukemuki-4', 'en', 'That shop is aimed at young people.', 'authored'),
  ('st-ex-chuu-1', 'sent-ex-chuu-1', 'en', 'The phone rang while I was playing a game.', 'authored'),
  ('st-ex-chuu-2', 'sent-ex-chuu-2', 'en', 'Please be quiet during the test.', 'authored'),
  ('st-ex-chuu-3', 'sent-ex-chuu-3', 'en', 'My older brother is at work on his part-time job.', 'authored'),
  ('st-ex-chuu-4', 'sent-ex-chuu-4', 'en', 'Please do not come in during the lesson.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('o-kudasai', 'sent-ex-okudasai-1', 0),
  ('o-kudasai', 'sent-ex-okudasai-2', 1),
  ('o-kudasai', 'sent-ex-okudasai-3', 2),
  ('o-kudasai', 'sent-ex-okudasai-4', 3),
  ('zaru-o-enai', 'sent-ex-zaruoenai-1', 0),
  ('zaru-o-enai', 'sent-ex-zaruoenai-2', 1),
  ('zaru-o-enai', 'sent-ex-zaruoenai-3', 2),
  ('zaru-o-enai', 'sent-ex-zaruoenai-4', 3),
  ('ni-chigainai', 'sent-ex-nichigainai-1', 0),
  ('ni-chigainai', 'sent-ex-nichigainai-2', 1),
  ('ni-chigainai', 'sent-ex-nichigainai-3', 2),
  ('ni-chigainai', 'sent-ex-nichigainai-4', 3),
  ('osore-ga-aru', 'sent-ex-osoregaaru-1', 0),
  ('osore-ga-aru', 'sent-ex-osoregaaru-2', 1),
  ('osore-ga-aru', 'sent-ex-osoregaaru-3', 2),
  ('osore-ga-aru', 'sent-ex-osoregaaru-4', 3),
  ('kanenai', 'sent-ex-kanenai-1', 0),
  ('kanenai', 'sent-ex-kanenai-2', 1),
  ('kanenai', 'sent-ex-kanenai-3', 2),
  ('kanenai', 'sent-ex-kanenai-4', 3),
  ('gachi', 'sent-ex-gachi-1', 0),
  ('gachi', 'sent-ex-gachi-2', 1),
  ('gachi', 'sent-ex-gachi-3', 2),
  ('gachi', 'sent-ex-gachi-4', 3),
  ('ppoi', 'sent-ex-ppoi-1', 0),
  ('ppoi', 'sent-ex-ppoi-2', 1),
  ('ppoi', 'sent-ex-ppoi-3', 2),
  ('ppoi', 'sent-ex-ppoi-4', 3),
  ('darake', 'sent-ex-darake-1', 0),
  ('darake', 'sent-ex-darake-2', 1),
  ('darake', 'sent-ex-darake-3', 2),
  ('darake', 'sent-ex-darake-4', 3),
  ('muke-muki', 'sent-ex-mukemuki-1', 0),
  ('muke-muki', 'sent-ex-mukemuki-2', 1),
  ('muke-muki', 'sent-ex-mukemuki-3', 2),
  ('muke-muki', 'sent-ex-mukemuki-4', 3),
  ('chuu', 'sent-ex-chuu-1', 0),
  ('chuu', 'sent-ex-chuu-2', 1),
  ('chuu', 'sent-ex-chuu-3', 2),
  ('chuu', 'sent-ex-chuu-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-okudasai-1', 'sent-ex-okudasai-2', 'sent-ex-okudasai-3', 'sent-ex-okudasai-4', 'sent-ex-zaruoenai-1', 'sent-ex-zaruoenai-2', 'sent-ex-zaruoenai-3', 'sent-ex-zaruoenai-4', 'sent-ex-nichigainai-1', 'sent-ex-nichigainai-2', 'sent-ex-nichigainai-3', 'sent-ex-nichigainai-4', 'sent-ex-osoregaaru-1', 'sent-ex-osoregaaru-2', 'sent-ex-osoregaaru-3', 'sent-ex-osoregaaru-4', 'sent-ex-kanenai-1', 'sent-ex-kanenai-2', 'sent-ex-kanenai-3', 'sent-ex-kanenai-4', 'sent-ex-gachi-1', 'sent-ex-gachi-2', 'sent-ex-gachi-3', 'sent-ex-gachi-4', 'sent-ex-ppoi-1', 'sent-ex-ppoi-2', 'sent-ex-ppoi-3', 'sent-ex-ppoi-4', 'sent-ex-darake-1', 'sent-ex-darake-2', 'sent-ex-darake-3', 'sent-ex-darake-4', 'sent-ex-mukemuki-1', 'sent-ex-mukemuki-2', 'sent-ex-mukemuki-3', 'sent-ex-mukemuki-4', 'sent-ex-chuu-1', 'sent-ex-chuu-2', 'sent-ex-chuu-3', 'sent-ex-chuu-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-okudasai-1', 0, 'どうぞ', 'どうぞ', (select id from words where primary_form = 'どうぞ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"どうぞ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-1', 1, 'お', 'お', NULL, 3, 4, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-1', 2, '座りください', 'すわりください', (select id from words where primary_form = '座る' and language_id = 'lang-ja' and published order by id limit 1), 4, 10, '[{"t":"座","r":"すわ"},{"t":"りください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-1', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-2', 0, '少々', 'しょうしょう', (select id from words where primary_form = '少々' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"少々","r":"しょうしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-2', 1, 'お', 'お', NULL, 2, 3, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-2', 2, '待ちください', 'まちください', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"待","r":"ま"},{"t":"ちください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-3', 0, '明日', 'あした', (select id from words where primary_form = '明日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"明日","r":"あした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-3', 1, 'お', 'お', NULL, 2, 3, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-3', 2, '電話', 'でんわ', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-3', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-4', 0, '後で', 'あとで', NULL, 0, 2, '[{"t":"後","r":"あと"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-4', 1, 'お', 'お', NULL, 2, 3, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-4', 2, '読み', 'よみ', (select id from words where primary_form = '読み' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"読","r":"よ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-4', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okudasai-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-1', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-1', 2, '中止', 'ちゅうし', (select id from words where primary_form = '中止' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"中止","r":"ちゅうし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-1', 3, 'せ', 'せ', NULL, 5, 6, '[{"t":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-1', 4, 'ざるを得ない', 'ざるを得ない', NULL, 6, 12, '[{"t":"ざるを"},{"t":"得","r":"得"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-2', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-2', 1, '意見', 'いけん', (select id from words where primary_form = '意見' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"意見","r":"いけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-2', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-2', 3, '賛成', 'さんせい', (select id from words where primary_form = '賛成' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"賛成","r":"さんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-2', 4, 'せ', 'せ', NULL, 7, 8, '[{"t":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-2', 5, 'ざるを得ない', 'ざるを得ない', NULL, 8, 14, '[{"t":"ざるを"},{"t":"得","r":"得"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-3', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-3', 1, '出', 'で', (select id from words where primary_form = '出' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"出","r":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-3', 2, 'かけ', 'かけ', NULL, 3, 5, '[{"t":"かけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-3', 3, 'ざるを得ない', 'ざるを得ない', NULL, 5, 11, '[{"t":"ざるを"},{"t":"得","r":"得"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-3', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-4', 0, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-4', 2, '下', 'さ', (select id from words where primary_form = '下' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"下","r":"さ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-4', 3, 'げ', 'げ', NULL, 4, 5, '[{"t":"げ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-4', 4, 'ざるを得ない', 'ざるを得ない', NULL, 5, 11, '[{"t":"ざるを"},{"t":"得","r":"得"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zaruoenai-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-1', 2, '知って', 'しって', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"知","r":"し"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-1', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-1', 5, '違いない', 'ちがいない', (select id from words where primary_form = '違いない' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"違","r":"ちが"},{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-2', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-2', 3, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-2', 5, '違いない', 'ちがいない', (select id from words where primary_form = '違いない' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"違","r":"ちが"},{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-3', 0, 'これは', 'これは', NULL, 0, 3, '[{"t":"これは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-3', 1, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-3', 2, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-3', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-3', 4, '違いない', 'ちがいない', (select id from words where primary_form = '違いない' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"違","r":"ちが"},{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-4', 0, '彼女', 'かのじょ', (select id from words where primary_form = '彼女' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼女","r":"かのじょ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-4', 2, '忘れた', 'わすれた', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"忘","r":"わす"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-4', 4, '違いない', 'ちがいない', (select id from words where primary_form = '違いない' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"違","r":"ちが"},{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nichigainai-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 0, '台風', 'たいふう', (select id from words where primary_form = '台風' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"台風","r":"たいふう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 3, 'お', 'お', NULL, 5, 6, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 4, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 5, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 6, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-1', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-2', 0, '川', 'かわ', (select id from words where primary_form = '川' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"川","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-2', 2, '水', 'みず', (select id from words where primary_form = '水' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"水","r":"みず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-2', 3, 'が', 'が', NULL, 3, 4, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-2', 4, '増える', 'ふえる', (select id from words where primary_form = '増える' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"増","r":"ふ"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-2', 5, 'おそれがある', 'おそれがある', NULL, 7, 13, '[{"t":"おそれがある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-3', 0, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-3', 2, '広がる', 'ひろがる', (select id from words where primary_form = '広がる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"広","r":"ひろ"},{"t":"がる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-3', 3, 'おそれがある', 'おそれがある', NULL, 6, 12, '[{"t":"おそれがある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 0, '事故', 'じこ', (select id from words where primary_form = '事故' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"事故","r":"じこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 2, '起こる', 'おこる', (select id from words where primary_form = '起こる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"起","r":"お"},{"t":"こる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 3, 'お', 'お', NULL, 6, 7, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 4, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 5, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 6, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-osoregaaru-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-1', 0, 'そんな', 'そんな', (select id from words where primary_form = 'そんな' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"そんな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-1', 1, '運転', 'うんてん', (select id from words where primary_form = '運転' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"運転","r":"うんてん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-1', 2, 'では', 'では', (select id from words where primary_form = 'では' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"では"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-1', 3, '事故', 'じこ', (select id from words where primary_form = '事故' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"事故","r":"じこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-1', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-1', 5, '起こしかねない', 'おこしかねない', (select id from words where primary_form = '起こす' and language_id = 'lang-ja' and published order by id limit 1), 10, 17, '[{"t":"起","r":"お"},{"t":"こしかねない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-1', 6, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-2', 1, 'なら', 'なら', NULL, 1, 3, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-2', 2, '言いかねない', 'いいかねない', (select id from words where primary_form = '言いつける' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"言","r":"い"},{"t":"いかねない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 0, '無理', 'むり', (select id from words where primary_form = '無理' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"無理","r":"むり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 2, 'すると', 'すると', (select id from words where primary_form = 'すると' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"すると"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 3, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 5, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 6, 'り', 'り', NULL, 10, 11, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 7, 'かねない', 'かねない', NULL, 11, 15, '[{"t":"かねない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-3', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-4', 0, '寝ない', 'ねない', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"寝","r":"ね"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-4', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-4', 2, '倒れかねない', 'たおれかねない', (select id from words where primary_form = '倒れる' and language_id = 'lang-ja' and published order by id limit 1), 4, 10, '[{"t":"倒","r":"たお"},{"t":"れかねない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kanenai-4', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-1', 2, '約束', 'やくそく', (select id from words where primary_form = '約束' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"約束","r":"やくそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-1', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-1', 4, '忘れがちだ', 'わすれがちだ', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"忘","r":"わす"},{"t":"れがちだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-2', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-2', 1, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-2', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-2', 3, '買いがちです', 'かいがちです', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 5, 11, '[{"t":"買","r":"か"},{"t":"いがちです"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-3', 0, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-3', 1, '言葉', 'ことば', (select id from words where primary_form = '言葉' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"言葉","r":"ことば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-3', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-3', 3, '使いがちだ', 'つかいがちだ', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"使","r":"つか"},{"t":"いがちだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-4', 0, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-4', 2, '日', 'ひ', (select id from words where primary_form = '日' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"日","r":"ひ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-4', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-4', 4, '寝すぎがちだ', 'ねすぎがちだ', (select id from words where primary_form = '寝かせる' and language_id = 'lang-ja' and published order by id limit 1), 5, 11, '[{"t":"寝","r":"ね"},{"t":"すぎがちだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gachi-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-1', 2, '忘れっぽい', 'わすれっぽい', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"忘","r":"わす"},{"t":"れっぽい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-2', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-2', 1, 'っぽい', 'っぽい', NULL, 2, 5, '[{"t":"っぽい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-2', 2, 'ところ', 'ところ', NULL, 5, 8, '[{"t":"ところ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-2', 3, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-2', 4, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-3', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-3', 1, '服', 'ふく', (select id from words where primary_form = '服' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"服","r":"ふく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-3', 3, '安っぽい', 'やすっぽい', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"安","r":"やす"},{"t":"っぽい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-4', 2, '怒り', 'おこり', (select id from words where primary_form = '怒り' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"怒","r":"おこ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-4', 3, 'っぽい', 'っぽい', NULL, 4, 7, '[{"t":"っぽい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ppoi-4', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-1', 0, '服', 'ふく', (select id from words where primary_form = '服' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"服","r":"ふく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-1', 2, '泥', 'どろ', (select id from words where primary_form = '泥' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"泥","r":"どろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-1', 3, 'だらけ', 'だらけ', NULL, 3, 6, '[{"t":"だらけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-1', 5, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-1', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-2', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-2', 1, '作文', 'さくぶん', (select id from words where primary_form = '作文' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"作文","r":"さくぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-2', 3, '間違い', 'まちがい', (select id from words where primary_form = '間違い' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"間違","r":"まちが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-2', 4, 'だらけ', 'だらけ', NULL, 8, 11, '[{"t":"だらけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-2', 5, 'だ', 'だ', NULL, 11, 12, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 0, '机', 'つくえ', (select id from words where primary_form = '机' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 2, '上', 'うえ', (select id from words where primary_form = '上' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"上","r":"うえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 4, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 5, 'だらけ', 'だらけ', NULL, 5, 8, '[{"t":"だらけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 6, 'だ', 'だ', NULL, 8, 9, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-3', 7, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-4', 0, '手', 'て', (select id from words where primary_form = '手' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"手","r":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-4', 2, '傷', 'きず', (select id from words where primary_form = '傷' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"傷","r":"きず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-4', 3, 'だらけ', 'だらけ', NULL, 3, 6, '[{"t":"だらけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-4', 4, 'だ', 'だ', NULL, 6, 7, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-darake-4', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-1', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-1', 1, '向け', 'むけ', (select id from words where primary_form = '向く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"向","r":"む"},{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-1', 2, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-1', 3, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-1', 4, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-1', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-2', 1, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-2', 3, '南', 'みなみ', (select id from words where primary_form = '南' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"南","r":"みなみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-2', 4, '向き', '向き', NULL, 6, 8, '[{"t":"向","r":"向"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-2', 5, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-2', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-3', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-3', 1, '向け', 'むけ', (select id from words where primary_form = '向く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"向","r":"む"},{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-3', 2, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-3', 3, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-3', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 3, '若い', 'わかい', (select id from words where primary_form = '若い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"若","r":"わか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 4, '人', 'ひとむ', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"人","r":"ひとむ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 5, '向け', 'むけ', (select id from words where primary_form = '向く' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"向","r":"む"},{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 6, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mukemuki-4', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-1', 0, 'ゲーム', 'ゲーム', (select id from words where primary_form = 'ゲーム' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"ゲーム"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-1', 1, '中', 'ちゅう', (select id from words where primary_form = '中' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"中","r":"ちゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-1', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-1', 3, '電話', 'でんわ', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-1', 4, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-1', 5, '鳴った', 'なった', (select id from words where primary_form = '鳴る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"鳴","r":"な"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 0, 'テスト', 'テスト', (select id from words where primary_form = 'テスト' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"テスト"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 1, '中', 'ちゅう', (select id from words where primary_form = '中' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"中","r":"ちゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 3, '静か', 'しずか', (select id from words where primary_form = '静か' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"静","r":"しず"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 5, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-2', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-3', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-3', 2, 'アルバイト', 'アルバイト', (select id from words where primary_form = 'アルバイト' and language_id = 'lang-ja' and published order by id limit 1), 2, 7, '[{"t":"アルバイト"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-3', 3, '中', 'ちゅう', (select id from words where primary_form = '中' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"中","r":"ちゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-3', 4, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-3', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-4', 0, 'レッスン', 'レッスン', (select id from words where primary_form = 'レッスン' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"レッスン"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-4', 1, '中', 'ちゅう', (select id from words where primary_form = '中' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"中","r":"ちゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-4', 3, '入らない', 'はいらない', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"入","r":"はい"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-4', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-chuu-4', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb);
