-- N3 example sentences, batch 5: half-done, hard to do, and whose fault it was.
--
-- 〜気味 and 〜かけ describe something partway; 〜がたい and 〜ようがない
-- describe something you cannot manage. 〜つつ, 〜ながらも, 〜ものの and
-- 〜くせに all concede a point before contradicting it, and the last two —
-- 〜せいで and 〜おかげで — split blame from credit for the same shape of
-- sentence, which is why they sit next to each other here.
--
-- Two rewordings:
--
--   食べかけのパンを置いた matched 食べかけのパンを as ONE token glossed
--   "to eat" — the longest-first index swallowed the whole phrase along with
--   its particle. Breaking the run with 机の上に … があります keeps the pieces
--   apart.
--
--   いい店 shreds to い|い: the index holds 良い but not the kana spelling.
--   The shop is 有名 instead.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- gimi
  ('sent-ex-gimi-1', 'lang-ja', '今日は風邪気味です。', 'きょう わ かぜ ぎみ です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gimi-2', 'lang-ja', '最近疲れ気味だ。', 'さいきん つかれぎみ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gimi-3', 'lang-ja', '少し太り気味です。', 'すこし ふとりぎみ です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gimi-4', 'lang-ja', '電車が遅れ気味です。', 'でんしゃ が おくれぎみ です。', 'lvl-ja-n3', 'authored', true),
  -- kake
  ('sent-ex-kake-1', 'lang-ja', '読みかけの本があります。', 'よみかけ の ほん が あります。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kake-2', 'lang-ja', '机の上に食べかけのケーキがあります。', 'つくえ の うえ に たべかけ の ケーキ が あります。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kake-3', 'lang-ja', '言いかけて、止めた。', 'いいかけて、やめた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kake-4', 'lang-ja', '作りかけの料理があります。', 'つくりかけ の りょうり が あります。', 'lvl-ja-n3', 'authored', true),
  -- nikui-gatai
  ('sent-ex-gatai-1', 'lang-ja', '信じがたい話だ。', 'しんじがたい はなし だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gatai-2', 'lang-ja', '忘れがたい思い出です。', 'わすれがたい おもいで です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gatai-3', 'lang-ja', '動かしがたい事実だ。', 'うごかしがたい じじつ だ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-gatai-4', 'lang-ja', '許しがたい行動だ。', 'ゆるしがたい こうどう だ。', 'lvl-ja-n3', 'authored', true),
  -- you-ga-nai
  ('sent-ex-youganai-1', 'lang-ja', '連絡のしようがない。', 'れんらく の しようがない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-youganai-2', 'lang-ja', '壊れていて直しようがない。', 'こわれて いて なおしようがない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-youganai-3', 'lang-ja', '答えようがない。', 'こたえようがない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-youganai-4', 'lang-ja', '今からでは間に合わせようがない。', 'いま から で わ まにあわせようがない。', 'lvl-ja-n3', 'authored', true),
  -- tsutsu
  ('sent-ex-tsutsu-1', 'lang-ja', '悪いと知りつつ、続けた。', 'わるい と しりつつ、つづけた。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tsutsu-2', 'lang-ja', '音楽を聞きつつ勉強する。', 'おんがく お ききつつ べんきょう する。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tsutsu-3', 'lang-ja', '町は変わりつつある。', 'まち わ かわりつつ ある。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tsutsu-4', 'lang-ja', '体は治りつつあります。', 'からだ わ なおりつつ あります。', 'lvl-ja-n3', 'authored', true),
  -- nagara-mo
  ('sent-ex-nagaramo-1', 'lang-ja', '小さいながらも、有名な店です。', 'ちいさい ながら も、ゆうめい な みせ です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nagaramo-2', 'lang-ja', '知っていながらも、言わなかった。', 'しって いながら も、いわなかった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nagaramo-3', 'lang-ja', '貧しいながらも幸せだった。', 'まずしい ながら も しあわせ だった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-nagaramo-4', 'lang-ja', '若いながらも、よく働く。', 'わかい ながら も、よく はたらく。', 'lvl-ja-n3', 'authored', true),
  -- mono-no
  ('sent-ex-monono-1', 'lang-ja', '約束したものの、行けなかった。', 'やくそく した ものの、いけなかった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-monono-2', 'lang-ja', '買ったものの、使っていない。', 'かった ものの、つかって いない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-monono-3', 'lang-ja', '難しいものの、面白い。', 'むずかしい ものの、おもしろい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-monono-4', 'lang-ja', '試験を受けたものの、落ちました。', 'しけん お うけた ものの、おちました。', 'lvl-ja-n3', 'authored', true),
  -- kuseni
  ('sent-ex-kuseni-1', 'lang-ja', '知っているくせに、教えない。', 'しって いる くせ に、おしえない。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kuseni-2', 'lang-ja', '子供のくせに難しい言葉を使う。', 'こども の くせ に むずかしい ことば お つかう。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kuseni-3', 'lang-ja', '下手なくせに、いつも歌う。', 'へた な くせ に、いつも うたう。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kuseni-4', 'lang-ja', 'お金があるくせに、払わない。', 'おかね が ある くせ に、はらわない。', 'lvl-ja-n3', 'authored', true),
  -- sei-de
  ('sent-ex-seide-1', 'lang-ja', '雨のせいで試合が中止になった。', 'あめ の せい で しあい が ちゅうし に なった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-seide-2', 'lang-ja', '風邪のせいで学校を休んだ。', 'かぜ の せい で がっこう お やすんだ。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-seide-3', 'lang-ja', '電車が遅れたせいで、遅刻した。', 'でんしゃ が おくれた せい で、ちこく した。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-seide-4', 'lang-ja', '彼のせいで失敗した。', 'かれ の せい で しっぱい した。', 'lvl-ja-n3', 'authored', true),
  -- okage-de
  ('sent-ex-okagede-1', 'lang-ja', '先生のおかげで合格しました。', 'せんせい の おかげ で ごうかく しました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-okagede-2', 'lang-ja', '薬のおかげで元気になった。', 'くすり の おかげ で げんき に なった。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-okagede-3', 'lang-ja', '彼のおかげで助かりました。', 'かれ の おかげ で たすかりました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-okagede-4', 'lang-ja', '天気がよかったおかげで、楽しい旅行になった。', 'てんき が よかった おかげ で、たのしい りょこう に なった。', 'lvl-ja-n3', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-gimi-1', 'sent-ex-gimi-1', 'en', 'I feel a bit of a cold coming on today.', 'authored'),
  ('st-ex-gimi-2', 'sent-ex-gimi-2', 'en', 'I have been a little tired lately.', 'authored'),
  ('st-ex-gimi-3', 'sent-ex-gimi-3', 'en', 'I am putting on a bit of weight.', 'authored'),
  ('st-ex-gimi-4', 'sent-ex-gimi-4', 'en', 'The trains are running slightly late.', 'authored'),
  ('st-ex-kake-1', 'sent-ex-kake-1', 'en', 'I have a book I am partway through.', 'authored'),
  ('st-ex-kake-2', 'sent-ex-kake-2', 'en', 'There is a half-eaten cake on the desk.', 'authored'),
  ('st-ex-kake-3', 'sent-ex-kake-3', 'en', 'I started to say it and stopped.', 'authored'),
  ('st-ex-kake-4', 'sent-ex-kake-4', 'en', 'There is a half-made dish.', 'authored'),
  ('st-ex-gatai-1', 'sent-ex-gatai-1', 'en', 'It is a hard story to believe.', 'authored'),
  ('st-ex-gatai-2', 'sent-ex-gatai-2', 'en', 'It is a memory I find hard to forget.', 'authored'),
  ('st-ex-gatai-3', 'sent-ex-gatai-3', 'en', 'It is a fact that cannot be shifted.', 'authored'),
  ('st-ex-gatai-4', 'sent-ex-gatai-4', 'en', 'It is unforgivable behaviour.', 'authored'),
  ('st-ex-youganai-1', 'sent-ex-youganai-1', 'en', 'There is no way of getting in touch.', 'authored'),
  ('st-ex-youganai-2', 'sent-ex-youganai-2', 'en', 'It is broken and there is no way of fixing it.', 'authored'),
  ('st-ex-youganai-3', 'sent-ex-youganai-3', 'en', 'There is no way to answer that.', 'authored'),
  ('st-ex-youganai-4', 'sent-ex-youganai-4', 'en', 'From here there is no way of making it in time.', 'authored'),
  ('st-ex-tsutsu-1', 'sent-ex-tsutsu-1', 'en', 'Knowing it was wrong, I carried on all the same.', 'authored'),
  ('st-ex-tsutsu-2', 'sent-ex-tsutsu-2', 'en', 'I study while listening to music.', 'authored'),
  ('st-ex-tsutsu-3', 'sent-ex-tsutsu-3', 'en', 'The town is in the middle of changing.', 'authored'),
  ('st-ex-tsutsu-4', 'sent-ex-tsutsu-4', 'en', 'My body is on the mend.', 'authored'),
  ('st-ex-nagaramo-1', 'sent-ex-nagaramo-1', 'en', 'Small though it is, it is a well-known shop.', 'authored'),
  ('st-ex-nagaramo-2', 'sent-ex-nagaramo-2', 'en', 'Even though he knew, he said nothing.', 'authored'),
  ('st-ex-nagaramo-3', 'sent-ex-nagaramo-3', 'en', 'Poor though they were, they were happy.', 'authored'),
  ('st-ex-nagaramo-4', 'sent-ex-nagaramo-4', 'en', 'Young as he is, he works hard.', 'authored'),
  ('st-ex-monono-1', 'sent-ex-monono-1', 'en', 'I promised, and yet I could not go.', 'authored'),
  ('st-ex-monono-2', 'sent-ex-monono-2', 'en', 'I bought it, and yet I have not used it.', 'authored'),
  ('st-ex-monono-3', 'sent-ex-monono-3', 'en', 'It is difficult, but interesting all the same.', 'authored'),
  ('st-ex-monono-4', 'sent-ex-monono-4', 'en', 'I sat the exam, but I failed it.', 'authored'),
  ('st-ex-kuseni-1', 'sent-ex-kuseni-1', 'en', 'He knows perfectly well, and still will not tell me.', 'authored'),
  ('st-ex-kuseni-2', 'sent-ex-kuseni-2', 'en', 'He is only a child and yet he uses difficult words.', 'authored'),
  ('st-ex-kuseni-3', 'sent-ex-kuseni-3', 'en', 'He is no good at it and still sings all the time.', 'authored'),
  ('st-ex-kuseni-4', 'sent-ex-kuseni-4', 'en', 'He has the money and yet he will not pay.', 'authored'),
  ('st-ex-seide-1', 'sent-ex-seide-1', 'en', 'The match was called off because of the rain.', 'authored'),
  ('st-ex-seide-2', 'sent-ex-seide-2', 'en', 'I was off school because of a cold.', 'authored'),
  ('st-ex-seide-3', 'sent-ex-seide-3', 'en', 'The train was late, and because of that I was late in.', 'authored'),
  ('st-ex-seide-4', 'sent-ex-seide-4', 'en', 'It went wrong because of him.', 'authored'),
  ('st-ex-okagede-1', 'sent-ex-okagede-1', 'en', 'Thanks to the teacher I passed.', 'authored'),
  ('st-ex-okagede-2', 'sent-ex-okagede-2', 'en', 'Thanks to the medicine I got better.', 'authored'),
  ('st-ex-okagede-3', 'sent-ex-okagede-3', 'en', 'Thanks to him I was saved.', 'authored'),
  ('st-ex-okagede-4', 'sent-ex-okagede-4', 'en', 'Thanks to the good weather it turned into an enjoyable trip.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('gimi', 'sent-ex-gimi-1', 0),
  ('gimi', 'sent-ex-gimi-2', 1),
  ('gimi', 'sent-ex-gimi-3', 2),
  ('gimi', 'sent-ex-gimi-4', 3),
  ('kake', 'sent-ex-kake-1', 0),
  ('kake', 'sent-ex-kake-2', 1),
  ('kake', 'sent-ex-kake-3', 2),
  ('kake', 'sent-ex-kake-4', 3),
  ('nikui-gatai', 'sent-ex-gatai-1', 0),
  ('nikui-gatai', 'sent-ex-gatai-2', 1),
  ('nikui-gatai', 'sent-ex-gatai-3', 2),
  ('nikui-gatai', 'sent-ex-gatai-4', 3),
  ('you-ga-nai', 'sent-ex-youganai-1', 0),
  ('you-ga-nai', 'sent-ex-youganai-2', 1),
  ('you-ga-nai', 'sent-ex-youganai-3', 2),
  ('you-ga-nai', 'sent-ex-youganai-4', 3),
  ('tsutsu', 'sent-ex-tsutsu-1', 0),
  ('tsutsu', 'sent-ex-tsutsu-2', 1),
  ('tsutsu', 'sent-ex-tsutsu-3', 2),
  ('tsutsu', 'sent-ex-tsutsu-4', 3),
  ('nagara-mo', 'sent-ex-nagaramo-1', 0),
  ('nagara-mo', 'sent-ex-nagaramo-2', 1),
  ('nagara-mo', 'sent-ex-nagaramo-3', 2),
  ('nagara-mo', 'sent-ex-nagaramo-4', 3),
  ('mono-no', 'sent-ex-monono-1', 0),
  ('mono-no', 'sent-ex-monono-2', 1),
  ('mono-no', 'sent-ex-monono-3', 2),
  ('mono-no', 'sent-ex-monono-4', 3),
  ('kuseni', 'sent-ex-kuseni-1', 0),
  ('kuseni', 'sent-ex-kuseni-2', 1),
  ('kuseni', 'sent-ex-kuseni-3', 2),
  ('kuseni', 'sent-ex-kuseni-4', 3),
  ('sei-de', 'sent-ex-seide-1', 0),
  ('sei-de', 'sent-ex-seide-2', 1),
  ('sei-de', 'sent-ex-seide-3', 2),
  ('sei-de', 'sent-ex-seide-4', 3),
  ('okage-de', 'sent-ex-okagede-1', 0),
  ('okage-de', 'sent-ex-okagede-2', 1),
  ('okage-de', 'sent-ex-okagede-3', 2),
  ('okage-de', 'sent-ex-okagede-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-gimi-1', 'sent-ex-gimi-2', 'sent-ex-gimi-3', 'sent-ex-gimi-4', 'sent-ex-kake-1', 'sent-ex-kake-2', 'sent-ex-kake-3', 'sent-ex-kake-4', 'sent-ex-gatai-1', 'sent-ex-gatai-2', 'sent-ex-gatai-3', 'sent-ex-gatai-4', 'sent-ex-youganai-1', 'sent-ex-youganai-2', 'sent-ex-youganai-3', 'sent-ex-youganai-4', 'sent-ex-tsutsu-1', 'sent-ex-tsutsu-2', 'sent-ex-tsutsu-3', 'sent-ex-tsutsu-4', 'sent-ex-nagaramo-1', 'sent-ex-nagaramo-2', 'sent-ex-nagaramo-3', 'sent-ex-nagaramo-4', 'sent-ex-monono-1', 'sent-ex-monono-2', 'sent-ex-monono-3', 'sent-ex-monono-4', 'sent-ex-kuseni-1', 'sent-ex-kuseni-2', 'sent-ex-kuseni-3', 'sent-ex-kuseni-4', 'sent-ex-seide-1', 'sent-ex-seide-2', 'sent-ex-seide-3', 'sent-ex-seide-4', 'sent-ex-okagede-1', 'sent-ex-okagede-2', 'sent-ex-okagede-3', 'sent-ex-okagede-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-gimi-1', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-1', 2, '風邪', 'かぜ', (select id from words where primary_form = '風邪' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"風邪","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-1', 3, '気味', 'きみ', (select id from words where primary_form = '気味' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"気味","r":"きみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-1', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-2', 0, '最近', 'さいきん', (select id from words where primary_form = '最近' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"最近","r":"さいきん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-2', 1, '疲れ', 'つかれ', (select id from words where primary_form = '疲れ' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"疲","r":"つか"},{"t":"れ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-2', 2, '気味', 'ぎみ', (select id from words where primary_form = '気味' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"気味","r":"ぎみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-2', 3, 'だ', 'だ', NULL, 6, 7, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-2', 4, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-3', 0, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-3', 1, '太り', 'ふとり', (select id from words where primary_form = '太る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"太","r":"ふと"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-3', 2, '気味', 'ぎみ', (select id from words where primary_form = '気味' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"気味","r":"ぎみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-3', 3, 'です', 'です', NULL, 6, 8, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-4', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-4', 2, '遅れ', 'おくれ', (select id from words where primary_form = '遅れ' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"遅","r":"おく"},{"t":"れ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-4', 3, '気味', 'ぎみ', (select id from words where primary_form = '気味' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"気味","r":"ぎみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-4', 4, 'です', 'です', NULL, 7, 9, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gimi-4', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-1', 0, '読み', 'よみ', (select id from words where primary_form = '読み' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"読","r":"よ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-1', 1, 'かけ', 'かけ', NULL, 2, 4, '[{"t":"かけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-1', 2, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-1', 3, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-1', 4, 'が', 'が', NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-1', 5, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-2', 0, '机', 'つくえ', (select id from words where primary_form = '机' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-2', 2, '上に', 'うえに', NULL, 2, 4, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-2', 3, '食べかけのケーキがあります', 'たべかけのケーキがあります', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 4, 17, '[{"t":"食","r":"た"},{"t":"べかけのケーキがあります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-2', 4, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-3', 0, '言いかけて', 'いいかけて', (select id from words where primary_form = '言いつける' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"言","r":"い"},{"t":"いかけて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-3', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-3', 2, '止めた', 'やめた', (select id from words where primary_form = '止める' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"止","r":"や"},{"t":"めた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-3', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-4', 0, '作り', 'つくり', (select id from words where primary_form = '作り' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"作","r":"つく"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-4', 1, 'かけ', 'かけ', NULL, 2, 4, '[{"t":"かけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-4', 2, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-4', 3, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-4', 4, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-4', 5, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kake-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-1', 0, '信じがたい', 'しんじがたい', (select id from words where primary_form = '信じる' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"信","r":"しん"},{"t":"じがたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-1', 1, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-1', 2, 'だ', 'だ', NULL, 6, 7, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-2', 0, '忘れがたい', 'わすれがたい', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"忘","r":"わす"},{"t":"れがたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-2', 1, '思い出', 'おもいで', (select id from words where primary_form = '思い出' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"思","r":"おも"},{"t":"い"},{"t":"出","r":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-2', 2, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-2', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-3', 0, '動かしがたい', 'うごかしがたい', (select id from words where primary_form = '動かす' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"動","r":"うご"},{"t":"かしがたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-3', 1, '事実', 'じじつ', (select id from words where primary_form = '事実' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"事実","r":"じじつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-3', 2, 'だ', 'だ', NULL, 8, 9, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-3', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-4', 0, '許しがたい', 'ゆるしがたい', (select id from words where primary_form = '許す' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"許","r":"ゆる"},{"t":"しがたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-4', 1, '行動', 'こうどう', (select id from words where primary_form = '行動' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"行動","r":"こうどう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-4', 2, 'だ', 'だ', NULL, 7, 8, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gatai-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-1', 0, '連絡', 'れんらく', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"連絡","r":"れんらく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-1', 2, 'しよう', 'しよう', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"しよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-1', 3, 'が', 'が', NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-1', 4, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-1', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-2', 0, '壊れて', 'こわれて', (select id from words where primary_form = '壊れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"壊","r":"こわ"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-2', 1, 'いて', 'いて', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-2', 2, '直', 'なお', (select id from words where primary_form = '直' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"直","r":"なお"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-2', 3, 'しよう', 'しよう', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"しよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-2', 4, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-2', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-3', 0, '答えよう', 'こたえよう', (select id from words where primary_form = '答える' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"答","r":"こた"},{"t":"えよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-3', 1, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-3', 2, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-3', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 2, 'では', 'では', (select id from words where primary_form = 'では' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"では"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 3, '間に', 'まに', NULL, 5, 7, '[{"t":"間","r":"ま"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 4, '合わせよう', 'あわせよう', (select id from words where primary_form = '合わせる' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"合","r":"あ"},{"t":"わせよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 5, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 6, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youganai-4', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-1', 0, '悪い', 'わるい', (select id from words where primary_form = '難い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"悪","r":"わる"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-1', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-1', 2, '知りつつ', 'しりつつ', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"知","r":"し"},{"t":"りつつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-1', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-1', 4, '続けた', 'つづけた', (select id from words where primary_form = '続ける' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"続","r":"つづ"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-2', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-2', 2, '聞きつつ', 'ききつつ', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"聞","r":"き"},{"t":"きつつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-2', 3, '勉強する', 'べんきょうする', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"勉強","r":"べんきょう"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 0, '町', 'まち', (select id from words where primary_form = '町' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"町","r":"まち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 2, '変', 'か', (select id from words where primary_form = '変' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"変","r":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 3, 'わ', 'わ', (select id from words where primary_form = 'わ' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"わ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 4, 'り', 'り', NULL, 4, 5, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 5, 'つつ', 'つつ', (select id from words where primary_form = 'つつ' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"つつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 6, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-3', 7, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-4', 0, '体', 'からだ', (select id from words where primary_form = '体' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"体","r":"からだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-4', 2, '治りつつあります', 'なおりつつあります', (select id from words where primary_form = '治る' and language_id = 'lang-ja' and published order by id limit 1), 2, 10, '[{"t":"治","r":"なお"},{"t":"りつつあります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsu-4', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 0, '小さい', 'ちいさい', (select id from words where primary_form = '小さい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"小","r":"ちい"},{"t":"さい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 1, 'ながらも', 'ながらも', NULL, 3, 7, '[{"t":"ながらも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 3, '有名', 'ゆうめい', (select id from words where primary_form = '有名' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"有名","r":"ゆうめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 4, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 5, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 6, 'です', 'です', NULL, 12, 14, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-1', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-2', 0, '知って', 'しって', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"知","r":"し"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-2', 1, 'い', 'い', NULL, 3, 4, '[{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-2', 2, 'ながらも', 'ながらも', NULL, 4, 8, '[{"t":"ながらも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-2', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-2', 4, '言わなかった', 'いわなかった', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 9, 15, '[{"t":"言","r":"い"},{"t":"わなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-2', 5, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-3', 0, '貧しい', 'まずしい', (select id from words where primary_form = '貧しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"貧","r":"まず"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-3', 1, 'ながらも', 'ながらも', NULL, 3, 7, '[{"t":"ながらも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-3', 2, '幸せ', 'しあわせ', (select id from words where primary_form = '幸せ' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"幸","r":"しあわ"},{"t":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-3', 3, 'だった', 'だった', NULL, 9, 12, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-4', 0, '若い', 'わかい', (select id from words where primary_form = '若い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"若","r":"わか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-4', 1, 'ながらも', 'ながらも', NULL, 2, 6, '[{"t":"ながらも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-4', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-4', 3, 'よく', 'よく', NULL, 7, 9, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-4', 4, '働く', 'はたらく', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"働","r":"はたら"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagaramo-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-1', 0, '約束した', 'やくそくした', (select id from words where primary_form = '約束' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"約束","r":"やくそく"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-1', 1, 'ものの', 'ものの', NULL, 4, 7, '[{"t":"ものの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-1', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-1', 3, '行け', 'いけ', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"行","r":"い"},{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-1', 4, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-1', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-2', 0, '買った', 'かった', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"買","r":"か"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-2', 1, 'ものの', 'ものの', NULL, 3, 6, '[{"t":"ものの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-2', 3, '使って', 'つかって', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"使","r":"つか"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-2', 4, 'いない', 'いない', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-2', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-3', 0, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-3', 1, 'ものの', 'ものの', NULL, 3, 6, '[{"t":"ものの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-3', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-3', 3, '面白い', 'おもしろい', (select id from words where primary_form = '面白い' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-4', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-4', 2, '受けた', 'うけた', (select id from words where primary_form = '受ける' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"受","r":"う"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-4', 3, 'ものの', 'ものの', NULL, 6, 9, '[{"t":"ものの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-4', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-4', 5, '落ちました', 'おちました', (select id from words where primary_form = '落ちる' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"落","r":"お"},{"t":"ちました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monono-4', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-1', 0, '知って', 'しって', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"知","r":"し"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-1', 1, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-1', 2, 'くせに', 'くせに', NULL, 5, 8, '[{"t":"くせに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-1', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-1', 4, '教えない', 'おしえない', (select id from words where primary_form = '教える' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"教","r":"おし"},{"t":"えない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-1', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 1, 'のく', 'のく', (select id from words where primary_form = '退く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"のく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 2, 'せ', 'せ', NULL, 4, 5, '[{"t":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 4, '難しい', 'むずかしい', (select id from words where primary_form = '難しい' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"難","r":"むずか"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 5, '言葉', 'ことば', (select id from words where primary_form = '言葉' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"言葉","r":"ことば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 6, 'を', 'を', NULL, 11, 12, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 7, '使う', 'つかう', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"使","r":"つか"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-2', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-3', 0, '下手', 'へた', (select id from words where primary_form = '下手' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"下手","r":"へた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-3', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-3', 2, 'くせに', 'くせに', NULL, 3, 6, '[{"t":"くせに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-3', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-3', 4, 'いつも', 'いつも', NULL, 7, 10, '[{"t":"いつも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-3', 5, '歌う', 'うたう', (select id from words where primary_form = '歌う' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"歌","r":"うた"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-4', 0, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-4', 2, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-4', 3, 'くせに', 'くせに', NULL, 5, 8, '[{"t":"くせに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-4', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-4', 5, '払わない', 'はらわない', (select id from words where primary_form = '払う' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"払","r":"はら"},{"t":"わない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kuseni-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 2, 'せい', 'せい', (select id from words where primary_form = '所為' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"せい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 4, '試合', 'しあい', (select id from words where primary_form = '試合' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"試合","r":"しあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 5, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 6, '中止', 'ちゅうし', (select id from words where primary_form = '中止' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"中止","r":"ちゅうし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 7, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 8, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-1', 9, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 0, '風邪', 'かぜ', (select id from words where primary_form = '風邪' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"風邪","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 2, 'せい', 'せい', (select id from words where primary_form = '所為' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"せい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 4, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 5, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 6, '休んだ', 'やすんだ', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"休","r":"やす"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-2', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 2, '遅れた', 'おくれた', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"遅","r":"おく"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 3, 'せい', 'せい', (select id from words where primary_form = '所為' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"せい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 5, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 6, '遅刻した', 'ちこくした', (select id from words where primary_form = '遅刻' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"遅刻","r":"ちこく"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-3', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-4', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-4', 1, 'せい', 'せい', (select id from words where primary_form = '所為' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"せい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-4', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-4', 3, '失敗した', 'しっぱいした', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"失敗","r":"しっぱい"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-seide-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-1', 2, 'おかげで', 'おかげで', NULL, 3, 7, '[{"t":"おかげで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-1', 3, '合格しました', 'ごうかくしました', (select id from words where primary_form = '合格' and language_id = 'lang-ja' and published order by id limit 1), 7, 13, '[{"t":"合格","r":"ごうかく"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-1', 4, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-2', 0, '薬', 'くすり', (select id from words where primary_form = '薬' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"薬","r":"くすり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-2', 2, 'おかげで', 'おかげで', NULL, 2, 6, '[{"t":"おかげで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-2', 3, '元気', 'げんき', (select id from words where primary_form = '元気' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"元気","r":"げんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-2', 5, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-3', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-3', 1, 'おかげで', 'おかげで', NULL, 2, 6, '[{"t":"おかげで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-3', 2, '助かりました', 'たすかりました', (select id from words where primary_form = '助かる' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"助","r":"たす"},{"t":"かりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-3', 3, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 0, '天気', 'てんき', (select id from words where primary_form = '天気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"天気","r":"てんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 2, 'よ', 'よ', (select id from words where primary_form = 'よ' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"よ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 3, 'かった', 'かった', NULL, 4, 7, '[{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 4, 'おかげで', 'おかげで', NULL, 7, 11, '[{"t":"おかげで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 5, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 6, '楽しい', 'たのしい', (select id from words where primary_form = '楽しい' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"楽","r":"たの"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 7, '旅行', 'りょこう', (select id from words where primary_form = '旅行' and language_id = 'lang-ja' and published order by id limit 1), 15, 17, '[{"t":"旅行","r":"りょこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 8, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 17, 18, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 9, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 18, 21, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-okagede-4', 10, '。', '。', NULL, 21, 22, '[{"t":"。"}]'::jsonb);
