-- N3 example sentences, batch 6: the last five topics, and the level is done.
--
-- 〜ため as cause (its purpose sense is the N4 〜ために), 〜ように見える,
-- 〜として, 〜から〜にかけて and 〜かわりに. Five topics, 20 sentences, and
-- every published N3 grammar point now has four examples.
--
-- Nothing had to be reworded: every sentence passed check:examples first
-- time, which after five batches of fighting the index is worth noting as the
-- exception rather than the rule.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- tame-cause
  ('sent-ex-tamecause-1', 'lang-ja', '雨のため、試合は中止になりました。', 'あめ の ため、しあい わ ちゅうし に なりました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tamecause-2', 'lang-ja', '事故のため、電車が遅れています。', 'じこ の ため、でんしゃ が おくれて います。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tamecause-3', 'lang-ja', '病気のため、会社を休みました。', 'びょうき の ため、かいしゃ お やすみました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-tamecause-4', 'lang-ja', '工事のため、通れません。', 'こうじ の ため、とおれません。', 'lvl-ja-n3', 'authored', true),
  -- you-ni-mieru
  ('sent-ex-younimieru-1', 'lang-ja', '彼は疲れているように見える。', 'かれ わ つかれて いる よう に みえる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-younimieru-2', 'lang-ja', '元気なように見えますが、病気です。', 'げんき な よう に みえます が、びょうき です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-younimieru-3', 'lang-ja', 'あの人は学生のように見える。', 'あの ひと わ がくせい の よう に みえる。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-younimieru-4', 'lang-ja', '空が明るくなったように見えます。', 'そら が あかるく なった よう に みえます。', 'lvl-ja-n3', 'authored', true),
  -- toshite
  ('sent-ex-toshite-1', 'lang-ja', '彼は先生として働いています。', 'かれ わ せんせい として はたらいて います。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-toshite-2', 'lang-ja', '留学生として日本へ行きます。', 'りゅうがくせい として にほん え いきます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-toshite-3', 'lang-ja', '趣味として写真を撮っています。', 'しゅみ として しゃしん お とって います。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-toshite-4', 'lang-ja', '代表として発表しました。', 'だいひょう として はっぴょう しました。', 'lvl-ja-n3', 'authored', true),
  -- kara-nikakete
  ('sent-ex-karanikakete-1', 'lang-ja', '春から夏にかけて雨が多い。', 'はる から なつ に かけて あめ が おおい。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-karanikakete-2', 'lang-ja', '夜から朝にかけて雪が降りました。', 'よる から あさ に かけて ゆき が ふりました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-karanikakete-3', 'lang-ja', '今週から来週にかけて忙しいです。', 'こんしゅう から らいしゅう に かけて いそがしい です。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-karanikakete-4', 'lang-ja', '北から南にかけて強い風が吹いた。', 'きた から みなみ に かけて つよい かぜ が ふいた。', 'lvl-ja-n3', 'authored', true),
  -- kawari-ni
  ('sent-ex-kawarini-1', 'lang-ja', '兄のかわりに私が行きます。', 'あに の かわり に わたし が いきます。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kawarini-2', 'lang-ja', '肉のかわりに野菜を使いました。', 'にく の かわり に やさい お つかいました。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kawarini-3', 'lang-ja', '働くかわりに、お金をもらう。', 'はたらく かわり に、おかね お もらう。', 'lvl-ja-n3', 'authored', true),
  ('sent-ex-kawarini-4', 'lang-ja', '電車のかわりにバスで行きます。', 'でんしゃ の かわり に バス で いきます。', 'lvl-ja-n3', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-tamecause-1', 'sent-ex-tamecause-1', 'en', 'Because of the rain, the match was called off.', 'authored'),
  ('st-ex-tamecause-2', 'sent-ex-tamecause-2', 'en', 'Owing to an accident, the trains are running late.', 'authored'),
  ('st-ex-tamecause-3', 'sent-ex-tamecause-3', 'en', 'I was off work because of illness.', 'authored'),
  ('st-ex-tamecause-4', 'sent-ex-tamecause-4', 'en', 'You cannot get through because of the roadworks.', 'authored'),
  ('st-ex-younimieru-1', 'sent-ex-younimieru-1', 'en', 'He looks tired.', 'authored'),
  ('st-ex-younimieru-2', 'sent-ex-younimieru-2', 'en', 'He looks well, but he is ill.', 'authored'),
  ('st-ex-younimieru-3', 'sent-ex-younimieru-3', 'en', 'That person looks like a student.', 'authored'),
  ('st-ex-younimieru-4', 'sent-ex-younimieru-4', 'en', 'The sky looks as though it has brightened.', 'authored'),
  ('st-ex-toshite-1', 'sent-ex-toshite-1', 'en', 'He works as a teacher.', 'authored'),
  ('st-ex-toshite-2', 'sent-ex-toshite-2', 'en', 'I am going to Japan as an exchange student.', 'authored'),
  ('st-ex-toshite-3', 'sent-ex-toshite-3', 'en', 'I take photographs as a hobby.', 'authored'),
  ('st-ex-toshite-4', 'sent-ex-toshite-4', 'en', 'I gave the presentation as our representative.', 'authored'),
  ('st-ex-karanikakete-1', 'sent-ex-karanikakete-1', 'en', 'From spring through to summer there is a lot of rain.', 'authored'),
  ('st-ex-karanikakete-2', 'sent-ex-karanikakete-2', 'en', 'It snowed from night through to morning.', 'authored'),
  ('st-ex-karanikakete-3', 'sent-ex-karanikakete-3', 'en', 'I am busy from this week through to next.', 'authored'),
  ('st-ex-karanikakete-4', 'sent-ex-karanikakete-4', 'en', 'A strong wind blew from the north down to the south.', 'authored'),
  ('st-ex-kawarini-1', 'sent-ex-kawarini-1', 'en', 'I am going in place of my older brother.', 'authored'),
  ('st-ex-kawarini-2', 'sent-ex-kawarini-2', 'en', 'I used vegetables instead of meat.', 'authored'),
  ('st-ex-kawarini-3', 'sent-ex-kawarini-3', 'en', 'In return for working, I get paid.', 'authored'),
  ('st-ex-kawarini-4', 'sent-ex-kawarini-4', 'en', 'I am going by bus instead of by train.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('tame-cause', 'sent-ex-tamecause-1', 0),
  ('tame-cause', 'sent-ex-tamecause-2', 1),
  ('tame-cause', 'sent-ex-tamecause-3', 2),
  ('tame-cause', 'sent-ex-tamecause-4', 3),
  ('you-ni-mieru', 'sent-ex-younimieru-1', 0),
  ('you-ni-mieru', 'sent-ex-younimieru-2', 1),
  ('you-ni-mieru', 'sent-ex-younimieru-3', 2),
  ('you-ni-mieru', 'sent-ex-younimieru-4', 3),
  ('toshite', 'sent-ex-toshite-1', 0),
  ('toshite', 'sent-ex-toshite-2', 1),
  ('toshite', 'sent-ex-toshite-3', 2),
  ('toshite', 'sent-ex-toshite-4', 3),
  ('kara-nikakete', 'sent-ex-karanikakete-1', 0),
  ('kara-nikakete', 'sent-ex-karanikakete-2', 1),
  ('kara-nikakete', 'sent-ex-karanikakete-3', 2),
  ('kara-nikakete', 'sent-ex-karanikakete-4', 3),
  ('kawari-ni', 'sent-ex-kawarini-1', 0),
  ('kawari-ni', 'sent-ex-kawarini-2', 1),
  ('kawari-ni', 'sent-ex-kawarini-3', 2),
  ('kawari-ni', 'sent-ex-kawarini-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-tamecause-1', 'sent-ex-tamecause-2', 'sent-ex-tamecause-3', 'sent-ex-tamecause-4', 'sent-ex-younimieru-1', 'sent-ex-younimieru-2', 'sent-ex-younimieru-3', 'sent-ex-younimieru-4', 'sent-ex-toshite-1', 'sent-ex-toshite-2', 'sent-ex-toshite-3', 'sent-ex-toshite-4', 'sent-ex-karanikakete-1', 'sent-ex-karanikakete-2', 'sent-ex-karanikakete-3', 'sent-ex-karanikakete-4', 'sent-ex-kawarini-1', 'sent-ex-kawarini-2', 'sent-ex-kawarini-3', 'sent-ex-kawarini-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 2, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 3, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 4, '試合', 'しあい', (select id from words where primary_form = '試合' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"試合","r":"しあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 5, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 6, '中止', 'ちゅうし', (select id from words where primary_form = '中止' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"中止","r":"ちゅうし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 7, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 8, 'なりました', 'なりました', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 11, 16, '[{"t":"なりました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-1', 9, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 0, '事故', 'じこ', (select id from words where primary_form = '事故' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"事故","r":"じこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 2, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 4, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 5, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 6, '遅れて', 'おくれて', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"遅","r":"おく"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 7, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-2', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 0, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 2, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 4, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 5, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 6, '休みました', 'やすみました', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"休","r":"やす"},{"t":"みました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-3', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-4', 0, '工事', 'こうじ', (select id from words where primary_form = '工事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"工事","r":"こうじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-4', 2, 'ため', 'ため', (select id from words where primary_form = '為' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ため"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-4', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-4', 4, '通れ', 'とおれ', (select id from words where primary_form = '通る' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"通","r":"とお"},{"t":"れ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-4', 5, 'ません', 'ません', NULL, 8, 11, '[{"t":"ません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tamecause-4', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-1', 2, '疲れて', 'つかれて', (select id from words where primary_form = '疲れる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"疲","r":"つか"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-1', 3, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-1', 4, 'ように見える', 'ようにみえる', NULL, 7, 13, '[{"t":"ように"},{"t":"見","r":"み"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-1', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 0, '元気', 'げんき', (select id from words where primary_form = '元気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"元気","r":"げんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 2, 'よう', 'よう', (select id from words where primary_form = '様' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 4, '見えます', 'みえます', (select id from words where primary_form = '見える' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"見","r":"み"},{"t":"えます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 5, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 6, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 7, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 8, 'です', 'です', NULL, 14, 16, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-2', 9, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-3', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-3', 1, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-3', 3, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-3', 4, 'の', 'の', NULL, 6, 7, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-3', 5, 'ように見える', 'ようにみえる', NULL, 7, 13, '[{"t":"ように"},{"t":"見","r":"み"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-4', 0, '空', 'そら', (select id from words where primary_form = '空' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"空","r":"そら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-4', 2, '明るくなったように', 'あかるくなったように', (select id from words where primary_form = '明るい' and language_id = 'lang-ja' and published order by id limit 1), 2, 11, '[{"t":"明","r":"あか"},{"t":"るくなったように"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-4', 3, '見えます', 'みえます', (select id from words where primary_form = '見える' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"見","r":"み"},{"t":"えます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimieru-4', 4, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 2, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 4, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 5, '働いて', 'はたらいて', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"働","r":"はたら"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 6, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-1', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-2', 0, '留学生', 'りゅうがくせい', (select id from words where primary_form = '留学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"留学生","r":"りゅうがくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-2', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-2', 2, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-2', 3, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-2', 4, 'へ', 'へ', NULL, 8, 9, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-2', 5, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 0, '趣味', 'しゅみ', (select id from words where primary_form = '趣味' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"趣味","r":"しゅみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 2, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 3, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 4, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 5, '撮って', 'とって', (select id from words where primary_form = '撮る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"撮","r":"と"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 6, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-3', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-4', 0, '代表', 'だいひょう', (select id from words where primary_form = '代表' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"代表","r":"だいひょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-4', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-4', 2, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-4', 3, '発表しました', 'はっぴょうしました', (select id from words where primary_form = '発表' and language_id = 'lang-ja' and published order by id limit 1), 5, 11, '[{"t":"発表","r":"はっぴょう"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshite-4', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 0, '春', 'はる', (select id from words where primary_form = '春' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"春","r":"はる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 2, '夏', 'なつ', (select id from words where primary_form = '夏' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"夏","r":"なつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 4, 'かけて', 'かけて', (select id from words where primary_form = '掛ける' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"かけて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 5, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 6, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 7, '多い', 'おおい', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"多","r":"おお"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-1', 8, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 0, '夜', 'よる', (select id from words where primary_form = '夜' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"夜","r":"よる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 2, '朝', 'あさ', (select id from words where primary_form = '朝' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 4, 'かけて', 'かけて', (select id from words where primary_form = '掛ける' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"かけて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 5, '雪', 'ゆき', (select id from words where primary_form = '雪' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"雪","r":"ゆき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 6, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 7, '降りました', 'ふりました', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"降","r":"ふ"},{"t":"りました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-2', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 0, '今週', 'こんしゅう', (select id from words where primary_form = '今週' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今週","r":"こんしゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 2, '来週', 'らいしゅう', (select id from words where primary_form = '来週' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"来週","r":"らいしゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 4, 'かけて', 'かけて', (select id from words where primary_form = '掛ける' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"かけて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 5, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 6, 'です', 'です', NULL, 13, 15, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-3', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 0, '北', 'きた', (select id from words where primary_form = '北' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"北","r":"きた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 2, '南', 'みなみ', (select id from words where primary_form = '南' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"南","r":"みなみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 4, 'かけて', 'かけて', (select id from words where primary_form = '掛ける' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"かけて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 5, '強い', 'つよい', (select id from words where primary_form = '強い' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"強","r":"つよ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 6, '風', 'かぜ', (select id from words where primary_form = '風' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"風","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 7, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 8, '吹いた', 'ふいた', (select id from words where primary_form = '吹く' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"吹","r":"ふ"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karanikakete-4', 9, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-1', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-1', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-1', 2, 'かわりに', 'かわりに', NULL, 2, 6, '[{"t":"かわりに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-1', 3, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-1', 4, 'が', 'が', NULL, 7, 8, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-1', 5, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-2', 0, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-2', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-2', 2, 'かわりに', 'かわりに', NULL, 2, 6, '[{"t":"かわりに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-2', 3, '野菜', 'やさい', (select id from words where primary_form = '野菜' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"野菜","r":"やさい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-2', 4, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-2', 5, '使いました', 'つかいました', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"使","r":"つか"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-3', 0, '働く', 'はたらく', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"働","r":"はたら"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-3', 1, 'かわりに', 'かわりに', NULL, 2, 6, '[{"t":"かわりに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-3', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-3', 3, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-3', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-3', 5, 'もらう', 'もらう', NULL, 10, 13, '[{"t":"もらう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-4', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-4', 2, 'かわりに', 'かわりに', NULL, 3, 7, '[{"t":"かわりに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-4', 3, 'バス', 'バス', (select id from words where primary_form = 'バス' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"バス"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-4', 5, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawarini-4', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb);
