-- N2 example sentences, batch 1: regardless of, based on, and around.
--
-- N2 is where the patterns stop being verb endings and start being set
-- phrases built on a particle. にかかわらず, にもかかわらず, を問わず and
-- にわたって set a scope; を皮切りに, を込めて, を巡って, に基づいて,
-- をもとに and に応じて say what a thing rests on or revolves around.
--
-- SKIPPED: 〜をものともせず (slug wo-kiniseze) is NOT in this seed. せず —
-- the literary negative of する — shreds to せ|ず in every form tried
-- (ものともせず, ものともせずに, 物ともせず), because the index holds する in
-- kanji-stemmed compounds and not as bare kana. ものともしない cuts clean, but
-- it is a different surface form from the one the topic teaches, and shipping
-- it would put four sentences under a pattern none of them contains. The topic
-- wants a lexicon entry for せず, which is not something a seed should do, so
-- 〜にわたって was brought forward from 310 in its place and wo-kiniseze is
-- left uncovered.
--
-- One rewording: をめぐって in kana shreds to を|め|ぐ. 巡る is a published
-- word, so the four sentences use を巡って — same phrase, spelled the way the
-- index can see it.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- ni-kakawarazu
  ('sent-ex-nikakawarazu-1', 'lang-ja', '天気にかかわらず、試合は行います。', 'てんき に かかわらず、しあい わ おこないます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikakawarazu-2', 'lang-ja', '結果にかかわらず、最後までやります。', 'けっか に かかわらず、さいご まで やります。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikakawarazu-3', 'lang-ja', '曜日にかかわらず、店は開いています。', 'ようび に かかわらず、みせ わ あいて います。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikakawarazu-4', 'lang-ja', '値段にかかわらず、品質を選びます。', 'ねだん に かかわらず、ひんしつ お えらびます。', 'lvl-ja-n2', 'authored', true),
  -- nimo-kakawarazu
  ('sent-ex-nimokakawarazu-1', 'lang-ja', '雨にもかかわらず、多くの人が集まった。', 'あめ に も かかわらず、おおく の ひと が あつまった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nimokakawarazu-2', 'lang-ja', '努力したにもかかわらず、失敗した。', 'どりょく した に も かかわらず、しっぱい した。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nimokakawarazu-3', 'lang-ja', '若いにもかかわらず、経験が豊富だ。', 'わかい に も かかわらず、けいけん が ほうふ だ。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nimokakawarazu-4', 'lang-ja', '忙しいにもかかわらず、彼は来た。', 'いそがしい に も かかわらず、かれ わ きた。', 'lvl-ja-n2', 'authored', true),
  -- wo-towazu
  ('sent-ex-wotowazu-1', 'lang-ja', '年齢を問わず参加できます。', 'ねんれい お とわず さんか できます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wotowazu-2', 'lang-ja', '経験を問わず募集しています。', 'けいけん お とわず ぼしゅう して います。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wotowazu-3', 'lang-ja', '季節を問わず人気があります。', 'きせつ お とわず にんき が あります。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wotowazu-4', 'lang-ja', '時間を問わず利用できます。', 'じかん お とわず りよう できます。', 'lvl-ja-n2', 'authored', true),
  -- ni-wataru
  ('sent-ex-niwataru-1', 'lang-ja', '長い時間にわたって話し合った。', 'ながい じかん に わたって はなしあった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-niwataru-2', 'lang-ja', '全国にわたって雨が降りました。', 'ぜんこく に わたって あめ が ふりました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-niwataru-3', 'lang-ja', '広い範囲にわたって調査しました。', 'ひろい はんい に わたって ちょうさ しました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-niwataru-4', 'lang-ja', '工事は長い期間にわたって続いた。', 'こうじ わ ながい きかん に わたって つづいた。', 'lvl-ja-n2', 'authored', true),
  -- wo-kawakiri-ni
  ('sent-ex-kawakiri-1', 'lang-ja', '日本を皮切りに、世界で発表します。', 'にほん お かわきり に、せかい で はっぴょう します。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kawakiri-2', 'lang-ja', 'あの映画を皮切りに、人気が出ました。', 'あの えいが お かわきり に、にんき が でました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kawakiri-3', 'lang-ja', '今回の会議を皮切りに、議論が始まった。', 'こんかい の かいぎ お かわきり に、ぎろん が はじまった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kawakiri-4', 'lang-ja', 'あの店を皮切りに、全国に広がった。', 'あの みせ お かわきり に、ぜんこく に ひろがった。', 'lvl-ja-n2', 'authored', true),
  -- wo-komete
  ('sent-ex-wokomete-1', 'lang-ja', '心を込めて作りました。', 'こころ お こめて つくりました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wokomete-2', 'lang-ja', '感謝を込めて手紙を書いた。', 'かんしゃ お こめて てがみ お かいた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wokomete-3', 'lang-ja', '愛を込めて歌います。', 'あい お こめて うたいます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wokomete-4', 'lang-ja', '力を込めて押した。', 'ちから お こめて おした。', 'lvl-ja-n2', 'authored', true),
  -- wo-megutte
  ('sent-ex-womegutte-1', 'lang-ja', 'あの問題を巡って議論が続いている。', 'あの もんだい お めぐって ぎろん が つづいて いる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-womegutte-2', 'lang-ja', '土地を巡って争いが起きた。', 'とち お めぐって あらそい が おきた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-womegutte-3', 'lang-ja', '計画を巡って意見が分かれた。', 'けいかく お めぐって いけん が わかれた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-womegutte-4', 'lang-ja', '事故を巡って調査が行われた。', 'じこ お めぐって ちょうさ が おこなわれた。', 'lvl-ja-n2', 'authored', true),
  -- ni-motozuite
  ('sent-ex-nimotozuite-1', 'lang-ja', '事実に基づいて書いてください。', 'じじつ に もとづいて かいて ください。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nimotozuite-2', 'lang-ja', '規則に基づいて処理します。', 'きそく に もとづいて しょり します。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nimotozuite-3', 'lang-ja', '経験に基づいて話します。', 'けいけん に もとづいて はなします。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nimotozuite-4', 'lang-ja', '調査に基づいて発表しました。', 'ちょうさ に もとづいて はっぴょう しました。', 'lvl-ja-n2', 'authored', true),
  -- wo-moto-ni
  ('sent-ex-womotoni-1', 'lang-ja', '事実をもとに小説を書いた。', 'じじつ お もと に しょうせつ お かいた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-womotoni-2', 'lang-ja', '資料をもとに計画を立てた。', 'しりょう お もと に けいかく お たてた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-womotoni-3', 'lang-ja', '経験をもとに説明します。', 'けいけん お もと に せつめい します。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-womotoni-4', 'lang-ja', '調査をもとに報告します。', 'ちょうさ お もと に ほうこく します。', 'lvl-ja-n2', 'authored', true),
  -- ni-oujite
  ('sent-ex-nioujite-1', 'lang-ja', '収入に応じて税金が決まる。', 'しゅうにゅう に おうじて ぜいきん が きまる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nioujite-2', 'lang-ja', '必要に応じて手伝います。', 'ひつよう に おうじて てつだいます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nioujite-3', 'lang-ja', '季節に応じて料理が変わる。', 'きせつ に おうじて りょうり が かわる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nioujite-4', 'lang-ja', '年齢に応じて値段が違います。', 'ねんれい に おうじて ねだん が ちがいます。', 'lvl-ja-n2', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-nikakawarazu-1', 'sent-ex-nikakawarazu-1', 'en', 'Regardless of the weather, the match will go ahead.', 'authored'),
  ('st-ex-nikakawarazu-2', 'sent-ex-nikakawarazu-2', 'en', 'Whatever the result, we will see it through to the end.', 'authored'),
  ('st-ex-nikakawarazu-3', 'sent-ex-nikakawarazu-3', 'en', 'Whatever the day, the shop is open.', 'authored'),
  ('st-ex-nikakawarazu-4', 'sent-ex-nikakawarazu-4', 'en', 'Price aside, we choose on quality.', 'authored'),
  ('st-ex-nimokakawarazu-1', 'sent-ex-nimokakawarazu-1', 'en', 'Despite the rain, a lot of people gathered.', 'authored'),
  ('st-ex-nimokakawarazu-2', 'sent-ex-nimokakawarazu-2', 'en', 'Despite my efforts, I failed.', 'authored'),
  ('st-ex-nimokakawarazu-3', 'sent-ex-nimokakawarazu-3', 'en', 'Young though he is, his experience is considerable.', 'authored'),
  ('st-ex-nimokakawarazu-4', 'sent-ex-nimokakawarazu-4', 'en', 'Busy as he was, he came.', 'authored'),
  ('st-ex-wotowazu-1', 'sent-ex-wotowazu-1', 'en', 'Anyone can take part, whatever their age.', 'authored'),
  ('st-ex-wotowazu-2', 'sent-ex-wotowazu-2', 'en', 'We are recruiting regardless of experience.', 'authored'),
  ('st-ex-wotowazu-3', 'sent-ex-wotowazu-3', 'en', 'It is popular whatever the season.', 'authored'),
  ('st-ex-wotowazu-4', 'sent-ex-wotowazu-4', 'en', 'You can use it at any hour.', 'authored'),
  ('st-ex-niwataru-1', 'sent-ex-niwataru-1', 'en', 'We talked it over for a long time.', 'authored'),
  ('st-ex-niwataru-2', 'sent-ex-niwataru-2', 'en', 'It rained right across the country.', 'authored'),
  ('st-ex-niwataru-3', 'sent-ex-niwataru-3', 'en', 'We surveyed a wide area.', 'authored'),
  ('st-ex-niwataru-4', 'sent-ex-niwataru-4', 'en', 'The roadworks went on over a long period.', 'authored'),
  ('st-ex-kawakiri-1', 'sent-ex-kawakiri-1', 'en', 'Starting with Japan, we will present it around the world.', 'authored'),
  ('st-ex-kawakiri-2', 'sent-ex-kawakiri-2', 'en', 'That film was the start of his popularity.', 'authored'),
  ('st-ex-kawakiri-3', 'sent-ex-kawakiri-3', 'en', 'Beginning with this meeting, the discussion got under way.', 'authored'),
  ('st-ex-kawakiri-4', 'sent-ex-kawakiri-4', 'en', 'Starting from that shop, it spread across the country.', 'authored'),
  ('st-ex-wokomete-1', 'sent-ex-wokomete-1', 'en', 'I made it with all my heart.', 'authored'),
  ('st-ex-wokomete-2', 'sent-ex-wokomete-2', 'en', 'I wrote the letter with gratitude.', 'authored'),
  ('st-ex-wokomete-3', 'sent-ex-wokomete-3', 'en', 'I sing it with love.', 'authored'),
  ('st-ex-wokomete-4', 'sent-ex-wokomete-4', 'en', 'I pushed with all my strength.', 'authored'),
  ('st-ex-womegutte-1', 'sent-ex-womegutte-1', 'en', 'The argument over that problem goes on.', 'authored'),
  ('st-ex-womegutte-2', 'sent-ex-womegutte-2', 'en', 'A dispute arose over the land.', 'authored'),
  ('st-ex-womegutte-3', 'sent-ex-womegutte-3', 'en', 'Opinion was divided over the plan.', 'authored'),
  ('st-ex-womegutte-4', 'sent-ex-womegutte-4', 'en', 'An investigation was carried out into the accident.', 'authored'),
  ('st-ex-nimotozuite-1', 'sent-ex-nimotozuite-1', 'en', 'Please write it based on the facts.', 'authored'),
  ('st-ex-nimotozuite-2', 'sent-ex-nimotozuite-2', 'en', 'We deal with it in accordance with the rules.', 'authored'),
  ('st-ex-nimotozuite-3', 'sent-ex-nimotozuite-3', 'en', 'I speak from experience.', 'authored'),
  ('st-ex-nimotozuite-4', 'sent-ex-nimotozuite-4', 'en', 'I presented it on the basis of the survey.', 'authored'),
  ('st-ex-womotoni-1', 'sent-ex-womotoni-1', 'en', 'He wrote a novel based on fact.', 'authored'),
  ('st-ex-womotoni-2', 'sent-ex-womotoni-2', 'en', 'We drew up the plan from the material.', 'authored'),
  ('st-ex-womotoni-3', 'sent-ex-womotoni-3', 'en', 'I will explain on the basis of experience.', 'authored'),
  ('st-ex-womotoni-4', 'sent-ex-womotoni-4', 'en', 'I will report on the basis of the survey.', 'authored'),
  ('st-ex-nioujite-1', 'sent-ex-nioujite-1', 'en', 'Tax is set according to income.', 'authored'),
  ('st-ex-nioujite-2', 'sent-ex-nioujite-2', 'en', 'I will help as needed.', 'authored'),
  ('st-ex-nioujite-3', 'sent-ex-nioujite-3', 'en', 'The cooking changes with the season.', 'authored'),
  ('st-ex-nioujite-4', 'sent-ex-nioujite-4', 'en', 'The price varies according to age.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('ni-kakawarazu', 'sent-ex-nikakawarazu-1', 0),
  ('ni-kakawarazu', 'sent-ex-nikakawarazu-2', 1),
  ('ni-kakawarazu', 'sent-ex-nikakawarazu-3', 2),
  ('ni-kakawarazu', 'sent-ex-nikakawarazu-4', 3),
  ('nimo-kakawarazu', 'sent-ex-nimokakawarazu-1', 0),
  ('nimo-kakawarazu', 'sent-ex-nimokakawarazu-2', 1),
  ('nimo-kakawarazu', 'sent-ex-nimokakawarazu-3', 2),
  ('nimo-kakawarazu', 'sent-ex-nimokakawarazu-4', 3),
  ('wo-towazu', 'sent-ex-wotowazu-1', 0),
  ('wo-towazu', 'sent-ex-wotowazu-2', 1),
  ('wo-towazu', 'sent-ex-wotowazu-3', 2),
  ('wo-towazu', 'sent-ex-wotowazu-4', 3),
  ('ni-wataru', 'sent-ex-niwataru-1', 0),
  ('ni-wataru', 'sent-ex-niwataru-2', 1),
  ('ni-wataru', 'sent-ex-niwataru-3', 2),
  ('ni-wataru', 'sent-ex-niwataru-4', 3),
  ('wo-kawakiri-ni', 'sent-ex-kawakiri-1', 0),
  ('wo-kawakiri-ni', 'sent-ex-kawakiri-2', 1),
  ('wo-kawakiri-ni', 'sent-ex-kawakiri-3', 2),
  ('wo-kawakiri-ni', 'sent-ex-kawakiri-4', 3),
  ('wo-komete', 'sent-ex-wokomete-1', 0),
  ('wo-komete', 'sent-ex-wokomete-2', 1),
  ('wo-komete', 'sent-ex-wokomete-3', 2),
  ('wo-komete', 'sent-ex-wokomete-4', 3),
  ('wo-megutte', 'sent-ex-womegutte-1', 0),
  ('wo-megutte', 'sent-ex-womegutte-2', 1),
  ('wo-megutte', 'sent-ex-womegutte-3', 2),
  ('wo-megutte', 'sent-ex-womegutte-4', 3),
  ('ni-motozuite', 'sent-ex-nimotozuite-1', 0),
  ('ni-motozuite', 'sent-ex-nimotozuite-2', 1),
  ('ni-motozuite', 'sent-ex-nimotozuite-3', 2),
  ('ni-motozuite', 'sent-ex-nimotozuite-4', 3),
  ('wo-moto-ni', 'sent-ex-womotoni-1', 0),
  ('wo-moto-ni', 'sent-ex-womotoni-2', 1),
  ('wo-moto-ni', 'sent-ex-womotoni-3', 2),
  ('wo-moto-ni', 'sent-ex-womotoni-4', 3),
  ('ni-oujite', 'sent-ex-nioujite-1', 0),
  ('ni-oujite', 'sent-ex-nioujite-2', 1),
  ('ni-oujite', 'sent-ex-nioujite-3', 2),
  ('ni-oujite', 'sent-ex-nioujite-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-nikakawarazu-1', 'sent-ex-nikakawarazu-2', 'sent-ex-nikakawarazu-3', 'sent-ex-nikakawarazu-4', 'sent-ex-nimokakawarazu-1', 'sent-ex-nimokakawarazu-2', 'sent-ex-nimokakawarazu-3', 'sent-ex-nimokakawarazu-4', 'sent-ex-wotowazu-1', 'sent-ex-wotowazu-2', 'sent-ex-wotowazu-3', 'sent-ex-wotowazu-4', 'sent-ex-niwataru-1', 'sent-ex-niwataru-2', 'sent-ex-niwataru-3', 'sent-ex-niwataru-4', 'sent-ex-kawakiri-1', 'sent-ex-kawakiri-2', 'sent-ex-kawakiri-3', 'sent-ex-kawakiri-4', 'sent-ex-wokomete-1', 'sent-ex-wokomete-2', 'sent-ex-wokomete-3', 'sent-ex-wokomete-4', 'sent-ex-womegutte-1', 'sent-ex-womegutte-2', 'sent-ex-womegutte-3', 'sent-ex-womegutte-4', 'sent-ex-nimotozuite-1', 'sent-ex-nimotozuite-2', 'sent-ex-nimotozuite-3', 'sent-ex-nimotozuite-4', 'sent-ex-womotoni-1', 'sent-ex-womotoni-2', 'sent-ex-womotoni-3', 'sent-ex-womotoni-4', 'sent-ex-nioujite-1', 'sent-ex-nioujite-2', 'sent-ex-nioujite-3', 'sent-ex-nioujite-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-1', 0, '天気', 'てんき', (select id from words where primary_form = '天気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"天気","r":"てんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-1', 1, 'にかかわらず', 'にかかわらず', NULL, 2, 8, '[{"t":"にかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-1', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-1', 3, '試合', 'しあい', (select id from words where primary_form = '試合' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"試合","r":"しあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-1', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-1', 5, '行います', 'おこないます', (select id from words where primary_form = '行う' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"行","r":"おこな"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-1', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 0, '結果', 'けっか', (select id from words where primary_form = '結果' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"結果","r":"けっか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 1, 'にかかわらず', 'にかかわらず', NULL, 2, 8, '[{"t":"にかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 3, '最後', 'さいご', (select id from words where primary_form = '最後' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"最後","r":"さいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 4, 'まで', 'まで', NULL, 11, 13, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 5, 'や', 'や', (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 6, 'り', 'り', NULL, 14, 15, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 7, 'ます', 'ます', NULL, 15, 17, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-2', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 0, '曜日', 'ようび', (select id from words where primary_form = '曜日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"曜日","r":"ようび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 1, 'にかかわらず', 'にかかわらず', NULL, 2, 8, '[{"t":"にかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 3, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 5, '開いて', 'あいて', (select id from words where primary_form = '開く' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"開","r":"あ"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 6, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 14, 17, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-3', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-4', 0, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-4', 1, 'にかかわらず', 'にかかわらず', NULL, 2, 8, '[{"t":"にかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-4', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-4', 3, '品質', 'ひんしつ', (select id from words where primary_form = '品質' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"品質","r":"ひんしつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-4', 4, 'を', 'を', NULL, 11, 12, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-4', 5, '選びます', 'えらびます', (select id from words where primary_form = '選ぶ' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"選","r":"えら"},{"t":"びます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikakawarazu-4', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 1, 'にもかかわらず', 'にもかかわらず', (select id from words where primary_form = 'にも関わらず' and language_id = 'lang-ja' and published order by id limit 1), 1, 8, '[{"t":"にもかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 3, '多くの', 'おおくの', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"多","r":"おお"},{"t":"くの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 4, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 5, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 6, '集まった', 'あつまった', (select id from words where primary_form = '集まる' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"集","r":"あつ"},{"t":"まった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-1', 7, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-2', 0, '努力した', 'どりょくした', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"努力","r":"どりょく"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-2', 1, 'にもかかわらず', 'にもかかわらず', (select id from words where primary_form = 'にも関わらず' and language_id = 'lang-ja' and published order by id limit 1), 4, 11, '[{"t":"にもかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-2', 2, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-2', 3, '失敗した', 'しっぱいした', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"失敗","r":"しっぱい"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-2', 4, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 0, '若い', 'わかい', (select id from words where primary_form = '若い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"若","r":"わか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 1, 'にもかかわらず', 'にもかかわらず', (select id from words where primary_form = 'にも関わらず' and language_id = 'lang-ja' and published order by id limit 1), 2, 9, '[{"t":"にもかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 2, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 3, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 4, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 5, '豊富', 'ほうふ', (select id from words where primary_form = '豊富' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"豊富","r":"ほうふ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 6, 'だ', 'だ', NULL, 15, 16, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-3', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-4', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-4', 1, 'にもかかわらず', 'にもかかわらず', (select id from words where primary_form = 'にも関わらず' and language_id = 'lang-ja' and published order by id limit 1), 3, 10, '[{"t":"にもかかわらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-4', 2, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-4', 3, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-4', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-4', 5, '来た', 'きた', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"来","r":"き"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimokakawarazu-4', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 0, '年齢', 'ねんれい', (select id from words where primary_form = '年齢' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"年齢","r":"ねんれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 2, '問わず', 'とわず', (select id from words where primary_form = '問う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"問","r":"と"},{"t":"わず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 3, '参加', 'さんか', (select id from words where primary_form = '参加' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"参加","r":"さんか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 5, 'き', 'き', NULL, 9, 10, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 6, 'ます', 'ます', NULL, 10, 12, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-1', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-2', 0, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-2', 2, '問わず', 'とわず', (select id from words where primary_form = '問う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"問","r":"と"},{"t":"わず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-2', 3, '募集して', 'ぼしゅうして', (select id from words where primary_form = '募集' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"募集","r":"ぼしゅう"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-2', 4, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-2', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-3', 0, '季節', 'きせつ', (select id from words where primary_form = '季節' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"季節","r":"きせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-3', 2, '問わず', 'とわず', (select id from words where primary_form = '問う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"問","r":"と"},{"t":"わず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-3', 3, '人気', 'にんき', (select id from words where primary_form = '人気' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"人気","r":"にんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-3', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-3', 5, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 0, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 2, '問わず', 'とわず', (select id from words where primary_form = '問う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"問","r":"と"},{"t":"わず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 3, '利用', 'りよう', (select id from words where primary_form = '利用' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"利用","r":"りよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 5, 'き', 'き', NULL, 9, 10, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 6, 'ます', 'ます', NULL, 10, 12, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotowazu-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-1', 0, '長い', 'ながい', (select id from words where primary_form = '長い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"長","r":"なが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-1', 1, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-1', 2, 'にわたって', 'にわたって', NULL, 4, 9, '[{"t":"にわたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-1', 3, '話し合った', 'はなしあった', (select id from words where primary_form = '話し合う' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"話","r":"はな"},{"t":"し"},{"t":"合","r":"あ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-1', 4, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-2', 0, '全国', 'ぜんこく', (select id from words where primary_form = '全国' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"全国","r":"ぜんこく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-2', 1, 'にわたって', 'にわたって', NULL, 2, 7, '[{"t":"にわたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-2', 2, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-2', 3, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-2', 4, '降りました', 'ふりました', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"降","r":"ふ"},{"t":"りました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-2', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-3', 0, '広い', 'ひろい', (select id from words where primary_form = '広い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"広","r":"ひろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-3', 1, '範囲', 'はんい', (select id from words where primary_form = '範囲' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"範囲","r":"はんい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-3', 2, 'にわたって', 'にわたって', NULL, 4, 9, '[{"t":"にわたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-3', 3, '調査しました', 'ちょうさしました', (select id from words where primary_form = '調査' and language_id = 'lang-ja' and published order by id limit 1), 9, 15, '[{"t":"調査","r":"ちょうさ"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-3', 4, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-4', 0, '工事', 'こうじ', (select id from words where primary_form = '工事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"工事","r":"こうじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-4', 2, '長い', 'ながい', (select id from words where primary_form = '長い' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"長","r":"なが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-4', 3, '期間', 'きかん', (select id from words where primary_form = '期間' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"期間","r":"きかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-4', 4, 'にわたって', 'にわたって', NULL, 7, 12, '[{"t":"にわたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-4', 5, '続いた', 'つづいた', (select id from words where primary_form = '続く' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"続","r":"つづ"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niwataru-4', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 2, '皮', 'かわ', (select id from words where primary_form = '皮' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"皮","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 3, '切り', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"切","r":"き"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 5, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 6, '世界', 'せかい', (select id from words where primary_form = '世界' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"世界","r":"せかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 7, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 8, '発表します', 'はっぴょうします', (select id from words where primary_form = '発表' and language_id = 'lang-ja' and published order by id limit 1), 11, 16, '[{"t":"発表","r":"はっぴょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-1', 9, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 1, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 3, '皮', 'かわ', (select id from words where primary_form = '皮' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"皮","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 4, '切り', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"切","r":"き"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 6, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 7, '人気', 'にんき', (select id from words where primary_form = '人気' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"人気","r":"にんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 8, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 9, '出ました', 'でました', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"出","r":"で"},{"t":"ました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-2', 10, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 0, '今回', 'こんかい', (select id from words where primary_form = '今回' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今回","r":"こんかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 2, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 4, '皮', 'かわ', (select id from words where primary_form = '皮' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"皮","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 5, '切り', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"切","r":"き"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 6, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 7, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 8, '議論', 'ぎろん', (select id from words where primary_form = '議論' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"議論","r":"ぎろん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 9, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 10, '始まった', 'はじまった', (select id from words where primary_form = '始まる' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"始","r":"はじ"},{"t":"まった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-3', 11, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 2, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 3, '皮', 'かわ', (select id from words where primary_form = '皮' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"皮","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 4, '切り', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"切","r":"き"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 6, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 7, '全国', 'ぜんこく', (select id from words where primary_form = '全国' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"全国","r":"ぜんこく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 8, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 9, '広がった', 'ひろがった', (select id from words where primary_form = '広がる' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"広","r":"ひろ"},{"t":"がった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kawakiri-4', 10, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-1', 0, '心', 'こころ', (select id from words where primary_form = '心' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"心","r":"こころ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-1', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-1', 2, '込めて', 'こめて', (select id from words where primary_form = '込める' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"込","r":"こ"},{"t":"めて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-1', 3, '作りました', 'つくりました', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"作","r":"つく"},{"t":"りました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-1', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-2', 0, '感謝', 'かんしゃ', (select id from words where primary_form = '感謝' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"感謝","r":"かんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-2', 2, '込めて', 'こめて', (select id from words where primary_form = '込める' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"込","r":"こ"},{"t":"めて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-2', 3, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-2', 4, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-2', 5, '書いた', 'かいた', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"書","r":"か"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-3', 0, '愛', 'あい', (select id from words where primary_form = '愛' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"愛","r":"あい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-3', 2, '込めて', 'こめて', (select id from words where primary_form = '込める' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"込","r":"こ"},{"t":"めて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-3', 3, '歌います', 'うたいます', (select id from words where primary_form = '歌う' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"歌","r":"うた"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-4', 0, '力', 'ちから', (select id from words where primary_form = '力' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"力","r":"ちから"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-4', 2, '込めて', 'こめて', (select id from words where primary_form = '込める' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"込","r":"こ"},{"t":"めて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-4', 3, '押した', 'おした', (select id from words where primary_form = '押す' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"押","r":"お"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wokomete-4', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 1, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 3, '巡って', 'めぐって', (select id from words where primary_form = '巡る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"巡","r":"めぐ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 4, '議論', 'ぎろん', (select id from words where primary_form = '議論' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"議論","r":"ぎろん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 5, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 6, '続いて', 'つづいて', (select id from words where primary_form = '続く' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"続","r":"つづ"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 7, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-1', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-2', 0, '土地', 'とち', (select id from words where primary_form = '土地' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"土地","r":"とち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-2', 2, '巡って', 'めぐって', (select id from words where primary_form = '巡る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"巡","r":"めぐ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-2', 3, '争い', 'あらそい', (select id from words where primary_form = '争い' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"争","r":"あらそ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-2', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-2', 5, '起きた', 'おきた', (select id from words where primary_form = '起きる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"起","r":"お"},{"t":"きた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-3', 0, '計画', 'けいかく', (select id from words where primary_form = '計画' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"計画","r":"けいかく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-3', 2, '巡って', 'めぐって', (select id from words where primary_form = '巡る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"巡","r":"めぐ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-3', 3, '意見', 'いけん', (select id from words where primary_form = '意見' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"意見","r":"いけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-3', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-3', 5, '分かれた', 'わかれた', (select id from words where primary_form = '分かれる' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"分","r":"わ"},{"t":"かれた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-4', 0, '事故', 'じこ', (select id from words where primary_form = '事故' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"事故","r":"じこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-4', 2, '巡って', 'めぐって', (select id from words where primary_form = '巡る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"巡","r":"めぐ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-4', 3, '調査', 'ちょうさ', (select id from words where primary_form = '調査' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"調査","r":"ちょうさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-4', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-4', 5, '行われた', 'おこなわれた', (select id from words where primary_form = '行う' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"行","r":"おこな"},{"t":"われた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womegutte-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-1', 0, '事実', 'じじつ', (select id from words where primary_form = '事実' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"事実","r":"じじつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-1', 2, '基づいて', 'もとづいて', (select id from words where primary_form = '基づく' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"基","r":"もと"},{"t":"づいて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-1', 3, '書いて', 'かいて', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"書","r":"か"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-1', 4, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-1', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-2', 0, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-2', 2, '基づいて', 'もとづいて', (select id from words where primary_form = '基づく' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"基","r":"もと"},{"t":"づいて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-2', 3, '処理します', 'しょりします', (select id from words where primary_form = '処理' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"処理","r":"しょり"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-2', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-3', 0, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-3', 2, '基づいて', 'もとづいて', (select id from words where primary_form = '基づく' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"基","r":"もと"},{"t":"づいて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-3', 3, '話します', 'はなします', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"話","r":"はな"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-3', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-4', 0, '調査', 'ちょうさ', (select id from words where primary_form = '調査' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"調査","r":"ちょうさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-4', 2, '基づいて', 'もとづいて', (select id from words where primary_form = '基づく' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"基","r":"もと"},{"t":"づいて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-4', 3, '発表しました', 'はっぴょうしました', (select id from words where primary_form = '発表' and language_id = 'lang-ja' and published order by id limit 1), 7, 13, '[{"t":"発表","r":"はっぴょう"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nimotozuite-4', 4, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 0, '事実', 'じじつ', (select id from words where primary_form = '事実' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"事実","r":"じじつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 2, 'も', 'も', NULL, 3, 4, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 5, '小説', 'しょうせつ', (select id from words where primary_form = '小説' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"小説","r":"しょうせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 6, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 7, '書いた', 'かいた', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"書","r":"か"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-1', 8, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 0, '資料', 'しりょう', (select id from words where primary_form = '資料' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"資料","r":"しりょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 2, 'も', 'も', NULL, 3, 4, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 5, '計画', 'けいかく', (select id from words where primary_form = '計画' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"計画","r":"けいかく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 6, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 7, '立てた', 'たてた', (select id from words where primary_form = '立てる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"立","r":"た"},{"t":"てた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-2', 8, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-3', 0, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-3', 2, 'も', 'も', NULL, 3, 4, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-3', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-3', 5, '説明します', 'せつめいします', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"説明","r":"せつめい"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-4', 0, '調査', 'ちょうさ', (select id from words where primary_form = '調査' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"調査","r":"ちょうさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-4', 2, 'も', 'も', NULL, 3, 4, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-4', 3, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-4', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-4', 5, '報告します', 'ほうこくします', (select id from words where primary_form = '報告' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"報告","r":"ほうこく"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-womotoni-4', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-1', 0, '収入', 'しゅうにゅう', (select id from words where primary_form = '収入' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"収入","r":"しゅうにゅう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-1', 2, '応じて', 'おうじて', (select id from words where primary_form = '応じる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"応","r":"おう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-1', 3, '税金', 'ぜいきん', (select id from words where primary_form = '税金' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"税金","r":"ぜいきん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-1', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-1', 5, '決まる', 'きまる', (select id from words where primary_form = '決まる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"決","r":"き"},{"t":"まる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-2', 0, '必要', 'ひつよう', (select id from words where primary_form = '必要' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"必要","r":"ひつよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-2', 2, '応じて', 'おうじて', (select id from words where primary_form = '応じる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"応","r":"おう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-2', 3, '手伝います', 'てつだいます', (select id from words where primary_form = '手伝う' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"手伝","r":"てつだ"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-3', 0, '季節', 'きせつ', (select id from words where primary_form = '季節' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"季節","r":"きせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-3', 2, '応じて', 'おうじて', (select id from words where primary_form = '応じる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"応","r":"おう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-3', 3, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-3', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-3', 5, '変わる', 'かわる', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"変","r":"か"},{"t":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-4', 0, '年齢', 'ねんれい', (select id from words where primary_form = '年齢' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"年齢","r":"ねんれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-4', 2, '応じて', 'おうじて', (select id from words where primary_form = '応じる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"応","r":"おう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-4', 3, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-4', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-4', 5, '違います', 'ちがいます', (select id from words where primary_form = '違う' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"違","r":"ちが"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioujite-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb);
