-- N2 example sentences, batch 2: scope, contrast, and the hypothetical.
--
-- に関して, に沿って, に反して, に限らず and に限り narrow or widen what a
-- statement covers. 〜反面 and 〜一方で set two halves of a thing against each
-- other. Then the ものなら pair, which look alike and mean opposite things:
-- potential + ものなら is a wish (帰れるものなら帰りたい), volitional +
-- ものなら is a threat (遅れようものなら叱られる) — so they are written back
-- to back. 〜といっても closes the batch by taking a claim back.
--
-- Nothing had to be reworded; all forty passed check:examples first time.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- ni-kanshite
  ('sent-ex-nikanshite-1', 'lang-ja', '事故に関して調査しています。', 'じこ に かんして ちょうさ して います。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikanshite-2', 'lang-ja', 'あの問題に関して意見を聞きたい。', 'あの もんだい に かんして いけん お ききたい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikanshite-3', 'lang-ja', '環境に関して発表します。', 'かんきょう に かんして はっぴょう します。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikanshite-4', 'lang-ja', '費用に関して説明します。', 'ひよう に かんして せつめい します。', 'lvl-ja-n2', 'authored', true),
  -- ni-sotte
  ('sent-ex-nisotte-1', 'lang-ja', '川に沿って歩きました。', 'かわ に そって あるきました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisotte-2', 'lang-ja', '道に沿って木が並んでいる。', 'みち に そって き が ならんで いる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisotte-3', 'lang-ja', '計画に沿って進めます。', 'けいかく に そって すすめます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisotte-4', 'lang-ja', '規則に沿って行動してください。', 'きそく に そって こうどう して ください。', 'lvl-ja-n2', 'authored', true),
  -- ni-hanshite
  ('sent-ex-nihanshite-1', 'lang-ja', '予想に反して、彼が勝った。', 'よそう に はんして、かれ が かった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nihanshite-2', 'lang-ja', '期待に反して、結果は悪かった。', 'きたい に はんして、けっか わ わるかった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nihanshite-3', 'lang-ja', '規則に反して行動した。', 'きそく に はんして こうどう した。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nihanshite-4', 'lang-ja', '親の考えに反して、彼は外国へ行った。', 'おや の かんがえ に はんして、かれ わ がいこく え いった。', 'lvl-ja-n2', 'authored', true),
  -- ni-kagirazu
  ('sent-ex-nikagirazu-1', 'lang-ja', '子供に限らず、大人も楽しめます。', 'こども に かぎらず、おとな も たのしめます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikagirazu-2', 'lang-ja', '日本に限らず、外国でも人気があります。', 'にほん に かぎらず、がいこく で も にんき が あります。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikagirazu-3', 'lang-ja', '冬に限らず、夏も忙しい。', 'ふゆ に かぎらず、なつ も いそがしい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikagirazu-4', 'lang-ja', '学生に限らず、先生も参加できます。', 'がくせい に かぎらず、せんせい も さんか できます。', 'lvl-ja-n2', 'authored', true),
  -- ni-kagiri
  ('sent-ex-nikagiri-1', 'lang-ja', '学生に限り、無料です。', 'がくせい に かぎり、むりょう です。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikagiri-2', 'lang-ja', '今日に限り、安くなります。', 'きょう に かぎり、やすく なります。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikagiri-3', 'lang-ja', '会員に限り利用できます。', 'かいいん に かぎり りよう できます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nikagiri-4', 'lang-ja', '予約した人に限り、入れます。', 'よやく した ひと に かぎり、はいれます。', 'lvl-ja-n2', 'authored', true),
  -- hanmen
  ('sent-ex-hanmen-1', 'lang-ja', '便利な反面、値段が高い。', 'べんり な はんめん、ねだん が たかい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-hanmen-2', 'lang-ja', '仕事は忙しい反面、面白い。', 'しごと わ いそがしい はんめん、おもしろい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-hanmen-3', 'lang-ja', 'あの店は安い反面、味がよくない。', 'あの みせ わ やすい はんめん、あじ が よくない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-hanmen-4', 'lang-ja', '都会は便利な反面、人が多い。', 'とかい わ べんり な はんめん、ひと が おおい。', 'lvl-ja-n2', 'authored', true),
  -- ippou-de
  ('sent-ex-ippoude-1', 'lang-ja', '経済が成長する一方で、環境が悪くなっている。', 'けいざい が せいちょう する いっぽう で、かんきょう が わるく なって いる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ippoude-2', 'lang-ja', '人口が増える一方で、子供が減っている。', 'じんこう が ふえる いっぽう で、こども が へって いる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ippoude-3', 'lang-ja', '便利になる一方で、失うものもある。', 'べんり に なる いっぽう で、うしなう もの も ある。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ippoude-4', 'lang-ja', '彼は厳しい一方で、優しいところもある。', 'かれ わ きびしい いっぽう で、やさしい ところ も ある。', 'lvl-ja-n2', 'authored', true),
  -- mono-nara
  ('sent-ex-mononara-1', 'lang-ja', '帰れるものなら帰りたい。', 'かえれる もの なら かえりたい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-mononara-2', 'lang-ja', '行けるものなら行きたい。', 'いける もの なら いきたい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-mononara-3', 'lang-ja', 'できるものならやってみたい。', 'できる もの なら やって みたい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-mononara-4', 'lang-ja', '会えるものなら会いたい。', 'あえる もの なら あいたい。', 'lvl-ja-n2', 'authored', true),
  -- you-mono-nara
  ('sent-ex-youmononara-1', 'lang-ja', '失敗しようものなら、大変なことになる。', 'しっぱい しよう もの なら、たいへん な こと に なる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-youmononara-2', 'lang-ja', '遅れようものなら、叱られる。', 'おくれよう もの なら、しかられる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-youmononara-3', 'lang-ja', '忘れようものなら、彼は怒るだろう。', 'わすれよう もの なら、かれ わ おこる だろう。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-youmononara-4', 'lang-ja', '言おうものなら、笑われるだろう。', 'いおう もの なら、わらわれる だろう。', 'lvl-ja-n2', 'authored', true),
  -- to-ittemo
  ('sent-ex-toittemo-1', 'lang-ja', '英語が話せるといっても、少しだけです。', 'えいご が はなせる と いっても、すこし だけ です。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-toittemo-2', 'lang-ja', '家といっても、小さいアパートです。', 'いえ と いっても、ちいさい アパート です。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-toittemo-3', 'lang-ja', '旅行といっても、近くの町へ行っただけだ。', 'りょこう と いっても、ちかく の まち え いった だけ だ。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-toittemo-4', 'lang-ja', '忙しいといっても、休む時間はある。', 'いそがしい と いっても、やすむ じかん わ ある。', 'lvl-ja-n2', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-nikanshite-1', 'sent-ex-nikanshite-1', 'en', 'We are investigating the accident.', 'authored'),
  ('st-ex-nikanshite-2', 'sent-ex-nikanshite-2', 'en', 'I would like to hear your view on that problem.', 'authored'),
  ('st-ex-nikanshite-3', 'sent-ex-nikanshite-3', 'en', 'I am giving a presentation on the environment.', 'authored'),
  ('st-ex-nikanshite-4', 'sent-ex-nikanshite-4', 'en', 'I will explain about the cost.', 'authored'),
  ('st-ex-nisotte-1', 'sent-ex-nisotte-1', 'en', 'I walked along the river.', 'authored'),
  ('st-ex-nisotte-2', 'sent-ex-nisotte-2', 'en', 'Trees stand along the road.', 'authored'),
  ('st-ex-nisotte-3', 'sent-ex-nisotte-3', 'en', 'We will proceed in line with the plan.', 'authored'),
  ('st-ex-nisotte-4', 'sent-ex-nisotte-4', 'en', 'Please act in accordance with the rules.', 'authored'),
  ('st-ex-nihanshite-1', 'sent-ex-nihanshite-1', 'en', 'Contrary to expectations, he won.', 'authored'),
  ('st-ex-nihanshite-2', 'sent-ex-nihanshite-2', 'en', 'Against our hopes, the result was poor.', 'authored'),
  ('st-ex-nihanshite-3', 'sent-ex-nihanshite-3', 'en', 'He acted against the rules.', 'authored'),
  ('st-ex-nihanshite-4', 'sent-ex-nihanshite-4', 'en', 'Against his parents'' wishes, he went abroad.', 'authored'),
  ('st-ex-nikagirazu-1', 'sent-ex-nikagirazu-1', 'en', 'Adults can enjoy it too, not just children.', 'authored'),
  ('st-ex-nikagirazu-2', 'sent-ex-nikagirazu-2', 'en', 'It is popular abroad as well as in Japan.', 'authored'),
  ('st-ex-nikagirazu-3', 'sent-ex-nikagirazu-3', 'en', 'We are busy in summer as well as in winter.', 'authored'),
  ('st-ex-nikagirazu-4', 'sent-ex-nikagirazu-4', 'en', 'Teachers can take part too, not only students.', 'authored'),
  ('st-ex-nikagiri-1', 'sent-ex-nikagiri-1', 'en', 'It is free for students only.', 'authored'),
  ('st-ex-nikagiri-2', 'sent-ex-nikagiri-2', 'en', 'Today only, it is cheaper.', 'authored'),
  ('st-ex-nikagiri-3', 'sent-ex-nikagiri-3', 'en', 'Only members may use it.', 'authored'),
  ('st-ex-nikagiri-4', 'sent-ex-nikagiri-4', 'en', 'Only those who booked may go in.', 'authored'),
  ('st-ex-hanmen-1', 'sent-ex-hanmen-1', 'en', 'It is convenient, but on the other side of that the price is high.', 'authored'),
  ('st-ex-hanmen-2', 'sent-ex-hanmen-2', 'en', 'The work is busy, but interesting with it.', 'authored'),
  ('st-ex-hanmen-3', 'sent-ex-hanmen-3', 'en', 'That shop is cheap, but the food is not good.', 'authored'),
  ('st-ex-hanmen-4', 'sent-ex-hanmen-4', 'en', 'The city is convenient, and for that very reason crowded.', 'authored'),
  ('st-ex-ippoude-1', 'sent-ex-ippoude-1', 'en', 'While the economy grows, the environment gets worse.', 'authored'),
  ('st-ex-ippoude-2', 'sent-ex-ippoude-2', 'en', 'While the population rises, the number of children falls.', 'authored'),
  ('st-ex-ippoude-3', 'sent-ex-ippoude-3', 'en', 'As things get more convenient, there are also things we lose.', 'authored'),
  ('st-ex-ippoude-4', 'sent-ex-ippoude-4', 'en', 'He is strict, and at the same time there is a kind side to him.', 'authored'),
  ('st-ex-mononara-1', 'sent-ex-mononara-1', 'en', 'If I could go home, I would.', 'authored'),
  ('st-ex-mononara-2', 'sent-ex-mononara-2', 'en', 'If I could go, I would want to.', 'authored'),
  ('st-ex-mononara-3', 'sent-ex-mononara-3', 'en', 'If it were possible, I would like to try.', 'authored'),
  ('st-ex-mononara-4', 'sent-ex-mononara-4', 'en', 'If I could see her, I would want to.', 'authored'),
  ('st-ex-youmononara-1', 'sent-ex-youmononara-1', 'en', 'If I were to fail, it would be a disaster.', 'authored'),
  ('st-ex-youmononara-2', 'sent-ex-youmononara-2', 'en', 'If I so much as turn up late, I get told off.', 'authored'),
  ('st-ex-youmononara-3', 'sent-ex-youmononara-3', 'en', 'If he were to forget, he would be furious.', 'authored'),
  ('st-ex-youmononara-4', 'sent-ex-youmononara-4', 'en', 'If I said that, I would be laughed at.', 'authored'),
  ('st-ex-toittemo-1', 'sent-ex-toittemo-1', 'en', 'I can speak English, but only a little.', 'authored'),
  ('st-ex-toittemo-2', 'sent-ex-toittemo-2', 'en', 'I say house, but it is a small flat.', 'authored'),
  ('st-ex-toittemo-3', 'sent-ex-toittemo-3', 'en', 'I say trip, but I only went to the next town.', 'authored'),
  ('st-ex-toittemo-4', 'sent-ex-toittemo-4', 'en', 'I say busy, but I have time to rest.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('ni-kanshite', 'sent-ex-nikanshite-1', 0),
  ('ni-kanshite', 'sent-ex-nikanshite-2', 1),
  ('ni-kanshite', 'sent-ex-nikanshite-3', 2),
  ('ni-kanshite', 'sent-ex-nikanshite-4', 3),
  ('ni-sotte', 'sent-ex-nisotte-1', 0),
  ('ni-sotte', 'sent-ex-nisotte-2', 1),
  ('ni-sotte', 'sent-ex-nisotte-3', 2),
  ('ni-sotte', 'sent-ex-nisotte-4', 3),
  ('ni-hanshite', 'sent-ex-nihanshite-1', 0),
  ('ni-hanshite', 'sent-ex-nihanshite-2', 1),
  ('ni-hanshite', 'sent-ex-nihanshite-3', 2),
  ('ni-hanshite', 'sent-ex-nihanshite-4', 3),
  ('ni-kagirazu', 'sent-ex-nikagirazu-1', 0),
  ('ni-kagirazu', 'sent-ex-nikagirazu-2', 1),
  ('ni-kagirazu', 'sent-ex-nikagirazu-3', 2),
  ('ni-kagirazu', 'sent-ex-nikagirazu-4', 3),
  ('ni-kagiri', 'sent-ex-nikagiri-1', 0),
  ('ni-kagiri', 'sent-ex-nikagiri-2', 1),
  ('ni-kagiri', 'sent-ex-nikagiri-3', 2),
  ('ni-kagiri', 'sent-ex-nikagiri-4', 3),
  ('hanmen', 'sent-ex-hanmen-1', 0),
  ('hanmen', 'sent-ex-hanmen-2', 1),
  ('hanmen', 'sent-ex-hanmen-3', 2),
  ('hanmen', 'sent-ex-hanmen-4', 3),
  ('ippou-de', 'sent-ex-ippoude-1', 0),
  ('ippou-de', 'sent-ex-ippoude-2', 1),
  ('ippou-de', 'sent-ex-ippoude-3', 2),
  ('ippou-de', 'sent-ex-ippoude-4', 3),
  ('mono-nara', 'sent-ex-mononara-1', 0),
  ('mono-nara', 'sent-ex-mononara-2', 1),
  ('mono-nara', 'sent-ex-mononara-3', 2),
  ('mono-nara', 'sent-ex-mononara-4', 3),
  ('you-mono-nara', 'sent-ex-youmononara-1', 0),
  ('you-mono-nara', 'sent-ex-youmononara-2', 1),
  ('you-mono-nara', 'sent-ex-youmononara-3', 2),
  ('you-mono-nara', 'sent-ex-youmononara-4', 3),
  ('to-ittemo', 'sent-ex-toittemo-1', 0),
  ('to-ittemo', 'sent-ex-toittemo-2', 1),
  ('to-ittemo', 'sent-ex-toittemo-3', 2),
  ('to-ittemo', 'sent-ex-toittemo-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-nikanshite-1', 'sent-ex-nikanshite-2', 'sent-ex-nikanshite-3', 'sent-ex-nikanshite-4', 'sent-ex-nisotte-1', 'sent-ex-nisotte-2', 'sent-ex-nisotte-3', 'sent-ex-nisotte-4', 'sent-ex-nihanshite-1', 'sent-ex-nihanshite-2', 'sent-ex-nihanshite-3', 'sent-ex-nihanshite-4', 'sent-ex-nikagirazu-1', 'sent-ex-nikagirazu-2', 'sent-ex-nikagirazu-3', 'sent-ex-nikagirazu-4', 'sent-ex-nikagiri-1', 'sent-ex-nikagiri-2', 'sent-ex-nikagiri-3', 'sent-ex-nikagiri-4', 'sent-ex-hanmen-1', 'sent-ex-hanmen-2', 'sent-ex-hanmen-3', 'sent-ex-hanmen-4', 'sent-ex-ippoude-1', 'sent-ex-ippoude-2', 'sent-ex-ippoude-3', 'sent-ex-ippoude-4', 'sent-ex-mononara-1', 'sent-ex-mononara-2', 'sent-ex-mononara-3', 'sent-ex-mononara-4', 'sent-ex-youmononara-1', 'sent-ex-youmononara-2', 'sent-ex-youmononara-3', 'sent-ex-youmononara-4', 'sent-ex-toittemo-1', 'sent-ex-toittemo-2', 'sent-ex-toittemo-3', 'sent-ex-toittemo-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-nikanshite-1', 0, '事故', 'じこ', (select id from words where primary_form = '事故' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"事故","r":"じこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-1', 2, '関して', 'かんして', (select id from words where primary_form = '関する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"関","r":"かん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-1', 3, '調査して', 'ちょうさして', (select id from words where primary_form = '調査' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"調査","r":"ちょうさ"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-1', 4, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-1', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 1, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 3, '関して', 'かんして', (select id from words where primary_form = '関する' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"関","r":"かん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 4, '意見', 'いけん', (select id from words where primary_form = '意見' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"意見","r":"いけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 5, 'を', 'を', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 6, '聞きたい', 'ききたい', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"聞","r":"き"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-3', 0, '環境', 'かんきょう', (select id from words where primary_form = '環境' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"環境","r":"かんきょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-3', 2, '関して', 'かんして', (select id from words where primary_form = '関する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"関","r":"かん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-3', 3, '発表します', 'はっぴょうします', (select id from words where primary_form = '発表' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"発表","r":"はっぴょう"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-3', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-4', 0, '費用', 'ひよう', (select id from words where primary_form = '費用' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"費用","r":"ひよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-4', 2, '関して', 'かんして', (select id from words where primary_form = '関する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"関","r":"かん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-4', 3, '説明します', 'せつめいします', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"説明","r":"せつめい"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikanshite-4', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-1', 0, '川', 'かわ', (select id from words where primary_form = '川' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"川","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-1', 2, '沿って', 'そって', (select id from words where primary_form = '沿う' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"沿","r":"そ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-1', 3, '歩きました', 'あるきました', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"歩","r":"ある"},{"t":"きました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-1', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 0, '道', 'みち', (select id from words where primary_form = '道' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"道","r":"みち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 2, '沿って', 'そって', (select id from words where primary_form = '沿う' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"沿","r":"そ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 3, '木', 'き', (select id from words where primary_form = '木' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"木","r":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 4, 'が', 'が', NULL, 6, 7, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 5, '並んで', 'ならんで', (select id from words where primary_form = '並ぶ' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"並","r":"なら"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 6, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-2', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-3', 0, '計画', 'けいかく', (select id from words where primary_form = '計画' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"計画","r":"けいかく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-3', 2, '沿って', 'そって', (select id from words where primary_form = '沿う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"沿","r":"そ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-3', 3, '進めます', 'すすめます', (select id from words where primary_form = '進める' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"進","r":"すす"},{"t":"めます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-4', 0, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-4', 2, '沿って', 'そって', (select id from words where primary_form = '沿う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"沿","r":"そ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-4', 3, '行動して', 'こうどうして', (select id from words where primary_form = '行動' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"行動","r":"こうどう"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-4', 4, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisotte-4', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 0, '予想', 'よそう', (select id from words where primary_form = '予想' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"予想","r":"よそう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 2, '反して', 'はんして', (select id from words where primary_form = '反する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"反","r":"はん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 4, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 5, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 6, '勝った', 'かった', (select id from words where primary_form = '勝つ' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"勝","r":"か"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-1', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 0, '期待', 'きたい', (select id from words where primary_form = '期待' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"期待","r":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 2, '反して', 'はんして', (select id from words where primary_form = '反する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"反","r":"はん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 4, '結果', 'けっか', (select id from words where primary_form = '結果' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"結果","r":"けっか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 5, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 6, '悪', 'わる', (select id from words where primary_form = '悪' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"悪","r":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 7, 'かった', 'かった', NULL, 11, 14, '[{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-2', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-3', 0, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-3', 2, '反して', 'はんして', (select id from words where primary_form = '反する' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"反","r":"はん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-3', 3, '行動した', 'こうどうした', (select id from words where primary_form = '行動' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"行動","r":"こうどう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 0, '親', 'おや', (select id from words where primary_form = '親' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"親","r":"おや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 2, '考え', 'かんがえ', (select id from words where primary_form = '考え' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"考","r":"かんが"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 4, '反して', 'はんして', (select id from words where primary_form = '反する' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"反","r":"はん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 6, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 7, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 8, '外国', 'がいこく', (select id from words where primary_form = '外国' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"外国","r":"がいこく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 9, 'へ', 'へ', NULL, 13, 14, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 10, '行った', 'いった', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 14, 17, '[{"t":"行","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nihanshite-4', 11, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 1, 'に限らず', 'にかぎらず', NULL, 2, 6, '[{"t":"に"},{"t":"限","r":"かぎ"},{"t":"らず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 3, '大人', 'おとな', (select id from words where primary_form = '大人' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"大人","r":"おとな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 4, 'も', 'も', NULL, 9, 10, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 5, '楽しめ', 'たのしめ', (select id from words where primary_form = '楽しむ' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"楽","r":"たの"},{"t":"しめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 6, 'ます', 'ます', NULL, 13, 15, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-1', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 1, 'に限らず', 'にかぎらず', NULL, 2, 6, '[{"t":"に"},{"t":"限","r":"かぎ"},{"t":"らず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 3, '外国', 'がいこく', (select id from words where primary_form = '外国' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"外国","r":"がいこく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 4, 'でも', 'でも', (select id from words where primary_form = 'でも' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"でも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 5, '人気', 'にんき', (select id from words where primary_form = '人気' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"人気","r":"にんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 6, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 7, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-2', 8, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-3', 0, '冬', 'ふゆ', (select id from words where primary_form = '冬' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"冬","r":"ふゆ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-3', 1, 'に限らず', 'にかぎらず', NULL, 1, 5, '[{"t":"に"},{"t":"限","r":"かぎ"},{"t":"らず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-3', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-3', 3, '夏', 'なつ', (select id from words where primary_form = '夏' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"夏","r":"なつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-3', 4, 'も', 'も', NULL, 7, 8, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-3', 5, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 1, 'に限らず', 'にかぎらず', NULL, 2, 6, '[{"t":"に"},{"t":"限","r":"かぎ"},{"t":"らず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 3, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 4, 'も', 'も', NULL, 9, 10, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 5, '参加', 'さんか', (select id from words where primary_form = '参加' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"参加","r":"さんか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 6, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 7, 'き', 'き', NULL, 13, 14, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 8, 'ます', 'ます', NULL, 14, 16, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagirazu-4', 9, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-1', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-1', 2, '限り', 'かぎり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"限","r":"かぎ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-1', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-1', 4, '無料', 'むりょう', (select id from words where primary_form = '無料' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"無料","r":"むりょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-1', 5, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-1', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-2', 0, '今日', 'きょう', (select id from words where primary_form = '今日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今日","r":"きょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-2', 2, '限り', 'かぎり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"限","r":"かぎ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-2', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-2', 4, '安くなります', 'やすくなります', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"安","r":"やす"},{"t":"くなります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-2', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 0, '会員', 'かいいん', (select id from words where primary_form = '会員' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会員","r":"かいいん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 2, '限り', 'かぎり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"限","r":"かぎ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 3, '利用', 'りよう', (select id from words where primary_form = '利用' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"利用","r":"りよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 5, 'き', 'き', NULL, 8, 9, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 6, 'ます', 'ます', NULL, 9, 11, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-3', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-4', 0, '予約した', 'よやくした', (select id from words where primary_form = '予約' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"予約","r":"よやく"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-4', 1, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-4', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-4', 3, '限り', 'かぎり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"限","r":"かぎ"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-4', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-4', 5, '入れます', 'はいれます', (select id from words where primary_form = '入れる' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"入","r":"はい"},{"t":"れます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikagiri-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 0, '便利', 'べんり', (select id from words where primary_form = '便利' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"便利","r":"べんり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 2, '反面', 'はんめん', NULL, 3, 5, '[{"t":"反面","r":"はんめん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 4, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 5, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 6, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-1', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-2', 0, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-2', 2, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-2', 3, '反面', 'はんめん', NULL, 6, 8, '[{"t":"反面","r":"はんめん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-2', 5, '面白い', 'おもしろい', (select id from words where primary_form = '面白い' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 3, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 4, '反面', 'はんめん', NULL, 6, 8, '[{"t":"反面","r":"はんめん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 6, '味', 'あじ', (select id from words where primary_form = '味' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"味","r":"あじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 7, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 8, 'よく', 'よく', NULL, 11, 13, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 9, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-3', 10, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 0, '都会', 'とかい', (select id from words where primary_form = '都会' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"都会","r":"とかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 2, '便利', 'べんり', (select id from words where primary_form = '便利' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"便利","r":"べんり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 4, '反面', 'はんめん', NULL, 6, 8, '[{"t":"反面","r":"はんめん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 6, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 7, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 8, '多い', 'おおい', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"多","r":"おお"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hanmen-4', 9, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 0, '経済', 'けいざい', (select id from words where primary_form = '経済' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経済","r":"けいざい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 2, '成長する', 'せいちょうする', (select id from words where primary_form = '成長' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"成長","r":"せいちょう"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 3, '一方', 'いっぽう', (select id from words where primary_form = '一方' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"一方","r":"いっぽう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 5, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 6, '環境', 'かんきょう', (select id from words where primary_form = '環境' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"環境","r":"かんきょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 7, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 8, '悪', 'わる', (select id from words where primary_form = '悪' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"悪","r":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 9, 'く', 'く', NULL, 15, 16, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 10, 'なって', 'なって', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 16, 19, '[{"t":"なって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 11, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 19, 21, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-1', 12, '。', '。', NULL, 21, 22, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 0, '人口', 'じんこう', (select id from words where primary_form = '人口' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"人口","r":"じんこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 2, '増える', 'ふえる', (select id from words where primary_form = '増える' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"増","r":"ふ"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 3, '一方', 'いっぽう', (select id from words where primary_form = '一方' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"一方","r":"いっぽう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 5, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 6, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 7, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 8, '減って', 'へって', (select id from words where primary_form = '減る' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"減","r":"へ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 9, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 16, 18, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-2', 10, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 0, '便利', 'べんり', (select id from words where primary_form = '便利' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"便利","r":"べんり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 2, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 3, '一方', 'いっぽう', (select id from words where primary_form = '一方' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"一方","r":"いっぽう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 6, '失う', 'うしなう', (select id from words where primary_form = '失う' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"失","r":"うしな"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 7, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 8, 'も', 'も', NULL, 13, 14, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 9, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-3', 10, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 2, '厳しい', 'きびしい', (select id from words where primary_form = '厳しい' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"厳","r":"きび"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 3, '一方', 'いっぽう', (select id from words where primary_form = '一方' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"一方","r":"いっぽう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 6, '優しい', 'やさしい', (select id from words where primary_form = '優しい' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"優","r":"やさ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 7, 'ところ', 'ところ', NULL, 12, 15, '[{"t":"ところ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 8, 'も', 'も', NULL, 15, 16, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 9, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 16, 18, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ippoude-4', 10, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-1', 0, '帰れる', 'かえれる', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"帰","r":"かえ"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-1', 1, 'ものなら', 'ものなら', NULL, 3, 7, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-1', 2, '帰りたい', 'かえりたい', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"帰","r":"かえ"},{"t":"りたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-1', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-2', 0, '行ける', 'いける', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"行","r":"い"},{"t":"ける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-2', 1, 'ものなら', 'ものなら', NULL, 3, 7, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-2', 2, '行きたい', 'いきたい', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"行","r":"い"},{"t":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-2', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-3', 0, 'できる', 'できる', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"できる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-3', 1, 'ものなら', 'ものなら', NULL, 3, 7, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-3', 2, 'や', 'や', (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-3', 3, 'って', 'って', (select id from words where primary_form = 'って' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-3', 4, 'み', 'み', NULL, 10, 11, '[{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-3', 5, 'たい', 'たい', (select id from words where primary_form = 'たい' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-4', 0, '会える', 'あえる', (select id from words where primary_form = '会う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"会","r":"あ"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-4', 1, 'ものなら', 'ものなら', NULL, 3, 7, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-4', 2, '会いたい', 'あいたい', (select id from words where primary_form = '会う' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"会","r":"あ"},{"t":"いたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mononara-4', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-1', 0, '失敗しよう', 'しっぱいしよう', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"失敗","r":"しっぱい"},{"t":"しよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-1', 1, 'ものなら', 'ものなら', NULL, 5, 9, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-1', 2, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-1', 3, '大変', 'たいへん', (select id from words where primary_form = '大変' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"大変","r":"たいへん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-1', 4, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-1', 5, 'ことになる', 'ことになる', NULL, 13, 18, '[{"t":"ことになる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-1', 6, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-2', 0, '遅れよう', 'おくれよう', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"遅","r":"おく"},{"t":"れよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-2', 1, 'ものなら', 'ものなら', NULL, 4, 8, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-2', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-2', 3, '叱られる', 'しかられる', (select id from words where primary_form = '叱る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"叱","r":"しか"},{"t":"られる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-2', 4, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 0, '忘れよう', 'わすれよう', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"忘","r":"わす"},{"t":"れよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 1, 'ものなら', 'ものなら', NULL, 4, 8, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 3, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 5, '怒る', 'おこる', (select id from words where primary_form = '怒る' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"怒","r":"おこ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 6, 'だろう', 'だろう', NULL, 13, 16, '[{"t":"だろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-3', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-4', 0, '言おう', 'いおう', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"言","r":"い"},{"t":"おう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-4', 1, 'ものなら', 'ものなら', NULL, 3, 7, '[{"t":"ものなら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-4', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-4', 3, '笑われる', 'わらわれる', (select id from words where primary_form = '笑う' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"笑","r":"わら"},{"t":"われる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-4', 4, 'だろう', 'だろう', NULL, 12, 15, '[{"t":"だろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-youmononara-4', 5, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 0, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 2, '話せる', 'はなせる', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"話","r":"はな"},{"t":"せる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 3, 'といっても', 'といっても', NULL, 6, 11, '[{"t":"といっても"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 4, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 5, '少し', 'すこし', (select id from words where primary_form = '少し' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"少","r":"すこ"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 6, 'だけ', 'だけ', (select id from words where primary_form = '丈' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"だけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 7, 'です', 'です', NULL, 16, 18, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-1', 8, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-2', 0, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-2', 1, 'といっても', 'といっても', NULL, 1, 6, '[{"t":"といっても"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-2', 3, '小さい', 'ちいさい', (select id from words where primary_form = '小さい' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"小","r":"ちい"},{"t":"さい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-2', 4, 'アパート', 'アパート', (select id from words where primary_form = 'アパート' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"アパート"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-2', 5, 'です', 'です', NULL, 14, 16, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-2', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 0, '旅行', 'りょこう', (select id from words where primary_form = '旅行' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"旅行","r":"りょこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 1, 'といっても', 'といっても', NULL, 2, 7, '[{"t":"といっても"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 3, '近く', 'ちかく', (select id from words where primary_form = '近く' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"近","r":"ちか"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 4, 'の', 'の', NULL, 10, 11, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 5, '町', 'まち', (select id from words where primary_form = '町' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"町","r":"まち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 6, 'へ', 'へ', NULL, 12, 13, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 7, '行った', 'いった', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"行","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 8, 'だけ', 'だけ', (select id from words where primary_form = '丈' and language_id = 'lang-ja' and published order by id limit 1), 16, 18, '[{"t":"だけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 9, 'だ', 'だ', NULL, 18, 19, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-3', 10, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 1, 'といっても', 'といっても', NULL, 3, 8, '[{"t":"といっても"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 3, '休む', 'やすむ', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"休","r":"やす"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 4, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 5, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 6, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toittemo-4', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb);
