-- N2 example sentences, batch 3: qualifying a claim, and cutting things out.
--
-- 〜とはいえ, 〜からといって and 〜とは限らない all stop a reasonable-looking
-- inference from going through; 〜にすぎない and 〜にほかならない size a claim
-- down or pin it to one cause. Then 〜なしに and 〜抜きに remove something,
-- 〜きり says nothing has happened since, 〜次第 says the moment it does, and
-- 〜か否か asks which of the two it is.
--
-- Two rewordings:
--
--   いい shreds to い|い — the index holds 良い and not the kana spelling —
--   so both とは限らない sentences that needed "good" use 良い.
--
--   すぎません came apart as す|ぎ|ません. にすぎない cuts clean in the
--   plain form only, so the 想像 sentence is 想像にすぎない.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- towa-ie
  ('sent-ex-towaie-1', 'lang-ja', '春とはいえ、朝は寒い。', 'はる と わ いえ、あさ わ さむい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-towaie-2', 'lang-ja', '便利とはいえ、値段が高い。', 'べんり と わ いえ、ねだん が たかい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-towaie-3', 'lang-ja', '子供とはいえ、責任はある。', 'こども と わ いえ、せきにん わ ある。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-towaie-4', 'lang-ja', '忙しいとはいえ、休みは必要だ。', 'いそがしい と わ いえ、やすみ わ ひつよう だ。', 'lvl-ja-n2', 'authored', true),
  -- kara-to-itte
  ('sent-ex-karatoitte-1', 'lang-ja', '安いからといって、全部買うことはない。', 'やすい から と いって、ぜんぶ かう こと わ ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-karatoitte-2', 'lang-ja', '学生だからといって、漢字が全部書けるわけではない。', 'がくせい だ から と いって、かんじ が ぜんぶ かける わけ で わ ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-karatoitte-3', 'lang-ja', '雨だからといって、試合は中止になりません。', 'あめ だ から と いって、しあい わ ちゅうし に なりません。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-karatoitte-4', 'lang-ja', '高いからといって、品質が良いとは限らない。', 'たかい から と いって、ひんしつ が よい と わ かぎらない。', 'lvl-ja-n2', 'authored', true),
  -- towa-kagiranai
  ('sent-ex-towakagiranai-1', 'lang-ja', '高いものが良いとは限らない。', 'たかい もの が よい と わ かぎらない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-towakagiranai-2', 'lang-ja', '有名な店が美味しいとは限らない。', 'ゆうめい な みせ が おいしい と わ かぎらない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-towakagiranai-3', 'lang-ja', '努力すれば成功するとは限らない。', 'どりょく すれば せいこう する と わ かぎらない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-towakagiranai-4', 'lang-ja', '医者が正しいとは限らない。', 'いしゃ が ただしい と わ かぎらない。', 'lvl-ja-n2', 'authored', true),
  -- ni-suginai
  ('sent-ex-nisuginai-1', 'lang-ja', 'それは言い訳にすぎない。', 'それ わ いいわけ に すぎない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisuginai-2', 'lang-ja', '彼は子供にすぎない。', 'かれ わ こども に すぎない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisuginai-3', 'lang-ja', 'それは私の想像にすぎない。', 'それ わ わたし の そうぞう に すぎない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisuginai-4', 'lang-ja', 'これは始まりにすぎない。', 'これ わ はじまり に すぎない。', 'lvl-ja-n2', 'authored', true),
  -- ni-hokanaranai
  ('sent-ex-hokanaranai-1', 'lang-ja', '成功は努力の結果にほかならない。', 'せいこう わ どりょく の けっか に ほかならない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-hokanaranai-2', 'lang-ja', 'これは彼のおかげにほかならない。', 'これ わ かれ の おかげ に ほかならない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-hokanaranai-3', 'lang-ja', '失敗は経験にほかならない。', 'しっぱい わ けいけん に ほかならない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-hokanaranai-4', 'lang-ja', 'あの音は風の音にほかならない。', 'あの おと わ かぜ の おと に ほかならない。', 'lvl-ja-n2', 'authored', true),
  -- nashi-ni
  ('sent-ex-nashini-1', 'lang-ja', '許可なしに入らないでください。', 'きょか なし に はいらないで ください。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nashini-2', 'lang-ja', '連絡なしに休んだ。', 'れんらく なし に やすんだ。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nashini-3', 'lang-ja', '予約なしに利用できます。', 'よやく なし に りよう できます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nashini-4', 'lang-ja', '説明なしに始めた。', 'せつめい なし に はじめた。', 'lvl-ja-n2', 'authored', true),
  -- nuki-ni
  ('sent-ex-nukini-1', 'lang-ja', '冗談抜きに話しましょう。', 'じょうだん ぬき に はなしましょう。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nukini-2', 'lang-ja', '彼の協力抜きにはできなかった。', 'かれ の きょうりょく ぬき に わ できなかった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nukini-3', 'lang-ja', '朝ご飯抜きに出かけた。', 'あさごはん ぬき に でかけた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nukini-4', 'lang-ja', '説明抜きには分からない。', 'せつめい ぬき に わ わからない。', 'lvl-ja-n2', 'authored', true),
  -- kkiri
  ('sent-ex-kkiri-1', 'lang-ja', '彼とは一度会ったきりです。', 'かれ と わ いちど あった きり です。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kkiri-2', 'lang-ja', '兄は出かけたきり帰りません。', 'あに わ でかけた きり かえりません。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kkiri-3', 'lang-ja', '二人きりで話しました。', 'ふたり きり で はなしました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kkiri-4', 'lang-ja', 'あの本は借りたきりです。', 'あの ほん わ かりた きり です。', 'lvl-ja-n2', 'authored', true),
  -- shidai
  ('sent-ex-shidai-1', 'lang-ja', '着き次第、連絡します。', 'つき しだい、れんらく します。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-shidai-2', 'lang-ja', '会議が終わり次第、帰ります。', 'かいぎ が おわり しだい、かえります。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-shidai-3', 'lang-ja', '分かり次第、教えます。', 'わかり しだい、おしえます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-shidai-4', 'lang-ja', '準備ができ次第、始めます。', 'じゅんび が でき しだい、はじめます。', 'lvl-ja-n2', 'authored', true),
  -- ka-ina-ka
  ('sent-ex-kainaka-1', 'lang-ja', '行くか否か、決めていない。', 'いく か いな か、きめて いない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kainaka-2', 'lang-ja', '正しいか否か調べます。', 'ただしい か いな か しらべます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kainaka-3', 'lang-ja', '成功するか否かは努力次第だ。', 'せいこう する か いな か わ どりょく しだい だ。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-kainaka-4', 'lang-ja', '参加するか否か教えてください。', 'さんか する か いな か おしえて ください。', 'lvl-ja-n2', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-towaie-1', 'sent-ex-towaie-1', 'en', 'Spring though it is, the mornings are cold.', 'authored'),
  ('st-ex-towaie-2', 'sent-ex-towaie-2', 'en', 'Convenient though it is, the price is high.', 'authored'),
  ('st-ex-towaie-3', 'sent-ex-towaie-3', 'en', 'Child though he is, he has responsibilities.', 'authored'),
  ('st-ex-towaie-4', 'sent-ex-towaie-4', 'en', 'Busy though I am, I need a day off.', 'authored'),
  ('st-ex-karatoitte-1', 'sent-ex-karatoitte-1', 'en', 'Just because it is cheap does not mean you have to buy the lot.', 'authored'),
  ('st-ex-karatoitte-2', 'sent-ex-karatoitte-2', 'en', 'Being a student does not mean you can write every kanji.', 'authored'),
  ('st-ex-karatoitte-3', 'sent-ex-karatoitte-3', 'en', 'The match will not be called off just because it is raining.', 'authored'),
  ('st-ex-karatoitte-4', 'sent-ex-karatoitte-4', 'en', 'Expensive does not necessarily mean well made.', 'authored'),
  ('st-ex-towakagiranai-1', 'sent-ex-towakagiranai-1', 'en', 'The expensive one is not necessarily the good one.', 'authored'),
  ('st-ex-towakagiranai-2', 'sent-ex-towakagiranai-2', 'en', 'A famous shop does not always serve good food.', 'authored'),
  ('st-ex-towakagiranai-3', 'sent-ex-towakagiranai-3', 'en', 'Working hard does not always mean succeeding.', 'authored'),
  ('st-ex-towakagiranai-4', 'sent-ex-towakagiranai-4', 'en', 'The doctor is not necessarily right.', 'authored'),
  ('st-ex-nisuginai-1', 'sent-ex-nisuginai-1', 'en', 'That is nothing but an excuse.', 'authored'),
  ('st-ex-nisuginai-2', 'sent-ex-nisuginai-2', 'en', 'He is no more than a child.', 'authored'),
  ('st-ex-nisuginai-3', 'sent-ex-nisuginai-3', 'en', 'It is only my imagination.', 'authored'),
  ('st-ex-nisuginai-4', 'sent-ex-nisuginai-4', 'en', 'This is only the beginning.', 'authored'),
  ('st-ex-hokanaranai-1', 'sent-ex-hokanaranai-1', 'en', 'Success is nothing other than the result of effort.', 'authored'),
  ('st-ex-hokanaranai-2', 'sent-ex-hokanaranai-2', 'en', 'This is thanks to him and nothing else.', 'authored'),
  ('st-ex-hokanaranai-3', 'sent-ex-hokanaranai-3', 'en', 'Failure is nothing but experience.', 'authored'),
  ('st-ex-hokanaranai-4', 'sent-ex-hokanaranai-4', 'en', 'That sound is nothing but the wind.', 'authored'),
  ('st-ex-nashini-1', 'sent-ex-nashini-1', 'en', 'Please do not enter without permission.', 'authored'),
  ('st-ex-nashini-2', 'sent-ex-nashini-2', 'en', 'He took the day off without letting anyone know.', 'authored'),
  ('st-ex-nashini-3', 'sent-ex-nashini-3', 'en', 'You can use it without booking.', 'authored'),
  ('st-ex-nashini-4', 'sent-ex-nashini-4', 'en', 'They started without any explanation.', 'authored'),
  ('st-ex-nukini-1', 'sent-ex-nukini-1', 'en', 'Let us talk with the joking left out.', 'authored'),
  ('st-ex-nukini-2', 'sent-ex-nukini-2', 'en', 'Without his help I could not have done it.', 'authored'),
  ('st-ex-nukini-3', 'sent-ex-nukini-3', 'en', 'I went out without any breakfast.', 'authored'),
  ('st-ex-nukini-4', 'sent-ex-nukini-4', 'en', 'Without an explanation I cannot follow it.', 'authored'),
  ('st-ex-kkiri-1', 'sent-ex-kkiri-1', 'en', 'I have met him just the once.', 'authored'),
  ('st-ex-kkiri-2', 'sent-ex-kkiri-2', 'en', 'My older brother went out and has not been back since.', 'authored'),
  ('st-ex-kkiri-3', 'sent-ex-kkiri-3', 'en', 'We talked, just the two of us.', 'authored'),
  ('st-ex-kkiri-4', 'sent-ex-kkiri-4', 'en', 'I borrowed that book and never gave it back.', 'authored'),
  ('st-ex-shidai-1', 'sent-ex-shidai-1', 'en', 'I will get in touch as soon as I arrive.', 'authored'),
  ('st-ex-shidai-2', 'sent-ex-shidai-2', 'en', 'I will go home the moment the meeting ends.', 'authored'),
  ('st-ex-shidai-3', 'sent-ex-shidai-3', 'en', 'I will tell you as soon as I know.', 'authored'),
  ('st-ex-shidai-4', 'sent-ex-shidai-4', 'en', 'We will start as soon as everything is ready.', 'authored'),
  ('st-ex-kainaka-1', 'sent-ex-kainaka-1', 'en', 'I have not decided whether to go or not.', 'authored'),
  ('st-ex-kainaka-2', 'sent-ex-kainaka-2', 'en', 'I will check whether it is right or not.', 'authored'),
  ('st-ex-kainaka-3', 'sent-ex-kainaka-3', 'en', 'Whether it succeeds or not depends on the effort.', 'authored'),
  ('st-ex-kainaka-4', 'sent-ex-kainaka-4', 'en', 'Please tell me whether you are taking part or not.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('towa-ie', 'sent-ex-towaie-1', 0),
  ('towa-ie', 'sent-ex-towaie-2', 1),
  ('towa-ie', 'sent-ex-towaie-3', 2),
  ('towa-ie', 'sent-ex-towaie-4', 3),
  ('kara-to-itte', 'sent-ex-karatoitte-1', 0),
  ('kara-to-itte', 'sent-ex-karatoitte-2', 1),
  ('kara-to-itte', 'sent-ex-karatoitte-3', 2),
  ('kara-to-itte', 'sent-ex-karatoitte-4', 3),
  ('towa-kagiranai', 'sent-ex-towakagiranai-1', 0),
  ('towa-kagiranai', 'sent-ex-towakagiranai-2', 1),
  ('towa-kagiranai', 'sent-ex-towakagiranai-3', 2),
  ('towa-kagiranai', 'sent-ex-towakagiranai-4', 3),
  ('ni-suginai', 'sent-ex-nisuginai-1', 0),
  ('ni-suginai', 'sent-ex-nisuginai-2', 1),
  ('ni-suginai', 'sent-ex-nisuginai-3', 2),
  ('ni-suginai', 'sent-ex-nisuginai-4', 3),
  ('ni-hokanaranai', 'sent-ex-hokanaranai-1', 0),
  ('ni-hokanaranai', 'sent-ex-hokanaranai-2', 1),
  ('ni-hokanaranai', 'sent-ex-hokanaranai-3', 2),
  ('ni-hokanaranai', 'sent-ex-hokanaranai-4', 3),
  ('nashi-ni', 'sent-ex-nashini-1', 0),
  ('nashi-ni', 'sent-ex-nashini-2', 1),
  ('nashi-ni', 'sent-ex-nashini-3', 2),
  ('nashi-ni', 'sent-ex-nashini-4', 3),
  ('nuki-ni', 'sent-ex-nukini-1', 0),
  ('nuki-ni', 'sent-ex-nukini-2', 1),
  ('nuki-ni', 'sent-ex-nukini-3', 2),
  ('nuki-ni', 'sent-ex-nukini-4', 3),
  ('kkiri', 'sent-ex-kkiri-1', 0),
  ('kkiri', 'sent-ex-kkiri-2', 1),
  ('kkiri', 'sent-ex-kkiri-3', 2),
  ('kkiri', 'sent-ex-kkiri-4', 3),
  ('shidai', 'sent-ex-shidai-1', 0),
  ('shidai', 'sent-ex-shidai-2', 1),
  ('shidai', 'sent-ex-shidai-3', 2),
  ('shidai', 'sent-ex-shidai-4', 3),
  ('ka-ina-ka', 'sent-ex-kainaka-1', 0),
  ('ka-ina-ka', 'sent-ex-kainaka-2', 1),
  ('ka-ina-ka', 'sent-ex-kainaka-3', 2),
  ('ka-ina-ka', 'sent-ex-kainaka-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-towaie-1', 'sent-ex-towaie-2', 'sent-ex-towaie-3', 'sent-ex-towaie-4', 'sent-ex-karatoitte-1', 'sent-ex-karatoitte-2', 'sent-ex-karatoitte-3', 'sent-ex-karatoitte-4', 'sent-ex-towakagiranai-1', 'sent-ex-towakagiranai-2', 'sent-ex-towakagiranai-3', 'sent-ex-towakagiranai-4', 'sent-ex-nisuginai-1', 'sent-ex-nisuginai-2', 'sent-ex-nisuginai-3', 'sent-ex-nisuginai-4', 'sent-ex-hokanaranai-1', 'sent-ex-hokanaranai-2', 'sent-ex-hokanaranai-3', 'sent-ex-hokanaranai-4', 'sent-ex-nashini-1', 'sent-ex-nashini-2', 'sent-ex-nashini-3', 'sent-ex-nashini-4', 'sent-ex-nukini-1', 'sent-ex-nukini-2', 'sent-ex-nukini-3', 'sent-ex-nukini-4', 'sent-ex-kkiri-1', 'sent-ex-kkiri-2', 'sent-ex-kkiri-3', 'sent-ex-kkiri-4', 'sent-ex-shidai-1', 'sent-ex-shidai-2', 'sent-ex-shidai-3', 'sent-ex-shidai-4', 'sent-ex-kainaka-1', 'sent-ex-kainaka-2', 'sent-ex-kainaka-3', 'sent-ex-kainaka-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-towaie-1', 0, '春', 'はる', (select id from words where primary_form = '春' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"春","r":"はる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-1', 1, 'とはいえ', 'とはいえ', NULL, 1, 5, '[{"t":"とはいえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-1', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-1', 3, '朝', 'あさ', (select id from words where primary_form = '朝' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"朝","r":"あさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-1', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-1', 5, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-1', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-2', 0, '便利', 'べんり', (select id from words where primary_form = '便利' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"便利","r":"べんり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-2', 1, 'とはいえ', 'とはいえ', NULL, 2, 6, '[{"t":"とはいえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-2', 3, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-2', 4, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-2', 5, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-3', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-3', 1, 'とはいえ', 'とはいえ', NULL, 2, 6, '[{"t":"とはいえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-3', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-3', 3, '責任', 'せきにん', (select id from words where primary_form = '責任' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"責任","r":"せきにん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-3', 5, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 1, 'とはいえ', 'とはいえ', NULL, 3, 7, '[{"t":"とはいえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 3, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 5, '必要', 'ひつよう', (select id from words where primary_form = '必要' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"必要","r":"ひつよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 6, 'だ', 'だ', NULL, 13, 14, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towaie-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 1, 'からといって', 'からといって', NULL, 2, 8, '[{"t":"からといって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 3, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 4, '買う', 'かう', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"買","r":"か"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 5, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 6, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 15, 16, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 7, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 16, 18, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-1', 8, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 1, 'だから', 'だから', (select id from words where primary_form = 'だから' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"だから"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 2, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 3, 'い', 'い', NULL, 6, 7, '[{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 4, 'って', 'って', (select id from words where primary_form = 'って' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 5, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 6, '漢字', 'かんじ', (select id from words where primary_form = '漢字' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"漢字","r":"かんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 7, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 8, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 9, '書ける', 'かける', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 15, 18, '[{"t":"書","r":"か"},{"t":"ける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 10, 'わけではない', 'わけではない', NULL, 18, 24, '[{"t":"わけではない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-2', 11, '。', '。', NULL, 24, 25, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 1, 'だから', 'だから', (select id from words where primary_form = 'だから' and language_id = 'lang-ja' and published order by id limit 1), 1, 4, '[{"t":"だから"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 2, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 3, 'い', 'い', NULL, 5, 6, '[{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 4, 'って', 'って', (select id from words where primary_form = 'って' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 6, '試合', 'しあい', (select id from words where primary_form = '試合' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"試合","r":"しあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 7, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 8, '中止', 'ちゅうし', (select id from words where primary_form = '中止' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"中止","r":"ちゅうし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 9, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 10, 'なりません', 'なりません', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 15, 20, '[{"t":"なりません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-3', 11, '。', '。', NULL, 20, 21, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 0, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 1, 'からといって', 'からといって', NULL, 2, 8, '[{"t":"からといって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 3, '品質', 'ひんしつ', (select id from words where primary_form = '品質' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"品質","r":"ひんしつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 4, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 5, '良い', 'よい', (select id from words where primary_form = '良い' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"良","r":"よ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 6, 'とは限らない', 'とは限らない', NULL, 14, 20, '[{"t":"とは"},{"t":"限","r":"限"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-karatoitte-4', 7, '。', '。', NULL, 20, 21, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-1', 0, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-1', 1, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-1', 2, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-1', 3, '良い', 'よい', (select id from words where primary_form = '良い' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"良","r":"よ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-1', 4, 'とは限らない', 'とは限らない', NULL, 7, 13, '[{"t":"とは"},{"t":"限","r":"限"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-1', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-2', 0, '有名', 'ゆうめい', (select id from words where primary_form = '有名' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"有名","r":"ゆうめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-2', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-2', 2, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-2', 3, 'が', 'が', NULL, 4, 5, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-2', 4, '美味しい', 'おいしい', (select id from words where primary_form = '美味しい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"美味","r":"おい"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-2', 5, 'とは限らない', 'とは限らない', NULL, 9, 15, '[{"t":"とは"},{"t":"限","r":"限"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-2', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-3', 0, '努力すれば', 'どりょくすれば', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"努力","r":"どりょく"},{"t":"すれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-3', 1, '成功する', 'せいこうする', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"成功","r":"せいこう"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-3', 2, 'とは限らない', 'とは限らない', NULL, 9, 15, '[{"t":"とは"},{"t":"限","r":"限"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-3', 3, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-4', 0, '医者', 'いしゃ', (select id from words where primary_form = '医者' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"医者","r":"いしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-4', 2, '正しい', 'ただしい', (select id from words where primary_form = '正しい' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"正","r":"ただ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-4', 3, 'とは限らない', 'とは限らない', NULL, 6, 12, '[{"t":"とは"},{"t":"限","r":"限"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towakagiranai-4', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-1', 0, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-1', 2, '言い訳', 'いいわけ', (select id from words where primary_form = '言い訳' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"言","r":"い"},{"t":"い"},{"t":"訳","r":"わけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-1', 3, 'にすぎない', 'にすぎない', NULL, 6, 11, '[{"t":"にすぎない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-1', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-2', 2, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-2', 3, 'にすぎない', 'にすぎない', NULL, 4, 9, '[{"t":"にすぎない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-3', 0, 'それ', 'それ', (select id from words where primary_form = 'それ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"それ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-3', 2, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-3', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-3', 4, '想像', 'そうぞう', (select id from words where primary_form = '想像' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"想像","r":"そうぞう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-3', 5, 'にすぎない', 'にすぎない', NULL, 7, 12, '[{"t":"にすぎない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-4', 0, 'これは', 'これは', NULL, 0, 3, '[{"t":"これは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-4', 1, '始まり', 'はじまり', (select id from words where primary_form = '始まり' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"始","r":"はじ"},{"t":"まり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-4', 2, 'にすぎない', 'にすぎない', NULL, 6, 11, '[{"t":"にすぎない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisuginai-4', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-1', 0, '成功', 'せいこう', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"成功","r":"せいこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-1', 2, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-1', 3, 'の', 'の', NULL, 5, 6, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-1', 4, '結果', 'けっか', (select id from words where primary_form = '結果' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"結果","r":"けっか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-1', 5, 'にほかならない', 'にほかならない', NULL, 8, 15, '[{"t":"にほかならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-1', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-2', 0, 'これは', 'これは', NULL, 0, 3, '[{"t":"これは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-2', 1, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-2', 2, 'お', 'お', NULL, 5, 6, '[{"t":"お"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-2', 3, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-2', 4, 'げ', 'げ', NULL, 7, 8, '[{"t":"げ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-2', 5, 'にほかならない', 'にほかならない', NULL, 8, 15, '[{"t":"にほかならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-2', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-3', 0, '失敗', 'しっぱい', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"失敗","r":"しっぱい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-3', 2, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-3', 3, 'にほかならない', 'にほかならない', NULL, 5, 12, '[{"t":"にほかならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 1, '音', 'おと', (select id from words where primary_form = '音' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"音","r":"おと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 3, '風', 'かぜ', (select id from words where primary_form = '風' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"風","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 4, 'の', 'の', NULL, 5, 6, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 5, '音', 'おと', (select id from words where primary_form = '音' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"音","r":"おと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 6, 'にほかならない', 'にほかならない', NULL, 7, 14, '[{"t":"にほかならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hokanaranai-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-1', 0, '許可', 'きょか', (select id from words where primary_form = '許可' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"許可","r":"きょか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-1', 1, 'なし', 'なし', (select id from words where primary_form = '無し' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"なし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-1', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-1', 3, '入らない', 'はいらない', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"入","r":"はい"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-1', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-1', 5, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-2', 0, '連絡', 'れんらく', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"連絡","r":"れんらく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-2', 1, 'なし', 'なし', (select id from words where primary_form = '無し' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"なし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-2', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-2', 3, '休んだ', 'やすんだ', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"休","r":"やす"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-2', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 0, '予約', 'よやく', (select id from words where primary_form = '予約' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"予約","r":"よやく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 1, 'なし', 'なし', (select id from words where primary_form = '無し' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"なし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 3, '利用', 'りよう', (select id from words where primary_form = '利用' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"利用","r":"りよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 5, 'き', 'き', NULL, 8, 9, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 6, 'ます', 'ます', NULL, 9, 11, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-3', 7, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-4', 0, '説明', 'せつめい', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"説明","r":"せつめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-4', 1, 'なし', 'なし', (select id from words where primary_form = '無し' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"なし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-4', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-4', 3, '始めた', 'はじめた', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"始","r":"はじ"},{"t":"めた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashini-4', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-1', 0, '冗談', 'じょうだん', (select id from words where primary_form = '冗談' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"冗談","r":"じょうだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-1', 1, '抜きに', '抜きに', NULL, 2, 5, '[{"t":"抜","r":"抜"},{"t":"きに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-1', 2, '話し', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"話","r":"はな"},{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-1', 3, 'ましょう', 'ましょう', NULL, 7, 11, '[{"t":"ましょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-1', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 1, '協力', 'きょうりょく', (select id from words where primary_form = '協力' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"協力","r":"きょうりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 2, '抜きに', '抜きに', NULL, 4, 7, '[{"t":"抜","r":"抜"},{"t":"きに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 5, 'き', 'き', NULL, 9, 10, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 6, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-2', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-3', 0, '朝ご飯', 'あさごはん', (select id from words where primary_form = '朝ごはん' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"朝","r":"あさ"},{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-3', 1, '抜きに', '抜きに', NULL, 3, 6, '[{"t":"抜","r":"抜"},{"t":"きに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-3', 2, '出かけた', 'でかけた', (select id from words where primary_form = '出かける' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"出","r":"で"},{"t":"かけた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-3', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-4', 0, '説明', 'せつめい', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"説明","r":"せつめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-4', 1, '抜きに', '抜きに', NULL, 2, 5, '[{"t":"抜","r":"抜"},{"t":"きに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-4', 3, '分からない', 'わからない', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"分","r":"わ"},{"t":"からない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nukini-4', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-1', 1, 'とは', 'とは', NULL, 1, 3, '[{"t":"とは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-1', 2, '一度', 'いちど', (select id from words where primary_form = '一度' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"一度","r":"いちど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-1', 3, '会った', 'あった', (select id from words where primary_form = '会う' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"会","r":"あ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-1', 4, 'きり', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"きり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-1', 5, 'です', 'です', NULL, 10, 12, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-2', 0, '兄', 'あに', (select id from words where primary_form = '兄' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"兄","r":"あに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-2', 2, '出かけた', 'でかけた', (select id from words where primary_form = '出かける' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"出","r":"で"},{"t":"かけた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-2', 3, 'きり', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"きり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-2', 4, '帰りません', 'かえりません', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 8, 13, '[{"t":"帰","r":"かえ"},{"t":"りません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-2', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-3', 0, '二人', 'ふたり', (select id from words where primary_form = '二人' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"二人","r":"ふたり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-3', 1, 'きり', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"きり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-3', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-3', 3, '話しました', 'はなしました', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"話","r":"はな"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-4', 1, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-4', 3, '借りた', 'かりた', (select id from words where primary_form = '借りる' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"借","r":"か"},{"t":"りた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-4', 4, 'きり', 'きり', (select id from words where primary_form = '切り' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"きり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-4', 5, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kkiri-4', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-1', 0, '着き', 'つき', (select id from words where primary_form = '着く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"着","r":"つ"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-1', 1, '次第', 'しだい', (select id from words where primary_form = '次第' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"次第","r":"しだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-1', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-1', 3, '連絡します', 'れんらくします', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"連絡","r":"れんらく"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-1', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-2', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-2', 2, '終わり', 'おわり', (select id from words where primary_form = '終わり' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"終","r":"お"},{"t":"わり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-2', 3, '次第', 'しだい', (select id from words where primary_form = '次第' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"次第","r":"しだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-2', 5, '帰ります', 'かえります', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"帰","r":"かえ"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-2', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-3', 0, '分', 'わ', (select id from words where primary_form = '分' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"分","r":"わ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-3', 1, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-3', 2, 'り', 'り', NULL, 2, 3, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-3', 3, '次第', 'しだい', (select id from words where primary_form = '次第' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"次第","r":"しだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-3', 4, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-3', 5, '教えます', 'おしえます', (select id from words where primary_form = '教える' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"教","r":"おし"},{"t":"えます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-3', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 0, '準備', 'じゅんび', (select id from words where primary_form = '準備' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"準備","r":"じゅんび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 3, 'き', 'き', NULL, 4, 5, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 4, '次第', 'しだい', (select id from words where primary_form = '次第' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"次第","r":"しだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 5, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 6, '始めます', 'はじめます', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"始","r":"はじ"},{"t":"めます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shidai-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-1', 0, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-1', 1, 'か否か', 'かいなか', NULL, 2, 5, '[{"t":"か"},{"t":"否","r":"いな"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-1', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-1', 3, '決めて', 'きめて', (select id from words where primary_form = '決める' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"決","r":"き"},{"t":"めて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-1', 4, 'いない', 'いない', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-2', 0, '正しい', 'ただしい', (select id from words where primary_form = '正しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"正","r":"ただ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-2', 1, 'か否か', 'かいなか', NULL, 3, 6, '[{"t":"か"},{"t":"否","r":"いな"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-2', 2, '調べます', 'しらべます', (select id from words where primary_form = '調べる' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"調","r":"しら"},{"t":"べます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-2', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-3', 0, '成功する', 'せいこうする', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"成功","r":"せいこう"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-3', 1, 'か否か', 'かいなか', NULL, 4, 7, '[{"t":"か"},{"t":"否","r":"いな"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-3', 3, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-3', 4, '次第', 'しだい', (select id from words where primary_form = '次第' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"次第","r":"しだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-3', 5, 'だ', 'だ', NULL, 12, 13, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-4', 0, '参加する', 'さんかする', (select id from words where primary_form = '参加' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"参加","r":"さんか"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-4', 1, 'か否か', 'かいなか', NULL, 4, 7, '[{"t":"か"},{"t":"否","r":"いな"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-4', 2, '教えて', 'おしえて', (select id from words where primary_form = '教える' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"教","r":"おし"},{"t":"えて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-4', 3, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kainaka-4', 4, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb);
