-- N2 example sentences, batch 4: far from it, on top of that, and in the end.
--
-- 〜どころか overturns an expectation and 〜どころではない says there is no
-- room for the thing at all; 〜ばかりか and 〜上に pile a second fact on the
-- first. 〜ものだから gives the excuse. Then three that all land on an
-- outcome and differ in how they feel about it: 〜上で is deliberate,
-- 〜末に is long-drawn-out, 〜あげく is long-drawn-out and disappointing.
-- 〜ついでに and 〜やら〜やら close the batch.
--
-- One rewording: 働きすぎた shreds to 働き|す|ぎ|た — 〜すぎる attached to a
-- verb stem has no entry in the past — so the あげく example is 長く働いた.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- dokoro-ka
  ('sent-ex-dokoroka-1', 'lang-ja', '休むどころか、もっと忙しくなった。', 'やすむ どころか、もっと いそがしく なった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-dokoroka-2', 'lang-ja', '安くなるどころか、値段が上がった。', 'やすく なる どころか、ねだん が あがった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-dokoroka-3', 'lang-ja', '彼は謝るどころか、笑っていた。', 'かれ わ あやまる どころか、わらって いた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-dokoroka-4', 'lang-ja', '返事どころか、連絡もなかった。', 'へんじ どころか、れんらく も なかった。', 'lvl-ja-n2', 'authored', true),
  -- dokoro-dewa-nai
  ('sent-ex-dokorodewanai-1', 'lang-ja', '忙しくて、旅行どころではない。', 'いそがしくて、りょこう どころ で わ ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-dokorodewanai-2', 'lang-ja', '試験があるので、遊ぶどころではない。', 'しけん が ある ので、あそぶ どころ で わ ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-dokorodewanai-3', 'lang-ja', '病気で、仕事どころではなかった。', 'びょうき で、しごと どころ で わ なかった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-dokorodewanai-4', 'lang-ja', 'お金がなくて、買い物どころではない。', 'おかね が なくて、かいもの どころ で わ ない。', 'lvl-ja-n2', 'authored', true),
  -- bakari-ka
  ('sent-ex-bakarika-1', 'lang-ja', '雨ばかりか、風も強くなった。', 'あめ ばかりか、かぜ も つよく なった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-bakarika-2', 'lang-ja', '彼は英語ばかりか、料理も上手だ。', 'かれ わ えいご ばかりか、りょうり も じょうず だ。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-bakarika-3', 'lang-ja', '値段が高いばかりか、味も悪い。', 'ねだん が たかい ばかりか、あじ も わるい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-bakarika-4', 'lang-ja', '遅れたばかりか、連絡もしなかった。', 'おくれた ばかりか、れんらく も しなかった。', 'lvl-ja-n2', 'authored', true),
  -- mono-dakara
  ('sent-ex-monodakara-1', 'lang-ja', '電車が遅れたものだから、遅刻しました。', 'でんしゃ が おくれた もの だ から、ちこく しました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-monodakara-2', 'lang-ja', '忙しかったものだから、連絡できませんでした。', 'いそがしかった もの だ から、れんらく できません でした。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-monodakara-3', 'lang-ja', '安かったものだから、買ってしまいました。', 'やすかった もの だ から、かって しまいました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-monodakara-4', 'lang-ja', '頭が痛かったものだから、休みました。', 'あたま が いたかった もの だ から、やすみました。', 'lvl-ja-n2', 'authored', true),
  -- ue-de
  ('sent-ex-uede-1', 'lang-ja', 'よく考えた上で、決めます。', 'よく かんがえた うえ で、きめます。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-uede-2', 'lang-ja', '相談した上で、返事します。', 'そうだん した うえ で、へんじ します。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-uede-3', 'lang-ja', '説明を聞いた上で、質問してください。', 'せつめい お きいた うえ で、しつもん して ください。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-uede-4', 'lang-ja', '調査の上で、報告します。', 'ちょうさ の うえ で、ほうこく します。', 'lvl-ja-n2', 'authored', true),
  -- ue-ni
  ('sent-ex-ueni-1', 'lang-ja', '安い上に、美味しい。', 'やすい うえ に、おいしい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ueni-2', 'lang-ja', '彼は優しい上に、面白い。', 'かれ わ やさしい うえ に、おもしろい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ueni-3', 'lang-ja', '雨が降った上に、風も強かった。', 'あめ が ふった うえ に、かぜ も つよかった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ueni-4', 'lang-ja', '道に迷った上に、雨に降られた。', 'みち に まよった うえ に、あめ に ふられた。', 'lvl-ja-n2', 'authored', true),
  -- sue-ni
  ('sent-ex-sueni-1', 'lang-ja', '長い間考えた末に、決めました。', 'ながい あいだ かんがえた すえ に、きめました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-sueni-2', 'lang-ja', '相談した末に、中止することにした。', 'そうだん した すえ に、ちゅうし する こと に した。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-sueni-3', 'lang-ja', '努力の末に、成功しました。', 'どりょく の すえ に、せいこう しました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-sueni-4', 'lang-ja', '議論の末に、結論が出ました。', 'ぎろん の すえ に、けつろん が でました。', 'lvl-ja-n2', 'authored', true),
  -- agaku
  ('sent-ex-ageku-1', 'lang-ja', '長く待ったあげく、断られた。', 'ながく まった あげく、ことわられた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ageku-2', 'lang-ja', '議論したあげく、決まらなかった。', 'ぎろん した あげく、きまらなかった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ageku-3', 'lang-ja', '迷ったあげく、買いませんでした。', 'まよった あげく、かいません でした。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-ageku-4', 'lang-ja', '長く働いたあげく、病気になった。', 'ながく はたらいた あげく、びょうき に なった。', 'lvl-ja-n2', 'authored', true),
  -- tsuide-ni
  ('sent-ex-tsuideni-1', 'lang-ja', '買い物のついでに、銀行へ行った。', 'かいもの の ついで に、ぎんこう え いった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tsuideni-2', 'lang-ja', '駅へ行くついでに、手紙を出します。', 'えき え いく ついで に、てがみ お だします。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tsuideni-3', 'lang-ja', '掃除のついでに、部屋を片付けた。', 'そうじ の ついで に、へや お かたづけた。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tsuideni-4', 'lang-ja', '散歩のついでに、写真を撮った。', 'さんぽ の ついで に、しゃしん お とった。', 'lvl-ja-n2', 'authored', true),
  -- yara
  ('sent-ex-yara-1', 'lang-ja', '宿題やら準備やらで忙しい。', 'しゅくだい やら じゅんび やら で いそがしい。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-yara-2', 'lang-ja', '雨やら風やらで大変だった。', 'あめ やら かぜ やら で たいへん だった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-yara-3', 'lang-ja', '本やらノートやらが置いてある。', 'ほん やら ノート やら が おいて ある。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-yara-4', 'lang-ja', '泣くやら笑うやらで大変だった。', 'なく やら わらう やら で たいへん だった。', 'lvl-ja-n2', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-dokoroka-1', 'sent-ex-dokoroka-1', 'en', 'Far from resting, I got busier.', 'authored'),
  ('st-ex-dokoroka-2', 'sent-ex-dokoroka-2', 'en', 'Far from getting cheaper, the price went up.', 'authored'),
  ('st-ex-dokoroka-3', 'sent-ex-dokoroka-3', 'en', 'Far from apologising, he was laughing.', 'authored'),
  ('st-ex-dokoroka-4', 'sent-ex-dokoroka-4', 'en', 'Not so much as a reply — there was no word at all.', 'authored'),
  ('st-ex-dokorodewanai-1', 'sent-ex-dokorodewanai-1', 'en', 'I am too busy for anything like a holiday.', 'authored'),
  ('st-ex-dokorodewanai-2', 'sent-ex-dokorodewanai-2', 'en', 'With the exam coming, this is no time for playing.', 'authored'),
  ('st-ex-dokorodewanai-3', 'sent-ex-dokorodewanai-3', 'en', 'I was ill; work was out of the question.', 'authored'),
  ('st-ex-dokorodewanai-4', 'sent-ex-dokorodewanai-4', 'en', 'I have no money, so shopping is out of the question.', 'authored'),
  ('st-ex-bakarika-1', 'sent-ex-bakarika-1', 'en', 'Not only did it rain, the wind got up as well.', 'authored'),
  ('st-ex-bakarika-2', 'sent-ex-bakarika-2', 'en', 'He is good not only at English but at cooking too.', 'authored'),
  ('st-ex-bakarika-3', 'sent-ex-bakarika-3', 'en', 'Not only is it expensive, it tastes bad as well.', 'authored'),
  ('st-ex-bakarika-4', 'sent-ex-bakarika-4', 'en', 'Not only was he late, he did not get in touch either.', 'authored'),
  ('st-ex-monodakara-1', 'sent-ex-monodakara-1', 'en', 'The train was late, and that is why I was late in.', 'authored'),
  ('st-ex-monodakara-2', 'sent-ex-monodakara-2', 'en', 'I was busy, and that is why I did not get in touch.', 'authored'),
  ('st-ex-monodakara-3', 'sent-ex-monodakara-3', 'en', 'It was cheap, and so I went and bought it.', 'authored'),
  ('st-ex-monodakara-4', 'sent-ex-monodakara-4', 'en', 'I had a headache, and that is why I stayed off.', 'authored'),
  ('st-ex-uede-1', 'sent-ex-uede-1', 'en', 'I will decide after giving it proper thought.', 'authored'),
  ('st-ex-uede-2', 'sent-ex-uede-2', 'en', 'I will reply after talking it over.', 'authored'),
  ('st-ex-uede-3', 'sent-ex-uede-3', 'en', 'Please ask your questions after hearing the explanation.', 'authored'),
  ('st-ex-uede-4', 'sent-ex-uede-4', 'en', 'I will report after the investigation.', 'authored'),
  ('st-ex-ueni-1', 'sent-ex-ueni-1', 'en', 'It is cheap, and good as well.', 'authored'),
  ('st-ex-ueni-2', 'sent-ex-ueni-2', 'en', 'He is kind, and interesting with it.', 'authored'),
  ('st-ex-ueni-3', 'sent-ex-ueni-3', 'en', 'It rained, and on top of that the wind was strong.', 'authored'),
  ('st-ex-ueni-4', 'sent-ex-ueni-4', 'en', 'I got lost, and on top of that I was rained on.', 'authored'),
  ('st-ex-sueni-1', 'sent-ex-sueni-1', 'en', 'After long thought, I decided.', 'authored'),
  ('st-ex-sueni-2', 'sent-ex-sueni-2', 'en', 'After talking it over, we decided to call it off.', 'authored'),
  ('st-ex-sueni-3', 'sent-ex-sueni-3', 'en', 'After all that effort, I succeeded.', 'authored'),
  ('st-ex-sueni-4', 'sent-ex-sueni-4', 'en', 'After a long argument, we reached a conclusion.', 'authored'),
  ('st-ex-ageku-1', 'sent-ex-ageku-1', 'en', 'After waiting a long time, I was turned down.', 'authored'),
  ('st-ex-ageku-2', 'sent-ex-ageku-2', 'en', 'After all that arguing, nothing was decided.', 'authored'),
  ('st-ex-ageku-3', 'sent-ex-ageku-3', 'en', 'After all that dithering, I did not buy it.', 'authored'),
  ('st-ex-ageku-4', 'sent-ex-ageku-4', 'en', 'After working long hours, he ended up ill.', 'authored'),
  ('st-ex-tsuideni-1', 'sent-ex-tsuideni-1', 'en', 'While I was out shopping I went to the bank.', 'authored'),
  ('st-ex-tsuideni-2', 'sent-ex-tsuideni-2', 'en', 'I will post the letter on my way to the station.', 'authored'),
  ('st-ex-tsuideni-3', 'sent-ex-tsuideni-3', 'en', 'While I was cleaning I tidied the room too.', 'authored'),
  ('st-ex-tsuideni-4', 'sent-ex-tsuideni-4', 'en', 'I took a photograph while I was out for a walk.', 'authored'),
  ('st-ex-yara-1', 'sent-ex-yara-1', 'en', 'What with homework and getting ready, I am busy.', 'authored'),
  ('st-ex-yara-2', 'sent-ex-yara-2', 'en', 'What with the rain and the wind, it was awful.', 'authored'),
  ('st-ex-yara-3', 'sent-ex-yara-3', 'en', 'There are books and notebooks and everything else lying about.', 'authored'),
  ('st-ex-yara-4', 'sent-ex-yara-4', 'en', 'What with the crying and the laughing, it was quite a business.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('dokoro-ka', 'sent-ex-dokoroka-1', 0),
  ('dokoro-ka', 'sent-ex-dokoroka-2', 1),
  ('dokoro-ka', 'sent-ex-dokoroka-3', 2),
  ('dokoro-ka', 'sent-ex-dokoroka-4', 3),
  ('dokoro-dewa-nai', 'sent-ex-dokorodewanai-1', 0),
  ('dokoro-dewa-nai', 'sent-ex-dokorodewanai-2', 1),
  ('dokoro-dewa-nai', 'sent-ex-dokorodewanai-3', 2),
  ('dokoro-dewa-nai', 'sent-ex-dokorodewanai-4', 3),
  ('bakari-ka', 'sent-ex-bakarika-1', 0),
  ('bakari-ka', 'sent-ex-bakarika-2', 1),
  ('bakari-ka', 'sent-ex-bakarika-3', 2),
  ('bakari-ka', 'sent-ex-bakarika-4', 3),
  ('mono-dakara', 'sent-ex-monodakara-1', 0),
  ('mono-dakara', 'sent-ex-monodakara-2', 1),
  ('mono-dakara', 'sent-ex-monodakara-3', 2),
  ('mono-dakara', 'sent-ex-monodakara-4', 3),
  ('ue-de', 'sent-ex-uede-1', 0),
  ('ue-de', 'sent-ex-uede-2', 1),
  ('ue-de', 'sent-ex-uede-3', 2),
  ('ue-de', 'sent-ex-uede-4', 3),
  ('ue-ni', 'sent-ex-ueni-1', 0),
  ('ue-ni', 'sent-ex-ueni-2', 1),
  ('ue-ni', 'sent-ex-ueni-3', 2),
  ('ue-ni', 'sent-ex-ueni-4', 3),
  ('sue-ni', 'sent-ex-sueni-1', 0),
  ('sue-ni', 'sent-ex-sueni-2', 1),
  ('sue-ni', 'sent-ex-sueni-3', 2),
  ('sue-ni', 'sent-ex-sueni-4', 3),
  ('agaku', 'sent-ex-ageku-1', 0),
  ('agaku', 'sent-ex-ageku-2', 1),
  ('agaku', 'sent-ex-ageku-3', 2),
  ('agaku', 'sent-ex-ageku-4', 3),
  ('tsuide-ni', 'sent-ex-tsuideni-1', 0),
  ('tsuide-ni', 'sent-ex-tsuideni-2', 1),
  ('tsuide-ni', 'sent-ex-tsuideni-3', 2),
  ('tsuide-ni', 'sent-ex-tsuideni-4', 3),
  ('yara', 'sent-ex-yara-1', 0),
  ('yara', 'sent-ex-yara-2', 1),
  ('yara', 'sent-ex-yara-3', 2),
  ('yara', 'sent-ex-yara-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-dokoroka-1', 'sent-ex-dokoroka-2', 'sent-ex-dokoroka-3', 'sent-ex-dokoroka-4', 'sent-ex-dokorodewanai-1', 'sent-ex-dokorodewanai-2', 'sent-ex-dokorodewanai-3', 'sent-ex-dokorodewanai-4', 'sent-ex-bakarika-1', 'sent-ex-bakarika-2', 'sent-ex-bakarika-3', 'sent-ex-bakarika-4', 'sent-ex-monodakara-1', 'sent-ex-monodakara-2', 'sent-ex-monodakara-3', 'sent-ex-monodakara-4', 'sent-ex-uede-1', 'sent-ex-uede-2', 'sent-ex-uede-3', 'sent-ex-uede-4', 'sent-ex-ueni-1', 'sent-ex-ueni-2', 'sent-ex-ueni-3', 'sent-ex-ueni-4', 'sent-ex-sueni-1', 'sent-ex-sueni-2', 'sent-ex-sueni-3', 'sent-ex-sueni-4', 'sent-ex-ageku-1', 'sent-ex-ageku-2', 'sent-ex-ageku-3', 'sent-ex-ageku-4', 'sent-ex-tsuideni-1', 'sent-ex-tsuideni-2', 'sent-ex-tsuideni-3', 'sent-ex-tsuideni-4', 'sent-ex-yara-1', 'sent-ex-yara-2', 'sent-ex-yara-3', 'sent-ex-yara-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-dokoroka-1', 0, '休む', 'やすむ', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"休","r":"やす"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-1', 1, 'どころか', 'どころか', NULL, 2, 6, '[{"t":"どころか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-1', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-1', 3, 'もっと', 'もっと', (select id from words where primary_form = 'もっと' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"もっと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-1', 4, '忙しくなった', 'いそがしくなった', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 10, 16, '[{"t":"忙","r":"いそが"},{"t":"しくなった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-1', 5, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-2', 0, '安くなるどころか', 'やすくなるどころか', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 0, 8, '[{"t":"安","r":"やす"},{"t":"くなるどころか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-2', 1, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-2', 2, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-2', 3, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-2', 4, '上がった', 'あがった', (select id from words where primary_form = '上がる' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"上","r":"あ"},{"t":"がった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-2', 5, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 2, '謝る', 'あやまる', (select id from words where primary_form = '謝る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"謝","r":"あやま"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 3, 'どころか', 'どころか', NULL, 4, 8, '[{"t":"どころか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 5, '笑って', 'わらって', (select id from words where primary_form = '笑う' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"笑","r":"わら"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 6, 'いた', 'いた', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-3', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-4', 0, '返事', 'へんじ', (select id from words where primary_form = '返事' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"返事","r":"へんじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-4', 1, 'どころか', 'どころか', NULL, 2, 6, '[{"t":"どころか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-4', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-4', 3, '連絡', 'れんらく', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"連絡","r":"れんらく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-4', 4, 'も', 'も', NULL, 9, 10, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-4', 5, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokoroka-4', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-1', 0, '忙しくて', 'いそがしくて', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"忙","r":"いそが"},{"t":"しくて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-1', 1, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-1', 2, '旅行', 'りょこう', (select id from words where primary_form = '旅行' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"旅行","r":"りょこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-1', 3, 'どころではない', 'どころではない', NULL, 7, 14, '[{"t":"どころではない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-1', 4, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 2, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 3, 'ので', 'ので', NULL, 5, 7, '[{"t":"ので"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 5, '遊ぶ', 'あそぶ', (select id from words where primary_form = '遊ぶ' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"遊","r":"あそ"},{"t":"ぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 6, 'どころではない', 'どころではない', NULL, 10, 17, '[{"t":"どころではない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-2', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 0, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 2, '、', '、', NULL, 3, 4, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 3, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 4, 'どこ', 'どこ', NULL, 6, 8, '[{"t":"どこ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 5, 'ろ', 'ろ', NULL, 8, 9, '[{"t":"ろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 6, 'では', 'では', (select id from words where primary_form = 'では' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"では"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 7, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-3', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-4', 0, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-4', 2, 'なくて', 'なくて', NULL, 3, 6, '[{"t":"なくて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-4', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-4', 4, '買い物', 'かいもの', (select id from words where primary_form = '買い物' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"買","r":"か"},{"t":"い"},{"t":"物","r":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-4', 5, 'どころではない', 'どころではない', NULL, 10, 17, '[{"t":"どころではない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dokorodewanai-4', 6, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 1, 'ばかりか', 'ばかりか', NULL, 1, 5, '[{"t":"ばかりか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 3, '風', 'かぜ', (select id from words where primary_form = '風' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"風","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 4, 'も', 'も', NULL, 7, 8, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 5, '強', 'つよ', (select id from words where primary_form = '強' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"強","r":"つよ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 6, 'く', 'く', NULL, 9, 10, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 7, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-1', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 2, '英語', 'えいご', (select id from words where primary_form = '英語' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"英語","r":"えいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 3, 'ばかりか', 'ばかりか', NULL, 4, 8, '[{"t":"ばかりか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 5, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 6, 'も', 'も', NULL, 11, 12, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 7, '上手', 'じょうず', (select id from words where primary_form = '上手' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"上手","r":"じょうず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 8, 'だ', 'だ', NULL, 14, 15, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-2', 9, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 0, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 2, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 3, 'ばかりか', 'ばかりか', NULL, 5, 9, '[{"t":"ばかりか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 5, '味', 'あじ', (select id from words where primary_form = '味' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"味","r":"あじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 6, 'も', 'も', NULL, 11, 12, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 7, '悪い', 'わるい', (select id from words where primary_form = '難い' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"悪","r":"わる"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-3', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-4', 0, '遅れた', 'おくれた', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"遅","r":"おく"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-4', 1, 'ばかりか', 'ばかりか', NULL, 3, 7, '[{"t":"ばかりか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-4', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-4', 3, '連絡', 'れんらく', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"連絡","r":"れんらく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-4', 4, 'も', 'も', NULL, 10, 11, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-4', 5, 'しなかった', 'しなかった', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 11, 16, '[{"t":"しなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakarika-4', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-1', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-1', 2, '遅れた', 'おくれた', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"遅","r":"おく"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-1', 3, 'ものだから', 'ものだから', NULL, 6, 11, '[{"t":"ものだから"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-1', 4, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-1', 5, '遅刻しました', 'ちこくしました', (select id from words where primary_form = '遅刻' and language_id = 'lang-ja' and published order by id limit 1), 12, 18, '[{"t":"遅刻","r":"ちこく"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-1', 6, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-2', 0, '忙しかったものだから', 'いそがしかったものだから', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 10, '[{"t":"忙","r":"いそが"},{"t":"しかったものだから"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-2', 1, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-2', 2, '連絡', 'れんらく', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"連絡","r":"れんらく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-2', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-2', 4, 'き', 'き', NULL, 14, 15, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-2', 5, 'ませんでした', 'ませんでした', NULL, 15, 21, '[{"t":"ませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-2', 6, '。', '。', NULL, 21, 22, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-3', 0, '安かったものだから', 'やすかったものだから', (select id from words where primary_form = '安っぽい' and language_id = 'lang-ja' and published order by id limit 1), 0, 9, '[{"t":"安","r":"やす"},{"t":"かったものだから"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-3', 1, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-3', 2, '買って', 'かって', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"買","r":"か"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-3', 3, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-3', 4, 'ま', 'ま', NULL, 14, 15, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-3', 5, 'いました', 'いました', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 15, 19, '[{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-3', 6, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-4', 0, '頭', 'あたま', (select id from words where primary_form = '頭' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"頭","r":"あたま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-4', 2, '痛かったものだから', 'いたかったものだから', (select id from words where primary_form = '痛める' and language_id = 'lang-ja' and published order by id limit 1), 2, 11, '[{"t":"痛","r":"いた"},{"t":"かったものだから"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-4', 3, '、', '、', NULL, 11, 12, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-4', 4, '休みました', 'やすみました', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 12, 17, '[{"t":"休","r":"やす"},{"t":"みました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monodakara-4', 5, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-1', 0, 'よく', 'よく', NULL, 0, 2, '[{"t":"よく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-1', 1, '考えた', 'かんがえた', (select id from words where primary_form = '考える' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"考","r":"かんが"},{"t":"えた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-1', 2, '上で', 'うえで', NULL, 5, 7, '[{"t":"上","r":"うえ"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-1', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-1', 4, '決めます', 'きめます', (select id from words where primary_form = '決める' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"決","r":"き"},{"t":"めます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-2', 0, '相談した', 'そうだんした', (select id from words where primary_form = '相談' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"相談","r":"そうだん"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-2', 1, '上で', 'うえで', NULL, 4, 6, '[{"t":"上","r":"うえ"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-2', 3, '返事します', 'へんじします', (select id from words where primary_form = '返事' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"返事","r":"へんじ"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-2', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 0, '説明', 'せつめい', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"説明","r":"せつめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 2, '聞いた', 'きいた', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"聞","r":"き"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 3, '上で', 'うえで', NULL, 6, 8, '[{"t":"上","r":"うえ"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 5, '質問して', 'しつもんして', (select id from words where primary_form = '質問' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"質問","r":"しつもん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-3', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-4', 0, '調査', 'ちょうさ', (select id from words where primary_form = '調査' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"調査","r":"ちょうさ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-4', 2, '上で', 'うえで', NULL, 3, 5, '[{"t":"上","r":"うえ"},{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-4', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-4', 4, '報告します', 'ほうこくします', (select id from words where primary_form = '報告' and language_id = 'lang-ja' and published order by id limit 1), 6, 11, '[{"t":"報告","r":"ほうこく"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-uede-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-1', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-1', 1, '上に', 'うえに', NULL, 2, 4, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-1', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-1', 3, '美味しい', 'おいしい', (select id from words where primary_form = '美味しい' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"美味","r":"おい"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-2', 2, '優しい', 'やさしい', (select id from words where primary_form = '優しい' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"優","r":"やさ"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-2', 3, '上に', 'うえに', NULL, 5, 7, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-2', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-2', 5, '面白い', 'おもしろい', (select id from words where primary_form = '面白い' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"面白","r":"おもしろ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-2', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 2, '降った', 'ふった', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"降","r":"ふ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 3, '上に', 'うえに', NULL, 5, 7, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 5, '風', 'かぜ', (select id from words where primary_form = '風' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"風","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 6, 'も', 'も', NULL, 9, 10, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 7, '強', 'つよ', (select id from words where primary_form = '強' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"強","r":"つよ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 8, 'かった', 'かった', NULL, 11, 14, '[{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-3', 9, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 0, '道', 'みち', (select id from words where primary_form = '道' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"道","r":"みち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 2, '迷った', 'まよった', (select id from words where primary_form = '迷う' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"迷","r":"まよ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 3, '上に', 'うえに', NULL, 5, 7, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 5, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 6, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 7, '降られた', 'ふられた', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"降","r":"ふ"},{"t":"られた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ueni-4', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-1', 0, '長い', 'ながい', (select id from words where primary_form = '長い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"長","r":"なが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-1', 1, '間', 'あいだ', (select id from words where primary_form = '間' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"間","r":"あいだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-1', 2, '考えた', 'かんがえた', (select id from words where primary_form = '考える' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"考","r":"かんが"},{"t":"えた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-1', 3, '末に', 'すえに', NULL, 6, 8, '[{"t":"末","r":"すえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-1', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-1', 5, '決めました', 'きめました', (select id from words where primary_form = '決める' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"決","r":"き"},{"t":"めました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 0, '相談した', 'そうだんした', (select id from words where primary_form = '相談' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"相談","r":"そうだん"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 1, '末に', 'すえに', NULL, 4, 6, '[{"t":"末","r":"すえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 3, '中止する', 'ちゅうしする', (select id from words where primary_form = '中止' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"中止","r":"ちゅうし"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 4, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 6, 'した', 'した', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-2', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-3', 0, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-3', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-3', 2, '末に', 'すえに', NULL, 3, 5, '[{"t":"末","r":"すえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-3', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-3', 4, '成功しました', 'せいこうしました', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"成功","r":"せいこう"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-3', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 0, '議論', 'ぎろん', (select id from words where primary_form = '議論' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"議論","r":"ぎろん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 2, '末に', 'すえに', NULL, 3, 5, '[{"t":"末","r":"すえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 4, '結論', 'けつろん', (select id from words where primary_form = '結論' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"結論","r":"けつろん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 5, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 6, '出ました', 'でました', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"出","r":"で"},{"t":"ました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sueni-4', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-1', 0, '長く', 'ながく', (select id from words where primary_form = '常しえ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"長","r":"なが"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-1', 1, '待った', 'まった', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"待","r":"ま"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-1', 2, 'あげく', 'あげく', NULL, 5, 8, '[{"t":"あげく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-1', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-1', 4, '断られた', 'ことわられた', (select id from words where primary_form = '断る' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"断","r":"ことわ"},{"t":"られた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-1', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-2', 0, '議論した', 'ぎろんした', (select id from words where primary_form = '議論' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"議論","r":"ぎろん"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-2', 1, 'あげく', 'あげく', NULL, 4, 7, '[{"t":"あげく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-2', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-2', 3, '決まらなかった', 'きまらなかった', (select id from words where primary_form = '決まる' and language_id = 'lang-ja' and published order by id limit 1), 8, 15, '[{"t":"決","r":"き"},{"t":"まらなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-2', 4, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-3', 0, '迷った', 'まよった', (select id from words where primary_form = '迷う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"迷","r":"まよ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-3', 1, 'あげく', 'あげく', NULL, 3, 6, '[{"t":"あげく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-3', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-3', 3, '買いませんでした', 'かいませんでした', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 7, 15, '[{"t":"買","r":"か"},{"t":"いませんでした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-3', 4, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 0, '長く', 'ながく', (select id from words where primary_form = '常しえ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"長","r":"なが"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 1, '働いた', 'はたらいた', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"働","r":"はたら"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 2, 'あげく', 'あげく', NULL, 5, 8, '[{"t":"あげく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 4, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 6, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-ageku-4', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 0, '買い物', 'かいもの', (select id from words where primary_form = '買い物' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"買","r":"か"},{"t":"い"},{"t":"物","r":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 1, 'の', 'の', NULL, 3, 4, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 2, 'ついでに', 'ついでに', NULL, 4, 8, '[{"t":"ついでに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 4, '銀行', 'ぎんこう', (select id from words where primary_form = '銀行' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"銀行","r":"ぎんこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 5, 'へ', 'へ', NULL, 11, 12, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 6, '行った', 'いった', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"行","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-1', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 0, '駅', 'えき', (select id from words where primary_form = '駅' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"駅","r":"えき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 1, 'へ', 'へ', NULL, 1, 2, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 2, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 3, 'ついでに', 'ついでに', NULL, 4, 8, '[{"t":"ついでに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 5, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 6, 'を', 'を', NULL, 11, 12, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 7, '出します', 'だします', (select id from words where primary_form = '出す' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"出","r":"だ"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-2', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 0, '掃除', 'そうじ', (select id from words where primary_form = '掃除' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"掃除","r":"そうじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 2, 'ついでに', 'ついでに', NULL, 3, 7, '[{"t":"ついでに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 4, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 5, 'を', 'を', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 6, '片付けた', 'かたづけた', (select id from words where primary_form = '片付ける' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"片付","r":"かたづ"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-3', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 0, '散歩', 'さんぽ', (select id from words where primary_form = '散歩' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"散歩","r":"さんぽ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 2, 'ついでに', 'ついでに', NULL, 3, 7, '[{"t":"ついでに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 4, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 5, 'を', 'を', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 6, '撮った', 'とった', (select id from words where primary_form = '撮る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"撮","r":"と"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsuideni-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-1', 0, '宿題', 'しゅくだい', (select id from words where primary_form = '宿題' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"宿題","r":"しゅくだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-1', 1, 'やら', 'やら', NULL, 2, 4, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-1', 2, '準備', 'じゅんび', (select id from words where primary_form = '準備' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"準備","r":"じゅんび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-1', 3, 'やら', 'やら', NULL, 6, 8, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-1', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-1', 5, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 1, 'やら', 'やら', NULL, 1, 3, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 2, '風', 'かぜ', (select id from words where primary_form = '風' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"風","r":"かぜ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 3, 'やら', 'やら', NULL, 4, 6, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 5, '大変', 'たいへん', (select id from words where primary_form = '大変' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"大変","r":"たいへん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 6, 'だった', 'だった', NULL, 9, 12, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-2', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 1, 'やら', 'やら', NULL, 1, 3, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 2, 'ノート', 'ノート', (select id from words where primary_form = 'ノート' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"ノート"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 3, 'やら', 'やら', NULL, 6, 8, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 5, '置いて', 'おいて', (select id from words where primary_form = '置く' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"置","r":"お"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 6, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-3', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 0, '泣く', 'なく', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"泣","r":"な"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 1, 'やら', 'やら', NULL, 2, 4, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 2, '笑う', 'わらう', (select id from words where primary_form = '笑う' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"笑","r":"わら"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 3, 'やら', 'やら', NULL, 6, 8, '[{"t":"やら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 5, '大変', 'たいへん', (select id from words where primary_form = '大変' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"大変","r":"たいへん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 6, 'だった', 'だった', NULL, 11, 14, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yara-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb);
