-- N2 example sentences, batch 5: cannot, will not, and formal occasions.
--
-- 〜ようにも〜ない is the wish blocked by circumstance; 〜もしない and
-- 〜てばかりいる are complaints about somebody else. 〜てたまらない,
-- 〜てしかたがない and 〜ずにはいられない are three degrees of not being able
-- to help it, and they sit together so the difference in strength is visible.
-- 〜てはならない prohibits. Then に当たって, に際して and を始め, which belong
-- to speeches and notices rather than conversation.
--
-- One rewording: をはじめ in kana shreds to を|は|じ|め. 始める is published,
-- so all four sentences use を始め — the same phrase in the spelling the index
-- can see, and the one a formal notice would use anyway.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- you-ni-mo
  ('sent-ex-younimo-1', 'lang-ja', '行こうにも、時間がない。', 'いこう に も、じかん が ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-younimo-2', 'lang-ja', '寝ようにも、眠れない。', 'ねよう に も、ねむれない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-younimo-3', 'lang-ja', '買おうにも、お金がない。', 'かおう に も、おかね が ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-younimo-4', 'lang-ja', '連絡しようにも、電話がない。', 'れんらく しよう に も、でんわ が ない。', 'lvl-ja-n2', 'authored', true),
  -- mo-shinai
  ('sent-ex-moshinai-1', 'lang-ja', '彼は謝りもしない。', 'かれ わ あやまり も しない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-moshinai-2', 'lang-ja', '話を聞きもしないで、怒った。', 'はなし お きき も しないで、おこった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-moshinai-3', 'lang-ja', '彼は手伝いもしない。', 'かれ わ てつだい も しない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-moshinai-4', 'lang-ja', '考えもしなかった。', 'かんがえ も しなかった。', 'lvl-ja-n2', 'authored', true),
  -- te-bakari-iru
  ('sent-ex-tebakariiru-1', 'lang-ja', '弟は遊んでばかりいる。', 'おとうと わ あそんで ばかり いる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tebakariiru-2', 'lang-ja', '彼は寝てばかりいる。', 'かれ わ ねて ばかり いる。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tebakariiru-3', 'lang-ja', '泣いてばかりいないで、話してください。', 'ないて ばかり いないで、はなして ください。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tebakariiru-4', 'lang-ja', 'テレビを見てばかりいる。', 'テレビ お みて ばかり いる。', 'lvl-ja-n2', 'authored', true),
  -- te-tamaranai
  ('sent-ex-tetamaranai-1', 'lang-ja', '暑くてたまらない。', 'あつくて たまらない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tetamaranai-2', 'lang-ja', '会いたくてたまらない。', 'あいたくて たまらない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tetamaranai-3', 'lang-ja', '眠くてたまらない。', 'ねむくて たまらない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tetamaranai-4', 'lang-ja', '嬉しくてたまらない。', 'うれしくて たまらない。', 'lvl-ja-n2', 'authored', true),
  -- te-shikata-ga-nai
  ('sent-ex-shikataganai-1', 'lang-ja', '寒くてしかたがない。', 'さむくて しかた が ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-shikataganai-2', 'lang-ja', '痛くてしかたがない。', 'いたくて しかた が ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-shikataganai-3', 'lang-ja', '疲れてしかたがない。', 'つかれて しかた が ない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-shikataganai-4', 'lang-ja', '忙しくてしかたがない。', 'いそがしくて しかた が ない。', 'lvl-ja-n2', 'authored', true),
  -- zu-ni-wa-irarenai
  ('sent-ex-zuniwairarenai-1', 'lang-ja', '笑わずにはいられない。', 'わらわず に わ いられない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-zuniwairarenai-2', 'lang-ja', '泣かずにはいられなかった。', 'なかず に わ いられなかった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-zuniwairarenai-3', 'lang-ja', '言わずにはいられない。', 'いわず に わ いられない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-zuniwairarenai-4', 'lang-ja', '買わずにはいられなかった。', 'かわず に わ いられなかった。', 'lvl-ja-n2', 'authored', true),
  -- te-wa-naranai
  ('sent-ex-tewanaranai-1', 'lang-ja', '約束を忘れてはならない。', 'やくそく お わすれて わ ならない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tewanaranai-2', 'lang-ja', '川で泳いではならない。', 'かわ で およいで わ ならない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tewanaranai-3', 'lang-ja', '規則を破ってはならない。', 'きそく お やぶって わ ならない。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-tewanaranai-4', 'lang-ja', '諦めてはならない。', 'あきらめて わ ならない。', 'lvl-ja-n2', 'authored', true),
  -- ni-atatte
  ('sent-ex-niatatte-1', 'lang-ja', '出発に当たって、注意することがあります。', 'しゅっぱつ に あたって、ちゅうい する こと が あります。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-niatatte-2', 'lang-ja', '始めるに当たって、準備が必要です。', 'はじめる に あたって、じゅんび が ひつよう です。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-niatatte-3', 'lang-ja', '入学に当たって、書類を出します。', 'にゅうがく に あたって、しょるい お だします。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-niatatte-4', 'lang-ja', '新しい仕事を始めるに当たって、相談しました。', 'あたらしい しごと お はじめる に あたって、そうだん しました。', 'lvl-ja-n2', 'authored', true),
  -- ni-saishite
  ('sent-ex-nisaishite-1', 'lang-ja', '卒業に際して、先生に感謝します。', 'そつぎょう に さいして、せんせい に かんしゃ します。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisaishite-2', 'lang-ja', '出発に際して、挨拶をしました。', 'しゅっぱつ に さいして、あいさつ お しました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisaishite-3', 'lang-ja', '試験に際して、注意を読んでください。', 'しけん に さいして、ちゅうい お よんで ください。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-nisaishite-4', 'lang-ja', '利用に際して、規則を守ってください。', 'りよう に さいして、きそく お まもって ください。', 'lvl-ja-n2', 'authored', true),
  -- wo-hajime
  ('sent-ex-wohajime-1', 'lang-ja', '先生を始め、学生も集まった。', 'せんせい お はじめ、がくせい も あつまった。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wohajime-2', 'lang-ja', '日本を始め、多くの国で人気があります。', 'にほん お はじめ、おおく の くに で にんき が あります。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wohajime-3', 'lang-ja', '両親を始め、家族が応援しました。', 'りょうしん お はじめ、かぞく が おうえん しました。', 'lvl-ja-n2', 'authored', true),
  ('sent-ex-wohajime-4', 'lang-ja', '社長を始め、多くの人が参加しました。', 'しゃちょう お はじめ、おおく の ひと が さんか しました。', 'lvl-ja-n2', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-younimo-1', 'sent-ex-younimo-1', 'en', 'Even if I wanted to go, I have no time.', 'authored'),
  ('st-ex-younimo-2', 'sent-ex-younimo-2', 'en', 'Try as I might to sleep, I cannot.', 'authored'),
  ('st-ex-younimo-3', 'sent-ex-younimo-3', 'en', 'Even if I wanted to buy it, I have no money.', 'authored'),
  ('st-ex-younimo-4', 'sent-ex-younimo-4', 'en', 'Even if I wanted to get in touch, there is no telephone.', 'authored'),
  ('st-ex-moshinai-1', 'sent-ex-moshinai-1', 'en', 'He will not so much as apologise.', 'authored'),
  ('st-ex-moshinai-2', 'sent-ex-moshinai-2', 'en', 'He got angry without even listening.', 'authored'),
  ('st-ex-moshinai-3', 'sent-ex-moshinai-3', 'en', 'He will not so much as lend a hand.', 'authored'),
  ('st-ex-moshinai-4', 'sent-ex-moshinai-4', 'en', 'It never even crossed my mind.', 'authored'),
  ('st-ex-tebakariiru-1', 'sent-ex-tebakariiru-1', 'en', 'My little brother does nothing but play.', 'authored'),
  ('st-ex-tebakariiru-2', 'sent-ex-tebakariiru-2', 'en', 'He does nothing but sleep.', 'authored'),
  ('st-ex-tebakariiru-3', 'sent-ex-tebakariiru-3', 'en', 'Stop crying and talk to me.', 'authored'),
  ('st-ex-tebakariiru-4', 'sent-ex-tebakariiru-4', 'en', 'He does nothing but watch television.', 'authored'),
  ('st-ex-tetamaranai-1', 'sent-ex-tetamaranai-1', 'en', 'It is unbearably hot.', 'authored'),
  ('st-ex-tetamaranai-2', 'sent-ex-tetamaranai-2', 'en', 'I want to see her so much I cannot bear it.', 'authored'),
  ('st-ex-tetamaranai-3', 'sent-ex-tetamaranai-3', 'en', 'I am so sleepy I cannot stand it.', 'authored'),
  ('st-ex-tetamaranai-4', 'sent-ex-tetamaranai-4', 'en', 'I am so happy I cannot contain myself.', 'authored'),
  ('st-ex-shikataganai-1', 'sent-ex-shikataganai-1', 'en', 'I am dreadfully cold.', 'authored'),
  ('st-ex-shikataganai-2', 'sent-ex-shikataganai-2', 'en', 'It hurts terribly.', 'authored'),
  ('st-ex-shikataganai-3', 'sent-ex-shikataganai-3', 'en', 'I am dreadfully tired.', 'authored'),
  ('st-ex-shikataganai-4', 'sent-ex-shikataganai-4', 'en', 'I am impossibly busy.', 'authored'),
  ('st-ex-zuniwairarenai-1', 'sent-ex-zuniwairarenai-1', 'en', 'I cannot help laughing.', 'authored'),
  ('st-ex-zuniwairarenai-2', 'sent-ex-zuniwairarenai-2', 'en', 'I could not help crying.', 'authored'),
  ('st-ex-zuniwairarenai-3', 'sent-ex-zuniwairarenai-3', 'en', 'I cannot keep it to myself.', 'authored'),
  ('st-ex-zuniwairarenai-4', 'sent-ex-zuniwairarenai-4', 'en', 'I could not stop myself buying it.', 'authored'),
  ('st-ex-tewanaranai-1', 'sent-ex-tewanaranai-1', 'en', 'A promise must not be forgotten.', 'authored'),
  ('st-ex-tewanaranai-2', 'sent-ex-tewanaranai-2', 'en', 'You must not swim in the river.', 'authored'),
  ('st-ex-tewanaranai-3', 'sent-ex-tewanaranai-3', 'en', 'The rules must not be broken.', 'authored'),
  ('st-ex-tewanaranai-4', 'sent-ex-tewanaranai-4', 'en', 'You must not give up.', 'authored'),
  ('st-ex-niatatte-1', 'sent-ex-niatatte-1', 'en', 'On setting out, there are some things to be careful of.', 'authored'),
  ('st-ex-niatatte-2', 'sent-ex-niatatte-2', 'en', 'On starting, preparation is needed.', 'authored'),
  ('st-ex-niatatte-3', 'sent-ex-niatatte-3', 'en', 'On entering the school, I hand in the paperwork.', 'authored'),
  ('st-ex-niatatte-4', 'sent-ex-niatatte-4', 'en', 'On starting the new job, I talked it over first.', 'authored'),
  ('st-ex-nisaishite-1', 'sent-ex-nisaishite-1', 'en', 'On graduating, I thank my teachers.', 'authored'),
  ('st-ex-nisaishite-2', 'sent-ex-nisaishite-2', 'en', 'On departing, I said my goodbyes.', 'authored'),
  ('st-ex-nisaishite-3', 'sent-ex-nisaishite-3', 'en', 'For the exam, please read the notes.', 'authored'),
  ('st-ex-nisaishite-4', 'sent-ex-nisaishite-4', 'en', 'On using it, please observe the rules.', 'authored'),
  ('st-ex-wohajime-1', 'sent-ex-wohajime-1', 'en', 'The teachers and the students too all gathered.', 'authored'),
  ('st-ex-wohajime-2', 'sent-ex-wohajime-2', 'en', 'It is popular in many countries, Japan among them.', 'authored'),
  ('st-ex-wohajime-3', 'sent-ex-wohajime-3', 'en', 'My parents and the rest of the family cheered me on.', 'authored'),
  ('st-ex-wohajime-4', 'sent-ex-wohajime-4', 'en', 'The company president and many others took part.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('you-ni-mo', 'sent-ex-younimo-1', 0),
  ('you-ni-mo', 'sent-ex-younimo-2', 1),
  ('you-ni-mo', 'sent-ex-younimo-3', 2),
  ('you-ni-mo', 'sent-ex-younimo-4', 3),
  ('mo-shinai', 'sent-ex-moshinai-1', 0),
  ('mo-shinai', 'sent-ex-moshinai-2', 1),
  ('mo-shinai', 'sent-ex-moshinai-3', 2),
  ('mo-shinai', 'sent-ex-moshinai-4', 3),
  ('te-bakari-iru', 'sent-ex-tebakariiru-1', 0),
  ('te-bakari-iru', 'sent-ex-tebakariiru-2', 1),
  ('te-bakari-iru', 'sent-ex-tebakariiru-3', 2),
  ('te-bakari-iru', 'sent-ex-tebakariiru-4', 3),
  ('te-tamaranai', 'sent-ex-tetamaranai-1', 0),
  ('te-tamaranai', 'sent-ex-tetamaranai-2', 1),
  ('te-tamaranai', 'sent-ex-tetamaranai-3', 2),
  ('te-tamaranai', 'sent-ex-tetamaranai-4', 3),
  ('te-shikata-ga-nai', 'sent-ex-shikataganai-1', 0),
  ('te-shikata-ga-nai', 'sent-ex-shikataganai-2', 1),
  ('te-shikata-ga-nai', 'sent-ex-shikataganai-3', 2),
  ('te-shikata-ga-nai', 'sent-ex-shikataganai-4', 3),
  ('zu-ni-wa-irarenai', 'sent-ex-zuniwairarenai-1', 0),
  ('zu-ni-wa-irarenai', 'sent-ex-zuniwairarenai-2', 1),
  ('zu-ni-wa-irarenai', 'sent-ex-zuniwairarenai-3', 2),
  ('zu-ni-wa-irarenai', 'sent-ex-zuniwairarenai-4', 3),
  ('te-wa-naranai', 'sent-ex-tewanaranai-1', 0),
  ('te-wa-naranai', 'sent-ex-tewanaranai-2', 1),
  ('te-wa-naranai', 'sent-ex-tewanaranai-3', 2),
  ('te-wa-naranai', 'sent-ex-tewanaranai-4', 3),
  ('ni-atatte', 'sent-ex-niatatte-1', 0),
  ('ni-atatte', 'sent-ex-niatatte-2', 1),
  ('ni-atatte', 'sent-ex-niatatte-3', 2),
  ('ni-atatte', 'sent-ex-niatatte-4', 3),
  ('ni-saishite', 'sent-ex-nisaishite-1', 0),
  ('ni-saishite', 'sent-ex-nisaishite-2', 1),
  ('ni-saishite', 'sent-ex-nisaishite-3', 2),
  ('ni-saishite', 'sent-ex-nisaishite-4', 3),
  ('wo-hajime', 'sent-ex-wohajime-1', 0),
  ('wo-hajime', 'sent-ex-wohajime-2', 1),
  ('wo-hajime', 'sent-ex-wohajime-3', 2),
  ('wo-hajime', 'sent-ex-wohajime-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-younimo-1', 'sent-ex-younimo-2', 'sent-ex-younimo-3', 'sent-ex-younimo-4', 'sent-ex-moshinai-1', 'sent-ex-moshinai-2', 'sent-ex-moshinai-3', 'sent-ex-moshinai-4', 'sent-ex-tebakariiru-1', 'sent-ex-tebakariiru-2', 'sent-ex-tebakariiru-3', 'sent-ex-tebakariiru-4', 'sent-ex-tetamaranai-1', 'sent-ex-tetamaranai-2', 'sent-ex-tetamaranai-3', 'sent-ex-tetamaranai-4', 'sent-ex-shikataganai-1', 'sent-ex-shikataganai-2', 'sent-ex-shikataganai-3', 'sent-ex-shikataganai-4', 'sent-ex-zuniwairarenai-1', 'sent-ex-zuniwairarenai-2', 'sent-ex-zuniwairarenai-3', 'sent-ex-zuniwairarenai-4', 'sent-ex-tewanaranai-1', 'sent-ex-tewanaranai-2', 'sent-ex-tewanaranai-3', 'sent-ex-tewanaranai-4', 'sent-ex-niatatte-1', 'sent-ex-niatatte-2', 'sent-ex-niatatte-3', 'sent-ex-niatatte-4', 'sent-ex-nisaishite-1', 'sent-ex-nisaishite-2', 'sent-ex-nisaishite-3', 'sent-ex-nisaishite-4', 'sent-ex-wohajime-1', 'sent-ex-wohajime-2', 'sent-ex-wohajime-3', 'sent-ex-wohajime-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-younimo-1', 0, '行こう', 'いこう', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"行","r":"い"},{"t":"こう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-1', 1, 'にも', 'にも', NULL, 3, 5, '[{"t":"にも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-1', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-1', 3, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-1', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-1', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-2', 0, '寝よう', 'ねよう', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"寝","r":"ね"},{"t":"よう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-2', 1, 'にも', 'にも', NULL, 3, 5, '[{"t":"にも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-2', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-2', 3, '眠れ', 'ねむれ', (select id from words where primary_form = '眠る' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"眠","r":"ねむ"},{"t":"れ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-2', 4, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-2', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-3', 0, '買おう', 'かおう', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"買","r":"か"},{"t":"おう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-3', 1, 'にも', 'にも', NULL, 3, 5, '[{"t":"にも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-3', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-3', 3, 'お金', 'おかね', (select id from words where primary_form = 'お金' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"お"},{"t":"金","r":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-3', 4, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-3', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-4', 0, '連絡しよう', 'れんらくしよう', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"連絡","r":"れんらく"},{"t":"しよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-4', 1, 'にも', 'にも', NULL, 5, 7, '[{"t":"にも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-4', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-4', 3, '電話', 'でんわ', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-4', 4, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-4', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-younimo-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-1', 2, '謝りもしない', 'あやまりもしない', (select id from words where primary_form = '謝る' and language_id = 'lang-ja' and published order by id limit 1), 2, 8, '[{"t":"謝","r":"あやま"},{"t":"りもしない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-2', 0, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-2', 2, '聞きもしないで', 'ききもしないで', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 2, 9, '[{"t":"聞","r":"き"},{"t":"きもしないで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-2', 3, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-2', 4, '怒った', 'おこった', (select id from words where primary_form = '怒る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"怒","r":"おこ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-2', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-3', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-3', 2, '手伝い', 'てつだい', (select id from words where primary_form = '手伝い' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"手伝","r":"てつだ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-3', 3, 'も', 'も', NULL, 5, 6, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-3', 4, 'しない', 'しない', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"しない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-3', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-4', 0, '考え', 'かんがえ', (select id from words where primary_form = '考え' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"考","r":"かんが"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-4', 1, 'も', 'も', NULL, 2, 3, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-4', 2, 'しなかった', 'しなかった', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"しなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-moshinai-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-1', 0, '弟', 'おとうと', (select id from words where primary_form = '弟' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"弟","r":"おとうと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-1', 2, '遊んで', 'あそんで', (select id from words where primary_form = '遊ぶ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"遊","r":"あそ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-1', 3, 'ばかりいる', 'ばかりいる', NULL, 5, 10, '[{"t":"ばかりいる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-1', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-2', 2, '寝て', 'ねて', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"寝","r":"ね"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-2', 3, 'ばかりいる', 'ばかりいる', NULL, 4, 9, '[{"t":"ばかりいる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 0, '泣いて', 'ないて', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"泣","r":"な"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 1, 'ばかり', 'ばかり', NULL, 3, 6, '[{"t":"ばかり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 2, 'いない', 'いない', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"いない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 4, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 5, '話して', 'はなして', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"話","r":"はな"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-3', 7, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-4', 0, 'テレビ', 'テレビ', (select id from words where primary_form = 'テレビ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"テレビ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-4', 1, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-4', 2, '見て', 'みて', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"見","r":"み"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-4', 3, 'ばかりいる', 'ばかりいる', NULL, 6, 11, '[{"t":"ばかりいる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tebakariiru-4', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-1', 0, '暑くてたまらない', 'あつくてたまらない', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 0, 8, '[{"t":"暑","r":"あつ"},{"t":"くてたまらない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-1', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-2', 0, '会いたくてたまらない', 'あいたくてたまらない', (select id from words where primary_form = '会う' and language_id = 'lang-ja' and published order by id limit 1), 0, 10, '[{"t":"会","r":"あ"},{"t":"いたくてたまらない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-2', 1, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-3', 0, '眠くてたまらない', 'ねむくてたまらない', (select id from words where primary_form = '眠る' and language_id = 'lang-ja' and published order by id limit 1), 0, 8, '[{"t":"眠","r":"ねむ"},{"t":"くてたまらない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-3', 1, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-4', 0, '嬉しくてたまらない', 'うれしくてたまらない', (select id from words where primary_form = '嬉しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 9, '[{"t":"嬉","r":"うれ"},{"t":"しくてたまらない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tetamaranai-4', 1, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-1', 0, '寒くてしかたがない', 'さむくてしかたがない', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 0, 9, '[{"t":"寒","r":"さむ"},{"t":"くてしかたがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-1', 1, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-2', 0, '痛くてしかたがない', 'いたくてしかたがない', (select id from words where primary_form = '痛める' and language_id = 'lang-ja' and published order by id limit 1), 0, 9, '[{"t":"痛","r":"いた"},{"t":"くてしかたがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-2', 1, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-3', 0, '疲れて', 'つかれて', (select id from words where primary_form = '疲れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"疲","r":"つか"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-3', 1, 'しかたがない', 'しかたがない', NULL, 3, 9, '[{"t":"しかたがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-3', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-4', 0, '忙しくてしかたがない', 'いそがしくてしかたがない', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 10, '[{"t":"忙","r":"いそが"},{"t":"しくてしかたがない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shikataganai-4', 1, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-1', 0, '笑', 'わら', (select id from words where primary_form = '笑' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"笑","r":"わら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-1', 1, 'わ', 'わ', (select id from words where primary_form = 'わ' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"わ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-1', 2, 'ずにはいられない', 'ずにはいられない', NULL, 2, 10, '[{"t":"ずにはいられない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-1', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-2', 0, '泣かずにはいられなかった', 'なかずにはいられなかった', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 0, 12, '[{"t":"泣","r":"な"},{"t":"かずにはいられなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-2', 1, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-3', 0, '言わずにはいられない', 'いわずにはいられない', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 0, 10, '[{"t":"言","r":"い"},{"t":"わずにはいられない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-3', 1, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-4', 0, '買わずにはいられなかった', 'かわずにはいられなかった', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 0, 12, '[{"t":"買","r":"か"},{"t":"わずにはいられなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-zuniwairarenai-4', 1, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-1', 0, '約束', 'やくそく', (select id from words where primary_form = '約束' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"約束","r":"やくそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-1', 2, '忘れて', 'わすれて', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"忘","r":"わす"},{"t":"れて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-1', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-1', 4, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-2', 0, '川', 'かわ', (select id from words where primary_form = '川' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"川","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-2', 2, '泳いで', 'およいで', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"泳","r":"およ"},{"t":"いで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-2', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-2', 4, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-2', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-3', 0, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-3', 2, '破って', 'やぶって', (select id from words where primary_form = '破る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"破","r":"やぶ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-3', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-3', 4, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-3', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-4', 0, '諦めて', 'あきらめて', (select id from words where primary_form = '諦める' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"諦","r":"あきら"},{"t":"めて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-4', 2, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tewanaranai-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 0, '出発', 'しゅっぱつ', (select id from words where primary_form = '出発' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"出発","r":"しゅっぱつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 2, '当たって', 'あたって', (select id from words where primary_form = '当たる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"当","r":"あ"},{"t":"たって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 4, '注意する', 'ちゅういする', (select id from words where primary_form = '注意' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"注意","r":"ちゅうい"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 5, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 6, 'が', 'が', NULL, 14, 15, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 7, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 15, 19, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-1', 8, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 0, '始める', 'はじめる', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"始","r":"はじ"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 2, '当たって', 'あたって', (select id from words where primary_form = '当たる' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"当","r":"あ"},{"t":"たって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 4, '準備', 'じゅんび', (select id from words where primary_form = '準備' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"準備","r":"じゅんび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 5, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 6, '必要', 'ひつよう', (select id from words where primary_form = '必要' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"必要","r":"ひつよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 7, 'です', 'です', NULL, 14, 16, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-2', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 0, '入学', 'にゅうがく', (select id from words where primary_form = '入学' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"入学","r":"にゅうがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 2, '当たって', 'あたって', (select id from words where primary_form = '当たる' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"当","r":"あ"},{"t":"たって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 4, '書類', 'しょるい', (select id from words where primary_form = '書類' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"書類","r":"しょるい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 5, 'を', 'を', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 6, '出します', 'だします', (select id from words where primary_form = '出す' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"出","r":"だ"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-3', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 0, '新しい', 'あたらしい', (select id from words where primary_form = '新しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"新","r":"あたら"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 1, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 2, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 3, '始める', 'はじめる', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"始","r":"はじ"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 5, '当たって', 'あたって', (select id from words where primary_form = '当たる' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"当","r":"あ"},{"t":"たって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 6, '、', '、', NULL, 14, 15, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 7, '相談しました', 'そうだんしました', (select id from words where primary_form = '相談' and language_id = 'lang-ja' and published order by id limit 1), 15, 21, '[{"t":"相談","r":"そうだん"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niatatte-4', 8, '。', '。', NULL, 21, 22, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-1', 0, '卒業', 'そつぎょう', (select id from words where primary_form = '卒業' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"卒業","r":"そつぎょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-1', 1, 'に際して', 'にさいして', NULL, 2, 6, '[{"t":"に"},{"t":"際","r":"さい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-1', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-1', 3, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-1', 5, '感謝します', 'かんしゃします', (select id from words where primary_form = '感謝' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"感謝","r":"かんしゃ"},{"t":"します"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-1', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-2', 0, '出発', 'しゅっぱつ', (select id from words where primary_form = '出発' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"出発","r":"しゅっぱつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-2', 1, 'に際して', 'にさいして', NULL, 2, 6, '[{"t":"に"},{"t":"際","r":"さい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-2', 3, '挨拶', 'あいさつ', (select id from words where primary_form = '挨拶' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"挨拶","r":"あいさつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-2', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-2', 5, 'しました', 'しました', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 1, 'に際して', 'にさいして', NULL, 2, 6, '[{"t":"に"},{"t":"際","r":"さい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 3, '注意', 'ちゅうい', (select id from words where primary_form = '注意' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"注意","r":"ちゅうい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 5, '読んで', 'よんで', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"読","r":"よ"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-3', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 0, '利用', 'りよう', (select id from words where primary_form = '利用' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"利用","r":"りよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 1, 'に際して', 'にさいして', NULL, 2, 6, '[{"t":"に"},{"t":"際","r":"さい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 3, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 5, '守って', 'まもって', (select id from words where primary_form = '守る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"守","r":"まも"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 6, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nisaishite-4', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 2, '始め', 'はじめ', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"始","r":"はじ"},{"t":"め"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 4, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 5, 'も', 'も', NULL, 8, 9, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 6, '集まった', 'あつまった', (select id from words where primary_form = '集まる' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"集","r":"あつ"},{"t":"まった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-1', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 2, '始め', 'はじめ', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"始","r":"はじ"},{"t":"め"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 4, '多くの', 'おおくの', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"多","r":"おお"},{"t":"くの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 5, '国', 'くに', (select id from words where primary_form = '国' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"国","r":"くに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 6, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 7, '人気', 'にんき', (select id from words where primary_form = '人気' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"人気","r":"にんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 8, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 9, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-2', 10, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 0, '両親', 'りょうしん', (select id from words where primary_form = '両親' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"両親","r":"りょうしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 2, '始め', 'はじめ', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"始","r":"はじ"},{"t":"め"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 4, '家族', 'かぞく', (select id from words where primary_form = '家族' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"家族","r":"かぞく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 5, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 6, '応援しました', 'おうえんしました', (select id from words where primary_form = '応援' and language_id = 'lang-ja' and published order by id limit 1), 9, 15, '[{"t":"応援","r":"おうえん"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-3', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 0, '社長', 'しゃちょう', (select id from words where primary_form = '社長' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"社長","r":"しゃちょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 2, '始め', 'はじめ', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"始","r":"はじ"},{"t":"め"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 4, '多くの', 'おおくの', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"多","r":"おお"},{"t":"くの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 5, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 6, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 7, '参加しました', 'さんかしました', (select id from words where primary_form = '参加' and language_id = 'lang-ja' and published order by id limit 1), 11, 17, '[{"t":"参加","r":"さんか"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wohajime-4', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb);
