-- N1 example sentences, batch 1: the literary register opens.
--
-- N1 is where the grammar stops sounding like speech. なしには, たりとも,
-- といえども, とは, ものを, べく, べからず and ながらに belong to notices,
-- speeches and written argument; や否や and が早いか are the two ways to say
-- one thing happened the instant another did, and they are written back to
-- back so the difference — や否や is neutral, が早いか is abrupt — has
-- somewhere to show.
--
-- Nothing had to be reworded, which was not expected at this level.
--
-- One authoring note for the next batch: 〜ものを ends in the particle を, so
-- its spoken reading is 「もの お」 and not 「ものを」. The tokeniser accepts
-- either and only the first is what a learner would say.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- nashi-ni-wa
  ('sent-ex-nashiniwa-1', 'lang-ja', '努力なしには成功できない。', 'どりょく なし に わ せいこう できない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nashiniwa-2', 'lang-ja', '彼の協力なしにはできなかった。', 'かれ の きょうりょく なし に わ できなかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nashiniwa-3', 'lang-ja', '準備なしには始められません。', 'じゅんび なし に わ はじめられません。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nashiniwa-4', 'lang-ja', '資料なしには説明できない。', 'しりょう なし に わ せつめい できない。', 'lvl-ja-n1', 'authored', true),
  -- taritomo
  ('sent-ex-taritomo-1', 'lang-ja', '一日たりとも忘れない。', 'いちにち たりとも わすれない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-taritomo-2', 'lang-ja', '一人たりとも許さない。', 'ひとり たりとも ゆるさない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-taritomo-3', 'lang-ja', '一度たりとも遅れたことがない。', 'いちど たりとも おくれた こと が ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-taritomo-4', 'lang-ja', '一言たりとも聞き逃せない。', 'ひとこと たりとも ききのがせない。', 'lvl-ja-n1', 'authored', true),
  -- to-iedomo
  ('sent-ex-toiedomo-1', 'lang-ja', '子供といえども、責任はある。', 'こども と いえども、せきにん わ ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toiedomo-2', 'lang-ja', '医者といえども、間違いはある。', 'いしゃ と いえども、まちがい わ ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toiedomo-3', 'lang-ja', '忙しいといえども、休みは必要だ。', 'いそがしい と いえども、やすみ わ ひつよう だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toiedomo-4', 'lang-ja', '社長といえども、規則を破ってはならない。', 'しゃちょう と いえども、きそく お やぶって わ ならない。', 'lvl-ja-n1', 'authored', true),
  -- towa
  ('sent-ex-towa-1', 'lang-ja', '彼が来るとは思わなかった。', 'かれ が くる と わ おもわなかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-towa-2', 'lang-ja', '彼が失敗するとは驚いた。', 'かれ が しっぱい する と わ おどろいた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-towa-3', 'lang-ja', 'そんなに簡単だとは知らなかった。', 'そんなに かんたん だ と わ しらなかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-towa-4', 'lang-ja', '彼が社長だとは知らなかった。', 'かれ が しゃちょう だ と わ しらなかった。', 'lvl-ja-n1', 'authored', true),
  -- mono-wo
  ('sent-ex-monowo-1', 'lang-ja', '早く言えばよかったものを。', 'はやく いえば よかった もの お。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-monowo-2', 'lang-ja', '相談すれば助けたものを。', 'そうだん すれば たすけた もの お。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-monowo-3', 'lang-ja', '休めばよかったものを、働き続けた。', 'やすめば よかった もの お、はたらきつづけた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-monowo-4', 'lang-ja', '謝れば許したものを。', 'あやまれば ゆるした もの お。', 'lvl-ja-n1', 'authored', true),
  -- beku
  ('sent-ex-beku-1', 'lang-ja', '成功すべく努力しています。', 'せいこう すべく どりょく して います。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-beku-2', 'lang-ja', '試験に合格すべく勉強した。', 'しけん に ごうかく すべく べんきょう した。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-beku-3', 'lang-ja', '早く着くべく走った。', 'はやく つくべく はしった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-beku-4', 'lang-ja', '問題を解決すべく話し合った。', 'もんだい お かいけつ すべく はなしあった。', 'lvl-ja-n1', 'authored', true),
  -- bekarazu
  ('sent-ex-bekarazu-1', 'lang-ja', '中に入るべからず。', 'なか に はいるべからず。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-bekarazu-2', 'lang-ja', '写真を撮るべからず。', 'しゃしん お とるべからず。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-bekarazu-3', 'lang-ja', '約束を忘れるべからず。', 'やくそく お わすれるべからず。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-bekarazu-4', 'lang-ja', '川で泳ぐべからず。', 'かわ で およぐべからず。', 'lvl-ja-n1', 'authored', true),
  -- nagara-ni
  ('sent-ex-nagarani-1', 'lang-ja', '彼は涙ながらに話した。', 'かれ わ なみだ ながら に はなした。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nagarani-2', 'lang-ja', '生まれながらの才能だ。', 'うまれ ながら の さいのう だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nagarani-3', 'lang-ja', '昔ながらの方法で作ります。', 'むかし ながら の ほうほう で つくります。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nagarani-4', 'lang-ja', '彼女は涙ながらに謝った。', 'かのじょ わ なみだ ながら に あやまった。', 'lvl-ja-n1', 'authored', true),
  -- ya-ina-ya
  ('sent-ex-yainaya-1', 'lang-ja', '家に着くや否や、雨が降った。', 'いえ に つく や いな や、あめ が ふった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yainaya-2', 'lang-ja', '話を聞くや否や、走って行った。', 'はなし お きく や いな や、はしって いった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yainaya-3', 'lang-ja', '店に入るや否や、彼を見つけた。', 'みせ に はいる や いな や、かれ お みつけた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yainaya-4', 'lang-ja', '座るや否や、寝てしまいました。', 'すわる や いな や、ねて しまいました。', 'lvl-ja-n1', 'authored', true),
  -- ga-hayai-ka
  ('sent-ex-gahayaika-1', 'lang-ja', 'ベルが鳴るが早いか、教室を出た。', 'ベル が なる が はやい か、きょうしつ お でた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gahayaika-2', 'lang-ja', '彼は食べるが早いか、出て行った。', 'かれ わ たべる が はやい か、でて いった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gahayaika-3', 'lang-ja', '電話を切るが早いか、出かけた。', 'でんわ お きる が はやい か、でかけた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gahayaika-4', 'lang-ja', '話を聞くが早いか、走り出しました。', 'はなし お きく が はやい か、はしりだしました。', 'lvl-ja-n1', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-nashiniwa-1', 'sent-ex-nashiniwa-1', 'en', 'Without effort there can be no success.', 'authored'),
  ('st-ex-nashiniwa-2', 'sent-ex-nashiniwa-2', 'en', 'Without his help it could not have been done.', 'authored'),
  ('st-ex-nashiniwa-3', 'sent-ex-nashiniwa-3', 'en', 'It cannot be started without preparation.', 'authored'),
  ('st-ex-nashiniwa-4', 'sent-ex-nashiniwa-4', 'en', 'It cannot be explained without the material.', 'authored'),
  ('st-ex-taritomo-1', 'sent-ex-taritomo-1', 'en', 'I do not forget it for a single day.', 'authored'),
  ('st-ex-taritomo-2', 'sent-ex-taritomo-2', 'en', 'I will not let a single one of them off.', 'authored'),
  ('st-ex-taritomo-3', 'sent-ex-taritomo-3', 'en', 'I have not been late even once.', 'authored'),
  ('st-ex-taritomo-4', 'sent-ex-taritomo-4', 'en', 'I cannot afford to miss a single word.', 'authored'),
  ('st-ex-toiedomo-1', 'sent-ex-toiedomo-1', 'en', 'Child though he is, he has responsibilities.', 'authored'),
  ('st-ex-toiedomo-2', 'sent-ex-toiedomo-2', 'en', 'Even a doctor makes mistakes.', 'authored'),
  ('st-ex-toiedomo-3', 'sent-ex-toiedomo-3', 'en', 'Busy though I am, I need a day off.', 'authored'),
  ('st-ex-toiedomo-4', 'sent-ex-toiedomo-4', 'en', 'Even the company president must not break the rules.', 'authored'),
  ('st-ex-towa-1', 'sent-ex-towa-1', 'en', 'I never thought he would come.', 'authored'),
  ('st-ex-towa-2', 'sent-ex-towa-2', 'en', 'I was astonished that he should fail.', 'authored'),
  ('st-ex-towa-3', 'sent-ex-towa-3', 'en', 'I had no idea it was that simple.', 'authored'),
  ('st-ex-towa-4', 'sent-ex-towa-4', 'en', 'I had no idea he was the company president.', 'authored'),
  ('st-ex-monowo-1', 'sent-ex-monowo-1', 'en', 'If only you had said so sooner.', 'authored'),
  ('st-ex-monowo-2', 'sent-ex-monowo-2', 'en', 'If you had asked, I would have helped.', 'authored'),
  ('st-ex-monowo-3', 'sent-ex-monowo-3', 'en', 'You should have rested, and instead you worked on.', 'authored'),
  ('st-ex-monowo-4', 'sent-ex-monowo-4', 'en', 'If you had apologised, I would have forgiven you.', 'authored'),
  ('st-ex-beku-1', 'sent-ex-beku-1', 'en', 'I am working hard in order to succeed.', 'authored'),
  ('st-ex-beku-2', 'sent-ex-beku-2', 'en', 'I studied in order to pass the exam.', 'authored'),
  ('st-ex-beku-3', 'sent-ex-beku-3', 'en', 'I ran in order to get there quickly.', 'authored'),
  ('st-ex-beku-4', 'sent-ex-beku-4', 'en', 'We talked in order to solve the problem.', 'authored'),
  ('st-ex-bekarazu-1', 'sent-ex-bekarazu-1', 'en', 'Do not enter.', 'authored'),
  ('st-ex-bekarazu-2', 'sent-ex-bekarazu-2', 'en', 'No photography.', 'authored'),
  ('st-ex-bekarazu-3', 'sent-ex-bekarazu-3', 'en', 'A promise is not to be forgotten.', 'authored'),
  ('st-ex-bekarazu-4', 'sent-ex-bekarazu-4', 'en', 'No swimming in the river.', 'authored'),
  ('st-ex-nagarani-1', 'sent-ex-nagarani-1', 'en', 'He spoke in tears.', 'authored'),
  ('st-ex-nagarani-2', 'sent-ex-nagarani-2', 'en', 'It is a natural-born talent.', 'authored'),
  ('st-ex-nagarani-3', 'sent-ex-nagarani-3', 'en', 'We make it by the old method.', 'authored'),
  ('st-ex-nagarani-4', 'sent-ex-nagarani-4', 'en', 'She apologised in tears.', 'authored'),
  ('st-ex-yainaya-1', 'sent-ex-yainaya-1', 'en', 'No sooner had I got home than it rained.', 'authored'),
  ('st-ex-yainaya-2', 'sent-ex-yainaya-2', 'en', 'The moment he heard, he ran off.', 'authored'),
  ('st-ex-yainaya-3', 'sent-ex-yainaya-3', 'en', 'The moment I entered the shop, I spotted him.', 'authored'),
  ('st-ex-yainaya-4', 'sent-ex-yainaya-4', 'en', 'The moment I sat down, I fell asleep.', 'authored'),
  ('st-ex-gahayaika-1', 'sent-ex-gahayaika-1', 'en', 'The instant the bell rang, he was out of the classroom.', 'authored'),
  ('st-ex-gahayaika-2', 'sent-ex-gahayaika-2', 'en', 'He ate and was out of the door in the same breath.', 'authored'),
  ('st-ex-gahayaika-3', 'sent-ex-gahayaika-3', 'en', 'He hung up and went straight out.', 'authored'),
  ('st-ex-gahayaika-4', 'sent-ex-gahayaika-4', 'en', 'The moment he heard, he broke into a run.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('nashi-ni-wa', 'sent-ex-nashiniwa-1', 0),
  ('nashi-ni-wa', 'sent-ex-nashiniwa-2', 1),
  ('nashi-ni-wa', 'sent-ex-nashiniwa-3', 2),
  ('nashi-ni-wa', 'sent-ex-nashiniwa-4', 3),
  ('taritomo', 'sent-ex-taritomo-1', 0),
  ('taritomo', 'sent-ex-taritomo-2', 1),
  ('taritomo', 'sent-ex-taritomo-3', 2),
  ('taritomo', 'sent-ex-taritomo-4', 3),
  ('to-iedomo', 'sent-ex-toiedomo-1', 0),
  ('to-iedomo', 'sent-ex-toiedomo-2', 1),
  ('to-iedomo', 'sent-ex-toiedomo-3', 2),
  ('to-iedomo', 'sent-ex-toiedomo-4', 3),
  ('towa', 'sent-ex-towa-1', 0),
  ('towa', 'sent-ex-towa-2', 1),
  ('towa', 'sent-ex-towa-3', 2),
  ('towa', 'sent-ex-towa-4', 3),
  ('mono-wo', 'sent-ex-monowo-1', 0),
  ('mono-wo', 'sent-ex-monowo-2', 1),
  ('mono-wo', 'sent-ex-monowo-3', 2),
  ('mono-wo', 'sent-ex-monowo-4', 3),
  ('beku', 'sent-ex-beku-1', 0),
  ('beku', 'sent-ex-beku-2', 1),
  ('beku', 'sent-ex-beku-3', 2),
  ('beku', 'sent-ex-beku-4', 3),
  ('bekarazu', 'sent-ex-bekarazu-1', 0),
  ('bekarazu', 'sent-ex-bekarazu-2', 1),
  ('bekarazu', 'sent-ex-bekarazu-3', 2),
  ('bekarazu', 'sent-ex-bekarazu-4', 3),
  ('nagara-ni', 'sent-ex-nagarani-1', 0),
  ('nagara-ni', 'sent-ex-nagarani-2', 1),
  ('nagara-ni', 'sent-ex-nagarani-3', 2),
  ('nagara-ni', 'sent-ex-nagarani-4', 3),
  ('ya-ina-ya', 'sent-ex-yainaya-1', 0),
  ('ya-ina-ya', 'sent-ex-yainaya-2', 1),
  ('ya-ina-ya', 'sent-ex-yainaya-3', 2),
  ('ya-ina-ya', 'sent-ex-yainaya-4', 3),
  ('ga-hayai-ka', 'sent-ex-gahayaika-1', 0),
  ('ga-hayai-ka', 'sent-ex-gahayaika-2', 1),
  ('ga-hayai-ka', 'sent-ex-gahayaika-3', 2),
  ('ga-hayai-ka', 'sent-ex-gahayaika-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-nashiniwa-1', 'sent-ex-nashiniwa-2', 'sent-ex-nashiniwa-3', 'sent-ex-nashiniwa-4', 'sent-ex-taritomo-1', 'sent-ex-taritomo-2', 'sent-ex-taritomo-3', 'sent-ex-taritomo-4', 'sent-ex-toiedomo-1', 'sent-ex-toiedomo-2', 'sent-ex-toiedomo-3', 'sent-ex-toiedomo-4', 'sent-ex-towa-1', 'sent-ex-towa-2', 'sent-ex-towa-3', 'sent-ex-towa-4', 'sent-ex-monowo-1', 'sent-ex-monowo-2', 'sent-ex-monowo-3', 'sent-ex-monowo-4', 'sent-ex-beku-1', 'sent-ex-beku-2', 'sent-ex-beku-3', 'sent-ex-beku-4', 'sent-ex-bekarazu-1', 'sent-ex-bekarazu-2', 'sent-ex-bekarazu-3', 'sent-ex-bekarazu-4', 'sent-ex-nagarani-1', 'sent-ex-nagarani-2', 'sent-ex-nagarani-3', 'sent-ex-nagarani-4', 'sent-ex-yainaya-1', 'sent-ex-yainaya-2', 'sent-ex-yainaya-3', 'sent-ex-yainaya-4', 'sent-ex-gahayaika-1', 'sent-ex-gahayaika-2', 'sent-ex-gahayaika-3', 'sent-ex-gahayaika-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-1', 0, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-1', 1, 'なしには', 'なしには', NULL, 2, 6, '[{"t":"なしには"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-1', 2, '成功', 'せいこう', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"成功","r":"せいこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-1', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-1', 4, 'き', 'き', NULL, 9, 10, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-1', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-2', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-2', 1, '協力', 'きょうりょく', (select id from words where primary_form = '協力' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"協力","r":"きょうりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-2', 2, 'なしには', 'なしには', NULL, 4, 8, '[{"t":"なしには"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-2', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-2', 4, 'き', 'き', NULL, 9, 10, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-2', 5, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-3', 0, '準備', 'じゅんび', (select id from words where primary_form = '準備' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"準備","r":"じゅんび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-3', 1, 'なしには', 'なしには', NULL, 2, 6, '[{"t":"なしには"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-3', 2, '始められません', 'はじめられません', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 6, 13, '[{"t":"始","r":"はじ"},{"t":"められません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-3', 3, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-4', 0, '資料', 'しりょう', (select id from words where primary_form = '資料' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"資料","r":"しりょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-4', 1, 'なしには', 'なしには', NULL, 2, 6, '[{"t":"なしには"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-4', 2, '説明', 'せつめい', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"説明","r":"せつめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-4', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-4', 4, 'き', 'き', NULL, 9, 10, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-4', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nashiniwa-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-1', 0, '一日', 'いちにち', (select id from words where primary_form = '一日' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一日","r":"いちにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-1', 1, 'たりとも', 'たりとも', NULL, 2, 6, '[{"t":"たりとも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-1', 2, '忘れない', 'わすれない', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"忘","r":"わす"},{"t":"れない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-1', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-2', 0, '一人', 'ひとり', (select id from words where primary_form = '一人' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一人","r":"ひとり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-2', 1, 'たりとも', 'たりとも', NULL, 2, 6, '[{"t":"たりとも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-2', 2, '許さない', 'ゆるさない', (select id from words where primary_form = '許す' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"許","r":"ゆる"},{"t":"さない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-2', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-3', 0, '一度', 'いちど', (select id from words where primary_form = '一度' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一度","r":"いちど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-3', 1, 'たりとも', 'たりとも', NULL, 2, 6, '[{"t":"たりとも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-3', 2, '遅れた', 'おくれた', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"遅","r":"おく"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-3', 3, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-3', 4, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-3', 5, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-3', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-4', 0, '一言', 'ひとこと', (select id from words where primary_form = '一言' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一言","r":"ひとこと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-4', 1, 'たりとも', 'たりとも', NULL, 2, 6, '[{"t":"たりとも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-4', 2, '聞き', 'きき', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"聞","r":"き"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-4', 3, '逃せ', 'のがせ', (select id from words where primary_form = '逃す' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"逃","r":"のが"},{"t":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-4', 4, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-taritomo-4', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-1', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-1', 1, 'といえども', 'といえども', NULL, 2, 7, '[{"t":"といえども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-1', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-1', 3, '責任', 'せきにん', (select id from words where primary_form = '責任' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"責任","r":"せきにん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-1', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-1', 5, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-1', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-2', 0, '医者', 'いしゃ', (select id from words where primary_form = '医者' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"医者","r":"いしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-2', 1, 'といえども', 'といえども', NULL, 2, 7, '[{"t":"といえども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-2', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-2', 3, '間違い', 'まちがい', (select id from words where primary_form = '間違い' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"間違","r":"まちが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-2', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-2', 5, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 1, 'といえども', 'といえども', NULL, 3, 8, '[{"t":"といえども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 3, '休み', 'やすみ', (select id from words where primary_form = '休み' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"休","r":"やす"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 5, '必要', 'ひつよう', (select id from words where primary_form = '必要' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"必要","r":"ひつよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 6, 'だ', 'だ', NULL, 14, 15, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-3', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 0, '社長', 'しゃちょう', (select id from words where primary_form = '社長' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"社長","r":"しゃちょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 1, 'といえども', 'といえども', NULL, 2, 7, '[{"t":"といえども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 3, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 4, 'を', 'を', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 5, '破って', 'やぶって', (select id from words where primary_form = '破る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"破","r":"やぶ"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 6, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 14, 15, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 7, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 15, 19, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toiedomo-4', 8, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-1', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-1', 2, '来る', 'くる', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"来","r":"く"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-1', 3, 'とは', 'とは', NULL, 4, 6, '[{"t":"とは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-1', 4, '思わなかった', 'おもわなかった', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 6, 12, '[{"t":"思","r":"おも"},{"t":"わなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-2', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-2', 2, '失敗する', 'しっぱいする', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 2, 6, '[{"t":"失敗","r":"しっぱい"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-2', 3, 'とは', 'とは', NULL, 6, 8, '[{"t":"とは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-2', 4, '驚いた', 'おどろいた', (select id from words where primary_form = '驚く' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"驚","r":"おどろ"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-3', 0, 'そんなに', 'そんなに', (select id from words where primary_form = 'そんなに' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"そんなに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-3', 1, '簡単', 'かんたん', (select id from words where primary_form = '簡単' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"簡単","r":"かんたん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-3', 2, 'だ', 'だ', NULL, 6, 7, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-3', 3, 'とは', 'とは', NULL, 7, 9, '[{"t":"とは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-3', 4, '知らなかった', 'しらなかった', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 9, 15, '[{"t":"知","r":"し"},{"t":"らなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-3', 5, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-4', 2, '社長', 'しゃちょう', (select id from words where primary_form = '社長' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"社長","r":"しゃちょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-4', 3, 'だ', 'だ', NULL, 4, 5, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-4', 4, 'とは', 'とは', NULL, 5, 7, '[{"t":"とは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-4', 5, '知らなかった', 'しらなかった', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 7, 13, '[{"t":"知","r":"し"},{"t":"らなかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-towa-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-1', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-1', 1, '言えば', 'いえば', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"言","r":"い"},{"t":"えば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-1', 2, 'よ', 'よ', (select id from words where primary_form = 'よ' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"よ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-1', 3, 'かった', 'かった', NULL, 6, 9, '[{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-1', 4, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-1', 5, 'を', 'を', NULL, 11, 12, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-2', 0, '相談すれば', 'そうだんすれば', (select id from words where primary_form = '相談' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"相談","r":"そうだん"},{"t":"すれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-2', 1, '助けた', 'たすけた', (select id from words where primary_form = '助ける' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"助","r":"たす"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-2', 2, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-2', 3, 'を', 'を', NULL, 10, 11, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-2', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 0, '休めば', 'やすめば', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"休","r":"やす"},{"t":"めば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 1, 'よ', 'よ', (select id from words where primary_form = 'よ' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"よ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 2, 'かった', 'かった', NULL, 4, 7, '[{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 3, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 5, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 6, '働き', 'はたらき', (select id from words where primary_form = '働き' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"働","r":"はたら"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 7, '続けた', 'つづけた', (select id from words where primary_form = '続ける' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"続","r":"つづ"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-3', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-4', 0, '謝れば', 'あやまれば', (select id from words where primary_form = '謝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"謝","r":"あやま"},{"t":"れば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-4', 1, '許した', 'ゆるした', (select id from words where primary_form = '許す' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"許","r":"ゆる"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-4', 2, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-4', 3, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-monowo-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-1', 0, '成功', 'せいこう', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"成功","r":"せいこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-1', 1, 'す', 'す', NULL, 2, 3, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-1', 2, 'べく', 'べく', NULL, 3, 5, '[{"t":"べく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-1', 3, '努力して', 'どりょくして', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"努力","r":"どりょく"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-1', 4, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-2', 0, '試験', 'しけん', (select id from words where primary_form = '試験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"試験","r":"しけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-2', 2, '合格', 'ごうかく', (select id from words where primary_form = '合格' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"合格","r":"ごうかく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-2', 3, 'す', 'す', NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-2', 4, 'べく', 'べく', NULL, 6, 8, '[{"t":"べく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-2', 5, '勉強した', 'べんきょうした', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"勉強","r":"べんきょう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-3', 0, '早く', 'はやく', (select id from words where primary_form = '早める' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"早","r":"はや"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-3', 1, '着く', 'つく', (select id from words where primary_form = '着く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"着","r":"つ"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-3', 2, 'べく', 'べく', NULL, 4, 6, '[{"t":"べく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-3', 3, '走った', 'はしった', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"走","r":"はし"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-4', 0, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-4', 2, '解決', 'かいけつ', (select id from words where primary_form = '解決' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"解決","r":"かいけつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-4', 3, 'す', 'す', NULL, 5, 6, '[{"t":"す"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-4', 4, 'べく', 'べく', NULL, 6, 8, '[{"t":"べく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-4', 5, '話し合った', 'はなしあった', (select id from words where primary_form = '話し合う' and language_id = 'lang-ja' and published order by id limit 1), 8, 13, '[{"t":"話","r":"はな"},{"t":"し"},{"t":"合","r":"あ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-beku-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-1', 0, '中', 'なか', (select id from words where primary_form = '中' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"中","r":"なか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-1', 2, '入る', 'はいる', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"入","r":"はい"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-1', 3, 'べからず', 'べからず', NULL, 4, 8, '[{"t":"べからず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-1', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-2', 0, '写真', 'しゃしん', (select id from words where primary_form = '写真' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"写真","r":"しゃしん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-2', 2, '撮る', 'とる', (select id from words where primary_form = '撮る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"撮","r":"と"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-2', 3, 'べからず', 'べからず', NULL, 5, 9, '[{"t":"べからず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-2', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-3', 0, '約束', 'やくそく', (select id from words where primary_form = '約束' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"約束","r":"やくそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-3', 2, '忘れる', 'わすれる', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"忘","r":"わす"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-3', 3, 'べからず', 'べからず', NULL, 6, 10, '[{"t":"べからず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-4', 0, '川', 'かわ', (select id from words where primary_form = '川' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"川","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-4', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-4', 2, '泳ぐ', 'およぐ', (select id from words where primary_form = '泳ぐ' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"泳","r":"およ"},{"t":"ぐ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-4', 3, 'べからず', 'べからず', NULL, 4, 8, '[{"t":"べからず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bekarazu-4', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-1', 2, '涙', 'なみだ', (select id from words where primary_form = '涙' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"涙","r":"なみだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-1', 3, 'ながらに', 'ながらに', NULL, 3, 7, '[{"t":"ながらに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-1', 4, '話した', 'はなした', (select id from words where primary_form = '話す' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"話","r":"はな"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-2', 0, '生まれ', 'うまれ', (select id from words where primary_form = '生まれ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"生","r":"う"},{"t":"まれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-2', 1, 'ながら', 'ながら', NULL, 3, 6, '[{"t":"ながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-2', 2, 'の', 'の', NULL, 6, 7, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-2', 3, '才能', 'さいのう', (select id from words where primary_form = '才能' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"才能","r":"さいのう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-2', 4, 'だ', 'だ', NULL, 9, 10, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-2', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-3', 0, '昔', 'むかし', (select id from words where primary_form = '昔' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"昔","r":"むかし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-3', 1, 'ながら', 'ながら', NULL, 1, 4, '[{"t":"ながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-3', 2, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-3', 3, '方法', 'ほうほう', (select id from words where primary_form = '方法' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"方法","r":"ほうほう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-3', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-3', 5, '作ります', 'つくります', (select id from words where primary_form = '作る' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"作","r":"つく"},{"t":"ります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-4', 0, '彼女', 'かのじょ', (select id from words where primary_form = '彼女' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼女","r":"かのじょ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-4', 2, '涙', 'なみだ', (select id from words where primary_form = '涙' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"涙","r":"なみだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-4', 3, 'ながらに', 'ながらに', NULL, 4, 8, '[{"t":"ながらに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-4', 4, '謝った', 'あやまった', (select id from words where primary_form = '謝る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"謝","r":"あやま"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nagarani-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 0, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 2, '着く', 'つく', (select id from words where primary_form = '着く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"着","r":"つ"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 3, 'や否や', 'やいなや', NULL, 4, 7, '[{"t":"や"},{"t":"否","r":"いな"},{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 5, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 6, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 7, '降った', 'ふった', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"降","r":"ふ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-1', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 0, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 2, '聞く', 'きく', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"聞","r":"き"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 3, 'や否や', 'やいなや', NULL, 4, 7, '[{"t":"や"},{"t":"否","r":"いな"},{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 5, '走って', 'はしって', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"走","r":"はし"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 6, '行った', 'いった', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"行","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-2', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 0, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 2, '入る', 'はいる', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"入","r":"はい"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 3, 'や否や', 'やいなや', NULL, 4, 7, '[{"t":"や"},{"t":"否","r":"いな"},{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 5, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 6, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 7, '見つけた', 'みつけた', (select id from words where primary_form = '見つける' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"見","r":"み"},{"t":"つけた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-3', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 0, '座る', 'すわる', (select id from words where primary_form = '座る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"座","r":"すわ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 1, 'や否や', 'やいなや', NULL, 2, 5, '[{"t":"や"},{"t":"否","r":"いな"},{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 3, '寝て', 'ねて', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"寝","r":"ね"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 4, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 5, 'ま', 'ま', NULL, 9, 10, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 6, 'いました', 'いました', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yainaya-4', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 0, 'ベル', 'ベル', (select id from words where primary_form = 'ベル' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"ベル"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 2, '鳴る', 'なる', (select id from words where primary_form = '鳴る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"鳴","r":"な"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 3, 'が早いか', 'がはやいか', NULL, 5, 9, '[{"t":"が"},{"t":"早","r":"はや"},{"t":"いか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 5, '教室', 'きょうしつ', (select id from words where primary_form = '教室' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"教室","r":"きょうしつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 6, 'を', 'を', NULL, 12, 13, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 7, '出た', 'でた', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"出","r":"で"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-1', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 2, '食べる', 'たべる', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"食","r":"た"},{"t":"べる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 3, 'が早いか', 'がはやいか', NULL, 5, 9, '[{"t":"が"},{"t":"早","r":"はや"},{"t":"いか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 5, '出て', 'でて', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"出","r":"で"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 6, '行った', 'いった', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 12, 15, '[{"t":"行","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-3', 0, '電話', 'でんわ', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電話","r":"でんわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-3', 2, '切る', 'きる', (select id from words where primary_form = '切る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"切","r":"き"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-3', 3, 'が早いか', 'がはやいか', NULL, 5, 9, '[{"t":"が"},{"t":"早","r":"はや"},{"t":"いか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-3', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-3', 5, '出かけた', 'でかけた', (select id from words where primary_form = '出かける' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"出","r":"で"},{"t":"かけた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-3', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 0, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 2, '聞く', 'きく', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"聞","r":"き"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 3, 'が早いか', 'がはやいか', NULL, 4, 8, '[{"t":"が"},{"t":"早","r":"はや"},{"t":"いか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 5, '走り', 'はしり', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"走","r":"はし"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 6, '出しました', 'だしました', (select id from words where primary_form = '出す' and language_id = 'lang-ja' and published order by id limit 1), 11, 16, '[{"t":"出","r":"だ"},{"t":"しました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gahayaika-4', 7, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb);
