-- N1 example sentences, batch 2: the instant, the failure, and the superlative.
--
-- 〜なり (the moment), 〜そこねる (missed the chance), 〜かねる (the polite
-- refusal), 〜までだ and 〜までもない (there is nothing more to it),
-- 〜に堪えない, 〜に難くない, 〜極まりない, 〜の至り and 〜の極み.
--
-- SKIPPED: 〜を余儀なくされる (slug wo-yoginaku-sareru) is NOT in this seed.
-- 余儀 is not a published word and splits to 余|儀 — two single kanji, which
-- `check:examples` raises as a warning and which would ship as two word-order
-- chips asking a reader to assemble a compound they have never seen. There is
-- no alternative spelling: 余儀なくされる has one. 〜の極み was brought forward
-- from 420 in its place and wo-yoginaku-sareru is left uncovered.
--
-- Two rewordings: その shreds to そ|の (as always), and なければ came apart as
-- な|け|れ|ば, so the までだ example is 電車がないなら rather than
-- 電車がなければ.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- nari-immediately
  ('sent-ex-nariimm-1', 'lang-ja', '彼は座るなり、寝てしまいました。', 'かれ わ すわる なり、ねて しまいました。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nariimm-2', 'lang-ja', '家に帰るなり、部屋に入った。', 'いえ に かえる なり、へや に はいった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nariimm-3', 'lang-ja', '話を聞くなり、泣きました。', 'はなし お きく なり、なきました。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nariimm-4', 'lang-ja', '彼は見るなり、笑いました。', 'かれ わ みる なり、わらいました。', 'lvl-ja-n1', 'authored', true),
  -- sokoneru
  ('sent-ex-sokoneru-1', 'lang-ja', '電車に乗りそこねた。', 'でんしゃ に のりそこねた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-sokoneru-2', 'lang-ja', 'ご飯を食べそこねた。', 'ごはん お たべそこねた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-sokoneru-3', 'lang-ja', 'お礼を言いそこねた。', 'おれい お いいそこねた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-sokoneru-4', 'lang-ja', 'あの映画を見そこねました。', 'あの えいが お みそこねました。', 'lvl-ja-n1', 'authored', true),
  -- kaneru
  ('sent-ex-kaneru-1', 'lang-ja', '答えかねます。', 'こたえかねます。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kaneru-2', 'lang-ja', '分かりかねます。', 'わかりかねます。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kaneru-3', 'lang-ja', '決めかねています。', 'きめかねて います。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kaneru-4', 'lang-ja', 'あの仕事は引き受けかねます。', 'あの しごと わ ひきうけかねます。', 'lvl-ja-n1', 'authored', true),
  -- made-da
  ('sent-ex-madeda-1', 'lang-ja', '断られたら、諦めるまでだ。', 'ことわられたら、あきらめる まで だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-madeda-2', 'lang-ja', '電車がないなら、歩くまでだ。', 'でんしゃ が ない なら、あるく まで だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-madeda-3', 'lang-ja', '失敗したら、もう一度やるまでだ。', 'しっぱい したら、もう いちど やる まで だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-madeda-4', 'lang-ja', '無理なら、自分でやるまでだ。', 'むり なら、じぶん で やる まで だ。', 'lvl-ja-n1', 'authored', true),
  -- made-mo-nai
  ('sent-ex-mademonai-1', 'lang-ja', '言うまでもない。', 'いう まで も ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-mademonai-2', 'lang-ja', '説明するまでもない。', 'せつめい する まで も ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-mademonai-3', 'lang-ja', '聞くまでもないことだ。', 'きく まで も ない こと だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-mademonai-4', 'lang-ja', '心配するまでもありません。', 'しんぱい する まで も ありません。', 'lvl-ja-n1', 'authored', true),
  -- ni-taenai
  ('sent-ex-nitaenai-1', 'lang-ja', '感謝に堪えません。', 'かんしゃ に たえません。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nitaenai-2', 'lang-ja', '喜びに堪えません。', 'よろこび に たえません。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nitaenai-3', 'lang-ja', '彼の話は聞くに堪えない。', 'かれ の はなし わ きく に たえない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nitaenai-4', 'lang-ja', '見るに堪えない映画だった。', 'みる に たえない えいが だった。', 'lvl-ja-n1', 'authored', true),
  -- no-kiwami
  ('sent-ex-nokiwami-1', 'lang-ja', '疲労の極みだった。', 'ひろう の きわみ だった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nokiwami-2', 'lang-ja', '幸せの極みです。', 'しあわせ の きわみ です。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nokiwami-3', 'lang-ja', '混乱の極みだった。', 'こんらん の きわみ だった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nokiwami-4', 'lang-ja', '緊張の極みだった。', 'きんちょう の きわみ だった。', 'lvl-ja-n1', 'authored', true),
  -- ni-katakunai
  ('sent-ex-nikatakunai-1', 'lang-ja', '想像に難くない。', 'そうぞう に かたくない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nikatakunai-2', 'lang-ja', '彼の気持ちは察するに難くない。', 'かれ の きもち わ さっする に かたくない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nikatakunai-3', 'lang-ja', '結果は予想に難くない。', 'けっか わ よそう に かたくない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nikatakunai-4', 'lang-ja', '彼が怒るのは想像に難くない。', 'かれ が おこる の わ そうぞう に かたくない。', 'lvl-ja-n1', 'authored', true),
  -- kiwamarinai
  ('sent-ex-kiwamarinai-1', 'lang-ja', '危険極まりない行動だ。', 'きけん きわまりない こうどう だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kiwamarinai-2', 'lang-ja', '失礼極まりない。', 'しつれい きわまりない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kiwamarinai-3', 'lang-ja', '不便極まりない場所だ。', 'ふべん きわまりない ばしょ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kiwamarinai-4', 'lang-ja', '退屈極まりない話だった。', 'たいくつ きわまりない はなし だった。', 'lvl-ja-n1', 'authored', true),
  -- no-itari
  ('sent-ex-noitari-1', 'lang-ja', '感激の至りです。', 'かんげき の いたり です。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-noitari-2', 'lang-ja', '後悔の至りです。', 'こうかい の いたり です。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-noitari-3', 'lang-ja', '恐縮の至りです。', 'きょうしゅく の いたり です。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-noitari-4', 'lang-ja', '喜びの至りです。', 'よろこび の いたり です。', 'lvl-ja-n1', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-nariimm-1', 'sent-ex-nariimm-1', 'en', 'The moment he sat down, he fell asleep.', 'authored'),
  ('st-ex-nariimm-2', 'sent-ex-nariimm-2', 'en', 'The moment he got home, he went to his room.', 'authored'),
  ('st-ex-nariimm-3', 'sent-ex-nariimm-3', 'en', 'The moment she heard, she cried.', 'authored'),
  ('st-ex-nariimm-4', 'sent-ex-nariimm-4', 'en', 'The moment he saw it, he laughed.', 'authored'),
  ('st-ex-sokoneru-1', 'sent-ex-sokoneru-1', 'en', 'I missed the train.', 'authored'),
  ('st-ex-sokoneru-2', 'sent-ex-sokoneru-2', 'en', 'I missed my chance to eat.', 'authored'),
  ('st-ex-sokoneru-3', 'sent-ex-sokoneru-3', 'en', 'I missed my chance to say thank you.', 'authored'),
  ('st-ex-sokoneru-4', 'sent-ex-sokoneru-4', 'en', 'I missed that film.', 'authored'),
  ('st-ex-kaneru-1', 'sent-ex-kaneru-1', 'en', 'I am not in a position to answer.', 'authored'),
  ('st-ex-kaneru-2', 'sent-ex-kaneru-2', 'en', 'I am afraid I cannot say.', 'authored'),
  ('st-ex-kaneru-3', 'sent-ex-kaneru-3', 'en', 'I am finding it hard to decide.', 'authored'),
  ('st-ex-kaneru-4', 'sent-ex-kaneru-4', 'en', 'I am afraid I cannot take that job on.', 'authored'),
  ('st-ex-madeda-1', 'sent-ex-madeda-1', 'en', 'If they turn me down, I will simply give up.', 'authored'),
  ('st-ex-madeda-2', 'sent-ex-madeda-2', 'en', 'If there is no train, I will simply walk.', 'authored'),
  ('st-ex-madeda-3', 'sent-ex-madeda-3', 'en', 'If it fails, I will simply do it again.', 'authored'),
  ('st-ex-madeda-4', 'sent-ex-madeda-4', 'en', 'If it cannot be helped, I will simply do it myself.', 'authored'),
  ('st-ex-mademonai-1', 'sent-ex-mademonai-1', 'en', 'It goes without saying.', 'authored'),
  ('st-ex-mademonai-2', 'sent-ex-mademonai-2', 'en', 'There is no need to explain.', 'authored'),
  ('st-ex-mademonai-3', 'sent-ex-mademonai-3', 'en', 'It is not something you need to ask about.', 'authored'),
  ('st-ex-mademonai-4', 'sent-ex-mademonai-4', 'en', 'There is no need to worry.', 'authored'),
  ('st-ex-nitaenai-1', 'sent-ex-nitaenai-1', 'en', 'I cannot thank you enough.', 'authored'),
  ('st-ex-nitaenai-2', 'sent-ex-nitaenai-2', 'en', 'My joy is more than I can bear.', 'authored'),
  ('st-ex-nitaenai-3', 'sent-ex-nitaenai-3', 'en', 'His talk is unbearable to listen to.', 'authored'),
  ('st-ex-nitaenai-4', 'sent-ex-nitaenai-4', 'en', 'It was a film I could not bear to watch.', 'authored'),
  ('st-ex-nokiwami-1', 'sent-ex-nokiwami-1', 'en', 'I was utterly exhausted.', 'authored'),
  ('st-ex-nokiwami-2', 'sent-ex-nokiwami-2', 'en', 'I could not be happier.', 'authored'),
  ('st-ex-nokiwami-3', 'sent-ex-nokiwami-3', 'en', 'It was utter confusion.', 'authored'),
  ('st-ex-nokiwami-4', 'sent-ex-nokiwami-4', 'en', 'The tension was at its height.', 'authored'),
  ('st-ex-nikatakunai-1', 'sent-ex-nikatakunai-1', 'en', 'It is not hard to imagine.', 'authored'),
  ('st-ex-nikatakunai-2', 'sent-ex-nikatakunai-2', 'en', 'His feelings are not hard to guess at.', 'authored'),
  ('st-ex-nikatakunai-3', 'sent-ex-nikatakunai-3', 'en', 'The result is not hard to predict.', 'authored'),
  ('st-ex-nikatakunai-4', 'sent-ex-nikatakunai-4', 'en', 'It is not hard to imagine him getting angry.', 'authored'),
  ('st-ex-kiwamarinai-1', 'sent-ex-kiwamarinai-1', 'en', 'It is extremely dangerous behaviour.', 'authored'),
  ('st-ex-kiwamarinai-2', 'sent-ex-kiwamarinai-2', 'en', 'It is the height of rudeness.', 'authored'),
  ('st-ex-kiwamarinai-3', 'sent-ex-kiwamarinai-3', 'en', 'It is an extremely inconvenient place.', 'authored'),
  ('st-ex-kiwamarinai-4', 'sent-ex-kiwamarinai-4', 'en', 'It was an unbelievably dull talk.', 'authored'),
  ('st-ex-noitari-1', 'sent-ex-noitari-1', 'en', 'I am deeply moved.', 'authored'),
  ('st-ex-noitari-2', 'sent-ex-noitari-2', 'en', 'I could not regret it more.', 'authored'),
  ('st-ex-noitari-3', 'sent-ex-noitari-3', 'en', 'I am extremely obliged to you.', 'authored'),
  ('st-ex-noitari-4', 'sent-ex-noitari-4', 'en', 'I could not be more delighted.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('nari-immediately', 'sent-ex-nariimm-1', 0),
  ('nari-immediately', 'sent-ex-nariimm-2', 1),
  ('nari-immediately', 'sent-ex-nariimm-3', 2),
  ('nari-immediately', 'sent-ex-nariimm-4', 3),
  ('sokoneru', 'sent-ex-sokoneru-1', 0),
  ('sokoneru', 'sent-ex-sokoneru-2', 1),
  ('sokoneru', 'sent-ex-sokoneru-3', 2),
  ('sokoneru', 'sent-ex-sokoneru-4', 3),
  ('kaneru', 'sent-ex-kaneru-1', 0),
  ('kaneru', 'sent-ex-kaneru-2', 1),
  ('kaneru', 'sent-ex-kaneru-3', 2),
  ('kaneru', 'sent-ex-kaneru-4', 3),
  ('made-da', 'sent-ex-madeda-1', 0),
  ('made-da', 'sent-ex-madeda-2', 1),
  ('made-da', 'sent-ex-madeda-3', 2),
  ('made-da', 'sent-ex-madeda-4', 3),
  ('made-mo-nai', 'sent-ex-mademonai-1', 0),
  ('made-mo-nai', 'sent-ex-mademonai-2', 1),
  ('made-mo-nai', 'sent-ex-mademonai-3', 2),
  ('made-mo-nai', 'sent-ex-mademonai-4', 3),
  ('ni-taenai', 'sent-ex-nitaenai-1', 0),
  ('ni-taenai', 'sent-ex-nitaenai-2', 1),
  ('ni-taenai', 'sent-ex-nitaenai-3', 2),
  ('ni-taenai', 'sent-ex-nitaenai-4', 3),
  ('no-kiwami', 'sent-ex-nokiwami-1', 0),
  ('no-kiwami', 'sent-ex-nokiwami-2', 1),
  ('no-kiwami', 'sent-ex-nokiwami-3', 2),
  ('no-kiwami', 'sent-ex-nokiwami-4', 3),
  ('ni-katakunai', 'sent-ex-nikatakunai-1', 0),
  ('ni-katakunai', 'sent-ex-nikatakunai-2', 1),
  ('ni-katakunai', 'sent-ex-nikatakunai-3', 2),
  ('ni-katakunai', 'sent-ex-nikatakunai-4', 3),
  ('kiwamarinai', 'sent-ex-kiwamarinai-1', 0),
  ('kiwamarinai', 'sent-ex-kiwamarinai-2', 1),
  ('kiwamarinai', 'sent-ex-kiwamarinai-3', 2),
  ('kiwamarinai', 'sent-ex-kiwamarinai-4', 3),
  ('no-itari', 'sent-ex-noitari-1', 0),
  ('no-itari', 'sent-ex-noitari-2', 1),
  ('no-itari', 'sent-ex-noitari-3', 2),
  ('no-itari', 'sent-ex-noitari-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-nariimm-1', 'sent-ex-nariimm-2', 'sent-ex-nariimm-3', 'sent-ex-nariimm-4', 'sent-ex-sokoneru-1', 'sent-ex-sokoneru-2', 'sent-ex-sokoneru-3', 'sent-ex-sokoneru-4', 'sent-ex-kaneru-1', 'sent-ex-kaneru-2', 'sent-ex-kaneru-3', 'sent-ex-kaneru-4', 'sent-ex-madeda-1', 'sent-ex-madeda-2', 'sent-ex-madeda-3', 'sent-ex-madeda-4', 'sent-ex-mademonai-1', 'sent-ex-mademonai-2', 'sent-ex-mademonai-3', 'sent-ex-mademonai-4', 'sent-ex-nitaenai-1', 'sent-ex-nitaenai-2', 'sent-ex-nitaenai-3', 'sent-ex-nitaenai-4', 'sent-ex-nokiwami-1', 'sent-ex-nokiwami-2', 'sent-ex-nokiwami-3', 'sent-ex-nokiwami-4', 'sent-ex-nikatakunai-1', 'sent-ex-nikatakunai-2', 'sent-ex-nikatakunai-3', 'sent-ex-nikatakunai-4', 'sent-ex-kiwamarinai-1', 'sent-ex-kiwamarinai-2', 'sent-ex-kiwamarinai-3', 'sent-ex-kiwamarinai-4', 'sent-ex-noitari-1', 'sent-ex-noitari-2', 'sent-ex-noitari-3', 'sent-ex-noitari-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 2, '座る', 'すわる', (select id from words where primary_form = '座る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"座","r":"すわ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 4, 'り', 'り', NULL, 5, 6, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 5, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 6, '寝て', 'ねて', (select id from words where primary_form = '寝る' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"寝","r":"ね"},{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 7, 'し', 'し', (select id from words where primary_form = 'し' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"し"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 8, 'ま', 'ま', NULL, 10, 11, '[{"t":"ま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 9, 'いました', 'いました', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-1', 10, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 0, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 2, '帰る', 'かえる', (select id from words where primary_form = '帰る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"帰","r":"かえ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 4, 'り', 'り', NULL, 5, 6, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 5, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 6, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 7, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 8, '入った', 'はいった', (select id from words where primary_form = '入る' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"入","r":"はい"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-2', 9, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 0, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 2, '聞く', 'きく', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"聞","r":"き"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 4, 'り', 'り', NULL, 5, 6, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 5, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 6, '泣きました', 'なきました', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"泣","r":"な"},{"t":"きました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-3', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 2, '見る', 'みる', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"見","r":"み"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 4, 'り', 'り', NULL, 5, 6, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 5, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 6, '笑いました', 'わらいました', (select id from words where primary_form = '笑う' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"笑","r":"わら"},{"t":"いました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nariimm-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-1', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-1', 2, '乗りそこねた', 'のりそこねた', (select id from words where primary_form = '乗る' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"乗","r":"の"},{"t":"りそこねた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-1', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-2', 0, 'ご飯', 'ごはん', (select id from words where primary_form = 'ご飯' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"ご"},{"t":"飯","r":"はん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-2', 2, '食べそこねた', 'たべそこねた', (select id from words where primary_form = '食べる' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"食","r":"た"},{"t":"べそこねた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-2', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-3', 0, 'お礼', 'おれい', (select id from words where primary_form = 'お礼' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"お"},{"t":"礼","r":"れい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-3', 2, '言いそこねた', 'いいそこねた', (select id from words where primary_form = '言いつける' and language_id = 'lang-ja' and published order by id limit 1), 3, 9, '[{"t":"言","r":"い"},{"t":"いそこねた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-3', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-4', 1, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-4', 2, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-4', 3, '見そこねました', 'みそこねました', (select id from words where primary_form = '見せびらかす' and language_id = 'lang-ja' and published order by id limit 1), 5, 12, '[{"t":"見","r":"み"},{"t":"そこねました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sokoneru-4', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-1', 0, '答え', 'こたえ', (select id from words where primary_form = '答え' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"答","r":"こた"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-1', 1, 'かね', 'かね', (select id from words where primary_form = 'かね' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-1', 2, 'ます', 'ます', NULL, 4, 6, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-1', 3, '。', '。', NULL, 6, 7, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-2', 0, '分', 'わ', (select id from words where primary_form = '分' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"分","r":"わ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-2', 1, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-2', 2, 'り', 'り', NULL, 2, 3, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-2', 3, 'かね', 'かね', (select id from words where primary_form = 'かね' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"かね"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-2', 4, 'ます', 'ます', NULL, 5, 7, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-2', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-3', 0, '決', 'き', (select id from words where primary_form = '決' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"決","r":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-3', 1, 'め', 'め', NULL, 1, 2, '[{"t":"め"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-3', 2, 'かねて', 'かねて', (select id from words where primary_form = '予て' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"かねて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-3', 3, 'います', 'います', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-3', 4, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-4', 1, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-4', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-4', 3, '引き', 'ひき', (select id from words where primary_form = '引きずる' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"引","r":"ひ"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-4', 4, '受けかねます', 'うけかねます', (select id from words where primary_form = '受ける' and language_id = 'lang-ja' and published order by id limit 1), 7, 13, '[{"t":"受","r":"う"},{"t":"けかねます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kaneru-4', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-1', 0, '断られたら', 'ことわられたら', (select id from words where primary_form = '断る' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"断","r":"ことわ"},{"t":"られたら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-1', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-1', 2, '諦める', 'あきらめる', (select id from words where primary_form = '諦める' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"諦","r":"あきら"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-1', 3, 'までだ', 'までだ', NULL, 9, 12, '[{"t":"までだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-1', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 0, '電車', 'でんしゃ', (select id from words where primary_form = '電車' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"電車","r":"でんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 2, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 3, 'なら', 'なら', NULL, 5, 7, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 5, '歩く', 'あるく', (select id from words where primary_form = '歩く' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"歩","r":"ある"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 6, 'までだ', 'までだ', NULL, 10, 13, '[{"t":"までだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-2', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 0, '失敗したら', 'しっぱいしたら', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"失敗","r":"しっぱい"},{"t":"したら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 1, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 2, 'もう', 'もう', (select id from words where primary_form = 'もう' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"もう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 3, '一度', 'いちど', (select id from words where primary_form = '一度' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"一度","r":"いちど"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 4, 'や', 'や', (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 5, 'る', 'る', NULL, 11, 12, '[{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 6, 'までだ', 'までだ', NULL, 12, 15, '[{"t":"までだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-3', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 0, '無理', 'むり', (select id from words where primary_form = '無理' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"無理","r":"むり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 1, 'なら', 'なら', NULL, 2, 4, '[{"t":"なら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 2, '、', '、', NULL, 4, 5, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 3, '自分', 'じぶん', (select id from words where primary_form = '自分' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"自分","r":"じぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 5, 'や', 'や', (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 6, 'る', 'る', NULL, 9, 10, '[{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 7, 'までだ', 'までだ', NULL, 10, 13, '[{"t":"までだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-madeda-4', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-1', 0, '言う', 'いう', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"言","r":"い"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-1', 1, 'までもない', 'までもない', NULL, 2, 7, '[{"t":"までもない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-1', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-2', 0, '説明する', 'せつめいする', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"説明","r":"せつめい"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-2', 1, 'までもない', 'までもない', NULL, 4, 9, '[{"t":"までもない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-2', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-3', 0, '聞く', 'きく', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"聞","r":"き"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-3', 1, 'までもない', 'までもない', NULL, 2, 7, '[{"t":"までもない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-3', 2, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-3', 3, 'だ', 'だ', NULL, 9, 10, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-4', 0, '心配する', 'しんぱいする', (select id from words where primary_form = '心配' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"心配","r":"しんぱい"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-4', 1, 'まで', 'まで', NULL, 4, 6, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-4', 2, 'も', 'も', NULL, 6, 7, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-4', 3, 'ありません', 'ありません', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 7, 12, '[{"t":"ありません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-mademonai-4', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-1', 0, '感謝', 'かんしゃ', (select id from words where primary_form = '感謝' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"感謝","r":"かんしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-1', 2, '堪えません', 'たえません', (select id from words where primary_form = '堪える' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"堪","r":"た"},{"t":"えません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-2', 0, '喜び', 'よろこび', (select id from words where primary_form = '喜び' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"喜","r":"よろこ"},{"t":"び"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-2', 2, '堪えません', 'たえません', (select id from words where primary_form = '堪える' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"堪","r":"た"},{"t":"えません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-3', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-3', 1, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-3', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-3', 3, '聞く', 'きく', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"聞","r":"き"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-3', 5, '堪えない', 'たえない', (select id from words where primary_form = '堪える' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"堪","r":"た"},{"t":"えない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-4', 0, '見る', 'みる', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"見","r":"み"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-4', 2, '堪えない', 'たえない', (select id from words where primary_form = '堪える' and language_id = 'lang-ja' and published order by id limit 1), 3, 7, '[{"t":"堪","r":"た"},{"t":"えない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-4', 3, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-4', 4, 'だった', 'だった', NULL, 9, 12, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitaenai-4', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-1', 0, '疲労', 'ひろう', (select id from words where primary_form = '疲労' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"疲労","r":"ひろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-1', 1, 'の極み', 'のきわみ', NULL, 2, 5, '[{"t":"の"},{"t":"極","r":"きわ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-1', 2, 'だった', 'だった', NULL, 5, 8, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-1', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-2', 0, '幸せ', 'しあわせ', (select id from words where primary_form = '幸せ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"幸","r":"しあわ"},{"t":"せ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-2', 1, 'の極み', 'のきわみ', NULL, 2, 5, '[{"t":"の"},{"t":"極","r":"きわ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-2', 2, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-2', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-3', 0, '混乱', 'こんらん', (select id from words where primary_form = '混乱' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"混乱","r":"こんらん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-3', 1, 'の極み', 'のきわみ', NULL, 2, 5, '[{"t":"の"},{"t":"極","r":"きわ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-3', 2, 'だった', 'だった', NULL, 5, 8, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-3', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-4', 0, '緊張', 'きんちょう', (select id from words where primary_form = '緊張' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"緊張","r":"きんちょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-4', 1, 'の極み', 'のきわみ', NULL, 2, 5, '[{"t":"の"},{"t":"極","r":"きわ"},{"t":"み"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-4', 2, 'だった', 'だった', NULL, 5, 8, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nokiwami-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-1', 0, '想像', 'そうぞう', (select id from words where primary_form = '想像' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"想像","r":"そうぞう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-1', 1, 'に難くない', 'にかたくない', NULL, 2, 7, '[{"t":"に"},{"t":"難","r":"かた"},{"t":"くない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-1', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-2', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-2', 1, '気持ち', 'きもち', (select id from words where primary_form = '気持ち' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"気持","r":"きも"},{"t":"ち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-2', 3, '察する', 'さっする', (select id from words where primary_form = '察する' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"察","r":"さっ"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-2', 4, 'に難くない', 'にかたくない', NULL, 9, 14, '[{"t":"に"},{"t":"難","r":"かた"},{"t":"くない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-2', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-3', 0, '結果', 'けっか', (select id from words where primary_form = '結果' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"結果","r":"けっか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-3', 2, '予想', 'よそう', (select id from words where primary_form = '予想' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"予想","r":"よそう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-3', 3, 'に難くない', 'にかたくない', NULL, 5, 10, '[{"t":"に"},{"t":"難","r":"かた"},{"t":"くない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 2, '怒る', 'おこる', (select id from words where primary_form = '怒る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"怒","r":"おこ"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 5, '想像', 'そうぞう', (select id from words where primary_form = '想像' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"想像","r":"そうぞう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 6, 'に難くない', 'にかたくない', NULL, 8, 13, '[{"t":"に"},{"t":"難","r":"かた"},{"t":"くない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nikatakunai-4', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-1', 0, '危険', 'きけん', (select id from words where primary_form = '危険' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"危険","r":"きけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-1', 1, '極まりない', '極まりない', NULL, 2, 7, '[{"t":"極","r":"極"},{"t":"まりない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-1', 2, '行動', 'こうどう', (select id from words where primary_form = '行動' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"行動","r":"こうどう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-1', 3, 'だ', 'だ', NULL, 9, 10, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-1', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-2', 0, '失礼', 'しつれい', (select id from words where primary_form = '失礼' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"失礼","r":"しつれい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-2', 1, '極まりない', '極まりない', NULL, 2, 7, '[{"t":"極","r":"極"},{"t":"まりない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-2', 2, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-3', 0, '不便', 'ふべん', (select id from words where primary_form = '不便' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"不便","r":"ふべん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-3', 1, '極まりない', '極まりない', NULL, 2, 7, '[{"t":"極","r":"極"},{"t":"まりない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-3', 2, '場所', 'ばしょ', (select id from words where primary_form = '場所' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"場所","r":"ばしょ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-3', 3, 'だ', 'だ', NULL, 9, 10, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-3', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-4', 0, '退屈', 'たいくつ', (select id from words where primary_form = '退屈' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"退屈","r":"たいくつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-4', 1, '極まりない', '極まりない', NULL, 2, 7, '[{"t":"極","r":"極"},{"t":"まりない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-4', 2, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-4', 3, 'だった', 'だった', NULL, 8, 11, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiwamarinai-4', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-1', 0, '感激', 'かんげき', (select id from words where primary_form = '感激' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"感激","r":"かんげき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-1', 1, 'の至り', 'のいたり', NULL, 2, 5, '[{"t":"の"},{"t":"至","r":"いた"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-1', 2, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-1', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-2', 0, '後悔', 'こうかい', (select id from words where primary_form = '後悔' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"後悔","r":"こうかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-2', 1, 'の至り', 'のいたり', NULL, 2, 5, '[{"t":"の"},{"t":"至","r":"いた"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-2', 2, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-2', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-3', 0, '恐縮', 'きょうしゅく', (select id from words where primary_form = '恐縮' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"恐縮","r":"きょうしゅく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-3', 1, 'の至り', 'のいたり', NULL, 2, 5, '[{"t":"の"},{"t":"至","r":"いた"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-3', 2, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-3', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-4', 0, '喜び', 'よろこび', (select id from words where primary_form = '喜び' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"喜","r":"よろこ"},{"t":"び"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-4', 1, 'の至り', 'のいたり', NULL, 2, 5, '[{"t":"の"},{"t":"至","r":"いた"},{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-4', 2, 'です', 'です', NULL, 5, 7, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-noitari-4', 3, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb);
