-- N1 example sentences, batch 3: combining, tendency, and disregard.
--
-- 〜と相まって (one thing working with another), 〜はずみに (the accidental
-- moment), 〜きらいがある (the unwelcome tendency), 〜に伴って (change that
-- follows change), 〜をよそに (going ahead regardless), 〜ならでは (only this
-- one has it), 〜いながらにして (without leaving where you are), 〜ごとき /
-- 〜ごとく, 〜としたって and 〜なくして.
--
-- Four rewordings:
--
--   楽しかった shredded to 楽|しか|っ|た behind 旅行は — the past of 楽しい
--   is not in the index — so the sentence ends 楽しい旅行になった instead.
--
--   面白かった warned on 面|白: the past inflection loses the compound. 良かった
--   does not.
--
--   手をついた lost を|つ|き; つく in kana has no entry. 本を落とした does.
--
--   ごとく in kana shreds to の|ご|とく, though ごとき does not. 如く is
--   published, so the 〜ごとく example uses the kanji spelling.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- to-aimatte
  ('sent-ex-toaimatte-1', 'lang-ja', '良い天気と相まって、楽しい旅行になった。', 'よい てんき と あいまって、たのしい りょこう に なった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toaimatte-2', 'lang-ja', '才能が努力と相まって、成功した。', 'さいのう が どりょく と あいまって、せいこう した。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toaimatte-3', 'lang-ja', '音楽と相まって、映画は良かった。', 'おんがく と あいまって、えいが わ よかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toaimatte-4', 'lang-ja', '安い値段と相まって、人気が出ました。', 'やすい ねだん と あいまって、にんき が でました。', 'lvl-ja-n1', 'authored', true),
  -- hazumi-ni
  ('sent-ex-hazumini-1', 'lang-ja', '転んだはずみに、本を落とした。', 'ころんだ はずみ に、ほん お おとした。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-hazumini-2', 'lang-ja', '立ち上がったはずみに、机にぶつかった。', 'たちあがった はずみ に、つくえ に ぶつかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-hazumini-3', 'lang-ja', '急いで走ったはずみに、転んだ。', 'いそいで はしった はずみ に、ころんだ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-hazumini-4', 'lang-ja', 'ドアを開けたはずみに、指を挟んだ。', 'ドア お あけた はずみ に、ゆび お はさんだ。', 'lvl-ja-n1', 'authored', true),
  -- kirai-ga-aru
  ('sent-ex-kiraigaaru-1', 'lang-ja', '彼は物事を悪く考えるきらいがある。', 'かれ わ ものごと お わるく かんがえる きらい が ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kiraigaaru-2', 'lang-ja', '若い人は無理をするきらいがある。', 'わかい ひと わ むり お する きらい が ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kiraigaaru-3', 'lang-ja', '彼女は人の話を聞かないきらいがある。', 'かのじょ わ ひと の はなし お きかない きらい が ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kiraigaaru-4', 'lang-ja', '彼は一人で決めるきらいがある。', 'かれ わ ひとり で きめる きらい が ある。', 'lvl-ja-n1', 'authored', true),
  -- ni-tomonatte
  ('sent-ex-nitomonatte-1', 'lang-ja', '経済の成長に伴って、生活が豊かになった。', 'けいざい の せいちょう に ともなって、せいかつ が ゆたか に なった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nitomonatte-2', 'lang-ja', '人口が増えるに伴って、問題も増えた。', 'じんこう が ふえる に ともなって、もんだい も ふえた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nitomonatte-3', 'lang-ja', '気温が上がるに伴って、雪が溶けた。', 'きおん が あがる に ともなって、ゆき が とけた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nitomonatte-4', 'lang-ja', '年をとるに伴って、体が弱くなる。', 'とし お とる に ともなって、からだ が よわく なる。', 'lvl-ja-n1', 'authored', true),
  -- wo-yoso-ni
  ('sent-ex-woyosoni-1', 'lang-ja', '親の心配をよそに、彼は旅に出た。', 'おや の しんぱい お よそ に、かれ わ たび に でた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-woyosoni-2', 'lang-ja', '反対をよそに、計画を進めた。', 'はんたい お よそ に、けいかく お すすめた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-woyosoni-3', 'lang-ja', '危険をよそに、川に飛び込んだ。', 'きけん お よそ に、かわ に とびこんだ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-woyosoni-4', 'lang-ja', '家族の期待をよそに、彼は会社を辞めた。', 'かぞく の きたい お よそ に、かれ わ かいしゃ お やめた。', 'lvl-ja-n1', 'authored', true),
  -- to-wa-ie-mono-no
  ('sent-ex-naradewa-1', 'lang-ja', '日本ならではの料理です。', 'にほん ならでは の りょうり です。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-naradewa-2', 'lang-ja', '冬ならではの楽しみがある。', 'ふゆ ならでは の たのしみ が ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-naradewa-3', 'lang-ja', 'あの店ならではの味だ。', 'あの みせ ならでは の あじ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-naradewa-4', 'lang-ja', 'あの先生ならではの説明だ。', 'あの せんせい ならでは の せつめい だ。', 'lvl-ja-n1', 'authored', true),
  -- inagara-ni-shite
  ('sent-ex-inagarani-1', 'lang-ja', '家にいながらにして買い物ができる。', 'いえ に いながら に して かいもの が できる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-inagarani-2', 'lang-ja', 'いながらにして世界の様子が分かる。', 'いながら に して せかい の ようす が わかる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-inagarani-3', 'lang-ja', '部屋にいながらにして映画が見られる。', 'へや に いながら に して えいが が みられる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-inagarani-4', 'lang-ja', '家にいながらにして仕事ができます。', 'いえ に いながら に して しごと が できます。', 'lvl-ja-n1', 'authored', true),
  -- gotoki
  ('sent-ex-gotoki-1', 'lang-ja', '彼のごとき人は少ない。', 'かれ の ごとき ひと わ すくない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gotoki-2', 'lang-ja', '私ごときには無理です。', 'わたし ごとき に わ むり です。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gotoki-3', 'lang-ja', '氷の如く冷たい。', 'こおり の ごとく つめたい。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gotoki-4', 'lang-ja', '山のごとき荷物だ。', 'やま の ごとき にもつ だ。', 'lvl-ja-n1', 'authored', true),
  -- to-ittatte
  ('sent-ex-toshitatte-1', 'lang-ja', '急いだとしたって、間に合わない。', 'いそいだ と したって、まにあわない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toshitatte-2', 'lang-ja', '高いとしたって、買います。', 'たかい と したって、かいます。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toshitatte-3', 'lang-ja', '反対したとしたって、変わらない。', 'はんたい した と したって、かわらない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-toshitatte-4', 'lang-ja', '説明したとしたって、分からないだろう。', 'せつめい した と したって、わからない だろう。', 'lvl-ja-n1', 'authored', true),
  -- nakushite
  ('sent-ex-nakushite-1', 'lang-ja', '努力なくして成功はない。', 'どりょく なくして せいこう わ ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nakushite-2', 'lang-ja', '彼の協力なくしてはできなかった。', 'かれ の きょうりょく なくして わ できなかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nakushite-3', 'lang-ja', '準備なくして始められません。', 'じゅんび なくして はじめられません。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nakushite-4', 'lang-ja', '愛なくして人生はない。', 'あい なくして じんせい わ ない。', 'lvl-ja-n1', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-toaimatte-1', 'sent-ex-toaimatte-1', 'en', 'Coupled with the good weather, it turned into an enjoyable trip.', 'authored'),
  ('st-ex-toaimatte-2', 'sent-ex-toaimatte-2', 'en', 'His talent, together with his effort, made him a success.', 'authored'),
  ('st-ex-toaimatte-3', 'sent-ex-toaimatte-3', 'en', 'Along with the music, the film was good.', 'authored'),
  ('st-ex-toaimatte-4', 'sent-ex-toaimatte-4', 'en', 'Coupled with the low price, it became popular.', 'authored'),
  ('st-ex-hazumini-1', 'sent-ex-hazumini-1', 'en', 'As I fell, I dropped my book.', 'authored'),
  ('st-ex-hazumini-2', 'sent-ex-hazumini-2', 'en', 'As I stood up, I banged into the desk.', 'authored'),
  ('st-ex-hazumini-3', 'sent-ex-hazumini-3', 'en', 'Running in a hurry, I went over.', 'authored'),
  ('st-ex-hazumini-4', 'sent-ex-hazumini-4', 'en', 'As I opened the door, I caught my finger in it.', 'authored'),
  ('st-ex-kiraigaaru-1', 'sent-ex-kiraigaaru-1', 'en', 'He has a tendency to see the worst in things.', 'authored'),
  ('st-ex-kiraigaaru-2', 'sent-ex-kiraigaaru-2', 'en', 'Young people have a tendency to overdo it.', 'authored'),
  ('st-ex-kiraigaaru-3', 'sent-ex-kiraigaaru-3', 'en', 'She has a tendency not to listen.', 'authored'),
  ('st-ex-kiraigaaru-4', 'sent-ex-kiraigaaru-4', 'en', 'He has a tendency to decide on his own.', 'authored'),
  ('st-ex-nitomonatte-1', 'sent-ex-nitomonatte-1', 'en', 'With economic growth, life became more comfortable.', 'authored'),
  ('st-ex-nitomonatte-2', 'sent-ex-nitomonatte-2', 'en', 'As the population rose, so did the problems.', 'authored'),
  ('st-ex-nitomonatte-3', 'sent-ex-nitomonatte-3', 'en', 'As the temperature rose, the snow melted.', 'authored'),
  ('st-ex-nitomonatte-4', 'sent-ex-nitomonatte-4', 'en', 'As you grow older, your body grows weaker.', 'authored'),
  ('st-ex-woyosoni-1', 'sent-ex-woyosoni-1', 'en', 'Ignoring his parents’ worry, he set off travelling.', 'authored'),
  ('st-ex-woyosoni-2', 'sent-ex-woyosoni-2', 'en', 'Ignoring the opposition, they pressed ahead with the plan.', 'authored'),
  ('st-ex-woyosoni-3', 'sent-ex-woyosoni-3', 'en', 'Ignoring the danger, he dived into the river.', 'authored'),
  ('st-ex-woyosoni-4', 'sent-ex-woyosoni-4', 'en', 'Ignoring his family’s hopes, he left the company.', 'authored'),
  ('st-ex-naradewa-1', 'sent-ex-naradewa-1', 'en', 'It is a dish you get only in Japan.', 'authored'),
  ('st-ex-naradewa-2', 'sent-ex-naradewa-2', 'en', 'There are pleasures you get only in winter.', 'authored'),
  ('st-ex-naradewa-3', 'sent-ex-naradewa-3', 'en', 'It is a taste you get only at that shop.', 'authored'),
  ('st-ex-naradewa-4', 'sent-ex-naradewa-4', 'en', 'It is an explanation only that teacher could give.', 'authored'),
  ('st-ex-inagarani-1', 'sent-ex-inagarani-1', 'en', 'You can do the shopping without leaving the house.', 'authored'),
  ('st-ex-inagarani-2', 'sent-ex-inagarani-2', 'en', 'You can see what the world is doing without stirring.', 'authored'),
  ('st-ex-inagarani-3', 'sent-ex-inagarani-3', 'en', 'You can watch a film without leaving your room.', 'authored'),
  ('st-ex-inagarani-4', 'sent-ex-inagarani-4', 'en', 'You can work without leaving the house.', 'authored'),
  ('st-ex-gotoki-1', 'sent-ex-gotoki-1', 'en', 'There are few people like him.', 'authored'),
  ('st-ex-gotoki-2', 'sent-ex-gotoki-2', 'en', 'Someone like me could not manage it.', 'authored'),
  ('st-ex-gotoki-3', 'sent-ex-gotoki-3', 'en', 'It is as cold as ice.', 'authored'),
  ('st-ex-gotoki-4', 'sent-ex-gotoki-4', 'en', 'It is a mountain of luggage.', 'authored'),
  ('st-ex-toshitatte-1', 'sent-ex-toshitatte-1', 'en', 'Even hurrying, I will not make it.', 'authored'),
  ('st-ex-toshitatte-2', 'sent-ex-toshitatte-2', 'en', 'Even if it is expensive, I am buying it.', 'authored'),
  ('st-ex-toshitatte-3', 'sent-ex-toshitatte-3', 'en', 'Even if I had objected, nothing would have changed.', 'authored'),
  ('st-ex-toshitatte-4', 'sent-ex-toshitatte-4', 'en', 'Even if I explained, they would not understand.', 'authored'),
  ('st-ex-nakushite-1', 'sent-ex-nakushite-1', 'en', 'Without effort there is no success.', 'authored'),
  ('st-ex-nakushite-2', 'sent-ex-nakushite-2', 'en', 'Without his help it could not have been done.', 'authored'),
  ('st-ex-nakushite-3', 'sent-ex-nakushite-3', 'en', 'It cannot be started without preparation.', 'authored'),
  ('st-ex-nakushite-4', 'sent-ex-nakushite-4', 'en', 'Without love there is no life.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('to-aimatte', 'sent-ex-toaimatte-1', 0),
  ('to-aimatte', 'sent-ex-toaimatte-2', 1),
  ('to-aimatte', 'sent-ex-toaimatte-3', 2),
  ('to-aimatte', 'sent-ex-toaimatte-4', 3),
  ('hazumi-ni', 'sent-ex-hazumini-1', 0),
  ('hazumi-ni', 'sent-ex-hazumini-2', 1),
  ('hazumi-ni', 'sent-ex-hazumini-3', 2),
  ('hazumi-ni', 'sent-ex-hazumini-4', 3),
  ('kirai-ga-aru', 'sent-ex-kiraigaaru-1', 0),
  ('kirai-ga-aru', 'sent-ex-kiraigaaru-2', 1),
  ('kirai-ga-aru', 'sent-ex-kiraigaaru-3', 2),
  ('kirai-ga-aru', 'sent-ex-kiraigaaru-4', 3),
  ('ni-tomonatte', 'sent-ex-nitomonatte-1', 0),
  ('ni-tomonatte', 'sent-ex-nitomonatte-2', 1),
  ('ni-tomonatte', 'sent-ex-nitomonatte-3', 2),
  ('ni-tomonatte', 'sent-ex-nitomonatte-4', 3),
  ('wo-yoso-ni', 'sent-ex-woyosoni-1', 0),
  ('wo-yoso-ni', 'sent-ex-woyosoni-2', 1),
  ('wo-yoso-ni', 'sent-ex-woyosoni-3', 2),
  ('wo-yoso-ni', 'sent-ex-woyosoni-4', 3),
  ('to-wa-ie-mono-no', 'sent-ex-naradewa-1', 0),
  ('to-wa-ie-mono-no', 'sent-ex-naradewa-2', 1),
  ('to-wa-ie-mono-no', 'sent-ex-naradewa-3', 2),
  ('to-wa-ie-mono-no', 'sent-ex-naradewa-4', 3),
  ('inagara-ni-shite', 'sent-ex-inagarani-1', 0),
  ('inagara-ni-shite', 'sent-ex-inagarani-2', 1),
  ('inagara-ni-shite', 'sent-ex-inagarani-3', 2),
  ('inagara-ni-shite', 'sent-ex-inagarani-4', 3),
  ('gotoki', 'sent-ex-gotoki-1', 0),
  ('gotoki', 'sent-ex-gotoki-2', 1),
  ('gotoki', 'sent-ex-gotoki-3', 2),
  ('gotoki', 'sent-ex-gotoki-4', 3),
  ('to-ittatte', 'sent-ex-toshitatte-1', 0),
  ('to-ittatte', 'sent-ex-toshitatte-2', 1),
  ('to-ittatte', 'sent-ex-toshitatte-3', 2),
  ('to-ittatte', 'sent-ex-toshitatte-4', 3),
  ('nakushite', 'sent-ex-nakushite-1', 0),
  ('nakushite', 'sent-ex-nakushite-2', 1),
  ('nakushite', 'sent-ex-nakushite-3', 2),
  ('nakushite', 'sent-ex-nakushite-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-toaimatte-1', 'sent-ex-toaimatte-2', 'sent-ex-toaimatte-3', 'sent-ex-toaimatte-4', 'sent-ex-hazumini-1', 'sent-ex-hazumini-2', 'sent-ex-hazumini-3', 'sent-ex-hazumini-4', 'sent-ex-kiraigaaru-1', 'sent-ex-kiraigaaru-2', 'sent-ex-kiraigaaru-3', 'sent-ex-kiraigaaru-4', 'sent-ex-nitomonatte-1', 'sent-ex-nitomonatte-2', 'sent-ex-nitomonatte-3', 'sent-ex-nitomonatte-4', 'sent-ex-woyosoni-1', 'sent-ex-woyosoni-2', 'sent-ex-woyosoni-3', 'sent-ex-woyosoni-4', 'sent-ex-naradewa-1', 'sent-ex-naradewa-2', 'sent-ex-naradewa-3', 'sent-ex-naradewa-4', 'sent-ex-inagarani-1', 'sent-ex-inagarani-2', 'sent-ex-inagarani-3', 'sent-ex-inagarani-4', 'sent-ex-gotoki-1', 'sent-ex-gotoki-2', 'sent-ex-gotoki-3', 'sent-ex-gotoki-4', 'sent-ex-toshitatte-1', 'sent-ex-toshitatte-2', 'sent-ex-toshitatte-3', 'sent-ex-toshitatte-4', 'sent-ex-nakushite-1', 'sent-ex-nakushite-2', 'sent-ex-nakushite-3', 'sent-ex-nakushite-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 0, '良い', 'よい', (select id from words where primary_form = '良い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"良","r":"よ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 1, '天気', 'てんき', (select id from words where primary_form = '天気' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"天気","r":"てんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 2, 'と相まって', 'とあいまって', NULL, 4, 9, '[{"t":"と"},{"t":"相","r":"あい"},{"t":"まって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 3, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 4, '楽しい', 'たのしい', (select id from words where primary_form = '楽しい' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"楽","r":"たの"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 5, '旅行', 'りょこう', (select id from words where primary_form = '旅行' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"旅行","r":"りょこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 6, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 15, 16, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 7, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 16, 19, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-1', 8, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-2', 0, '才能', 'さいのう', (select id from words where primary_form = '才能' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"才能","r":"さいのう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-2', 2, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-2', 3, 'と相まって', 'とあいまって', NULL, 5, 10, '[{"t":"と"},{"t":"相","r":"あい"},{"t":"まって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-2', 4, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-2', 5, '成功した', 'せいこうした', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"成功","r":"せいこう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-2', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-3', 0, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-3', 1, 'と相まって', 'とあいまって', NULL, 2, 7, '[{"t":"と"},{"t":"相","r":"あい"},{"t":"まって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-3', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-3', 3, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-3', 5, '良かった', 'よかった', (select id from words where primary_form = '良し悪し' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"良","r":"よ"},{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-3', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 1, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 2, 'と相まって', 'とあいまって', NULL, 4, 9, '[{"t":"と"},{"t":"相","r":"あい"},{"t":"まって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 3, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 4, '人気', 'にんき', (select id from words where primary_form = '人気' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"人気","r":"にんき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 5, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 6, '出ました', 'でました', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"出","r":"で"},{"t":"ました"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toaimatte-4', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-1', 0, '転んだ', 'ころんだ', (select id from words where primary_form = '転ぶ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"転","r":"ころ"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-1', 1, 'はずみに', 'はずみに', NULL, 3, 7, '[{"t":"はずみに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-1', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-1', 3, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-1', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-1', 5, '落とした', 'おとした', (select id from words where primary_form = '落とす' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"落","r":"お"},{"t":"とした"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-2', 0, '立ち上がった', 'たちあがった', (select id from words where primary_form = '立ち上がる' and language_id = 'lang-ja' and published order by id limit 1), 0, 6, '[{"t":"立","r":"た"},{"t":"ち"},{"t":"上","r":"あ"},{"t":"がった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-2', 1, 'はずみに', 'はずみに', NULL, 6, 10, '[{"t":"はずみに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-2', 2, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-2', 3, '机', 'つくえ', (select id from words where primary_form = '机' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-2', 5, 'ぶつかった', 'ぶつかった', (select id from words where primary_form = 'ぶつかる' and language_id = 'lang-ja' and published order by id limit 1), 13, 18, '[{"t":"ぶつかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-2', 6, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-3', 0, '急いで', 'いそいで', (select id from words where primary_form = '急ぐ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"急","r":"いそ"},{"t":"いで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-3', 1, '走った', 'はしった', (select id from words where primary_form = '走る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"走","r":"はし"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-3', 2, 'はずみに', 'はずみに', NULL, 6, 10, '[{"t":"はずみに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-3', 3, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-3', 4, '転んだ', 'ころんだ', (select id from words where primary_form = '転ぶ' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"転","r":"ころ"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-3', 5, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 0, 'ドア', 'ドア', (select id from words where primary_form = 'ドア' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"ドア"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 2, '開けた', 'あけた', (select id from words where primary_form = '開ける' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"開","r":"あ"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 3, 'はずみに', 'はずみに', NULL, 6, 10, '[{"t":"はずみに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 4, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 5, '指', 'ゆび', (select id from words where primary_form = '指' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"指","r":"ゆび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 6, 'を', 'を', NULL, 12, 13, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 7, '挟んだ', 'はさんだ', (select id from words where primary_form = '挟む' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"挟","r":"はさ"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hazumini-4', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 2, '物事', 'ものごと', (select id from words where primary_form = '物事' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"物事","r":"ものごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 4, '悪', 'わる', (select id from words where primary_form = '悪' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"悪","r":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 5, 'く', 'く', NULL, 6, 7, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 6, '考える', 'かんがえる', (select id from words where primary_form = '考える' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"考","r":"かんが"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 7, 'きらいがある', 'きらいがある', NULL, 10, 16, '[{"t":"きらいがある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-1', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 0, '若い', 'わかい', (select id from words where primary_form = '若い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"若","r":"わか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 1, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 3, '無理', 'むり', (select id from words where primary_form = '無理' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"無理","r":"むり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 4, 'を', 'を', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 5, 'する', 'する', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 6, 'きらいがある', 'きらいがある', NULL, 9, 15, '[{"t":"きらいがある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 0, '彼女', 'かのじょ', (select id from words where primary_form = '彼女' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼女","r":"かのじょ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 2, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 4, '話', 'はなし', (select id from words where primary_form = '話' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"話","r":"はなし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 5, 'を', 'を', NULL, 6, 7, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 6, '聞かない', 'きかない', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"聞","r":"き"},{"t":"かない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 7, 'きらいがある', 'きらいがある', NULL, 11, 17, '[{"t":"きらいがある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-3', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-4', 2, '一人', 'ひとり', (select id from words where primary_form = '一人' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"一人","r":"ひとり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-4', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-4', 4, '決める', 'きめる', (select id from words where primary_form = '決める' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"決","r":"き"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-4', 5, 'きらいがある', 'きらいがある', NULL, 8, 14, '[{"t":"きらいがある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kiraigaaru-4', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 0, '経済', 'けいざい', (select id from words where primary_form = '経済' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経済","r":"けいざい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 2, '成長', 'せいちょう', (select id from words where primary_form = '成長' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"成長","r":"せいちょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 4, '伴って', 'ともなって', (select id from words where primary_form = '伴う' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"伴","r":"ともな"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 5, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 6, '生活', 'せいかつ', (select id from words where primary_form = '生活' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"生活","r":"せいかつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 7, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 8, '豊か', 'ゆたか', (select id from words where primary_form = '豊か' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"豊","r":"ゆた"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 9, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 15, 16, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 10, 'なった', 'なった', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 16, 19, '[{"t":"なった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-1', 11, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 0, '人口', 'じんこう', (select id from words where primary_form = '人口' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"人口","r":"じんこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 2, '増える', 'ふえる', (select id from words where primary_form = '増える' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"増","r":"ふ"},{"t":"える"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 4, '伴って', 'ともなって', (select id from words where primary_form = '伴う' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"伴","r":"ともな"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 5, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 6, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 7, 'も', 'も', NULL, 13, 14, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 8, '増えた', 'ふえた', (select id from words where primary_form = '増える' and language_id = 'lang-ja' and published order by id limit 1), 14, 17, '[{"t":"増","r":"ふ"},{"t":"えた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-2', 9, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 0, '気温', 'きおん', (select id from words where primary_form = '気温' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"気温","r":"きおん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 2, '上がる', 'あがる', (select id from words where primary_form = '上がる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"上","r":"あ"},{"t":"がる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 4, '伴って', 'ともなって', (select id from words where primary_form = '伴う' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"伴","r":"ともな"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 5, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 6, '雪', 'ゆき', (select id from words where primary_form = '雪' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"雪","r":"ゆき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 7, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 8, '溶けた', 'とけた', (select id from words where primary_form = '溶ける' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"溶","r":"と"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-3', 9, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 0, '年', 'とし', (select id from words where primary_form = '年' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"年","r":"とし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 2, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 3, 'る', 'る', NULL, 3, 4, '[{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 5, '伴って', 'ともなって', (select id from words where primary_form = '伴う' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"伴","r":"ともな"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 6, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 7, '体', 'からだ', (select id from words where primary_form = '体' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"体","r":"からだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 8, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 9, '弱', 'よわ', (select id from words where primary_form = '弱' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"弱","r":"よわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 10, 'く', 'く', NULL, 12, 13, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 11, 'なる', 'なる', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"なる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nitomonatte-4', 12, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 0, '親', 'おや', (select id from words where primary_form = '親' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"親","r":"おや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 2, '心配', 'しんぱい', (select id from words where primary_form = '心配' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"心配","r":"しんぱい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 4, 'よそ', 'よそ', (select id from words where primary_form = '余所' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"よそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 6, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 7, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 8, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 9, '旅', 'たび', (select id from words where primary_form = '旅' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"旅","r":"たび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 10, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 11, '出た', 'でた', (select id from words where primary_form = '出る' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"出","r":"で"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-1', 12, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 0, '反対', 'はんたい', (select id from words where primary_form = '反対' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"反対","r":"はんたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 2, 'よそ', 'よそ', (select id from words where primary_form = '余所' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"よそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 4, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 5, '計画', 'けいかく', (select id from words where primary_form = '計画' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"計画","r":"けいかく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 6, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 7, '進めた', 'すすめた', (select id from words where primary_form = '進める' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"進","r":"すす"},{"t":"めた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-2', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 0, '危険', 'きけん', (select id from words where primary_form = '危険' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"危険","r":"きけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 2, 'よそ', 'よそ', (select id from words where primary_form = '余所' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"よそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 4, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 5, '川', 'かわ', (select id from words where primary_form = '川' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"川","r":"かわ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 6, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 7, '飛び込んだ', 'とびこんだ', (select id from words where primary_form = '飛び込む' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"飛","r":"と"},{"t":"び"},{"t":"込","r":"こ"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-3', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 0, '家族', 'かぞく', (select id from words where primary_form = '家族' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"家族","r":"かぞく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 1, 'の', 'の', NULL, 2, 3, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 2, '期待', 'きたい', (select id from words where primary_form = '期待' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"期待","r":"きたい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 3, 'を', 'を', NULL, 5, 6, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 4, 'よそ', 'よそ', (select id from words where primary_form = '余所' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"よそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 5, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 6, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 7, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 8, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 9, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 10, 'を', 'を', NULL, 14, 15, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 11, '辞めた', 'やめた', (select id from words where primary_form = '辞める' and language_id = 'lang-ja' and published order by id limit 1), 15, 18, '[{"t":"辞","r":"や"},{"t":"めた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-woyosoni-4', 12, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-1', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-1', 1, 'ならでは', 'ならでは', NULL, 2, 6, '[{"t":"ならでは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-1', 2, 'の', 'の', NULL, 6, 7, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-1', 3, '料理', 'りょうり', (select id from words where primary_form = '料理' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"料理","r":"りょうり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-1', 4, 'です', 'です', NULL, 9, 11, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-2', 0, '冬', 'ふゆ', (select id from words where primary_form = '冬' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"冬","r":"ふゆ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-2', 1, 'ならでは', 'ならでは', NULL, 1, 5, '[{"t":"ならでは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-2', 2, 'の', 'の', NULL, 5, 6, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-2', 3, '楽しみ', 'たのしみ', (select id from words where primary_form = '楽しみ' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"楽","r":"たの"},{"t":"しみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-2', 4, 'が', 'が', NULL, 9, 10, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-2', 5, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-3', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-3', 1, '店', 'みせ', (select id from words where primary_form = '店' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"店","r":"みせ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-3', 2, 'ならでは', 'ならでは', NULL, 3, 7, '[{"t":"ならでは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-3', 3, 'の', 'の', NULL, 7, 8, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-3', 4, '味', 'あじ', (select id from words where primary_form = '味' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"味","r":"あじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-3', 5, 'だ', 'だ', NULL, 9, 10, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-3', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-4', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-4', 1, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-4', 2, 'ならでは', 'ならでは', NULL, 4, 8, '[{"t":"ならでは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-4', 3, 'の', 'の', NULL, 8, 9, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-4', 4, '説明', 'せつめい', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"説明","r":"せつめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-4', 5, 'だ', 'だ', NULL, 11, 12, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-naradewa-4', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-1', 0, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-1', 2, 'いながらにして', 'いながらにして', NULL, 2, 9, '[{"t":"いながらにして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-1', 3, '買い物', 'かいもの', (select id from words where primary_form = '買い物' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"買","r":"か"},{"t":"い"},{"t":"物","r":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-1', 4, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-1', 5, 'できる', 'できる', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"できる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-1', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-2', 0, 'いながらにして', 'いながらにして', NULL, 0, 7, '[{"t":"いながらにして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-2', 1, '世界', 'せかい', (select id from words where primary_form = '世界' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"世界","r":"せかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-2', 2, 'の', 'の', NULL, 9, 10, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-2', 3, '様子', 'ようす', (select id from words where primary_form = '様子' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"様子","r":"ようす"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-2', 4, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-2', 5, '分かる', 'わかる', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"分","r":"わ"},{"t":"かる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-2', 6, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-3', 0, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-3', 2, 'いながらにして', 'いながらにして', NULL, 3, 10, '[{"t":"いながらにして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-3', 3, '映画', 'えいが', (select id from words where primary_form = '映画' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"映画","r":"えいが"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-3', 4, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-3', 5, '見られる', 'みられる', (select id from words where primary_form = '見る' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"見","r":"み"},{"t":"られる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-3', 6, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 0, '家', 'いえ', (select id from words where primary_form = '家' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"家","r":"いえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 2, 'いながらにして', 'いながらにして', NULL, 2, 9, '[{"t":"いながらにして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 3, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 4, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 5, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 6, 'き', 'き', NULL, 13, 14, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 7, 'ます', 'ます', NULL, 14, 16, '[{"t":"ます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-inagarani-4', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-1', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-1', 1, 'ごとき', 'ごとき', NULL, 2, 5, '[{"t":"ごとき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-1', 2, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-1', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-1', 4, '少ない', 'すくない', (select id from words where primary_form = '少ない' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"少","r":"すく"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-2', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-2', 1, 'ごとき', 'ごとき', NULL, 1, 4, '[{"t":"ごとき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-2', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-2', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-2', 4, '無理', 'むり', (select id from words where primary_form = '無理' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"無理","r":"むり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-2', 5, 'です', 'です', NULL, 8, 10, '[{"t":"です"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-2', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-3', 0, '氷', 'こおり', (select id from words where primary_form = '氷' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"氷","r":"こおり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-3', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-3', 2, '如', 'ごと', NULL, 2, 3, '[{"t":"如","r":"ごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-3', 3, 'く', 'く', NULL, 3, 4, '[{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-3', 4, '冷たい', 'つめたい', (select id from words where primary_form = '冷たい' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"冷","r":"つめ"},{"t":"たい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-3', 5, '。', '。', NULL, 7, 8, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-4', 0, '山', 'やま', (select id from words where primary_form = '山' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"山","r":"やま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-4', 1, 'の', 'の', NULL, 1, 2, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-4', 2, 'ごとき', 'ごとき', NULL, 2, 5, '[{"t":"ごとき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-4', 3, '荷物', 'にもつ', (select id from words where primary_form = '荷物' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"荷物","r":"にもつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-4', 4, 'だ', 'だ', NULL, 7, 8, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gotoki-4', 5, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-1', 0, '急いだ', 'いそいだ', (select id from words where primary_form = '急ぐ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"急","r":"いそ"},{"t":"いだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-1', 1, 'としたって', 'としたって', NULL, 3, 8, '[{"t":"としたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-1', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-1', 3, '間に合わない', 'まにあわない', (select id from words where primary_form = '間に合う' and language_id = 'lang-ja' and published order by id limit 1), 9, 15, '[{"t":"間","r":"ま"},{"t":"に"},{"t":"合","r":"あ"},{"t":"わない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-1', 4, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-2', 0, '高い', 'たかい', (select id from words where primary_form = '高い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"高","r":"たか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-2', 1, 'としたって', 'としたって', NULL, 2, 7, '[{"t":"としたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-2', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-2', 3, '買います', 'かいます', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"買","r":"か"},{"t":"います"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-2', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-3', 0, '反対した', 'はんたいした', (select id from words where primary_form = '反対' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"反対","r":"はんたい"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-3', 1, 'としたって', 'としたって', NULL, 4, 9, '[{"t":"としたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-3', 2, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-3', 3, '変わらない', 'かわらない', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"変","r":"か"},{"t":"わらない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-3', 4, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-4', 0, '説明した', 'せつめいした', (select id from words where primary_form = '説明' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"説明","r":"せつめい"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-4', 1, 'としたって', 'としたって', NULL, 4, 9, '[{"t":"としたって"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-4', 2, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-4', 3, '分からない', 'わからない', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"分","r":"わ"},{"t":"からない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-4', 4, 'だろう', 'だろう', NULL, 15, 18, '[{"t":"だろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-toshitatte-4', 5, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-1', 0, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-1', 1, 'なくして', 'なくして', NULL, 2, 6, '[{"t":"なくして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-1', 2, '成功', 'せいこう', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"成功","r":"せいこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-1', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-1', 4, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-1', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 0, '彼の', 'かれの', (select id from words where primary_form = '彼の' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"彼","r":"かれ"},{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 1, '協力', 'きょうりょく', (select id from words where primary_form = '協力' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"協力","r":"きょうりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 2, 'なくして', 'なくして', NULL, 4, 8, '[{"t":"なくして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 5, 'き', 'き', NULL, 10, 11, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 6, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-3', 0, '準備', 'じゅんび', (select id from words where primary_form = '準備' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"準備","r":"じゅんび"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-3', 1, 'なくして', 'なくして', NULL, 2, 6, '[{"t":"なくして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-3', 2, '始められません', 'はじめられません', (select id from words where primary_form = '始める' and language_id = 'lang-ja' and published order by id limit 1), 6, 13, '[{"t":"始","r":"はじ"},{"t":"められません"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-3', 3, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-4', 0, '愛', 'あい', (select id from words where primary_form = '愛' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"愛","r":"あい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-4', 1, 'なくして', 'なくして', NULL, 1, 5, '[{"t":"なくして"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-4', 2, '人生', 'じんせい', (select id from words where primary_form = '人生' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"人生","r":"じんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-4', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-4', 4, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nakushite-4', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb);
