-- N1 example sentences, batch 4: emphasis, concession, and listing.
--
-- 〜もさることながら, 〜にして, 〜と思いきや, 〜にあらず, 〜ばこそ, 〜であれ,
-- 〜なり〜なり, 〜だの〜だの, 〜つ〜つ and 〜ことなく.
--
-- THREE TOPICS SKIPPED, and the reason is the same each time — the pattern
-- itself ends in a particle, or is bare kana the index does not hold:
--
--   〜ところを (tokoro-wo): the glossary loads grammar PATTERNS as entries, so
--   ところを is matched whole and glossed correctly — and `check:examples`
--   then reports "particle swallowed", because its rule is that a multi-
--   character token ending in を with a gloss is a mistake. Here it is not,
--   but every sentence the topic can have trips it, so none can be validated.
--
--   〜うが〜まいが (you-ga-you-ga): same trap on まいが, and worse — 食べまいが
--   was matched as a form of 食べる and glossed "to eat".
--
--   〜まい (mai): まい alone shreds to ま|い in every position tried —
--   来るまい, 降るまい, 言うまい, あるまい, 行くまいと.
--
-- 〜だの〜だの, 〜つ〜つ and 〜ことなく were brought forward from 441-443 in
-- their place. Note that 〜つ〜つ survives only as its set phrases —
-- 行きつ戻りつ and 持ちつ持たれつ — which is all the pattern really has.
--
-- Two rewordings: 難しかった shredded to 難|しか|っ|た (the same past-tense
-- gap batch 3 hit on 楽しかった), and この shreds to こ|の.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- mo-sarukoto-nagara
  ('sent-ex-sarukoto-1', 'lang-ja', '味もさることながら、値段も安い。', 'あじ も さることながら、ねだん も やすい。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-sarukoto-2', 'lang-ja', '才能もさることながら、努力が大切だ。', 'さいのう も さることながら、どりょく が たいせつ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-sarukoto-3', 'lang-ja', 'デザインもさることながら、使いやすい。', 'デザイン も さることながら、つかいやすい。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-sarukoto-4', 'lang-ja', '経験もさることながら、人柄が重要だ。', 'けいけん も さることながら、ひとがら が じゅうよう だ。', 'lvl-ja-n1', 'authored', true),
  -- ni-shite
  ('sent-ex-nishite-1', 'lang-ja', '彼にして初めてできることだ。', 'かれ に して はじめて できる こと だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nishite-2', 'lang-ja', '今にして思えば、間違いだった。', 'いま に して おもえば、まちがい だった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nishite-3', 'lang-ja', '町は一日にして変わった。', 'まち わ いちにち に して かわった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nishite-4', 'lang-ja', '先生にして分からない問題だ。', 'せんせい に して わからない もんだい だ。', 'lvl-ja-n1', 'authored', true),
  -- to-omoikiya
  ('sent-ex-omoikiya-1', 'lang-ja', '晴れると思いきや、雨が降った。', 'はれる と おもいきや、あめ が ふった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-omoikiya-2', 'lang-ja', '簡単だと思いきや、時間がかかった。', 'かんたん だ と おもいきや、じかん が かかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-omoikiya-3', 'lang-ja', '来ないと思いきや、彼が来た。', 'こない と おもいきや、かれ が きた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-omoikiya-4', 'lang-ja', '安いと思いきや、高かった。', 'やすい と おもいきや、たかかった。', 'lvl-ja-n1', 'authored', true),
  -- ni-arazu
  ('sent-ex-niarazu-1', 'lang-ja', 'これは冗談にあらず。', 'これ わ じょうだん に あらず。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-niarazu-2', 'lang-ja', '彼は普通の人にあらず。', 'かれ わ ふつう の ひと に あらず。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-niarazu-3', 'lang-ja', '成功は偶然にあらず。', 'せいこう わ ぐうぜん に あらず。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-niarazu-4', 'lang-ja', 'これは夢にあらず。', 'これ わ ゆめ に あらず。', 'lvl-ja-n1', 'authored', true),
  -- ba-koso
  ('sent-ex-bakoso-1', 'lang-ja', '努力すればこそ成功する。', 'どりょく すれば こそ せいこう する。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-bakoso-2', 'lang-ja', '大切に思えばこそ、厳しく言う。', 'たいせつ に おもえば こそ、きびしく いう。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-bakoso-3', 'lang-ja', '体が丈夫であればこそ働ける。', 'からだ が じょうぶ で あれば こそ はたらける。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-bakoso-4', 'lang-ja', '彼がいればこそ、会社がある。', 'かれ が いれば こそ、かいしゃ が ある。', 'lvl-ja-n1', 'authored', true),
  -- de-are
  ('sent-ex-deare-1', 'lang-ja', '子供であれ大人であれ、規則は同じだ。', 'こども で あれ おとな で あれ、きそく わ おなじ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-deare-2', 'lang-ja', 'どんな理由であれ、遅刻は困る。', 'どんな りゆう で あれ、ちこく わ こまる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-deare-3', 'lang-ja', '先生であれ、間違いはある。', 'せんせい で あれ、まちがい わ ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-deare-4', 'lang-ja', '雨であれ雪であれ、行きます。', 'あめ で あれ ゆき で あれ、いきます。', 'lvl-ja-n1', 'authored', true),
  -- nari-nari
  ('sent-ex-narinari-1', 'lang-ja', '電話するなり手紙を書くなり、連絡してください。', 'でんわ する なり てがみ お かく なり、れんらく して ください。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-narinari-2', 'lang-ja', '本を読むなり音楽を聞くなり、自由にしてください。', 'ほん お よむ なり おんがく お きく なり、じゆう に して ください。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-narinari-3', 'lang-ja', '肉なり魚なり、好きなものを選んでください。', 'にく なり さかな なり、すき な もの お えらんで ください。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-narinari-4', 'lang-ja', '先生なり親なり、誰かに相談してください。', 'せんせい なり おや なり、だれか に そうだん して ください。', 'lvl-ja-n1', 'authored', true),
  -- dano
  ('sent-ex-dano-1', 'lang-ja', '暑いだの寒いだの、文句ばかり言う。', 'あつい だの さむい だの、もんく ばかり いう。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-dano-2', 'lang-ja', '肉だの魚だの、全部買った。', 'にく だの さかな だの、ぜんぶ かった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-dano-3', 'lang-ja', '忙しいだの疲れただの、言い訳が多い。', 'いそがしい だの つかれた だの、いいわけ が おおい。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-dano-4', 'lang-ja', '本だのノートだの、机の上に置いてある。', 'ほん だの ノート だの、つくえ の うえ に おいて ある。', 'lvl-ja-n1', 'authored', true),
  -- tsu-tsu
  ('sent-ex-tsutsutsu-1', 'lang-ja', '彼は部屋を行きつ戻りつしている。', 'かれ わ へや お いきつ もどりつ して いる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tsutsutsu-2', 'lang-ja', '行きつ戻りつ、答えを考えた。', 'いきつ もどりつ、こたえ お かんがえた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tsutsutsu-3', 'lang-ja', '持ちつ持たれつの関係だ。', 'もちつ もたれつ の かんけい だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tsutsutsu-4', 'lang-ja', '人は持ちつ持たれつで生きている。', 'ひと わ もちつ もたれつ で いきて いる。', 'lvl-ja-n1', 'authored', true),
  -- koto-naku
  ('sent-ex-kotonaku-1', 'lang-ja', '休むことなく働いた。', 'やすむ こと なく はたらいた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kotonaku-2', 'lang-ja', '諦めることなく続けた。', 'あきらめる こと なく つづけた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kotonaku-3', 'lang-ja', '変わることなく、昔のままだ。', 'かわる こと なく、むかし の まま だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-kotonaku-4', 'lang-ja', '彼は迷うことなく決めた。', 'かれ わ まよう こと なく きめた。', 'lvl-ja-n1', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-sarukoto-1', 'sent-ex-sarukoto-1', 'en', 'The taste aside, it is cheap as well.', 'authored'),
  ('st-ex-sarukoto-2', 'sent-ex-sarukoto-2', 'en', 'Talent aside, it is effort that matters.', 'authored'),
  ('st-ex-sarukoto-3', 'sent-ex-sarukoto-3', 'en', 'The design aside, it is easy to use.', 'authored'),
  ('st-ex-sarukoto-4', 'sent-ex-sarukoto-4', 'en', 'Experience aside, character is what counts.', 'authored'),
  ('st-ex-nishite-1', 'sent-ex-nishite-1', 'en', 'It is something only he could do.', 'authored'),
  ('st-ex-nishite-2', 'sent-ex-nishite-2', 'en', 'Looking back on it now, it was a mistake.', 'authored'),
  ('st-ex-nishite-3', 'sent-ex-nishite-3', 'en', 'The town changed in a single day.', 'authored'),
  ('st-ex-nishite-4', 'sent-ex-nishite-4', 'en', 'It is a problem even a teacher cannot solve.', 'authored'),
  ('st-ex-omoikiya-1', 'sent-ex-omoikiya-1', 'en', 'I thought it would clear up, and instead it rained.', 'authored'),
  ('st-ex-omoikiya-2', 'sent-ex-omoikiya-2', 'en', 'I thought it would be simple, and it took ages.', 'authored'),
  ('st-ex-omoikiya-3', 'sent-ex-omoikiya-3', 'en', 'I thought he would not come, and there he was.', 'authored'),
  ('st-ex-omoikiya-4', 'sent-ex-omoikiya-4', 'en', 'I thought it was cheap, and it was expensive.', 'authored'),
  ('st-ex-niarazu-1', 'sent-ex-niarazu-1', 'en', 'This is no joke.', 'authored'),
  ('st-ex-niarazu-2', 'sent-ex-niarazu-2', 'en', 'He is no ordinary man.', 'authored'),
  ('st-ex-niarazu-3', 'sent-ex-niarazu-3', 'en', 'Success is no accident.', 'authored'),
  ('st-ex-niarazu-4', 'sent-ex-niarazu-4', 'en', 'This is no dream.', 'authored'),
  ('st-ex-bakoso-1', 'sent-ex-bakoso-1', 'en', 'It is precisely because you work at it that you succeed.', 'authored'),
  ('st-ex-bakoso-2', 'sent-ex-bakoso-2', 'en', 'It is because I care that I speak sharply.', 'authored'),
  ('st-ex-bakoso-3', 'sent-ex-bakoso-3', 'en', 'It is only because I am in good health that I can work.', 'authored'),
  ('st-ex-bakoso-4', 'sent-ex-bakoso-4', 'en', 'It is thanks to him alone that this company exists.', 'authored'),
  ('st-ex-deare-1', 'sent-ex-deare-1', 'en', 'Child or adult, the rules are the same.', 'authored'),
  ('st-ex-deare-2', 'sent-ex-deare-2', 'en', 'Whatever the reason, being late is a nuisance.', 'authored'),
  ('st-ex-deare-3', 'sent-ex-deare-3', 'en', 'Even a teacher makes mistakes.', 'authored'),
  ('st-ex-deare-4', 'sent-ex-deare-4', 'en', 'Rain or snow, I am going.', 'authored'),
  ('st-ex-narinari-1', 'sent-ex-narinari-1', 'en', 'Ring me or write to me — get in touch somehow.', 'authored'),
  ('st-ex-narinari-2', 'sent-ex-narinari-2', 'en', 'Read a book, listen to music, do as you please.', 'authored'),
  ('st-ex-narinari-3', 'sent-ex-narinari-3', 'en', 'Meat or fish — take whichever you like.', 'authored'),
  ('st-ex-narinari-4', 'sent-ex-narinari-4', 'en', 'Talk to a teacher, or your parents, or somebody.', 'authored'),
  ('st-ex-dano-1', 'sent-ex-dano-1', 'en', 'Too hot, too cold — nothing but complaints.', 'authored'),
  ('st-ex-dano-2', 'sent-ex-dano-2', 'en', 'Meat and fish and the rest of it — I bought the lot.', 'authored'),
  ('st-ex-dano-3', 'sent-ex-dano-3', 'en', 'Busy, tired — he is full of excuses.', 'authored'),
  ('st-ex-dano-4', 'sent-ex-dano-4', 'en', 'Books and notebooks and what have you are all over the desk.', 'authored'),
  ('st-ex-tsutsutsu-1', 'sent-ex-tsutsutsu-1', 'en', 'He is pacing up and down the room.', 'authored'),
  ('st-ex-tsutsutsu-2', 'sent-ex-tsutsutsu-2', 'en', 'Going back and forth over it, I worked out the answer.', 'authored'),
  ('st-ex-tsutsutsu-3', 'sent-ex-tsutsutsu-3', 'en', 'It is a give-and-take relationship.', 'authored'),
  ('st-ex-tsutsutsu-4', 'sent-ex-tsutsutsu-4', 'en', 'People live by give and take.', 'authored'),
  ('st-ex-kotonaku-1', 'sent-ex-kotonaku-1', 'en', 'He worked without a break.', 'authored'),
  ('st-ex-kotonaku-2', 'sent-ex-kotonaku-2', 'en', 'He kept at it without giving up.', 'authored'),
  ('st-ex-kotonaku-3', 'sent-ex-kotonaku-3', 'en', 'It is unchanged, just as it was.', 'authored'),
  ('st-ex-kotonaku-4', 'sent-ex-kotonaku-4', 'en', 'He decided without a moment’s hesitation.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('mo-sarukoto-nagara', 'sent-ex-sarukoto-1', 0),
  ('mo-sarukoto-nagara', 'sent-ex-sarukoto-2', 1),
  ('mo-sarukoto-nagara', 'sent-ex-sarukoto-3', 2),
  ('mo-sarukoto-nagara', 'sent-ex-sarukoto-4', 3),
  ('ni-shite', 'sent-ex-nishite-1', 0),
  ('ni-shite', 'sent-ex-nishite-2', 1),
  ('ni-shite', 'sent-ex-nishite-3', 2),
  ('ni-shite', 'sent-ex-nishite-4', 3),
  ('to-omoikiya', 'sent-ex-omoikiya-1', 0),
  ('to-omoikiya', 'sent-ex-omoikiya-2', 1),
  ('to-omoikiya', 'sent-ex-omoikiya-3', 2),
  ('to-omoikiya', 'sent-ex-omoikiya-4', 3),
  ('ni-arazu', 'sent-ex-niarazu-1', 0),
  ('ni-arazu', 'sent-ex-niarazu-2', 1),
  ('ni-arazu', 'sent-ex-niarazu-3', 2),
  ('ni-arazu', 'sent-ex-niarazu-4', 3),
  ('ba-koso', 'sent-ex-bakoso-1', 0),
  ('ba-koso', 'sent-ex-bakoso-2', 1),
  ('ba-koso', 'sent-ex-bakoso-3', 2),
  ('ba-koso', 'sent-ex-bakoso-4', 3),
  ('de-are', 'sent-ex-deare-1', 0),
  ('de-are', 'sent-ex-deare-2', 1),
  ('de-are', 'sent-ex-deare-3', 2),
  ('de-are', 'sent-ex-deare-4', 3),
  ('nari-nari', 'sent-ex-narinari-1', 0),
  ('nari-nari', 'sent-ex-narinari-2', 1),
  ('nari-nari', 'sent-ex-narinari-3', 2),
  ('nari-nari', 'sent-ex-narinari-4', 3),
  ('dano', 'sent-ex-dano-1', 0),
  ('dano', 'sent-ex-dano-2', 1),
  ('dano', 'sent-ex-dano-3', 2),
  ('dano', 'sent-ex-dano-4', 3),
  ('tsu-tsu', 'sent-ex-tsutsutsu-1', 0),
  ('tsu-tsu', 'sent-ex-tsutsutsu-2', 1),
  ('tsu-tsu', 'sent-ex-tsutsutsu-3', 2),
  ('tsu-tsu', 'sent-ex-tsutsutsu-4', 3),
  ('koto-naku', 'sent-ex-kotonaku-1', 0),
  ('koto-naku', 'sent-ex-kotonaku-2', 1),
  ('koto-naku', 'sent-ex-kotonaku-3', 2),
  ('koto-naku', 'sent-ex-kotonaku-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-sarukoto-1', 'sent-ex-sarukoto-2', 'sent-ex-sarukoto-3', 'sent-ex-sarukoto-4', 'sent-ex-nishite-1', 'sent-ex-nishite-2', 'sent-ex-nishite-3', 'sent-ex-nishite-4', 'sent-ex-omoikiya-1', 'sent-ex-omoikiya-2', 'sent-ex-omoikiya-3', 'sent-ex-omoikiya-4', 'sent-ex-niarazu-1', 'sent-ex-niarazu-2', 'sent-ex-niarazu-3', 'sent-ex-niarazu-4', 'sent-ex-bakoso-1', 'sent-ex-bakoso-2', 'sent-ex-bakoso-3', 'sent-ex-bakoso-4', 'sent-ex-deare-1', 'sent-ex-deare-2', 'sent-ex-deare-3', 'sent-ex-deare-4', 'sent-ex-narinari-1', 'sent-ex-narinari-2', 'sent-ex-narinari-3', 'sent-ex-narinari-4', 'sent-ex-dano-1', 'sent-ex-dano-2', 'sent-ex-dano-3', 'sent-ex-dano-4', 'sent-ex-tsutsutsu-1', 'sent-ex-tsutsutsu-2', 'sent-ex-tsutsutsu-3', 'sent-ex-tsutsutsu-4', 'sent-ex-kotonaku-1', 'sent-ex-kotonaku-2', 'sent-ex-kotonaku-3', 'sent-ex-kotonaku-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-sarukoto-1', 0, '味', 'あじ', (select id from words where primary_form = '味' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"味","r":"あじ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-1', 1, 'もさることながら', 'もさることながら', NULL, 1, 9, '[{"t":"もさることながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-1', 2, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-1', 3, '値段', 'ねだん', (select id from words where primary_form = '値段' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"値段","r":"ねだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-1', 4, 'も', 'も', NULL, 12, 13, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-1', 5, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-1', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 0, '才能', 'さいのう', (select id from words where primary_form = '才能' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"才能","r":"さいのう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 1, 'もさることながら', 'もさることながら', NULL, 2, 10, '[{"t":"もさることながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 2, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 3, '努力', 'どりょく', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"努力","r":"どりょく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 4, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 5, '大切', 'たいせつ', (select id from words where primary_form = '大切' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"大切","r":"たいせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 6, 'だ', 'だ', NULL, 16, 17, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-2', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-3', 0, 'デザイン', 'デザイン', (select id from words where primary_form = 'デザイン' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"デザイン"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-3', 1, 'もさることながら', 'もさることながら', NULL, 4, 12, '[{"t":"もさることながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-3', 2, '、', '、', NULL, 12, 13, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-3', 3, '使いやすい', 'つかいやすい', (select id from words where primary_form = '使う' and language_id = 'lang-ja' and published order by id limit 1), 13, 18, '[{"t":"使","r":"つか"},{"t":"いやすい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-3', 4, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 0, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 1, 'もさることながら', 'もさることながら', NULL, 2, 10, '[{"t":"もさることながら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 2, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 3, '人柄', 'ひとがら', (select id from words where primary_form = '人柄' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"人柄","r":"ひとがら"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 4, 'が', 'が', NULL, 13, 14, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 5, '重要', 'じゅうよう', (select id from words where primary_form = '重要' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"重要","r":"じゅうよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 6, 'だ', 'だ', NULL, 16, 17, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-sarukoto-4', 7, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 2, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 3, '初めて', 'はじめて', (select id from words where primary_form = '初めて' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"初","r":"はじ"},{"t":"めて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 4, 'できる', 'できる', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"できる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 5, 'こと', 'こと', (select id from words where primary_form = '事' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"こと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 6, 'だ', 'だ', NULL, 12, 13, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-1', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-2', 0, '今に', 'いまに', (select id from words where primary_form = '今に' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"今","r":"いま"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-2', 1, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-2', 2, '思えば', 'おもえば', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"思","r":"おも"},{"t":"えば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-2', 3, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-2', 4, '間違い', 'まちがい', (select id from words where primary_form = '間違い' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"間違","r":"まちが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-2', 5, 'だった', 'だった', NULL, 11, 14, '[{"t":"だった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-2', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-3', 0, '町', 'まち', (select id from words where primary_form = '町' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"町","r":"まち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-3', 2, '一日', 'いちにち', (select id from words where primary_form = '一日' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"一日","r":"いちにち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-3', 3, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-3', 4, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-3', 5, '変わった', 'かわった', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"変","r":"か"},{"t":"わった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-3', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-4', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-4', 2, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-4', 3, '分からない', 'わからない', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"分","r":"わ"},{"t":"からない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-4', 4, '問題', 'もんだい', (select id from words where primary_form = '問題' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"問題","r":"もんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-4', 5, 'だ', 'だ', NULL, 12, 13, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishite-4', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-1', 0, '晴れる', 'はれる', (select id from words where primary_form = '晴れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"晴","r":"は"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-1', 1, 'と思いきや', 'とおもいきや', NULL, 3, 8, '[{"t":"と"},{"t":"思","r":"おも"},{"t":"いきや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-1', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-1', 3, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-1', 4, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-1', 5, '降った', 'ふった', (select id from words where primary_form = '降る' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"降","r":"ふ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-1', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 0, '簡単', 'かんたん', (select id from words where primary_form = '簡単' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"簡単","r":"かんたん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 1, 'だ', 'だ', NULL, 2, 3, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 2, 'と思いきや', 'とおもいきや', NULL, 3, 8, '[{"t":"と"},{"t":"思","r":"おも"},{"t":"いきや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 4, '時間', 'じかん', (select id from words where primary_form = '時間' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"時間","r":"じかん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 5, 'が', 'が', NULL, 11, 12, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 6, 'か', 'か', (select id from words where primary_form = 'か' and language_id = 'lang-ja' and published order by id limit 1), 12, 13, '[{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 7, 'かった', 'かった', NULL, 13, 16, '[{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-2', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-3', 0, '来ない', 'こない', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"来","r":"こ"},{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-3', 1, 'と思いきや', 'とおもいきや', NULL, 3, 8, '[{"t":"と"},{"t":"思","r":"おも"},{"t":"いきや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-3', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-3', 3, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-3', 4, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-3', 5, '来た', 'きた', (select id from words where primary_form = '来る' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"来","r":"き"},{"t":"た"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-3', 6, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-4', 0, '安い', 'やすい', (select id from words where primary_form = '安い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"安","r":"やす"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-4', 1, 'と思いきや', 'とおもいきや', NULL, 2, 7, '[{"t":"と"},{"t":"思","r":"おも"},{"t":"いきや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-4', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-4', 3, '高かった', 'たかかった', (select id from words where primary_form = '高まる' and language_id = 'lang-ja' and published order by id limit 1), 8, 12, '[{"t":"高","r":"たか"},{"t":"かった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-omoikiya-4', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-1', 0, 'これは', 'これは', NULL, 0, 3, '[{"t":"これは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-1', 1, '冗談', 'じょうだん', (select id from words where primary_form = '冗談' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"冗談","r":"じょうだん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-1', 2, 'にあらず', 'にあらず', NULL, 5, 9, '[{"t":"にあらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-1', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-2', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-2', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-2', 2, '普通', 'ふつう', (select id from words where primary_form = '普通' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"普通","r":"ふつう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-2', 3, 'の', 'の', NULL, 4, 5, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-2', 4, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-2', 5, 'にあらず', 'にあらず', NULL, 6, 10, '[{"t":"にあらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-2', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-3', 0, '成功', 'せいこう', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"成功","r":"せいこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-3', 2, '偶然', 'ぐうぜん', (select id from words where primary_form = '偶然' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"偶然","r":"ぐうぜん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-3', 3, 'にあらず', 'にあらず', NULL, 5, 9, '[{"t":"にあらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-3', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-4', 0, 'これは', 'これは', NULL, 0, 3, '[{"t":"これは"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-4', 1, '夢', 'ゆめ', (select id from words where primary_form = '夢' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"夢","r":"ゆめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-4', 2, 'にあらず', 'にあらず', NULL, 4, 8, '[{"t":"にあらず"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-niarazu-4', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-1', 0, '努力すれば', 'どりょくすれば', (select id from words where primary_form = '努力' and language_id = 'lang-ja' and published order by id limit 1), 0, 5, '[{"t":"努力","r":"どりょく"},{"t":"すれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-1', 1, 'こそ', 'こそ', NULL, 5, 7, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-1', 2, '成功する', 'せいこうする', (select id from words where primary_form = '成功' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"成功","r":"せいこう"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-1', 3, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 0, '大切', 'たいせつ', (select id from words where primary_form = '大切' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"大切","r":"たいせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 2, '思えば', 'おもえば', (select id from words where primary_form = '思う' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"思","r":"おも"},{"t":"えば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 3, 'こそ', 'こそ', NULL, 6, 8, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 5, '厳しく', 'きびしく', (select id from words where primary_form = '厳しい' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"厳","r":"きび"},{"t":"しく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 6, '言う', 'いう', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"言","r":"い"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-2', 7, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 0, '体', 'からだ', (select id from words where primary_form = '体' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"体","r":"からだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 2, '丈夫', 'じょうぶ', (select id from words where primary_form = '丈夫' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"丈夫","r":"じょうぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 3, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 4, 'あれば', 'あれば', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"あれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 5, 'こそ', 'こそ', NULL, 8, 10, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 6, '働ける', 'はたらける', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"働","r":"はたら"},{"t":"ける"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-3', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 1, 'が', 'が', NULL, 1, 2, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 2, 'いれば', 'いれば', (select id from words where primary_form = '居る' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"いれば"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 3, 'こそ', 'こそ', NULL, 5, 7, '[{"t":"こそ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 4, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 5, '会社', 'かいしゃ', (select id from words where primary_form = '会社' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"会社","r":"かいしゃ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 6, 'が', 'が', NULL, 10, 11, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 7, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-bakoso-4', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 2, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 3, '大人', 'おとな', (select id from words where primary_form = '大人' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"大人","r":"おとな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 5, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 6, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 7, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 8, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 9, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 10, 'だ', 'だ', NULL, 16, 17, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-1', 11, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 0, 'どんな', 'どんな', (select id from words where primary_form = 'どんな' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"どんな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 1, '理由', 'りゆう', (select id from words where primary_form = '理由' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"理由","r":"りゆう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 3, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 5, '遅刻', 'ちこく', (select id from words where primary_form = '遅刻' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"遅刻","r":"ちこく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 6, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 7, '困る', 'こまる', (select id from words where primary_form = '困る' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"困","r":"こま"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-2', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 2, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 4, '間違い', 'まちがい', (select id from words where primary_form = '間違い' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"間違","r":"まちが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 5, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 6, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-3', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 2, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 3, '雪', 'ゆき', (select id from words where primary_form = '雪' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"雪","r":"ゆき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 4, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 5, 'あれ', 'あれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"あれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 6, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 7, '行きます', 'いきます', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"行","r":"い"},{"t":"きます"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-deare-4', 8, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 0, '電話する', 'でんわする', (select id from words where primary_form = '電話' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"電話","r":"でんわ"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 2, 'り', 'り', NULL, 5, 6, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 3, '手紙', 'てがみ', (select id from words where primary_form = '手紙' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"手紙","r":"てがみ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 4, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 5, '書く', 'かく', (select id from words where primary_form = '書く' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"書","r":"か"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 6, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 7, 'り', 'り', NULL, 12, 13, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 8, '、', '、', NULL, 13, 14, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 9, '連絡して', 'れんらくして', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 14, 18, '[{"t":"連絡","r":"れんらく"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 10, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 18, 22, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-1', 11, '。', '。', NULL, 22, 23, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 1, 'を', 'を', NULL, 1, 2, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 2, '読む', 'よむ', (select id from words where primary_form = '読む' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"読","r":"よ"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 3, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 4, 'り', 'り', NULL, 5, 6, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 5, '音楽', 'おんがく', (select id from words where primary_form = '音楽' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"音楽","r":"おんがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 6, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 7, '聞く', 'きく', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"聞","r":"き"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 8, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 9, 'り', 'り', NULL, 12, 13, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 10, '、', '、', NULL, 13, 14, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 11, '自由', 'じゆう', (select id from words where primary_form = '自由' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"自由","r":"じゆう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 12, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 16, 17, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 13, 'して', 'して', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 17, 19, '[{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 14, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 19, 23, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-2', 15, '。', '。', NULL, 23, 24, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 0, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 2, 'り', 'り', NULL, 2, 3, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 3, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 4, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 5, 'り', 'り', NULL, 5, 6, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 6, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 7, '好き', 'すき', (select id from words where primary_form = '好き' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"好","r":"す"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 8, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 9, 'もの', 'もの', (select id from words where primary_form = 'もの' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"もの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 10, 'を', 'を', NULL, 12, 13, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 11, '選んで', 'えらんで', (select id from words where primary_form = '選ぶ' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"選","r":"えら"},{"t":"んで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 12, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 16, 20, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-3', 13, '。', '。', NULL, 20, 21, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 1, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 2, 'り', 'り', NULL, 3, 4, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 3, '親', 'おや', (select id from words where primary_form = '親' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"親","r":"おや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 4, 'な', 'な', (select id from words where primary_form = 'な' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"な"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 5, 'り', 'り', NULL, 6, 7, '[{"t":"り"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 6, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 7, '誰か', 'だれか', (select id from words where primary_form = '誰か' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"誰","r":"だれ"},{"t":"か"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 8, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 9, '相談して', 'そうだんして', (select id from words where primary_form = '相談' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"相談","r":"そうだん"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 10, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 15, 19, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-narinari-4', 11, '。', '。', NULL, 19, 20, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 0, '暑い', 'あつい', (select id from words where primary_form = '暑い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"暑","r":"あつ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 1, 'だの', 'だの', NULL, 2, 4, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 2, '寒い', 'さむい', (select id from words where primary_form = '寒い' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"寒","r":"さむ"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 3, 'だの', 'だの', NULL, 6, 8, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 5, '文句', 'もんく', (select id from words where primary_form = '文句' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"文句","r":"もんく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 6, 'ばかり', 'ばかり', NULL, 11, 14, '[{"t":"ばかり"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 7, '言う', 'いう', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"言","r":"い"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-1', 8, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 0, '肉', 'にく', (select id from words where primary_form = '肉' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"肉","r":"にく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 1, 'だの', 'だの', NULL, 1, 3, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 2, '魚', 'さかな', (select id from words where primary_form = '魚' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"魚","r":"さかな"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 3, 'だの', 'だの', NULL, 4, 6, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 4, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 5, '全部', 'ぜんぶ', (select id from words where primary_form = '全部' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"全部","r":"ぜんぶ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 6, '買った', 'かった', (select id from words where primary_form = '買う' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"買","r":"か"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-2', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 0, '忙しい', 'いそがしい', (select id from words where primary_form = '忙しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"忙","r":"いそが"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 1, 'だの', 'だの', NULL, 3, 5, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 2, '疲れた', 'つかれた', (select id from words where primary_form = '疲れる' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"疲","r":"つか"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 3, 'だの', 'だの', NULL, 8, 10, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 4, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 5, '言い訳', 'いいわけ', (select id from words where primary_form = '言い訳' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"言","r":"い"},{"t":"い"},{"t":"訳","r":"わけ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 6, 'が', 'が', NULL, 14, 15, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 7, '多い', 'おおい', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 15, 17, '[{"t":"多","r":"おお"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-3', 8, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 0, '本', 'ほん', (select id from words where primary_form = '本' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"本","r":"ほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 1, 'だの', 'だの', NULL, 1, 3, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 2, 'ノート', 'ノート', (select id from words where primary_form = 'ノート' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"ノート"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 3, 'だの', 'だの', NULL, 6, 8, '[{"t":"だの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 4, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 5, '机', 'つくえ', (select id from words where primary_form = '机' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"机","r":"つくえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 6, 'の', 'の', NULL, 10, 11, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 7, '上に', 'うえに', NULL, 11, 13, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 8, '置いて', 'おいて', (select id from words where primary_form = '置く' and language_id = 'lang-ja' and published order by id limit 1), 13, 16, '[{"t":"置","r":"お"},{"t":"いて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 9, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 16, 18, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dano-4', 10, '。', '。', NULL, 18, 19, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 2, '部屋', 'へや', (select id from words where primary_form = '部屋' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"部屋","r":"へや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 3, 'を', 'を', NULL, 4, 5, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 4, '行き', 'いき', (select id from words where primary_form = '行き' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"行","r":"い"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 5, 'つ', 'つ', NULL, 7, 8, '[{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 6, '戻りつしている', 'もどりつしている', (select id from words where primary_form = '戻る' and language_id = 'lang-ja' and published order by id limit 1), 8, 15, '[{"t":"戻","r":"もど"},{"t":"りつしている"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-1', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 0, '行き', 'いき', (select id from words where primary_form = '行き' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"行","r":"い"},{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 1, 'つ', 'つ', NULL, 2, 3, '[{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 2, '戻りつ', 'もどりつ', (select id from words where primary_form = '戻る' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"戻","r":"もど"},{"t":"りつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 3, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 4, '答え', 'こたえ', (select id from words where primary_form = '答え' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"答","r":"こた"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 5, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 6, '考えた', 'かんがえた', (select id from words where primary_form = '考える' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"考","r":"かんが"},{"t":"えた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-2', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-3', 0, '持ちつ', 'もちつ', (select id from words where primary_form = '持つ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"持","r":"も"},{"t":"ちつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-3', 1, '持たれつの', 'もたれつの', (select id from words where primary_form = '持つ' and language_id = 'lang-ja' and published order by id limit 1), 3, 8, '[{"t":"持","r":"も"},{"t":"たれつの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-3', 2, '関係', 'かんけい', (select id from words where primary_form = '関係' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"関係","r":"かんけい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-3', 3, 'だ', 'だ', NULL, 10, 11, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-3', 4, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-4', 0, '人', 'ひと', (select id from words where primary_form = '人' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"人","r":"ひと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-4', 2, '持ちつ', 'もちつ', (select id from words where primary_form = '持つ' and language_id = 'lang-ja' and published order by id limit 1), 2, 5, '[{"t":"持","r":"も"},{"t":"ちつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-4', 3, '持たれつで', 'もたれつで', (select id from words where primary_form = '持つ' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"持","r":"も"},{"t":"たれつで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-4', 4, '生きて', 'いきて', (select id from words where primary_form = '生きる' and language_id = 'lang-ja' and published order by id limit 1), 10, 13, '[{"t":"生","r":"い"},{"t":"きて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-4', 5, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tsutsutsu-4', 6, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-1', 0, '休む', 'やすむ', (select id from words where primary_form = '休む' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"休","r":"やす"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-1', 1, 'ことなく', 'ことなく', NULL, 2, 6, '[{"t":"ことなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-1', 2, '働いた', 'はたらいた', (select id from words where primary_form = '働く' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"働","r":"はたら"},{"t":"いた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-1', 3, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-2', 0, '諦める', 'あきらめる', (select id from words where primary_form = '諦める' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"諦","r":"あきら"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-2', 1, 'ことなく', 'ことなく', NULL, 3, 7, '[{"t":"ことなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-2', 2, '続けた', 'つづけた', (select id from words where primary_form = '続ける' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"続","r":"つづ"},{"t":"けた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-2', 3, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 0, '変わる', 'かわる', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"変","r":"か"},{"t":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 1, 'ことなく', 'ことなく', NULL, 3, 7, '[{"t":"ことなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 3, '昔', 'むかし', (select id from words where primary_form = '昔' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"昔","r":"むかし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 4, 'の', 'の', NULL, 9, 10, '[{"t":"の"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 5, 'まま', 'まま', NULL, 10, 12, '[{"t":"まま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 6, 'だ', 'だ', NULL, 12, 13, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-3', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-4', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-4', 2, '迷う', 'まよう', (select id from words where primary_form = '迷う' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"迷","r":"まよ"},{"t":"う"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-4', 3, 'ことなく', 'ことなく', NULL, 4, 8, '[{"t":"ことなく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-4', 4, '決めた', 'きめた', (select id from words where primary_form = '決める' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"決","r":"き"},{"t":"めた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-kotonaku-4', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb);
