-- N1 example sentences, batch 5: the last eleven writable topics.
--
-- 〜において, 〜を通じて, 〜ゆえに and 〜がゆえに (the plain cause and the
-- emphatic one, written next to each other), 〜とて, 〜よりほかない,
-- どうにも〜ない, 〜にしろ〜にしろ, 〜ひとつで, 〜始末だ and 〜たところで.
--
-- Three rewordings:
--
--   一年を通じて warned on 一|年 — two single kanji the index does not hold as
--   a compound, the same shape N3 batch 1 hit on 十年. The sentence is about
--   television and the world instead.
--
--   止められない shredded to 止め|ら|れ|ない, a potential negative one
--   inflection past what the index reaches; どうにもならない says the same
--   thing and cuts clean.
--
--   生きてきた lost き|た — 〜てくる in the past has no entry — so it is
--   生きている.
--
-- After this seed, four N1 topics remain uncovered, all recorded in seeds 129
-- and 133: 〜を余儀なくされる (余儀 splits to 余|儀), 〜ところを and
-- 〜うが〜まいが (the pattern ends in a particle, which check:examples reads
-- as a swallowed one), and 〜まい (shreds to ま|い everywhere). Each needs a
-- lexicon entry rather than a different sentence. 51 of 55.
--
-- Additive, idempotent, safe on a live database.

INSERT INTO sentences (id, language_id, text, reading_kana, level_id, source, published) VALUES
  -- ni-oite
  ('sent-ex-nioite-1', 'lang-ja', '会議は大学において行われた。', 'かいぎ わ だいがく に おいて おこなわれた。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nioite-2', 'lang-ja', '日本において、教育は重要だ。', 'にほん に おいて、きょういく わ じゅうよう だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nioite-3', 'lang-ja', 'あの分野において、彼は有名だ。', 'あの ぶんや に おいて、かれ わ ゆうめい だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nioite-4', 'lang-ja', '現代社会において、情報は大切だ。', 'げんだい しゃかい に おいて、じょうほう わ たいせつ だ。', 'lvl-ja-n1', 'authored', true),
  -- wo-tsuujite
  ('sent-ex-wotsuujite-1', 'lang-ja', '友人を通じて彼を知った。', 'ゆうじん お つうじて かれ お しった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-wotsuujite-2', 'lang-ja', 'テレビを通じて世界を知る。', 'テレビ お つうじて せかい お しる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-wotsuujite-3', 'lang-ja', '新聞を通じて情報を集める。', 'しんぶん お つうじて じょうほう お あつめる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-wotsuujite-4', 'lang-ja', '経験を通じて学んだ。', 'けいけん お つうじて まなんだ。', 'lvl-ja-n1', 'authored', true),
  -- yue-ni
  ('sent-ex-yueni-1', 'lang-ja', '若いゆえに失敗した。', 'わかい ゆえ に しっぱい した。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yueni-2', 'lang-ja', '貧しいゆえに学校へ行けなかった。', 'まずしい ゆえ に がっこう え いけなかった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yueni-3', 'lang-ja', '経験がないゆえに、迷った。', 'けいけん が ない ゆえ に、まよった。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yueni-4', 'lang-ja', '病気ゆえに、仕事を辞めた。', 'びょうき ゆえ に、しごと お やめた。', 'lvl-ja-n1', 'authored', true),
  -- tote
  ('sent-ex-tote-1', 'lang-ja', '子供とて許されない。', 'こども とて ゆるされない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tote-2', 'lang-ja', '私とて同じ気持ちだ。', 'わたし とて おなじ きもち だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tote-3', 'lang-ja', '先生とて間違いはある。', 'せんせい とて まちがい わ ある。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tote-4', 'lang-ja', '今からとて遅くはない。', 'いま から とて おそく わ ない。', 'lvl-ja-n1', 'authored', true),
  -- yori-hoka-nai
  ('sent-ex-yorihokanai-1', 'lang-ja', '諦めるよりほかない。', 'あきらめる より ほか ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yorihokanai-2', 'lang-ja', '自分でやるよりほかない。', 'じぶん で やる より ほか ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yorihokanai-3', 'lang-ja', '待つよりほかない。', 'まつ より ほか ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-yorihokanai-4', 'lang-ja', '彼に頼むよりほかない。', 'かれ に たのむ より ほか ない。', 'lvl-ja-n1', 'authored', true),
  -- dou-ni-mo
  ('sent-ex-dounimo-1', 'lang-ja', 'どうにも我慢できない。', 'どうにも がまん できない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-dounimo-2', 'lang-ja', 'どうにも眠れない。', 'どうにも ねむれない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-dounimo-3', 'lang-ja', 'どうにも分からない。', 'どうにも わからない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-dounimo-4', 'lang-ja', 'どうにもならない。', 'どうにも ならない。', 'lvl-ja-n1', 'authored', true),
  -- ni-shiro
  ('sent-ex-nishiro-1', 'lang-ja', '行くにしろ行かないにしろ、連絡してください。', 'いく に しろ いかない に しろ、れんらく して ください。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nishiro-2', 'lang-ja', '雨にしろ雪にしろ、試合はあります。', 'あめ に しろ ゆき に しろ、しあい わ あります。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nishiro-3', 'lang-ja', '学生にしろ先生にしろ、規則は同じだ。', 'がくせい に しろ せんせい に しろ、きそく わ おなじ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-nishiro-4', 'lang-ja', '賛成するにしろ反対するにしろ、意見を言ってください。', 'さんせい する に しろ はんたい する に しろ、いけん お いって ください。', 'lvl-ja-n1', 'authored', true),
  -- hitotsu-de
  ('sent-ex-hitotsude-1', 'lang-ja', '考えひとつで人生は変わる。', 'かんがえ ひとつ で じんせい わ かわる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-hitotsude-2', 'lang-ja', '一言ひとつで印象が変わる。', 'ひとこと ひとつ で いんしょう が かわる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-hitotsude-3', 'lang-ja', '彼は腕ひとつで生きている。', 'かれ わ うで ひとつ で いきて いる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-hitotsude-4', 'lang-ja', '気持ちひとつで結果は変わります。', 'きもち ひとつ で けっか わ かわります。', 'lvl-ja-n1', 'authored', true),
  -- ga-yue-ni
  ('sent-ex-gayueni-1', 'lang-ja', '若いがゆえに、失敗も多い。', 'わかい が ゆえ に、しっぱい も おおい。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gayueni-2', 'lang-ja', '有名であるがゆえに、自由がない。', 'ゆうめい で ある が ゆえ に、じゆう が ない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gayueni-3', 'lang-ja', '真面目であるがゆえに、疲れる。', 'まじめ で ある が ゆえ に、つかれる。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-gayueni-4', 'lang-ja', '経験がないがゆえに、失敗した。', 'けいけん が ない が ゆえ に、しっぱい した。', 'lvl-ja-n1', 'authored', true),
  -- shimatsu-da
  ('sent-ex-shimatsuda-1', 'lang-ja', '遅れた上に、謝らない始末だ。', 'おくれた うえ に、あやまらない しまつ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-shimatsuda-2', 'lang-ja', '最後には泣く始末だ。', 'さいご に わ なく しまつ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-shimatsuda-3', 'lang-ja', '注意しても聞かない始末だ。', 'ちゅうい して も きかない しまつ だ。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-shimatsuda-4', 'lang-ja', '約束まで忘れる始末だ。', 'やくそく まで わすれる しまつ だ。', 'lvl-ja-n1', 'authored', true),
  -- ta-tokoro-de
  ('sent-ex-tatokorode-1', 'lang-ja', '急いだところで、間に合わない。', 'いそいだ ところ で、まにあわない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tatokorode-2', 'lang-ja', '謝ったところで、許されない。', 'あやまった ところ で、ゆるされない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tatokorode-3', 'lang-ja', '言ったところで、変わらない。', 'いった ところ で、かわらない。', 'lvl-ja-n1', 'authored', true),
  ('sent-ex-tatokorode-4', 'lang-ja', '勉強したところで、合格しないだろう。', 'べんきょう した ところ で、ごうかく しない だろう。', 'lvl-ja-n1', 'authored', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentence_translations (id, sentence_id, lang, text, source) VALUES
  ('st-ex-nioite-1', 'sent-ex-nioite-1', 'en', 'The meeting was held at the university.', 'authored'),
  ('st-ex-nioite-2', 'sent-ex-nioite-2', 'en', 'In Japan, education matters.', 'authored'),
  ('st-ex-nioite-3', 'sent-ex-nioite-3', 'en', 'In that field, he is well known.', 'authored'),
  ('st-ex-nioite-4', 'sent-ex-nioite-4', 'en', 'In modern society, information matters.', 'authored'),
  ('st-ex-wotsuujite-1', 'sent-ex-wotsuujite-1', 'en', 'I came to know him through a friend.', 'authored'),
  ('st-ex-wotsuujite-2', 'sent-ex-wotsuujite-2', 'en', 'You get to know the world through television.', 'authored'),
  ('st-ex-wotsuujite-3', 'sent-ex-wotsuujite-3', 'en', 'I gather information through the newspapers.', 'authored'),
  ('st-ex-wotsuujite-4', 'sent-ex-wotsuujite-4', 'en', 'I learned it through experience.', 'authored'),
  ('st-ex-yueni-1', 'sent-ex-yueni-1', 'en', 'He failed because he was young.', 'authored'),
  ('st-ex-yueni-2', 'sent-ex-yueni-2', 'en', 'Because they were poor, he could not go to school.', 'authored'),
  ('st-ex-yueni-3', 'sent-ex-yueni-3', 'en', 'Having no experience, I hesitated.', 'authored'),
  ('st-ex-yueni-4', 'sent-ex-yueni-4', 'en', 'Because of illness, he left his job.', 'authored'),
  ('st-ex-tote-1', 'sent-ex-tote-1', 'en', 'Even a child is not excused.', 'authored'),
  ('st-ex-tote-2', 'sent-ex-tote-2', 'en', 'I feel exactly the same way.', 'authored'),
  ('st-ex-tote-3', 'sent-ex-tote-3', 'en', 'Even a teacher makes mistakes.', 'authored'),
  ('st-ex-tote-4', 'sent-ex-tote-4', 'en', 'It is not too late even now.', 'authored'),
  ('st-ex-yorihokanai-1', 'sent-ex-yorihokanai-1', 'en', 'There is nothing for it but to give up.', 'authored'),
  ('st-ex-yorihokanai-2', 'sent-ex-yorihokanai-2', 'en', 'There is nothing for it but to do it myself.', 'authored'),
  ('st-ex-yorihokanai-3', 'sent-ex-yorihokanai-3', 'en', 'There is nothing for it but to wait.', 'authored'),
  ('st-ex-yorihokanai-4', 'sent-ex-yorihokanai-4', 'en', 'There is nothing for it but to ask him.', 'authored'),
  ('st-ex-dounimo-1', 'sent-ex-dounimo-1', 'en', 'I simply cannot stand it.', 'authored'),
  ('st-ex-dounimo-2', 'sent-ex-dounimo-2', 'en', 'I simply cannot get to sleep.', 'authored'),
  ('st-ex-dounimo-3', 'sent-ex-dounimo-3', 'en', 'I simply cannot make it out.', 'authored'),
  ('st-ex-dounimo-4', 'sent-ex-dounimo-4', 'en', 'There is nothing to be done about it.', 'authored'),
  ('st-ex-nishiro-1', 'sent-ex-nishiro-1', 'en', 'Whether you are going or not, please let me know.', 'authored'),
  ('st-ex-nishiro-2', 'sent-ex-nishiro-2', 'en', 'Rain or snow, the match is on.', 'authored'),
  ('st-ex-nishiro-3', 'sent-ex-nishiro-3', 'en', 'Student or teacher, the rules are the same.', 'authored'),
  ('st-ex-nishiro-4', 'sent-ex-nishiro-4', 'en', 'Whether you agree or object, say what you think.', 'authored'),
  ('st-ex-hitotsude-1', 'sent-ex-hitotsude-1', 'en', 'A single thought can change a life.', 'authored'),
  ('st-ex-hitotsude-2', 'sent-ex-hitotsude-2', 'en', 'A single word changes the impression.', 'authored'),
  ('st-ex-hitotsude-3', 'sent-ex-hitotsude-3', 'en', 'He has lived on his own two hands.', 'authored'),
  ('st-ex-hitotsude-4', 'sent-ex-hitotsude-4', 'en', 'A change of heart changes the result.', 'authored'),
  ('st-ex-gayueni-1', 'sent-ex-gayueni-1', 'en', 'Being young, he makes plenty of mistakes.', 'authored'),
  ('st-ex-gayueni-2', 'sent-ex-gayueni-2', 'en', 'Precisely because he is famous, he has no freedom.', 'authored'),
  ('st-ex-gayueni-3', 'sent-ex-gayueni-3', 'en', 'It is precisely because he is so conscientious that he is worn out.', 'authored'),
  ('st-ex-gayueni-4', 'sent-ex-gayueni-4', 'en', 'It was precisely for want of experience that it went wrong.', 'authored'),
  ('st-ex-shimatsuda-1', 'sent-ex-shimatsuda-1', 'en', 'Not only was he late, he did not even apologise.', 'authored'),
  ('st-ex-shimatsuda-2', 'sent-ex-shimatsuda-2', 'en', 'In the end he was reduced to tears.', 'authored'),
  ('st-ex-shimatsuda-3', 'sent-ex-shimatsuda-3', 'en', 'He was warned and still would not listen.', 'authored'),
  ('st-ex-shimatsuda-4', 'sent-ex-shimatsuda-4', 'en', 'He has got to the point of forgetting his promises.', 'authored'),
  ('st-ex-tatokorode-1', 'sent-ex-tatokorode-1', 'en', 'Hurrying will not get me there in time.', 'authored'),
  ('st-ex-tatokorode-2', 'sent-ex-tatokorode-2', 'en', 'Apologising will not get me forgiven.', 'authored'),
  ('st-ex-tatokorode-3', 'sent-ex-tatokorode-3', 'en', 'Saying it will change nothing.', 'authored'),
  ('st-ex-tatokorode-4', 'sent-ex-tatokorode-4', 'en', 'Even if I studied, I would probably not pass.', 'authored')
ON CONFLICT (id) DO NOTHING;

INSERT INTO grammar_point_sentences (grammar_point_id, sentence_id, role, sort_index)
SELECT g.id, s.id, 'example', s.n
FROM (VALUES
  ('ni-oite', 'sent-ex-nioite-1', 0),
  ('ni-oite', 'sent-ex-nioite-2', 1),
  ('ni-oite', 'sent-ex-nioite-3', 2),
  ('ni-oite', 'sent-ex-nioite-4', 3),
  ('wo-tsuujite', 'sent-ex-wotsuujite-1', 0),
  ('wo-tsuujite', 'sent-ex-wotsuujite-2', 1),
  ('wo-tsuujite', 'sent-ex-wotsuujite-3', 2),
  ('wo-tsuujite', 'sent-ex-wotsuujite-4', 3),
  ('yue-ni', 'sent-ex-yueni-1', 0),
  ('yue-ni', 'sent-ex-yueni-2', 1),
  ('yue-ni', 'sent-ex-yueni-3', 2),
  ('yue-ni', 'sent-ex-yueni-4', 3),
  ('tote', 'sent-ex-tote-1', 0),
  ('tote', 'sent-ex-tote-2', 1),
  ('tote', 'sent-ex-tote-3', 2),
  ('tote', 'sent-ex-tote-4', 3),
  ('yori-hoka-nai', 'sent-ex-yorihokanai-1', 0),
  ('yori-hoka-nai', 'sent-ex-yorihokanai-2', 1),
  ('yori-hoka-nai', 'sent-ex-yorihokanai-3', 2),
  ('yori-hoka-nai', 'sent-ex-yorihokanai-4', 3),
  ('dou-ni-mo', 'sent-ex-dounimo-1', 0),
  ('dou-ni-mo', 'sent-ex-dounimo-2', 1),
  ('dou-ni-mo', 'sent-ex-dounimo-3', 2),
  ('dou-ni-mo', 'sent-ex-dounimo-4', 3),
  ('ni-shiro', 'sent-ex-nishiro-1', 0),
  ('ni-shiro', 'sent-ex-nishiro-2', 1),
  ('ni-shiro', 'sent-ex-nishiro-3', 2),
  ('ni-shiro', 'sent-ex-nishiro-4', 3),
  ('hitotsu-de', 'sent-ex-hitotsude-1', 0),
  ('hitotsu-de', 'sent-ex-hitotsude-2', 1),
  ('hitotsu-de', 'sent-ex-hitotsude-3', 2),
  ('hitotsu-de', 'sent-ex-hitotsude-4', 3),
  ('ga-yue-ni', 'sent-ex-gayueni-1', 0),
  ('ga-yue-ni', 'sent-ex-gayueni-2', 1),
  ('ga-yue-ni', 'sent-ex-gayueni-3', 2),
  ('ga-yue-ni', 'sent-ex-gayueni-4', 3),
  ('shimatsu-da', 'sent-ex-shimatsuda-1', 0),
  ('shimatsu-da', 'sent-ex-shimatsuda-2', 1),
  ('shimatsu-da', 'sent-ex-shimatsuda-3', 2),
  ('shimatsu-da', 'sent-ex-shimatsuda-4', 3),
  ('ta-tokoro-de', 'sent-ex-tatokorode-1', 0),
  ('ta-tokoro-de', 'sent-ex-tatokorode-2', 1),
  ('ta-tokoro-de', 'sent-ex-tatokorode-3', 2),
  ('ta-tokoro-de', 'sent-ex-tatokorode-4', 3)
) AS s(slug, id, n)
JOIN grammar_points g ON g.language_id = 'lang-ja' AND g.slug = s.slug
ON CONFLICT (grammar_point_id, sentence_id, role) DO NOTHING;

-- The tokens. `tokenise:authored` is a dev script and production runs only
-- migrations and seeds; the quiz derivation cuts its chips from these rows.
DELETE FROM sentence_tokens WHERE sentence_id IN ('sent-ex-nioite-1', 'sent-ex-nioite-2', 'sent-ex-nioite-3', 'sent-ex-nioite-4', 'sent-ex-wotsuujite-1', 'sent-ex-wotsuujite-2', 'sent-ex-wotsuujite-3', 'sent-ex-wotsuujite-4', 'sent-ex-yueni-1', 'sent-ex-yueni-2', 'sent-ex-yueni-3', 'sent-ex-yueni-4', 'sent-ex-tote-1', 'sent-ex-tote-2', 'sent-ex-tote-3', 'sent-ex-tote-4', 'sent-ex-yorihokanai-1', 'sent-ex-yorihokanai-2', 'sent-ex-yorihokanai-3', 'sent-ex-yorihokanai-4', 'sent-ex-dounimo-1', 'sent-ex-dounimo-2', 'sent-ex-dounimo-3', 'sent-ex-dounimo-4', 'sent-ex-nishiro-1', 'sent-ex-nishiro-2', 'sent-ex-nishiro-3', 'sent-ex-nishiro-4', 'sent-ex-hitotsude-1', 'sent-ex-hitotsude-2', 'sent-ex-hitotsude-3', 'sent-ex-hitotsude-4', 'sent-ex-gayueni-1', 'sent-ex-gayueni-2', 'sent-ex-gayueni-3', 'sent-ex-gayueni-4', 'sent-ex-shimatsuda-1', 'sent-ex-shimatsuda-2', 'sent-ex-shimatsuda-3', 'sent-ex-shimatsuda-4', 'sent-ex-tatokorode-1', 'sent-ex-tatokorode-2', 'sent-ex-tatokorode-3', 'sent-ex-tatokorode-4');
INSERT INTO sentence_tokens (id, sentence_id, index, surface, reading, word_id, char_start, char_end, furigana) VALUES
  (gen_random_uuid()::text, 'sent-ex-nioite-1', 0, '会議', 'かいぎ', (select id from words where primary_form = '会議' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"会議","r":"かいぎ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-1', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-1', 2, '大学', 'だいがく', (select id from words where primary_form = '大学' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"大学","r":"だいがく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-1', 3, 'において', 'において', NULL, 5, 9, '[{"t":"において"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-1', 4, '行われた', 'おこなわれた', (select id from words where primary_form = '行う' and language_id = 'lang-ja' and published order by id limit 1), 9, 13, '[{"t":"行","r":"おこな"},{"t":"われた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-1', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 0, '日本', 'にほん', (select id from words where primary_form = '日本' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"日本","r":"にほん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 1, 'において', 'において', NULL, 2, 6, '[{"t":"において"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 3, '教育', 'きょういく', (select id from words where primary_form = '教育' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"教育","r":"きょういく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 5, '重要', 'じゅうよう', (select id from words where primary_form = '重要' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"重要","r":"じゅうよう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 6, 'だ', 'だ', NULL, 12, 13, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-2', 7, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 0, 'あの', 'あの', (select id from words where primary_form = 'あの' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"あの"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 1, '分野', 'ぶんや', (select id from words where primary_form = '分野' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"分野","r":"ぶんや"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 2, 'において', 'において', NULL, 4, 8, '[{"t":"において"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 4, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 5, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 10, 11, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 6, '有名', 'ゆうめい', (select id from words where primary_form = '有名' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"有名","r":"ゆうめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 7, 'だ', 'だ', NULL, 13, 14, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-3', 8, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 0, '現代', 'げんだい', (select id from words where primary_form = '現代' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"現代","r":"げんだい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 1, '社会', 'しゃかい', (select id from words where primary_form = '社会' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"社会","r":"しゃかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 2, 'において', 'において', NULL, 4, 8, '[{"t":"において"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 3, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 4, '情報', 'じょうほう', (select id from words where primary_form = '情報' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"情報","r":"じょうほう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 5, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 6, '大切', 'たいせつ', (select id from words where primary_form = '大切' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"大切","r":"たいせつ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 7, 'だ', 'だ', NULL, 14, 15, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nioite-4', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-1', 0, '友人', 'ゆうじん', (select id from words where primary_form = '友人' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"友人","r":"ゆうじん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-1', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-1', 2, '通じて', 'つうじて', (select id from words where primary_form = '通じる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"通","r":"つう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-1', 3, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-1', 4, 'を', 'を', NULL, 7, 8, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-1', 5, '知った', 'しった', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 8, 11, '[{"t":"知","r":"し"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-1', 6, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-2', 0, 'テレビ', 'テレビ', (select id from words where primary_form = 'テレビ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"テレビ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-2', 1, 'を', 'を', NULL, 3, 4, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-2', 2, '通じて', 'つうじて', (select id from words where primary_form = '通じる' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"通","r":"つう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-2', 3, '世界', 'せかい', (select id from words where primary_form = '世界' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"世界","r":"せかい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-2', 4, 'を', 'を', NULL, 9, 10, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-2', 5, '知る', 'しる', (select id from words where primary_form = '知る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"知","r":"し"},{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-2', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-3', 0, '新聞', 'しんぶん', (select id from words where primary_form = '新聞' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"新聞","r":"しんぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-3', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-3', 2, '通じて', 'つうじて', (select id from words where primary_form = '通じる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"通","r":"つう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-3', 3, '情報', 'じょうほう', (select id from words where primary_form = '情報' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"情報","r":"じょうほう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-3', 4, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-3', 5, '集める', 'あつめる', (select id from words where primary_form = '集める' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"集","r":"あつ"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-4', 0, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-4', 1, 'を', 'を', NULL, 2, 3, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-4', 2, '通じて', 'つうじて', (select id from words where primary_form = '通じる' and language_id = 'lang-ja' and published order by id limit 1), 3, 6, '[{"t":"通","r":"つう"},{"t":"じて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-4', 3, '学んだ', 'まなんだ', (select id from words where primary_form = '学ぶ' and language_id = 'lang-ja' and published order by id limit 1), 6, 9, '[{"t":"学","r":"まな"},{"t":"んだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-wotsuujite-4', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-1', 0, '若い', 'わかい', (select id from words where primary_form = '若い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"若","r":"わか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-1', 1, 'ゆえ', 'ゆえ', (select id from words where primary_form = '故' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"ゆえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-1', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-1', 3, '失敗した', 'しっぱいした', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"失敗","r":"しっぱい"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 0, '貧しい', 'まずしい', (select id from words where primary_form = '貧しい' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"貧","r":"まず"},{"t":"しい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 1, 'ゆえ', 'ゆえ', (select id from words where primary_form = '故' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ゆえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 3, '学校', 'がっこう', (select id from words where primary_form = '学校' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"学校","r":"がっこう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 4, 'へ', 'へ', NULL, 8, 9, '[{"t":"へ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 5, '行け', 'いけ', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"行","r":"い"},{"t":"け"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 6, 'なかった', 'なかった', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 11, 15, '[{"t":"なかった"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-2', 7, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 0, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 2, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 3, 'ゆえ', 'ゆえ', (select id from words where primary_form = '故' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"ゆえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 5, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 6, '迷った', 'まよった', (select id from words where primary_form = '迷う' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"迷","r":"まよ"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-3', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 0, '病気', 'びょうき', (select id from words where primary_form = '病気' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"病気","r":"びょうき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 1, 'ゆえ', 'ゆえ', (select id from words where primary_form = '故' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"ゆえ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 2, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 3, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 4, '仕事', 'しごと', (select id from words where primary_form = '仕事' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"仕事","r":"しごと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 5, 'を', 'を', NULL, 8, 9, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 6, '辞めた', 'やめた', (select id from words where primary_form = '辞める' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"辞","r":"や"},{"t":"めた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yueni-4', 7, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-1', 0, '子供', 'こども', (select id from words where primary_form = '子供' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"子供","r":"こども"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-1', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-1', 2, 'て', 'て', NULL, 3, 4, '[{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-1', 3, '許されない', 'ゆるされない', (select id from words where primary_form = '許す' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"許","r":"ゆる"},{"t":"されない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-1', 4, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-2', 0, '私', 'わたし', (select id from words where primary_form = '私' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"私","r":"わたし"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-2', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-2', 2, 'て', 'て', NULL, 2, 3, '[{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-2', 3, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-2', 4, '気持ち', 'きもち', (select id from words where primary_form = '気持ち' and language_id = 'lang-ja' and published order by id limit 1), 5, 8, '[{"t":"気持","r":"きも"},{"t":"ち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-2', 5, 'だ', 'だ', NULL, 8, 9, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-2', 6, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-3', 0, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-3', 1, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-3', 2, 'て', 'て', NULL, 3, 4, '[{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-3', 3, '間違い', 'まちがい', (select id from words where primary_form = '間違い' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"間違","r":"まちが"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-3', 4, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-3', 5, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-3', 6, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-4', 0, '今', 'いま', (select id from words where primary_form = '今' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"今","r":"いま"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-4', 1, 'から', 'から', (select id from words where primary_form = 'から' and language_id = 'lang-ja' and published order by id limit 1), 1, 3, '[{"t":"から"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-4', 2, 'と', 'と', (select id from words where primary_form = 'と' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"と"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-4', 3, 'て', 'て', NULL, 4, 5, '[{"t":"て"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-4', 4, '遅くはない', 'おそくはない', (select id from words where primary_form = '遅くとも' and language_id = 'lang-ja' and published order by id limit 1), 5, 10, '[{"t":"遅","r":"おそ"},{"t":"くはない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tote-4', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-1', 0, '諦める', 'あきらめる', (select id from words where primary_form = '諦める' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"諦","r":"あきら"},{"t":"める"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-1', 1, 'よりほかない', 'よりほかない', NULL, 3, 9, '[{"t":"よりほかない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-1', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-2', 0, '自分', 'じぶん', (select id from words where primary_form = '自分' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"自分","r":"じぶん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-2', 2, 'や', 'や', (select id from words where primary_form = 'や' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"や"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-2', 3, 'る', 'る', NULL, 4, 5, '[{"t":"る"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-2', 4, 'よりほかない', 'よりほかない', NULL, 5, 11, '[{"t":"よりほかない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-2', 5, '。', '。', NULL, 11, 12, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-3', 0, '待つ', 'まつ', (select id from words where primary_form = '待つ' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"待","r":"ま"},{"t":"つ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-3', 1, 'よりほかない', 'よりほかない', NULL, 2, 8, '[{"t":"よりほかない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-3', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-4', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-4', 2, '頼む', 'たのむ', (select id from words where primary_form = '頼む' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"頼","r":"たの"},{"t":"む"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-4', 3, 'よりほかない', 'よりほかない', NULL, 4, 10, '[{"t":"よりほかない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-yorihokanai-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-1', 0, 'どうにも', 'どうにも', NULL, 0, 4, '[{"t":"どうにも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-1', 1, '我慢', 'がまん', (select id from words where primary_form = '我慢' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"我慢","r":"がまん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-1', 2, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 6, 7, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-1', 3, 'き', 'き', NULL, 7, 8, '[{"t":"き"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-1', 4, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-1', 5, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-2', 0, 'どうにも', 'どうにも', NULL, 0, 4, '[{"t":"どうにも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-2', 1, '眠れ', 'ねむれ', (select id from words where primary_form = '眠る' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"眠","r":"ねむ"},{"t":"れ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-2', 2, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-2', 3, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-3', 0, 'どうにも', 'どうにも', NULL, 0, 4, '[{"t":"どうにも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-3', 1, '分からない', 'わからない', (select id from words where primary_form = '分かる' and language_id = 'lang-ja' and published order by id limit 1), 4, 9, '[{"t":"分","r":"わ"},{"t":"からない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-3', 2, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-4', 0, 'どうにも', 'どうにも', NULL, 0, 4, '[{"t":"どうにも"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-4', 1, 'ならない', 'ならない', (select id from words where primary_form = '成る' and language_id = 'lang-ja' and published order by id limit 1), 4, 8, '[{"t":"ならない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-dounimo-4', 2, '。', '。', NULL, 8, 9, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 0, '行く', 'いく', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"行","r":"い"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 2, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 3, '行かない', 'いかない', (select id from words where primary_form = '行く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"行","r":"い"},{"t":"かない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 5, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 6, '、', '、', NULL, 12, 13, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 7, '連絡して', 'れんらくして', (select id from words where primary_form = '連絡' and language_id = 'lang-ja' and published order by id limit 1), 13, 17, '[{"t":"連絡","r":"れんらく"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 8, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 17, 21, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-1', 9, '。', '。', NULL, 21, 22, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 0, '雨', 'あめ', (select id from words where primary_form = '雨' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"雨","r":"あめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 2, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 2, 4, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 3, '雪', 'ゆき', (select id from words where primary_form = '雪' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"雪","r":"ゆき"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 5, 6, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 5, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 6, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 7, '試合', 'しあい', (select id from words where primary_form = '試合' and language_id = 'lang-ja' and published order by id limit 1), 9, 11, '[{"t":"試合","r":"しあい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 8, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 9, 'あります', 'あります', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 12, 16, '[{"t":"あります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-2', 10, '。', '。', NULL, 16, 17, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 0, '学生', 'がくせい', (select id from words where primary_form = '学生' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"学生","r":"がくせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 2, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 3, '先生', 'せんせい', (select id from words where primary_form = '先生' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"先生","r":"せんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 7, 8, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 5, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 8, 10, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 6, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 7, '規則', 'きそく', (select id from words where primary_form = '規則' and language_id = 'lang-ja' and published order by id limit 1), 11, 13, '[{"t":"規則","r":"きそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 8, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 13, 14, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 9, '同じ', 'おなじ', (select id from words where primary_form = '同じ' and language_id = 'lang-ja' and published order by id limit 1), 14, 16, '[{"t":"同","r":"おな"},{"t":"じ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 10, 'だ', 'だ', NULL, 16, 17, '[{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-3', 11, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 0, '賛成する', 'さんせいする', (select id from words where primary_form = '賛成' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"賛成","r":"さんせい"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 4, 5, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 2, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 5, 7, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 3, '反対する', 'はんたいする', (select id from words where primary_form = '反対' and language_id = 'lang-ja' and published order by id limit 1), 7, 11, '[{"t":"反対","r":"はんたい"},{"t":"する"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 4, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 11, 12, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 5, 'しろ', 'しろ', (select id from words where primary_form = '為る' and language_id = 'lang-ja' and published order by id limit 1), 12, 14, '[{"t":"しろ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 6, '、', '、', NULL, 14, 15, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 7, '意見', 'いけん', (select id from words where primary_form = '意見' and language_id = 'lang-ja' and published order by id limit 1), 15, 17, '[{"t":"意見","r":"いけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 8, 'を', 'を', NULL, 17, 18, '[{"t":"を"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 9, '言って', 'いって', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 18, 21, '[{"t":"言","r":"い"},{"t":"って"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 10, 'ください', 'ください', (select id from words where primary_form = '下さい' and language_id = 'lang-ja' and published order by id limit 1), 21, 25, '[{"t":"ください"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-nishiro-4', 11, '。', '。', NULL, 25, 26, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-1', 0, '考え', 'かんがえ', (select id from words where primary_form = '考え' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"考","r":"かんが"},{"t":"え"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-1', 1, 'ひとつで', 'ひとつで', NULL, 2, 6, '[{"t":"ひとつで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-1', 2, '人生', 'じんせい', (select id from words where primary_form = '人生' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"人生","r":"じんせい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-1', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 8, 9, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-1', 4, '変わる', 'かわる', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"変","r":"か"},{"t":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-1', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-2', 0, '一言', 'ひとこと', (select id from words where primary_form = '一言' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"一言","r":"ひとこと"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-2', 1, 'ひとつで', 'ひとつで', NULL, 2, 6, '[{"t":"ひとつで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-2', 2, '印象', 'いんしょう', (select id from words where primary_form = '印象' and language_id = 'lang-ja' and published order by id limit 1), 6, 8, '[{"t":"印象","r":"いんしょう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-2', 3, 'が', 'が', NULL, 8, 9, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-2', 4, '変わる', 'かわる', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 9, 12, '[{"t":"変","r":"か"},{"t":"わる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-2', 5, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-3', 0, '彼', 'かれ', (select id from words where primary_form = '彼' and language_id = 'lang-ja' and published order by id limit 1), 0, 1, '[{"t":"彼","r":"かれ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-3', 1, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 1, 2, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-3', 2, '腕', 'うで', (select id from words where primary_form = '腕' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"腕","r":"うで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-3', 3, 'ひとつで', 'ひとつで', NULL, 3, 7, '[{"t":"ひとつで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-3', 4, '生きて', 'いきて', (select id from words where primary_form = '生きる' and language_id = 'lang-ja' and published order by id limit 1), 7, 10, '[{"t":"生","r":"い"},{"t":"きて"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-3', 5, 'いる', 'いる', (select id from words where primary_form = '要る' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"いる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-3', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-4', 0, '気持ち', 'きもち', (select id from words where primary_form = '気持ち' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"気持","r":"きも"},{"t":"ち"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-4', 1, 'ひとつで', 'ひとつで', NULL, 3, 7, '[{"t":"ひとつで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-4', 2, '結果', 'けっか', (select id from words where primary_form = '結果' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"結果","r":"けっか"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-4', 3, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 9, 10, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-4', 4, '変わります', 'かわります', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 10, 15, '[{"t":"変","r":"か"},{"t":"わります"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-hitotsude-4', 5, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-1', 0, '若い', 'わかい', (select id from words where primary_form = '若い' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"若","r":"わか"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-1', 1, 'がゆえに', 'がゆえに', NULL, 2, 6, '[{"t":"がゆえに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-1', 2, '、', '、', NULL, 6, 7, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-1', 3, '失敗', 'しっぱい', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 7, 9, '[{"t":"失敗","r":"しっぱい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-1', 4, 'も', 'も', NULL, 9, 10, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-1', 5, '多い', 'おおい', (select id from words where primary_form = '多い' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"多","r":"おお"},{"t":"い"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-1', 6, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 0, '有名', 'ゆうめい', (select id from words where primary_form = '有名' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"有名","r":"ゆうめい"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 2, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 3, 'がゆえに', 'がゆえに', NULL, 5, 9, '[{"t":"がゆえに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 5, '自由', 'じゆう', (select id from words where primary_form = '自由' and language_id = 'lang-ja' and published order by id limit 1), 10, 12, '[{"t":"自由","r":"じゆう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 6, 'が', 'が', NULL, 12, 13, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 7, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 13, 15, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-2', 8, '。', '。', NULL, 15, 16, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-3', 0, '真面目', 'まじめ', (select id from words where primary_form = '真面目' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"真面目","r":"まじめ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-3', 1, 'で', 'で', (select id from words where primary_form = 'で' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"で"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-3', 2, 'ある', 'ある', (select id from words where primary_form = '有る' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"ある"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-3', 3, 'がゆえに', 'がゆえに', NULL, 6, 10, '[{"t":"がゆえに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-3', 4, '、', '、', NULL, 10, 11, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-3', 5, '疲れる', 'つかれる', (select id from words where primary_form = '疲れる' and language_id = 'lang-ja' and published order by id limit 1), 11, 14, '[{"t":"疲","r":"つか"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-3', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-4', 0, '経験', 'けいけん', (select id from words where primary_form = '経験' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"経験","r":"けいけん"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-4', 1, 'が', 'が', NULL, 2, 3, '[{"t":"が"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-4', 2, 'ない', 'ない', (select id from words where primary_form = 'ない' and language_id = 'lang-ja' and published order by id limit 1), 3, 5, '[{"t":"ない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-4', 3, 'がゆえに', 'がゆえに', NULL, 5, 9, '[{"t":"がゆえに"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-4', 4, '、', '、', NULL, 9, 10, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-4', 5, '失敗した', 'しっぱいした', (select id from words where primary_form = '失敗' and language_id = 'lang-ja' and published order by id limit 1), 10, 14, '[{"t":"失敗","r":"しっぱい"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-gayueni-4', 6, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-1', 0, '遅れた', 'おくれた', (select id from words where primary_form = '遅れる' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"遅","r":"おく"},{"t":"れた"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-1', 1, '上に', 'うえに', NULL, 3, 5, '[{"t":"上","r":"うえ"},{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-1', 2, '、', '、', NULL, 5, 6, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-1', 3, '謝らない', 'あやまらない', (select id from words where primary_form = '謝る' and language_id = 'lang-ja' and published order by id limit 1), 6, 10, '[{"t":"謝","r":"あやま"},{"t":"らない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-1', 4, '始末だ', 'しまつだ', NULL, 10, 13, '[{"t":"始末","r":"しまつ"},{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-1', 5, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-2', 0, '最後', 'さいご', (select id from words where primary_form = '最後' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"最後","r":"さいご"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-2', 1, 'に', 'に', (select id from words where primary_form = 'に' and language_id = 'lang-ja' and published order by id limit 1), 2, 3, '[{"t":"に"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-2', 2, 'は', 'は', (select id from words where primary_form = 'は' and language_id = 'lang-ja' and published order by id limit 1), 3, 4, '[{"t":"は"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-2', 3, '泣く', 'なく', (select id from words where primary_form = '泣く' and language_id = 'lang-ja' and published order by id limit 1), 4, 6, '[{"t":"泣","r":"な"},{"t":"く"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-2', 4, '始末だ', 'しまつだ', NULL, 6, 9, '[{"t":"始末","r":"しまつ"},{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-2', 5, '。', '。', NULL, 9, 10, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-3', 0, '注意して', 'ちゅういして', (select id from words where primary_form = '注意' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"注意","r":"ちゅうい"},{"t":"して"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-3', 1, 'も', 'も', NULL, 4, 5, '[{"t":"も"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-3', 2, '聞かない', 'きかない', (select id from words where primary_form = '聞く' and language_id = 'lang-ja' and published order by id limit 1), 5, 9, '[{"t":"聞","r":"き"},{"t":"かない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-3', 3, '始末だ', 'しまつだ', NULL, 9, 12, '[{"t":"始末","r":"しまつ"},{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-3', 4, '。', '。', NULL, 12, 13, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-4', 0, '約束', 'やくそく', (select id from words where primary_form = '約束' and language_id = 'lang-ja' and published order by id limit 1), 0, 2, '[{"t":"約束","r":"やくそく"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-4', 1, 'まで', 'まで', NULL, 2, 4, '[{"t":"まで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-4', 2, '忘れる', 'わすれる', (select id from words where primary_form = '忘れる' and language_id = 'lang-ja' and published order by id limit 1), 4, 7, '[{"t":"忘","r":"わす"},{"t":"れる"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-4', 3, '始末だ', 'しまつだ', NULL, 7, 10, '[{"t":"始末","r":"しまつ"},{"t":"だ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-shimatsuda-4', 4, '。', '。', NULL, 10, 11, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-1', 0, '急いだ', 'いそいだ', (select id from words where primary_form = '急ぐ' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"急","r":"いそ"},{"t":"いだ"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-1', 1, 'ところで', 'ところで', NULL, 3, 7, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-1', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-1', 3, '間に合わない', 'まにあわない', (select id from words where primary_form = '間に合う' and language_id = 'lang-ja' and published order by id limit 1), 8, 14, '[{"t":"間","r":"ま"},{"t":"に"},{"t":"合","r":"あ"},{"t":"わない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-1', 4, '。', '。', NULL, 14, 15, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-2', 0, '謝った', 'あやまった', (select id from words where primary_form = '謝る' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"謝","r":"あやま"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-2', 1, 'ところで', 'ところで', NULL, 3, 7, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-2', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-2', 3, '許されない', 'ゆるされない', (select id from words where primary_form = '許す' and language_id = 'lang-ja' and published order by id limit 1), 8, 13, '[{"t":"許","r":"ゆる"},{"t":"されない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-2', 4, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-3', 0, '言った', 'いった', (select id from words where primary_form = '言う' and language_id = 'lang-ja' and published order by id limit 1), 0, 3, '[{"t":"言","r":"い"},{"t":"った"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-3', 1, 'ところで', 'ところで', NULL, 3, 7, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-3', 2, '、', '、', NULL, 7, 8, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-3', 3, '変わらない', 'かわらない', (select id from words where primary_form = '変わる' and language_id = 'lang-ja' and published order by id limit 1), 8, 13, '[{"t":"変","r":"か"},{"t":"わらない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-3', 4, '。', '。', NULL, 13, 14, '[{"t":"。"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-4', 0, '勉強した', 'べんきょうした', (select id from words where primary_form = '勉強' and language_id = 'lang-ja' and published order by id limit 1), 0, 4, '[{"t":"勉強","r":"べんきょう"},{"t":"した"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-4', 1, 'ところで', 'ところで', NULL, 4, 8, '[{"t":"ところで"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-4', 2, '、', '、', NULL, 8, 9, '[{"t":"、"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-4', 3, '合格しない', 'ごうかくしない', (select id from words where primary_form = '合格' and language_id = 'lang-ja' and published order by id limit 1), 9, 14, '[{"t":"合格","r":"ごうかく"},{"t":"しない"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-4', 4, 'だろう', 'だろう', NULL, 14, 17, '[{"t":"だろう"}]'::jsonb),
  (gen_random_uuid()::text, 'sent-ex-tatokorode-4', 5, '。', '。', NULL, 17, 18, '[{"t":"。"}]'::jsonb);
