/* eslint-disable no-console */
import { readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { listKeys } from './lib/bucket.js'

/**
 * Write the seed that attaches vocabulary illustrations to their cards.
 *
 * Production never runs a pipeline script, so `import:images` — which talks to
 * the database directly — is a local convenience only. What actually ships is a
 * seed, and this generates it.
 *
 * The list of ent_seqs has to be literal: it is the answer to "which drawings
 * exist", which lives in the bucket and cannot be derived in SQL. Everything
 * else IS derived — the URL is built from the ent_seq in the query, so moving
 * the bucket stays an env change rather than an edit to thousands of lines.
 *
 * A NEW numbered file every time, never an edit to the last one: `seed_history`
 * records seeds by filename with no content hash, so a seed that has already
 * run in production will never run again however much it changes. Emitting the
 * complete current list rather than only what is new is therefore deliberate —
 * re-attaching a drawing a card already has is a no-op, so a superset is safe
 * and cannot leave a gap if a batch is ever missed.
 *
 *   pnpm -C nihongo/backend seed:images
 */

const SEEDS = path.resolve(process.cwd(), 'src/db/seeds')

async function main() {
  const stored = await listKeys('images/vocab/')
  const entSeqs = [...stored.keys()]
    .map(key => Number.parseInt(path.basename(key, '.svg'), 10))
    .filter(n => Number.isFinite(n))
    .sort((a, b) => a - b)

  if (entSeqs.length === 0)
    throw new Error('No vocabulary illustrations in the bucket — nothing to seed.')

  const existing = (await readdir(SEEDS)).filter(f => f.endsWith('.sql')).sort()
  const last = existing.at(-1)
  const next = String(Number.parseInt(last?.slice(0, 3) ?? '0', 10) + 1).padStart(3, '0')
  const name = `${next}-vocab-illustrations.sql`

  // Twelve to a line: short enough to read in a diff, long enough that several
  // thousand ids do not become several thousand lines.
  const rows: string[] = []
  for (let i = 0; i < entSeqs.length; i += 12)
    rows.push(`    ${entSeqs.slice(i, i + 12).join(', ')}`)

  const sql = `-- Vocabulary illustrations: attach the hand-drawn SVG to every word that has one.
--
-- Generated by \`pnpm -C nihongo/backend seed:images\` from the bucket listing.
-- ${entSeqs.length} drawings exist under \`images/vocab/<ent_seq>.svg\`, keyed by JMdict
-- ent_seq exactly as the audio is.
--
-- The ent_seq list is literal because it cannot be derived in SQL: it is the
-- answer to "which drawings exist", which lives in the bucket. The URL is built
-- from the ent_seq below, so moving the bucket stays an env change.
--
-- \`assets\` is MERGED, not replaced: audio already lives in that column and
-- overwriting it would silence every card this touches.
--
-- Touches \`assets\` on vocabulary prompts and nothing else -- no accounts, no
-- srs_cards, no review logs. Safe on a live database, and safe to re-run: the
-- final predicate makes a second run a no-op.
UPDATE exercise_prompts p
SET assets = p.assets || jsonb_build_object('image', '/images/vocab/' || w.ent_seq || '.svg'),
    updated_at = now()
FROM study_item_facets f
JOIN study_items si ON si.id = f.study_item_id
JOIN words w ON w.id = si.word_id
WHERE p.facet_id = f.id
  AND w.ent_seq IN (
${rows.join(',\n')}
  )
  -- Only where it would actually change something.
  AND coalesce(p.assets ->> 'image', '') <> '/images/vocab/' || w.ent_seq || '.svg';
`

  await writeFile(path.join(SEEDS, name), sql)
  console.log(`Wrote ${name} — ${entSeqs.length} illustrations`)
}

main().catch((err) => {
  console.error('Seed generation failed:', err)
  process.exitCode = 1
})
